### ISSUE TITLE
Integrate the parameter passing guidance

### ISSUE THREAD

**Issue by hsutter** [isocpp/CppCoreGuidelines#1]
F.15 is an omnibus item that covers the guidance we want to pursue. There is overlap/redundancy with related material in F.20-25, and F.40. These need to be integrated.
The obvious options are "keep F.15 and remove others that are redundant" or "distribute F.15 material into the others." But I think a better option is: Keep F.15 and have just one item each on how to pass "in", "inout", and "out" parameters. I'll go with that if there's no objection.

**Comment by AndrewPardoe** [comment]
Consider tie(). Multiple value returns should return a tuple. Move tie() to an example as an alternative and mention the weakness wrt uninitialized variables.
