### ISSUE TITLE
C.128, heading for example could be improved

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1001]
I think the heading for the example in rule C.128 could be improved (see screenshot)

![c128_misleading_heading](https://user-images.githubusercontent.com/17589466/28501570-ccf76152-6fde-11e7-8bf8-8f70370be564.png)

**Comment by jwakely** [comment]
I can't help thinking it would have been easier to submit a pull request (maybe by editing the source and creating a pull request directly using the web UI) than to use MS Paint, save an image and then upload it.

I'll make this change.

**Comment by franzhollerer** [comment]
@jwakely Yes you are right. Will do so next time.
