### ISSUE TITLE
Inconsistent indenting of switch - case

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1002]
NL.17 gives the following example for switch - case:

```cpp
double foo(int x)
{
    // ...

    switch (x) {
        case 0:
            // ...
            break;
        case amazing:
            // ...
            break;
        default:
            // ...
            break;
    }

    // ...
    return some_value;
}

```

Actually, I personally prefer this over the classic K&R style. Anyway, as far as I have seen it is not used consistently throughout the guidelines. In some examples the *case* is intended another level in relation to the *switch* (as given in NL.17), while in others the classic K&R style without additional indenting is used.

### Example

I.30

```cpp
bool owned;
owner<istream*> inp;
switch (source) {
case std_in:        owned = false; inp = &cin;                       break;
case command_line:  owned = true;  inp = new istringstream{argv[2]}; break;
case file:          owned = true;  inp = new ifstream{argv[2]};      break;
}
istream& in = *inp
```

versus

F.3

```cpp
double simple_func(double val, int flag1, int flag2)
    // simple_func: takes a value and calculates the expected ASIC output,
    // given the two mode flags.
{
    // ...
    switch (flag2 / 10) {
        case 1: if (flag1 == -1) return finalize(intermediate, 1.171);
                break;
        case 2: return finalize(intermediate, 13.1);
        default: break;
    }
    return finalize(intermediate, 0.);
}
```

You may consider to rework the examples for consistent appearance within the Cpp Core Guidlines.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we prefer that the `case` be aligned with the `switch`. We'll fix up NL.17 now. If you like, could you please PR the remainder of the switches that you'd like to see fixed?
