### ISSUE TITLE
II.5  if(a || b) {…}

### ISSUE THREAD

**Issue by vladtepesch** [isocpp/CppCoreGuidelines#101]
A branch of the form if(a || b) {…} is treated as if(a){ if(b) {} else{…}}

should be

A branch of the form if(a || b) {…} is treated as if(a){..}else{ if(b) {..} }

**Comment by thatbrod** [comment]
Both work, but your suggestion requires copying/pasting.

**Comment by gdr-at-ms** [comment]
Which section is this rule really about?

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

**Comment by hsutter** [comment]
I cannot find the text in the guidelines. This seems to be a stale issue.
