### ISSUE TITLE
if (obj) : if statements and operator overloading

### ISSUE THREAD

**Issue by GuillaumeDua** [isocpp/CppCoreGuidelines#1010]
Maybe related to issue #1006 ,
I notice during my last training session that newcomers to C++ are quite confused about if statements and operator overloading.

Maybe the guideline could describe a best-practice for this purpose.

For instance (see https://godbolt.org/g/X4R3Pc for complete code) :
``` c++
struct object1
{
    inline operator bool() const noexcept;
};

struct object2
{
    inline operator bool() const noexcept;
    inline bool operator!() const noexcept;
};

void    use_objects()
{
    object1 obj1;
    if (!obj1)      // call operator bool(), then operator!(bool)
        /* deal with invalid object */ ;
    object2 obj2;
    if (!obj2)      // call object2::operator!()
       /* deal with invalid object */  ;
}
```

I also see students that define overload functions like :
``` cpp
bool object::operator!=(int i)
```
In order to write such synthax :
``` cpp
if (obj != 0)
   /* deal with invalid object */;
```

Also, many libraries use :
``` cpp
if (!!obj)
 ;
```

**Comment by MikeGitb** [comment]
Correct me if I'm wrong, the last one was used pre c++11 to use explicit operator bool in if statements correct? In that case the compiler/core guideline checker could just warn about it and recommend the removal of the `!!` (clang tidy could probably just directly remove it).

Detecting the pattern of writing operator!=(int) or operator! and using them in if statements instead is probably also possible, but it might be more difficult to provide a useful warning and avoid false positives.

**Comment by GuillaumeDua** [comment]
Indeed, to my knowledge it was use to force conversion to bool.
I guess a warning is fine if it suggests refactoring.

About the first code snippet, what do you think if the checker display a warning such like :
if (!obj2) -> operator! overload hides/shadows operator bool()

**Comment by BjarneStroustrup** [comment]
We prefer if (x), see ES.87
