### ISSUE TITLE
Special case for range based for loop.

### ISSUE THREAD

**Issue by jack17529** [isocpp/CppCoreGuidelines#1011]
In the guidelines in the example of range based for loop - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-3

I think that the special case of proxy iterators should too be mentioned 
As mentioned here  - https://stackoverflow.com/a/15927037/7740389

**Comment by MikeGitb** [comment]
How about recommending `auto&&` for all cases where the value is to be modified?

**Comment by AndrewPardoe** [comment]
Per our discussion, Bjarne would like to take a stab at this.

**Comment by cubbimew** [comment]
[ES.71 Prefer a range-for-statement to a for-statement when there is a choice](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-for-range) might be the better spot for a range-for detail than a philosophy guideline..

**Comment by BjarneStroustrup** [comment]
I added a reference to ES.71, but didn't yet add anything about &&
