### ISSUE TITLE
Use of file path in #include directive

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1021]
Can you please provide some advices on the use of a path components in the #incude directive.

Rational. The Microchip xc8 C compiler complains if it sees this:

```c
#include <utils/byteorder.h>
```

Instead Microchip encourage to use:

```c
#include <byteorder.h>
```

and pass the path to it as command line option. They claim that this is more portable. The first one injects the build/host's underlying filesystem vagaries into the semantics of the program.

Well that argument is true, but it is common practice to use a relative path in the #include directive. It helps to avoid name clashes.

Note: I remember that I have already seen somening about this topic in the FAQ section. Unfortunately I failed to look it up again. Maybe it has been removed.

Anyway, it would be helpful to have some advices on this topic in the guidlines.

**Comment by gdr-at-ms** [comment]
The existing practice is so widely varied that it is nearly impossible to provide a single recommendation without creating more confusion.
