### ISSUE TITLE
Want translate CPP Core Guidelines to Chinese.

### ISSUE THREAD

**Issue by sniper00** [isocpp/CppCoreGuidelines#1024]
Hello,I am from China. I like this book very much, and so do many Chinese CPP programmers. Can I translate this book into Chinese , help someone who is not good at English ?

**Comment by jwakely** [comment]
The licence is clear that you can create derivative works, under the terms of the licence:
https://github.com/isocpp/CppCoreGuidelines/blob/master/LICENSE
