### ISSUE TITLE
ES.106: Don't try to avoid negative values by using unsigned

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1029]
I have some troubles to figure out ES.106

> These problems with such (perfectly legal) constructs are hard to spot in real code and are the source of many real-world errors. Consider:
> 
> unsigned area(unsigned height, unsigned width) { return height*width; } // [see also](#Ri-expects)
> // ...
> int height;
> cin >> height;
> auto a = area(height, 2);   // if the input is -2 a becomes 4294967292
>
> Remember that -1 when assigned to an unsigned int becomes the largest unsigned int. Also, 
> since unsigned arithmetic is modulo arithmetic the multiplication didn't overflow, it wrapped around.

In real code INT_MAX will be to large too, thus someone has to check the input range anyway. At least the range of height and width must be limited in order that the result of the multiplications fits in the selected type.

Thus I have some troubles to figure out why:

```cpp
int area(int height, int width)
{
    assert((height > 0) && (height <= max_height));
    assert((width > 0) && (width <= max_width));
    return height*width;
}
```

is better than

```cpp
unsigned area(unsigned height, unsigned width)
{
    assert(height <= max_height); 
    assert(width <= max_width);
    return height*width;
}
```
What did I miss?

**Comment by jwakely** [comment]
It's not necessarily the case that you need the range checks. If you just use signed types then overflows can be detected by sanitizers, or compiler options like `-ftrapv`. If you use unsigned types the conversions to very large values are well-defined and can't be detected by sanitizers.

If `area(-2, 1);` returns `429496729 * 1` there is no overflow or other undefined behaviour that can be trapped. On the other hand, if the result of a call like `area(INT_MAX, INT_MAX)` doesn't fit in the relevant signed type and overflows then it can be detected by sanitizers.

**Comment by franzhollerer** [comment]
Thanks @jwakely. I understand.

**Comment by Enhex** [comment]
Wouldn't it be better to explicitly require passing unsigned values using traits or deleting signed overloads?
and for the return value using something like:
```C++
 static_assert(ULLONG_MAX > UINT_MAX * UINT_MAX);
 assert((unsigned long long)(height * width) <= UINT_MAX);
```
Instead of relying on sanitizers and undefined behavior?

**Comment by vitalybuka** [comment]
> (height * width)
potential signed integer overflow which is  undefined behavior

**Comment by Enhex** [comment]
Thanks, fixed my code to properly convert.

**Comment by vitalybuka** [comment]
or assert(height <= UINT_MAX / width);

**Comment by MikeGitb** [comment]
@Enhex: And what do you do when there is no bigger type? 

@vitalybuka's solution is the only one I know of that actually works in all cases. In general, checking all math operations in your code for overflow/underflow etc. is very tedious, error prone and will make the code much harder to read. Of course, you can use a numerics library that does all the checking for you, but I much prefer the compiler to take care of it if possible. 

Where a library solution has imho merit is, when it statically propagates range information as part of the type (I remember at least one such library, but it's name escapes me). And I think there was also some discussion about introducing e.g. a not-negative integral type into the gsl, similar to the not_null wrapper for pointers but I can't remember if that got any traction.

**Comment by gdr-at-ms** [comment]
Requiring passing unsigned values using traits is too complicated to recommend for most C++ programmers.  Regarding the `static_assert` suggestion, it would become a source of error if it is put into general use.
