### ISSUE TITLE
[implementation of 'is_owned'?] since 'owner' is just a template alias

### ISSUE THREAD

**Issue by krzysztof-jusiak** [isocpp/CppCoreGuidelines#103]
Although I do understand reasoning behind using template alias with the 'owner' (no semantic code changes and might be used by external tools), my concern is that it actually limits the availability to write a generic code using it. What I mean by that, is that it's not possible to distinguish it from not owning, raw, pointer.

Example:

    auto f(auto object) {
         static_assert(is_owned(object));
    }

    {
    T* ptr = nullptr;
    f(ptr); // is_owned=false
    }

    {
    owner<T*> ptr = nulltpr;
    f(ptr); // is_owned=true? // the same for smart pointers
    }

Question:
Is there any way to implement is_owned? since it's just an alias for raw pointer it seems not possible? Following question (if the previous answer is yes - it's not possible), any thoughts of making detection of is_owned possible in the future?

**Comment by AndrewPardoe** [comment]
C++ doesn't support that. That would require a change to the fundamental type system.
