### ISSUE TITLE
Q: How to express that something is accessed for its side effect in C++?

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1048]
This question is derived from the exception in MISRA C 2017, Rule 2.2.

> A cast to void is assumed to indicate a value that is intentionally not being used. The cast is therefore not dead code itself. It is treated as using its operand which is therefore also not dead code.

I would like to know how to do this in C++, as C-style cast are discouraged.

Example:

```c
extern volatile uint32_t* uart_rx_reg;

void foo()
{
    // do something here
    :
    // uart_rx_reg is accessed for its side effect to empty the receive register
    (void) *uart_rx_reg;    // read and discard received character
}
```
Is *static_cast* the right choice, or are there better ways to express this?

**Comment by MikeGitb** [comment]
There should be an attribute for this.

**Comment by franzhollerer** [comment]
> There should be an attribute for this.
Many thanks @MikeGitb for the quick response. Unfortunately, I did not get the point. Could you please provide an example.

**Comment by JonasToth** [comment]
I am not 100% sure, but maybe he means this:
http://en.cppreference.com/w/cpp/language/expressions#Discarded-value_expressions
http://en.cppreference.com/w/cpp/language/attributes see [[nodiscard]]

**Comment by arvidn** [comment]
@franzhollerer I take it the question really is about how to suppress warnings about unused variables. The fact that ``uart_rx_reg`` is volatile indicates that the read is an observable side effect.

If the remaining issue is just to suppress the warning, you may change the cast to a c++-style cast, like this:

```
static_cast<void*>(*uart_rx_reg);
```

**Comment by jwakely** [comment]
> I would like to know how to do this in C++, as C-style cast are discouraged.

`(void)expr;` is not really a cast, since it's not converting anything. 

Using `(void)e` exactly the same way is fine IMHO, or `static_cast<void>(e)` if you prefer. I'm not sure this deserves a guideline.

**Comment by MikeGitb** [comment]
Actually, that line does **NOT** force clang to perform a read at the specified address (just look at the assembly).

**Comment by arvidn** [comment]
interesting. at least it produces a warning. https://godbolt.org/g/Ts3L3P

**Comment by franzhollerer** [comment]
That's very intersting, even slightly off-topic for the CPP Core Guidelines. Thank you for pointing that out.

Unfortunately, I am not that familiar with the C++ standard, but the ISO/IEC 9899:1999 C standard states:

```
6.3.2.2 void
The (nonexistent) value of a void expression (an expression that has type void) shall not
be used in any way, and implicit or explicit conversions (except to void) shall not be
applied to such an expression. If an expression of any other type is evaluated as a void
expression, its value or designator is discarded. (A void expression is evaluated for its
side effects.)
```

Is my code wrong, or is it an abnormality of clang? I used the (void) cast sometimes on embedded system for forcing a read form a peripheral register. I thought it is a nice way to state that the expression is evaluated for its side effects only. And I felt comfortable to be in line with MISRA. Probably I failed to catch and understand the details :-(

**Comment by MikeGitb** [comment]
The void cast is perfectly fine. Clang seems to disagree with the other compilers if just dereferencing a volatile  pointer (as opposed to copy the value stored at that address)  requires the program to actually read from that memory location. And yes, it is OT, but I wanted to point out that no obvious pitfall, before it ends up in an example on the guidelines.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, our advice in ES.48 should allow for the usage of a C-style cast to `(void)` in this situation. See 10.6.7 in the standard. 

By the way, `volatile` is I/O. If you're compiler is warning about that it seems to be a bug in your compiler.

**Comment by hsutter** [comment]
There are three cases covered by this issue:

1. `volatile` (as in the top example): We are taking no action. In the example at top, you do not need any cast at all. As noted above, C++ (and C) compilers should never warn about "apparently unused" reads from `volatile` variables. If yours does, submit it as a bug to your compiler vendor. (I do not have a copy of MISRA C:2012, the latest, to see if their examples include `volatile`, but I hope they don't because `volatile` accesses are never dead code.)

2. `[[nodiscard]]`: More specifically, our decision was to update ES.48 to allow `(void)` to turn off `[[nodiscard]]` warnings, and those only. (This is the way the C++ standard itself says to turn off `[[nodiscard]]` warnings.)

3. Other expressions that look like dead code: We are taking no action. At this point we don't want to change to the Guidelines to bless using a cast to shut up other compiler warnings. If after addressing `volatile` and ``[[nodiscard]]`` as above, you feel we nevertheless should reconsider doing more for the general case, please reopen a new issue.

Thanks!

**Comment by MikeGitb** [comment]
@hsutter: IIRC, the warning by clang is justified, because it does NOT generate a read instruction unless you assign the result of  ` *uart_rx_reg` to some variable. I don't know if this is a known bug in clang or due to insufficient specification in the standard.

**Comment by franzhollerer** [comment]
> If yours does, submit it as a bug to your compiler vendor. (I do not have a copy of MISRA C:2012, the latest, to see if their examples include volatile, but I hope they don't because volatile accesses are never dead code.)

@hsutter: Below screenshots from MISRA C 2012, Rule 2.2 on page 41 and 42

![misra_c_2012_rule2 2_page_41](https://user-images.githubusercontent.com/17589466/31980900-f4d2d160-b94f-11e7-932f-800d1930e722.png)

![misra_c_2012_rule2 2_page_42](https://user-images.githubusercontent.com/17589466/31980904-fc689658-b94f-11e7-9570-dc78a1462e94.png)

**Comment by hsutter** [comment]
@MikeGitb: I view this as a Clang problem -- if not a bug, then a poor quality of implementation. I have repro'd it here: https://godbolt.org/g/GhtMYg . Note that GCC, CL (MSVC), and ICC all perform the read even at the highest optimization levels, but Clang omits the read even at default optimization levels. That's a bug, `volatile` accesses are explicitly not optimizable (cannot be invented, elided, or reordered with respect to each other).

If you change the code from

    v;

to

    int work_around_clang_bug = v;

or to even just

    v+0;

then all compilers including Clang preserve the read. So if your compiler does not interpret the original code as a read, then (a) report it as a bug (usually the Clang folks are interested in being GCC compatible and this is also a GCC incompatibility issue), or else (b) prefer either of the alternatives immediately above as better than a `(void)` cast.

Note that the standard says in 4.6/7:

> The least requirements on a conforming implementation are:
> (7.1) — Accesses through volatile glvalues are evaluated strictly according to the rules of the abstract machine. [...]

and /14:

> Reading an object designated by a `volatile` glvalue (6.10), modifying an object, calling a library I/O
function, or calling a function that does any of those operations are all side effects, which are changes in the state of the execution environment.

So the only conformance question is whether

    v;

is a read of `v`. I believe it is, but I haven't parsed the standardese to check this formally.
