### ISSUE TITLE
Guidline on how to deal with unused parameters

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1049]
Can you please provide a guidline on how to deal with unused parameters, e.g. because the API is fixed but the implementation is changed later on.

In C I would write:

```c

void foo(int arg)
{
    (void) arg; // parameter not used, but the API needs to keep compatible
    :
    :
}
```

Usually, the cast avoids compiler warnings about unused parameters. What is a good way to express this in C++?

**Comment by MikeGitb** [comment]
Just don't give them a name. That way you can actually be sure the parameter is ignored in your code.

**Comment by franzhollerer** [comment]
> Just don't give them a name. That way you can actually be sure the parameter is ignored in your code.
Good point. Many thanks @MikeGitb.

**Comment by arvidn** [comment]
this is covered by [F.9](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-unused).

**Comment by jwakely** [comment]
Yes, see F.9

**Comment by viboes** [comment]
You have an issue when the parameter are used conditionally e.g. via assert :(

**Comment by jwakely** [comment]
That's what the `[[maybe_unused]]` attribute is for.
