### ISSUE TITLE
List of C legacy resource functions

### ISSUE THREAD

**Issue by JonasToth** [isocpp/CppCoreGuidelines#1050]
Hello everybody,

while implementing a check for `gsl::owner<>` in clang-tidy I added functionality to treat functions like `malloc` similar to `new`. The question that came to us in Codereview now is:

What are all the resource management functions in the C Standard. We could think of `malloc`, `free` and friends, but functionality related to mutexes and threads could be thought of as owners, too. We would like to cover everything sensible, especially since this would only require to make a list of functionnames related to resource management.

Could you help us out there what we may cover to be considered as `gsl::owner<>`? Thank you very much.

The review is here [Phabricator](https://reviews.llvm.org/D38396) and [Checker Docs](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-owning-memory.html) for the functionality already implemented.

**Comment by jwakely** [comment]
(This doesn't seem like an issue with the guidelines, so off-topic)

**Comment by phillipjohnston** [comment]
If you're limiting the list to just the C standard, `malloc`/`free` are the primary ones. You also have the file operations defined in `stdio.h` (http://www.cplusplus.com/reference/cstdio/).

**Comment by JonasToth** [comment]
We now have memory management and `fopen`, `fclose`. But the guideline could state what from the standard is considerable as `gsl::owner<>`. It currently only says resources.

**Comment by jwakely** [comment]
I don't really think it's useful to list the functions in the standard that create resources, but if you want to add such a list feel free to create a pull request. "Please add the list so I don't have to figure it out" is just asking people to do your work for you though, isn't it?

**Comment by JonasToth** [comment]
> "Please add the list so I don't have to figure it out" is just asking people to do your work for you though, isn't it?

In some sense, but i meant it more as a question if owner<> actually should apply to threads, because there are only(?) memory management examples.
And maybe there were already thoughts on that as well.

If not, I will try to find them and include them here and in the check.

**Comment by JonasToth** [comment]
Please let me ask my question again, but a little more educated :)

C11 introduced support for threading facilities (as well as C++). Threads, mutexes, conditional variables and tls must be initilized and released. C11 added RAII-simulation functions for this. (see http://en.cppreference.com/w/c/thread), ` thrd_create`, `mtx_init`, `mtx_destroy`, ...

Should these facilities be considered an `owner<>`? The semantics is somewhat similar in my opinion, but the functionality is different to e.g. `malloc`.

My opinion on that one, and thats what lands in the clang-tidy check as well for now:
- Threading facilities are new in C11, the `owner<>` alias needs C++11 anyway, so programmers programming with C++11 and using C11 should rethink
- There is no long legacy history for these functions, like with `malloc`, so automatic tooling support might not be as relevant

**Comment by jwakely** [comment]
Calling those functions "RAII-simulation" is a bit weird, no object gets initialized, because C doesn't have objects or destructors. The whole point of RAII is to avoid the need for explicit "free" calls like `mtx_destroy`.

> Should these facilities be considered an owner<>?

They're not part of C++ (only C) so why does it matter?

**Comment by JonasToth** [comment]
> They're not part of C++ (only C) so why does it matter?

I thought, that C++ includes the C stdlibrary as well including the C facilities for this. If C++ doesn't, it doesn't matter. If this is the cases, this issue can be closed and the question is irrelevant.

**Comment by jwakely** [comment]
Almost nothing from C11 is part of C++ (there are a few exceptions, such as `aligned_alloc`).
