### ISSUE TITLE
Change captions of button to (un)highlight on gh-pages presentation

### ISSUE THREAD

**Issue by martinmoene** [isocpp/CppCoreGuidelines#1051]
On the [gh-pages presentation](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines), the captions of  the button to highlight or un-highlight the code are confusing.

As it is, **Hightlight** means the code _is_ highlighted. Expressing states, i'd expect phrases like **Highlighted** and **Non-highlighted**.

As pressing a button is about performing an action, it is expected that the button's caption indicates the action linked to pressing it, so I'd suggest **Hightlight** to make the code highlighted and **Un-highlight** to remove the highlghting.

**Comment by AndrewPardoe** [comment]
I changed the words entirely: turn ON syntax, turn OFF syntax. Unfortunately the button has a character limit.
