### ISSUE TITLE
Q: How to use classes designed according C.129

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1052]
I think I grasped the idea of distinguishing between implementation inheritance and interface inheritance. I am slightly unsure how this effects the user of a library.

For example the Smiley class is implemented as follows:

```cpp
class Smiley : public Circle { // pure interface
public:
    // ...
};

class Impl::Smiley : public Smiley, public Impl::Circle {   // implementation
public:
    // constructors, destructor
    // ...
}
```

How do I use the class in my own code? I would expect something like that:

```cpp
int main()
{
    Impl::Smiley my_smiley{....};

    my_smiley.redraw();
    :
    :
}
```

But having *Impl::Smiley* in the user code feels somehow strange. Is there a better way to use classes designed as proposed in C.129?

**Comment by jwakely** [comment]
I think "Impl" is meant to be read in the sense of "concrete implementation" not "internal implementation details", so there's nothing strange about using it.

The code that creates the type creates the concrete implementation, then passes it to functions which only use the abstract interfaces and don't care about the concrete implementations:

````
void work_with_shape(Shape&);
int main()
{
  // create concrete shape:
  Impl::Smiley my_smiley{....};
  work_with_shape(my_smiley);
}
````

**Comment by jwakely** [comment]
See the text:

> To make this interface useful, we must provide its implementation classes (here, named equivalently, but in the Impl namespace):

**Comment by AndrewPardoe** [comment]
Per our discussion, it's unusual to have both `Shape` and `Impl::Shape` in the public interface. Should we consider renaming these classes?

The text of the example does explain what's going on. We don't know if we need to make a change. But we might consider changing `Impl::Shape` to `Concrete::Shape`.

**Comment by franzhollerer** [comment]
I like the wording *Concrete::Shape*. IMHO I think it fits better.

**Comment by BjarneStroustrup** [comment]
I added Jonathan's example and a bit of explanation.
