### ISSUE TITLE
Multiple issues with ES.106

### ISSUE THREAD

**Issue by FrankHB** [isocpp/CppCoreGuidelines#1054]
[**ES.106: Don't try to avoid negative values by using unsigned**](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-nonnegative)

This rule directly violates [P.5](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-compile-time), also does not interact well with [P.1](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-direct), [P.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-typesafe) and [P.9](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-waste) in many cases. The rule is lack of rationale to override these meta-rules.

It should be noted that some intentional use of unsigned types (notably, indices) is a workaround to the weakness of expressiveness of the built-in type system on [ordinals v. cardinals](http://wiki.c2.com/?OrdinalsAndCardinals). This is still surely compromised (to the ease of coding and code size, etc), but arguably, more type-safe comparing to using signed integers for all cases instead.

The first example directly violates [ES.100](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-mix). When the issue is fixed, it does not illustrate why the rule is still needed.

The second point is compromised to the failure of expressing orthogonal notions between wrapping behavior and `signed`ness. The statement "unsigned arithmetic is modulo arithmetic" is misleading because unsigned arithmetic is not modulo arithmetic in nature. Making unsigned arithmetic in C++ as an instance of modulo arithmetic is caused by the limitation in the language design for some historical and occasional reasons.

Lack of sufficient rationale also troubles readers for other considerations, e.g. see https://github.com/isocpp/CppCoreGuidelines/issues/1029.

**Comment by FrankHB** [comment]
There are also some side notes about ES. 107.

(I don't find it necessary to open a new issue currently because it seems to be totally covered by ES. 106 as a special case.)

Why `unsigned` instead of "unsigned"? Does `std::size_t` counts?

The example is not enough to lead to a clear way to pick up the right type. Built-in array subscription certainly prefer `std::ptrdiff_t` over `int`, so why `int`?

As per the "enforcement" section, "as the standard-library containers get it wrong", but there is no reason why it is "wrong". The "note" section only mentions the built-in rule disagree with the standard library interface. Since sequence indexing is in different problem domain to pointer arithmetic, it seems nothing is wrong. The inconsistency is introduced by naively defining array subscription as synonym as direct composition of pointer addition and indirection through operations in the built-in language rule inherited from C, which leaks detailed assumptions of the implementation to the abstraction. The approach is also not type-safe to ordinal types (see above). The fact of not having well-formed `index[vector]` should also be respected for the very same reason.

**Comment by MikeGitb** [comment]
I don't have a strong opinion on this, but as a side note on your text:  Imho It would make your issue more readable if you'd cite/ inline the text you are referring to (or at the very least link to it).

**Comment by jwakely** [comment]
> It would make your issue more readable if you'd cite/ inline the text you are referring to (or at the very least link to it).

Agreed, I've edited it to add links.

**Comment by jwakely** [comment]
@FrankHB 

> This rule directly violates P.5, 

I disagree. Using `unsigned` might guarantee that you don't have negative values, but because of implicit conversions you might just have huge values instead, so it doesn't move run-time checks to compile-time, it just changes the run-time checks.

> also does not interact well with P.1,

If you want to use modular arithmetic then unsigned types express that idea directly in the code. If you want natural numbers then they don't do a great job, again because of implicit conversions. A natural number type that enforces non-negative values but also avoids value-changing conversions would directly express the idea. Unsigned types do so poorly.

> P.4

Why?

> and P.9 in many cases. 

Why, because a bit is used for the sign?

> The first example directly violates ES.100.

It's not supposed to be an example of good code, it demonstrates the behaviour of signed/unsigned conversions. 

> The statement "unsigned arithmetic is modulo arithmetic" is misleading because unsigned arithmetic is not modulo arithmetic in nature.

Yes it is.

> Why `unsigned` instead of "unsigned"? Does `std::size_t` counts?

Good point, that should be fixed so it clearly refers to any unsigned types.

> "as the standard-library containers get it wrong", but there is no reason why it is "wrong".

What? The standard library containers violate the guideline, so from the point of view of the guidelines they use the wrong type. If you start from the position that ES.106 is wrong you won't agree, but unsurprisingly the guidelines don't take that position.

> The inconsistency is introduced by naively defining array subscription as the synonym of direct composition of pointer addition and indirection through operation in the built-in language rules inherited from C, which leaks detailed assumptions of the implementation to the abstraction.

It's not wrong because of built-in rules, it's wrong because of ES.106.

> The fact of not having well-formed `index[vector]` should also be respected for the very same reason.

Strawman?

I don't see any actionable suggestions in this issue except for changing `unsigned` in ES.107.

**Comment by FrankHB** [comment]
Perhaps I should have emphasized (not only for ES.107), every points previously mentioned in this issue is about unsigned integer types, non only the type `unsigned`.

The rule ES.106 originally address the problem in #571, which makes choices between `int` and `unsigned`. But the rationale here is not only effective for the 2 particular types. So this can be qualified as the first problem here: despite other concerns, should the rule be explicitly extended for other unsigned types?

This disambiguity is necessary here because not all unsigned type is introduced by an `unsigned` keyword by the user (e.g. `using size_type = std::size_t;`). This is also significant for the topics about style of the standard library interface.

I will treat the two aspects separately when needed.

**Comment by FrankHB** [comment]
@jwakely

Well, it should be clear that using an unsigned integer would not necessarily introduce a compile-time check to ensure the value is non-negative, but the guarantee always holds during compilation by static type-safety, which is superior to additional run-time checks in general, particularly when in the interface. This can be qualified as case of P.4, but since it states "ideally", so this is not a violation. In such cases, it just _eliminates_ the needed check because the vocabulary type is sufficient. This _does not_ qualify to P.5.

However, note the rule ES.106 is not only for explicit vocabulary type. It still allows check, if needed (primarily in some generic code when the type is not so):

```
template_name<typename T>
using guarantees_nonnegative_v = std::is_unsigned_v<T>; // and something else user-defined;

static_assert(guarantees_nonnegative_<some_type>);
```

I don't see why signed integer should be still used here, if the original need is an unsigned integer type.

As you mentioned, there is disagreement about the method to guarantee the range of values. Surely using unsigned integers does not change a run-time check into a compile-time one without magic, but why we need the check in the first place?

I know there are benefits from the check. But this is not necessarily superior than explicit checks because with aid of some static property of programs checked and guaranteed by implementation, implicit style may perform better (as destructor vs. `finally` for resource cleanup). Detailed discussion below.

> If you want to use modular arithmetic then unsigned types express that idea directly in the code.

I don't think that is clear (enough) expressing the idea of "modular arithmetic". As a mathematical structure, modular arithmetic can be defined on various base construct, including both _signed_ integers and unsigned integers. Unfortunately C++ (and C) chooses to couple wrapping behavior and the signedness together for some ad-hoc reasons and this is subtle to most people. Thus, the more I relying on the special convention, the more probabilities I will have to mislead others.

Particularly, consider documentation: when it does not (very carefully) differentiate the keyword `unsigned` and word "unsigned" explicitly enough, how do the readers know I am relying on the wrapping behavior?

So practically I prefer more explicit way to express the intention in the code as well as in documentation: type alias. Ideally it should be opaque, but a plain C++ alias declaration with sufficient comments would still work better than plain unsigned types.

This essentially has nothing to do with the fact of signedness of underlying type. The ease of being portable is an implementation detail, particularly with the fact that almost all machines nowadays have native support of 2's compliment signed integer arithmetics.

Simply using plain unsigned types without extraordinary cautious to express modular arithmetic is likely to lead to false relationship between wrapping behavior and signedness to readers. Compared with the approach above, it seems to undermine the discipline built by P.1.

> If you want natural numbers then they don't do a great job, again because of implicit conversions.

That's I always agree.

But I also don't think signed types is in a better place here. Signed types also have implicit conversions which can easily mess the needed computation up, even when not dealing with natural numbers, just integers.

With such case, I can't be relaxed to code C++ without `-Wsign-conversion` (and `-Wsign-compare`, etc.) before I carefully marked each piece of interested code by cast as long as the operand types differ to what I need; but without unsigned integers, I even (mostly) miss these warnings, and sadly, that does not indicates the problems have really gone.

>> P.4

> Why?

The most obvious reason is mentioned above.

For the root reason, we have to know how we use static types to model set of expected values in general.

Consider an ideal type for some use: the domain of the type is exact the expected range of the values, so all well-defined values inhabited in that type is expected. Use of the value would not introduce any type-error not only within the language used, but also with the types _needed_ in the program - unless some operations deliberately not type-safe are used (e.g. for intropability).

When we don't have the ideal type directly in the language, we often model it with some type (as an underlying type) having a domain as a super set of the expected range and some contracts (often run-time checks) to limit the allowed value set, to build the keeping-in-expected-range invariant (i.e. to ensure the value _always_ does not go out of the expected range, which usually being guaranteed by the typing discipline where the type solely is expressive enough for this purpose). Since integer types are usually not so expressive to satisfy the needed case, this is a _very_ common idiom to use native integer types among _many_ languages.

For example, in C++, valid index value of an array of length N ranges from 0 to N, so the ideal type should have a domain of integer interval [0, N). But we don't necessarily have that type expressed directly by the language, so for simplicity, we weaken the static type discipline with an integer type having a more permissive domain [0, M) (where M is an integer value guaranteed not less than N) as the underlying type, with additional value check as a contract to ensure the index always less than N (not M). Only with the aid of allowing the additional check, the type is convinced expressive to the original intent, so "safe".

In canonical C++, the underlying type in this case is `std::size_t`, and M - 1 is equal to to `std::numeric_limits<std::size_t>::max()`.

If you change `std::size_t` to some integer type, say, `std::ptrdiff_t`, the approach can still work, but you need at least one more additional contract for the valid range invariant to achieve same effect, i.e. type safety here.

The static type plus contracts can be still considered equally safe when the contracts are enforced. It is just not so _statically_-safe. So this qualifies to P.4.

> Why, because a bit is used for the sign?

Yes, though I mostly don't care it much.

> What? The standard library containers violate the guideline, so from the point of view of the guidelines they use the wrong type. If you start from the position that ES.106 is wrong you won't agree, but unsurprisingly the guidelines don't take that position.

That's tautology.

The guideline does not impose any axiomatic semantics by the statements, while the spec in the ISO publications impose _conformance_. And they are not consistent.

So I think the best initial position is to suspect both are not proved necessarily needed, or, probably being inconsistent to common consensus of users (when I am not standing for a vendor of some conforming implementation).

To _reason_ whether the rules are convincing, there should be external materials (which is often called the _rationale_) rather than the rules themselves (the title here; or in ISO parlance, the "normative text") or simply the _conclusion_ of the rules.

This should eventually determine it is a defect on the standard or it is of the guideline itself (as long as the guidelines intentionally refers to the whole standard).

> It's not wrong because of built-in rules, it's wrong because of ES.106.

So in this turn you have a different position than before. You assume the a particular special set of rules from the standard unconditionally acceptable without reason that can be consensus, which is even not covered by ISO policy.

But things are now more complicated:

> Good point, that should be fixed so it clearly refers to any unsigned types.

You seem to admit `std::size_t` is in the scope. Since this is covered by the core rules, I am curious which set of the rules from the standard are supposed not "wrong" by the guidelines.

**Comment by FrankHB** [comment]
Some additional notes on integer arithmetic solely (without conversions) follows.

Except when the integer is stored in a `volatile` object and being modified by others' code unexpectedly (which is no responsibility of the coder), the keeping-in-valid-range invariant does not change. In other words, suspicious "unsafe" operations are limited.

For integers with same types, built-in arithmetic operations are all suspicious without contracts, because the results of those operations are simply not mathematically closed in the domain.

But there are slight differences to make signed integers face more subtle and error-prone troubles than unsigned integers in general.

* For `/` and `%`, both have to be aware of divide-by-zero error (otherwise it is UB), while signed integers should additionaly prevent case like `INT_MIN / -1` (otherwise it is also UB).
* For `+`, `-` and `*`, signed integers need to check the value preventing _both_ overflow and underflow in general, while unsigned integers need to check one of them when the minimum value in the expected range is zero (quite common case), argubly indicating more explict intention of the arithmetic operation.
	* So when there is no `-`, underflow check can be totally eliminated by design for unsigned integers safely in spite of the existence of value check on operand, because "no underflow" invariant is effectively ensured by a static and type-safe manner. Signed integers still have mental burden to doubt.

**Comment by arvidn** [comment]
I think i may have lost what your argument is now. But I get the impression that you're focusing on the range of integers that can be represented *more* than the arithmetic on signed and unsigned types. I would argue (and I think the guidelines agree with me) that the modulo 2 arithmetic is a more important property of unsigned types than their range. it's the property that's causing the most surprise.

The compiler will assume that you are going to wrap your unsigned integers, because that's how they are defined. It will make sure that all of your expressions with unsigned types will behave exactly as you wrote them even when they may wrap.

The fact that most hardware does twos complement in hardware isn't all that relevant, the optimizer will make the results of signed overflow unexpected anyway.

Are you calling for a type that has normal arithmetic and can only represent positive numbers? That might be a useful type, but it's only a single bit away from what we already have (signed integers).

**Comment by FrankHB** [comment]
@arvidn

> I think i may have lost what your argument is now.

So there were multiple issues. Each of them are not the same, but related to the necessity and the encouraged direction of the rules.

> But I get the impression that you're focusing on the range of integers that can be represented more than the arithmetic on signed and unsigned types.

Use of interval types is significant, but not the only case being respected in these points. The _range_ of values represented by a type is a common (in mathematical sense) property one have to dealt with for _almost all_ types. A few exception would be `void` and unit types like `std::input_iterator_tag` because there are less than two distinct values can inhabited and the concrete value (if any) is not interested in the high-level language; integers are never of those cases in nature.

> The compiler will assume that you are going to wrap your unsigned integers, because that's how they are defined.

Because it is _requried_ by semantic rules of the language. That does not imply users _should_ rely on such rules. This is like requiring sane names on identifiers even if the compiler does not distinguish their meanings.

The specific rules are even not invented by C++, and they are hardly treated as just "by design" now. They are not changed for historical reasons like backward compatibility, not readability or sanity.

Note the word "unsigned" in literal just guarantees the consideration of the sign is considered (and the form of sign bit is determined by more general rules of representation of integer types), but it does not imply wrapping on arithmetic operations at all. It also does not mean "2's complement", "having (no) padding bit" and all other guarantees on value representation just being an "integer", or even "machine-supported fixed-width integer". It is reasonable of not supporting built-in arbitrary-precision integers due to object model or memory consumption reasons, but relying on those over-specific properties blindly are error-prone in reality.

(The coupling of wrapping is particularly odd because it is not meaningful without specific arithmetic operations defined with that in mind. This is not the case of padding bit, for example. This also indicates if the specific wrapping behavior is needed, they perhaps don't need to be in the core rules.)

> The fact that most hardware does twos complement in hardware isn't all that relevant, the optimizer will make the results of signed overflow unexpected anyway.

Machine support is perhaps the only sane reason why 2's complement is historically expected, besides the simplicity of interoperations.

The optimizer is free to have assumption of overflow-free properties on integer types, as long as the language allows to _express_ them. But now there is no potable way to specify no wrapping on unsigned types. If the they are provided by the language, they are still "unsigned" types. ES.106 and its friends suddenly only work for bug-to-bug compatibility of wrong design.

> Are you calling for a type that has normal arithmetic and can only represent positive numbers? That might be a useful type, but it's only a single bit away from what we already have (signed integers).

This is somewhat off topic. If I'd like to propose such feature, I've gone to [std-proposals](https://groups.google.com/a/isocpp.org/forum/#!forum/std-proposals). But I can tell you the rationale I need.

In short, I'd not call for any particular type for concrete use cases here. I'd call for a consistent, methodological way to pick up proper types from a high-level language, along with respecting to zero-overhead principle and any other common reasons to choose C++.

(For this case, such type would be better to replace many cases of integers being used currently, but to avoid over-complicated language specification, I don't agree it should be provided by the core language.)

As illustrated, when there is no other requirement to determine which one of the two set of static types is better, the basic method is to figure out which is more statically type-safe based on some general rules (e.g. some P. rules from guideline) and some common sense of PLT. The soundness of such method is formally provable sometimes.

Without such kind of method, both signed types and unsigned types are imperfect for various reasons. Some of them are obvious to noobs and others are only obvious to experts, but both kind are problematic. I don't think it is appropriate to endorse an imperfect choice over the other without sufficient reasoning implying the consensus, so I think here is the correct place.

**Comment by FrankHB** [comment]
@arvidn

> I think i may have lost what your argument is now.

So there were multiple issues. Each of them are not the same, but related to the necessity and the encouraged direction of the rules.

> But I get the impression that you're focusing on the range of integers that can be represented more than the arithmetic on signed and unsigned types.

Use of interval types is significant, but not the only case being respected in these points. The _range_ of values represented by a type is a common (in mathematical sense) property one have to dealt with for _almost all_ types. A few exception would be `void` and unit types like `std::input_iterator_tag` because there are less than two distinct values can inhabited and the concrete value (if any) is not interested in the high-level language; integers are never of those cases in nature.

> The compiler will assume that you are going to wrap your unsigned integers, because that's how they are defined.

Because it is _requried_ by semantic rules of the language. That does not imply users _should_ rely on such rules. This is like requiring sane names on identifiers even if the compiler does not distinguish their meanings.

The specific rules are even not invented by C++, and they are hardly treated as just "by design" now. They are not changed for historical reasons like backward compatibility, not readability or sanity.

Note the word "unsigned" in literal just guarantees the consideration of the sign is considered (and the form of sign bit is determined by more general rules of representation of integer types), but it does not imply wrapping on arithmetic operations at all. It also does not mean "2's complement", "having (no) padding bit" and all other guarantees on value representation just being an "integer", or even "machine-supported fixed-width integer". It is reasonable of not supporting built-in arbitrary-precision integers due to object model or memory consumption reasons, but relying on those over-specific properties blindly are error-prone in reality.

(The coupling of wrapping is particularly odd because it is not meaningful without specific arithmetic operations defined with that in mind. This is not the case of padding bit, for example. This also indicates if the specific wrapping behavior is needed, they perhaps don't need to be in the core rules.)

> The fact that most hardware does twos complement in hardware isn't all that relevant, the optimizer will make the results of signed overflow unexpected anyway.

Machine support is perhaps the only sane reason why 2's complement is historically expected, besides the simplicity of interoperations.

The optimizer is free to have assumption of overflow-free properties on integer types, as long as the language allows to _express_ them. But now there is no potable way to specify no wrapping on unsigned types. If the they are provided by the language, they are still "unsigned" types. ES.106 and its friends suddenly only work for bug-to-bug compatibility of wrong design.

> Are you calling for a type that has normal arithmetic and can only represent positive numbers? That might be a useful type, but it's only a single bit away from what we already have (signed integers).

This is somewhat off topic. If I'd like to propose such feature, I've gone to [std-proposals](https://groups.google.com/a/isocpp.org/forum/#!forum/std-proposals). But I can tell you the rationale I need.

In short, I'd not call for any particular type for concrete use cases here. I'd call for a consistent, methodological way to pick up proper types from a high-level language, along with respecting to zero-overhead principle and any other common reasons to choose C++.

(For this case, such type would be better to replace many cases of integers being used currently, but to avoid over-complicated language specification, I don't agree it should be provided by the core language.)

As illustrated, when there is no other requirement to determine which one of the two set of static types is better, the basic method is to figure out which is more statically type-safe based on some general rules (e.g. some P. rules from guideline) and some common sense of PLT. The soundness of such method is formally provable sometimes.

Without such kind of method, both signed types and unsigned types are imperfect for various reasons. Some of them are obvious to noobs and others are only obvious to experts, but both kind are problematic. I don't think it is appropriate to endorse an imperfect choice over the other without sufficient reasoning implying the consensus, so I think here is the correct place.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we will stay with our recommendation. We don't have a clear recommendation to change so we'll leave the advice in ES.106 as-is. 

Thank you for the suggestion!
