### ISSUE TITLE
SF.7 says not to put using directives in a header. Is "std::literals" an exception?

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#1055]
Template libraries that use string literals don't have a reasonable place to put `using namespace std::literals`. Is it acceptable to put this using statement at the broadest scope? `std::literals` seems to be an exception to rule [SF.7](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-using-directive).

**Comment by MikeGitb** [comment]
Well, as user defined litterals have to have an underscore, there seems to be no danger of collisions, so I don't see any reason not to. 

What I'm wondering is why they haven't been defined in the global namespace to begin with. Would probably be a good idea to first check if the committee had good reasons for this.

**Comment by jwakely** [comment]
Defining them in sub-namespaces allows the same suffix to be used for different things, and for users to select which set of literals they want to use in a given scope. e.g. a future standard could define `std::literals::physics_literals::operator""b` for barn and `std::literals::computing_literals::operator""b`for byte.

**Comment by galik** [comment]
Has that rule gotten stricter? I seem to remember (I cold be wrong) when there was a conversation about this here the general consensus was that it was acceptable to use `using namespace ...;` in a header file *within a namespace* but not at the global level. And if you look at the **enforcement** section it only says to check for usage at the *global namespace*. But the rule itself does not appear to make that concession.

**Comment by MikeGitb** [comment]
@jwakely: Thanks, that makes sense. 
So the danger of using namespace std::litterals is that the standard (in the future) might define litterals that can't coexist in the same scope as the existing ones and if a header starts to pull std::litterals (which afaik inlined all currently existing litterals  namespaces) into global namespace (directly or indirectly) that would prevent me from using any colliding ones in the future...  
Thing would be so much easier if we had somehing like a `cancel using namespace` directive, just like you can under macros.

So the answer would be to wait for modules and hope that the effects of `using namespace xxx` stay contained within the module boundaries (I assume that is the case?).

@galik: Good question. As Andrew referred to the "broadest scope" I just assumed he was referring to the global namespace and didn't check what exactly the rule said.

**Comment by arvidn** [comment]
@MikeGitb it's already the case in the standard that ``operator""s`` is used both for *seconds* and *string*, depending on which namespace you pull in.

**Comment by MikeGitb** [comment]
@arvidn: They don't collide, because the arument types are different. E.g. this is perfectly valid code:

    #include <chrono>
    #include <string>

    using namespace std::literals;

    int main() {
        std::string str = "1000"s;
        std::chrono::seconds s1 = 1000s;
    }
