### ISSUE TITLE
Potential for confusion between gsl::string_view and existing TS

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#106]
Beman Dawes pointed out that there is potential for confusion between the string_view in the GSL and the existing string_view in the TS. The main issue is that the former allows mutation whereas the latter does not. 

While we plan to discuss aligning these types at the upcoming ISO C++ meeting in October, we should consider a different name such as string_ref.

**Comment by trebconnell** [comment]
I was assuming that it was referring to the string_view that will(?) exist in the future.  The guidelines here don't go into details.  Maybe it'd just be best to call out that any implementation (Microsoft.GSL, examples in the guidelines) are temporary until the official standardization is complete.

**Comment by hsutter** [comment]
We'll a FAQ section that will answer this and some related questions.

**Comment by hsutter** [comment]
Reopening until we actually push the FAQ addition that resolves this.
