### ISSUE TITLE
R.33 suggested enforcement leads to spurious warnings

### ISSUE THREAD

**Issue by TartanLlama** [isocpp/CppCoreGuidelines#1062]
On CppLang Slack, a user wrote code similar to this:

```
struct foo {
    void add (std::unique_ptr<bar> ptr) {
        bars_.push_back(std::move(ptr));
    }
    std::vector<std::unique_ptr<bar>> bars_;
};
```

The core guidelines checker warned them that they should use `T&` or `T*` instead since they weren't assigning to or calling `reset` on `ptr`. However, the code they wrote was legitimate. I'd recommend updating the enforcement warning to allow moving the `unique_ptr` into some storage. 

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r32-take-a-unique_ptrwidget-parameter-to-express-that-a-function-assumes-ownership-of-a-widget

**Comment by TartanLlama** [comment]
There was an additional piece of information which I missed, and which muddies things. Closing for now.

**Comment by jwakely** [comment]
The enforcement only refers to parameters taken by reference. A `unique_ptr` value parameter obviously takes ownership, so the tool is broken if it warns.
