### ISSUE TITLE
Listing unenforceable guidelines

### ISSUE THREAD

**Issue by MikeGitb** [isocpp/CppCoreGuidelines#1064]
I just saw [the interview of Bjarne Stroustroup at channel 9](https://channel9.msdn.com/Shows/C9-GoingNative/Bjarne-Stroustrup-Interview-at-cppcon-2017) and he restated that people should not have read the full guidelines but have a look at the philosphical guidlines and leave it to the tools to warn them about violations of the other guidelines.

I wonder if it would make sense to curate a list of rules that are not in the section P, but can't be enforced by a tool and thus have to be enforced (and hence read) by humans.

**Comment by JonasToth** [comment]
I work an the opposite site. 
https://github.com/JonasToth/CppCoreGuidelinesTooling
this is thought of collecting all guidelines that are enforceable and mention tools and configurations that enforce the guideline. I think these two approaches could be combined somehow.

**Comment by markyin** [comment]
https://github.com/Microsoft/GSL
Maybe it's helpful for you

**Comment by MikeGitb** [comment]
Sorry, I didn't have my coffee yet. Can you explain how the gsl is relevant to the question?

**Comment by markyin** [comment]
![for_mikegitb](https://user-images.githubusercontent.com/350279/32129983-f3893f5a-bbc1-11e7-9587-e51f9ac8ed7c.png)

@MikeGitb

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion and for your work in maintaining the list of current tooling at https://github.com/JonasToth/CppCoreGuidelinesTooling. The guidelines and associated enforcement tooling are constantly changing at this point. We don't feel that maintaining an official subset is fruitful at this point.
