### ISSUE TITLE
Translations to Other Languages

### ISSUE THREAD

**Issue by leoperezpulido** [isocpp/CppCoreGuidelines#1065]
Hi,

I am planning to translate Cpp Core Guidelines to Spanish and publish it into a GitHub repository but I see that the Standard C++ Foundation licence is (very) restrictive.

- Do I have permission to do that?
- Any plans to "lower the bar" of the licence so that it can be more accessible to the community?
- Isn't this licence a "low blow" to the spirit in which the Core Guidelines are published?

Thanks!

**Comment by johelegp** [comment]
I can't answer your questions, but I'll let you know that I have a stalled Spanish translation of the guidelines here: https://github.com/johelegp/CppCoreGuidelines-es.

**Comment by leoperezpulido** [comment]
So, it is not a matter of the translation "per se" which certainly can or cannot be done, although yours isn't completely translated (you must admit it) and there can be space for improvement of the work you have already done.

It is a matter of what can you do with the actual license, please consider:

`Standard C++ Foundation grants you a worldwide, nonexclusive, royalty-free,
perpetual license to copy, use, modify, and create derivative works from this
project for **your personal or internal business use only**.`

What does it really mean "your personal or internal business use only"? Well, according to this first statement, one can use this work for personal or internal use **only.** Here nothing else is said, and when one thing is clearly stated, there is no room for interpretation.

And that is how I interpret it (I am sure we all already note the use of the word "only"). But there is a community's spirit much bigger and wider behind the license itself: a spirit to promote the correct use of modern C++ that lays within the CppCoreGuidelines.

> The aim of the guidelines is to help people to use modern C++ effectively.

The spirit "to help people" (it is called aim here). And it is there where I see the contradiction between the current license and this "aim." If I may:

- How can the Guidelines help "people" (the word people should be changed for _programmer_, ordinary "people" doesn't write programs) when the only source of information is only in one language? Is it C++ used in countries where English is not the native language? How many programmers in those countries speak English? Japan, Israel, Greece, UAE?

- How can the Guidelines help "people" if these license does not allow to publicly publish derivative works? (Translations count as derivative works according to many licenses.)

- How can the Guidelines be spread in other (spoken) languages to help "people" if the license is "only" for personal or internal use?

Yes, there is a "_laguna legis_" (or an explicit intent to protect the Guidelines) and I hope that it can be taken into consideration. The point is that there is no explicit statement that says that you can publish a derivative work based on this license, and either there is no statement that says that you cannot. Sorry, but other licenses are more explicit in this regard, and sorry my friend, but according to this you are "breaking the law."

And it is in this context in which I wrote asking for "permission" not to translate, but to publish the derivative work.

**Comment by AraHaan** [comment]
Well it says nothing about something that can auto generate the translated files based on the english ones.

**Comment by AndrewPardoe** [comment]
You are welcome to translate the guidelines to another language. Please let us know so that we can link to it. 

The intent of the license, as I understand it, is solely to prevent individuals or enterprises from profiting from the Core Guidelines. For example, the Standard C++ Foundation would not be pleased if you published a book based on the guidelines.

**Comment by leoperezpulido** [comment]
Thanks!
