### ISSUE TITLE
F15 Suggests passing impossible to copy arguments by value

### ISSUE THREAD

**Issue by dharvey1986** [isocpp/CppCoreGuidelines#1076]
Presumably this should only be in the case where they ownership (in the case of e.g. unique_ptr) is being taken over. For pure read-only input values taking a copy is not an option...

**Comment by cubbimew** [comment]
What's "F13"? The rule mentioning passing by value is [F.16: For "in" parameters, pass cheaply-copied types by value and others by reference to const](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-in)

**Comment by dharvey1986** [comment]
Thanks - I fixed the title. I'm looking at the table in F15. For "in" parameters where you don't retain a "copy", it looks like it suggest passing unique_ptr by value?

**Comment by jwakely** [comment]
> Thanks - I fixed the title.

Looks the same to me.

If you don't need to transfer ownership then you should be passing a raw pointer anyway. See [R.30](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-smartptrparam).

**Comment by dharvey1986** [comment]
OK sure - I haven't read that far. I was trying to point out that the table is potentially a bit misleading.
