### ISSUE TITLE
Need more details on CP.1 "Assume that your code will run as part of a multi-threaded program"

### ISSUE THREAD

**Issue by paulmckrcu** [isocpp/CppCoreGuidelines#108]
The CP.1 rule needs context, namely that it applies most sharply to code that is intended to be shared (such as libraries) and less urgently to things like standalone applications.

This rule also needs an example, and needs alternatives for fixing that example.

A prototype may be found here:  https://github.com/paulmckrcu/CppCoreGuidelines at commit 4462a0462d7f8ee4cc04a321190dbbdfd35db2f0 .

**Comment by thecoshman** [comment]
[direct link to the commit in question](https://github.com/paulmckrcu/CppCoreGuidelines/commit/4462a0462d7f8ee4cc04a321190dbbdfd35db2f0)

**Comment by thecoshman** [comment]
I think this can just be handled as a pull request, I don't see anything ground braking here.

**Comment by paulmckrcu** [comment]
Works for me.

Is there some trick to get the pull request to go to the parent of a
forked archive?  Sorry for the newbie github question, but I normally
just use command-line git directly, and my attempt to send a github pull
request seemed to just come directly back to my forked github archive.  :-/

							Thanx, Paul

**Comment by thecoshman** [comment]
I've not really dealt much with forks via cli. I think you need to use the gh site to create the request for isocpp to pull changes. Don't forget to make sure your fork is up-to-date with this main repo first.

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

**Comment by hsutter** [comment]
Will add a note that "even if you think it will not happen, it might."

**Comment by hsutter** [comment]
Thanks for the example, it's a good one. I'll take it.

**Comment by AndrewPardoe** [comment]
Discussed 21 Dec. We'll accept this PR as written. Thank you!

**Comment by hsutter** [comment]
Thanks!
