### ISSUE TITLE
C.67 / C.130 Question/Suggestion

### ISSUE THREAD

**Issue by uweBender** [isocpp/CppCoreGuidelines#1080]
In the C++ Core Guidelines C.67/C.130 is the recommendation to forbid
the copy c'tor and use a virtual function clone() instead.  But it may
be difficult to write a simple clone() method without having a copy
c'tor. Just imagine that some base class attributes are private.

The intent ist to prevent slicing, because the normal copy operations
will copy only the base portion of a derived object.

But there is a another solution to make a deep copy of derived
objects, without a clone() function:

The non-virtual operator=() must exist. It just calls a virtual
function assign(const Base&). Covariance is allowed (see code)

Each class shall have a swap()-method. The swap-method of a derived
class calls the swap-method of the superclass and then swaps only
class-local data.

The base class and the derived classes all have a certain structure
which can be seen from the example, see
http://ide.geeksforgeeks.org/M3mlh9

Is that a reasonable approach? Weaknesses?

**Comment by jwakely** [comment]
> Just imagine that some base class attributes are private.

Well then your base class is making it unnecessarily hard to use. Don't do that.

I don't udnerstand how your solution can work. If I have `Base& b` and I want a new object of the same type, how does assignment help? I can't declare the new object, because I don't know its dynamic type.

**Comment by uweBender** [comment]
Yes, it is not easy to use. clone() may be also difficult.
How to create Base&:
`  Base b8(8);
  Base& rb = b8;     // new ref
  Derived d9(9, "nine");
  Base& rd = d9;     // dynamic ref
  assert(rd == d9);  // ok
`

**Comment by MikeGitb** [comment]
Is a copy ctor really a problem in practice? Usually (always?) the  base class copy*) ctor gets involved in contexts where I'm explicitly creating an object of base class type. That is certainly not what I'd call accidental slicing.

Copy assignment is admittedly a different beast though

*) When I say copy I mean copy/move

**Comment by jwakely** [comment]
There's nothing useful here, closing.
