### ISSUE TITLE
Con.1 clarification

### ISSUE THREAD

**Issue by tiagomacarios** [isocpp/CppCoreGuidelines#1081]
[Con.1: By default, make objects immutable](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#con1-by-default-make-objects-immutable) says:

```
Exception Function arguments are rarely mutated, but also rarely declared const.
To avoid confusion and lots of false positives, don’t enforce this rule for function arguments.
void f(const char* const p); // pedantic
void g(const int i);        // pedantic
Note that function parameter is a local variable so changes to it are local.
```

IMHO this somewhat contradicts the main reasoning behind the rule:

```
Reason Immutable objects are easier to reason about, so make objects
non-const only when there is a need to change their value.
Prevents accidental or hard-to-notice change of value.
```

Function parameters passed by value are local variables to the function, so shouldn't they also be const? I guess I am having a hard time understanding why this is pedantic.

@BjarneStroustrup I saw that you were the one that wrote this part of the guidelines. Would you mind further explaining your reasoning?

**Comment by jwakely** [comment]
Yes, it contradicts it, but for the reasons given:

> To avoid confusion and lots of false positives

Not enforcing it for function parameters avoids confusion because many C++ users don't even realise it's valid to add `const` in the function definition even if it wasn't there in the declaration. Rather than enforcing a rule that would simply lead to confusion, don't enforce it for function parameters.

Not enforcing it for function parameters avoids lots of false positives because most people do not write their function parameters that way, and there are billions of lines of C++ code that would trigger new warnings.

**Comment by galik** [comment]
>Not enforcing it for function parameters avoids confusion because many C++ users don't even realise it's valid to add const in the function definition even if it wasn't there in the declaration.

Heaven forbid we should teach people how C++ works.  :smile: That aside nothing is lost if programmers also put `const` in the function declaration. Also it seems confusing to me to have one rule for local variables declared as parameters and the opposite rule for other local variables.

>Not enforcing it for function parameters avoids lots of false positives because most people do not write their function parameters that way, and there are billions of lines of C++ code that would trigger new warnings.

Those are not really *false positives* those are *genuine positives* that you have decided are too much trouble to bother with. But the point is you can turn checker tool features on and off so couldn't people decide for themselves if they want to enforce this rule for function parameters or not? I for one would like to have it as a feature.

Also I don't see why the fact that "most people do not write their function parameters that way" is relevant. What is the point of the guidelines if not to change the way people write their code? Safe coding practices are not determined by the way previous code happens to have been written. 

>Rather than enforcing a rule that would simply lead to confusion and tons of new warnings for correct code, the recommendation is that checkers should not enforce this guideline for function parameters.

Very many people do not declare general local variables `const` in the same way they do not declare parameter local variables `const` so I suspect this check is going to throw up thousands of new warnings regardless. Is it not best to give people the opportunity to make all the variables `const` at the same time?

And once again these features are supposed to be easy to turn on and off so people should easily be able to avoid being this pedantic if they choose not to be.

>If you want to add const to your functions that's fine, go for it, but the guidelines don't require checkers to enforce that.

Would it not be *much much easier* for us to add `const` to our function parameters if we had a checking tool to tell us where those changes should be made?

All we need checkers to be able to do is select if they enforce it or not. But whether or not we set our checkers to enforce it or not, I do not see how the argument made for local variables does not also apply to local variables defined in the parameter list.

Having one rule for some locals and the opposite rule for others can be a source of confusion and also it could lead people into a *false sense of security* by assuming the checker has protected them from accidentally modifying local variables that are not supposed to be modified. The truth is the checker will only be protecting them from accidentally modifying **some** of their local variables but not all of them.

By at least adding the **option** to pedantically check parameters you give people a tool they can use to make their code safer if they want to use it.

But the way the guideline is currently worded it seems to assume that local variables defined as function parameters are somehow magically protected from accidental modification. Shouldn't the guidelines be there to raise awareness of the fact that there is no magical protection and that making parameters `const` is *always* going to be safer?

**Comment by jwakely** [comment]
> Safe coding practices are not determined by the way previous code happens to have been written.

Best practices are supposed to be based on real world experience.

> By at least adding the option to pedantically check parameters you give people a tool they can use to make their code safer if they want to use it.

That would be something for a specific checker to provide, not the guidelines.

> But the way the guideline is currently worded it seems to assume that local variables defined as function parameters are somehow magically protected from accidental modification.

Nonsense, "don’t enforce this rule for function arguments" means nothing of the sort.

**Comment by galik** [comment]
>>But the way the guideline is currently worded it seems to assume that local variables defined as function parameters are somehow magically protected from accidental modification.

>Nonsense, "don’t enforce this rule for function arguments" means nothing of the sort.

But "Function arguments are rarely mutated, but also rarely declared const." does.

**Comment by jwakely** [comment]
Not in the version of English I'm familiar with.

**Comment by cubbimew** [comment]
> nothing is lost if programmers also put const in the function declaration

The match between what the code says and what function is actually declared is lost, although it's not a big deal to most people. Actually, if we are being pedantic, the text of the Con.1 enforcement exception discussed in this issue should be showing a pair of definitions.

> one rule for some locals and the opposite rule for others

as already pointed out, there is no opposite rule. There is one rule with two levels of enforcement.

**Comment by galik** [comment]
>>nothing is lost if programmers also put const in the function declaration

>The match between what the code says and what function is actually declared is lost, although it's not a big deal to most people.

I'm not entirely sure what you mean there but whether you declare a parameter `const` or not in the prototype it means the same thing. What would be lost (and some might say **should** be lost) is the match between what the code says it does and how the code goes about doing it. If a parameter is set to `const` then that is an *implementation detail* that the outside world doesn't need or benefit from knowing. But what I am saying is that nothing is lost if it does.

**Comment by BjarneStroustrup** [comment]
Have you ever - in real code - observed a bug caused by a parameter not being const? I have not. The Core Guidelines are intended to address real-world problems, preferably without causing extra work or new problems.

**Comment by jwakely** [comment]
@galik this was already explained in #975 -- if you don't like it that's fine, but do you need to waste everybody's time by bringing it up again?

**Comment by galik** [comment]
> @galik this was already explained in #975 -- if you don't like it that's fine, but do you need to waste everybody's time by bringing it up again?

Well I was going to link that conversation in as *relevant* to this issue but when I looked through the conversation got sidetracked to a different issue so I decided not to.

**Comment by jwakely** [comment]
Aaaaaaand this one has got sidetracked too, from "what is the reasoning?" to you disagreeing with that reasoning again. You're welcome to have your own opinion, but it's not necessary to keep repeating it. The reasoning is as explained in 
https://github.com/isocpp/CppCoreGuidelines/issues/1081#issuecomment-345230904

**Comment by galik** [comment]
> Aaaaaaand this one has got sidetracked too, from "what is the reasoning?" to you disagreeing with that reasoning again. You're welcome to have your own opinion, but it's not necessary to keep repeating it. The reasoning is as explained in
#1081 (comment)

The front page of the guidelines invites people to "Join the discussion in Issues.". If we are no longer allowed to give our opinions or join in on discussions perhaps that could be re-worded?

**Comment by jwakely** [comment]
I didn't say people are not allowed to join in, I said it's not necessary for **you** to keep **repeating** it. I don't know if you deliberately misinterpret everything just for the sake of an argument, but it's extremely tedious.

**Comment by phillipjohnston** [comment]
I just want to provide a gentle reminder that these discussions are public and go to many email inboxes. The question has been answered. Perhaps there is a better medium to resolve this argument?

**Comment by hsutter** [comment]
All: Fresh input is always welcome and helpful. But once a particular issue has been considered, we should let it go even if we don't all agree with the result; just repeating it is not helpful (and clogs a lot of people's inboxes as was mentioned). I self-censor too when I've been heard and re-raising it would be repetitive. :) Thanks for understanding.

**Comment by tiagomacarios** [comment]
#975 has the answer to my question. I tried looking for this issues before posting, not sure why I didn't see that one. I am closing this issue since the conversation has derailed substantially.
