### ISSUE TITLE
Should C.81 also recommend the function to be public?

### ISSUE THREAD

**Issue by brenoguim** [isocpp/CppCoreGuidelines#1083]
Item [C.81](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c81-use-delete-when-you-want-to-disable-default-behavior-without-wanting-an-alternative) recommends to use `= delete` to disable behavior.

Should it also recommend the function to be public?

It may sound counter-intuitive that someone would make these functions private, but in a lot of pre-C++11 code that was a common idiom.
So, I'm seeing people updating the code and keeping the function on private block, or creating new code in private block just because they didn't notice that subtle change is ok now.

Also, is there any application for private deleted functions?

**Comment by MikeGitb** [comment]
Imho, public should be the default, but does it make a difference for deleted functions, whether they are private or public.

**Comment by jwakely** [comment]
With some compilers the diagnostics are worse if it's private, because you get two errors (one for using a deleted function, one for using an inaccessible function). So there's no advantage to making deleted functions private, but I'm not sure that making them public is important enough to add to the guidelines. Slightly worse diagnostics for ill-formed code is not a safety or correctness issue. Not every little thing needs to be in the guidelines, or the useful advice gets drowned in noise.

**Comment by brenoguim** [comment]
> With some compilers the diagnostics are worse if it's private, because you get two errors (one for using a deleted function, one for using an inaccessible function).

This is one reason and the first reason that called for my attention to this issue. In GCC you only get the "using inaccessible function".

Another mentionable point is that deleted methods are part of the class public API. It's part of the documentation of how the class is supposed to be used, and it's expected to be read and known by the class user.
I believe those two reasons are worth being documented and recommended.
 
> Not every little thing needs to be in the guidelines, or the useful advice gets drowned in noise.
Agreed. And that is definitely nitpicking and kind of noisy. But also leads to clean code.

Is there any session "additional notes" or "details" we can add this explanation and link it to C.81?

If not, and if that is not the desire of the maintainers of this guideline, I understand. (I'm not willing to fight very hard for having it :D).
Just having this discussion is already something to point for when I'm doing code reviews.

**Comment by jwakely** [comment]
> In GCC you only get the "using inaccessible function".

No, you get both. Same with Clang.

**Comment by brenoguim** [comment]
True! My bad.

**Comment by brenoguim** [comment]
So, my concrete suggestions in order of intrusiveness:

1 - Fix all deleted functions to be public in the document ([T.150](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#t150-check-that-a-class-matches-a-concept-using-static_assert), [C.67](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c67-a-base-class-should-suppress-copying-and-provide-a-virtual-clone-instead-if-copying-is-desired)). Making the guildelines consistent regarding this helps teaching by example.
2 - Add a note to the C.81 example, similar to what is done on [F.18](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f18-for-consume-parameters-pass-by-x-and-stdmove-the-parameter). Something on the lines of "Notice the deleted default operations should be public.".
3 - Same as 2, but with external link to explanation on why they should be public.

I'd be happy to come up with a pull request for any of those options.

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion, @brenoguim. Could you please prepare **separate** PRs for your suggestions 1 and 2?

**Comment by brenoguim** [comment]
Happy to!
