### ISSUE TITLE
Is vector<char> necessary when we have string? (Reconcile SL.str.1 and SL.con.2)

### ISSUE THREAD

**Issue by Epholys** [isocpp/CppCoreGuidelines#1084]
[SL.con.2](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slcon2-prefer-using-stl-vector-by-default-unless-you-have-a-reason-to-use-a-different-container) recommends using a `vector<char>` instead of a `string` for a container of individual character. However [SL.str.1](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slstr1-use-stdstring-to-own-character-sequences) recommends using `string` for all character sequences.

I don't see an advantage using a vector in any way:

- strings can do everything vectors can
- strings have additional useful operations specifically for manipulating characters
- the underlying data structure is a contiguous array in memory for both
- mixing the two is impossible without boilerplate conversion functions

The only difference would be a very specific semantic one, and I don't think it's worth the hassle.

**Comment by jwakely** [comment]
Not all sequences of characters are strings, e.g. a sequence of binary data stored as `char` or `unsigned `char` should be in `vector<char>` or `vector<unsigned char>` not `std::string` or `std::basic_string<unsigned char>`.  SL.con.2 seems clear and correct. Maybe SL.str.1 could be clarified to say it is talking about _textual_ character sequences, so it is consistent with SL.con.2

**Comment by Epholys** [comment]
I see the difference now, thank you. I was confused by the term "character", as it was different from raw binary data in my mind. Shouldn't we use `std::byte` for this kind of data instead of `unsigned char` ([SL.str.5](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slstr5-use-stdbyte-to-refer-to-byte-values-that-do-not-necessarily-represent-characters)) anyway ?

**Comment by markyin** [comment]
std::byte is defined since C++17. I think it's one of reasons.
But std::byte is better in this case in my point of view

**Comment by AndrewPardoe** [comment]
Thank you for the question. Per our editors' discussion and the discussion above, a `vector<char>` and `string` aren't exactly the same. For example, the `vector` could be an input buffer or a buffer used for storage during some iterative operation.
