### ISSUE TITLE
C.49 needs better example

### ISSUE THREAD

**Issue by rmasp98** [isocpp/CppCoreGuidelines#1085]
C.49's good example is the same what was defined as a bad example in C.45. Your good examples should not contradict your own rules

**Comment by xtofl** [comment]
For easy reference: 
[c.45](/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-default): Don't define a default constructor that only initializes data members; use member initializers instead
[c.49](/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-initialize): Prefer initialization to assignment in constructors

**Comment by jwakely** [comment]
Agreed. We could just put /* ... */ in the default constructor in the C.49 example, suggesting it does something _other_ than simply initialize the member. Or we could add a "better" example that follows C.45, with a cross-reference.

**Comment by xtofl** [comment]
Would

```
class X {
    string s;
public:
    X(string n) :s{n} { } // GOOD
    // ...
};
```

Be a better 'good' example?

**Comment by jwakely** [comment]
Yes, that works too. The `B` example should be changed similarly.

**Comment by AndrewPardoe** [comment]
Thank you for the suggestions! We agree, especially with the sample provided by @xtofl. @rmasp98, could you please prepare a PR?

**Comment by rmasp98** [comment]
Done! (https://github.com/isocpp/CppCoreGuidelines/pull/1092)

**Comment by beinhaerter** [comment]
The PR #1092 was merged and closed, so shouldn't this issue be closed, too?
