### ISSUE TITLE
Size inicialize std::vector -  confusing modern inicialization syntacs

### ISSUE THREAD

**Issue by steakhal** [isocpp/CppCoreGuidelines#1089]
I've not found any guidelines for inicializing `std::vector` with a given size.

There is the **curly braced constructor** which does the work, but what if the `value_type` is `T = int`.
And an eager co-worker sees the curly braces and refactors the line in sense of using the **'modern inicialization syntacs'**. In that case the **it will lead to a bug**.

My question is, what is the idiomatic solution for a generic non-ambiguous inicialization of a `std::vector` with a given size.

I'm considering two ways currently:
1. Using the simple **curly braced constructor** the `std::vector`.
2. Splitting into **two statements**, to **default construct** and **resize** right after it.

None of these seems to be a good solution. Please let me know, what is the 'way' to do this.

Thanks.

[Example: ](https://godbolt.org/g/My7K5y)
```c++
int size_ctor() {
  std::vector<int> v(13);  // =/= std::vector<int> v{ 13 };
  return v.size();  // 13
}

int default_ctor_and_reserve() {
  std::vector<int> v;
  v.resize(13);
  return v.size();  // 13
}

int modern_size_ctor() {
  std::vector<int> v{ 13 };
  return v.size();  // 1
}
```

**Comment by BjarneStroustrup** [comment]
comment added in the standard-library sections about vector
