### ISSUE TITLE
Statement about Markdown format

### ISSUE THREAD

**Issue by NicolBolas** [isocpp/CppCoreGuidelines#109]
Markdown has a number of dialects to it, and it seems that the .md files in this archive are built around the specific extensions made by GitHub. That's fine, but there should be a statement somewhere that these files use GitHub's Markdown dialect.

I mention this because I tried to format it with [Pandoc](http://pandoc.org/), and the headers didn't come out well at all. I'd prefer that some formatting work be done to make it work, but I recognize that supporting different Markdown formatters is probably not on the top of your priority list.

**Comment by blakehawkins** [comment]
Pandoc has pretty sub-par support for markdown though, for example `inline code` just doesn't work.

**Comment by NicolBolas** [comment]
I don't know. I've been using Pandoc for a while now, and I haven't noticed any problems with inline code. Even files from this repo format OK, in terms of inline code markup.

The main thing Pandoc has a problem with in these Markdown files are headings of the form: `## In.aims: Aims`. It has no idea what to do with the `In.aims` part, and it doesn't even see them as proper headings.

**Comment by blakehawkins** [comment]
> I don't know. I've been using Pandoc for a while now, and I haven't noticed any problems with inline code. Even files from this repo format OK, in terms of inline code markup.

Sorry, I should have asked - what target format are you primarily using pandoc for?

Markdown to PDF is what I assumed.

**Comment by octoploid** [comment]
You need to use `-f markdown-blank_before_header`  to render the headers correctly.
See https://github.com/isocpp/CppCoreGuidelines/issues/23 for an example.

**Comment by AndrewPardoe** [comment]
We do want this to be portable but will document which flavor of MarkDown we are using.

**Comment by NicolBolas** [comment]
Thanks for the `-f markdown-blank_before_header` notation. It might be good to have items like that noted in the README or a similar bit of documentation.

**Comment by hsutter** [comment]
Added FAQ.10 to document that we are (not yet consistently) using CommonMark plus `<a>` HTML anchors, and considering GFM tables and fenced code blocks.
