### ISSUE TITLE
Enum.4 example:  use explicit constructor cast instead of static_cast

### ISSUE THREAD

**Issue by ksdd** [isocpp/CppCoreGuidelines#1090]
Instead of 
`d = (d == Day::sun) ? Day::mon : static_cast<Day>(static_cast<int>(d)+1);`
one may use
`(d == Day::sun) ? Day::mon : Day(int(d)+1);`
which is also explicit, but not that ugly.

**Comment by AndrewPardoe** [comment]
The guidelines suggest the opposite of what you're suggesting: please see rule ES.49 where the guidelines specifically call out functional casts. Thank you, but we're closing this issue.
