### ISSUE TITLE
ES.107: Don't use unsigned for subscripts, bad example good?

### ISSUE THREAD

**Issue by ChrisGuzak** [isocpp/CppCoreGuidelines#1098]
the first example uses "int", so it seems to follow the guideline. the last uses "auto i = 0;" and that, I believe is signed too. only the second one seems clearly wrong.

**Comment by jwakely** [comment]
> the first example uses "int", so it seems to follow the guideline.

The comments explain the problem. The first and last ones mix signed (the `int`) and unsigned (the vector's `size_type`).

**Comment by ChrisGuzak** [comment]
got it. but isn't that the domain of "ES.100: Don't mix signed and unsigned arithmetic"? It does not seem appropriate to expand the scope of ES.107.

**Comment by gdr-at-ms** [comment]
@ChrisGuzak You are right.

**Comment by AndrewPardoe** [comment]
Our recommendation is to move the first example from ES.107 to ES.100 as you suggest. Thanks!

`unsigned` and subscripting/indexing is always difficult. And while we might want an `index` type, it's not something we should design on the fly. And there are security concerns to consider: adding type conversions wouldn't help to make code more secure.

**Comment by AndrewPardoe** [comment]
@gdr-at-ms, could you please fix ES.100 and ES.107?

**Comment by hsutter** [comment]
Re the initial question: There's also a problem with the size of `int` (explicitly or via `auto`) which may not be big enough for large containers.
