### ISSUE TITLE
Should there be a Guideline to not use `string` as a parameter?

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#1101]
Instead, prefer `string_view`, `span<char>`, etc? See PR #1092. 

Some people recommend that developers pass a string by value followed by move. This may be too clever, but it offers a little bit of advantage.

**Comment by BjarneStroustrup** [comment]
Is "SL.str: String" https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#slstr-string explicit enough? If not what and where?

**Comment by BjarneStroustrup** [comment]
Added a reference to SL.std
