### ISSUE TITLE
Question on contributions to section: NL: Naming and layout rules

### ISSUE THREAD

**Issue by nick42** [isocpp/CppCoreGuidelines#1104]
As noted, this is bound to be one of the more contentious sections, and as such, is one of the only sections where I personally have substantial disagreements with the suggestions. To that end, I think it could be better constructed, but I was wondering to what intent contributions to that end are desired.

To wit, to my mind, there are two logical areas here, which are currently co-mingled:
- Syntax suggestions which are relatively standard in modern code and/or uncontroversial good advice (eg: NL.1, NL,2, NL.26, etc.)
- Suggestions which are very arbitrary, not a consensus, are minimally justified, and for which there are valid arguments against (eg: NL.5 (especially), NL.7, NL.10, NL.15, etc.)

I feel like this section could be split into two sections, one for uncontroversial general advise, and one for personal opinions. The latter section could then be expanded, perhaps in linked documents, for multiple opinions, each with justifications. I feel like stating an unjustified opinion as advice, in a document where everything else is fairly well accepted as good advise, really undermines the intent of the guidelines on the whole.

Anyway, I'm curious if input in this area is desired, or if the advise "is what it is", based on the opinions of the people who wrote it.

**Comment by Wolf-at-SO** [comment]
I had a look on NL.5 and found it very questionable, although I don't like types encoded in names (if it doesn't add value to using the named entities). The first "bad" example misses occasions where a visible type affinity absolutely makes sense: for instance `asString` or `asInteger` for accessing variant types come to my mind. And the next "code" snippet seems not even to be C++:

    printS  // print a std::string
    prints  // print a C-style string
    printi  // print an int

Also the (repetitive) *is evil* and *is not not evil* statements seem just arrogant to me.

Without reasonable justification and without realistic examples, NL.5 seems intolerable to me.

**Comment by blakehawkins** [comment]
Link to NL.5 for convenience:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-name-type

I agree with the categorical argument that these suggestions don't fit well with the rest of the document. 

On the other hand, I think the style suggestions are otherwise mostly non-contentious.

**Comment by Wolf-at-SO** [comment]
I'd suggest to change the NL.5 title to something like ***Encode type information in names only when necessary*** for two reasons:
1. positive formulations are psychologically better in leading people
2. there are reasons for encoding types in names, but they are really rare

The Hungarian approach is of course bad in this sense: it teaches thoughtless inclusion of type information in names.

**Comment by nick42** [comment]
Personally, I think one could make a reasonable counter-argument, wrt type information in [variable] names (inclusive on Hungarian notation, and even notwithstanding consistency with the large amount of code written with type information in names as the existing convention, which would suggest using it per the initial overarching guideline of the section).

To wit, with modern C++ and the 'auto' keyword, there is an increasing amount of type inference in language constructs, which leads to increasing frequency of instances where variable type information isn't implicitly obvious from code. In these instances, it can decrease the cognitive burden of parsing if [high level] type information is implicitly available in the variable name; for instance, it's easy to tell the [logical] difference between these resulting values (assuming a consistent type encoding convention):
```
auto nValue = object.GetNumericValue();
auto sValue = object.GetStringValue();
auto oValue = object.GetObjectValue();
// etc.
```

Now obviously, you won't always have type information in the function/method names, and in fact that would generally be discouraged. So real code is more likely to look like this:
```
auto error_info = object.GetErrorInfo();
// or...
auto oErrorInfo = object.GetErrorInfo();

auto error = object.GetError();
// or...
auto sError = object.GetError();
```

In the above case(s), which case is easier to understand the type of the result of the method? Might you assume the result of `GetErrorInfo()` was a string? A numeric code? Do you need to rely on a [heavy-weight] IDE to tell you the type, with a manual hover-over, and wait for parse/update? How do you know the result type of `GetError()`? Did you need to wait for your IDE to tell you as you were reading through the code, or could you just implicitly know it based on the code itself (ie: following NL.1)? Should you generally avoid using `auto`, because you want to make parsing the code easier, but you're not allowed to encode type information in variable names?

To be clear, I'm not saying that's the *best* way to write code. I am saying that there are reasonable, logical arguments for writing code this way, and guidelines which do not at least acknowledge this seem like just arbitrary, unjustified, one-sided opinion pieces (or worse, subtle advertisements for tools to overcome purposeful defects in coding style).

And really, the point of the original question was: is an update to this effect (to expound on counter-arguments and other opinions) actually desired, or is this document just intended to be arbitrary non-consensus opinions? Cause if it's the latter, there's no point in debating anything, and we can all just move on.

**Comment by hsutter** [comment]
> Suggestions which are very arbitrary, not a consensus, are minimally justified, and for which there are valid arguments against (eg: NL.5 (especially), ...

I think that's a great counterexample -- I actually think NL.5 is one of the least controversial ones, that has the strongest consensus, of the NL.* guidelines. So at least this is an example that I don't think we can successfully call some of these as 'clearly' less controversial than others; different people will almost certainly give different and conflicting lists of the ones they think are controversial. Which... is kind of the point of the section intro.

By the way the section exists because of user demand: We do know they're contentious, but we keep being asked for suggestions by people who don't have conventions. They would rather see ours than invent their own.

**Comment by nick42** [comment]
FWIW, as I suggested originally, I personally think a better approach would be to expand this section a little (and/or other sections which might be contentious), and allow formulated a reasoned arguments for different approaches as linked reference pages.

I think the idea of having a consistent style is more/less not contentious, and that is encapsulated well in the intro. I also think there's certainly merit in providing some "suggested style" guidelines, for people/groups which do not already have a settled style. The only part I don't like about NL.5, in particular, is that it seems arbitrary and without justification, at least in the guidelines. Given that [many] people have other styles, and many with well-supported justifications, it would seem better to provide a few examples with justifications, rather than just picking one.

I singled out NL.5 because 1) there's some very obvious subjective bias (ie: "Hungarian is evil"), and 2) you can have type information in variable names based on logical type, which would still satisfy the Rationale given for precluding it (see my above hypothetical, where for example the specific string implementation type is unspecified). It just seems to me that, at the least, if the guidelines are going to recommend an approach, it should be reasonably objective and justified, and/or alternatives should be presented. My 2c, anyway.

**Comment by nick42** [comment]
Also, lest this be seen as just complaining without being constructive, I'd be happy to draft an alternative version of NL5 as an example, if that would be desired by anyone. My original inquiry was about whether this would be desired or not; if it's not "set in stone", I can provide something alternative for comparison.

**Comment by jwakely** [comment]
Arguably it's better not to try and justify the material in that section. If you just want to be told a style to use, that section is for you. If you aren't happy taking it on trust and want rationale, there are better places to find it than these guidelines.

**Comment by nick42** [comment]
> Arguably it's better not to try and justify the material in that section. If you just want to be told a style to use, that section is for you. If you aren't happy taking it on trust and want rationale, there are better places to find it than these guidelines. Adding extra justification just invites people to argue about it, and wastes everybody's time. I think simply saying "these are presented as-is, take them or leave them, but please don't try to argue about them" might be better.

The counter-argument to that approach is that presenting a controversial opinion without apparent justification undermines the entire point of having guidelines in the first place. To wit, if the proposition is that the guidelines represent "best practices", and they are perceived as arbitrary and not necessarily best practices, that undermines the credibility of the rest of the document (most of which is much less controversial).

That goes back to my other suggestion: these might be better in linked documents, where there can be a clearer demarcation between what "we suggest you do this as a best practice", and "this is one possible approach, without comment on how good/justified it is".

Part of that decision also touches on the desired intent of the guidelines; that is, broad adoption or niche usage. For the former, you'd generally want to stick to only generally accepted "best practices", while in the latter case you could pick an arbitrary standard (as many organizations have already done). I was under the impression the intent was the former, but admittedly that might be inaccurate.

**Comment by jwakely** [comment]
> that undermines the credibility of the rest of the document (most of which is much less controversial).

The rest of the document doesn't have an intro saying "We present a set of rules that you might use if you have no better ideas, but the real aim is consistency, rather than any particular rule set."

Whatever, I'm not going to waste any more time here.

**Comment by hsutter** [comment]
I've decided to merge the suggestions above: I'll rename the item to "Avoid..." and refresh the text a little because we really do believe it's broadly uncontroversial that Hungarian is actively harmful, and generally unnecessary in a language with strong class types, and I think those words are clearer and less controversial than "evil."

**Comment by nick42** [comment]
If I may make some general suggestions, re text refresh, and interject my opinions (for whatever that's worth):

- Type information in method/function names should generally be avoided, unless the method/function name is specific to a type and might likely be confused.

- If type information is encoded in names, try to make the type information logical, rather than specific. For example:
`print_int(); // bad`
`print_number(); // less bad`

- Consider the above also for variables; that is, if you want to encode type information, do it in a general and concise manner.
`int iValue; // bad`
`int nValue; // less bad`
`std::string stdstringValue; // bad`
`std::string sValue; // less bad`
- Note: Encoded type information which is general/logical, rather than specific, allows changing the underlying type to better address the intent without rewriting the usage code. For example, changing `nValue` from `int` to `long long` does not necessarily require any usage changes.
- Note: It is considered by many to be unnecessary in a strongly typed language to encode type information in variables, but depending on uniform IDE usage and consistency, this can aid in code readability and comprehension.

- A convention to distinguish variable scope is not a bad thing; as with the general guidelines, aim for consistency. By way of example:
`m_nValue // <~ this is a member variable of numeric value`
`g_nValue // <~ this is a global variable of numeric value`
`nValue // <~ this is a scope-local variable of numeric value`
`pnValue // <~ this is a pointer to a numeric value`

- Try to craft variable and function names to be as specific to the intent as possible, while still being concise.
`user // <~ bad; what is that variable/type?`
`sUserName // <~ less bad; string of the user's name`
`user_name_for_current_user_in_domain_qualified_format_as_std_string` // <~ bad again; likely way too verbose for context, and also still too in-specific`

-----

That's my 2c anyway; take/use from it however much you want (likely none, admittedly, although it felt cathartic to write out what I consider to be a "good" way to write code).

**Comment by hsutter** [comment]
I incorporated some examples like those, though not all of them. Thanks!

**Comment by nick42** [comment]
For enough; it's certainly better now, IMHO. :)
