### ISSUE TITLE
in cpplint a compound literal in return statement gives readability/brace warning

### ISSUE THREAD

**Issue by alpo** [isocpp/CppCoreGuidelines#1112]
## Actions:

Check with cpplint a source code with 2 fragments:

1:
```c
return (SomeType){.some_field = some_value};
```

2:
```c
SomeType x = (SomeType){.some_field = some_value};
return x;
```

## Expected result: 

Cpplint will not emit the message "You don't need a ; after a }  [readability/braces]" in both cases

## Actual result:

Cpplint emits the warning in the 1st case.

## Suggestion:

Add "return" statement to the line prefixes blocking this warning for compound literals.

**Comment by alpo** [comment]
https://github.com/isocpp/CppCoreGuidelines/pull/1113

**Comment by cubbimew** [comment]
Good idea, though a simple `return {a, b};` for a function returning an `std::pair` or tuple etc makes a more convincing motivation demo.

**Comment by GabrielDosReis** [comment]
Note that there is no compound literals in C++.  The notation `(SomeType){.some_field = some_value}` is C.
