### ISSUE TITLE
Early invoke for gsl::finally (or gsl::final_act)

### ISSUE THREAD

**Issue by adishavit** [isocpp/CppCoreGuidelines#1118]
The `gsl::final_act` class has a `dismiss()` method to prevent invoking the cleanup code upon dtor.
What I'd like to have is another method for _early invocation_ of the cleanup code _before_ the dtor.

In many cases, I can put my object in a braced scope and let the dtor run. This is fine and also prevents name pollution for later code. 
However, I have some code that (typical in COM APIs):

1. Creates resource R1;
2. Uses R1 it to create resource R2;
3. Releases R1 as is it no longer needed 
 (we don't want to keep it around until the end as it consumes e.g. memory);
4. Proceeds to use R2 to create R3...

In this case, in order to keep R1 in its own scope, I need to define R2 outside this scope (with some not-always possible) default initialization, just דo it can outlive R1. This is ugly and not always possible.

Alternatively, I'd have to create many nested scopes or abuse IIFE for forcing dtors and using elision to return R2. This is again ugly creating a lot of unnecessary bloat.

With an early release method, the code can remain serial, with the drawback that the user must know not to use the cleaned-up resource after the early release.

**Comment by ChrisGuzak** [comment]
resources (com interface pointers in your example) should use an RAII class to manage lifetimes and given that your example is satisfied, null out the smart pointer to free the resource. 

I'm not familiar with gsl::final_act, but it sounds similar to a design I am, wil::scope_exit. Analysis of our code base found this is often mis-used, using it for resource management when RAII should be used instead. That reduces the scenarios where final_act would be used and makes this missing feature less problematic.

**Comment by adishavit** [comment]
The point is that when one is using an existing 3rd party C API, creating RAII wrappers for all the 3rd party resource types is way beyond what can be expected from a typical user.
`gsl::final_act` gives you an _ad-hoc_, inline solution that promotes type, resource and exception safety with little extra boilerplate code.

This is analogous to using Comparator function objects pre-lambdas. 
It was possible but way more messy.

**Comment by jwakely** [comment]
> creating RAII wrappers for all the 3rd party resource types is way beyond what can be expected from a typical user.

Then they should be using `unique_ptr` instead of creating their own.

**Comment by adishavit** [comment]
Who is "they"? 
`unique_ptr` requires a deleter as part of the type so if you want to use a lambda you have to pre-declare it to use it once with `decltype` and once in the ctor (unless there are deduction guides... hmm).

**Comment by jwakely** [comment]
> Who is "they"?

The typical user you referred to (that's why I quoted that part of your comment).

> so if you want to use a lambda you have to pre-declare it to use it once with decltype and once in the ctor

So don't use a lambda then. Unless you're suggesting you have 3rd party resource types that can only be destroyed by lambdas, which seems unlikely. Your 3rd party API will have functions to free the resources. Even if you want to use a lambda to do some extra work around that function, you can usually use a function pointer as the deleter for `unique_ptr`, and convert a lambda to a function pointer (as long as it has no captures)

**Comment by adishavit** [comment]
FWIW, there are APIs that you need to wrap the supplied lambda.  
For example, in the OpenCV C API: [`void cvReleaseImage(IplImage ** image)`](https://docs.opencv.org/master/d2/df8/group__core__c.html#ga6d14201d7658e0e757398b102da0c959) takes a double `**`. It may be bad design, but that's the API. In this case lambdas make it easy to wrap.  

But I feel like we kind of strayed from the discussion about early `final_act` release.
If this is not the right usage for `finally` but the recommendation is to use `unique_ptr<>` instead, then the guidelines should explain this and the distinction.

Incidentally, I just wrote up a very rough initial draft exactly about these issues.  
@jwakely, your feedback would be very welcome.

**Comment by neilmacintosh** [comment]
@adishavit `gsl::final_action` had a `dismiss()` method added as an experiment. You'll note this method is not mentioned in the Guidelines. This method has exactly the drawback you identify - it actually complicates understanding the resource management being done by `final_action`. It is likely to be removed from the GSL implementation in the near future. So we won't be adding an early release method to its interface either.

I think the key point - which the Guidelines make repeatedly in context of `finally()` and `final_action` - is that you should prefer to write your own classes that follow the RAII idiom. `final_action` is designed really only as a quick-fix or pain-reducer and is not meant to be a general solution.

`unique_ptr` with custom deleters is certainly one option for doing resource management. So is writing one or more template classes that reflect the specific shape/needs of the legacy APIs you are dealing with.
