### ISSUE TITLE
Suggestion: E.32: catch without ellipsis from well-specified functions

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#1122]
# E.32: catch without ellipsis from well-specified functions

## Reason

STL functions is well-specified, both in terms of behaviour and exceptions thrown. Catch those exceptions, or catch their base class `std::exception`. Using ellipsis misleads in thinking that anything may happen. This may be the case in the `main` function of a bigger program.

## Example

```c++
//Good: handle both exceptions
const std::string s{/* anything */};
try {
  const int i{std::stoi(s)};
  // do something with i
}
catch (const std::invalid_argument&) {
  // handle invalid argument
}
catch (const std::out_of_range&) {
  // handle out of range
}
```

```c++
//Good: handle base class of both exceptions
const std::string s{/* anything */};
try {
  const int i{std::stoi(s)};
  // do something with i
}
catch (const std::exception&) {
  // handle both exceptions
}
```

```c++
//Bad: handle anything that may happen, where 'anything that may happen' is well specified 
const std::string s{/* anything */};
try {
  const int i{std::stoi(s)};
  // do something with i
}
catch (...) {
  // handle anything that may happen
}
```

```c++
//Good: anything may happen
int main() 
{
  try {
    do_complex_things();
  }
  catch (...) {
    // handle anything that may happen
  }
}
```

## Exceptions

None

## Enforcement

None

## See also

None

## Notes

None

## Discussion

None

## References

None

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, the majority of code should be exception-neutral, just catching `...` and rethrowing. With regards to this particular suggested rule, we believe it's dangerous to assume that you can know every exception that might happen. Also, this approach doesn't always scale if you have template functions. You can't always assume that exceptions derive from `std::exception`. 

There's a much bigger issue here about when to use error codes, when to use exceptions, and when to use something terminating such as a contract.  I've created #1133 for Herb to work on this. 

Thank you for the suggestion regardless!
