### ISSUE TITLE
When to/not to use nested classes and rules for nested classes

### ISSUE THREAD

**Issue by nathanowen42** [isocpp/CppCoreGuidelines#1128]
Maybe I am blind but I cannot find any explicit guidelines for nested classes.   There are rules that would apply to these classes in the "Classes and class hierarchies" section but no explicit mentions of nested classes.

I would like to see:
- When to use nested classes
- When not to use nested classes
- Rules to follow when using nested classes

**Comment by jwakely** [comment]
> Our initial set of rules emphasizes safety (of various forms) and simplicity. 

I am not aware of any safety issues regarding the use of nested classes. Use them or don't use them, it's not likely to cause serious problems either way.

IMHO the guidelines are not supposed to be a complete guide to software design in C++, because adding material on every conceivable topic will make it harder to focus on the important safety issues (harder both for readers and the authors of the guidelines).

**Comment by nathanowen42** [comment]
Fair enough.  Guess I was just hoping for more of a decision tree for suggesting which design paradigm to use in what situation to avoid over-complexity and/or code which is difficult to understand and/or reuse.

For example, if I have a class which contains a queue would it be considered appropriate to make a subclass that extends/inherits[occurs to me that I don't know the correct word to use here so please inform] or contains a (as in the example below, which clearly does not use inheritance) std::dequeue and then make a second class that extends or contains a std::string for each node?
```
class very_important_class_that_has_a_hidden_queue
{
    public:
        ...
    private:
        class node_impl
        {
            public:
                node_impl( std::string data );
                std::string get_data();
                ...
            private:
                std::string data;
        }

        class queue_impl
        {
            public:
                void add_element( std::string data );
                std::string getNext();
                ...
            private:
                std::queue<node_impl> the_real_queue;
            
        }    

        queue_impl my_queue;  
        ...
}
```
Then rather than giving the encapsulating class [the class which owns the nested classes] functions that operate on the queue, you could give these operations to the queue subclass, and instead of giving the encapsulating function functions that operate on a node you could give these to the node subclass.

You could also make the queue subclass own the node subclass so that the node subclass cannot even be seen by its owner.
```
class very_important_class_that_has_a_hidden_queue
{
    public:
        ...
    private:

        class queue_impl
        {
            public:
                void add_element( std::string data );
                int handle_next();
                ...
            private:

                class node_impl
                {
                    public:
                        node_impl( std::string data );
                        std::string get_data();
                        ...data type specific access functions...
                        ...
                    private:
                        std::string data;
                }

                std::queue<node_impl> the_real_queue;
            
        }    

        queue_impl my_queue;  

        ...
}
```
By the end of all this you have spent 3 hours "optimizing" [more like adding a bunch of (overly complex?) access control] your code for no reason and have probably ended up with less optimal code than if you had just made the queue a std::dequeue<std::string> and added all the knowledge to the encapsulating class.  Then you start second guessing yourself and after countless more hours of research and contemplation you finally resort to asking the C++ standards committee for there opinion because there is no guidance in the C++ Core Guidelines.  I mean clearly someone that over thinks to that degree is a lost-cause [their probably also the type of person who second guesses every sentence and has to add clarification notes] but you get the idea...

So while I agree that this may not be safety related [and thus, depending on the desired scope, may not be needed in the core guidelines], it seems to me like this could be a useful point of discussion.  Though perhaps this is the wrong place for such guidelines [not sure].

**Comment by jwakely** [comment]
If the types are purely internal implementation details of your class then it makes perfect sense for them to be private to that class, rather than declared at namespace scope. And the same logic applies for the node, if it's purely internal to the queue class, it makes sense for it to be nested in the queue class. If it's not needed at an outer scope, why define it there?

But this is the wrong place to ask such questions, e.g. https://codereview.stackexchange.com/

(Also, it's `deque` not `dequeue`, it's pronounced like "deck")

**Comment by jwakely** [comment]
This can be seen as a form of [C.9: Minimize exposure of members](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-private)

**Comment by nathanowen42** [comment]
Fair enough, thanks for your help.  I suppose it is a bit much to ask to have explicit usage recommendations for every type/paradigm, that is included in the standard, in the *Core* [non-comprehensive] Guidelines.  Also occurs to me that a pronunciation guide would be useful for those of us who are largely self taught (still urgs me that they largely still only teach Java in University and what C++ they do teach is not Modern) though a pronunciation guide does not seem like something that should be in the Guidelines.

**Comment by jwakely** [comment]
See footnote 1 at https://web.archive.org/web/20170922193812/http://www.sgi.com/tech/stl/Deque.html#1
