### ISSUE TITLE
Mention strong typedefs in I.4 "Make interfaces precisely and strongly typed"

### ISSUE THREAD

**Issue by allopislozano** [isocpp/CppCoreGuidelines#1136]
I think it would be helpful to add the notion of strong typedefs to this item of the guidelines, e.g having a class TypedIndex that wraps int  so that we  can do:

using Row = TypedIndex<>
using Column = TypedIndex<> 

getItem(Row const & row, Column const & column)   instead of 
getItem(int const & row, int const & column) 

and in this way we can have clearer table interfaces that wouldn't allow us to pass in a row where a column is needed

**Comment by viboes** [comment]
I don't know if your are mixing strong types and named parameters.
BTW the two types you showed are the same :(

**Comment by allopislozano** [comment]
I don't think I'm mixing ... I do mean strong types as a way to distinguish types that really are the same but we want to make a compiler enforced distinction between them. My proposed implementation was wrong, as you correctly point out, but I think my point still makes sense. Should be something like
BOOST_STRONG_TYPEDEF( Row, size_t);
BOOST_STRONG_TYPEDEF( Column, size_t);

I think there is a proposal for including strong typedefs as well in the standard.

**Comment by xtofl** [comment]
We actually found three severe bugs in some gpu code we wrote by 'just' using exactly this technique.  It is more than just named params.  You cannot add a column number to a row number without consideration, and here the compiler will draw your attention to that.

**Comment by viboes** [comment]
@xtofl You are right, columns number and row numbers don't mix well most of the time. I don't know why I associated them to named parameters. BTW, how many things share columns numbers and row numbers?

@allopislozano Anyway, we need much more than BOOST_STRONG_TYPEDEF if you want to add columns or rows. And even much more to add some guidelines. 

Defining basic strong types is not complex (other than choosing the good operations) but it is cumbersome. Defining complete strong types is much complex. Been able to derive operations from the underlying types helps, but no one has a concrete proposal that has consensus yet. So while I agree we need strong types, we need a way to define them simply and productive. I don't see what the guideline could say today without having a concrete solution to the problem that is applicable to a lot of cases. 

When I define strong types I tend to use CRTP mixins but this seems to be too complex for most of the C++ developers and having reusable mixins grouping some operations is not so simple, there is always a specific case that prevents you from using a specific mixin. At the end you finish by an almost flat strong types or adding more specific mixins which takes more time than you wanted to spend for their development. Take for example the difficulty of chrono::duration or just std::pair, a counter, money, units, address/offset, ...   There are others as identifier, day, month, weekday that look much simpler, but if you take a look at the proposed Date library you will see that it is not so simple.

**Comment by AndrewPardoe** [comment]
We brought up in our editor's sync that this issue has been discussed for 40 years. People have never been able to design strong typedefs perfectly. Might we suggest that this is more fitting as a Standards proposal than as an idea driven through these Guidelines?
