### ISSUE TITLE
ES.20 "Always initialize an object": = 0 is good but = uninit is bad?

### ISSUE THREAD

**Issue by stbergmann** [isocpp/CppCoreGuidelines#1137]
<https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-always> "ES.20: Always initialize an object" has one example
```
int i2 = 0;   // better
// ...
cin >> i;
```
arguing that initialization by 0 is good (or at least "better"), followed by an example
```
widget i = uninit;  // bad
widget j = uninit;

// ...
use(i);         // possibly used before set
// ...
```
arguing that initialization by a "sentinel value" is bad because "the compiler cannot even simply detect a used-before-set."
But the compiler can't in the first example, either.  How is the "useless" initialization in the first example qualitatively different from that in the second one?  (In my opinion, any such initialization is not a good solution, as it defeats tooling that detects usage of uninitialized values---them being the best approximation to bottom that C++ can offer, it seems...)

**Comment by BjarneStroustrup** [comment]
clarified
