### ISSUE TITLE
guidance on uniform initialization desired

### ISSUE THREAD

**Issue by binarycrusader** [isocpp/CppCoreGuidelines#1140]
There are a variety of opinions and comments that have been posted about uniform initialization:

https://herbsutter.com/2013/05/09/gotw-1-solution/
https://herbsutter.com/2011/10/28/elements-of-modern-c-style/
https://herbsutter.com/2011/10/28/elements-of-modern-c-style/#comment-4266
http://scottmeyers.blogspot.com/2015/09/thoughts-on-vagaries-of-c-initialization.html

...and even hints about it in the Core Guidelines:

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#Rc-in-class-initializer

From what I can gather so far, brace-style initialization is generally preferred, except when using auto, or when performing single value assignment for non-POD types.  However, there seems to be little specific guidance specifically around POD types and it doesn't seem to be mentioned directly at all in the current Core Guidelines.

It would be great to get an up-to-date summary of guidance regarding this particular topic in the Core Guidelines if possible.

**Comment by AndrewPardoe** [comment]
We do recommend brace initialization. Vector initialization can use a type tag. `auto` presents difficulties of its own. Also see [N3922](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3922.html).

@BjarneStroustrup, can you please write this up for the Guidelines?

**Comment by suncho** [comment]
Is this more a matter of style than anything else?  I prefer to use copy initialization whenever possible.  I also avoid using braced initialization except when initializing aggregates.

I find this style to be more readable to people familiar with C and with older C++ code.  Is there any good reason why I shouldn't be doing this?

**Comment by binarycrusader** [comment]
I happened to stumble on this relevant guidance in the guide today which I missed because it doesn't refer to it using the terminology "uniform":

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-list

**Comment by BjarneStroustrup** [comment]
clarified (and you can now search for "uniform")
