### ISSUE TITLE
Checks for `p == nullptr` in examples is against recommendation in ES.87

### ISSUE THREAD

**Issue by TobiasMende** [isocpp/CppCoreGuidelines#1142]
I have seen many examples in the core guidelines that use the `p == nullptr` style to check for null pointers. May I suggest to use the `!p` for these examples as this is the recommended form according to **ES.87**?

If so I would be happy to provide a pull request for this change.

**Comment by jwakely** [comment]
I think a pull request to fix those cases to follow ES.87 would be good, please go ahead. Thanks!

**Comment by TobiasMende** [comment]
I made these changes in PR #1144
