### ISSUE TITLE
Header file name convention

### ISSUE THREAD

**Issue by fekir** [isocpp/CppCoreGuidelines#1153]
Hello,

I noticed that `SF.1` proposes to use `.h`, since it is a longstanding convention, for header files.

I know a lot of projects that follow that convention, but I'm convinced that using another file extension would be better.

I would like to propose to use `.hpp` since it unambiguously identifies it as C++ interface, and to use `.h` if the interface is a  C interface or a C interface that can also be compiled as C++ code.
I think it is important to make a distinction, and using a different naming convention makes it easier to manage project.

External tools, like formatting tool, search tools, static analyzers and so on, can use this information for skipping particular files, and it is also immediately clear that a `.hpp` file should not get included from a `.c` file.

**Comment by jwakely** [comment]
This has already been discussed, please see #686

**Comment by fekir** [comment]
Sorry, completely missed it
