### ISSUE TITLE
ES.23 - "prefer braces" overly-permits explicit conversions

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#1155]
Preferring braces everywhere prevents narrowing conversions:
int i = 7.3;  // bad
int j{7.3};  // yay
(I suspect static-analysis and code-review is sufficient to catch much of that, at least in some environments.)

However, it also *allows* the much larger class of dangerous conversions: those that are tagged explicit
https://godbolt.org/g/97kboZ

Braces everywhere probably makes sense in generics (although hopefully concepts restricts that enough to not need that?) Relying on it everywhere also means that there is no trace left at the call site when performing a maybe-dangerous explicit conversion between types that have a different essence. 

See [abseil.io/tips/142](https://abseil.io/tips/142) and [abseil.io/tips/88](https://abseil.io/tips/88) for long-form details?

**Comment by jdennett** [comment]
For the double-to-int case there's the strange copy-brace-initialization syntax
`int i = {7.3};`
which uses braces but not direct initialization.  I don't expect to see much use of that, and in particular it's not going to be used by default, so it won't catch most accidents.

**Comment by BjarneStroustrup** [comment]
I have clarified a bit, but I think e have to agree to disagree on this (unless you have changed your mind or have new arguments for me)
