### ISSUE TITLE
PDF or HTML target for Makefile

### ISSUE THREAD

**Issue by mabkenar** [isocpp/CppCoreGuidelines#1159]
Right now, the makefile only generates two text output files: `plain.txt` and `plain-nohtml.txt` (or am I missing something?). It would be nice if the makefile could generate formatted PDF or HTML outputs that looked like a proper book.

**Comment by hsutter** [comment]
There is a [rendered version here](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines).
