### ISSUE TITLE
Guideline I.16 is partially checkable in many configurations.

### ISSUE THREAD

**Issue by sstewartgallus** [isocpp/CppCoreGuidelines#116]
With Microsoft's compiler the annotation extension  `__declspec(dllexport)` can be used and with the GCC compiler (and many other compilers) the annotation extension `__attribute__ ((visibility ("default"))` (if the compiler option `-fvisibility` is set to `hidden`) it is possible to explicitly mark which symbols should be exported from a shared library. Such marked symbols could be checked to see if they are primitive and C like. Note that C++ and its vague linkage entities have weird interactions with the `-fvisibility` option though. Note also that generalized attribute syntax can be used for GCC's visibility's annotation syntax at least I think.

**Comment by neilmacintosh** [comment]
@sstewartgallus , you are correct, there are certainly platform-specific ways that exported symbols can be identified and checked. A checker for the Guidelines on a particular platform could definitely take advantage of those to try and offer a better "quality of implementation" for users.
