### ISSUE TITLE
new SF guideline, "header files should include the other headers they depend on"

### ISSUE THREAD

**Issue by ChrisGuzak** [isocpp/CppCoreGuidelines#1168]
This seems obvious, but I've found myself in this discussion a few times, recently in the context of the Windows SDK header files that have a history of getting this wrong. (wincon.h being a case were we fixed a circular dependency and then violated this guideline in the process).

Should there be a guideline that .h files should include all of the headers that contain the types they depend on (and no more)?

**Comment by jwakely** [comment]
I think this is covered by https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-implicit

**Comment by ChrisGuzak** [comment]
That appears to be about consumers of header files not depending on what those files include to facilitate their implementation. I'm interested in describing what header file authors should do.

**Comment by MikeGitb** [comment]
Dies that allow for forward declarations?

**Comment by jwakely** [comment]
If you don't use the complete type, you don't need to include the definition.

**Comment by AndrewPardoe** [comment]
@ChrisGuzak, this is a great suggestion! We'd love for you to provide a PR with your suggested guidance. This rule should probably be SF.11. Thank you!

**Comment by ChrisGuzak** [comment]
See PR #1181 #1181

**Comment by AndrewPardoe** [comment]
Thank you!
