### ISSUE TITLE
Suppression guidelines

### ISSUE THREAD

**Issue by annagrin** [isocpp/CppCoreGuidelines#1173]
GSL library uses attributes like [[gsl::suppress(type.1)]] to suppress warnings. 

Different compilers require different syntax (clang) or do not recognize them (gcc). This means that using suppress in GSL itself is complicated - not every static analysis tool will be able to suppress them, and we need ifdefs around suppressions to make sure they even compile. 

Currently [[gsl::suppress]] are only recognized by CppCoreCheck. not compilers, which could have some warnings from Cpp Core Guidelines as well (for example, unitialized variables)

Would be great to create a standard suppression mechanism for compiler and static analysis warnings.

**Comment by cubbimew** [comment]
> we need ifdefs around suppressions to make sure they even compile.

Sounds like a compiler bug: [dcl.attr]p6 says [Any attribute-token that is not recognized by the implementation is ignored](http://eel.is/c++draft/dcl.attr#grammar-6.sentence-2)

**Comment by hsutter** [comment]
Thanks Anna, some more context Anna provided separately:

MSVC understands [[gsl::suppress(something.x)]]
Clang understands [[gsl::suppress(“something.x”)]]
GCC doesn't understand them on a line inside a function

**Comment by AndrewPardoe** [comment]
Per our discussion. the core problem is that Clang does recognize this suppression, but expects a different format of the suppression. But it's also an issue that there's not a standard way to suppress diagnostics. 

We don't believe there is a WG21-level issue concerning this syntax. Clang's string format is expressive, but requires tokenization to parse it. MSVC's is tokenized.

**Comment by hsutter** [comment]
Note that this is specified to be quoteless in [In.force](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#inforce-enforcement)

**Comment by daveedvdv** [comment]
A late comment on this.

I'm surprised by the choice of syntax here.  Attribute arguments rely on balanced _token_ sequences. In something like `gsl::suppress(r.10)`, `r.10` is two tokens (`r` and `.10`). Semantically, it has no difference from `gsl::suppress(r.1)`.  Presumably that's why Clang requires a quoted string instead.

**Comment by hsutter** [comment]
Editors call: Thanks! Sorry for the lag -- this has been addressed with #2178.
