### ISSUE TITLE
Rule C.21 should give an example

### ISSUE THREAD

**Issue by randomascii** [isocpp/CppCoreGuidelines#1175]
Rule C.21 seems to assume that people know what the six operators are and the correct syntax for deleting them. This is a dangerous assumption. The rule says:

"If you define or =delete any default operation, define or =delete them all"

but it does not list them all. I had to find an alternate reference to double-check what the functions were. I used this one:

http://www.modernescpp.com/index.php/c-core-guidelines-constructors-assignments-and-desctructors

I think rule C.21 should stand alone. Also, I thought that deleting some of the functions implicitly deleted others, and mentioning that (true or false) seems important.

**Comment by cubbimew** [comment]
Does the pending PR #1152 address this sufficiently?

**Comment by jwakely** [comment]
I've just updated #1152 to add:

The _special member functions_ are the default constructor, copy constructor,
copy assignment operator, move constructor, move assignment operator, and
destructor.

**Comment by randomascii** [comment]
The recently added text made in the comment right above is slightly helpful, but what is really needed is an example that can be cut and pasted. It looks like the pending PR has that, so that is good.

I saw this in the updated text: "Defining only the move operations or only the copy operations would have the same effect here, but stating the intent explicitly for each special member makes it more obvious to the reader"

I appreciate that clarification of the language rules. However I disagree with the implementation of the warning. If deleting just the copy operations is sufficient then the warning should not fire in that case. Forcing developers to add an extra two lines of boilerplate to a flawless class in order to suppress a warning seems like a bad idea.

The warning is a good idea when it warns about missing declarations. It is not a good warning when it enforces redundant declarations. Putting both warnings under the same warning number means I have to choose between being warning clean, disabling a useful warning, and cluttering my code.

**Comment by jwakely** [comment]
> but what is really needed is an example that can be cut and pasted. It looks like the pending PR has that, so that is good.

An example where you have to replace 50% of the words doesn't seem very useful for copy&paste!

> Forcing developers to add an extra two lines of boilerplate to a flawless class in order to suppress a warning seems like a bad idea.

That's precisely what the guideline is about though. Don't rely on your readers to know the subtleties, be explicit about each member.

**Comment by randomascii** [comment]
> An example where you have to replace 50% of the words doesn't seem very useful for copy&paste!

I strongly disagree. I just went through a project resolving these issues and in every case I copied an existing block and then did search/replace for the eight occurrences of the class name. This is much faster and much less error prone than typing it all from scratch. The precise function names and return types and modifiers are not obvious. For many developers they are infrequently used. A template that can be copy/pasted is crucial.

I'm curious as to how you fill in this boilerplate. Do you type the whole thing? Type the copy operators then copy them and add the extra ampersand? I'm genuinely curious. Every option I can think of would be several times longer than copy/paste, replace-eight-times.

**Comment by jwakely** [comment]
> The precise function names and return types and modifiers are not obvious.

I find that surprising, at least for anybody writing C++ regularly. The copy constructor and copy assignment operator and destructor have looked that way for decades, and the move constructor and move assignment operator are just the same with `const X&` changed to `X&&`.

> Type the copy operators then copy them and add the extra ampersand?

Almost. I type out the copy constructor, then copy it and edit it with something like `yypwi& operator=<Esc>ykjp:s/const \(\w*\)/\1\&/ 2<CR>` (Vim commands). I find that far quicker than going to some other file or webpage and finding an example to copy.

**Comment by randomascii** [comment]
The warnings are arguably at their most valuable for users who are not experts, who are infrequent C++ users.

I have definitely seen people forget the 'const' or '&' on the parameters, and a known-good example helps welcome these developers to the C++ club, instead of making them learn these things the hard way. The '&&' syntax is not obvious to users who haven't used C++ for a while.

I can type them from scratch but I dislike doing it. Most of my development is in existing classes so I add new ones rarely, type these four rarely, and have to think about it to be sure I get them right.

**Comment by jwakely** [comment]
> The warnings are arguably at their most valuable for users who are not experts, who are infrequent C++ users.

Which is why I said don't rely on your readers to know the subtleties, be explicit about each member.

**Comment by randomascii** [comment]
> Which is why I said don't rely on your readers to know the subtleties, be explicit about each member.

Fair point. However I still think that it is a mistake to conflate the two warnings that /analyze puts behind one warning number:

Warning a) Due to missing declarations there is nothing to stop your class from copied/moved/assigned and this might cause a double-free which could be really bad.
Warning b) Your class is missing a pair of declarations that are unnecessary but which might make the behavior more obvious.

I'm not saying that these two warnings are not useful. I am suggesting that they are very different. One of the warnings is orders of magnitude more severe than the other. And, if a developer disagrees stylistically with warning b) they have no way to disable it without disabling the indisputably valuable warning a).


I wish that warning a) was a W3 warning, and warning b) was a /analyze warning.

**Comment by AndrewPardoe** [comment]
Thanks for the suggestion! We've merged #1152. Does this address your concerns about the C.21? Your last point seems to concern the tools more than the Guidelines.

**Comment by randomascii** [comment]
> Does this address your concerns about the C.21?

Yep. Looks good.

I do have concerns about the tools which I will share in more detail elsewhere.

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, you do raise a very good point about these warnings. We'll assign this over to Bjarne to see if there's something we can do with the rules that encourage the warnings.

**Comment by BjarneStroustrup** [comment]
I added a note with a warning and a recommedation to rely more on the rule of zero
