### ISSUE TITLE
T.12 "Prefer concept names over auto for local variables" should make some concessions

### ISSUE THREAD

**Issue by alex-weej** [isocpp/CppCoreGuidelines#1180]
Consider this expression:

```c++
frobnicate(thingy + (other - 12) + banana(rama()));
```

It adds useful information to be able to factor out part of this expression and give it a name, without spelling (aka constraining) either a type or a concept:

```c++
auto const numberOfShoes = thingy + (other - 12);
frobnicate(numberOfShoes + banana(rama()));
```

Following T.12 requires that you put a concept, for some reason. I don't understand why this should be required.

```c++
DoYouReallyCare const numberOfShoes = thingy + (other - 12);
frobnicate(numberOfShoes + banana(rama()));
```

**Comment by hsutter** [comment]
Our feeling is that the rule covers enough for now and we don't want to expand it too much until the concepts syntax settles down in the IS.

**Comment by alex-weej** [comment]
My concern is that people may use this rule to justify an opposition to AAA, when the more important thing is giving good, self-documenting names to things. How about a concession in the text? Happy to PR something short.
