### ISSUE TITLE
"C.164: Avoid conversion operators" and explicit

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1185]
C.164 sends different messages.

Suggesting not to use conversion operators at all:
Title: "avoid conversion operators"
Note: "through conversion operators or non-explicit constructors" (mentioning all conversion operators, not only the non-explicit ones)
There is C.46 for explicit conversion ctors, but there is no rule for explicit conversion operators.

Suggesting not to use implicit conversion operators (but maybe explicit):
Reason: "Implicit conversions can [...] often cause surprises"
Note: "Prefer explicitly named conversions"
Note: "Do not introduce implicit conversions"

Do I understand C.146 right that only non-explicit conversion operators are discouraged?
If this is the case then I'd ask if it makes sense to change the title to "avoid implicit conversion operators" and/or to change the note to "through non-explicit conversion operators or non-explicit constructors". Would it even make sense to add a short "Sample, better" showing an explicit conversion operator?

**Comment by BjarneStroustrup** [comment]
Done (with new examples)
