### ISSUE TITLE
NL rules exist to recommend a default style, and should not ban other styles

### ISSUE THREAD

**Issue by hsutter** [isocpp/CppCoreGuidelines#1186]
The NL.* rules are prefaced by saying they are "a set of rules that you might use if you have no better ideas."

However, some of the items have "BAD" code examples and "DON'T" Enforcement clauses that reject code that chooses other styles. That goes beyond the above charter by banning code that happens to make a different naming and layout convention.

The following is a list of "BAD" examples and "DON'T" Enforcements that I recommend removing. The only purely stylistic Enforcements I recommend keeping are the ones that macros, and only macros, should have all-caps names.

### NL.1: Don’t say in comments what can be clearly stated in code

Remove the Enforcement: It just seems snarky and unuseful.

### NL.3: Keep comments crisp

Remove the Enforcement: "Not possible" doesn't add any useful information.

### NL.10: Avoid CamelCase

Remove this whole item. An all-"Avoid" item is not appropriate in a section that is 'use these rules if you have nothing better.'

### NL.26: Use conventional const notation

Remove at least the Enforcement. We should not flag violating a style that is 'if you have no better ideas' and the item itself documents that there are technical advantages to the style the Enforcement would like to ban.

Consider removing this whole item.

**Comment by MikeGitb** [comment]
I wholeheartedly support the removal of NL.10 & NL.26.

One thing that could be considered is to create a "house style" for the core guidelines, that may be adopted by a project and should be used by examples in the guidelines, but it's not a guideline otherwise.

(And btw.: I also support the rule for using all upper case for macros)

**Comment by blakehawkins** [comment]
> Remove the Enforcement: "Not possible" doesn't add any useful information.

Not 100% on this. If we're saying that some rules should have no enforcement section at all, then fine.

Otherwise, isn't it useful to signal to the reader "this isn't missing - we've thought about it."?

**Comment by jwakely** [comment]
@blakehawkins a Note like "this isn't enforceable anyway" seems better for doing that.

@MikeGitb  don't the NL rules already define a house style, which is already followed (mostly) by the guidelines?

**Comment by hsutter** [comment]
Correction to NL.10 committed and pushed: Renamed to "prefer underscore_style names"

**Comment by hsutter** [comment]
No consensus among editors to make any other change.

**Comment by mloskot** [comment]
Pitiful!

"Instead of fixing the training material, we are going to condemn the entire industry to a less logical approach" ~@JonKalb

https://www.youtube.com/watch?v=gRmI_gsNqcI&t=5m
