### ISSUE TITLE
F.17 - clarify "in-out" wrt. lifetime

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#1197]
I find people commonly equate "in-out param" with "passed by T&".  Most of the time that's true, but there's an important gotcha: mutable parameters that need to outlive the function call. 

```
class Foo {
 public:
  // The provided context must live as long as this object, not just the c'tor call.
  Foo(FooContext& context) : context_(context) {}
...
};
```
Temporaries passed to such functions don't tend to trigger compiler warnings. 

```
Foo my_foo(FooContext());  // oops
```

Accepting unusual lifetime-requirement mutable parameters by pointer is likely safer
```
Foo my_foo(&FooContext());  // compiler warning, also obvious to code reviewer
```

If we agree this is worth clarifying, I think the fix can be as simple as defining out that "in-out" parameters cannot have unusual lifetime requirements.

**Comment by jwakely** [comment]
Neither example will compile, because you can't bind a temporary to an lvalue reference, and can't take the address of a temporary. Has something been lost when simplifying the examples?

**Comment by tituswinters** [comment]
Yeah, something lost coupled with me riffing on const-ref lifetime issues.  Skip it, I'll try again later. :)
