### ISSUE TITLE
using std::make_shared<>() to invoke protected constructor

### ISSUE THREAD

**Issue by computingdolas** [isocpp/CppCoreGuidelines#1205]
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#discussion-use-a-factory-function-if-you-need-virtual-behavior-during-initialization uses std::make_shared<T>() to construct shared pointer to derived class. I think std::make_shared<T>() cannot be used  here since the constructor of the derived class is protected. I compiled it with MSVC2017  and GCC 7.1 and both of them throws error
. I think example should demostrate use of std::shared_ptr<T>(new T(()) even though it involves two memory allocations. I have tried it here : https://godbolt.org/g/k2bgL2

But the primary focus here is to have working example in the document. Let me know what are your views on it.

**Comment by cubbimew** [comment]
cppreference actually makes a note of that on [make_shared](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared#Notes): "std::shared_ptr<T>(new T(args...)) may call a non-public constructor of T if executed in context where it is accessible, while std::make_shared requires public access to the selected constructor."

That may indeed have to become a small exception from the "no naked new" rule.

**Comment by computingdolas** [comment]
@cubbimew Indeed :).
@djarek Well, the solution is interesting, but I have some doubts on its practical implications. More importantly I wanted to point out a kind of bug in c++ core guidelines. I think we should either change the above mentioned example or change the usage of std::make_shared<T>.

**Comment by computingdolas** [comment]
@hsutter please review this one.

**Comment by gdr-at-ms** [comment]
Herb: please suggest a resolution.

**Comment by computingdolas** [comment]
@gdr-at-ms Thanks for the notice. I think this is an important one.

**Comment by pdimov** [comment]
In theory, `allocate_shared` with `std::allocator`, which needs to be made a friend.

In practice, this only works with boost::allocate_shared, and even then, not with libstdc++, which calls the constructor from `new_allocator<>::construct` instead of from `std::allocator<>::construct`.

So you have to use your own allocator.

**Comment by cubbimew** [comment]
just came across an interesting hack to use make_shared with a private constructor: https://stackoverflow.com/a/54456533
