### ISSUE TITLE
CP.31 Memory corruption from example

### ISSUE THREAD

**Issue by mabuchner** [isocpp/CppCoreGuidelines#1207]
The CP.31 example currently looks like this

```c++
string modify1(string);
void modify2(shared_ptr<string>);

void fct(string& s)
{
    auto res = async(modify1, s);
    async(modify2, &s);
}
```

`fct` passes the reference `s` as `shared_ptr` into `modify2`. This will very likely cause a memory corruption.

**Comment by cubbimew** [comment]
The note right after that example elaborates the point it's trying to make with "the implementation of modify2 will need some form of locking to avoid data races."

**Comment by cubbimew** [comment]
(You're correct course that it's an error to make a shared_ptr out of the address of a function parameter.. but passing a raw pointer may not be a great idea either)

**Comment by cubbimew** [comment]
(you're correct, of course, that it's a bug to make a shared_ptr out of the address of a function parameter)

**Comment by mabuchner** [comment]
Yes, the statements after the example will still apply after the PR. Passing by reference still requires proper locking.
