### ISSUE TITLE
C.37: Make destructors noexcept: Should this be explicit?

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [isocpp/CppCoreGuidelines#1209]
It's clear that destructors should be noexcept. What is not clear (we have a disagreement with a colleague), when reading the wording of this rule, is whether it advocates for always being explicit with destructors. For instance:
```
struct A {
  ~A() {}
};

struct B {
};
```
Do you think the above code is bad code according to the rule, and should instead be rewritten:
```
struct A {
  ~A() noexcept {}
};

struct B {
  ~B() noexcept {}
};
```

@neilmacintosh : I think you made the change to the rule text that makes us wonder

**Comment by johelegp** [comment]
A destructor, whether user-declared or not, is by default `noexcept`. So all the destructors in your examples are `noexcept`. For them to not be `noexcept`, you'd have to explicitly mark them with `noexcept(false)` or something like `noexcept(std::is_nothrow_destructible_v<T>)`.

**Comment by gdr-at-ms** [comment]
C.37 seems to be redundant with C.36.  Suggestion: Remove C.37 and clarify C.36.
When C.37 is removed, the anchor should be kept, and references should be rerouted to C.36.

**Comment by cubbimew** [comment]
Related: #814 and #167

**Comment by BjarneStroustrup** [comment]
I added a variant of Sergey's example from #167, but retained both C.37 and C.36. I think C.37 focuses on 'how?" and C.36 on "why?"
