### ISSUE TITLE
R.2 - Reasonable should be unreasonable

### ISSUE THREAD

**Issue by ljestrada** [isocpp/CppCoreGuidelines#1211]
**Note**

Many current uses of pointers to a single element could be references. However, where nullptr is a possible value, a reference may not be an reasonable alternative.

Should read:

**Note**
Many current uses of pointers to a single element could be references. However, where nullptr is a possible value, a reference may not be an unreasonable alternative.

**Comment by jwakely** [comment]
I think it's correct as written. A reference is not a reasonable alternative to a maybe-null-pointer, because a reference cannot be null.
