### ISSUE TITLE
why is std::reference_wrapper ignored by the core guidelines

### ISSUE THREAD

**Issue by PeterSommerlad** [isocpp/CppCoreGuidelines#1215]
In many places where the core guidelines talk about references and pointers, the possibility to use std::reference_wrapper (instead of not_null, for example) is completely ignored.

I wonder, if there is an underlying motivation for it, or just to sidestep the inclusion of <functional> header. Or is it to judge using not_null<T> instead of reference_wrapper<T>.

Curious, because of other guidelines I support editing.

**Comment by mloskot** [comment]
Possibly, a historical reasons:

https://github.com/Microsoft/GSL/issues/89#issuecomment-283472088
> The most common use-case we had for not_null is with raw pointers (which realy should be the most commonly passed type of pointer in most codebases). As a result, that was the first use-case addressed.

**Comment by hsutter** [comment]
GSL `not_null` is related but is a simpler concept. We are currently reviewing `not_null` (e.g., whether it should be a typedef or a type).
