### ISSUE TITLE
F.52 explanation should mention on how to achieve const reference capture

### ISSUE THREAD

**Issue by PeterSommerlad** [isocpp/CppCoreGuidelines#1217]
While efficient it might not be obvious how to capture a mutable (large) variable by const reference.

One option is to use std::cref():

```
std::vector<double> var(1'000'000);
[cr=std::cref(var)](){ /* use cr safely here */}
```

**Comment by jwakely** [comment]
Or `[&cr = std::as_const(var)]{ }`

**Comment by PeterSommerlad** [comment]
as always jwakely is more precise and suggests the better solution...

**Comment by jwakely** [comment]
Although my suggestion is only valid for C++17 and later. The C++14 version is ugly:

    [&cr = const_cast<const T&>(var)] { }

or if you don't know `T` it's even worse:

    [&cr = const_cast<remove_reference_t<decltype(var)> const&>(var)] { }

So for C++14 `std::cref` seems appropriate (as long as it doesn't matter that `cr` is not `const T&`, only convertible to it).

**Comment by hsutter** [comment]
Editors call: We decided to not get into the detail of capturing a const reference at this time, but plan to look at it again next time we revise this item.
