### ISSUE TITLE
Enum.7 example non-portable

### ISSUE THREAD

**Issue by PeterSommerlad** [isocpp/CppCoreGuidelines#1218]
In Enum.7 

```
enum class Web_color : int { red   = 0xFF0000,
                             green = 0x00FF00,
                             blue  = 0x0000FF };  // underlying type is redundant
```

says that int is redundant here, but that is IMHO a non-portable assumption, valid for 32bit int. On a 16bit int, it might be invalid code (did not test), on a 64bit int it might be too big, wasting space. Also the hex enum values indicate unsigned usage of the values. I would recommend to change the example to  one where the values and the type actually always match in a portable way.

**Comment by hsutter** [comment]
Fixed, thanks!
