### ISSUE TITLE
I2 vs cin/cout/cerr

### ISSUE THREAD

**Issue by imre-palik** [isocpp/CppCoreGuidelines#1220]
cin/cout/cerr are obvious counterexamples for this rule.

More generaly, when an external entity/interface that supposed to exist for the whole program run is wrapped in a library, then non-const globals are useful.  (At least I am not aware of any other way to deal with them.)

**Comment by hsutter** [comment]
Thanks! The rule is "avoid", not "don't use." Of course there will be (rare) exceptions, such as `cin`, `cout`, and `cerr`. We'll add a Note to that effect.
