### ISSUE TITLE
ES.30: too strict enforcement rule

### ISSUE THREAD

**Issue by imre-palik** [isocpp/CppCoreGuidelines#1228]
I'd say macros using the # and the ## operators are also valid.

**Comment by hsutter** [comment]
We really want to ban macros for other than configuration control. In fact, `##` is exactly an example of something used primarily for the kind of code generation that this item seeks to ban.

We believe want to add an Example;bad also to ban `#` and `##`.

**Comment by MikeGitb** [comment]
But what would be the replacement then? Until we get reflection I don't know if an alternative.

**Comment by BjarneStroustrup** [comment]
Depends what you want to do. What do you want to use macros for?

**Comment by MikeGitb** [comment]
Macros in general or the stringification and concatenation operators imre-palik was talking about?

The latter I sometimes use for stringification of enums, logging of function parameters and in a few odd cases I was quite happy about the ability to programmatically create identifyers.

**Comment by BjarneStroustrup** [comment]
Adding explicit discouragement of the use of # and ##

**Comment by imre-palik** [comment]
If you do this, then please also explicitely discourage the use of external code generators.
Compared to them, generating code with preprocessor macros are benign, and easily debuggable.

**Comment by MikeGitb** [comment]
I contest that statement. If you have an external code generator and debug the resulting code, you have straight forward c++ code. When you use macros (or templates for that matter) you have to do a lot of substitution in your head.
