### ISSUE TITLE
Purpose of zstring unclear

### ISSUE THREAD

**Issue by hpesoj** [isocpp/CppCoreGuidelines#123]
The documentation gives the following reason for `zstring`'s existence:

> C-style strings are ubiquitous. They are defined by convention: zero-terminated arrays of characters. Functions are inconsistent in their use of nullptr and we must be more explicit.

Is this correct?  It seems to me that the utility of `zstring` is in differentiating between pointers-to-char and strings, and doesn't really have anything to do with `nullptr`.  Sure, `not_null` can be used _with_ `zstring`, but that is just the combination of two different features.

The second (related) question I have about `zstring` is whether it is meant to be used just to annotate legacy "C-style" APIs, or whether it is meant to be used in new code.  I ask, because in my opinion `zstring` should never be null.  My rationale is that `zstring` is conceptually a string, not a pointer; pointers may be null, strings may not (if you disagree, ask yourself why `std::string` cannot be null).  The only reason that some APIs allow `zstring` to be null is that the authors have been fooled by its pointer-esque appearance (`char const*`).  If you need an optional string parameter, do what you do with every other type: use a pointer:

    void f(zstring* s); // void f(char** s);

Of course, legacy code can and does allow `zstring` to be null, so if it _is_ meant to be used in said legacy code, it must be possible to assign `zstring` a null value.  However, if you agree with my analysis above, it seems a little unwise to encourage the use of this legacy-compatible `zstring` in new code.  Thus, regarding this excerpt from the guidelines:

> Use not_null<zstring> for C-style strings that cannot be nullptr. ??? Do we need a name for not_null<zstring>? or is its ugliness a feature?

I think the answer is yes, given that `not_null<zstring>` is (IMHO) the correct usage.  In fact, in order to encourage correct use of the types, I would probably rename `zstring` to something like `nullable_zstring`, and then have `zstring` as an alias for `not_null<nullable_zstring>` (a bit of a double negative, but it does the job!)

Let me know if I'm horribly wide of the mark here.

**Comment by AndrewPardoe** [comment]
C-style strings are ubiquitous. They are defined by convention: zero-terminated arrays of characters. Functions are inconsistent in their use of  nullptr  and we must be more explicit.
To be changed to: 
C-style strings are ubiquitous. They are defined by convention: zero-terminated arrays of characters. We must distinguish C-style strings from a pointer to a single character or an old-fashioned pointer to an array of characters.

As for the not_null<zstring>. We don't know the answer yet for the question in the text.

**Comment by AndrewPardoe** [comment]
Edited text as indicated above.
