### ISSUE TITLE
Per.1-Per.5 Superfluous

### ISSUE THREAD

**Issue by imre-palik** [isocpp/CppCoreGuidelines#1230]
Would it be possible to remove these rules?

These days people only work with C++ if they have some performance requirements.  So Per.1 is not needed.

The rest is covered by Per.6  (Don't assume, measure)

**Comment by scraimer** [comment]
New developers in C++ are often beguiled into believing all kinds of myths about performance. Each of these guidelines attacks such an assumption. For example, that they should write every line to be as optimized as possible - prematurely optimizing. This is often at the cost of readability or maintenance, and even correctness. Reading Per 2, 4 and 5 might discourage such mistakes.

While I see there's much overlap among Per.1-6, these myths/beliefs are so entrenched that it is worth some repetition to combat them.

**Comment by gdr-at-ms** [comment]
Agreed with @scraimer
