### ISSUE TITLE
Inheriting from STL containers

### ISSUE THREAD

**Issue by tiagomacarios** [isocpp/CppCoreGuidelines#1232]
Inheriting from STL containers is usually frowned upon. Usual points are:
- stl containers have non-virtual destructors which could lead to undefined behavior if deallocated through a pointer to base class
- usually points to a bad design:
  - try to extend the container behavior through algorithms instead
  - violates the standard library encapsulation

Maybe we could touch on this on rule [C.120](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c120-use-class-hierarchies-to-represent-concepts-with-inherent-hierarchical-structure-only) or have a rule specific for it?

**Comment by hsutter** [comment]
Perhaps add inheriting from `std::vector` as a "bad" example in C.120?

**Comment by Amaroker** [comment]
I noticed that inheriting from std::vector is shown as an example of good style in "A Tour of C++" (4.4.1.2 in the draft available at isocpp.org).

**Comment by gdr-at-ms** [comment]
@Amoraker is correct: that has been a good programming technic and shown since at least TC++PL3.

The rule as proposed is too broad and too inflexible.

**Comment by arvidn** [comment]
another similar example is to inherit `std::vector` or `std::queue` to make it indexed by a strong type instead of `std::size_t`

**Comment by hsutter** [comment]
Editors call: We think C.35 covers this sufficiently for now. The problem isn't so much the inheritance as that an attempt to delete through a pointer to base would be wrong and so shouldn't be attempted. A class that is intended to be an interface to a set of derived classes should have virtual functions; a vector is not such a type.

**Comment by tiagomacarios** [comment]
@Amaroker reading that part of "A Tour of C++" without further context it seems like he is just trying to illustrate the difference between operator[] and .at.

**Comment by amosnier** [comment]
> @Amaroker reading that part of "A Tour of C++" without further context it seems like he is just trying to illustrate the difference between operator[] and .at.

Well, at least in TC++PL, 4th edition, he writes:

>   out-of-range errors are a common problem. Consequently, I often use a simple range-checking adaptation of vector:

```
template<typename T>
class Vec : public std::vector<T> {
```

To me it sounds like an encouragement to use that pattern.
