### ISSUE TITLE
C.129 illustration example does not compile

### ISSUE THREAD

**Issue by mzdun** [isocpp/CppCoreGuidelines#1239]
The `Impl::Smiley` has _two_ `::Circle` base classes, with _two_ V-tables, one through `::Smiley`, without implementation, one through `Impl::Circle`, with implementation. This causes the `Impl::Smiley` to be abstract through `::Smiley`. See the example in [Compiler Explorer](https://godbolt.org/g/VUaG2q) with working example [with virtual inheritance](https://godbolt.org/g/4QW1Y9).

Please revise C.129 or change example to use `virtual` inheritance on the pure interface edges.

**Comment by hsutter** [comment]
Editors: We agree the code should compile :) we'll take a look and adjust the example in a way that retains the meaning in the text.
