### ISSUE TITLE
F.45: rethink suggestion of return type specification

### ISSUE THREAD

**Issue by unixod** [isocpp/CppCoreGuidelines#1241]
Hi everyone,

The rule [F.45: Don't return a `T&&`](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-return-ref-ref) says:

> For passthrough functions that pass in parameters (by ordinary reference or by perfect forwarding) and want to return values, use simple auto return type deduction (not auto&&).

I think, the more correct way to handle this situation is to use ```decltype(auto)``` instead of simple ```auto``` as a return type specification:

```c++
template<class F>
decltype(auto) wrapper(F f)
{
    log_call(typeid(f)); // or whatever instrumentation
    return f();
}
```
As opposed to ```auto```, ```decltype(auto)``` truly forwards return value of forwarded call without loosing value category.

What do you think about this?

**Comment by jwakely** [comment]
It still makes it too easy to create dangling reference:

````
template<typename T>
  decltype(auto) max(T&& x, T&& y)
  { return std::forward<T>(x > y ? x : y); }
````

When called with a temporary this returns a dangling reference.

**Comment by unixod** [comment]
@jwakely thanks for your comment. The function, you have presented actually doesn't return dangling reference, even when called with temporary. E.g. _prvalue_ passed to the function, will be materialized to _xvalue_ whose lifetime ends only at the end of the full expression containing the ```max``` function call.
if I've missed something, please correct me :)

**Comment by jwakely** [comment]
It's dangling after the end of the full expression though. Lifetime extension doesn't apply, so it leads to bugs like:

````
auto&& x = max(0, 1);
foo(x); // undefined
````

This kind of thing is a frequent source of bugs, often incorrectly reported as a compiler bug.

**Comment by hsutter** [comment]
Editors call: Add this example to F.45 and mention that the Lifetime rules will also cover these cases in the future.
