### ISSUE TITLE
C.67 does not take exception objects into account 

### ISSUE THREAD

**Issue by akrzemi1** [isocpp/CppCoreGuidelines#1246]
The advice in C.67 (A base class should suppress copying, and provide a virtual clone instead if "copying" is desired) is counter to the commonly accepted practice of using exception objects in C++ today.

Typically I want a hierarchy of exceptions. There may be no exception hierarchy in the future C++, but today people define exception hierarchies to mimic the solution from the Standard Library. So they define the base type like this:

```c++
class ExceptionBase // derived or not
{
public:
  virtual Context getContext() const;
  virtual ~ExceptionBase() = defaut;
  // all copy operations available
};

class XException : public ExceptionBase 
{
  // ...
  // all copy operations available
};
```

And when an exception needs to be thrown, you just throw it by value. So we need at least to be able to move-construct an exception object. In C++17 we often do not need to copy/move an object to return by value, but sometimes a move is still necessary:

```c++
return XException{}.setTrace(trace()).setLocation(__FILE__).setData(data);
                // ^~~~~~  temporary materialization here
```

So maybe an exception should be made to C.67 for types in exception hierarchies?

**Comment by hsutter** [comment]
Thanks Andrzej. Yes, "throw by value / catch by reference" is our current two-phase model. [[except.throw]/5](http://eel.is/c++draft/except.throw#5) requires that an exception object of class type be copyable, but throwing a type with deleted copy/move [seems to work in gcc and Clang](https://wandbox.org/permlink/Ch9EZzxxewIyeMx6).

Would you please open a PR with suggested edits to C.67?

**Comment by akrzemi1** [comment]
I'll do that. But I would like first to propose further modification. So I request some discussion.

Sometimes slicing is exactly what we need and is intended:

```c++
struct Location // key
{
  int row;
  int column;
};

struct Pixel : Location // value
{
  Color color
};

void process(Location l);
Pixel p;
process(p); // perfectly fine to slice
```

So I would change the rule form disallowing slicing of base classes to disallowing slicing of _polymorphic_ base classes. Would this be an acceptable change?

(This also applies to C.130.)

**Comment by akrzemi1** [comment]
Actually, C130 and C.67 look a bit like duplicates; with inconsistent advice. 

Also, I cannot make sense of the exception clause: 

> If you need covariant return types, return an `owner<derived*>`.

Maybe drop C.67 altogether in favor of C.130 (and update C.130)?

**Comment by hsutter** [comment]
Base classes that have no virtual functions make slicing safer as we know we're not losing behavior.

I think the Enforcement for C.67 is correct. The title should also mention 'if there's a virtual function.'

I think C.130 still makes sense on its own but the title should be adjusted to reflect that it's mostly about how to write the `clone` function if you need one, remove the Enforcements, and point more strongly to C.67 as the main guideline.

Thanks Andrzej!

**Comment by hsutter** [comment]
Closed with PR. Thanks!
