### ISSUE TITLE
Is it necessary to add a stronger keyword than `const`?

### ISSUE THREAD

**Issue by 678uhb** [isocpp/CppCoreGuidelines#1247]
`const` can only prohibit modifying members. Is it necessary to add a keyword, such as `blind`, to prohibit member variable access (except `this`), because sometimes some methods need to be inherited by subclasses, but these methods should remain stateless.

**Comment by jwakely** [comment]
That seems like a C++ language design question, not suitable for the Core Guidelines.

**Comment by hsutter** [comment]
Editors: Agreed, we aren't generating language proposals in the Guidelines but anyone is free to make a well-thought-out language evolution proposal in WG21.
