### ISSUE TITLE
SF.11, use forward declaration in header file as a first try

### ISSUE THREAD

**Issue by pandysong** [isocpp/CppCoreGuidelines#1248]
I feel that SF.11 could be improved, for example in following case, a forward declaration is enough instead of `#include "class_b.h"` in the `class_a.h`.

```cpp
// class_a.h
class class_b; #here the forward declaration is enough
class class_a
{
    class_b *adp;
    public:
        class_a(class_b *b);
        class_b *adaptor();
};
```

Reason: `class_a.h` does not care about the implementation details of `class_b`, if `class_a.cpp` does need to access the methods in `class_b` then, it should itself include `class_b.h`, Same rule applies for the client of class_a: if the client needs to access `class_b` then it should include `class_b.h` by itself. 

Benefits: if `class_b.h` will included 'class_c.h` which includes other header files, a forward declaration will break the long chain of this recursive `#include`s. This will reduce the `make` time significantly , as `make` does much less job to resolve the dependencies. 

Overall, the rule might be improved: we should first use forward declaration, if not working, we should include other dependent header file, for example in following case

```cpp
// class_a.h
#include "class_b.h"  // we should include "class_b.h"
class class_a
{
    class_b adp;  // as class_a has full access to class_b
    public:
        class_a(class_b *b);
};
```

**Comment by jeffreylindsey** [comment]
My understanding of the intent behind guideline SF.11 is that for any header file, there should be no requirements for anything to be included or declared before that header file is included.

Your example to forward declare `class_b` in the header file `class_a.h` is acceptable within this guideline.

A counterexample, for what not to do, would be to neither forward declare `class_b` nor include `class_b.h` within `class_a.h`.  This would require anyone who wishes to include `class_a.h` to then also take on the responsibility to either forward declare `class_b` or include `class_b.h`, which is what I believe this guideline is trying to avoid.

The guideline could certainly be improved to explain this more clearly.

**Comment by pandysong** [comment]
Regarding "This would require anyone who wishes to include class_a.h to then also take on the responsibility to either forward declare class_b", I feel that a client of class_a does not need to forward declare class_b. And it of cause need to include class_b.h if it needs to access the method of class b in client's code.

In SF.11 It might be helpful to add a reference to I.27
     I.27: For stable library ABI, consider the Pimpl idiom

I.27 helps to reduce `#include` because of private members which anyway not accessible for a client.

**Comment by jwakely** [comment]
> My understanding of the intent behind guideline SF.11 is that for any header file, there should be no requirements for anything to be included or declared before that header file is included.

Right.

SF.11 is not about reducing the number of include files, so Pimpl and forward declarations aren't relevant to SF.11 IMHO.

**Comment by pandysong** [comment]
> SF.11 is not about reducing the number of include files, so Pimpl and forward declarations aren't relevant to SF.11 IMHO.

Logically they might be independent. The issue is about `not to over #include`. 

Guidelines are to help `human` to write good code and guidelines themselves are not the code, we do not have separate them so clearly. Both helps to write a `easy to use` header file, so they are related, I feel it always helps to add cross-link to other relevant rules. 

Maybe we should put into a separate rule.

**Comment by jwakely** [comment]
> Guidelines are to help human to write good code and guidelines themselves are not the code, we do not have separate them so clearly

Mashing unrelated issues together into one guideline doesn't help anybody.

If they are independent then it should be a separate rule.

And I'm not convinced "use forward declarations to reduce the number of includes" is always a good guideline. Sometimes ease-of-use is more important than reducing the number of dependencies, it depends.

**Comment by scraimer** [comment]
>  [...] of dependencies, it depends.

Thank you, sir. The giggle made a drink go right up my nose!

**Comment by pandysong** [comment]
> Mashing unrelated issues together into one guideline doesn't help anybody.
> If they are independent then it should be a separate rule.

Agree to put to separate rule, but better to be cross-referenced. 

> And I'm not convinced "use forward declarations to reduce the number of includes" is always a good guideline. Sometimes ease-of-use is more important than reducing the number of dependencies, it depends.

Agree that It is possible that it is not always the case.  But Similar arguments exists on the rule:

> I.27: For stable library ABI, consider the Pimpl idiom

There are always cons. and pros. But it does not prevent it from being a rule, with detailed explanations and examples given such that people could understand and justify.
