### ISSUE TITLE
Is there a versioning scheme in place for the Guideline Support Library?

### ISSUE THREAD

**Issue by michaelbprice** [isocpp/CppCoreGuidelines#125]
There is already at least one implementation at https://github.com/Microsoft/GSL and it might be good (essential?) that people understand what they are getting when they adopt of of these implementations.  If we don't really expect multiple implementations, why not just include the implementation in this repository so that changes to the specification and the implementation can happen simultaneously?

**Comment by AndrewPardoe** [comment]
This is being discussed in issues at Microsoft's GSL repo: https://github.com/Microsoft/GSL/issues/43
