### ISSUE TITLE
format issue: C.140  indent/level is wrong

### ISSUE THREAD

**Issue by pandysong** [isocpp/CppCoreGuidelines#1250]
it should be 

`### <a name="Rh-virtual-default-arg"></a>C.140:.......`

instead of 
`## <a name="Rh-virtual-default-arg"></a>C.140:.......`

The issue was found when I tried to parse the markdown file (I was trying to help with https://github.com/isocpp/CppCoreGuidelines/issues/923)

**Comment by jwakely** [comment]
Fixed, thanks!
