### ISSUE TITLE
P.3: Express intent: for_each() Construct does Not Exists

### ISSUE THREAD

**Issue by will-meig** [isocpp/CppCoreGuidelines#1254]
In P.3: Express intent:

```
for_each(v, [](int x) { /* do something with the value of x */ });
for_each(par, v, [](int x) { /* do something with the value of x */ });
```

I couldn't find those for_each() versions in the STL or the GSL. The STL version requires a begin and end iterator to be given:

`for_each( InputIt first, InputIt last, UnaryFunction f )`

It would be nice to extend the GSL so that those first calls without explicit iterators can be used.

**Comment by jwakely** [comment]
See https://en.cppreference.com/w/cpp/experimental/ranges

Adding that to the GSL as waaaaaaaaaay out of scope.

**Comment by cubbimew** [comment]
Since Ranges are now in C++20, we may be able to revert this (as well as the earlier https://github.com/isocpp/CppCoreGuidelines/commit/a26d6c98d54b9f2e33334415639f0789e4af8d8b ) at some point!
Probably after C++20 is published.
