### ISSUE TITLE
E.27: "goto error" technique violates RAII, won't compile

### ISSUE THREAD

**Issue by chipolson** [isocpp/CppCoreGuidelines#1257]
E.27 includes a brief discussion of what I call the "goto error" technique of error handling. While the section does not particularly encourage this technique, I would like to note a serious drawback that I think should be called out explicitly: It is an error for a variable to be declared between a `goto` and its target label, because otherwise code following the label might use the variable when its declaration was never executed. As a result, in functions that use this technique, all variable have to be declared _before_ the first `goto`. This, of course, is a serious impediment to proper RAII technique.

Indeed, the code sample given declares the `g2` variable after the first `goto`, and uses it after the `exit` label. I wrapped the sample up into a program and GCC had this to say:
```
goto.cpp: In function ‘bool foo()’:
goto.cpp:38:1: error: jump to label ‘exit’ [-fpermissive]
 exit:
 ^
goto.cpp:25:18: note:   from here
             goto exit;
                  ^
goto.cpp:28:12: note:   crosses initialization of ‘Gadget g2’
     Gadget g2 = make_gadget(17);

```

**Comment by hsutter** [comment]
Good catch, thanks! Example fixed.
