### ISSUE TITLE
F.3 Refactored example seems to have a typo

### ISSUE THREAD

**Issue by vlgimen** [isocpp/CppCoreGuidelines#1262]
In the refactored example under **F.3 Keep functions short and simple** I believe there is a typo on the function signature for `double funct1_tau(double val, int flag1, int flag2)`. The `simple_code` function has a call to `func1_tau` and not `funct1_tau`.

**Comment by cubbimew** [comment]
thanks, fixed with https://github.com/isocpp/CppCoreGuidelines/commit/b16eb424e9d4331ec5f4c238f303e240dd383aa6
