### ISSUE TITLE
C.4 - chaining, cohesion and coupling

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1265]
In http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class

there is an exception, concerning chaining

--------------

Similarly, a set of functions may be designed to be used in a chain:

```
x.scale(0.5).rotate(45).set_color(Color::red);
```

Typically, some but not all of such functions directly access private data.

-------------

Does the C++ core guidelines suggest chaining as good design?

I'm asking because it reduce cohesion, increase possibly coupling, if the functions have parameters types that we not needed by the class, making the test of the original class or each one of the free functions more difficult.

If we want chaining, we have an alternative that consists in defining a wrapper that provides the member functions and call either to the free functions or the member functions.

```
chain(x).scale(0.5).rotate(45).set_color(Color::red);
```

This wrapper could be cumbersome to maintain, but it is just a workaround to not having yet UFC, extension methods or variations of "Deducing this on free functions",and maybe we can get it with reflection.

The chain approach increase the coupling of the users. However the cohesion of the chain class is good as it has a single responsibility, to chain the operations.

Only the parts of the code that want to use this chaining syntactic sugar will pay for the increase of coupling.

Another alternative could be range style pipelines.

```
x | scale(0.5) | rotate(45) | set_color(Color::red);
```

This needs to use namespace for the free functions `scale(`,  `rotate`| or `set_color`.
The definition of these functions is more complex fro the author, as they return a class that support the pipe operation to this end.

I'm not aware of IDE tools that help with the pipeline sntax, but I could expect that wit hthe standard range library, IDE would evolve.

The advantage of the pipe approach is that we reduce coupling and maintain cohesion as those can be defined as free functions.

Don't having UFC shouldn't be a reason to increase the coupling and reduce the cohesion of a class.  If one day we have UFC, this will allow to replace `chain(x).fct()` by `x.fct()` or `x | fct()` by `x.fct()`.

Do you believe it is worth mentioning on the guidelines this chain wrapper or the pipeline alternative designs to avoid adding more and more function members to a class and increase the coupling and reduce the cohesion?

**Comment by cubbimew** [comment]
> Do you believe it is worth mentioning on the guidelines this chain wrapper or the pipeline alternative designs?

Does this also imply removal of C.4 Enforcement exception "Ignore functions returning this"?

**Comment by viboes** [comment]
> Does this also imply removal of C.4 Enforcement exception "Ignore functions returning this"?
Sure.

**Comment by hsutter** [comment]
Editors call: We agree that chaining is useful and is an intentional exception covered by the last Enforcement bullet. But the chaining example may be a little hard to see, so we've added another heading in front of it to make it more visible.

**Comment by viboes** [comment]
I see the added Exception as a guideline to do such kind of chaining functions, which I don't adhere to :(

Not having UFCS is not a reason to reduce cohesion on a class. 
Not having extension methods is not a reason to reduce cohesion on a class. 

Please, don't promote this member function chaining style for C++, just because the IDE could help the developer to find out some members.
