### ISSUE TITLE
C.11 make concrete types (with value semantics) regular.

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1267]
C.11 says make concrete types regular. I suspect we are talking of types with value semantic.
I don't believe you are suggesting to make types that are part of a OO hierarchy regular as C.67 suggest, nor utility types as `std::lock_ward`.

What do you think to be more precise?

**Comment by hsutter** [comment]
Editors call: Thanks, we agree this could use more precision. Assigned to Bjarne to write up the clarification.

**Comment by BjarneStroustrup** [comment]
I singled out resource handles

**Comment by viboes** [comment]
I was just waiting for precision on the title as suggested by the title issue. 
IMO, changing the scope of the guideline would make it clearer. No need for the exceptions about the locks, or hierarchies.

It is up to you as always.
