### ISSUE TITLE
C.10 concrete type versus value types

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1268]
In https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cconcrete-concrete-types we use the term of concrete type as a type that can be allocated on the stack, a value type, while in the glossary is defined in opposition to abstract

concrete class: class for which objects can be created.

I'm for the last definition, and so I would replace the section above and use the term value type, as I believe this kind of types is what we are talking about, isn't it?

**Comment by hsutter** [comment]
Editors call: Thanks, this basically needs the same clarification as the previous issue.

**Comment by BjarneStroustrup** [comment]
I have tried to clarify. I didn't go with "concrete class: class for which objects can be created." because classes in a hierarchy can be created, yet are not what I call concrete (e.g., needs to be accessed through pointers and cloned as opposed to copied).

**Comment by viboes** [comment]
For me, the clarifications have not fixed the issue.
There was a confusion with the concrete term and it is there yet.
Independently of what do you prefer, the fix need to remove the confusion :)
