### ISSUE TITLE
Guidelines about how tests impact the product code 

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1269]
I've not read completely the guidelines and they are changing continuously, but I have the impression that there are no guidelines on what concerns test. Please, let me know if I'm wrong.

What do you think of having some guidelines about how testing impact the product code? The do that and the don't do that ... 

I'm not looking for process based guidelines but more about the impact of the tests on the product code. I was thinking on e.g.

- Test only public interfaces.
- Avoid conditional compilation on production code depending on test flags. test depends on production code, not the opposite
- Don't define private as public using the pre-processor to provide access to the product code from the test.
- Don't make (Avoid making) something public/protected only to make it accessible to the tests. You need a better rationale.
- Don't parametrize only to make it possible to inject mocks from the test. Making code testable in C++ doesn't implies having to use dependency inversion/injection and run-time polymorphism. Think of pre-processor time / link time / load time polymorphism:
  - Use  #include <> to make it possible to select the included file with the build system
  - Use the linker options to select a different implementation of the dependencies 
  - Use the loader ...
...

**Comment by viboes** [comment]
See also #886

**Comment by cubbimew** [comment]
> Test only public interfaces.
> Don't define private as public
> Don't make something public/protected only to make it accessible to the tests.
> Don't parametrize only to make it possible to inject mocks from the test.

As an individual C++ programmer I strongly agree with those, but I doubt these fit well into the C++ Core Guidelines, because

1. What would be the "Enforcement" clauses of these rules? Other than "Don't define private as public", what would trigger a guidelines checker tool to print a warning with a link to a guideline?

2. A robust and defensible guideline on testing needs more than just a few disjoint rules. For example, Bloomberg has both a large-scale success story and meticulous logic behind their testing methodology  (I can't seem to find anything off-hand beyond a teaser on pages 627-661 of the [cppnow 2013](https://github.com/boostcon/cppnow_presentations_2013/blob/master/wed/accu2013.130511b/accu2013.130511b_Part3of3.pdf?raw=true) presentation, but the full story of `uniqueBirthday` and other examples was enlightening), but there isn't such central, "core", methodology applicable across all of C++.

See also prior discussions on testing in #849 and #776 and the newly added #1270 (to which my points apply even more)

**Comment by neithernut** [comment]
> What would be the "Enforcement" clauses of these rules? Other than "Don't define private as public", what would trigger a guidelines checker tool to print a warning with a link to a guideline?

This isn't really a valid argument. The core guidelines are not meant to be a specification for a checker tool. Also, [In.not](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#innot-non-aims) says at the very beginning:

> The rules are not intended to be minimal or orthogonal. In particular, general rules can be simple, but unenforceable.

**Comment by cubbimew** [comment]
> Also, In.not says at the very beginning:

Don't miss the very next sentence "their main intended use is to be targets for tools"

**Comment by viboes** [comment]
I'm sure some of the guidelines will have checkers, other will be more difficult if not impossible.
This is already the case for a lot of the guidelines on this guide.

While it is good that tools help us, please, do,'t let reduce our knowledge to what tools can do. People is able to do much more.

E.g. you can define a checker that looks for some conditional code, based on some conditional flag (which could of corse configurable) e.g. UNIT_TEST.

Check for members that are public/protected and that have only access from the test part.

Maybe it is difficult to identify test in general, but if test are organized conveniently this could be done. I like when test are in a parallel folder that follows the product organization, or the features for integration tests. I don't like to have product and test in the same folder. But what is more important is to have possibility to identify the product and the tests.

Specific (run-time) parametrization for the test could be identified when there is only one specific use of the seam in the production code and possibly much more on the test.

While I'm interested also in how test are organized, writer, ... #1270, I'm more interested in his impact on the productions code.

Some of these guidelines can not be checked at the library level, as the goal of a library is to be open. But we should be able to check them when we see together the library and the application.

I'm sure that people have a lot of imagination and creativity and they will reach to create checker for a lot of guidelines concerning the impact of test on the product code.

**Comment by viboes** [comment]
The fact that we could need more guidelines don't prevents us from stating with some guidelines we can agree on. If you are saying that we cannot agree on any guideline on how the test could or couldn't impact the product code then we can close this issue.

If we believe that we would work on some of the items I suggested, I could create separated issues to discuss them independently.

**Comment by scraimer** [comment]
I'd like to play devil's advocate, and claim that tests are your primary customer. They are certainly your first customer.

When first written, the product code will only be run by a developer running tests, or by an automated testing framework. Only after you ship it does it get executed in production. Under that assumption, changes to the product code that serve the tests are fair game (e.g. dependency injection, making public, etc).

**Comment by viboes** [comment]
@scraimer I agree that tests are a customer of my product. This is why, it should test only the public interface. No more. 

In C++ you have other alternatives to test your product other than making the functions public or using dependency injection. In C+C++, you are able to replace your dependencies by test double without changing the source code :) 

Making a function public only to be able to test a function makes your code less robust and more costly to maintain. In addition it doesn't document the real interface.

Dependency inversion makes your code much more complex. Dependency inversion has a run-time cost.
Forcing you to use dependency injection only because of test makes your code more complex and could not respect the required performances. I understand that your class will be more open, but not simpler. If you don't need to inject the dependency, why would you like to make it more complex than necessary? is it because you are using a bad tool to test your class? or because you use to do it this way with other languages? or because we can do it? 

I'm not saying that you shouldn't use dependency injection at all or make a function public because this is what the class must provide, but only if this makes your product better respect to his requirements.    

Said in other words, would you accept a redesign of a class as a template having his dependencies as template parameters, only to make it possible to replace the dependencies by double test (mocks, ...)? I will do it only if this make my class more usable for the product, but not for making it testable.

**Comment by hsutter** [comment]
Editors call: We agree testing is important, but we don't feel we're ready to add extensive guidance on testing at this time. A good treatment of testing could involve commenting on too many details of things like the build system, file organization, testing frameworks, defining keywords, and such.

**Comment by viboes** [comment]
I'm not asking for how test are organized, but for how they could impact the product :(
It seems we don't understand each other.
