### ISSUE TITLE
Guidelines for writing Unit Tests

### ISSUE THREAD

**Issue by will-meig** [isocpp/CppCoreGuidelines#1270]
Hi,

there does not seem to be any mention of writing unit tests in the C++ Core Guideline. Interestingly, other C++ guidelines also seem to be mostly silent about the issue of unit tests. There seem to be a void that needs to be filled in this regard.

I have started writing some "rules" to address this. There are to sides to this topic. First, how to write unit tests, and second, how to write the code so that is it actually testable.

Here is the outline of the rules I have so far and am currently detailing a bit. It would be nice to have your feedback on this. Do you see room for unit testing advise in the Core Guidelines?

Outline:

- UT: Unit Tests
  - Tests should run fast
  - Tests should isolate errors
  - Tests should be high quality
  - Use the AAA Format: Arrange, Act, Assert
  - Tests should be independent of each other
  - Don't try to create "realistic" test data.
  - Test for the edge cases

- T: Testability
  - Keep your objects easy to instantiate
  - Make your interfaces public
  - Make effects visible
  - Avoid declaring classes and methods 'final' if you don't have to

**Comment by neithernut** [comment]
From what I see, your proposals regarding unit tests are pretty much covered by standard literature. And unit-test How-tos. Personally, I don't see any point to include them.

Also: #1269.

**Comment by will-meig** [comment]
Hi neithernut,

Thanks for the quick feedback. I am looking at this from the point of view of adopting a C++ guideline in a project. If we write code and unit tests and need a guideline for the code. I don’t see why we wouldn’t need a guideline for the unit tests. 

By the argument you cited, a big chuck of the C++ Core Guidelines is also covered by standard literature already. It is not even specific to C++:

- P.1: Express ideas directly in code
- I.4: Make interfaces precisely and strongly typed
- F.2: A function should perform a single logical operation
- Con.1: By default, make objects immutable

To name but a few. 


I admit that I don’t see a clear pattern for deciding what to include and exclude from the guidelines I have seen until now. It looks like a mixed bad of several things to me:

- Formatting/indenting:  best left to an automatic tool but you still need to agree on a configuration for the tool. This is not covered by the C++ Core Guidelines AFAIK but other guidelines define this in details. 

- Conventions: when there are several valid alternatives, deciding on which one to use for readability and consistency. This is what makes the most sense to put into a guideline in my view. 

Avoiding common mistakes/bugs: this also makes sense in a guideline but technically, this is just knowing the language. 

Promoting good design: the rules I gave as example above are mostly in this category. That’s why they are not specific to C++. This is technically just being competent in software design. 

I came to the conclusion that guidelines are for setting conventions for the “trivial” matters to avoid wasting time defining them again for each project and the rest is mostly a “crash-course” in the programming language — such as C++ — and the paradigms — such as object-oriented design — agremented with some “gotchas” and tips. 
From this point of view, it makes as much sense to give a crash-course in writing unit tests as it does in, say, object-oriented design. 

Maybe all it comes down to, is the view that the authors have of unit tests. If they think, it belongs together with writing code, they should endorse it and give advice on how to do it best. If they think it is optional or not the developers’ job, they should leave it out. 

I tend to see it as an essential part of writing and designing code but that may not be the point of view of the majority.

**Comment by neithernut** [comment]
> By the argument you cited, a big chuck of the C++ Core Guidelines is also covered by standard literature already. It is not even specific to C++: [...]

Yes, many rules in the core guidelines are also found in the literature (and be it in books like Scott Meyer's "Effective C++" with a similar guideline character). However, the rules supplement information which is usually found in educational material on C++. Sure, one or the other rule will be included in such books, but it may as well be lacking --especially in tutorials.

The proposed outline for "UT", however, would be a fitting outline for some unit-testing how-to. Virtually the only thing lacking is an introduction (e.g. "What is unit testing?"). So, rather than supplement information which may or (may not) be missing from literature a novice would consume, it covers everything which should belong into a proper tutorial anyway (modulo "Tests should be high quality").

**Comment by scraimer** [comment]
Testing is a huge topic. I think adding all that into the guidelines is too much. There are too many ways to do it, and laying down "the one right way to test" could take forever, with much debate.

Can we narrow this down to just a few universally true statements? For example, "Testing is good for you." (Which, now I've written it, makes me worry even that statement isn't truly universally true!)

**Comment by hsutter** [comment]
(Same as #1269): Editors call: We agree testing is important, but we don't feel we're ready to add extensive guidance on testing at this time. A good treatment of testing could involve commenting on too many details of things like the build system, file organization, testing frameworks, defining keywords, and such.
