### ISSUE TITLE
Covariant return types and ownership

### ISSUE THREAD

**Issue by allopislozano** [isocpp/CppCoreGuidelines#1276]
At the moment these guidelines encourage, as quite a fundamental guideline, to denote ownership in interfaces by either returning unique_ptrs or owner<T> , but doing so disables covariance in return types. Example:

https://godbolt.org/z/GF2QHK

I think this should be either pointed out as a defect in the language or discussed on how to work around it

**Comment by neithernut** [comment]
I don't really see the problem: https://godbolt.org/z/I4Q2HR

**Comment by neithernut** [comment]
Approaching the question from a different angle (this is somewhat the rationale for my answer): in what way does returning a `std::unique_ptr` _disable_ covariance? E.g. how would you achieve covariance using a (raw) pointer in C++? As the return type of the method is dictated by the base class, the overridden method can also not just return a pointer of a different type.

As shown above, you can also perform regular upcasts and dynamic downcasts using unique pointers. If the type of covariance you need is served by (dynamic) polymorphism anyway, you are fine.

If you really need to return different types in some sub-class, consider using something like a `std::variant` or `std::any`.

**Comment by allopislozano** [comment]
How to get covariance using a raw pointer:

https://godbolt.org/z/pOCjWD

**Comment by jwakely** [comment]
@neithernut 

> As the return type of the method is dictated by the base class, the overridden method can also not just return a pointer of a different type.

But it can, that's what covariance is. If you call the derived override you can get a pointer to a different type back.

**Comment by neithernut** [comment]
TIL...

**Comment by hsutter** [comment]
Editors call: This is covered in Guidelines [C.130](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-copy) and [C.67](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-copy-virtual) which link to each other.
