### ISSUE TITLE
C.33 - misassumption of double deletion

### ISSUE THREAD

**Issue by Hexlord** [isocpp/CppCoreGuidelines#1277]
**Trigger:**
[Last listing of code](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c33-if-a-class-has-an-owning-pointer-member-define-a-destructor) states that copy constructor IS defined (assume copy is deep, else it makes little sense)
`// ... copy and move operations ... `

**Expected behaviour:**
Assignment comment altered to something like below or removed
`auto p2 = p1;   // ok: no double deletion`

**Actual behaviour:**
But the comment about double deletion is not altered 
`auto p2 = p1;   // error: double deletion`

**Comment by jwakely** [comment]
N.B. there's no need to submit an issue _and_ a pull request, you can just submit a pull request (with an explanation of the issue in the comments there).

**Comment by hsutter** [comment]
Merged, thanks!
