### ISSUE TITLE
What are C.133, C.131, C.9 supposed to do with unions?

### ISSUE THREAD

**Issue by LebedevRI** [isocpp/CppCoreGuidelines#1281]
I'm writing a clang-tidy check for [`C.133`](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-protected) - https://reviews.llvm.org/D52771
Among the review notes raised, was the question as to what should be done regarding `union`s.
Should they be diagnosed just like the normal `struct`s/`class`es?

CC @AaronBallman, @JonasToth

**Comment by BjarneStroustrup** [comment]
Yes, I don't see good uses of unions with private or protected members.

**Comment by LebedevRI** [comment]
Thank you for commenting!

> I don't see good uses of unions with private or protected members.

This is confusing. So for `union`s, everything *but* `public` members should be diagnosed?
Because for `struct`s/`class`es we will either complain on all non-`private`, or all `protected` members.

**Comment by LebedevRI** [comment]
Yep, after thinking about it a bit more, i think that was sufficiently clear.
Would be great if those rules could be expanded with a note that they only apply to non-`union`s.
