### ISSUE TITLE
SF.6, SF.7, Guideline improvement?: where "using namespace xxx" is allowed - header particularly

### ISSUE THREAD

**Issue by hmbdc-dev** [isocpp/CppCoreGuidelines#1282]
Hi,
The above 2 guildelines seems not going far or precise enough in my opinion. To be specific, it says it is allowed to be used in local scope. With more template usage, and more implementation has to be in header file, this gets important.
Consider this head file foo.hpp and bar.cpp example:

    #pragma once
    #include <iostream>

    namespace foo {
    using namespace std;  // if I understand correctly, this is allowed?
    template <typename T>
    void f() { cout << endl;}
    }
    =============
    #include "foo.hpp"
    void g() {
    {
        using namespace foo;
        cout << endl; //this unexpectedly compiles, no std needed
    }

    {
        foo::cout << foo::endl; //this also compiles
    }
    }
==========
This would cause problems since when the "using namespace std; " line gets removed from header, some cpp code that relies on it (without knowing) would break - unexpectedly.

I suggest changing the wording of SF 6 and 7, saying it is only allowed in impl or detail namespace.
See below:

    namespace foo {
    namespace detail {
    using namespace std;  
    template <typename T>
    void f() { cout << endl;}
    }
    using detail::f; //only expose f, not std namespace
    }

The point being, no client code is supposed to explicitly use "detail" namespace.
PS, It would be nice if C++ supports a "private namespace", that is only accessible in its immediate enclosing scope - instead of relying on the client code to honor the "detail" namespace privacy.

**Comment by jwakely** [comment]
````
namespace foo {
using namespace std;  // if I understand correctly, this is allowed?
````

No, that's not a local scope.

**Comment by hmbdc-dev** [comment]
yes, I was mistaken about what local scope meaning there. 
Arguably “detail” is a local scope if client code plays along by not accessing it.

**Comment by jwakely** [comment]
No, it's still not a local scope. How you happen to use it doesn't change that.

I think this issue can be closed since it's based on  misunderstanding of what the current guidelines allows.

**Comment by hmbdc-dev** [comment]
Sorry, what is ur concern of allowing it in the detail namespace? That would help coding quite a bit if u have to write impl in the header because of templat.

**Comment by brenoguim** [comment]
The "local scope" part is very important to avoid headers to messing with each other.
See https://godbolt.org/z/2lBJUB

Each header is fine in isolation. But when the user includes both of them, then things start clashing.

**Comment by hmbdc-dev** [comment]
That is fair example. Looks like there isn’t a good solution for people who have to put impl in headers.
Thanks, and I am closing it.
