### ISSUE TITLE
Enum.4 Example could be simplified

### ISSUE THREAD

**Issue by kblomqvist** [isocpp/CppCoreGuidelines#1285]
I was struggling with the following quite longish one-liner, that in addition to incrementation, contains two static_casts and a ternary.

```cpp
Day& operator++(Day& d)
{
    return d = (d == Day::sun) ? Day::mon : static_cast<Day>(static_cast<int>(d)+1);
}
```

I would propose to simplify the code as

```cpp
Day& operator++(Day& d)
{
    if (d == Day::sun) return Day::mon;
    int tomorrow = static_cast<int>(d) + 1;
    return static_cast<Day>(tomorrow);
}
```

**Comment by kblomqvist** [comment]
> Your replacement is not setting `d` as the original code does.

Now when you're saying that I can see it, but missed it in the first place.
 
> I don't like return and if being in the same line.

I agree, but for that I was using the same style used in some other examples.

> According to Con.4 tomorrow should be const.

👍

> All in all I can't read and understand your function better than the original one-liner. I like the original function more. I only would make `return d=...` a two-liner `d=...;` and `return d;`.

At least having this I wouldn't had misread that the reference d was, of course, intended to be changed.

```cpp
d = (d == Day::sun) ? Day::mon : static_cast<Day>(static_cast<int>(d)+1);
return d;
```

**Comment by grahamreeds** [comment]
I always split ternary across multiple lines for readability.

*d = (d == Day::sun) *
*    ? Day::mon *
*    : static_cast<Day>(static_cast<int>(d)+1);*
*return d;*

Probably violates a rule or two.

GR
