### ISSUE TITLE
`CppCoreGuidelines.md` navigation (TOC) is broken.

### ISSUE THREAD

**Issue by DmitrySokolov** [isocpp/CppCoreGuidelines#1287]
All anchor links in the TOC are broken. It's impossible to navigate to `CppCoreGuidelines.md` sections.

For example, `In: Introduction` has the anchor `#S-introduction` while the real anchor is `#in-introduction`.

**Comment by cubbimew** [comment]
They work on http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines though

**Comment by cubbimew** [comment]
actually the Rc-xyz links stopped working too (e.g. https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-zero ), and I am certain they worked before, I've been using them when sharing links to the guidelines.

**Comment by cubbimew** [comment]
They all seem to be working now, even without the new PR..

**Comment by hsutter** [comment]
Editors call: As mentioned in #1289, this seems to be working again, let's hold off and see if there's an issue that needs to be solved. Thanks for reporting this! Please let us know if it recurs.

**Comment by hsutter** [comment]
For now we'll just close this, we can reopen it again if it recurs.
