### ISSUE TITLE
Should guidelines discourage use of bool parameters, especially multiple?

### ISSUE THREAD

**Issue by ChrisGuzak** [isocpp/CppCoreGuidelines#1288]
At Microsoft many teams discourage use of bool parameters when their semantics are not obvious at the call site, recommending `enum class` (with good names) instead.  For multiple bools my team recommends a 'flags enum' (enums with a plural name, hex values, a none value (of zero) and operators overloads for the bit operations), to improve legibility and provide easy extensibility.  

Guidelines discourage [adjacent parameters of the same type](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i24-avoid-adjacent-unrelated-parameters-of-the-same-type). I'd like this to go further in the case of bool.

Thoughts?

**Comment by scraimer** [comment]
This is a good idea for bool.

I like this as a specific example of the general concept of "always use strong types", that is probably easy to enforce by always pointing out bool argument as a code smell.

On the other hand, doesn't this basically deprecate `bool`?

If you replace all `bool` parameters with `enum class`, that sort of change will spread in the code - all the places where people now (mistakely!) use `bool` as a flag will be gone. The only valid remaining way to use `bool` would be for intermediate variables that temporarily hold the result of a condition expression:

```
bool condition = /* some complex multi-line expression */;
some_enum_type decision = condition ? some_enum_type::yes : some_enum_type::no;
if( decision ==  some_enum_type::yes ) {
   /* do stuff */
}
```

That sort future is quite attractive. `bool` could still be around, but it would only be used for actual boolean expressions, and not for a symantic stand-in for flags.

**Comment by johelegp** [comment]
> flags enum

Those are https://wg21.link/bitmask.types.

**Comment by ChrisGuzak** [comment]
https://github.com/isocpp/CppCoreGuidelines/pull/1291 updates the content to address this

**Comment by hsutter** [comment]
Approved #1291, closing this. Thanks!
