### ISSUE TITLE
Explicit template initialization

### ISSUE THREAD

**Issue by paolobolzoni** [isocpp/CppCoreGuidelines#1293]
Usually when I write template classes or functions I split the declarations and the definitions in two different headers (with extension `.tpl.h` and `.h` respectively) where the second includes the first.

The idea is that normally you can use the `.tpl.h` file to just use the templates easily. But if one starts to have problem with long compilation times or code duplication, then it is possible to include the `.h` everywhere instead and to add a single source file that includes the `.tpl.h`. In the new file is then necessary to add the explicit instantiation templates. Doing so the linker will find the code it needs and the compiler will compile it only once.

I do not think this approach is original, but I was wondering if it is worthwhile to add a rule to the guidelines under the header or template sections. Personally, I had the problem with long compilations times only once, but I guess it might happen more often in large projects. Besides, it is easy to start just using the `.h` files and to switch if needed.

Example. In the following code one can use `struct S` either including `s.h` or using the explicit instantiations in `templates.cpp` and including `a.tpl.h`.

(The guards are omitted)

    // s.tpl.h
    template <class T>
    struct S { 
        T f(); 
    };

.

    // s.h
    #include "s.tpl.h"
    template <class T>
    T S<T>::f() {
        return T{};
    }

.

    // templates.cpp
    #include "s.h"
    template struct S<int>;

.

    // main.cpp
    #include "a.tpl.h"
    int main() {
        S<int> b{};
        return b.f();
    }

(tested with `clang` and `g++`)

**Comment by paolobolzoni** [comment]
Can you argue a bit more? It is always possible to use the `.h` file if needed, why do you think it is easy to get wrong?

**Comment by jwakely** [comment]
If you want to structure your code this way, that's fine. It doesn't belong in the guidelines as a recommendation for everybody to follow.

**Comment by scraimer** [comment]
paolobolzoni, the main issue I see with this sort of arrangement is that it introduces extra maintenance. There a whole other file you have to maintain that isn't always going to be checked by the compiler (since you're not always including both).

The guidelines are meant to be a list of recommended practices. Not only that, but practices that should apply generally to the **entire** C++ developer population. This seems more like a solution to personal problem.

It's a neat idea, though. Do you mind if I steal it for my next project? With a bit of tooling to auto-generate the headers and a CI to continually test the headers, it should be very useful for reducing compile times.

**Comment by paolobolzoni** [comment]
Feel free to use it, I do not think this idea is original anyway. (I noticed I swapped `.h` and `.tpl.h` few times in the first comment. Now fixed.)

However, I am not sure I see the problem you mention, it is true that the compiler won't see the `.tpl.h` file all the time (that's the point) but if you change the `.h` file your build tool should recompile also the `.tpl.h` because it includes it; together with all the other files that include that header. And if for any reason you forgot to initialize one kind of template you will get a linker error.

As mentioned by jwakely you may have a problem if make a new header with specialized templates (for example because you cannot change the `.tpl.h`) and and in the file with initializations you include the `.tpl.h` and not your header. The compiler may happily compile the templates ignoring the existence of the specializations and your linker will happily use the result.

**Comment by hsutter** [comment]
Editors call: This is trying to address a real problem, with one style of use, but we think the more general solution is to use modules to address the underlying issue, and so we think we shouldn't add a Guideline at this time.

**Comment by paolobolzoni** [comment]
Modules are not standard, wouldn't be better to update the guidelines
when (and if) modules are standard?
