### ISSUE TITLE
Ref-qualifying assignment operators of Regular types

### ISSUE THREAD

**Issue by johelegp** [isocpp/CppCoreGuidelines#1296]
A few times I've seen mentioned the possibility of creating a guideline for the community about `&`-qualifying the assignment operator for [`std::Semiregular`](https://wg21.link/concepts.object) types because "that's what `int`s do." Is that a tried-and-true best practice fit for the C++ Core Guidelines that we should be following?

Indeed, `42 = 1729` is an ill-formed expression. But [`42s = 1729s`](https://godbolt.org/z/DXAqvJ) works and evaluates to a reference to a temporary.

Regular types like `std::chrono::seconds`, which are strong types for arithmetic types, have even more operators that return `*this` which are similarly ill-formed for prvalues of arithmetic types, like `17 += 3` vs `17s += 3s`. Should those be addressed, too?

**Comment by jwakely** [comment]
> Is that a tried-and-true best practice fit for the C++ Core Guidelines that we should be following?

No, it's not common at all in my experience. It sounds like a solution looking for a problem.

**Comment by hsutter** [comment]
@jwakely I don't think I ever said to return const (but it's it's possible I might have done that briefly in the 90s) -- I know for sure Scott Meyers said that. The trouble with that has been that interferes with template instantiation and other things.

**Comment by hsutter** [comment]
Editors call: We don't think we should be teaching people about &-qualification as a standard practice.
