### ISSUE TITLE
C.67: syntax error in example

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1297]
In 

```c++
auto d = make_unique<D>();
auto b = d.clone(); // ok, deep clone
````

we should have used '->' instead of '.'

```c++
auto b = d->clone(); // ok, deep clone
```

**Comment by jwakely** [comment]
Thanks. Could you send a pull request to fix it please?

**Comment by hsutter** [comment]
It looks like that text moved to C.10 somehow? We don't see it in C.67.

I'll go fix it in C.10, please reopen this if we missed a `.clone` somewhere.

**Comment by cubbimew** [comment]
There was some confusion here because http://isocpp.github.io/CppCoreGuidelines was outdated and the version of C.67 there was different from the one in master. It is now up to date.
