### ISSUE TITLE
Guarantee freedom from undefined behavior

### ISSUE THREAD

**Issue by DemiMarie** [isocpp/CppCoreGuidelines#1299]
Programs that follow all of the Guidelines, and do not contain any suppression annotations, should be guaranteed to be free of undefined behavior, even if they are multi-threaded.  This is the same guarantee that Rust makes for programs that do not use `unsafe`, and is subject to the same caveats: there could be bugs in the toolchain used to build the program, the linter used to check conformance to the Guidelines, or in the OS or hardware the program runs on.

**Comment by jwakely** [comment]
That property was designed into Rust from the beginning, it's not something you can add to C++ later with some heuristic checkers and English prose.

**Comment by DemiMarie** [comment]
@MikeGitb The guidelines could request users to use (non-standard) compiler flags (such as `-ftrapv`, `-fwrapv`, or `-fsanitize=undefined`) which make signed integer overflow well-defined.  That said, this is arguably a bug in the standard.

@jwakely I know it will be hard.  I still believe that it is worthwhile.

**Comment by jwakely** [comment]
Not hard, impossible.

**Comment by brenoguim** [comment]
@DemiMarie undefined behavior on integer overflow allows the compiler to assume that `some_int + 1 > some_int`, which allows optimizations. Other undefined behaviors also allow optimizations.
We don't want to lose that, do we?

**Comment by DemiMarie** [comment]
@brenoguim if we want to guarantee freedom from memory corruption security vulnerabilities, then yes, we do want to lose that.  If the optimization is desired, then either the compiler or the programmer would need to provide proof that it is valid.

**Comment by brenoguim** [comment]
@DemiMarie so it's a trade-off on performance by default and safety by default. Why should we choose one over another?

**Comment by DemiMarie** [comment]
@brenoguim We need secure-by-default.  Virtually every program handles untrusted data.

**Comment by jwakely** [comment]
What you describe is a fine thing, but it's not C++ today, and probably isn't going to be C++ tomorrow either. Sanitizers and other tools already exist, but they're imperfect, not available on all systems, and not usable in all environments.

Saying that the guidelines should require their use, and that this will somehow guarantee no UB in C++ programs, is an unrealistic and unhelpful goal.

If you want Rust, use Rust.

**Comment by brenoguim** [comment]
@DemiMarie  Well, mine doesn't.
This is the point I wanted to make. The community is very diverse, and many (like me) use C++ because it brings performance by default and if safety is needed, then that is solved by having stronger process (like review) around that code.

**Comment by hsutter** [comment]
Editors call: Even with a blank slate, it is not at all clear that "no UB" is the right answer, because not all UB is the same and some UB is actively desirable even if we were designing a brand new systems programming language. See the [CppCon talks on undefined behavior](https://www.google.com/search?q=cppcon+undefined+behavior) which show examples of both bad UB (which totally exists) and good useful UB.
