### ISSUE TITLE
GSL.assert Expanding support for contracts

### ISSUE THREAD

**Issue by johelegp** [isocpp/CppCoreGuidelines#1302]
With [contract attributes](https://wg21.link/dcl.attr.contract) now part of the C++20 WD, we could benefit if [GSL.assert](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#SS-assertions) was expanded accordingly. But how close to the contract attributes should these GSL macros be?

**Comment by hsutter** [comment]
Editors call: We should postpone this until C++20 contracts are finalized.

**Comment by johelegp** [comment]
Reopening for C++23.
