### ISSUE TITLE
ES.20 Always initialize variable -- enforces bugs are not detected

### ISSUE THREAD

**Issue by danmar** [isocpp/CppCoreGuidelines#131]
Thank you for writing these guidelines. Helping people write robust code is great.

I am against the rule ES.20 -- Always initialize variable

I sometimes write code that has some bug in it. By mistake of course. Then, if this bug is detected by a tool I use there is not much harm done. But preventing that it is detected sounds bad to me.

Initializing variables does ensure that there are not uninitialized variables. However it is well defined that it is a bug to use uninitialized variables. Therefore static analysis tools and dynamic analysis tools look for this bug. No combination of tools is perfect as far as I know but imho most of these bugs are found using such tools.

Initializing variables prevents that tools can discover subtle bugs. For instance:

    int i, j;
    if (a) i = j = 1;
    else  j = 2;  // <- forgot to assign i in this else
    return i+j;

If i and j are initialized. then it is not well defined if there is a bug or not. and then tools can't warn about that code.

Subtle bugs are very common. So preventing that subtle bugs are found is a big mistake.

For information I am a open source static analysis tool developer.

**Comment by galik** [comment]
It could be argued that what you are doing here is *complex initialization* whereby you don't want to initialize the variables first to zero and immediately after to their desired initial value. Rule `ES.20` does *sort of* have an exception for this:

> "Exception: It you are declaring an object that is just about to be initialized from input, initializing it would cause a double initialization."

But it later goes on to contradict that exception:

> "Don't consider simple variables that are targets for input operations exceptions to this rule"

It might be good to broaden the scope of  that exception beyond *initialization from input* to *complex initialization* in general. 

There is also the point that if you give a variable an initial value like `0` (just for the sake of *following the rule*) when it is supposed to be initialized from (say) a function call *out parameter* (like input) or other *complex initialization* then that `0` could be a meaningless or bad value and may itself be a hard to detect bug waiting to manifest.

**Comment by danmar** [comment]
I only wanted to prove my point with a simple example, we can scale up this problem to general code of any size. Hiding subtle bugs is always bad, I see no exceptions to that.

I do believe it's often a good idea to initialize variables. Tools can tell you when this is a good idea - you get warnings about uninitialized variables.

I think like a tool developer. If people start following this guideline and do it even where you have written exceptions, then they start hiding subtle bugs. If I try to enforce this guideline in a tool it will not be good - users will probably hide subtle bugs to make my tools happy. I don't want to work hard on a checker and then the result is hidden bugs in software.

**Comment by galik** [comment]
@danmar I'm agreeing with you.

GCC already tells me if I use an uninitialized variable and it's smart enough not to complain if I don't assign a variable a value at declaration as long as that variable is passed to a function that promises to give it a value (by accepting it by reference). Or if it is given a value by other means before use.

So it seems to me that tools are already smart enough that this rule in its current form is too rigid.

I feel it might be better to say "always initialize an object" with the proviso that *complex initialization* is completely acceptable as "initialization".

So your example would be fine:

    int i, j; // complex initialization follows
    if (a) i = j = 1;
    else  j = 2;  // <- forgot to assign i in this else
    return i+j; // <- compiler is smart enough to catch this

As would user input.

    int i;
    cin >> i;

If the above fails it would be because the programmer failed to check the error state to make sure the initialization succeeded, ie. they broke a different rule.

**Comment by danmar** [comment]
ok thanks.

**Comment by hsutter** [comment]
Let's add the example to the guideline and emphasize that taking the complex initialization into a separate function can better.
