### ISSUE TITLE
Link for Static analysis tools is broken

### ISSUE THREAD

**Issue by scholervb** [isocpp/CppCoreGuidelines#1323]
Hi,

In section P.12: Use supporting tools as appropriate
the link for Static analysis tools<https://github.com/isocpp/CppCoreGuidelines/blob/master/??? >
 is broken.

Update: for Testing tools also link is broken

Thanks
Vijay

**Comment by hsutter** [comment]
Editors call: Thanks. the `???` is a placeholder to remind us to write a future section.
