### ISSUE TITLE
Yoda conditions

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#1324]
Please can you add a few lines on "Yoda conditions" to the guidelines.

https://en.wikipedia.org/wiki/Yoda_conditions

Rational: It's something I often see in other code, thus I would like to know if the CppCoreGuideline team encourage or discourage its use.

**Comment by hsutter** [comment]
Editors call: We neither encourage nor discourage it, it's really a matter of style rather than something we would have a Guideline for.
