### ISSUE TITLE
CP.44 unnamed locks might be fine

### ISSUE THREAD

**Issue by fekir** [isocpp/CppCoreGuidelines#1325]
Rule CP.44 states that there should be no unnamed `lock_guards` and `unique_locks`, because temporaries get out of scope immediately.

This is not completely true, since

````
std::mutex m{};
std::vector<T> a = {...}
auto v = (std::lock_guard<std::mutex>{m}, void(), a[0]); // copies elemt out of vector
````

and

````
std::mutex m{};
std::vector<T> a = {...}
auto v = [&](){
        std::lock_guard<std::mutex> _{m}; // need to remember to give a name I'll never use
        return a[0];
}();
````

are equally safe.

Nevertheless I think that the first version, even with `, void(),`, is easier to read and use, and harder to misuse (there is no possibility to forget to name the lock) even if normally using the comma operator leads to more complex code.

i think the rule should state that one needs to ensure that the lifetime of a lock is long enough.

**Comment by MikeGitb** [comment]
Personally, I find the second version more readable, but more importantly, I think a simple rule without exceptions is easier to teach and enforce than considering every exception that might lead to slightly more elelegant code in some corner cases.

Is this a real example you encountered?
Was there no other way to stick to the simple rule than by using a lambda?

**Comment by tghesp** [comment]
Ff uitproberen, wat word het type van v?

**Comment by hsutter** [comment]
Editors call: While the first code works, it's subtle and fragile (easy to break under maintenance). So we don't think we should alter the rule right now in order to accommodate that style.

**Comment by fekir** [comment]
@MikeGitb 
I guess the rule ``no variable without names`` should then hold for a lot more use-cases, since most of the case they do not make much sense... expect when they do.

`auto v = (std::lock_guard<std::mutex>{m}, void(), a[0]);` also reads better since it looks like a single statement, just like `(std::lock_guard<std::mutex>{m}, void(), ++i);`.
The operation and mutex belong together, not splitted on different lines (one could argue they belong in a function, that's a different story).
This reasoning holds only because those operation are single statements, I'm not advocating to "compress" multiple operations on a single line with he comma operator.


@hsutter 
Under what conditions is the code with the comma operator easier to break?
I actually think that the first piece of code is easier to maintain because it is easier to notice when introduces a bug.

Consider

````
std::mutex m{};
std::vector<T> a = {...}
auto v = [&](){
        std::lock_guard<std::mutex> _{m}; // need to remember to give a name I'll never use
        return a[0];
}();
````

If someone refactors it/removes the lambda, it changes too

````
std::mutex m{};
std::vector<T> a = {...}
std::lock_guard<std::mutex> _{m};
auto v = a[0];
````

and now the scope of `_` is too big, and AFAIK no tool (sanitizers, valgrind, static analyzers...) will give you a hint.


On the other hand, if

````
std::mutex m{};
std::vector<T> a = {...}
auto v = (std::lock_guard<std::mutex>{m}, void(), a[0]);
````

gets refactored too

````
std::mutex m{};
std::vector<T> a = {...}
std::lock_guard<std::mutex>{m};
auto v = a[0];
````

we have multiple tools that are able to complain.

Static analyzers or compiler are able to trigger a warning, since the mutex does not protect anything. Thus the code is suspicious.
Dynamic analyzers like valgrind and sanitizers will complain that `a` has been accessed from multiple threads or without locking the mutex.

The first refactored example is correct but suboptimal, which can be a major issue, but also difficult to correct.
The second sample breaks, but we have multiple tools to assist us to avoid this type of bugs while changing the code.


It is also easier to avoid bugs when copy-pasting (a common practice), since with the lambda one could carelessly copy the line `return a[0];` without the mutex, while with the comma operator, it's impossible (or very hard) not to notice the lock.

Yes, dynamic analyzers would spot this bug, but with the comma operator we would avoid the error even before compiling the code/in more circumstances.
