### ISSUE TITLE
Per.7: example code isn't working

### ISSUE THREAD

**Issue by Deophius** [isocpp/CppCoreGuidelines#1337]
It seems that someone wrote `r.first()` instead of `r.first`, so the code won't compile.
Or is it some other library we are using, not ISO standard library?

**Comment by neithernut** [comment]
Apparently, Per.9 doesn't exist. Did you mean [Per.7](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#per7-design-to-enable-optimization)? It does contain the following example:

    auto r = equal_range(begin(c), end(c), 7);
    for (auto p = r.first(); p != r.second(), ++p)
        cout << *p << '\n';

**Comment by Deophius** [comment]
Yeah, thanks.

**Comment by cubbimew** [comment]
Definitely a typo. There's another one on the same line: comma instead of semicolon.
