### ISSUE TITLE
Conflicting clone() advice (C.67 and C.130)

### ISSUE THREAD

**Issue by hans-erickson** [isocpp/CppCoreGuidelines#134]
The guidelines provide conflicting advice for implementing a clone() method.

C.67 states: "Don't let this tempt you into returning an owning raw pointer; this is a minor drawback compared to the major robustness benefit delivered by the owning smart pointer."

C.130 gives an example in which the clone() method does, indeed, return a raw pointer, and notes: "Note that because of language rules, the covariant return type cannot be a smart pointer."

I might suggest the following as an initial straw man for how to allow cloning of a derived class with a smart pointer. This has some drawbacks, perhaps some of which I am not aware, but I'm hoping that some variation of this technique might be suggested as an alternative:

```
class base {
public:
    inline std::unique_ptr<base> clone()
        { return do_clone(); }

private:
    virtual std::unique_ptr<base> do_clone() =0;
};


class derived : public base {
public:
    inline std::unique_ptr<derived> clone()
        { return std::make_unique<derived>(); }

private:
    virtual std::unique_ptr<base> do_clone();
};

///...

std::unique_ptr<base> derived::do_clone()
{
    return std::make_unique<derived>();
}
```

**Comment by AndrewPardoe** [comment]
We'll consider adding an exception to C.67 referring to C.130. Thank you for the suggestion!

**Comment by hsutter** [comment]
Improved the examples and added cross-references.
