### ISSUE TITLE
F.41 needs to be heavily qualified; example must be redone

### ISSUE THREAD

**Issue by andralex** [isocpp/CppCoreGuidelines#135]
The example in F.41 reads:

```C++
int f( const string& input, /*output only*/ string& output_data ) { // BAD: output-only parameter documented in a comment
    // ...
    output_data = something();
    return status;
}

tuple<int,string> f( const string& input ) { // GOOD: self-documenting
    // ...
    return make_tuple(something(), status);
}
```

In fact the BAD version may as well be good and the GOOD one, bad. Consider:

```C++
for (auto&& item : many_items) {
    auto result = f(item);
    ...
}
```

This is ouchworthy because it creates and destroys a string compulsively with every iteration. In contrast, the version deemed bad fares quite a bit better:

```C++
string data;
for (auto&& item : many_items) {
    auto result = f(item, data);
    ...
}
```

In this case memory is (re)allocated only when the current data does not have enough capacity. Howard Hinnant, Eric Niebler are good to talk to for this kind of stuff.

**Comment by galik** [comment]
Also I suspect returning a `tuple` to a `tie` is maybe going to conflict with `RVO`?

**Comment by AndrewPardoe** [comment]
Thank you! This is related to issue #1. Assigning this to Herb.

**Comment by hsutter** [comment]
This is covered in the "Exception" -- if you want to reuse a string's or vector's additional capacity, you're really treating it as an in/out parameter because you're viewing the capacity as part of the input.
