### ISSUE TITLE
C.21: mention `boost::noncopyable`

### ISSUE THREAD

**Issue by loskutov** [isocpp/CppCoreGuidelines#1354]
Inheriting from `boost::noncopyable` is a common way to make a class non-copyable, as an alternative to explicitly `delete`ing 4 special member functions. I think it would make sense to mention whether this idiom is encouraged by the guidelines or not.

**Comment by ifknot** [comment]
I think prefer public default and delete keywords makes explicit the design decisions and behaviour wrp copyable and moveable over oddly named syntactic sugar of boost::noncopyable.

JT

Source: iPhone


On 25 Feb 2019, at 10:25, Ignat Loskutov <notifications@github.com<mailto:notifications@github.com>> wrote:


Inheriting from boost::noncopyable is a common way to make a class non-copyable, as an alternative to explicitly deleteing 4 special member functions. I think it would make sense to mention whether this idiom is encouraged by the guidelines or not.

**Comment by MikeGitb** [comment]
Just saying: Achieving the same as boost::noncopyable requires only the deletion of 2 functions.

However, as it  is makes the class not just non-copyable, but also  non-movable,  (which may or may not be intuitive), I find it much better to declare all the operations explicitly.

**Comment by beinhaerter** [comment]
That may be a common pattern for users of boost. But why should someone add a dependency on boost in his projects just to prevent having to write 2-4 lines? In my opinion the CppCoreGuidelines - part of the name is *core* - should use plain C++ and not reference other libraries.

**Comment by loskutov** [comment]
It's not hard to write a similar class by hand, so it's a common idiom regardless of boost.

**Comment by loskutov** [comment]
Also, some parts of Boost (e.g. `intrusive_ptr`) are already referenced by the guidelines.

**Comment by beinhaerter** [comment]
> Also, some parts of Boost (e.g. intrusive_ptr) are already referenced by the guidelines.

Yes, but that is in two example sections, the coding rules sections and in two links. I do not see any guideline suggesting to use Boost.

**Comment by jwakely** [comment]
`boost::noncopyable` is a C++03 idiom. Deleted functions are the right way to do it now.

**Comment by hsutter** [comment]
Editors call: As @jwakely said, `boost::noncopyable` was a useful type but it has been superseded, prefer to use `=delete`.
