### ISSUE TITLE
R.14: "what do we recommend???"

### ISSUE THREAD

**Issue by dksmiffs** [isocpp/CppCoreGuidelines#1355]
We explicitly recommend `gsl::span` for this purpose in [P.4](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#p4-ideally-a-program-should-be-statically-type-safe).  So is that definitely the recommended approach, or is it an "alternative", as suggested in [R.14](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r14--array-vs-pointer-parameter)?  Recommend removing uncertainty and/or duplication if we can.

**Comment by hsutter** [comment]
Editors call: Agreed, thanks!
