### ISSUE TITLE
C.150 misses another reason to use make_unique

### ISSUE THREAD

**Issue by yegord** [isocpp/CppCoreGuidelines#136]
The another reason is exception-safety:

```c++
// Not exception-safe: T2() may throw after T1() was constructed
// and before unique_ptr<T1> was constructed.
f(unique_ptr<T1>(new T1()), unique_ptr<T2>(new T2())); 

// Exception-safe: calls to functions are not interleaved.
f(make_unique<T1>(), make_unique<T2>()); 
```

Herb's article on the topic: http://herbsutter.com/gotw/_102/

**Comment by AndrewPardoe** [comment]
Good suggestion, thank you! Have you submitted a PR?

**Comment by yegord** [comment]
You are welcome. Created a pull request.
And thanks to @hsutter for writing the article in the first place. :-)

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

Herb will review this. It might be solved by order-of-evaluation specification but we should at least amend this item for older compilers (such as all those existing today.)

**Comment by hsutter** [comment]
Added, thanks! I editing in your PR change by hand because the PR was a little stale (my fault, sorry for the lag on this).
