### ISSUE TITLE
Should #if macro check defined?

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#1360]
There is a risk a programmer might use

#if SECURITY_ON
// secure code clear ram etc
#endif 

Unfortunately if they didn't #define SECURITY_ON then this wouldn't even give a warning...
g++ has -Wundef  but that is not on by default

What's your opinion? the workaround seems clunky
#ifndef SECURITY_ON
#warning error SECURITY_ON not present
#else 
#if  SECURITY_ON
// secure code clear ram etc
#endif 
#endif  

This is better at least (I'm assuming left to right evaluation order...)
#if defined(SECURITY_ON) && SECURITY_ON

**Comment by jwakely** [comment]
> This is better at least (I'm assuming left to right evaluation order...)
> #if defined(SECURITY_ON) && SECURITY_ON

Now if you have a typo in the macro name (e.g. the macro you're supposed to be checking is `SECURITY_IS_ON`) you can't use `-Wundef` to detect it. The way some projects use `-Wundef` is exactly what you say is a risk.

There is no foolproof solution, and I certainly don't think advising against `#if FOO` is a good idea.

**Comment by jonnygrant** [comment]
Actually my example was bad

> This is better at least (I'm assuming left to right evaluation order...)
> #if defined(SECURITY_ON) && SECURITY_ON

This doesn't give any build warning

// g++-8 -Wundef -Wall -Wextra -o undef undef.cpp
#include <cstdio>

int main()
{
#if defined(SECURITY_ON) && SECURITY_ON
    printf("SECURITY_ON\n");
#endif

return 0;
}

**Comment by jonnygrant** [comment]
Pretty horrible, but this is a way to do it without -Wundef

// g++-8 -Wundef -Wall -Wextra -o undef undef.cpp
#include <cstdio>

//#define SECURITY_ON 0

int main()
{
#ifndef SECURITY_ON
#error SECURITY_ON not defined
#elif SECURITY_ON
    printf("SECURITY_ON\n");
#else
    printf("SECURITY_ON not active\n");
#endif

return 0;
}

**Comment by jwakely** [comment]
That seems fine to me. If you have a macro which needs to be explicitly defined, then you should enforce that in code.

**Comment by jonnygrant** [comment]
If C++ spec could introduce a new pre-processor directive for next version of C++, that would be clearer. eg #ifset

I'm not in touch with C++ standards committee to propose it though.

Example below, would generate this error

undef.cpp:9:2: error: #ifset requires SECURITY_ON to be set
 #ifset SECURITY_ON
  ^~~~~


int main()
{
#ifset SECURITY_ON
    printf("SECURITY_ON\n");
#else
    printf("SECURITY_ON not active\n");
#endif
return 0;
}

**Comment by jwakely** [comment]
I think we have far bigger problems to solve.

**Comment by hsutter** [comment]
Editors call: It's not clear that this is common enough to write a suitable guideline at this time.
