### ISSUE TITLE
F.6 Explicit Default Constructors Should Not Be Considered a Low-Level Function

### ISSUE THREAD

**Issue by BlackStarX42** [isocpp/CppCoreGuidelines#1367]
As mentioned in NR.5, it is not recommended to avoid substantive work in constructors. In my opinion this also includes default constructors. While in many cases, the work in default constructors is simple (low-level) and does not exceed trivial initialization of variables, there is also a category of use cases where it is necessary to do high-level tasks, e.g. resource allocation. Consider certain cases of smart pointers where the initialization of the inner pointer must happen the moment the object is created because it cannot be delayed until the call of any other function of that object.

Because the work of such a default constructor is not low-level anymore, you mark it as `explicit` (because you don't want to risk calling it implicitly). A typical side effect of such a high-level default constructor is that it may throw (e.g. because of the resource allocation), which is why the guideline cannot be applied anymore.

I suggest to add this supplement to the guideline:
- Default constructors which are marked as `explicit` should not be considered a low-level function.

**Comment by johelegp** [comment]
I don't think that applies to smart pointers. The underlying pointer is initialized to `nullptr` in the default constructor, and are thus `noexcept.

**Comment by MikeGitb** [comment]
What exactly are the semantics of a explicit default constructor anyway? And what do you mean by low level?

**Comment by cubbimew** [comment]
> As mentioned in NR.5, it is not recommended to avoid substantive work in constructors

You may have misread it due to double negation (if #1356 is accepted, it will be made clearer). The rule says avoiding substantive work is wrong.

**Comment by cubbimew** [comment]
> A typical side effect of such a high-level default constructor is that it may throw (e.g. because of the resource allocation), 

This would contradict F.6, which says "default constructors should never throw"

> Because the work of such a default constructor is not low-level anymore, you mark it as explicit (because you don't want to risk calling it implicitly).

`explicit` doesn't have that effect.

**Comment by BlackStarX42** [comment]
> I don't think that applies to smart pointers. The underlying pointer is initialized to nullptr in the default constructor, and are thus `noexcept.

I am not talking about smart pointers. I am talking about plain pointers, which are still sometimes necessary, for instance when writing an adaptor for a C library:

```
struct SomeOldschoolCType;

SomeOldschoolCType* CreateSomeOldschoolCType();

class NewCppType
{
	SomeOldschoolCType* Data;

public:
	NewCppType()
	{
		Data = CreateSomeOldschoolCType();
		// checking error conditions here, memory allocation failure might be one of them:
		if (Data == nullptr)
			throw std::bad_alloc();
	}
	// move semantics + destructor go here of course :-)
};
```
Consider I cannot delay the call to CreateSomeOldschoolCType() because it has some side effects, so I *need* to do it in the default constructor.

> What exactly are the semantics of a explicit default constructor anyway?

> > Because the work of such a default constructor is not low-level anymore, you mark it as explicit (because you don't want to risk calling it implicitly).
> 
> explicit doesn't have that effect on default constructors.

Now that you both mention it, I should have tested it. I assumed that `explicit` has the same effect on a default constructor as on every other constructor: you have to name the type when creating a new object. Obviously that assumption was a bit reckless. At least I have always used it in cases like that to make my intention explicit that this constructor indeed might do something time-consuming or even throw an exception.

> And what do you mean by low level?

I mean it in the meaning of F.6: A low-level function is a function that is expected to work transparently or do nothing but simple tasks like variable assignments, e.g. the move constructor and assignment operator or the swap function.

> A typical side effect of such a high-level default constructor is that it may throw (e.g. because of the resource allocation),
> 
> This would contradict F.6, which says "default constructors should never throw"
 
That's why I'm arguing that this is reasonably *not* always the case. Even default constructors might *have* to do something that causes an exception. I don't agree to the approach to always make default constructors ```noexcept``` as this would frequently introduce additional and unnecessary internal states in a class. In the case above, someone would have to add an Initialize() function and you would have to bother with the case when you call it twice. Also, the user of the class would have to always remember to call it. These pitfalls are all just purely unnecessary from an OOP point of view. Why not just initialize the class *completely* in the constructor (even if it is a default one).

So, how about we just give ```explicit``` default constructors a real meaning by interpreting such constructors as not meant to be called implicitly?

**Comment by hsutter** [comment]
Editors call: We agree with the advice as it stands, it's suspicious to have a default constructor that could throw. However, we've updated F.6 with a cross-reference to C.44 which covers this in more detail.
