### ISSUE TITLE
C.126 Constructors in Abstract Classes Are Totally Valid in General

### ISSUE THREAD

**Issue by BlackStarX42** [isocpp/CppCoreGuidelines#1368]
Abstract classes are classes which have at least one abstract ("pure virtual") function. This does *not* imply that the class itself has no functionality in terms of other function definitions, in fact even the abstract function is allowed to have a definition to serve as a base functionality for inherited classes. In general, if you put several functions with definitions together into one class, they access a common state. This state is stored in non-static member variables of that class, which may need to be initialized by a constructor. So having a constructor in an abstract class is totally correct in general.

There are special instances of abstract classes which have no function definitions, so that such a class has no state. Consequently, the class has no need for member variables. Consequently, the class needs no constructor. Such a case is commonly referred to as an "interface". C++ lacks the concept of real interfaces, which makes it necessary to write abstract classes for that purpose. That does *not* mean that abstract classes generally are interfaces. Interfaces are special cases of abstract classes, not vice versa.

With the current wording of the guideline, especially the word "typically", I see the risk that all abstract classes may be treated as interfaces just because interfaces are the most common use of abstract classes. In my opinion, the wording of the guideline is chosen in such an opaque way that it makes it difficult to implement a correct analysis for it, i.e. one that minimizes the number of false positives.

Some considerations:
- If you disallow constructors, you would also have to disallow non-static data member initialization. Otherwise you could disable the guideline easily with it.
- A class with a state (or a base class with a state), basically a non-empty type, must be allowed to initialize its state in a constructor, no matter if it is abstract.
- Public constructors of an abstract class cannot be called meaningfully from outside.

I suggest to replace the current guideline with 2 more meaningful ones:
1) An empty class/struct should have no constructor.
2) An abstract class/struct should have no public constructors.

**Comment by cubbimew** [comment]
>  a base class with a state

...contradicts the Enforcement of C.121 "Warn on any class that contains data members and also has an overridable (non-final) virtual function"

**Comment by MikeGitb** [comment]
Maybe off topic but I think c.121 is actually bad advice.

**Comment by BlackStarX42** [comment]
In my opinion the enforcement of C.121 is too strict for the intended goal. The goal of C.121 is to avoid non-static data members in interfaces, which sounds reasonable. But the presence of an overridable virtual function does not indicate an interface. An interface is an abstract class which has only pure virtual functions without definitions. This also applies to its base classes recursively (or rather base *interfaces*). As soon as a class has a definition for *any* non-static member function, this function could access a state of the class. Thus, such a class is not an interface anymore.

**Comment by hsutter** [comment]
Editors call: For C.121, perhaps change

* Warn on any class that contains data members and also has an overridable (non-`final`) virtual function.

to

* Warn on any class that contains data members and also introduces a new overridable (non-`final`) virtual function.

**Comment by BjarneStroustrup** [comment]
Clarified as decided
