### ISSUE TITLE
C.20/C.21 As the Rule of Zero and the Rule of Five Are Allowed, the Rule of Three Should Be Too

### ISSUE THREAD

**Issue by BlackStarX42** [isocpp/CppCoreGuidelines#1369]
Guideline C.20 requires to implement none of the special member functions in cases where it is not necessary, so this guideline demands the developer to rely on the compiler and language automatism to define or delete these functions according to the language standard. Guideline C.21 requires to write down all 5 special member functions as soon as the developer writes any of them, so the guideline demands the developer to *not* rely on the compiler and language automatism to delete a function according to the language standard. This is an inconsistency.

The essence of C.21 is to write all 5 special member functions because "stating the intent explicitly for each special member makes it more obvious to the reader." So one could justifiably argue, that writing all 5 special members makes it more obvious even in case of C.20, where *all* of them are defaulted. Besides, the wording of C.20 is chosen in such an opaque way that it makes it difficult to implement a correct analysis for it, e.g. how does an algorithm decide that one "can avoid" default operations? In contrast to the depiction of the guideline, it is *not* a safe criterion if all non-static member variables support all the special member functions. Consider a class which has one variable containing a map and one variable containing an iterator referencing an item in that map.

It is not a mistake to rely on compiler and language automatisms. The whole point of inventing move semantics was to give the developer the *chance* to provide a more effective way to handle constructions/assignments with temporary objects. But it was not invented to suddenly make move semantics *mandatory*. So implementing move semantics next to copy semantics in a class is purely a way to improve the performance but its absence is not an error. If a copy semantics is missing, this will certainly quickly attract attention as soon as it is needed. A common and safe method of implementing a class is to only provide move semantics as long as there is no need for a copy semantics. This is often the intention of a developer. In contrast, writing down all 5 special member functions states a different intention, namely that copy semantics is not intended for that class at all, which is not the case.

Furthermore, guideline C.21 does not consider the possibility of an assignment operator that passes its parameter as value. This is often used for the so called copy-and-swap idiom. When using this idiom, to define a move or copy assignment operator is usually an error.

Finally, guideline C.21 does not take into account the special case of empty classes. Whenever a class is empty (i.e. does not contain non-static member variable and does not have any base class with a non-static member variable), a deviation from the guideline has no harmful effect. A frequent example are interfaces (i.e. abstract classes with no non-static member function/variable definitions), which require to provide a virtual or protected destructor to allow for correct deletion of instances of derived classes through a base class pointer. Naturally one does not want to write down all other 4 special member functions just because "stating the intent explicitly for each special member makes it more obvious to the reader." Nothing would be made more obvious to the reader that way in this case.

As long as C.20 is a separate guideline and developers have the chance to disable it, it is ok to leave it in, though I don't consider it any useful. Also, I suggest to replace C.21 with 2 more meaningful guidelines:
1) A non-empty class/struct should have defined the member function combination specified by one of the 14 columns:

|                       |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|-----------------------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| Move Constructor      |   | + |   | + | + |   | – |   | + | + | – | + | – | – |
| Copy Constructor      |   |   | + | + |   | + |   | – | + | – | + | – | + | – |
| Move Assignment Operator   |   |   |   |   | + |   | – |   | + |   |   | + | – | – |
| Copy Assignment Operator   |   |   |   |   |   | + |   | – | + |   |   | – | + | – |
| C'n'S Assignment Operator  |   | + | + | + |   |   |   |   |   | + | + |   |   |   |
| Destructor            |   | + | + | + | + | + | + | + | + | + | + | + | + | + |

Where an empty cell means that the function is not defined by the developer, a plus means that the function is defined by the developer as non-deleted and a minus means that the function is defined as deleted by the developer.

This guideline is to satisfy the Rule of Zero/Three/Five and to spot the obvious errors.

2) A non-empty class/struct should have defined the member function combination specified by one of the 6 right-hand columns in the table above if C.20 does not apply for that class/struct. This guideline is to make the intention obvious.

Guideline 2) is a restricted version of 1) to allow developers to disable the stronger requirement while still getting reports about obviously wrong combinations of special member functions.

**Comment by beinhaerter** [comment]
I understand your argument that it is unnecessary to write down things (`=default` operations) that the compiler manages itself according to the language standard.
And yes, I sometimes find it quite noisy to write all the `=default` lines.
But yet I do it because it makes the intent clear. Especially for developers that are not 100% sure which constructors and assignment operators the compiler generates in which cases.

Regarding your proposal I don't think that your guideline 1 would help me. C.21 as written now is easy to understand, to remember and to follow. Your guideline 1 is nothing that I could remember. If I would remember your guideline then probably only because it just summarizes what the language standard says. But de facto I would remember the rules in the standard and then just rebuild in memory your table. I would not remember your table. I would need to rebuild it myself or look it up. In my opinion such a hard to remember guideline is a bad guideline.

**Comment by BlackStarX42** [comment]
> But yet I do it because it makes the intent clear. Especially for developers that are not 100% sure which constructors and assignment operators the compiler generates in which cases.

Well, you can still do exactly this according to the 2nd guideline I proposed. What I suggest is to remove the *need* to do something necessary. It would still be *allowed* though. Actually the 2nd proposed guideline is very similar to the current wording of C.21, except for the lack of the consideration of the copy-and-swap assignment operator, which would still be needed to incorporate.

> Regarding your proposal I don't think that your guideline 1 would help me. C.21 as written now is easy to understand, to remember and to follow. Your guideline 1 is nothing that I could remember.

Why would you need to remember it, there are automatic tools which can do that for you, ideally coupled with the compilation process itself. It is interesting though, the need to remember a guideline is a frequent argument against improving it. It seems no one is aware of the fact that e.g. Visual C++ is already incorporating the rules into the compiler. I am using it so understandably, *my* goal is to design the guidelines in a way they yield as little false positives as possible, because currently the number of false positives is just unmanagable.

**Comment by hsutter** [comment]
Editors call: We try to avoid writing guidelines that enumerate anything that could be useful to somebody. We like that the rule as written now is easy to to understand and remember and follow.

We think the Rule of Three made a lot of sense in C++98, but we now have move operations. If you think there is a compelling reason to add the Rule of Three that would not apply to Two and Four or other combinations, we can consider reopening this issue. At the moment it doesn't seem to rise to the level of clarity of One and Five.
