### ISSUE TITLE
A saturation_cast instead (or in addition) to narrow_cast.

### ISSUE THREAD

**Issue by p-groarke** [isocpp/CppCoreGuidelines#1382]
`narrow_cast` is interesting for certain fields of c++, but many others would be best served by a `saturation_cast` (or `clamp_cast`). For example, any industry that doesn't use exception, or in situations where you are sanitizing user input.

When using `narrow_cast`, one has to do checks himself every time he casts, even if he desires saturation of the input value. A lot of times, saturation is the "correct" approach.

I've written a quick and dirty prototype, you can find it here : https://github.com/p-groarke/clamp_cast

I believe many programmers would be best serve by this approach.

Good day,
Philippe

**Comment by hsutter** [comment]
Editors call: First, thank you for providing an implementation for your proposal!

These could be useful in the standard library and there are proposals in this direction, including `std::clamp` which is not a type cast but does the clamping operation.

For GSL, we're trying to keep GSL to very common usages including addressing language issues, and narrowing is pervasively common and implicitly done in the language today. It's unclear that saturation and clamping are as pervasively common as narrowing, so they probably wouldn't be appropriate for GSL but they would definitely be good candidates for a numerics library.

**Comment by hsutter** [comment]
Update: This is progressing in the committee as paper [P0543](http://wg21.link/p0543). If it's in `std::` we don't need to consider it for GSL. Does P0543 give you what you need?

**Comment by p-groarke** [comment]
Well I'll be damned :) That paper covers exactly what I need. Thank you!
