### ISSUE TITLE
ES.78 is unclear: is fallthrough on non-empty cases to be avoided?

### ISSUE THREAD

**Issue by lukebradford** [isocpp/CppCoreGuidelines#1392]
ES.78's recommendation is unclear because some of its language is in conflict with its examples. Is the guideline recommending that fallthrough from non-empty `case`s should be avoided?

- "Always end a non-empty `case` with a `break`," "A deliberate fallthrough is a maintenance hazard," and "Flag all fallthroughs from non-empty `case`s" suggest that yes, fallthrough on non-empty `case`s should be avoided, at least in general.
- However, both "good" examples include a fallthrough from a non-empty `case`. (The recommendation to use `// fallthrough` or `[[fallthrough]]` in these cases is absolutely clear.)

If the guideline is recommending that fallthrough from non-empty `case`s should be avoided, I suggest adding a "best" example that does not include fallthrough from a non-empty `case`, e.g.:

```
switch (eventType) {
case Information:
    update_status_bar();
    break;
case Warning:
    write_event_log();
    display_error_window();
    break;
case Error:
    display_error_window();
    break;
}
```

The current "good" examples can be introduced with language like "If you must use a fallthrough on a non-empty `case`, be explicit:"

In this case, I also recommend changing "Always end a non-empty `case` with a `break`" to "Always end a non-empty `case` with a `break` or a `return`" since `return` avoids fallthrough just as well as `break`.

On the other hand, if the guideline is **not** recommending that fallthrough from non-empty `case`s should be avoided, the misleading language should be changed. I suggest:

- Instead of "Always end a non-empty `case` with a `break`," "Explicitly mark fallthrough from non-empty `case`s."
- Instead of "A deliberate fallthrough is a maintenance hazard," "A deliberate fallthrough that is unmarked is a maintenance hazard."
- Instead of "Flag all fallthroughs from non-empty `case`s," "Flag all unmarked fallthroughs from non-empty `case`s."

**Comment by hsutter** [comment]
Editors call: We agree and will push a commit to update these. Thanks!
