### ISSUE TITLE
Distinguish between different enforcement levels

### ISSUE THREAD

**Issue by MikeGitb** [isocpp/CppCoreGuidelines#1393]
As all guidelines and static analysis tools (including compiler warnings), the core guidelines (especially in the enforcement section) have to make tradeoffs between what new code should ideally look like and what checks and guidelines are actually actionable in an existing codebase. I.e. what level of conformance can be enforced, without drowning the user in warnings about code that uses a suboptimal/dangerous pattern, but isn't actually problematic in that particular case.

Two more or less recent issues that come to mind are e.g. https://github.com/isocpp/CppCoreGuidelines/issues/1322 about prefix/postfix and https://github.com/isocpp/CppCoreGuidelines/issues/1370 about virtual member functions. 

In both cases the actual guideline we want people to follow ideally is stricter (but also simpler) than what most people would like to see enforced by a static analysis tool that runs on an existing codebase.

So I wonder if it would make sense if enforcement sections would more often distinguish between different "enforcement levels". E.g.:

- `postfix-basic`: Warn on use of any **user defined** postfix operator whose return value is unused. 
- `postfix-strict`: Warn on use of **any** postfix operator whose return value is unused. 

In a codebase, that so far hasn't tried to follow the strict version so far, the first version has probably a much higher signal to noise ratio and thus higher initial value for the user. I.e. a higher percentage of the warnings will point to actual performance bugs caused by careless use of the postfix operator on types where retaining a copy is expensive.

The second version on the other hand will probably point to a lot of places where it doesn't really matter performance wise, but in the interest of consistency and simplicity it still makes sense to follow the strict rule when writing new code or e.g. run clang-tidy in `-fix ` mode.

**Comment by hsutter** [comment]
Editors call: We do have some of this in the safety profiles (type, bounds, and lifetime safety), so those are sets of rules that can be selected individually. Also, we distinguish between "easy" and "hard" enforcements such as in ES.6. Are you mainly asking for more of one or the other of those? We're concerned that creating levels of enforcement may be come unmanageable.

**Comment by hsutter** [comment]
Also, in 7 some places we identify enforcements that are "to reduce noise" or mention concern about being "noisy" for similar reasons to what you cite -- new "clean" code vs. old code where they would generate more false positives. Are you asking for more of that, such as a "strict, noisy warnings too please" mode?

**Comment by MikeGitb** [comment]
The second. 

Strict rules/guidelines often have the advantage that they are simpler (easier to teach, easier to follow, easier to check automatically), so I  the long term, that's what I prefer. But in a legacy codebase, you have to look more closely if a piece of code that doesn't follow the simple rule is actually a bug/error  prone or is it ok under the specific circumstances.

**Comment by hsutter** [comment]
Editors call: Distinguishing between "legacy" and "new" code is a reasonable distinction that has been suggested before (including by us) but the difficulty we've run into each time was that is was hard to actually bucket the Enforcements into two categories. Making a distinction between 'basic' and 'strict' would be difficult and likely require several iterations through the whole document to get right.

The Guidelines' current default is to say "these are Guidelines intended for modern code written in an encouraged style." In existing code, they can't easily be adopted wholesale by an existing project (unless the Guidelines were toothless and not really providing much value) and so will generally need to be adopted incrementally.

For the moment we've left it to enforcement tools to group the rules and provide ways to turn then on and off, including on/off for specific parts of a code base.

We'll take another look at how to capture more of this in the Gradual Introduction section. And we do need more support for gradual introduction of the rules in an existing code base, which can include better tool support.
