### ISSUE TITLE
Eliminate macros and make settings const

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#1394]
Would be great if there was a way to eliminate pre-processor macros. eg

#define ENABLE_X 1
#if ENABLE_X
const int setting_a = 1;
#else 
const int setting_a = 2;
#endif 

Would be nicer if could somehow express as
const bool enable_x = false;
if(enable_x)
{
const int setting_a = 1;
}
else
{
const int setting_a = 2;
}

Of course this will not work, as setting_a goes out of scope.

A workaround is an inline function
inline int get_setting(bool enable_x)
{
if(enable_x) return 1;
else return 2;
}

So then the code becomes ::
const bool enable_x = false;
const int setting_a = get_setting(enable_x);

At least this means the variables are const, preventing any accidental modification.

**Comment by dksmiffs** [comment]
@jonnygrant, with macros being (unfortunately, a widely used) part of the language, I think these guidelines can only strongly discourage their use. See the following rules: Enum.1, ES.30, ES.31, ES.32

**Comment by jonnygrant** [comment]
Hi Dave, thank you for your reply. Enum.1 would be the only one that might cover my use-case above (how to selectivity initialise a const), but upon reading I don't think Enum.1 applies.

Could a new rule/example be added to show the solution I used? The inline function.

**Comment by MikeGitb** [comment]
I'd rather use an immedeately invoked lambda function - maybe with `if constexpr` where applicable.

**Comment by jonnygrant** [comment]
Hi Mike, that sounds good. I searched and found a few examples https://herbsutter.com/2013/04/05/complex-initialization-for-a-const-variable/
https://www.bfilipek.com/2016/12/please-declare-your-variables-as-const.html

Would be good to add to cpp guidelines this approach.

**Comment by cubbimew** [comment]
Isn't that already there, [ES.28: Use lambdas for complex initialization, especially of const variables](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-lambda-init)

**Comment by jonnygrant** [comment]
Great! I'll close the issue.
