### ISSUE TITLE
CP.2 sort in second "Example, bad"?

### ISSUE THREAD

**Issue by dksmiffs** [isocpp/CppCoreGuidelines#1395]
- Shouldn't the first parameter on `sort` be a `pat` rather than a `par`?
-  Is this intended to be `std::sort` usage? If so, it's not obvious to me which function signature is intended.

I think these stumbling blocks might distract the reader from the core focus of the rule, and we probably want to avoid that.

**Comment by jwakely** [comment]
I think it's calling `std::sort` with the [`par` execution policy](https://en.cppreference.com/w/cpp/algorithm/execution_policy_tag) and a range (the `span`).

**Comment by dksmiffs** [comment]
Same example, what is `find_all`? Are we to assume `boost::algorithm::find_all`, or something else? Or was predictive intended here?

**Comment by cubbimew** [comment]
> was pseudocode intended here? 

Given that the same example has a `read_vec` taking a stream, an std::array, and a size, I'd say yes.

**Comment by hsutter** [comment]
Editors call: We agree `par` and `pat` in the same example is confusing, we'll tweak the example to make it a bit clearer.
