### ISSUE TITLE
ES.22 - Additional example possibly required

### ISSUE THREAD

**Issue by shieldfoss** [isocpp/CppCoreGuidelines#1400]
ES.22 repeats the (good) advice to avoid uninitialized variables, but the second example shows a use case with SomeLargeVariable where it appears hard to avoid. The example from ES.20 with widgets i and j could possibly be linked as a demonstration of how to re-work this type of problem.

**Comment by hsutter** [comment]
Editors call: Thanks, we'll look at improving this.

**Comment by hsutter** [comment]
Here's an example where this comes up all the time:

~~~
array<byte,K> buffer;
if (cond)
    fill_from_database(buffer);
else
    fill_with_default_values(buffer);
~~~

**Comment by shieldfoss** [comment]
Having read further, it appears ES.28 provides some relevant guidance for complex initialization.

**Comment by BjarneStroustrup** [comment]
example added
