### ISSUE TITLE
Is there any plan to provide multi language guidelines?

### ISSUE THREAD

**Issue by soroshsabz** [isocpp/CppCoreGuidelines#1409]
ITNOA

Hi,

Is there any plan to provide any translation of [English guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) to another language in this repo? for example provide Chinese or Arabic ? or add some another repo in isocpp for this? or any other infrastructure for add multi language document for this guidelines

Did you accept PR about this?

Thanks :)

**Comment by cubbimew** [comment]
As noted in https://github.com/isocpp/CppCoreGuidelines/issues/567#issuecomment-205406510 , you're free to fork the guidelines to create a translation, and it helps to mention its location here.
Here are the two current examples mentioned in that discussion:
* https://github.com/CppKorea/CppCoreGuidelines (korean) 
* https://github.com/masterl/CppCoreGuidelines_PT_BR (portugese)

**Comment by hsutter** [comment]
Editors call: Yes, as Sergei mentioned please feel free to create a translation via a fork. Thanks!

**Comment by soroshsabz** [comment]
@hsutter @cubbimew I added Persian translation for CppCoreGuidelines in 

* https://github.com/BSVN/CppCoreGuidelines

Where did you added these locations for tomorrow ?

But I think it is very useful to add these locations in this project that help people to found these.

Thanks
