### ISSUE TITLE
Renaming finally to make_final_act

### ISSUE THREAD

**Issue by trebconnell** [isocpp/CppCoreGuidelines#141]
make_final_act (or make_final)  would be more consistent with other std construction helpers such as make_unique.

Additionally there's danger of finally accidentally being called without assigning into a temporary, thus inducing the destructor to activate immediately.  The static analysis could catch this, or renaming makes this sort of mistake less likely to happen imo.

**Comment by AndrewPardoe** [comment]
We prefer the status quo: we'll keep this as `finally`. See TC++PL 4 on this topic.
