### ISSUE TITLE
Rule C.21 Suggest clarity regarding default constructor

### ISSUE THREAD

**Issue by projectJosh** [isocpp/CppCoreGuidelines#1415]
In Rule C.21, the line "Declaring any special member function except a default constructor, even as =default or =delete, will suppress the implicit declaration of a move constructor and move assignment operator." seems to me to imply that if you declare the default constructor as =default or =delete, it doesn't mean you should/must tinker with the other special members, almost like a Rule of 0.5. If that is the intended meaning, could we make that more clear in the rule, so that people know that they can still follow the rule of zero even when, say, deleting the default constructor of a class to prevent other classes from misusing it?

**Comment by jwakely** [comment]
The text you quoted is just a statement of fact: declaring a default constructor doesn't suppress anything. I don't think it's meant to imply anything, it's just being precise (if it _didn't_ say "except a default constructor" people would point out it was wrong).

How common is it to define the default constructor as deleted and not need to declare any of the other special member functions?

Is it worth complicating the rules with exceptions for special cases that almost never occur in practice?

If you really want to define the default constructor as deleted and not declare the others, and you're confident the effects are clear to yourself and all other readers of the code, then do that. Or just declare the others as defaulted, to be clear and to be consistent with the guidelines.
