### ISSUE TITLE
Rule suggestion: Avoid using raw memory manipulation functions

### ISSUE THREAD

**Issue by ZachHenkel** [isocpp/CppCoreGuidelines#1424]
In the same spirit as R.11: Avoid calling new and delete explicitly, (w)memset, (w)memcpy, (w)memmove and (w)memcmp should be avoided.  These are very sharp tools, and most often should be reserved for library authors.

While we discussed internally if we'd like to raise this issue, a report came in on my company's C++ support mailing list.  Someone was looking for help debugging a crash regarding std::shared_ptr and a "corrupted" control block.  It eventually came out that they had authored code to memcpy shared_ptr objects.

**Comment by JordanMaples** [comment]
To add to this:

Currently, memset and memcmp are used as examples of what not to do, particularly in bounds.4 and SL.Con.3. As an immediate change, we could alter those two rules to include examples and guidance to avoid them, however the issues with clobbered v-tables and corrupted data structures would not be properly conveyed without a new rule. 

Here are some examples we can use for the new rule. 

This should never happen. 
```
struct base
{
    virtual void update() = 0;
};

struct derived : public base
{ 
    void update() override {}
};

// goodbye v-tables
void f (derived& a, derived& b)
{
    memset(&a, 0, sizeof(derived));
    memcpy(&a, &b, sizeof(derived));
    memcmp(&a, &b, sizeof(derived));
}

// the authors of the class should ensure a proper assignment and equivalence operator 
// exists for the class
void g(derived& a, derived& b)
{
    a = {};
    b = a; 
    a == b;
}
```


These functions also commonly run into bounds issues with POD types.
```
// bounds error abound
void f()
{
    int i[3];
    int j[3];

    // ...
    // sizeof would properly address the bounds issues below, however I believe it would
    // benefit the developer to avoid using these functions altogether.

    memset(i, 1, std::size(i)); // bad
    memcpy(j, i, 3); // bad
    memcmp(i, j, 3); // bad
}

// better alternatives
void g()
{
    int i[3]{}; 
    int j[3]{};

    // ...
  
    std::fill( std::begin(i), std::end(i), 1 );
    std::copy( std::begin(i), std::end(i), std::begin(j) );
    std::equal( std::begin(i), std::end(i), std::begin(j) );
}
```

**Comment by hsutter** [comment]
Editors call: We should add an Enforcement flagging use of these functions with a non-trivially copyable type, and add a note about the bounds issue as well.
