### ISSUE TITLE
Is * in C.60 a typo?

### ISSUE THREAD

**Issue by L0uisc** [isocpp/CppCoreGuidelines#1429]
Is the * after the `this` in the comment inside the second `if` statement in the function in [this example](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-94) a typo?

**Comment by jwakely** [comment]
Looks like it was either meant to be markdown to add emphasis (which doesn't work in a preformatted code block) or it's just a typo.

**Comment by L0uisc** [comment]
So what do you think should be done to it? Kept as is, changed to `*this` or changed to `this`?

**Comment by jwakely** [comment]
Any of the above would be an improvement.
