### ISSUE TITLE
Compiler options may help with "Don't try to avoid negative values by using unsigned"

### ISSUE THREAD

**Issue by travnick** [isocpp/CppCoreGuidelines#1432]
[Don't try to avoid negative values by using unsigned](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es106-dont-try-to-avoid-negative-values-by-using-unsigned) paragraph is all about not using `unsigned` to ensure `value > 0`. And the reasons given there are that it's easy to mix things up.

All of that is very true until you enable all warnings about `signed`/`unsigned` in your compiler and other range checking features. gcc has it, clang too, even msvc has the warnings.

So in my opinion it's valid to simply use unsigned since one will ensure that mismatch will not happen (by properly setting up the compiler, to forbid such constructions).

If you agree then I propose to state clearly this condition to use `unsigned` in the code.

**Comment by dksmiffs** [comment]
ES.100's enforcement section already gives some guidance that might be applicable here.  Also, perhaps @travnick 's suggestion about compiler flags would be more helpful than ES.106's existing Enforcement section in this rule?  ES.106's current Enforcement is an unsatisfying conclusion for a trap that's so easy for new C++ devs to fall into.

**Comment by euloanty** [comment]
No. This is wrong. This should not provide an error.

for(auto i(vec.size()-1);i!=-1;--i)

or

for(auto i(vec.size()-1);i<vec.size();--i)

**Comment by MikeGitb** [comment]
If this an obscure header contest, then I prefer

    for(auto i= v.size(); i-->0;)

**Comment by euloanty** [comment]
> If this an obscure header contest, then I prefer
> 
> ```
> for(auto i= v.size(); i-->0;)
> ```

Avoid using i-- or i++.
i++ IS BAD. Prefer ++i
i-- is BAD. Prefer --i

The only thing you probably need for i++:
stack.push(stack.top()++);

Avoid a-b. Avoid a/b. Avoid sqrt(a). Only use +,*,pow

**Comment by robert-andrzejuk** [comment]
Please read related  #1115

**Comment by euloanty** [comment]
> Please read related #1115

Herb sutter is wrong.

Read this:

https://github.com/FrankHB/pl-docs/blob/master/en-US/integer-type-reasoning.md

**Comment by euloanty** [comment]
ALWAYS use std::size_t. NEVER use gsl. NEVER use int!

**Comment by euloanty** [comment]
>  ES.106's current Enforcement is an unsatisfying conclusion for a trap that's so easy for new C++ devs to fall into.

Just like a stupid argument:

vector<std::size_t> vec;
vec[5] is an unsatisfying conclusion for a trap that's so easy for new C++ devs to fall into as well.

sutter is just wrong.

Stupid like 
std::shared_ptr use long or std::uncaught_exceptions use int. No reason but stupidity.

The std::shared_ptr has a counter type of long. I don't find the reason at all. It may be attributed to boost::shared_ptr. An invented unsigned count_t, or simply std::size_t (following the prior art of the standard library containers in the std::default_allocator cases) will be consistent and easier to reason.

The std::uncaught_exceptions use int for the reasons endorsed by Herb Sutter and Bjarne Stroustrup. However, it is still not sufficient discussed in a formal sense. Actually I have asked the question in the std-discussion list but there is yet no official (WG21) response and most people do agree this is based on opinions.

**Comment by euloanty** [comment]
https://github.com/isocpp/CppCoreGuidelines/issues/1433

std::size_t is always right. NEVER use int.

**Comment by hsutter** [comment]
Editors call: We agree with the suggestion to have ES.106's Enforcements refer to ES.100, that's more helpful. Thanks!
