### ISSUE TITLE
std::size_t IS the DEFAULT integer type for C++. NEVER USE int or any other internal integer type!

### ISSUE THREAD

**Issue by euloanty** [isocpp/CppCoreGuidelines#1433]
Reason: size_t is the subscript type for ALL C++ containers and ALL C++ and C-style APIs. MORE IMPORTANTLY, std::size_t is the contract of size.

You can avoid all your issues by avoiding minus. I don't understand why people are so stupid and love uses shit like minus or divide. Prefer using== or != rather than <,>,<=,>=

BOYCOTT std::ssize()
Here are bad examples people are using against std::size_t.

1.
for(auto i(vec.size()-1);i>=0;--i)
You can easily avoid this issue by:
for(auto i(vec.size()-1);i<vec.size();--i)
or
for(auto i(vec.size()-1);i!=-1;--i)
or just use reverse_iterator
for(auto i(vec.crbegin());i!=vec.crend();++i)

2.
for(auto i(0);i<vec.size()-1;--i)
why write vec.size()-1? What's wrong with you for using a-b? minus and divide is bad for integer.
for(auto i(0);i+1<vec.size();--i)
This example is tbh just as stupid like this:
double c(0);
if(a/c==b)
why you can't write code: * is even faster than /
if(a==b*c)??

3. the guideline provides:

Mess up the usage of signed integer and the unsigned integer is objectively a GOOD thing.

Bjarne and Herb Sutter are OBJECTIVELY wrong.

https://github.com/FrankHB/pl-docs/blob/master/en-US/integer-type-reasoning.md

I've even found people are making because they use int and other signed integer type (without even use unsigned integer types).

**Comment by euloanty** [comment]
`vector<int> vec = /*...*/;

for (int i = 0; i < vec.size(); i += 2)                    // may not be big enough
    cout << vec[i] << '\n';
for (unsigned i = 0; i < vec.size(); i += 2)               // risk wraparound
    cout << vec[i] << '\n';
for (auto i = 0; i < vec.size(); i += 2)                   // may not be big enough
    cout << vec[i] << '\n';
for (vector<int>::size_type i = 0; i < vec.size(); i += 2) // verbose
    cout << vec[i] << '\n';
for (auto i = vec.size()-1; i >= 0; i -= 2)                // bug
    cout << vec[i] << '\n';
for (int i = vec.size()-1; i >= 0; i -= 2)                 // may not be big enough
    cout << vec[i] << '\n';`

Here are incorrect examples the guideline provides:
It should be
`vector<std::size_t> vec = /*...*/;

for (std::size_t i = 0; i < vec.size(); i += 2)                    // correct
    cout << vec[i] << '\n';
for (std::size_t i = 0; i < vec.size(); i += 2)               // correct
    cout << vec[i] << '\n';
for (std::size_t i = 0; i < vec.size(); i += 2)                   // correct
    cout << vec[i] << '\n';
for (std::size_t i = 0; i < vec.size(); i += 2) // correct
    cout << vec[i] << '\n';
for (auto i = vec.size()-1; i < vec.size() ; i -= 2)                // correct
    cout << vec[i] << '\n';
for (int i = vec.size()-1; i <vec.size(); i -= 2)                 // problem of int becuse int SUCKS and should never be used. However this still works for non overflow integer
    cout << vec[i] << '\n';`

This <vec.size() can even solve more problems:
for (std::size_t i = 0; i*4-5 <vec.size(); ++i)

**Comment by cugone** [comment]
You can make your code examples more readable by either indenting with four spaces or a tab; or for inline code, surrounding the code with backticks (the tilde key without pressing shift).

**Comment by euloanty** [comment]
> You can make your code examples more readable by either indenting with four spaces or a tab; or for inline code, surrounding the code with backticks (the tilde key without pressing shift).

tab/spaces are ignored for github comment.

**Comment by jwakely** [comment]
tab/spaces are ignored for github comment.

    No they aren't.

**Comment by euloanty** [comment]
> This issue just seems like an unhelpful rant.

Bjrane and Herb Sutter failed to argue with me and FrankHB. We are right. They are wrong. Trash like gsl::index_t should never be used.

**Comment by jwakely** [comment]
So you're just going to troll the issues list instead. No thanks.

**Comment by euloanty** [comment]
> So you're just going to troll the issues list instead. No thanks.

You are wrong. This guideline is just as stupid as google guideline with censorship and shit.

**Comment by phillipjohnston** [comment]
@euloanty I don't get how you think you're being censored when you are literally spamming thousands of developers around the world.
