### ISSUE TITLE
Always USE std::size_t. NEVER use ANY internal integer types. This guideline is OBJECTIVELY terrible.

### ISSUE THREAD

**Issue by euloanty** [isocpp/CppCoreGuidelines#1434]
std::size_t IS the DEFAULT integer type for C++. NEVER USE int or any other internal integer type!

No matter how you censor my issue, I am RIGHT. You guys failed to argue with TRUTH TELLERS like me.

https://github.com/FrankHB/pl-docs/blob/master/en-US/integer-type-reasoning.md

This guideline is just as stupid as google C++ guideline which disallows people for using iostreams.

https://github.com/isocpp/CppCoreGuidelines/issues/1433

**Comment by jwakely** [comment]
Nobody's censoring you, you're free to make yourself look as childish as you like.

You are not forced to agree with the guidelines, nor to use them them. But equally the authors of the guidelines are not forced to agree with you and accept your opinion.

If you don't like it, start your own guidelines and make them more popular than these ones. If you're right it should be easy.

**Comment by euloanty** [comment]
> Nobody's censoring you, you're free to make yourself look as childish as you like.
> 
> You are not forced to agree with the guidelines, nor to use them them. But equally the authors of the guidelines are not forced to agree with you and accept your opinion.
> 
> If you don't like it, start your own guidelines and make them more popular than these ones. If you're right it should be easy.

Making your own XXX is always stupid and the words to censor people.

You ARE censoring me.

**Comment by jwakely** [comment]
![giphy](https://user-images.githubusercontent.com/1254480/58344908-e66d9180-7e4e-11e9-9c10-70f2f401498d.gif)
