### ISSUE TITLE
??? in I.26 for cross-compiler ABI

### ISSUE THREAD

**Issue by Holt59** [isocpp/CppCoreGuidelines#1438]
In the I.26 section, there is an exception remark:

> You can carefully craft an interface using a few carefully selected higher-level C++ types. See ???.

The *???*  reference is missing and unfortunately I cannot make any "carefully crafted" example that would work.

Could someone point me to the right reference?

This is very related to https://github.com/isocpp/CppCoreGuidelines/issues/1304, although example for C.122 should be easier to come by.

**Comment by hsutter** [comment]
Editors call: We don't have a reference to point to, so we agree we should just remove the Exception. Thanks!
