### ISSUE TITLE
F.25 could mention `std::string_view`

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1445]
As written right now "F.25: Use a zstring or a not_null<zstring> to designate a C-style string" mentions the GSL types `zstring` and `not_null` but it does not mention the STL type `std::string_view`. Would it make sense to add a note mentioning `std::string_view` as a possible alternative?

I believe that advanced programmers know `string_view` and would not need this hint. But unexperienced programmers might strictly read F.25 as "replace `char*` for C-style string by `zstring`" where sometimes `std::string_view` is a sufficient and better alternative.

**Comment by MikeGitb** [comment]
With the caveat that std::string_view might not be zero terminated.

**Comment by beinhaerter** [comment]
> With the caveat that std::string_view might not be zero terminated.

That's true. But that also makes it more flexible. If the called function does not really need the null termination, then it can be called with C-style strings, with conversions from `std::string` and with span-like views of a (part of a) string (that is not null terminated).

**Comment by MikeGitb** [comment]
True, and string_view absolutely should be the preferred method for accepting strings you don't need ownership of and it should be mentioned/recommended in the guideline. I'm just saying that there is a caveat people need to be aware of before they start to convert const char* API to string_view ones.

zstring on the other hand (assuming the type is properly designed,  which I haven't checked) can be used as a straight up replacement.

**Comment by hsutter** [comment]
Editors call: Thanks, added.
