### ISSUE TITLE
C.128 No example given of error from redundant virtual+override

### ISSUE THREAD

**Issue by shaneasd** [isocpp/CppCoreGuidelines#1450]
The guideline states that
>However, writing more than one of these three is both redundant and a potential source of errors.

The examples and discussion do not (as far as I can tell) elaborate at all on how combining virtual and override could cause an error. I'd love to see the justification of this claim included in the examples and/or discussion.

The above is the crux of the issue. What follows is musing on my part.

As far as I can see specifying override will never cause an error (not counting failure to compile). So if we take the override as a given and look at the additional virtual keyword. It seems contradictory to state that the additional virtual is both redundant (implying it has no effect) and a potential source of errors (implying it must have some effect). The best example I could think of would be if it's redundant right now but might in future become not redundant in a way that would cause an error such as if a parent's method was changed to be not virtual and the child method's override specifier was removed but not the redundant virtual specifier. This may lead to the child method being unnecessarily virtual but presumably this would not be a bug since it was already virtual before the change.

It seems to me that C.128 is proposing two distinct guidelines. Firstly and most importantly, use override everywhere you can unless you're using final instead. Secondly (and it seems to me more weakly) don't use virtual if you've already used override/final.

Regarding the redundancy, if we prioritize the workload of the reader over the writer I think you could make a claim that actually having the keyword consistently at the start of the function reduces the burden on the reader. By this argument the reader could determine whether a function was virtual by looking at the start of all the function rather than having to check the start for virtual and the end for override/final. In an ideal world of course they'd all be at the start (or end I suppose) but given the situation we have there's at least some benefit to the redundancy.

**Comment by scraimer** [comment]
@shaneasd You make some good arguments but I think they've already been covered in previous discussions. Did you see the discussion about C.128 in #1271 ? It might explain the motivation in more detail. Actually, I'd recommend searching for "C.128" in all the issues (both open and closed) to see all the discussions about this.

**Comment by shaneasd** [comment]
Thanks @scraimer I thought I had found the relevant existing issues but apparently I didn't look hard enough. I hadn't seen #1271 and having read it, I agree  the scope of that issue is essentially identical to this issue. I'm concerned, however, that really there are two related concerns raised in both #1271 and this issue and only one of them has been addressed in #1271.

The two concerns are:
1. Does the guideline make the right recommendation?
2. Does the guideline sufficiently justify the recommendation it makes?

The decision has been made (rightly or wrongly) in #1271 that the answer to concern 1 is yes. However the discussion on that issue seems to be almost solely focused on concern 1 and ignore  concern 2.

I actually think the justification is there in #1271. There's a reasonably clear argument throughout that the current guideline is the simplest to teach and has the fewest special cases. However this isn't documented on #1271 itself. Similarly I don't think I saw a compelling argument specifically for the claim that the current guideline prevents errors when compared to alternative guidelines discussed in that issue. If one exists I think it should be provided in C.128. If it doesn't then I think the assertion that it prevents errors should be replaced with an assertion that it's the most straightforward rule to teach.

I'm not sure if it's a given that the rules in the guideline must offer justification but to provide some context, the static analysis tool used at my work doesn't correctly identify methods as virtual unless they have the virtual keyword applied (clearly it should but that's a whole separate issue). As such when deciding whether to recommend C.128 to my colleagues I have to way up the potential errors the guideline claims can arise by including virtual against the potential errors the static analysis tool will fail to detect if it is omitted. Without an explanation of the former it makes it hard to make that judgement call.

Not sure if this is the best place to discuss this given #1271 already exists but is closed?

**Comment by brenoguim** [comment]
If you make a method `virtual + final`, it will compile even if it does not override any other method, while if you only mark it only `final`, you will get the compiler error.

https://godbolt.org/z/BSpRxe
https://godbolt.org/z/xsTlDd

**Comment by shaneasd** [comment]
@brenoguim could you please clarify the point you are making? Is your point that a rule that permits ```virtual+final``` would result in an error because someone could think they were overriding a function and not be? Or is your point that the current rule precludes the (debatably?) valid use case of ```virtual+final``` to indicate a new virtual function which cannot be overridden?

If the former then that might be one of several good examples of errors that could result from not following C.128 as it stands. To restate my point though, I think it's important that the guideline provide these examples so that users can make an informed decision when adapting the guidelines for their own purposes.

If the latter then I should point out that this case was specifically raised at the end of #1271 though admittedly wasn't really discussed.

**Comment by brenoguim** [comment]
> As such when deciding whether to recommend C.128 to my colleagues I have to way up the potential errors the guideline claims can arise by including virtual against the potential errors the static analysis tool will fail to detect if it is omitted. Without an explanation of the former it makes it hard to make that judgement call.

I was just pointing very explicitly what is the "errors the guideline claims can arise by including virtual".

**Comment by hsutter** [comment]
Editors call: Thanks for the question, we have reviewed it. We think this is fine as written, "potential" already covers that there is a possibility of an error, and @brenoguim gives an example.
