### ISSUE TITLE
return value, error handling: use error handling technique for non-errors

### ISSUE THREAD

**Issue by luopeien** [isocpp/CppCoreGuidelines#1452]
This is seen from some production code. A function has many ways to return false (fail) and true (success). Both upon fail and success, need to do some callback function. The code then uses ScopeGuard to ensure this (I think this use is mix error and non-error handling):

```
bool log_on() {
    bool success = false; // set the flag to indicate if function succeeds
    scope_guard guard = [&success]() {
        if (success) {
            _log_on_callback(success);
        } else {
            cleanup();
            disconnect();
            _log_on_callback(false);
        }
    }
    if (!connect()) return false;
    if (!prepare_logon()) return false;
    if (!check_password()) return false;
    if (!send_some_data()) return false;
    success = true;
    return true;
}
```

On the positive side, this seems to reduce code duplication, on the other side, mixing non-error logic in error handling code seems weird (possible not easy for readability?)

**Comment by neithernut** [comment]
The approach also introduces an additional variable which is semantically intertwined with the scope guard. I don't think ScopeGuards should be used this way. What about the following solution?

    bool log_on() {
        scope_guard scope = []() {
            cleanup();
            disconnect();
            _log_on_callback(false);
        }
        if (!connect()) return false;
        if (!prepare_logon()) return false;
        if (!check_password()) return false;
        if (!send_some_data()) return false;
        scope.reset(); // Assuming your scope guard has some reset functionality
        _log_on_callback(true);
       return true;
    }

Now, `scope` really is used only for clean-up tasks and the state which was previously tracked through `success` is now also encapsulated within `scope`. You could also split `scope` into additional tasks, e.g. one for (general) cleanup and the callback and the other for disconnect (which would be initialized after the `connect()`). However, you'd then also need to reset multiple guards.

**Comment by luopeien** [comment]
> The approach also introduces an additional variable which is semantically intertwined with the scope guard. I don't think ScopeGuards should be used this way. What about the following solution?
> 
> ```
> bool log_on() {
>     scope_guard scope = []() {
>         cleanup();
>         disconnect();
>         _log_on_callback(false);
>     }
>     if (!connect()) return false;
>     if (!prepare_logon()) return false;
>     if (!check_password()) return false;
>     if (!send_some_data()) return false;
>     scope.reset(); // Assuming your scope guard has some reset functionality
>     _log_on_callback(true);
>    return true;
> }
> ```
> 
> Now, `scope` really is used only for clean-up tasks and the state which was previously tracked through `success` is now also encapsulated within `scope`. You could also split `scope` into additional tasks, e.g. one for (general) cleanup and the callback and the other for disconnect (which would be initialized after the `connect()`). However, you'd then also need to reset multiple guards.

It works... but if you have multiple return true, then it still need some duplication. Another way may be add a wrapper function call and check return there.

For the original code, I can imagine this error when a maintainer wants to add something like:
```
bool log_on() {
    bool success = false; // set the flag to indicate if function succeeds
    scope_guard guard = [&success]() {
        if (success) {
            _log_on_callback(success);
        } else {
            cleanup();
            disconnect();
            _log_on_callback(false);
        }
    }
    if (!connect()) return false;
    if (!prepare_logon()) return false;
    **success = do_extra_work(); // there is already a success, why not reuse it
    if (!success) {
        log_error();
        return false;
    }**
    if (!check_password()) return false;
    if (!send_some_data()) return false;
    success = true;
    return true;
}
```

**Comment by xtofl** [comment]
There is also the functorial approach.  It should be possible to invert the logic somewhat, but you get rid of the internal state variable and explicitize the success and error response:

```C++
bool log_on() {
  auto on_error = []{ cleanup; disconnect(); _log_on_callback(false); };
  auto on_success = []{ _log_on_callback(true); };
  with(on_error, on_success, [] {
    if (!connect()) return false;
    if (!prepare_logon()) return false;
    ...
  });
}
```

Where the `with` function would do the plumbing:

```C++
auto with(auto on_error, auto on_success, auto success_returner) {
  if (success_returner()) on_success();
  else on_error();
}
```

**Comment by hsutter** [comment]
Editors call: The advice we recommend is to use RAII (e.g., E.6) wherever possible, and then this kind of issue usually does not arise. Scope guards and similar techniques are for when there is no RAII type and you want to create one ad-hoc for local cleanup; generally you will do better by creating a reusable RAII type. Beyond that, error handling is a very complex and contentious issue where there are several lively discussions going on, including proposing standardizing scope guards. If you have a concrete suggestion please make it, otherwise we are not going to make new guidelines in this area until the currently active conversations converge more.
