### ISSUE TITLE
stop using header files

### ISSUE THREAD

**Issue by catastrop** [isocpp/CppCoreGuidelines#1454]
Use module or package system

**Comment by jwakely** [comment]
What exactly are you suggesting?

Using C++ modules isn't an option until you have a compiler that supports them, and they're not universally available yet.

How does a package system help to avoid headers?

**Comment by catastrop** [comment]
@jwakely ,  handle including library like golang, rust, ecmascript etc. we will write files containing source code of a library and decide what can be exported or not. then include the file directly. the compiler will first compile the library then provide it to its caller. so the compiler knows, is every things exist. currently the compiler don't know, is the function definition exist or not. they got caught by the linker.

**Comment by jwakely** [comment]
That requires changes to the C++ language, so this is the wrong place to propose that. This repository is for a set of guidelines for using existing C++ well, not for evolving the language itself.

There is already a mature design for modules in C++ anyway, see [N4720](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4720.pdf). A modified version of the feature is expected to be part of the C++20 revision of the standard.
