### ISSUE TITLE
Suggestion: provide github page

### ISSUE THREAD

**Issue by tkruse** [isocpp/CppCoreGuidelines#146]
Github allows to create so called github pages. Using that, it would be possible to provide the contents of CppCoreGuidelines.md with custom fonts and style. It would require adding some files on a branch called gh-pages. Github instructions are at: https://pages.github.com/

For fun, I did this with this commit:
https://github.com/tkruse/CppCoreGuidelines/commit/48cfc54bba
 
Result:
http://tkruse.github.io/CppCoreGuidelines/CppCoreGuidelines.html

The example maybe shows that at least the sidebar can be useful. Fonts and colors are a matter of personal tastes, of course (ad possibly of browser rendering speed). Note adding this does not affect viewing the file as it is now on github.

As you can see in the commit, the file CppCoreGuidelines.md does not require changes other than adding:
```
---
layout: default
---
```
at the top. 

After that, each update would still have to be merged with the gh-pages branch, but that should not cause conflicts (as CppCoreGuidelines.md is basically unchanged). The additional files would only live on the gh-pages branch, the master branch would remain 'clean'.

Since this is just a cosmetic suggestion, you may close this issue without further dicussion if you don't like it.

**Comment by tkruse** [comment]
Btw, this also allows plenty of HTML5 hackery, as an example here I added highlight.js so that users can toggle on syntax highlighting:
http://tkruse.github.io/CppCoreGuidelines/CppCoreGuidelines.html

**Comment by tkruse** [comment]
Also note that while no additional programs are required locally for this, installing and using jekyll locally helps tremendously with previewing the Markdown rendering, which greatly helps detecting markdown issues.

**Comment by blakehawkins** [comment]
:+1:

**Comment by hsutter** [comment]
We are interested in this suggestion. We plan to look at this and other formatting suggestions in November after we all finish preparing/attending/recovering from the Kona standards meeting. Thanks!

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

**Comment by tkruse** [comment]
A summary of presented arguments may be nice.

**Comment by AndrewPardoe** [comment]
: ) 

@tkruse, normally we just say it was discussed so that we 1) remember it was discussed before, so we can pull up meeting notes and 2) show some activity on the Issue. Usually we don't want to put our half-baked opinions out publicly until the opinions are fully baked. 

That said, Herb's comment from September 29th pretty much sums it up. We like your suggestion and will go forward with it. Thank you!

**Comment by AndrewPardoe** [comment]
@tkruse, I've copied over your code and created a GitHub page. Thanks!

There's some prettying up I should do, and I'll re-enable the download links one day. 

I have a question about the style: how do I increase the space between paragraphs? The MarkDownify of the Readme, for example, could use some vertical spacing. I looked through the .css files but I must admit I know very little about web programming.

**Comment by tkruse** [comment]
Cool.  It's already online at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html.
I expect you'll get quite a few pull requests soon for style, I can look at the specific spacing challenge tomorrow.

2 more things you could do that I did not say before:
* abandon the master branch in favor of the gh-pages branch
* mention the gh-pages site in the readme file, so people landing at github have a quick link to the site.

**Comment by AndrewPardoe** [comment]
Thanks, I'll mention the gh-pages site in the readme file. Great idea.

We'll at least keep working from the master branch, so I'll let that stay.

I appreciate any PRs. Web programming is not a strength of mine!

**Comment by tkruse** [comment]
Using only the gh-pages branch is the most convenient solution (no need to remember anything). The second choice should IMO be to regularly merge the master branch into gh-pages. That's a bit painful because of the merge conflicts around the file header, but still okay, it's transparent in the version control history of what happens.

Creating independent commits on the master branch and the gh-pages branch as you have already done seems like the least desirable solution to me, as you'd need to diff directories to check whether any change in master is reflected in gh-pages.

Just my 5 cents.

**Comment by AndrewPardoe** [comment]
We discussed offline and prefer to keep both branches. Thank you for the formatting fixes!

Normally the only file being edited in the main repo is the guidelines file. It's easy enough to copy that over and make the one change--the file header.

**Comment by tkruse** [comment]
It seems the gh-pages branch is not being updated regularly, nor did you create a link to the gh-pages in the README.md file. That way people can only find the gh-pages by coincidence.

**Comment by LegalizeAdulthood** [comment]
It is also customary to put a link to the gh-pages in the description of the repository so the link is easily discoverable at the the top of the page for the repository.

**Comment by tkruse** [comment]
@AndrewPardoe, the gh-pages branch is lagging behind, causing the browser-optimized version to miss latest updates.

**Comment by blakehawkins** [comment]
@tkruse @AndrewPardoe I think this might be some good news -

https://github.com/blog/2228-simpler-github-pages-publishing

(I haven't actually read it yet)

**Comment by tkruse** [comment]
The master branch could thus be used for publishing, but that would mean
the layout files would become part of the master branch. Not sure if that
would be acceptable.
