### ISSUE TITLE
whats the approach towards returning a byte buffer to the caller ?

### ISSUE THREAD

**Issue by DevNaga** [isocpp/CppCoreGuidelines#1464]
In, **P.6: What cannot be checked at compile time should be checkable at run time
Reason**

The bad example shows,

```cpp
// separately compiled, possibly dynamically loaded
extern void f(int* p);

void g(int n)
{
    // bad: the number of elements is not passed to f()
    f(new int[n]);
}
```

Lets take an example of a byte buffer, aka 

```cpp
uint8_t buffer[128];
```
that is most commonly used in network programming / serialization and deserialization primitives.

```cpp
// encout is the outout, caller allocates and owns this
// encout_size is  the passed output buffer size
// return either length of encoded buffer (serialized data will be placed in encout) of failure error
// to_be_enc is input
int encode (const my_struct &to_be_enc, uint8_t *encout, size_t encout_size)
{
    int encode_len = 0;

    // do encode operation taking to_be_enc data and serializing into encout

    return encode_len;
}
```

I am sure that the above code example, looks more of C and violates the rule of passing a pointer to the function, this is exactly my problem when trying to use C++ in performing data serialization / deserialization.

Per the guidelines, passing an `std::vector<uint8_t> bytebuf` may seem expensive for `push_back` or using the `operator[ ]` operations. I am not so sure if using `std::array<uint8_t, 128> bytebuf` would be of better performance comparatively with the `std::vector`.

So, whats the preferred approach when returning a byte buffer and the final size of the filled data when passed as argument ?

Thank you in advance.

**Comment by MikeGitb** [comment]
Replace encout and encout_size with gsl/std::span.Other than that I'd keep the interface as is (at most you could return a gsl::span instead of an int, but then there is the ambiguity if it points to the serialized data or the remaining buffer). 
Such functions are usually called in a loop and creating a new buffer everytime is just wasteful.

**Comment by arvidn** [comment]
I'd suggest using `std::byte` instead of `std::uint8_t` and maybe even returning a `span<std::byte>` would be convenient, just as it may let you chain calls.

**Comment by DevNaga** [comment]
Thank you for the replies. I still think this adds a function call overhead for serialize / deserialize routines.

Use of `std::vector<std::byte>` may seem useful, with calling `.reserve` method and then using the `operator[ ]` (but however this look still a function call, which might have been optimised by the compiler).

**Comment by jwakely** [comment]
The purpose of these guidelines is not to avoid the overhead of individual functions. That is usually optimizing for the wrong thing.
