### ISSUE TITLE
R.21: unique_ptr <-> Unique_ptr, shared_ptr <-> Shared_ptr

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1466]
In the text of R.21 all `unique_ptr` are written with small letters but all `Shared_ptr` are written capitalized. This looks inconsistent to me. I would expect all small letters (like the class names) or all capitalized (like the concepts), but not the given mix.

Is there a reasoning about it? Or a) shall `unique_ptr` be changed to `Unique_ptr` or b) shall `Shared_ptr` be changed to `shared_ptr`?

The same question applies to other rules like for example C.22 where `shared_ptr` is used. Maybe someone can clarify and provide a rule when to use which writing!?

**Comment by jwakely** [comment]
It should be written the same way as the class template, always.

**Comment by beinhaerter** [comment]
> It should be written the same way as the class template, always.

OK, I'll prepare a PR.

Just for your information, in R.31 I found "These smart pointers match the `Shared_ptr` concept". I would keep the capitalized writing at such a place (as concept is mentioned there) and not always replace.

**Comment by hsutter** [comment]
But wait: This is intended to refer to the [smart pointer concepts](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslconcept-concepts).

I'll clean it up a little now to remove a dangling reference to an early version of the Lifetime profile, but this is as currently intended.

Separately, we can revisit the spellings of all of those -- this is a great time, because at Cologne meeting later this month we'll confirm the final naming convention of concepts in the standard and so once that's settled it would be a good time to talk about the names of concepts in GSL.

**Comment by hsutter** [comment]
@beinhaerter Please revert?

**Comment by jwakely** [comment]
> But wait: This is intended to refer to the smart pointer concepts.

Oh, sorry for not checking the context. It's obviously OK to use different names for different things!

**Comment by hsutter** [comment]
"Yes, but"! -- clearly the similarity in names is causing confusion. If these concept names can confuse the editors, we should consider whether they're the best names. So this is good feedback, thank you.

**Comment by beinhaerter** [comment]
I deleted my PR.

@hsutter Thanks for taking a look at it. Even if you keep the names "Unique_ptr" and "Shared_ptr" I think it would be a good idea to revisit the Guidelines and check for each unique_ptr, Unique_ptr, shared_ptr and Shared_ptr if the class or the concept was meant to be referenced. Take for example R.21:

Title and Reason use class, Example of course too.
> R.21: Prefer unique_ptr over shared_ptr unless you need to share ownership
>Reason A unique_ptr is conceptually […]

Enforcement uses concept for Shared_ptr but class for unique_ptr.

>(Simple) Warn if a function uses a Shared_ptr with […] the Shared_ptr or […] a Shared_ptr&. Suggest using unique_ptr instead.

**Comment by hsutter** [comment]
@beinhaerter Thanks, that's a good example. I think that is intended -- if we see the general `Shared_ptr` pattern, recommend the specific `unique_ptr` replacement. That said, I agree `S` and `s` are not super distinguishable in many fonts, including on this comment thread...

**Comment by hsutter** [comment]
Editors call: We decided to rename the concepts from `Unique_ptr` to `Unique_pointer` and from `Shared_ptr` to `Shared_pointer` to make the distinction clearer.
