### ISSUE TITLE
Are in-class member initializers bad for interface headers?

### ISSUE THREAD

**Issue by KUGA2** [isocpp/CppCoreGuidelines#1472]
I am pretty new to C++11 (and newer). I just found the possibility to do in-class member initializers. There is this rule [C.45](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead) for this feature:

> C.45: Don’t define a default constructor that only initializes data members; use in-class member initializers instead

Isn`t this bad practice for interface headers? A library with a header like this would need the user to recompile to get the changed default. If I set it in the constructor (in the *.cpp) the using executable does not need recompilation.

**Comment by jwakely** [comment]
The guideline is assuming that a constructor that does nothing but set some data members would be defined inline.

You're assuming that a constructor that does nothing but set some data members would not be defined inline.

**Comment by FraserRoss** [comment]
Compilation dependencies can be introduced by using member initialisers.  For instance a header file with global constants might have to be included by a units header.

**Comment by arvidn** [comment]
You can still define the constructor as =default in a cpp file in the library, to get the best of both worlds.

**Comment by hsutter** [comment]
Editors call: Whether to define a function out of line is a dependency management judgment call that should be decided on a case by case basis.
