### ISSUE TITLE
question about local lambdas (ES.28 and further)

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1477]
As described in ES.28 I am using local lambdas for complex initialization or when I want a local function.

Here is a simple example (made up, not production code). In this version the lambda captures necessary parameters.

	int foo(myclass& t)
	{
		auto const mapper = [v = t.get_some_value()](){
			switch (v) {
			case enum_value_one:	return 42;
			case enum_value_two:	return 815;
			default:		return 0;
			}
		};
		return mapper() * 2;
	}

In this second version the lambda does not capture and the user has to pass the values as function parameters.

	int foo(myclass& t)
	{
		auto const mapper = [](auto v){
			switch (v) {
			case enum_value_one:	return 42;
			case enum_value_two:	return 815;
			default:		return 0;
			}
		};
		return mapper(t.get_some_value()) * 2;
	}

Are there any recommendations which version to prefer? The first approach results in shorter code, but the second approach is more like a regular function. Are there any other advantages of either version?

It is clear that you need to capture what you cannot pass as function parameters (for example when passing a lambda to `find_if`). But what if you have a choice? Would a (maybe new) guideline be "Only capture what you can't pass as function parameter"? Or is this not worth a guideline because it is just "Choose whatever you prefer"?

**Comment by jwakely** [comment]
What is the value of a guideline that says "do whatever you like" ?

This doesn't seem like something the guidelines need to deal with. Every new guideline covering something trivial and unimportant makes them longer to read and makes the important parts less easy to find.

**Comment by beinhaerter** [comment]
I clarified my question, the wording was misleading. Of course I did not mean to add a guideline "Do whatever you like". My main question is if there is a guideline/rule (maybe not in the CppCoreGuidelines) how to do it best.

**Comment by jwakely** [comment]
No (how hard is it to search for every use of "capture" in the guidelines?), and I don't think there should be.

**Comment by beinhaerter** [comment]
> how hard is it to search for every use of "capture" in the guidelines?

That is just offensive. Of course I did search the guidelines and I did not find any related guideline. But what does that tell me? Are the guidelines as of today complete and anything not mentioned there is not worth a guideline?

**Comment by oleksandrkozlov** [comment]
I guess important thing from the [ES.28 examples](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-good-14) is that lambda is invoked immediately (like [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression) in JS). And in case if we capture values we can skip `()` in the lambda declaration, only `[]` is required.

``` cpp
int foo(bool arg)
{
    return [arg] {
        if (arg)
            return 1;
        else
            return 2;
    }();
}
```

If we pass values as parameters the code looks a little bit complicated.

``` cpp
int foo(bool arg)
{
    return [](bool arg) {
        if (arg)
            return 1;
        else
            return 2;
    }(arg);
}
```
From a generated closure class point of view, I don't see a big difference.

``` cpp
int foo(bool arg)
{
    class Closure
    {
    public:
        Closure(bool arg)
            : arg_{arg}
        {
        }

        int operator()() const
        {
            if (arg_)
                return 1;
            else
                return 2;
        }

    private:
        bool arg_;
    };

    return Closure{arg}();
}
```

vs.

``` cpp
int foo(bool arg)
{
    class Closure
    {
    public:
        int operator()(bool arg) const
        {
            if (arg)
                return 1;
            else
                return 2;
        }
    };

    return Closure{}(arg);
}
```

Therefore for an immediately invoked lambda expression, I would prefer to **capture values** because the code looks simpler.

**Comment by beinhaerter** [comment]
@oleksandrkozlov OK, thanks. That was roughly also my understanding. I just wanted to be sure that I haven't missed some technical difference.
