### ISSUE TITLE
F.50 function can be declared at local scope

### ISSUE THREAD

**Issue by filixi** [isocpp/CppCoreGuidelines#1479]
F.50 states:

> Functions can't capture local variables or be declared at local scope;

But in fact, function can be declared at local scope as long as such declaration is not definition. [Code example](https://godbolt.org/z/A2gZD5)

**Comment by cubbimew** [comment]
s/declared/defined would be sufficient, right?

**Comment by filixi** [comment]
Yes, replacing "defined" with "declared" will be sufficient.
