### ISSUE TITLE
P.1: Express ideas directly in code Example, good A much clearer expression of intent would be:

### ISSUE THREAD

**Issue by Blonder** [isocpp/CppCoreGuidelines#1483]
`void f(vector<string>& v)
{
    string val;
    cin >> val;
    // ...
    auto p = find(begin(v), end(v), val);  // better
    // ...
}
`
should use const vector<string>& v as parameter and cbegin(), cend()

**Comment by sankurm** [comment]
Perhaps, the function f is not fully specified in this example. Notice the use of ellipsis (which are commented too!). That part of the unspecified code could be mutating the found entry. The original author(s) may have put this unspecified part to help the reader see the point being made and not distract. In that sense, making these changes will not be helpful.

**Comment by hsutter** [comment]
Editors' call: We think the example is probably fine as is, but we agree that adding `const` can avoid distraction, so we'll add `const`. Thanks!
