### ISSUE TITLE
IMOH it would be better to use File Transclusion instead a single big md file

### ISSUE THREAD

**Issue by ClausKlein** [isocpp/CppCoreGuidelines#1490]
[File Transclusion](https://fletcher.github.io/MultiMarkdown-5/transclusion.html)

File transclusion is the ability to tell MultiMarkdown to insert the contents of another file inside the current file being processed. For example:
```
This is some text.

{{some_other_file.txt}}

Another paragraph
```

**Comment by ClausKlein** [comment]
Unfortunately it does NOT work on GitHub!

[see sample](https://github.com/ClausKlein/samples/blob/master/Discussion.md#discussion-use-a-factory-function-if-you-need-virtual-behavior-during-initialization)

**Comment by ClausKlein** [comment]
It is possible to prepossess with multimarkdown:

```bash
multimarkdown -t mmd -o Discussion.mmd Discussion.md
multimarkdown -t html -o Discussion.html Discussion.md
```

**Comment by hsutter** [comment]
Editors' call: We do get requests to split the Guidelines into multiple files, but we still prefer to keep it as one file for now even though it's very large.
