### ISSUE TITLE
F.45: Don't return a T&&

### ISSUE THREAD

**Issue by Exaeta** [isocpp/CppCoreGuidelines#1493]
I would like to suggest an exception for the F.45: Don't return a T&& rule.

I have seen some examples where returning a T&& makes sense.

Consider:
```cpp
foo foo::operator + (foo const &) const &
foo&& foo::operator + (foo &&) const &
foo&& foo::operator + (foo &&) &&
foo&& foo::operator + (foo const &) &&
```

While "foo" can be a valid return type, the fact remains that moving, while cheap, is not free in the case of objects with multiple data fields.
Suppose that "foo" has a "data" pointer, size, and a capacity. Initializing these to null and 0s then swapping does contain more overhead than updating whatever parameter is passed in and returning it by reference.

E.g. in an expression like `b + (foo(4) + a) + foo(6)` the `operator +` can return a reference to the temporary `foo(4)` which persists for the life of the expression and is mutated by the other calls to `operator +`, thus the expression only generates two temporaries (`foo(4)` and `foo(6)`) without generating intermediate temporaries for each execution of `operator +`.

**Comment by MikeGitb** [comment]
Is this a common enough case to be mentioned in the guidelines? I mean: There is an exception to every rule, but not everything can (and should) be listed - that's what suppression are for.

**Comment by Exaeta** [comment]
It's not common, but it should be, since it improves performance, sometimes non-trivially.

**Comment by MikeGitb** [comment]
Do you have a concrete example in mind (e.g. something you encountered in your coffee,  where it made a measurable and significant difference)? 

My question was not,  if the pattern is common,  but if the situations in which it is actually beneficial are so common?

I don't know what the authors of the guidelines think,  but personally I'd prefer if the guidelines themselves are kept as simple as possible and - when in doubt - favor safety/correctness over performance (if there is a tradeoff at all). 

The people who have special requirements can then use supressions to express those requirements.

All that being said. How would you actually formulate the exception? How about "you can return a `foo&&` if it refers to a `foo&&` argument"?

**Comment by Exaeta** [comment]
I think 

**Exception**

Functions that accept T&& as a parameter and member functions that are overloaded as rvalue functions may return T&& to reduce the number of temporaries created in expressions.

Would work.

**Comment by Exaeta** [comment]
I'm not allowed to share source code from the actual example where this made a minor but nonetheless significant improvement, but I will try to create an example benchmark that illustrates the point later today.

**Comment by Exaeta** [comment]
I'm not allowed to share source code from the actual example where this made a minor but nonetheless significant improvement, but I will try to create an example benchmark that illustrates the point later today.

**Comment by jwakely** [comment]
> E.g. in an expression like `b + (foo(4) + a) + foo(6)` the `operator +` can return a reference to the temporary `foo(4)` which persists for the life of the expression

How do you prevent people shooting themselves in the face with this?

    auto&& sum = b + (foo(4) + a) + foo(6);

You have a dangling reference. That's exactly the situation the guideline aims to prevent. Why does the rationale for the guideline not apply to your case?

> It's asking to return a reference to a destroyed temporary object. A `&&` is a magnet for temporary objects.

Why is your example not **exactly** the situation described?

> Example
> A returned rvalue reference goes out of scope at the end of the full expression to which it is returned:
>
>   `    auto&& x = max(0, 1);   // OK, so far`
>   `    foo(x);                 // Undefined behavior`
>
>This kind of use is a frequent source of bugs, often incorrectly reported as a compiler bug. **An implementer of a function should avoid setting such traps for users.**

[emphasis mine]

**Comment by Exaeta** [comment]
@jwakely Definitely an issue, though I lean on the side of "don't use `auto&&`", which has worked fine for me so far.

**Comment by jwakely** [comment]
The problem is nothing to do with `auto`, this has exactly the same problem:

    foo&& sum = b + (foo(4) + a) + foo(6);

And so does this:

    const foo& sum = b + (foo(4) + a) + foo(6);

Your approach might work in a small-ish codebase with careful review or style guides that forbid these problem cases, but it's not suitable for general purpose code and so not appropriate for the guidelines to promote it.

**Comment by hsutter** [comment]
Editors call: We think @jwakely has answered the question, please feel free to reopen if we missed a part not yet answered.
