### ISSUE TITLE
Suggestion: F*: Express behavioral differences as arguments or overloads to member functions rather than member variables

### ISSUE THREAD

**Issue by Exaeta** [isocpp/CppCoreGuidelines#1494]
**Reason:**

Expressing algorithmic differences as arguments or overloads to a function minimizes state dependencies which can introduce differing behavior of member functions related to prior calls and order of execution which are difficult to debug and complex to analyze. Additionally, object state dependencies in call sequences that would otherwise be const expand the scope of functionality which needs to mutate the object to execute, thus degrading multi-threaded performance.

**Example, bad:**

```cpp
class foo
{
public:
  void write(std::byte const * data, std::size_t count);
  void read(std::byte * data, std::size_t count);
  void set_readwrite_timeout(std::chrono::monotonic_clock::duration timeout);
};
```

**Example, good:**

```cpp
class foo
{
public:
  void write(std::byte const * data, std::size_t count, std::chrono::monotonic_clock::duration timeout);
  void read(std::byte * data, std::size_t count, std::chrono::monotonic_clock::duration timeout);
};
```

**Comment by hsutter** [comment]
Editors' call: It seems the examples were intended to show a timeout data member? Also, this is moving state from the class to the user code in addition to storing it as a member. We don't think this specific and clear enough about where it applies to be made a guideline at this point.
