### ISSUE TITLE
Single file vs Multiple Files vs GitHub Pages

### ISSUE THREAD

**Issue by michaelbprice** [isocpp/CppCoreGuidelines#15]
Having the contents of the guidelines in a single Markdown file seems an odd decision.  Why not split each section into a separate Markdown file?  By doing so, you'd make the merging of pull requests much easier.

Also, has the Foundation considered trying to use [GitHub Pages](https://pages.github.com/) for presenting the material?

**Comment by kirbyfan64** [comment]
Completely unrelated side note: it'd be cool if you guys used a service like ReadTheDocs to render and host the markdown. It looks really cool!

**Comment by nasosi** [comment]
Reading, referring back and searching through the document is so much easier using a single page for all of it. I hope it is kept this way.

**Comment by rkawulak** [comment]
OTOH, editing a single document is far from convenient. It's not easy to locate the place where you want to make edits, and (at least on my system) GitHub is unable to show changes preview for such a huge file.

**Comment by AndrewPardoe** [comment]
For the time being we are preferring the status quo. Thank you for the suggestion!

**Comment by MaxDZ8** [comment]
Please reconsider. In-browser diff is just too convenient, especially as this keeps being a work in progress.
