### ISSUE TITLE
Code should be written to be read

### ISSUE THREAD

**Issue by sdoiel61** [isocpp/CppCoreGuidelines#1500]
The example code in this text is filled with code that I typically see with junior programmers.

1) Don't use variable names that tell you nothing about the content.  Single letter variable names tell you nothing.  If you're defining an index into a lookup table, use "iLookup" or "lookupIndex", choose and stick with a convention, don't use "i" it doesn't tell you anything and leads to errors.

2) Don't "using namespace std".  Reading "std::vector" tells you more than "vector".  The standard library is big and seeing the prefix instantly draws attention to the source of the definition without adding significantly to the amount of text.  I have never seen a bug introduced by qualifying code with the std namespace, the converse is not true.

3) Only use "auto" if it does not obscure the code.  In C/C++ it's hard enough dealing with bugs due to typing and range issues when you can identify the type.

There is an example "Use literal suffixes where clarification is needed" that gives good examples where the use of "auto" obscured the code:

    auto hello = "Hello!"s; // a std::string
    auto world = "world";   // a C-style string
    auto interval = 100ms;  // using <chrono>

This code required comments because the code itself was obscured because of the use of auto.

In the example "Use digit separators to avoid log strings of digits":

    auto c = 299'792'458; // m/s2
    auto q2 = 0b0000'1111'0000'0000;
    auto ss_number = 123'456'7890;

If I were doing a code review using a web based tool where I don't have an IDE where I can hover over the identifier to determine the type, I would have to do a fair amount of digging to sort out the data types.  These days I work with more than one programming language and the rules differ.  It's a lot easier to understand the code if simple types are explicit.

Please save this kind of code for an obfuscated code contest.

I work on a code base of hundreds of thousands of lines of C/C++ code.  I spend a lot more time reading code than writing code.  The code is written by dozens of programmers with different levels of programming skill.  Some code is easy to follow, some code is difficult to follow.  Some of code has been made more difficult to follow by the use of "auto".

There are certainly cases where the use of "auto" does not obscure the code.  These are usually where using the actual type is verbose and does not add information:

    for( auto iter = my_list.begin() ; iter != my_list.end() ; ++iter )

When I write code, I consider many constructs to have a cost and a benefit.  The cost is sometimes clarity to the reader, the benefit is often reuse, abstraction and flexibility.  When "auto" is used in place of "float" or "double", it is usually incurring a cost with no benefit.

**Comment by cubbimew** [comment]
The examples in these guidelines are expected to follow the guidelines, so an issue raised against an example would be "it violates guideline XY.nn". It appears that what you are disagreeing with are some of the guidelines, namely

> Single letter variable names tell you nothing

disagrees with [NL.7: Make the length of a name roughly proportional to the length of its scope](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-name-length)

> Don't "using namespace std". Reading "std::vector" tells you more than "vector".

disagrees with [SF.6: Use using namespace directives for transition, for foundation libraries (such as std), or within a local scope (only)](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-using)

> Only use "auto" if it does not obscure the code.

disagrees with [ES.11: Use auto to avoid redundant repetition of type names](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-auto) 

To make the issue actionable, could you propose more specific changes to these guidelines?

**Comment by sdoiel61** [comment]
In section I.7 State postconditions, the example is suggested:

int area(int height, int width)
{
    auto res = height * width;
    Ensures(res > 0);
    return res;
}

In this example the use of "auto" obscures the fact that the intended range check is invalid.  Consider a system with 32 bit integers where the value of height is 2147483647 and the value of width is 2.

A novice programmer might have assumed that since multiplying two 32 bit integers can potentially require a 64 bit result, that "auto" might represent a 64 bit value.  An incorrect assumption that would make this error difficult to find.  Replacing "auto" with "int" might make it easier for a programmer to recognize the error.

The examples in the core guidelines are as a matter of necessity small samples of code that do not reflect how they would appear in normal use.  This means that in the example in ES.1:

    auto sum = accumulate(begin(a), end(a), 0.0);

Due to the abbreviated context of the example, it is unknown whether this is within a local scope, so the use of begin and accumulate should be qualified with std.

I'll have more feedback later.

**Comment by Freekjan** [comment]
As a point against SF.6, if you type `using namespace std;` with the wrong set of #includes you get a name collision between `::abs`, which is allowed to have c-linkage, and `std::abs`, which must always have c++-linkage.

In this context, wrong depends on the choices your library author made for transitive #includes.

**Comment by jwakely** [comment]
@Freekjan what do you mean by name collision? It's an overload set.

**Comment by Freekjan** [comment]
std::abs is indeed an overload set, but the version of abs in the global namespace is inherited from the C standard library and it is expressedly allowed to have c-linkage by the standard. Since C does not support overloads, functions with c-linkage cannot be part of overload sets.

**Comment by jwakely** [comment]
> functions with c-linkage cannot be part of overload sets.

That's not true at all.

**Comment by Freekjan** [comment]
ok, sorry, maybe I misread sections [9.10.5](http://eel.is/c++draft/dcl.link#5) and 9.10.6 of the standard. Can you maybe enlighten me as to how they should be read?

**Comment by jwakely** [comment]
I assume you mean [dcl.link] p5 and p6, because there is no 9.10 in the current (C++17) standard.

You should read it exactly as it's written.

>  If two declarations declare functions **with the same name and parameter-type-list** to be members of the same namespace or declare objects with the same name to be members of the same namespace and the declarations give the names different language linkages, the program is ill-formed; no diagnostic is required [...]

So this is perfectly valid because each overload has a different parameter-type-list:

    extern "C" int abs(int);
    extern "C++" {
      long abs(long);
      long long abs(long long);
      float abs(float);
      double abs(double);
      long double abs(long double);
      namespace std { using ::abs; }
    }

What [dcl.link] p5 is saying is that you can't re-declare the _same overload_ with two different language linkages, so this is invalid:

    extern "C" int abs(int);
    extern "C++" int abs(int);

But if your standard library implementation does that, it's completely broken. Nobody does that. I don't see any problem with SF.6 related to this.

**Comment by Freekjan** [comment]
I stand corrected. That being said, I got confused because I have been bitten in the past by a library implementation that (naively) did 

    extern "C" int abs(int);
    namespace std {
      int abs(int);
      long abs(long);
      long long abs(long long);
      float abs(float);
      double abs(double);
      long double abs(long double);
    }

which is valid only until someone types `using namespace std;` anywhere.

**Comment by shaneasd** [comment]
A note regarding the auto example you mentioned from "Use literal suffixes where clarification is needed"
```
auto hello = "Hello!"s; // a std::string
auto world = "world";   // a C-style string
auto interval = 100ms;  // using <chrono>
```
Presumably you're referring primarily to the first two where it appears that comments have been used to inform the reader of the type because auto does not do that.

I think this is more for the benefit of the reader of the guideline though, not for real world code. I think the intent is that the real world code would look like
```
auto hello = "Hello!"s;
auto world = "world";
```
The comment is just there to illustrate the effect the suffix has in the same way that a programming book might contain something like ```x = x + 1 //calculate the number one more than x and put it in x```.

Note that if the example read
```
std::string hello = "Hello!"s;
char* world = "world";
```
then the suffix would be redundant making it a pretty bad example

**Comment by hsutter** [comment]
Editors' call: We agree naming is important, and is often controversial. However, we think it would be good to add a note about how we use names in our examples in the Guidelines.

For examples showing the meaning of language-technical issues, single-letter names are fine because the purpose is to illustrate a rule, not to write production maintainable code itself. The comments about the literal suffixes are for emphasis to the Guideline reader.

**Comment by BjarneStroustrup** [comment]
Added explanatory note
