### ISSUE TITLE
when to use noexcept (on trivial functions that don't throw)?

### ISSUE THREAD

**Issue by ChrisGuzak** [isocpp/CppCoreGuidelines#1506]
We have a case where the MSVC compiler will insert NOPs to satisfy the needs of is exception implementation increasing binary size for code that uses the `throw()` exception specification. These are trivial functions on a base class that don't throw (initializing members to null, incrementing and decrementing reference a counters, etc.). Removing these is supported by ([E.30: Don't use exception specifications](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e30-dont-use-exception-specifications) ) but in C++17 `throw()` and `noexcept` are the same and will produce the same binary growth.

I see [Discussion: Usage of noexcept](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#discussion-usage-of-noexcept) - is empty.

[F.6: If your function may not throw, declare it noexcept](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-noexcept) - contradicts this change (this is a case of "impossible").

For those that have access here is [the change to remove `throw()`](https://microsoft.visualstudio.com/_git/os/pullrequest/3690378?_a=files).

Are updates to the guidelines needed or is this a problem specific to this compiler?

**Comment by beinhaerter** [comment]
Why does F.6 contradict E.30?
E.30 says "don't use the old throw(x,y) exception specification". In the Note it explicitely says
> If no exception may be thrown, use noexcept or its equivalent throw().

That is what the title of F.6 also says. And the Note in F.6 says
>Do not use traditional exception-specifications.

Which totally aligns with E.30.

I am sorry, but I do not see the contradiction. Can you please elaborate?

**Comment by hsutter** [comment]
I'm not sure I understand, let me try to restate:

- E.30 discourages using `throw(x,y,z)` including the empty `throw()`.
- F.6 encourages using `noexcept`.

I think those are consistent, and that following E.30 to remove `throw()` is fine even if you cannot (yet) add the `noexcept` for other reasons... does that make sense?

**Comment by ChrisGuzak** [comment]
I was not very clear. the result is adding `noexcept` here (that is the same as `throw()`) increases code size. so code size efficiency is in conflict with using `noexcept`

**Comment by ChrisGuzak** [comment]
I think we've gone far enough on this. we should use noexcept where we can but the fact that COM does not use noexcept gets in our way to do so. we will try to get this addressed by updating COM.
