### ISSUE TITLE
F.42 Broken link "if the object referred to should not change."

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#1513]
In F.42, the following text contains two links. the last one is broken. 

"A reference is often a superior alternative to a pointer if there is no need to use nullptr or if the object referred to should not change."

**Comment by profnandaa** [comment]
This is intentionally left as "missing info". Check the introduction section under **Problems**

>Triple question marks (???) mark known missing information

**Comment by viboes** [comment]
Could you clarify why this is done intentionaly? What i sthe added value to have an link that points no where?

**Comment by pegleGrot** [comment]
I believe the link description/text is a topic planned for the future.

**Comment by jwakely** [comment]
Yes, it's a placeholder for missing info, like a "TODO" note.

**Comment by hsutter** [comment]
Editors call: Yes, it's a placeholder.
