### ISSUE TITLE
Corner case in wording for F.16

### ISSUE THREAD

**Issue by kevgs** [isocpp/CppCoreGuidelines#1514]
Current wording is:

> (Simple) ((Foundation)) Warn when a parameter being passed by value has a size greater than 2 * sizeof(void*). Suggest using a reference to const instead.

> (Simple) ((Foundation)) Warn when a parameter passed by reference to const has a size less than 2 * sizeof(void*). Suggest passing by value instead.

But what to do with parameters which size is exactly `2 * sizeof(void*)`? I suppose those should be passed by value and wording should be fixed.

**Comment by hsutter** [comment]
Editors call: We think it's okay as written -- we warn on `>` one way, on `<` the other way, and for `==` we don't warn because the programmer might choose either way.
