### ISSUE TITLE
I.9 talks about 2018 as the future

### ISSUE THREAD

**Issue by Cre3per** [isocpp/CppCoreGuidelines#1525]
The [note in I.9](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-32) sounds like 2018 is in the future. It could be rephrased as
"Soon (in C+20), most compilers [...]".

**Comment by cubbimew** [comment]
This is technically a subtask of #1547, but this bit is an easy fix.
