### ISSUE TITLE
Typos, wording, links...

### ISSUE THREAD

**Issue by pegleGrot** [isocpp/CppCoreGuidelines#1529]
A few small issues:

* [C.168](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ro-namespace). "Flag operator definitions that are not **_it_** the namespace of their operands" -- it -> in.
* [R.1](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-raii), In "See also: RAII", links to self.
* [ES.49](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-casts-named). "(e.g. from float to double or int64 from int32)" -- better use "int32 to int64" for consistency?
* [E.6](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Re-raii): "See also" links to non-existent #Se-noexcept instead of #Re-noexcept.
* [E.15](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Re-exception-ref): Under Note, the links link to a different base URL, rather than just target hashes.
* [T (intro)](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-templates): "...found in another ISO TS: ranges"(.) -- missing period.
* [T.60](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rt-depend): ..."an algorithm usually uses other algorithms and **_invoke_** operations that"... -- invoke -> invokes.
* [T.65](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rt-tag-dispatch): In example, "template\<class Itert\>" -- Itert -> Iter.

**Comment by cubbimew** [comment]
Thanks. E.6 was already fixed in 778b44c2 ,E.15 was fixed in ef78ef4d, I applied the rest.
