### ISSUE TITLE
F.5: declaring small functions inline is a pre-mature optimization

### ISSUE THREAD

**Issue by mmatrosov** [isocpp/CppCoreGuidelines#1534]
The current wording is:

> F.5: If a function is very small and time-critical, declare it inline

I thought C++ community agreed that our understanding of the `inline` keyword shifted from "apply this function in-place" to "this symbol (a function or a variable) might be present in multiple translation units". There is also a ubiquitous call that the only reliable way to prove performance of your code is to measure it. Even the current wording of the item says this:

> Some optimizers are good at inlining without hints from the programmer, but don't rely on it. Measure!

Now this seems a self-contradiction to me. The item says not to rely on the compiler and measure it, but it also says to rely on `inline`. Does not make sense. Seems like a call to pre-mature optimization violating current consensus of the community on the topic. 

I also remember that some clever guy (most probably Chandler Carruth, but I'm not sure) said that if a compiler (gcc IIRC) sees too many inlines in your code, it just starts to ignore them.

I propose to remove this item completely.

**Comment by jwakely** [comment]
If the function body isn't visible, the compiler can't inline it even if it wants to, because doing so would probably make the code smaller and faster. To make the body visible, you might need to declare it inline so it can be defined in a header.

The guideline days to do it for time critical functions, which assumes you have measured.

I don't think removing this would be an improvement.

In general, simple functions like accessors that just return a data member should be inline. That's uncontroversial, and it's unhelpful to suggest otherwise.

**Comment by mmatrosov** [comment]
> If the function body isn't visible, the compiler can't inline it even if it wants to when doing so would provably make the code smaller and faster.

This is not exactly true. Some work can be done with LTO. Also, I can imagine how a thorough implementation can import the body of a function from a module, since nothing prevents the compiler from doing it.

> To make the body visible, you might need to declare it inline so it can be defined in a header.

The logic is inverted here. You might say "To make the body visible, you might need to define it in a header", which would require adding `inline`. The key here is that the function body is visible to the compiler, _not_ that the function is `inline`. Exactly the same reasoning can be applied to small member functions, but they do not require `inline` keyword.

> The guideline days to do it for time critical functions, which assumes you have measured.

The guideline says "If a function is very _small_ and _time-critical_, declare it inline". First, I don't like this "very small" part. How you define "small"? In some cases it is obvious, but in most it is not. Why should a function size dictate how it should be declared? What if its size changes in future? Second, concerning "time-critical" part. Declaring a function inline might indeed improve your timings. But this is just one of possible optimization strategies, among the horde of them. What's so special about it? Let's move it to Performance section, where it should be.

> In general, simple functions like accessors that just return a data member should be inline. That's uncontroversial, and it's unhelpful to suggest otherwise.

I disagree. This is not free. If you edit a function declared in a header, the amount of code you need to recompile increases drastically. Even if you don't touch it, it is included in every translation unit and consumes time for parsing. So you definitely do pay for this, but it is not clear if you have anything in return. If you are not in performance critical code, you won't be able to measure difference. If you are overriding getters defined in an abstract base class, only through which this getter is ever called, it does not make any sense to define it inline.

**Comment by jwakely** [comment]
>  Exactly the same reasoning can be applied to small member functions, but they do not require inline keyword.

I'm not sure what you mean here. If you're referring to member functions defined in the class body, those _are_ inline functions, and _are_ declared inline, just as the guideline recommends.

**Comment by Philippe91** [comment]
The idea behind the anti-pattern "premature optimization", is to prevent adding complexity to make code fast during the early development stage. An inline function is rather the opposite than adding complexity.

**Comment by jwakely** [comment]
Exactly. Defining trivial getters that consist of a single return statement as non-inline functions, with separate declaration and definition, just in case you might need to change what they do later is needless complexity.

In fact, I'd call it premature optimization for compile times.

**Comment by mmatrosov** [comment]
> The inline specifier is not necessary to declare a function inline, there are other ways to declare a function inline 

Ok, agree. But this is not particularly obvious from the wording. Especially for a novice (to whom I believe the guidelines might be most valuable).

> Defining trivial getters that consist of a single return statement as non-inline functions, with separate declaration and definition, just in case you might need to change what they do later is needless complexity.

Most of the classes we write have both trivial small functions and non-trivial large functions. You suggest to declare the former as inline and the latter as non-inline. This means, the former must live in the header (either in a class body, or outside it), and the latter must live in the .cpp file. Thus, they end up in different places. Seems like an inconsistency to me. Inconsistency, which increases complexity.

**Comment by jwakely** [comment]
> Thus, they end up in different places.

Yes. And that's how most C++ code is written.

It would be a mistake for the guidelines to say all functions should be non-inline and separately defined and separately compiled, because it would negatively impact the performance of many (maybe most) C++ programs.

To get good performance without LTO, very small and/or time-critical functions should be made available to the compiler for inlining. So they should be visible to all callers, which generally means declaring them inline. Which is what the guideline recommends.

**Comment by jwakely** [comment]
> But this is not particularly obvious from the wording. Especially for a novice (to whom I believe the guidelines might be most valuable).

Such a novice who doesn't know that in-class function definitions are inline might instead write:

````
class A {
public:
  int foo() const;
};

inline int A::foo() const
{ /* ... */ }
```

So what? The end result is the same.

I still see no motivation to change the guideline.

**Comment by mmatrosov** [comment]
> Yes. And that's how most C++ code is written.

This is a weak argument. Most of C++ code I've seen is written really poorly, mostly because of the complexity of the language.

> It would be a mistake for the guidelines to say all functions should be non-inline and separately defined and separately compiled, because it would negatively impact the performance of many (maybe most) C++ programs.

I am not advocating this. I'm saying, both approaches have pros and cons.

> So what? The end result is the same.

It is not clear what we recommend in this case: define function inside or outside of a class. More decisions, more cognitive load. Would be nice to have a recommendation here as well.

**Comment by hsutter** [comment]
Editors call: We have no consensus for a change for the reasons that @jwakely mentioned.
