### ISSUE TITLE
C.46: Why does the rule only address single argument constructors?

### ISSUE THREAD

**Issue by BerndGe** [isocpp/CppCoreGuidelines#1536]
The same argument as in the rule can be made for
```
class Image
{
    public:
      Image (int width, int height);
};

void paint (const Image &img);

void f ()
{
    paint ({ 1, 2 }); // compiles
}
```
I find the implicit conversion here surprising. It would be avoided if the constructor were explicit.
In general I would make constructors 'explicit' except where a conversion is natural because the argument or list of arguments can be reasonable viewed as a representation of the object. For example,
```
Vec2d v;
...
v += { 1.0, 2.0 };
```
(for a two-dimensional vector) looks clear because { 1.0, 2.0 } looks like a two-dimensional vector. In contrast, { 1, 2} cannot reasonable be interpreted as an image.

**Comment by shaneasd** [comment]
To me the braces in ```paint ({ 1, 2 });``` imply that something is being constructed. If I see ```paint(1)```, without being familiar with the signature of ```paint``` I would assume it to be something like ```paint(int)```. If I see ```paint({1,2})``` I would assume the signature is ```paint(T)``` where T is some type which is constructed from two integers (i.e. it's clearer at the call site that something is being constructed before paint is called).

I think C.46 is right to highlight single argument implicit constructors as particularly problematic. Perhaps it is worth also having a rule providing guidance for multi-argument constructors though. I think probably the default in both cases should be to declare them explicit but that the deviation from this default should be much rarer for single argument constructors.

**Comment by BerndGe** [comment]
I even agree that single argument implicit constructors are "particularly problematic". My argument goes more in this direction: the core guidelines have many rules, IMO too many for teaching them practically (and rules like this cannot be enforced when there is room for deviations from the default). Under such circumstances it's good to have rules as general as possible.

**Comment by OrdoFlammae** [comment]
The syntax `{ 1, 2 }` actually creates an `initializer_list<int>`, which is actually calling the constructor of `vector<int>`. When you see that syntax, it should imply construction, not vectors.

**Comment by hsutter** [comment]
Editors call: We don't think multi-argument converting constructors are problematic in practice because they are invoked explicitly.
