### ISSUE TITLE
Consider a different mark up system

### ISSUE THREAD

**Issue by suy** [isocpp/CppCoreGuidelines#154]
Markdown is a very, very simple format that doesn't scale for such a large piece of text. Using GitHub Flavored Markdown (see #109) helps, but still doesn't have all the features that you might find useful, hence, why some people have suggested a full blown website (see #146). There is also the wish of having the site in a printable format (see #23).

I know this can open the bikeshedding gates, but I would like to suggest to use a more ambitious mark up language and tooling. [AsciiDoctor](http://asciidoctor.org) and [Sphinx](http://sphinx-doc.org/) are mature and powerful systems that still give you the lightweight formatting taste of MarkDown, but in AsciiDoc and reStructuredText respectively. They depend on Ruby and Python respectively, but GitHub also has native rendering of the files, there are online previewers, syntax highlighting and checking in editors, and a large etc.

I am not that familiar with Sphinx, but let me give you from the top of my head some obvious advantages of AsciiDoctor:

* You could split the file in several, and include all of them from the master document. GitHub doesn't render the master document in their preview, but provides a link as a fallback ([see AsciiDoctor's website as example](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/asciidoc-syntax-quick-reference.adoc)).
* Native table of contents.
* You could add a line with `source-language: cpp` at the top, and all the code blocks get syntax highlighting in C++ by default just indenting the code, without the "fenced code blocks".
* Callouts in source code.
* Proper cross references. To prevent #95.
* Support for pretty much everything you can think of.

Pandoc can help in the migration, and I can offer support in the manual adjustments afterwards. In any case, I think you should decide on this ASAP. You can stick with your preferred MarkDown extension/dialect, of course, but I'll advice you to decide it soon, because the MarkDown ecosystem can be quite fragmented.

**Comment by fdenzer** [comment]
i hate wikisyntax, yet this should be non-linear.
+1 for asciidoc.

It certainly does not qualify as a book in this rough draft stage which i like to read front to cover.
Being a single markdown page makes this even harder to read.

**Comment by kirbyfan64** [comment]
Anyone here considered using ReadTheDocs + reStructuredText or Markdown?

**Comment by NicolBolas** [comment]
How good is AsciiDoctor at generating PDFs, particularly for printing purposes? How does it handle hyphenation? What about pagination controls? And so forth.

I mention this because I'm more familiar with heavier-weight formatting tools like DocBook. The DocBook XSL stylesheets give you a *vast* array of options for configuring them, even without using customizations. And with customizations, you can get very good looking printable files.

**Comment by fdenzer** [comment]
Asciidoc can be converted to docbook. This format chain allows typesetting
comparable to LaTeX, as both are used for commercial books.

**Comment by suy** [comment]
@kirbyfan64 ReadTheDocs is using Sphinx. Note that MarkDown on ReadTheDocs still has some MarkDown limitations. Quoting [Getting Started](https://read-the-docs.readthedocs.org/en/latest/getting_started.html): "Markdown doesn’t support a lot of the features of Sphinx, like inline markup and directives. However, it works for basic prose content."

**Comment by tkruse** [comment]
Please note the tool pandoc (http://pandoc.org/) which transforms in a wide range of formats. As an example it can read markdown and export to AsciiDoc, latex, epub, etc.

That does not make the question irrelevant, but also not very urgent.

Also note my example of turning the markdown file to a github page at:
http://tkruse.github.io/CppCoreGuidelines/CppCoreGuidelines.html

Without requiring changes to the existing markdown file. A lot more things could be hacked in the github-pages process either by enhancing the html generation in ruby, or by some html5 client-side reprocessing of the document.

**Comment by tkruse** [comment]
My recipe for PDF file with code highlighting using pandoc (http://pandoc.org/) and mdast (https://github.com/wooorm/mdast):

file mdastrc.fenced:
```
{
  "settings": {
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*",
    "fences": true
  }
}
```
Only `"fences": true` is really necessary, but the other settings help preserving the original markdown)

shell:
```
# turn all indented code to fenced code
mdast CppCoreGuidelines.md -q --config-path ./mdast/.mdastrc-fenced 1> CppCoreGuidelines.md.fenced

# add 'cpp' as code language to fence openers (careful with indented fences in bullet lists)
sed ':a;N;$!ba;s/\n\n\(\s*\)```/\n\n\1```cpp/g' CppCoreGuidelines.md.fenced > CppCoreGuidelines.md.coded

# turn `<a name="foo"></a>` anchors into latex anchors `\label{foo}`
sed 's/<a name="/\\label{/g' CppCoreGuidelines.md.coded | sed 's/"><\/a>/\}/g' > CppCoreGuidelines.md.texlabels

# generate pdf
pandoc -f markdown -t latex -o CppCoreGuidelines.pdf CppCoreGuidelines.md.texlabels
```
Result: http://s000.tinyupload.com/?file_id=99209882622091444255

This was using pandoc 1.15 (though 1.13 should also work), mdast 2.0.0. The search/replace lines are brittle, could be made more robust, use with appropriate care.

I also tried asciidoc and asciidoctor based on pandoc asciidoc output, but both disappointed in comparison. (multiple parsing errors, pdf links opened "Open file" popup, asciidoctor took 5 minutes to render, pandoc takes 10 secs, asciidoctor pdf looked uglier than latex)

**Comment by DanielSWolf** [comment]
+1 for AsciiDoc. Look at the excellent open source book Pro Git. Its [first edition](https://github.com/progit/progit) was written in Markdown. For the [second edition](https://github.com/progit/progit2), they switched to AsciiDoc, which apparently made things much easier.

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

We did consider other options and picked MarkDown. This thread reflects why no other option stood out as a clear winner. Thanks for the suggestion and discussion.

**Comment by suy** [comment]
Well, I read this thread and I reach out a very different conclusion. ;)

Just the fact that this document has to be single file with 14000 lines, and that you have to add ad hoc HTML due to MarkDown's limitations speaks clearly of which format is not the winner. Editing and previewing the changes in Github is not so convenient with such a massive document. I don't think that MarkDown's popularity is a strong argument when the alternatives have a good amount of compatibility.

I agree with Thibault, though, that is not urgent because there is good tooling to convert to other formats in case you change your mind.

Thanks for considering.

**Comment by kirbyfan64** [comment]
I still think someone should at least look at using ReadTheDocs with the current Markdown. It lets you split it into multiple files and will generate a TOC-style sidebar for navigation.

**Comment by suy** [comment]
That and the full website (cf #146) are good approaches, yes.
