### ISSUE TITLE
Use of "may not"

### ISSUE THREAD

**Issue by gennaroprota** [isocpp/CppCoreGuidelines#1542]
Throughout the guidelines, the expression "may not" is sometimes used to mean "it's possible that it doesn't", sometimes to mean "must not". In fact, both usages are possible in English, but this ambiguity doesn't seem good for a technical document. See also:

  &lt;https://english.stackexchange.com/questions/56065/must-not-or-may-not-which-is-the-most-correct&gt;

(thanks Paul Smith for providing that link).

I suggest, as a drafting rule, to always avoid "may not".

**Comment by hsutter** [comment]
Editors call: We agree that "may not" is ambiguous and will take a pass through the document to either "might not" or "must not" to clear.

**Comment by gennaroprota** [comment]
Thanks. That's more than I asked for. Quickly skimming through the diff, I
noticed three edits that "ate" the space following "might": you might (:-))
want to look for "mighthave", "mighteventually" and "mightown".

**Comment by hsutter** [comment]
Thanks, fixed! Yay regex search `might[^\s]` ... FTW.
