### ISSUE TITLE
Guideline for noexcept default constructors

### ISSUE THREAD

**Issue by johelegp** [isocpp/CppCoreGuidelines#1544]
- F.6: If your function may not throw, declare it `noexcept`
Enforcement: Flag throwing `swap`, `move`, destructors, and **default constructors**.
Emphasis mine.
  * C.37: Make destructors `noexcept`
  * C.66: Make move operations `noexcept`
  * C.85: Make `swap` `noexcept`
  * No rule for default constructors.
    - E.16: Destructors, deallocation, and `swap` must never fail
      Same.

Given the close relationship between the moved-from state and default-constructed state, it seems this guideline's missing.

**Comment by vmgolovin** [comment]
Actually, the guidelines about non-throwing are somewhat contradictive: https://github.com/isocpp/CppCoreGuidelines/issues/231

**Comment by hsutter** [comment]
Editors call: This is covered in C.44.
