### ISSUE TITLE
Singular/plural mismatch and lack of subject in "SF.9: Avoid cyclic dependencies among source files"

### ISSUE THREAD

**Issue by gennaroprota** [isocpp/CppCoreGuidelines#1545]
Hi,

the first paragraph of SF.9 currently reads:

"Cycles complicates comprehension and slows down compilation. Complicates conversion to use language-supported modules (when they become available)."

It should either read:

  1. "*A cycle* complicates comprehension and slows down compilation. *It also*
  complicates conversion to use language-supported modules (when they become
  available)."

or

  2. "Cycles *complicate* comprehension and *slow* down compilation. *They also
  complicate* conversion to use language-supported modules (when they become
  available)."

Note that the paragraphs that follow use plural. That might be a reason to choose (2); or even, to choose (1), to be less boring.

**Comment by cubbimew** [comment]
went with 2 to keep it consistent, thanks
