### ISSUE TITLE
Consider using `std::size_t` over `size_t`

### ISSUE THREAD

**Issue by Pharap** [isocpp/CppCoreGuidelines#1546]
By the rules of the standard, the only way to get access to `size_t` without explicitly bringing `std::size_t` into the global namespace is to use _deprecated_ (as of C++11) C headers (e.g. `<stddef.h>`), which is arguably not good practice.

Perhaps this guideline should lead by example and exclusively use `std::size_t` to reflect that headers such as `<cstddef>` should be preferred over deprecated headers such as `<stddef.h>`, and to reflect that bringing names from the `std` namespace into the global namespace is generally a bad idea (i.e. it 'pollutes' the global namespace)?

**Comment by Pharap** [comment]
Related to #391, though not strictly a duplicate.

**Comment by jwakely** [comment]
> is to use _deprecated_ (as of C++11) C headers

They have been deprecated since C++98, and in reality they're not going away.
