### ISSUE TITLE
[Progress Report] Translation to Korean

### ISSUE THREAD

**Issue by utilForever** [isocpp/CppCoreGuidelines#1558]
Hello, long time no sees.
Finally, we completed the translation of "C++ Core Guidelines" to Korean.
It is based on the version of September 2018.
Also, we changed the design of a web site. It is based on mkdocs.

- Links: https://www.cppkorea.org/CppCoreGuidelines/

We'll update the document for 2020. Thanks. :)

**Comment by hsutter** [comment]
Editors call: Thanks for letting us know! Tagged as [translation].
