### ISSUE TITLE
ES.23: Prefer the {} initializer syntax - a different point of view

### ISSUE THREAD

**Issue by r4nt** [isocpp/CppCoreGuidelines#156]
Here's a different set of rules for braced initialization. The underlying principle is "always use the least powerful feature to get the job done". This gives more information to the reader at the call site, as it conveys information that certain things cannot happen.

1. Prefer copy initialization (T x = y) over other forms of initialization because it will only call implicit constructors. When you see T x = y, you know x becomes the same as y. This is the least powerful construct for initialization and thus should be used when possible.

2. Prefer direct initialization (T x(a, b, c)) over brace initialization (T x{a, b, c}). Brace initialization is the more powerful feature, and thus should only be used if direct initialization doesn't get the job done.
T x{a, b, c} may either call a 3-arg constructor of T or a constructor from an initializer_list. It is unclear at the call site which constructor gets called.
T x(a, b, c) will always call a 3-arg constructor; the reader now knows more about what this code does.

Experience shows that it's non-trivial to figure out what string{3, 'a'} does.
Another interesting example is the innocent looking snippet:
int n;
Foo({&n, {}});

with Foo being declared as:
void Foo(unique_ptr<int> p);

**Comment by hsutter** [comment]
Having many syntaxes is confusing and we would like a more uniform style. Brace init is not fully uniform, but it's close.

**Comment by hsutter** [comment]
The `(size, default_value)` or `(size)` case is a quirk and a documented exception.

Passing the address of a local to a `unque_ptr` seems problematic; the snippest doesn't look innocent to us.

**Comment by jeremyong** [comment]
Is it worth revisiting this guideline due to the class template deduction present in C++17?

```c++
std::vector<int> stuff{1, 2, 3}; // Vector of 1, 2, 3
std::vector last_two{stuff.begin() + 1, stuff.end()}; // Becomes a vector of two iterators (surprise)
```

The quirk seems to extend far beyond `(size, default_value)` simply because a user may implement classes that have colliding semantics (not just two arguments).

I think I keep wanting to like uniform initialization but find myself unsure of how to explain the quirk to a newer programmer. Alternatively, the recommendation may be to avoid initializer_list usage in user-code and just memorize the exceptions in the standard `container` classes.

**Comment by MikeGitb** [comment]
I follow the rule to use `Foo{x,y,z}` when I want to insert the values x,y,z into the newly created container / struct / pair / data structure and `Foo(x,y,z)` for constructors that resemble a classic function call (x,y,z are parameters to a constructor that performs some computation on them like size & default value or the path to the file to be opened) that (usually) works out quite nicely with standard library and other types and imho improves readability.

Using a single syntax almost (but just almost) everywhere when it means conceptually different things is imho in no way more intuitive or easier to understand than consistently using the difference in syntax to mark a difference in semantics.

**Comment by jeremyong** [comment]
Funnily enough, I just ran into another case where initializing a `std::vector<size_t>` like `vec{3}` (intending to preallocate 3 elements accidentally created a vector with a single element 3. This was again, another new case for me which is a nuisance to explain to beginners if teaching them to "prefer this syntax everywhere."
