### ISSUE TITLE
avoid static const string/vector

### ISSUE THREAD

**Issue by tiagomacarios** [isocpp/CppCoreGuidelines#1560]
Ex:
https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
"Global strings: if you require a global or static string constant, consider using a simple character array, or a char pointer to the first element of a string literal. String literals have static storage duration already and are usually sufficient.
Maps, sets, and other dynamic containers: if you require a static, fixed collection, such as a set to search against or a lookup table, you cannot use the dynamic containers from the standard library as a static variable, since they have non-trivial destructors. Instead, consider a simple array of trivial types, e.g. an array of arrays of ints (for a "map from int to int"), or an array of pairs (e.g. pairs of int and const char*). For small collections, linear search is entirely sufficient (and efficient, due to memory locality); consider using the facilities from absl/algorithm/container.h for the standard operations. If necessary, keep the collection in sorted order and use a binary search algorithm. If you do really prefer a dynamic container from the standard library, consider using a function-local static pointer, as described below."

**Comment by cubbimew** [comment]
is this effectively the same as #638 ?

**Comment by MikeGitb** [comment]
> Maps, sets, and other dynamic containers: if you require a static, fixed collection, such as a set to search against or a lookup table, you cannot use the dynamic containers from the standard library as a static variable, since they have non-trivial destructors. 

Why does the existence of a non-trivial destructor prevent their use? I believe that is an Google/Abseil - specific rule, where they generally ban destruction of static/global data (due to potential races when multiple threads are involved).
Regarding strings: Please use/recommend string_view over a string litteral instead of a simple pointer or char array.

**Comment by hsutter** [comment]
Editors call: We think the key is to avoid/manage dynamic initialization as proposed in #638 and we will consider this in the context of that issue.
