### ISSUE TITLE
Consider editing Con.1 Exception

### ISSUE THREAD

**Issue by alanbarr** [isocpp/CppCoreGuidelines#1562]
On first glance I initially thought the [Con.1](https://github.com/isocpp/CppCoreGuidelines/blob/1429d9ec719e869bea87ae98f94a89a96c122d7e/CppCoreGuidelines.md#Rconst-immutable) Exception and  [Con.3](https://github.com/isocpp/CppCoreGuidelines/blob/1429d9ec719e869bea87ae98f94a89a96c122d7e/CppCoreGuidelines.md#con3-by-default-pass-pointers-and-references-to-consts) were a little contradictory.

I was distracted by the leftmost / first const, and wonder if dropping it altogether would make the example clearer, i.e. from:

    void f(const char* const p); // pedantic

to

    void f(char* const p); // pedantic

Or alternatively elaborating more in the comment as to the specifics. 

Related issues: #975

**Comment by hsutter** [comment]
Editors call: Thanks, but we're not sure this makes the examples clearer so we think it's okay as it is.
