### ISSUE TITLE
Pro.bounds.2: Only index into arrays using constant expressions - What about std::arrays?

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#1563]
Hi,

Regarding rule `Pro.bounds.2: Only index into arrays using constant expressions`. What is your opinion about raw indexing into `std::array`s? Example:

```
template <std::size_t N>
void foo (std::array<int, N>& x, std::array<int, N>& y)
{
    for (std::size_t i = 0U; i < N; ++i)
    {
          some_complex_function(x[i], y[i]);
    }
}
```
Here the indexing is perfectly safe because `i` is guaranteed at compile-time to be in the range `[0, N)`, therefore always having a safe access. Should we really be doing bound checks in this scenario?

**Comment by hsutter** [comment]
Editors call: A range-for loop here would be safe by construction. This code is a good example of code that a reader may deduce happens to be safe today (and fragile under maintenance) but where proving it is safe can require arbitrary static analysis. We do want bounds checking in this scenario, and if the compiler can deduce that out of bounds access can never occur it free to elide the checking.

**Comment by carlosgalvezp** [comment]
Hi again @hsutter !
First of all thanks for the comments, I definitely agree with making code safe by construction and future-proof.

However I don't see how to make the code safer, could you provide a suggestion? You mention "a range-for loop", but that's not possible here, is it? Note that I'm indexing into **two** arrays, not one (where a range-for loop would be the de-facto choice).

Replacing the loop with iterators is more verbose and error-prone, would you agree?

```
auto it_x = x.begin();
auto it_y = y.begin();

while ( (it_x != x.end()) && (it_y != y.end()) )
{
    some_complex_function(*it_x, *it_y);
   ++it_x;
   ++it_y;
}
```

**Comment by jwakely** [comment]
It's no help today, but if [P2164](https://wg21.link/p2164) gets approved for C++23 then it should be possible to:

```cpp
for(const auto& [i, x_i] : std::views::enumerate(x))
  some_complex_function(x_i, y[i]);
```

**Comment by jwakely** [comment]
Or with [p2321](https://wg21.link/p2321):

```cpp
for(auto z : std::views::zip(x, y))
  some_complex_function(std::get<0>(z), std::get<1>(z));
```

which can be written as:

```cpp
for(auto z : std::views::zip(x, y))
  std::apply(some_complex_function, z);
```
or:

```cpp
std::ranges::for_each(std::views::zip(x, y), [](auto z) { std::apply(some_complex_function, z); });
```

**Comment by shaneasd** [comment]
related question: https://stackoverflow.com/questions/8511035/sequence-zip-function-for-c11

**Comment by carlosgalvezp** [comment]
Thanks, `zip` plus structured bindings sounds like it would be the best solution! Unfortunately not available in the STL yet, I'll look into ways of implementing them myself until then. Thanks!

**Comment by jwakely** [comment]
See https://github.com/ericniebler/range-v3
