### ISSUE TITLE
22512 lines (15313 sloc) 794 KB - and no complaints?

### ISSUE THREAD

**Issue by ghost** [isocpp/CppCoreGuidelines#1575]
The source:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md

A single-file, 22512 lines?

What happened to "splitting systems down into manageable chunks"?

The result:

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

Again, a single document, without any hierarchy, even not in the navigation?

## Expected

C++ should be an example for "Engineering Bests Practices".

=> Split the sources down into managable chunks

=> Sources should follow rules of file-format (md) and host (github)

=> The html result should have an hierarchical navigation

I am sure that many companies are willing to assist in modernizing the document-source and document-result.

Edit: Ideally, the resulting site has an option to download as PDF (but with full native hierarchical navigation)

## Examples

* https://developers.quarkchain.io/#transaction
  * no pdf, but for now my personal favorite
* https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/#feedback
  * with full-nav-pdf, md, generator: https://github.com/dotnet/docfx
* https://docs.ansible.com/ansible/latest/user_guide/index.html

**Comment by shaneasd** [comment]
You might have a point about the source file but I think the resulting html is reasonable. If you know the category of the rule you're looking for then you can select it from the bar on the side which then provides you with a contents page of rules in that category with links to the details of each rule. To my mind that is hierarchical navigation. If you don't know what category the rule you're looking for is in then it's quite helpful to have them all on the one page which you can use your browsers search on.

What is the use case that you have that the current format is inappropriate for and that the linked ansible docs are better for? Maybe I just don't realize what I'm missing out on.

**Comment by lazaridiscom** [comment]
See, for sure there is folks out there which would say:

 "the html site is too much. A single txt file is enough, I can still search fine, and grep better".

Matter of mentality.

This one is very nice, based on `md` and has a pdf-download with full hierarchical TOC:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/#feedback

Not sure how its generated, though (but I guess MS would be supportive towards a isocpp/Stroustrup project).

(I actually believe they should add they doc-generator as a github action, but that's another issue)

**Comment by shaneasd** [comment]
Can you elaborate on what it is that makes that documentation very nice though? Is it easier to find the information you need? If so why?

**Comment by lazaridiscom** [comment]
I can't. What I can is to find another (possibly even nicer example).

**Comment by lazaridiscom** [comment]
https://developers.quarkchain.io/#transaction

**Comment by cubbimew** [comment]
Similar request was raised in an earlier issue #1490

**Comment by lazaridiscom** [comment]
nah, #1490 with the fancy name "tranclusion" is a about using and include directive.

My issue here is essentially about "professionalism of process and result" (though I did not express it like this, to avoid the usual drama).

* must: the resulting documentation must have "industrial grade quality"
* should: the document-collaboration-process should have "industrial grade quality"

For "industrial grade quality", refer e.g. to hardware-design domain.

C++ is the King - deserves simply a better quality.

**Comment by lazaridiscom** [comment]
> nah, #1490 with the fancy name "tranclusion" is a about using and include directive.

on second thiught, you're right. it's similar.

**Comment by hsutter** [comment]
Editors call: Understood, there are pros and cons to a single source file, but our opinion remains the same as for #1490.
