### ISSUE TITLE
R.37 Does not give a viable option for aliased unique_pointer

### ISSUE THREAD

**Issue by phxnsharp** [isocpp/CppCoreGuidelines#1582]
R.37 states that a function should maintain a local function scope reference for aliased shared or unique pointers. However, by definition Unique_pointer does not allow that as there can only ever be one reference. This rule cannot be applied to a unique pointer and no alternatives are given to ensure the longevity of the unique_pointer.

```cpp
// global (static or heap), or aliased local ...
unique_ptr<widget> g_p = ...;

void my_code()
{
    // cheap: 1 increment covers this entire function and all the call trees below us
    auto pin = g_p;  //BAD: Does not compile

    // GOOD: passing pointer or reference obtained from a local unaliased smart pointer
    f(*pin);

    // GOOD: same reason
    pin->func();
}
```

**Comment by markyin** [comment]
> Enforcement
(Simple) Warn if a pointer or reference obtained from a smart pointer variable (Unique_pointer or Shared_pointer) that is non-local, or that is local but potentially aliased, is used in a function call. If the smart pointer is a Shared_pointer then suggest taking a local copy of the smart pointer and obtain a pointer or reference from that instead.

**Comment by phxnsharp** [comment]
Yes of course I read and understood that. However, I consider that even worse. R.37 spends a significant amount of space trying to convince you that using aliased pointers is bad, then leaves you with no alternatives. 

In our environment we use the PIMPL pattern quite a lot. A convenient way to implement it is with a std::unique_ptr to the implementation object at the class level. This warning would invalidate nearly every use of the PIMPL pattern (we treat warnings as errors). Moreover, no viable alternatives for this case have been provided. This would render the warning meaningless in our context as it would be wrong way more often than it is right.

**Comment by hsutter** [comment]
Editors call: The Enforcement aims to cover this by recommending taking a copy only for copyable smart pointers.
