### ISSUE TITLE
Avoid locale, facet, ctype.h.

### ISSUE THREAD

**Issue by expnkx** [isocpp/CppCoreGuidelines#1583]
Locale related stuffs are notoriously slow and harm the deterministic of programs.

Do not use isspace. It is UB.

**Comment by jwakely** [comment]
The example at https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-367 does need to cast the value you avoid UB, but that function is a simple table lookup and so neither slow but non-deterministic.

**Comment by expnkx** [comment]
> The example at https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-367 does need to cast the value you avoid UB, but that function is a simple table lookup and so neither slow but non-deterministic.

Even you are the author of libstdc++ and I appreciate your work. Unfortunately, you are terribly wrong. std::isspace uses locale and it will generate any output it could theoretically, that definitely harms the deterministic of the program.

//std::isspace considered harmful. Time to kick locale from the language because it violates zero overhead principle
/*
$ ./isspace.exe
std::isspace:   0.900008s
misspace1:      0.331s
misspace2:      0.329s
misspace3:      0.26898700000000003s
misspace4:      0.274999s
fastisspace:    0.219001s
fastisspacerev: 0s
fastisspacerev2:        0.131999s
fastisspacerev3:        0s
fastisspacerev4:        0s
total value: 0


*/
https://bitbucket.org/ejsvifq_mabmip/fast_io/src/master/benchmarks/0005.standardlibrary_bench/isspace.cc

**Comment by expnkx** [comment]
https://github.com/lattera/glibc/blob/master/ctype/ctype.c
https://github.com/lattera/glibc/blob/master/ctype/ctype.h
What are these abominations of glibc? function pointer for one line function like isspace? No thank you, avoid it at all cost.

**Comment by expnkx** [comment]
https://godbolt.org/z/rWaFIc

This proves isspace cannot be inlined
