### ISSUE TITLE
Avoid iostream and cstdio

### ISSUE THREAD

**Issue by expnkx** [isocpp/CppCoreGuidelines#1584]
They are harmful, slow and insecure.

**Comment by cubbimew** [comment]
As In.0 puts it, 

> We are uncomfortable with rules that simply state "don't do that!" without offering an alternative.

what's your alternative?

**Comment by shaneasd** [comment]
Note also http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slio3-prefer-iostreams-for-io

**Comment by expnkx** [comment]
> Note also http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slio3-prefer-iostreams-for-io

Wrong. They should be both avoided since iostream is implemented by stdio.h.

iostream does not immue to TOCTTOU and you cannot add O_NOFOLLOW flags like POSIX does which means theoretically any fstream open could be a privilege boost.
And unlike FILE*, you can use fdopen with POSIX standard to construct one, you cannot do that with iostream.
iostream's virtual inheritance graph is a long term issue of C++.
Not considering std::locale and facet are just another abominations. 

Solution is to revamp the C++ io system in the future and deprecate iostream and FILE*. Also we need to deprecate charconv, fmt,  filesystem, network, LLFIO, process, boost iostreams all these IO libraries who just do the same thing and iostream and stdio.h do and they have a compatibility issue. There is a reason why iostream is largely banned like exceptions and RTTI. 
https://bitbucket.org/ejsvifq_mabmip/fast_io

**Comment by expnkx** [comment]
iostream is another issue that needs to be solved like herbception does to the C++ exceptions.

**Comment by shaneasd** [comment]
My point with http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slio3-prefer-iostreams-for-io was merely that a rule already exists addressing your concern. Maybe it's right. Maybe it's wrong but it's a relevant read for anyone concerned with this issue. If something were to change as a result of this issue it would be that rule.

Unfortunately I think I distracted you from @cubbimew's more relevant question: **what's your alternative?**

Keep in mind, rewriting iostream, charconv, fmt, filesystem, network, LLFIO, proces and boost iostreams is not practical advice to give to a c++17 programmer who is the target audience for theses guidelines.

**Comment by expnkx** [comment]
> Keep in mind, rewriting iostream, charconv, fmt, filesystem, network, LLFIO, proces and boost iostreams is not practical advice to give to a c++17 programmer who is the target audience for theses guidelines.


That is exactly the priority of the language now. Make a new plan to deprecate all of them and revamp a new one. Or the language will die since this trend of charconv and filesystem are just problematic.

People (like LLVM does) who banned iostream should be legalized. They have legitimate reasons to ban them.

**Comment by jwakely** [comment]
It's very hard to take you seriously with phrases like abomination used to describe facilities used by most C++ programs, without problems.

**Comment by dominiklohmann** [comment]
You're commenting on guidelines for the current language. This is neither a place for asking other people to write the proposal you so desperately want written, nor is it a place for pitching your own libraries. This is just unnecessary noise for people watching this repository.

**Comment by expnkx** [comment]
> It's very hard to take you seriously with phrases like abomination used to describe facilities used by most C++ programs, without problems.

You do not take seriously since you have used abominations for so long just like C programmers do not realize error code is security issues. I have serious discussions with a lot of people in real-world and they completely agree with me.

We could have a serious skype talk on this topic since I believe C++ is going the terribly wrong direction.

Herbception should be prioritized for everything else. C++23 network library needs to be further delayed. Add herbception and contract in C++23. Other stuffs should be furtherly postponed.

**Comment by expnkx** [comment]
> You're commenting on guidelines for the current language. This is neither a place for asking other people to write the proposal you so desperately want written, nor is it a place for pitching your own libraries. This is just unnecessary noise for people watching this repository.

Just do not use iostream tbh. Write your own one and wrap with POSIX apis.

**Comment by expnkx** [comment]
https://www.linkedin.com/pulse/c-iostreams-considered-harmful-henrique-bucher

**Comment by jwakely** [comment]
Some of that article is so stupid it makes my head hurt.

> most of the C++ methods are explicitly mapped to the GLIBC C-functions

when looking at a function that just extracts an integer from a `time_point` and returns it as a `time_t`. There are no "GLIBC C-functions" there at all, he got confused by a code comment.

Do you have anything constructive for the guidelines, or just more of the same hyperbole?

**Comment by expnkx** [comment]
> Some of that article is so stupid it makes my head hurt.
> 
> > most of the C++ methods are explicitly mapped to the GLIBC C-functions
> 
> when looking at a function that just extracts an integer from a `time_point` and returns it as a `time_t`. There are no "GLIBC C-functions" there at all, he got confused by a code comment.
> 
> Do you have anything constructive for the guidelines, or just more of the same hyperbole?

"And third, now() just makes a dumb call to clock_gettime(). Another compiler path, depending on system, would call gettimeofday(). I removed several of these #ifdefs for clarity."

He is exactly right.

That is a very true fact so-called C++ standard library that just usually wraps libc functions. stdio_filebuf for example.

https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/ext/stdio_filebuf.h

These are all the different levels of hacks I did to stream. Hack its internal FILE*, construct stream from FILE* cross platforms to support legacy C++ toxic stream code base. It is totally a pain.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/stream_file.h

**Comment by expnkx** [comment]
Here is another example of why C++ iostream sucks. Protected methods and private data members are OBJECTIVELY harmful. getting fd will cause UBsanitizers to complain. Like I said before, iostream encourages type confusion. Itself is a bug. iostream = type confusion. DON'T USE IT, IT IS UB.
https://github.com/google/sanitizers/issues/1203

**Comment by expnkx** [comment]
iostream = binary bloat. AVOID IT AS PLAGUE IF YOU WANT PERFORMANCE.

**Comment by jwakely** [comment]
You should know that these rants just make everybody want to ignore you, even if some of your points are valid.

I'm unsubscribing from updates to this ticket.
