### ISSUE TITLE
es.28 has deducing type error

### ISSUE THREAD

**Issue by markyin** [isocpp/CppCoreGuidelines#1590]
`string var = [&]{
    if (!in) return "";   // default
    string s;
    for (char c : in >> c)
        s += toupper(c);
    return s;
}(); // note ()
`
there's an error to deduce for lambda return type. Demo is [here](https://godbolt.org/z/cRHcM9)

**Comment by jwakely** [comment]
And it has undefined behaviour if `is_signed_v<char>` and a negative value is read from the stream.

**Comment by jwakely** [comment]
And `for (char c : in >> c)` doesn't compile either.

**Comment by SharpSnake** [comment]
Sure it is, in lambda every return branch must deduce to the same type.
(And the "for (char c : in >> c)" also doesn't make scese)

How about change the example like this:

        using namespace std::string_literals;
	string var = [&]{
		if (!in) return ""s;   // default
		string s;
		char c;
		for (;in >> c;)
			s += toupper(c);
		return s;
	}();

or this maybe even better:

         string var = [&]() -> std::string	{
		if (!in) return "";   // default
		string s;
		char c;
		for (;in >> c;)
			s += toupper(c);
		return s;
	}();

**Comment by cubbimew** [comment]
char c; is in wider scope than necessary, and it still has the UB @jwakely noted.
I think this example can be just dropped; the rule already has "Example, bad", and "Example, good", and it's unclear what this additional example adds.
