### ISSUE TITLE
Consider guidance on consistent, explicit default initalization

### ISSUE THREAD

**Issue by davidmatson** [isocpp/CppCoreGuidelines#1594]
Should there be guidance on whether to rely on implicit default initialization for types where that works?

As the guidelines mention in **C.43**, some local variables will be uninitialized if they are declared without any initializer specified, and some will be default initialized:
>Statically allocated objects of built-in types are by default initialized to 0, but local built-in variables are not.

The guidelines also suggest using explicit default initialization for the types that don't get it automatically:
>Assuming that you want initialization, an explicit default initialization can help

Should there be guidance on when to use explicit default initialization?

For example, consider:
```c++
void use()
{
    int i;
    std::string s;
    std::string* p;
    my_type t;
}
```

Both `i` and `p` are uninitialized, and `t` may or may not be uninitialized (or contain uninitialized data) depending on what my_type is (alias, type with fields of a built-in type, \#define, etc.).

As an extension/combination of **ES.20: Always initialize an object** and **ES.23: Prefer the {}-initializer syntax**, would it be worth recommending always using explicit default initialization?
```c++
void use()
{
    int i{};
    std::string s{};
    std::string* p{};
    my_type t{};
}
```

Note that the sample code in the guidelines is currently mixed here (if I'm understanding correctly which types could be uninitializedvariables), sometimes using an explicit default initialization for types where it isn't "needed" and sometimes omitting it:
```c++
void use()
{
    // From ES.20:
    int i;   // bad: uninitialized variable
    // From ES.20:
    string s;    // OK: default initialized
    // From C.64:
    X x{};
    // From C.81:
    unique_ptr<int> pi {};
}

**Comment by davidmatson** [comment]
In _The C++ Programing Language_, Fourth Edition, there's a similar recommendation in 11.2:

(Shows a type that is initialized by default an a type that isn't.)
> … This can be confusing. To be sure to get default initialization, use {}.
(Shows initializing both types with {}, even the type that would get initialized by default without that syntax.)

**Comment by hsutter** [comment]
Editors call: Initialization is important, and we think ES.20 is sufficient. Requiring `{}` on types where it well known to make no difference will probably be perceived as burdensome and not useful enough to justify a rule.
