### ISSUE TITLE
Consider compile-time override approach.

### ISSUE THREAD

**Issue by mvoronoy** [isocpp/CppCoreGuidelines#1595]
**Motivation**: Standard classes contains lot of algorithms to do conceptually similar actions in different way. For example you can initialize iteration over `std::map` by methods: `begin`, `find`, `lower_bound`, `rbegin`. But range-based `for` loop allows leverage only begin/end pair. (Of course  c++20 ranges library gives a way to overcome this but using runtime capabilities only).
**Rationale**: range-base for loop expects from container 2 simple idioms "give me begin of range and end of range". Programmers have several ways to implement such idioma:
  
- create proxy to feed begin/end in expected way (actually c++20 ranges do it) ;
- overrides some method by inheritance;
- provide lambda/callback to invoke correct functionality.

My rationale - to give a way to do as much as possible at compile time.
**Proposed Implementation**
create something like mixed_idiom_map_view ( _pseudo-code_ )

    template <typename Idiom1, typename ... IdiomX>
    class mixed_idiom_map_view : public Idiom1, public mixed_idiom_map_view <IdiomX ...>
    { 
    //... some code there
        using base_t = mixed_idiom_map_view<IdiomX ... >;
        using use_begin_t = typename std::conditional< CHECK_CLASS_HAS_MEMBER(Idiom1, begin), Idiom1, base_t >::type;
        using base_begin_t::begin; // <--(!) compile time override begin behavior
       // the same definition for "end" nethod
    }

After this we can create many small definitions that allow modify begin/end behavior at compile time. ( _pseudo-code_ )

    namespace idiom{
      struct regular_begin { iterator begin() const {return some_cont.begin(); }};
      struct lower_bound_as_begin { iterator begin() const {return some_cont.lower_bound(my_key);}};
      struct find_as_begin { iterator begin() const {return some_cont.lower_bound(my_key);}};
     
       //some idioms can combine both methods begin / end like std::map::equal_range
      struct equal_range {
            equal_range(key, map) { this->_pair = map.equal_range(key); }
            iterator begin() const {return _pair.first;};
            iterator end() const {return _pair.second;};
     };
   }

Putting all together:

    //allow implement iteration on range [lower_bound, end)
    mixed_idiom_map_view <idiom::lower_bound_as_begin, idiom::regular_end > my_composed_map1;
    for( auto v : my_composed_map1 ) ...

    // allow implement iteration in reverse order [rbegin, rend)
     mixed_idiom_map_view <idiom::rbegin, idiom::rend> my_composed_map2;
    for( auto v : my_composed_map2 ) ...   

give as ability to write `for( auto p: my_composed_map)` where begin/end evaluated at compile time

Note: that `mixed_idiom` approach may be used not only for container implementation, but whenever exists more than one algorithm to implement generic idiom of initialization, checking bounds, iterate next

**Comment by brenoguim** [comment]
I use another approach to solve that same problem. Something along these lines (code has been simplified):
 ```
template <class It>
struct iterable { It begin, end; };
template <class It> It begin(iterable<It> it) { return it.begin; }
template <class It> It end(iterable<It> it) { return it.end; }
template <class It> iterable<It> make_iterable(It begin, It end) { return iterable<It>{b, e}; }
```
To be used as:

```
for (auto& k2v  : make_iterable(map.lower_bound(my_key), map.end())) {
}
```

**Comment by mvoronoy** [comment]
Th example with `make_pair` is clear and simple. But It doesn't allow lazy evaluation) e.g.
    auto pair = make_iterable(map.lower_bound(my_key), map.end());
    map.insert(minimal_value ...
    for( k2v : pair )// <-- pair is taken before minimal_value inserted

**Comment by brenoguim** [comment]
Well, if you want to make that lazy, just add a lambda:
```
auto lazy_pair = [&] { return make_iterable(map.lower_bound(my_key), map.end()); };
map.insert(minimal_value ...
for( k2v : lazy_pair())
```

But honestly, I don't think anyone actually ever did that. This is just the old problem of taking an iterator, modifying the container and then using that iterator. That's everywhere. Being careful with that is part of writing C++.

By the way, for the example:
```
mixed_idiom_map_view <idiom::lower_bound_as_begin, idiom::regular_end > my_composed_map1;
for( auto v : my_composed_map1 ) ...
```

Where does "my_key" go?

**Comment by mvoronoy** [comment]
@brenoguim - with lambda you caught my point. That what I started with - but lambda is a kind of "runtime overriding" , my initial post tries to introduce compile-time overriding "pattern" (quotas because I'd like avoid too ambition goals). 

Also, back to laziness, as shown by functional-programming - is a good start point for predictable code.

**Comment by brenoguim** [comment]
Sorry, I might be missing the point. By the time the compiler reaches the `for (auto k2v : lazy_pair())`, it knows exactly which code to invoke. It's compile time. Of course, the actual calculation of lower_bound will be in runtime, but that's the same for your example, right?

**Comment by mvoronoy** [comment]
In construction like `for (auto k2v : lazy_pair)` methods begin/lower_bound/... is invoked at the time when loop begins, not when object is created. So once constructed object can be (for example) passed to some functions without doubt if object in actual state or not.

**Comment by brenoguim** [comment]
I guess what I didn't understand is where  `my_key` goes in your example. Is it at the construction site?

But anyway, I don't think this is the appropriate place for this suggestion. This is not a guideline but more like a library thing.

**Comment by mvoronoy** [comment]
About `my_key` - it should be constructor's argument of classes: `lower_bound_as_begin` and  `find_as_begin`.
 
About suggestion on placement... I agree that enlisted example is more about library. But conception of "mixed" classes that are compound at compile time and have 2 important benefits (1) laziness (2) be part of `constexpr` functions  deserve attention exactly as "pattern" of c++

**Comment by brenoguim** [comment]
It feels to me this might be very niche, but maybe this is just from my experience with the codebases I've seen over time.
Let's wait for the opinion of people with more diverse backgrounds :)

**Comment by jwakely** [comment]
I agree it's pretty niche, and fairly novel, and doesn't belong in the Core Guidelines.

**Comment by mvoronoy** [comment]
@jwakely IMHO compile-time override looks like core functionality of c++. But anyway - can you please recommend right niche for this proposal?

**Comment by jwakely** [comment]
I didn't say compile-time programming is not core functionality, but just because that has the word "core" doesn't make it suitable for these guidelines.

"The C++ Core Guidelines are a set of tried-and-true guidelines, rules, and best practices about coding in C++"

This seems to be a novel idea used by one person, with unknown field experience in unknown contexts. That is not a "tried-and-true ... best practice" .

If you want to publicize your idea there are more suitable places, such as proposing a library for Boost, or writing an article for [Overload](https://accu.org/index.php/journal). For a start that will provide useful feedback and peer review.

**Comment by hsutter** [comment]
Editors call: We agree with @jwakely, we aim for general and established Guidelines. Thanks though!
