### ISSUE TITLE
github repo: restore Travis static checks broken since dec 2019

### ISSUE THREAD

**Issue by tkruse** [isocpp/CppCoreGuidelines#1597]
it seems the integration with travis.org for checking the markdown is not  working anymore, new open PRs do not get checked.

Open PRs should all have a checks section like
```
All checks have passed
1 successful check
continuous-integration/travis-ci/pr — The Travis CI build passed 
```

CC @hsutter

**Comment by cubbimew** [comment]
hm, they are running https://travis-ci.org/github/isocpp/CppCoreGuidelines  but not getting notified back

**Comment by cubbimew** [comment]
It's back on, thanks
