### ISSUE TITLE
R.22 and C.151 are identical

### ISSUE THREAD

**Issue by Quuxplusone** [isocpp/CppCoreGuidelines#1612]
[R.22: Use `make_shared()` to make `shared_ptr`s](https://github.com/isocpp/CppCoreGuidelines/blob/986402298afa31acb46f44af5a2f8b3cb6788b73/CppCoreGuidelines.md#Rr-make_shared)

[C.151: Use `make_shared()` to construct objects owned by `shared_ptr`s](https://github.com/isocpp/CppCoreGuidelines/blob/986402298afa31acb46f44af5a2f8b3cb6788b73/CppCoreGuidelines.md#Rh-make_shared)

These could be links to the same place in the doc, instead of two separate sections with similar text.

Notably, R.22's enforcement section says

> - (Simple) Warn if a `shared_ptr` is constructed from the result of `new` rather than `make_shared`.

but C.151's enforcement section says (much more controversially)

> - Flag the repetitive usage of template specialization list `<Bar>`
>
> - Flag variables declared to be `shared_ptr<Bar>`

R.22's title should probably also be adjusted to match C.151's wording exactly. Obviously it's still okay to make a `shared_ptr` by doing e.g. `std::shared_ptr<Foo> p = nullptr;` or `auto q = p;` even though those lines don't use `make_shared` to do it.

**Comment by hsutter** [comment]
Editors call: We agree, we will merge any useful extra bits from C.151 into R.22 so as not to lose them, then replace C.151's body with a link to R.22. Thanks!

**Comment by cubbimew** [comment]
If we're doing this, I think we should also merge C.150 into R.23. I'll make two PRs.
