### ISSUE TITLE
Clarification wanted I.2, do modules complicate anything?

### ISSUE THREAD

**Issue by vingeldal** [isocpp/CppCoreGuidelines#1620]
I'm still learning about modules. If I have a global variable within a module but I don't export it, is it still considered global?

**Comment by MikeGitb** [comment]
I'd say the closest equivalent is a variable in the scope of an anonymous namespace, which is a less evil type of global but should still be avoided in most cases.

**Comment by hsutter** [comment]
Editors call: The Guidelines will add rules about modules when we support C++20.
