### ISSUE TITLE
E.27: "goto error" technique refers to `g2` outside its scope, won't compile

### ISSUE THREAD

**Issue by Quuxplusone** [isocpp/CppCoreGuidelines#1622]
Commit 104cd63a377f16f7031513e1384e39c4bba63d1b claimed to fix #1257, but actually just made the problem worse:

```
    std::pair<int, error_indicator> user()
    {
        error_indicator err = 0;

        Gadget g1 = make_gadget(17);
        if (!g1.valid()) {
                err = g1_error;
                goto exit;
        }

        {
        Gadget g2 = make_gadget(17);
        if (!g2.valid()) {
                err = g2_error;
                goto exit;
        }

        if (all_foobar(g1, g2)) {
            err = foobar_error;
            goto exit;
        }
        // ...
        }

    exit:
      if (g1.valid()) cleanup(g1);
      if (g2.valid()) cleanup(g2);
      return {res, err};
    }
```

The sins here are three (at least):
- Using `goto` at all.
- Overusing `// ...` in lieu of compilable code. (Violates the "MVCE" or ["SSCCE"](http://sscce.org/) principle.)
- Using curly braces to introduce a new scope, without a matching indentation level. (Exacerbated by inconsistent indentation in the original code.)

Here's the second and third sins fixed, but the code still doesn't compile because "OOPS!"

```
    std::pair<int, error_indicator> user() {
        int res = -1;  // violates ES.22
        error_indicator err = 0;
        Gadget g1 = make_gadget(17);
        if (!g1.valid()) {
            err = g1_error;
            goto exit;
        }
        if (true) {
            Gadget g2 = make_gadget(17);
            if (!g2.valid()) {
                err = g2_error;
                goto exit;
            }
            res = all_foobar(g1, g2);
        }
    exit:
        g1.cleanup_if_needed();
        g2.cleanup_if_needed();  // OOPS! g2 is not in scope here
        return {res, err};
    }
```

The right way to fix this would probably be to introduce a new `struct RAIIGadget` that did the one-line cleanup in its destructor. Then you could use `RAIIGadget` instead of `Gadget`, and I think that would fix all the issues at once. You could even replace `err = foo; goto exit;` with a straightforward `return {-1, foo};`.

RAII isn't just for codebases that use exceptions!

**Comment by Quuxplusone** [comment]
Oh, and notice that `g1` and `g2` are cleaned up in not-the-usual order. This is more likely to be harmful than helpful.

**Comment by hsutter** [comment]
Editors call: We agree with fixing the example by moving the g2 cleanup into a second label in the g2-enclosing block.

**Comment by cubbimew** [comment]
(also touched the preceding example to clean up g2 before g1)
The guideline does warn "this can be messy"
