### ISSUE TITLE
Are the code examples of C48 bad style in terms implicitly using the namespce std (SF.7)?

### ISSUE THREAD

**Issue by cmorty** [isocpp/CppCoreGuidelines#1624]
Shouldn't either be
```C++
class X {   // BAD
    using namespace std;
    int i;
    string s;
    int j;
public:
    X() :i{666}, s{"qqq"} {}       // j is uninitialized
    explicit X(int ii) :i{ii} {}   // s is "" and j is uninitialized
    // ...
};
```
or
```C++
class X {   // BAD
    int i;
    std::string s;
    int j;
public:
    X() :i{666}, s{"qqq"} {}       // j is uninitialized
    explicit X(int ii) :i{ii} {}   // s is "" and j is uninitialized
    // ...
};
```
?

**Comment by jwakely** [comment]
```
class X {   // BAD
    using namespace std;
```

You can't put a using-directive at class scope.

**Comment by robert-andrzejuk** [comment]
In the *imaginary* example code above, the `X` class definition could have been:  `using std::string`,
-or- even a custom `string` class.

**Comment by cmorty** [comment]
@jwakely: You are right, of course. I'm still on the steep leaning curve. And I've seen so many `using`s, in classes that I kind of assumed I can import namespaces, too.
@robert-andrzejuk: You are right. Though using a custom `string` class would be bad practice, too, right? I just think example code should always show the best practice, even if it is totally irrelevant in the context of the example. :)
