### ISSUE TITLE
Concepts: focus on what the type is or what the type is not?

### ISSUE THREAD

**Issue by the-moisrex** [isocpp/CppCoreGuidelines#1636]
In the time of writing C++20 concepts, should we focus on what the type IS or should we think about what the type IS NOT or both?

Of course sometimes what a type is not, is what a type is; excluding those times, is it a good idea to only focus on what a type is instead of also writing concepts that also restricts the type by specifying what a type is not?

After all, excluding types is the only job of concepts; so should we focus on what the type is not before we focus on what the type is or should we focus on what the type is before what it's not?

ps: what I mean by what the type is, also includes what the type has, and vice-versa.

**Comment by MikeGitb** [comment]
Not sure I understand your question could you provide an example of what those two approaches would look like?

**Comment by jwakely** [comment]
> After all, excluding types is the only job of concepts

I disagree.

**Comment by the-moisrex** [comment]
Isn't "typename" like the most broad type you could write? So using concepts instead of "typename" is almost equal to saying the concept job is to __exclude__ some types from the list of possible types.

Recently I've been dealing with concepts a lot; the problem is I write what the type is, and then in my tests, those things give me false positives as well.

Of course any example I tried to come up with can be interpreted as both "what is" and "what is not";  I guess my question is about the approach one should take to resolve it. For example if we need a type that is not final, then we use `std::is_final`; so should we think of this action as a _what is_ or as a _what is not_? Because it can be both.

Another point is for example sometimes I need to write a concept that:

- if it has a `requires { typename T::something; }`, then check the if the `something` is of the type I want
- if it doesn't have that `something` at all, then it's okay too.

Now, imagine instead of having one `something`, we have 10 of those; so the code to write that becomes very complicated (unless you know some trick I don't). This is an example of where we are  thinking about what the type is not; because we are excluding all the types except those that make sense.

But we also could think of it as what the type is; in that situation, we shouldn't care much about the type of the `something` because it could easily be omitted if it's not of the type we need later in the code.

So maybe my question is, should we restrict the concept as much as possible, or should we just express what the type is and down in the chain, when we need the `something`, we check it then?!

I myself like the idea of restricting as much as possible, but the problem, as I mentioned, is that it sometimes takes a lot more code to write that concept.

**Comment by cubbimew** [comment]
> should we restrict the concept as much as possible, or should we just express what the type is

sounds like something already answered by the rules about concepts, notably T.20, T.21, and T.26

**Comment by hsutter** [comment]
Editors call: Thanks! We agree with @jwakely and @cubbimew that this is already covered though.
