### ISSUE TITLE
ES.84 unnamed return value

### ISSUE THREAD

**Issue by shimondoodkin** [isocpp/CppCoreGuidelines#1639]
in ES.84 nothing said about unnamed return value.

probably need to add return values are ok also as function arguments.

visual c++ makes I believe wrong warning.

Severity	Code	Description	File	Line	Suppression State
Warning	C26444	Don't try to declare a local variable with no name (es.84).	

f(){
 const CloseFrame emptyframe = {}; // here compiler adds NOP asembly command
                return emptyframe;
}

vs

f(){
                // no NOP here 
                return {};   // here warning
}

**Comment by hsutter** [comment]
Editors call: We agree there shouldn't be a warning on `return {};". We will follow up with the vendor, thank you.

**Comment by shimondoodkin** [comment]
thank you
