### ISSUE TITLE
Default constructor missing?

### ISSUE THREAD

**Issue by HFriberg** [isocpp/CppCoreGuidelines#1643]
Having read [C.43: Ensure that a copyable (value type) class has a default constructor](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c43-ensure-that-a-copyable-value-type-class-has-a-default-constructor), I find it strange that the good example of `class Picture` in [NR.5: Don’t use two-phase initialization](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nr5-dont-use-two-phase-initialization) does not have a default constructor. The purpose is of course to strengthen the invariant, making it easy to reason about and use, but if C.43 is respected, this must mean that `class Picture` is designed to not be copyable which I struggle to justify.

My personal rule is that **distinct states of an object should be non-overlapping** to provoke errors in buggy code (worst thing in programming is bugs that hide). So if the normal picture state is `mx > 0` and `my > 0` and `data!=nullptr`, the default constructed empty picture state should satisfy `mx <= 0` and `my <= 0` (`-1` sensible for provoking errors; `0` sensible if a picture can be grown from the empty state) and `data==nullptr`. This rules out all the worst cases of two-phase initialization, leaving only the possibility of constructing into a "special state" which fits nicely with the discussion in C.43.

**Comment by cubbimew** [comment]
I think NR.5 examples don't show the default ctor because it's not directly involved in the use cases shown. In general, examples try to focus on what they intend to demonstrate, and these are already a screenful or more.
That could be acknowledged with a simple `// ...`. Or, indeed, a C.43-compatible default ctor would look good if it's not too much..

**Comment by HFriberg** [comment]
I am perfectly alright with keeping the example minimalistic, but a default ctor that constructs into a "special state" (weakening the class invariance) definitely falls under the rule of NR.5 and is worth elaborating. 

I will not try to come up with a suggestion (I am no expert), but I would like to see the default ctor being described as the exception for which the cost of a "special state" (cumbersome and error-prone!) may sometimes be worth the effort, possibly followed by advice (or just an example) of how to design such a "special state".

**Comment by hsutter** [comment]
Editors' call: We'll add `// ...` to make it clearer that there's more in the class.

**Comment by cubbimew** [comment]
(It would still be good to see a PR with a good default ctor here, but until then, // ...)
