### ISSUE TITLE
Why does C.21 advocate for the "Rule of 6" instead of the "Rule of 5"?

### ISSUE THREAD

**Issue by russellmcc** [isocpp/CppCoreGuidelines#1647]
I think more motivation is needed on why C.21 advocates for a "rule of 6" rather than a "rule of 5".  I don't understand why, if I define a default constructor, I also should define the other 5 special member functions.  To be concrete, I don't understand why I should write:

    class My_class {
    public:
      My_class() = default;
      explicit My_class(const Other_thing& starting_thing) : thing{starting_thing} {}
      ~My_class() = default;
      My_class(const My_class&) = default;
      My_class(My_class&&) = default;
      My_class& operator=(const My_class&) = default;
      My_class& operator=(My_class&&) = default;
    private:
      Other_thing thing;
    };

rather than

    class My_class {
    public:
      My_class() = default;
      explicit My_class(const Other_thing& starting_thing) : thing{starting_thing} {}
    private:
      Other_thing thing;
    };

Which feels less verbose, and just as safe and clear to me, subjectively.

The discussion in C.21 gives good justification for the rule of five, by which I mean "if you define at least one of the destructor, copy constructor, move constructor, copy assignment operator, or move assignment operator, define all five".

However, I don't understand why this should be extended to the "rule of six" that the guideline states.  The only justification I can see is, "The semantics of the special functions are closely related, so if one needs to be declared, the odds are that others need consideration too".  This sentence directly contradicts my experience.  Often, I don't need to consider the other five when I need to declare the default constructor, because I might have only needed to declare it because I defined a non-default constructor.

**Comment by cubbimew** [comment]
your example is essentially the same as the one in the currently-open #1571 (where I suspect more discussion will take place)

**Comment by russellmcc** [comment]
Ah yes, I did see that issue before opening this one.  The reason I opened a new issue is that #1571 is actually advocating dropping the rule of five - i.e.,  "I think it is better to learn when the compiler supplies, deletes or inhibits special member functions" - to me, this implies that this sort of thing would be okay:

```
class My_class {
public:
  ~My_class();
  My_class(const My_class&);
  My_class& operator=(const My_class&);
private:
  Special_thing thing;
};
```

My proposal is not to drop the rule of five but rather to not count the default constructor as part of that set.  So, the above code would still be against the guidelines, since it should have defined the move constructor and assignment.  So, I don't see the two as the same.

**Comment by hsutter** [comment]
Editors' call: We agree with cleaning this up to remove the default constructor, and will reword "special member functions" which is a standardese term that happens to include the default constructor. It's only the copy/move/destructor functions that are related. Note that this change addresses this issue #1647, but not the central point of related issue #1571.
