### ISSUE TITLE
Giving new names to function parameters using references

### ISSUE THREAD

**Issue by WysokiStudent** [isocpp/CppCoreGuidelines#1652]
When implementing a mathematical formula it often happens that variable names are single letters and I remember watching a video from cppcon where Kate Gregory talked about how temperature should be called "T" if everyone uses that name. 

The problem is that the meaning those of letters isn't obvious to someone without knowledge of the basis of the implementation. Functions with descriptive parameter names can be used to convey meaning, expectations and abstract the implementation but if the function parameter names are descriptive they don't follow the convention of the documented mathematical formulation in question.

A solution to this discrepancy could be to use references inside a function to give new names to parameters that follow the mathematical convention but is this considered good style or is it exotic?

Example:

    Matrix foo(const Matrix& elaborate_name1, const Matrix& elaborate_name2) {
        const Matrix& A = elaborate_name1;
        const Matrix& B = elaborate_name2;
        
        return A*B;
    }

I sought guidance on stackoverflow prior to asking this question here: [link](https://stackoverflow.com/questions/62919499/can-usage-of-c-references-be-considered-giving-a-function-parameter-a-new-name)

**Comment by MikeGitb** [comment]
The main reason I have done such renaming in the past, was in order to shorten the identifiers and make the whole math expression more readable/reckognizable.

That being said: Is this really something that needs a guideline?

**Comment by WysokiStudent** [comment]
I can see it being done in the wild in [this manner](https://github.com/PX4/ecl/blob/46a5e6e4285df7f16ebc7b81d43149324d86133d/EKF/mag_fusion.cpp#L47) but other approaches using a single letter as a parameter name and documenting its meaning [exist](https://github.com/Kitware/VeloView/blob/e70d2580cdeb5aa3154b480a4ac761b0b2ca1e79/VelodyneHDL/Common/vtkEigenTools.h#L40). Having some baseline would be great for consistency.

This reminds me a little of the .h vs .hpp split except that this one might have performance consequences which I, as a newbie, am unable to predict.

**Comment by hsutter** [comment]
Editors call: The Guidelines don't ban this, but it's a personal preferences not something that would be a Guideline.
