### ISSUE TITLE
p.1 - how to implement the 'Speed' type

### ISSUE THREAD

**Issue by pm100** [isocpp/CppCoreGuidelines#1653]
I really like this idea and felt that the intent of the guideline is that this be a 'strong' alias. Ie having defined 

change_speed(Speed s)

I cannot do

double s = 42.0;
change_speed(s);

But how to implement that? using Speed = double; does not achieve it.

**Comment by MikeGitb** [comment]
Essentially two possibilities: 

1) Wrap it in a struct and - if necessary - define whatever math operations you think would make sense i.e.

        struct Speed {
            double value;
            friend constexpr Speed operator+(Speed l, Speed r) noexcept{ return {l.value+r.value};}
            //....
         };

2) Google for a full-fledged units library

**Comment by pm100** [comment]
> Essentially two possibilities:
> 
> 1. Wrap it in a struct and - if necessary - define whatever math operations you think would make sense i.e.
>    ```
>     struct Speed {
>         double value;
>         friend constexpr Speed operator+(Speed l, Speed r) noexcept{ return {l.value+r.value};}
>         //....
>      };
>    ```
> 2. Google for a full-fledged units library

I dont think I need the units bit. But I do need all the possible overloads, I need it to behave just like the primitive type, except sometimes you have to cast in or out. Nothing in GSL?

**Comment by MikeGitb** [comment]
> I need it to behave just like the primitive type, 

Are you sure? What would it mean for you, if you multiplied a `Speed` with a `Speed`? And if you divide `6 kph` by `2 kph`, is it really a good idea if you get `3 kph` as a result? Along the same lines, you probably want to allow to multiply a `Speed` with a `double`, but not to add a double to a `Speed`.

> Nothing in GSL?

Not that I'm aware of.

**Comment by MikeGitb** [comment]
Btw.: If you really want to have the same operations as a normal double and if math operations should always return the same type, it is relatively easy to write a helper like this once:

     template<class T, class TagType>
     struct StrongAlias {
          T value;
           friend constexpr StrongAlias operator+(StrongAlias l, StrongAlias r) noexcept{ return {l.value+r.value};}
          //....
     };

And then use it like this:

    using Speed = StrongAlias<double, struct SpeedTag>

**Comment by cubbimew** [comment]
the StackOverflow answers to this question are also relevant: https://stackoverflow.com/questions/62941169/strong-aliases-for-primitive-types

**Comment by hsutter** [comment]
Editors call: The way you would write such a strong type for a given use case and domain depends on the situation, e.g., which conversions to other types there should be, which set of operations are considered valid (e.g., Speed * Speed), and opaque types doesn't solve the units problem. Since there are conflicting demands they have to be written as custom types. We don't think the Guidelines are the right place to give just one example.
