### ISSUE TITLE
ES.103 First Example, bad problematic

### ISSUE THREAD

**Issue by dboyce-gh** [isocpp/CppCoreGuidelines#1656]
August 03, 2020
The content of the first **Example, bad** code on ES.103 appears to suffer from copy-and-paste from ES.104.

 This part:
```
int a[10];
a[10] = 7;   // bad
```
is OK (although it would help if the comment said "// bad, array bounds overflow"),

but the following part:
```
int n = 0;
while (n++ < 10)
    a[n - 1] = 9; // bad (twice)
```

does not overflow the array bounds at all; the post increment of n means that values of n _within_ the loop run from 1 to 10, meaning that the array indices used are 0 to 9, which are valid. It's poor style, but not an example of array bounds overflow.

I suspect this fragment has been copied from ES.104 and modified.

**Comment by BjarneStroustrup** [comment]
Yes, for (int n = 0; n<=10; ++n) a[n] = 9; would be better and more realistic

**Comment by hsutter** [comment]
Editors call: PR merged, thanks!
