### ISSUE TITLE
"If statement" Guideline improvements for Integer checks

### ISSUE THREAD

**Issue by incetents** [isocpp/CppCoreGuidelines#1657]
After some experimentation, I believe I have created a perfect hierarchical system for comparing integer values in Cpp for the biggest benefit of readability and performance gain.
I believe I have wasted enough time with the explanation, here is the breakdown:

Normal:
`if(myInt > 0){...}`

Good:
`if(myInt >= 1){...}`

Great:
`if(!(myInt <= 0)){...}`

Amazing:
`if(max(0,myInt) != false){...}`

Godly: (requires OpenGL 4.2)
`if(GLCheckIfNegative( glGenNumberBuffer(&nullptr, 1) )){...}`

Alternative for DirectX and Vulkan
`abort();`

And currently the best solution:
`goto CorrectSolution(myInt);`

Feel free to use this knowledge in any way shape of form for future development of the cpp guidelines.

Godspeed

![CppGuidelineSpec](https://user-images.githubusercontent.com/22376381/89569102-3afdf200-d7f2-11ea-95a5-3217ace54203.png)

**Comment by incetents** [comment]
That's some good advice!
Thanks!!!

**Comment by Satlazer** [comment]
Huh, that is better!

**Comment by EmilianC** [comment]
This aligns closely with my own professional experience.

**Comment by GOOD-Stuff** [comment]
Maybe I'm still green or doesn't get some kind of ironic but why is  `if(!(myInt <= 0))` should be great variant?

**Comment by jwakely** [comment]
> doesn't get some kind of ironic

:point_up: 

Thanks for the chuckles, but let's close this.
