### ISSUE TITLE
References to [C++CS] appears to correspond to [SuttAlex05] 

### ISSUE THREAD

**Issue by dboyce-gh** [isocpp/CppCoreGuidelines#1660]
Appendix C contains several linked references to [C++CS] Items.  The Bibliography contains the entry

- \[C++CS\]: ???

which is somewhat uninformative.  My guess is that this is intended to refer to the same book as [SuttAlex05] in RF.Books.

If someone can confirm this is the case, I am happy to prepare a PR to fix it.

My first instinct would be to replace the textual references to \[C++CS\] to \[SuttAlex05\], and remove the Bibliography entry mentioned above.    

Alternatively, the references could be left alone and the bibliography entry altered to e.g. 

- \[C++CS\]: _See_ \[SuttAlex05\]

**Comment by cubbimew** [comment]
Yes, the three references to "C++CS" currently are:
* "[C++CS] Item 50" under [Discussion: Make base class destructors public and virtual, or protected and non-virtual](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#discussion-make-base-class-destructors-public-and-virtual-or-protected-and-non-virtual) corresponding to SuttAlex05 chapter "50. Make base class destructors public and virtual, or protected and nonvirtual"
*  "[C++CS] Item 51" under [Discussion: Destructors, deallocation, and swap must never fail](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#discussion-destructors-deallocation-and-swap-must-never-fail) corresponding to SuttAlex05 chapter "51. Destructors, deallocation, and swap never fail"
* "[C++CS] Item 52" under [Define Copy, move, and destroy consistently](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#define-copy-move-and-destroy-consistently) corresponding to SuttAlex05 "52. Copy and destroy consistently"

I think it's clearly the same reference and the simplest fix is to make those three "[SuttAlex05]" and drop "C++CS" frmo bibliography

**Comment by cubbimew** [comment]
Thanks for the PR
