### ISSUE TITLE
Proposal, gsl::range

### ISSUE THREAD

**Issue by hdf89shfdfs** [isocpp/CppCoreGuidelines#1668]
Example:

I'm writing a window class.
My window class takes inputs for width/height.

```
uint64_t width  = 0;
uint64_t height = 0;

Window wnd(width, height)
```

So what's the problem?

The problem is a width/height of zero makes no sense.

It's very similar to gsl::not_null and gsl::span in that regard.

I want to make sure my input are valid, and if possible at compile time.

```
# The underlying type, min, max
gsl::range<uint64_t, 200, 10'000> width  = 200;
# FAILS TO COMPILE
gsl::range<uint64_t, 200, 10'000> height = 0;

# Now my inputs are guaranteed to be valid.
Window wnd(width, height)
```

To make it nicer I can just use "using".

```
using WindowDimension = gsl::range<uint64_t, 200, 10'000>;

WindowDimension width  = 200;

WindowDimension height = 0;

# Now my inputs are guaranteed to be valid.
Window wnd(width, height)
```

Now just adding 1 more quality of life, would be the ability to modify the static_assert message.

```
using WindowDimension = gsl::range<uint64_t, 200, 10'000, "Window dimensions are invalid">;

WindowDimension width  = 200;

WindowDimension height = 0; // Now the static_assert will be even more clear.

# Now my inputs are guaranteed to be valid.
Window wnd(width, height)
```

I've seen this exact issue so many times in drivers I work on. And would love for something like this to exist.

It isn't a very difficult class to write. But a great quality of life.

**Comment by hdf89shfdfs** [comment]
Ideally something like this would work for floats as well

Handling range value
[0.0f - 1.0f)

**Comment by shaneasd** [comment]
https://www.boost.org/doc/libs/develop/libs/safe_numerics/doc/html/index.html seems related

**Comment by hsutter** [comment]
Editors call: This may be a useful feature, but the GSL is specifically a minimal set of not-yet-standard tools that are required to support the Guidelines, and there is no guideline regarding range/interval.

**Comment by jwakely** [comment]
N.b. the name `range` conflicts with a concept in the standard with a different meaning.
