### ISSUE TITLE
Recommendations for ES.105: Don't divide by zero

### ISSUE THREAD

**Issue by DEVoytas** [isocpp/CppCoreGuidelines#1678]
Why in the **good** examples for ES.105, e.g.:
```c++
double divide(int a, int b)
{
    // good, address via precondition (and replace with contracts once C++ gets them)
    Expects(b != 0);
    return a / b;
}
```
the function return type is `double` despite of performing the integer division?

Although I understand that the word "good" here refers to avoiding division by zero, and not to the proper usage of float/integer types when performing division, I think some people may [get confused](https://stackoverflow.com/questions/7571326/why-does-dividing-two-int-not-yield-the-right-value-when-assigned-to-double) if they copy-paste a "good example" and get unexpected results (truncated decimal part of the result).

Would it make sense to change the examples in the recommendation to either:
* return the `int` type, as this is the integer division, e.g.:
```c++
int divide(int a, int b)
{
    // good, address via precondition (and replace with contracts once C++ gets them)
    Expects(b != 0);
    return a / b;
}
```
* or force conversion to `double`, to assure the expected result e.g.:
```c++
double divide(int a, int b)
{
    // good, address via precondition (and replace with contracts once C++ gets them)
    Expects(b != 0);
    return double(a) / b;
}
```
?

With regard the second example, please see my other question about proper way of dividing the integers: #1677

**Comment by gdr-at-ms** [comment]
It is just a typo -- the return type should read `int`.

**Comment by cubbimew** [comment]
not quite a typo; the third example in ES.105 is
```
    double divide(int a, int b)
    {
        // good, address via check
        return b ? a / b : quiet_NaN<double>();
    }
```

**Comment by hsutter** [comment]
Editors call: Fixed, thanks!
