### ISSUE TITLE
[FEATURE]: Move to GitHub Actions

### ISSUE THREAD

**Issue by Panquesito7** [isocpp/CppCoreGuidelines#1686]
GitHub Actions is faster, easier and better to use, IMHO.
I think it would be a good idea to replace Travis CI with GitHub Actions.

What do you think about this? 🙂

**Comment by cubbimew** [comment]
I can give it a try, since it looks like we lost the travis checkmarks again recently.

**Comment by cugone** [comment]
Personally, TravisCI is old and outdated compared to any other popular CI solution like CircleCI or AppVeyor.
