### ISSUE TITLE
constexpr "guaranteed compile-time evaluation" - i don't think that's strictly true

### ISSUE THREAD

**Issue by divinity76** [isocpp/CppCoreGuidelines#1692]
quote:
```
Con.5: Use constexpr for values that can be computed at compile time
Reason
Better performance, better compile-time checking, guaranteed compile-time evaluation, no possibility of race conditions.
```
i haven't read the actual specs in enough detail to say for sure, but i'm pretty sure constexpr is supposed to guarantee that it *CAN* be evaled at compile-time, it does not guarantee that the compiler actually does so

(also pretty sure i've seen g++ compile a constexpr function which absolutely could not be computed at compile time, without complaining, but that may just have been a g++ bug, and i've forgotten the exact details)

**Comment by jwakely** [comment]
A call constexpr function is not guaranteed to be evaluated at compile time (e.g. because you can call it with data that is only known at runtime) but a constexpr variable is guaranteed to be initialized at compile time.

    constexpr int x = func(0); // eval'd at compile time
    int y = func(argc); // eval'd at run time

**Comment by divinity76** [comment]
thanks for clearing that up!

 well it's close enough for me to not care then, closing.

> Probably a function template, in which case the compiler would be correct to compile it, and ignore the constexpr.

 hope that's something caught by `-Wall`

**Comment by jwakely** [comment]
> hope that's something caught by `-Wall`

No, because it's not a problem. A function template declared `constexpr` will be constexpr for some template arguments and not others, and that's fine.

e.g. `std::pair<int, int>` can be used in a constant expression, but `std::pair<std::list<int>, std::fstream>` can't be used in a constant expression. And that's fine, warning about it would not be useful.

**Comment by MikeGitb** [comment]
To add to that: Even a normal (non-template) function can be marked constexpr even though they contain code that can't be evaluated in a constexpr context (e.g. throw or a non-constexpr function) as long as that particular code path isn't evaluated during constexpr evaluation.

https://godbolt.org/z/dccav7

This is why I find the argument against auto constexpr that "constexpr is a promise about the interface" absurd, but that is a different can of worms.
