### ISSUE TITLE
prefer `while (true)` vs `for (;;)`

### ISSUE THREAD

**Issue by tiagomacarios** [isocpp/CppCoreGuidelines#1693]
The Core Guidelines use for (;;) to refer to infinite loops (ex [ES.32: Use ALL_CAPS for all macro name](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es32-use-all_caps-for-all-macro-names)). Wouldn't it be preferred to use while (true). I would think that the later is more friendly to beginners and somewhat more explicit.

**Comment by jwakely** [comment]
Personally I use `while (true)` in code I write, but ...

> The form `for (;;)` for an infinite loop is traditional, appearing in the standard reference _The C Programming Language_, and is often punningly pronounced "forever".

Source: https://en.wikipedia.org/wiki/Infinite_loop#Examples_of_intentional_infinite_loops

**Comment by cugone** [comment]
Depending on the warning level, compilers will emit a warning `expression is always true` when `while(true)` is used. If "treat warnings as errors" is turned on (as it should be!) code will fail to compile. Using `for(;;)` will work in all cases.

**Comment by jwakely** [comment]
Which compilers? I understand warning about `while (x)` where `x` is always true, but warning about the tokens `while(true)` is stupid. It's obvious the programmer meant the condition to be true.

**Comment by cugone** [comment]
It's a good thing you challenged my assumptions. I hadn't actually *tested* the "feature" (I only have access to Visual Studio) in a while. There have been several dozen updates and multiple full-version updates since the last time I saw the behavior.

A little sample program, even on Warning Level 4 and the dreaded All Warnings settings, compiling in both both Debug and Release, does not reproduce the problem.

```cpp
#include <chrono>
#include <random>
#include <thread>
#include <iostream>

int DoStuff();

std::mt19937 g;

int main() {
    std::random_device rd;
    g.seed(rd());
    std::uniform_int_distribution d{-1, -360};
    unsigned int i = d(g);
    while(i < 0u) { //Wall only, Caught as "Warning C4296: '<' Expression is always false."
        --i;
        std::cout << "Accidental Infinite Loop" << i  << '\n';
    }
    while(true) { //Never caught, regardless of settings
        ++i;
        std::cout << "while(true) Infinite Loop " << i << '\n';
    }
    for(;;) { //Never caught, regardless of settings
        ++i;
        std::cout << "for(;;) Infinite Loop " << i << '\n';
    }
    std::cout << DoStuff() << std::endl;
}

int DoStuff() {
    std::this_thread::sleep_for(std::chrono::milliseconds{1000});
    std::uniform_int_distribution d{-360, 360};
    return d(g);
}


```

**Comment by hsutter** [comment]
Editors call: We don't think there's a strong consensus to prefer either form. Currently the Guidelines use `while(true)` in two places and `for(;;)` in five places. Seems fine.
