### ISSUE TITLE
Remove F.2 and F.3

### ISSUE THREAD

**Issue by ghbplayer** [isocpp/CppCoreGuidelines#1696]
> F.2: A function should perform a single logical operation
> F.3: Keep functions short and simple

These are bad rules and should be removed. The idea behind these rule comes from snake oil that was being peddled circa 2005 (Martin Fowler?). The premise behind the snake oil was that simpler functions result in easier to understand code. That's utter nonsense, the complexity of your software doesn't go away just because your functions are too simple. You'll find that the relationships between functions becomes complex instead, and that's not something you can see on one page.

A skilled programmer will balance the complexity of their functions and the complexity of relationships between functions. The goal is to make software you can understand and reason about. A thousand two-line functions are not easier to understand than one two-thousand line function, there's a better balance to be found.

For F.2, the example code is absurd. Moving one line into its own function does not improve the code, it just makes more code, and separates the code. If you commonly need to read and print, it's good practice to have a read_and_print function. That helps you to understand and reason about the code.

**Comment by hsutter** [comment]
Editors call: We agree programmers should balance concerns, and that it's totally fine to have the `read_and_print` function (as we showed) in addition to the reusable component functions. This advice is a lot older than 2005, and we feel it's still appropriate.
