### ISSUE TITLE
Suggested: C153. Use final only sparingly

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#170]
# C153. Use final classes only sparingly

Marking a class final can (often negatively) affect a class hierarchy its design, by disallowing further derivation of that class. 

## Examples

```
class Base {};
class Derived final : public Base {}; //No
class Derived : public Base {}; //OK

```

## Exceptions

Adding final increases performance. If this performance is essential, you may choose to keep it. But see `PER.1: Don't optimize without reason`

## Enforcement

None

## See also

See reference

## Notes
 
None

## Discussion

None

## References

Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 20.7. Advice. page 611: '[5] Use final only sparingly'

**Comment by hsutter** [comment]
Correct, thanks. Bjarne will take a pass at writing this item.

**Comment by hsutter** [comment]
Note that there is related guidance in Bjarne's FAQ.

**Comment by xtofl** [comment]
To me, this feels related to https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-immutable.  I'm not sure about the rest of the world, but my (implementation) classes are only rarely meant to subclass.

Therefor I wonder if one shouldn't advise to use `final` classes, unless you _mean_ to have them subclassed.

**Comment by richelbilderbeek** [comment]
@xtofl : I'd personally also prefer your rule, but I think Bjarne has thought about this more than me, so I would not mind to follow his recommendations.

It feels similar to using `virtual` to me: I do not mark member functions virtual if I do not intend their class to inherit from. For me, labeling those class final would just be being consistent.

**Comment by galik** [comment]
Just to add a thought.

Isn't it easier to change an interface to move from `final` to *non final* than to go the other way? By avoiding the `final` keyword you are *committing* your class to be forever extensible by *inheritance* but by *using* the `final` keyword you still allow for fewer restrictions in the future.

I tend to feel that extensibility through *inheritance* (in particular) should be a firm design decision. So I was surprised to discover that avoiding `final` is recommended here.

Having said that I have never used the `final` keyword  so I am not arguing from a position of practical strength, just airing a gut feeling. That and when you mention *speed* to a *C++ programmer*....

**Comment by avakar** [comment]
Note that Bjarne's FAQ talks about `final` specifier for functions, not for classes (I don't know what's in CPL). I am with @xtofl and @galik. Also, I suggest that classes without virtual functions and no protected members should always be `final`; that way, nobody will attempt to inherit instead of composing (and you should prefer composition to inheritance).

**Comment by BjarneStroustrup** [comment]
added as C.139
