### ISSUE TITLE
NL.3 Many code examples comments do not follow NL.3 on  punctuation, and capitalization.

### ISSUE THREAD

**Issue by peno2** [isocpp/CppCoreGuidelines#1702]
If you are to follow NL.3 
"Avoid SMS lingo and watch your grammar, punctuation, and capitalization. " then I would expect a comment to look as follows:
// Bug waiting to happen.
Not
// bug waiting to happen

The latter seems to be quite a common style of how to write comments.
It would be easier to convince coders during a code review, if code examples in the guidelines follow the guidelines.

Since I am not a native English speaker, I don't know exactly how and when to expect capital letters and periods.
Are there cases where a comment is viewed as a heading and thus should not end with a period?
Also, how about incomplete sentences? How should they be written?
Is there a lower limit on where correct punctuation, and capitalization is not needed? 1, 2 or 3 words of text?
Anyway, I wish that code comments in the guidelines could be used as good examples of NL.3.

**Comment by shaneasd** [comment]
I would use a capital letter at the start of a sentence and a full stop at the end of a sentence. I don't consider "bug waiting to happen" to be a sentence. It's a fragment of the sentence "This is a bug waiting to happen." The author of that comment presumably felt that the salient content of that sentence was "bug waiting to happen" and took the advice of [NL.3](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl3-keep-comments-crisp)
) to avoid verbosity by removing the implied sentence structure. Whether this violates the note in NL.3 I guess depends on whether the comment is still intelligible. I think the point of the note is to ensure that your comment is readable and understandable by a wide range of people (as opposed to just the author) and I believe that this example is.

**Comment by hsutter** [comment]
Editors call: NL.3 is about making comments meaningful, not prescribing a style. For sentence fragments, it's common not to write in full sentence case and punctuation. Grammar is more important for longer comments.

**Comment by peno2** [comment]
Thanks for the clarifications.
