### ISSUE TITLE
[[gsl::suppress]] should allow a justification/reason field for suppressions

### ISSUE THREAD

**Issue by sunnychatterjee** [isocpp/CppCoreGuidelines#1703]
C++ Core Guidelines should support a reason/justification field when adding a suppression attribute. This will help Engineering Systems teams audit suppressions from C++ Core Check, a checker that enforces C++ Core Guideline rules. Here are some suggestions:

-	Preferred syntax: [[gsl::suppress(type.1, justification: “It is Friday afternoon, and I need to catch the bus”)]].
-	Alternative syntax: [[gsl::suppress(type.1, reason: “It is Friday afternoon, and I need to catch the bus”)]].
-	Desired behavior for Engineering Systems: Be able to audit suppressions without justification string.

**Comment by sunnychatterjee** [comment]
One example to consider from precedent is static_assert.

**Comment by MikeGitb** [comment]
Why not just use a comment? The difference to stati_assert is that static_assert produces an error message during compilation,  while a suppression is explicitly about avoiding the generation of a diagnostic.

**Comment by hsutter** [comment]
Editors call: Agreed, thanks! We'll go with "justification" because even though some of us think it's rather a mouthful, apparently some static analysis tools use it already so we're aligning with existing practice.
