### ISSUE TITLE
A common macro code patttern

### ISSUE THREAD

**Issue by hdf89shfdfs** [isocpp/CppCoreGuidelines#1704]
With the advent of std::source_location in C++20 macros are more and more a thing of the past.
https://en.cppreference.com/w/cpp/utility/source_location

However there is still a very prominent use case we use macros for in our code base (at my company at least).

```cpp
#pragma once

// Disallow the use of the copy constructor and copy assignment operator for a class:
// Note: prefer to place this in public for better compiler error messages (Scott Meyers Effective C++)
#define UTIL_DELETE_COPY_AND_ASSIGN(udt)       \
    udt(const udt&)             = delete; \
    udt& operator =(const udt&) = delete;

// Disallow the use of the move constructor and move assignment operator for a class:
// Note: prefer to place this in public for better compiler error messages (Scott Meyers Effective C++)
#define UTIL_DELETE_MOVE_AND_ASSIGN(udt)                  \
    udt(udt &&) noexcept             = delete; \
    udt& operator =(udt &&) noexcept = delete;

// Disallow the use of the copy/move constructor and copy/move assignment operator for a class:
// Note: prefer to place this in public for better compiler error messages (Scott Meyers Effective C++)
#define UTIL_DELETE_ALL_COPY_AND_MOVE_METHODS(udt)  \
    UTIL_DELETE_COPY_AND_ASSIGN(udt)                \
    UTIL_DELETE_MOVE_AND_ASSIGN(udt)

```

How can this be done effectively without macros?

**Comment by jwakely** [comment]
That's a terrible use of macros.

**Comment by jwakely** [comment]
Deleting the move operations without deleting the copy operations has almost no valid use cases, so the second macro doesn't need to exist. Deleting the copy operations will suppress the move operations, so the third macro is only useful to prevent people from "accidentally" adding move semantics to a non-copyable class, but that doesn't seem like something you need to use macros to defend against.

Just learn the rules and spell out the defaulted or deleted members you want.

Also there no point adding `noexcept` to deleted members.

**Comment by MikeGitb** [comment]
Personally I just add the special member functions to the macros/templates /whatever the feature is called in my IDE/Editor and then =default/=delete them as needed.

**Comment by shaneasd** [comment]
There's also boost::noncopyable if you find typing all those lines too onerous. I don't recall if it's a 1:1 correspondence. It's also pretty simple to recreate your own noncopyable if you can't include boost for whatever reason.

**Comment by hdf89shfdfs** [comment]
I don't really love the boost approach either. Not to sound too spoiled. Ideally I would just apply an attribute to my class.

[[gsl::noncopyable]]
class foobar
{
...
};

**Comment by hdf89shfdfs** [comment]
@jwakely  I agree that the macro approach isn't very clean, and as you mentioned has issues. However, I've seen this code pattern at both AMD and Nintendo. People want a succinct way to delete methods.

I'm not sure the best way is.

**Comment by hdf89shfdfs** [comment]
I've changed the title to reflect the fact that this is a common code pattern.

Both the macro and the boost inheritance code pattern show that people want a way to quickly communicate their class isn't copyable.

**Comment by jwakely** [comment]
```cpp
// This type is not copyable or movable.
foo(foo&&) = delete;
```

Why is this not quick and succinct? Every C++ dev should be able to understand this (the comment is clear even if they don't know all the rules). I find this a lot more obvious than some project-specific `UTIL_DELETE_ALL_COPY_AND_MOVE_METHODS` macro that might have a misleading name.

Maybe the projects you see doing this are not yet living in the modern age and have legacy macros that predate C++11.

**Comment by YMba9g8j9CJp0wLoQf5y** [comment]
@jwakely but what about the placement of the delete. As mentioned in the comments for those macros.

```
// Disallow the use of the move constructor and move assignment operator for a class:
// Note: prefer to place this in public for better compiler error messages (Scott Meyers Effective C++)
```

Not everyone is using a compiler that has "-Weffc++" and can tell them that they should put the delete in the public section of the class.

**Comment by MikeGitb** [comment]
I don't see a relevant differnce between putting them in the public/private section of a class: https://godbolt.org/z/Gdfxcs

That aside, I think stuff like that really belongs into the coding guidelines and ideally into linter rules instead of into comments that people may or may not read.

**Comment by YMba9g8j9CJp0wLoQf5y** [comment]
Hmm I guess this isn't an issue with newer compilers.

If you mess around with the compiler versions you get different error messages.

Thanks for pointing this out!

**Comment by MikeGitb** [comment]
Darn - forgot to check. Sorry for the noise.

**Comment by shaneasd** [comment]
So if I understand correctly the goal is:
a way that is briefer and/or clearer than deleting the relevant functions or inheriting from boost::noncopyable or equivalent

I'm not sure there's really a way to do that without changing the compiler. gsl adding the attribute you mentioned wouldn't actually change the behavior of the compiler. deleting the method will give you a compilation error if you try to call it. adding an attribute would, best case, give you a warning from your static analysis tool. The actual diagnostic from either of the two approaches above is sufficiently superior in my opinion to disregard the attribute option. Of course you could add something to the language so that compilers had to support it but not by raising it in the core guidelines github and not by adding adding it to gsl.

If you're willing to accept the black box solution of
```
[[gsl::noncopyable]]
class foobar
```
then it's odd to me that you wouldn't consider 
```
class foobar : boost::noncopyable
```

it communicates the same information in slightly fewer characters at the same location in the code. Granted using inheritance for this purpose is a bit weird so it's a pattern you'd need to be familiar with but I would say that's equally true of a macro or non-standard attribute.

**Comment by jwakely** [comment]
Right, an attribute is completely inappropriate for semantic changes like this.

**Comment by hdf89shfdfs** [comment]
Thank you all very much for contributing to the conversation.

I've very much changed my mind, this isn't a good use case of macros and is really a relic of legacy macros that predate C++11.
In fact talking to my colleagues it was exactly that. Those macros did predate C++11 and they were just slightly updated.

In which case you should just updated your code base because writing the =delete code isn't that much effort. As @jwakely mentioned.

And as @shaneasd also put it any other convention is just that another non-standard convention.

Thank you very much for your time.
