### ISSUE TITLE
RF.rules: Coding rules - Mozilla, Google

### ISSUE THREAD

**Issue by amitdo** [isocpp/CppCoreGuidelines#1705]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#rfrules-coding-rules

>Mozilla Portability Guide. As the name indicates, this aims for portability across many (old) compilers. As such, it is restrictive.

There's no guide there. It only has a broken link.

Mozilla now uses C++17 in Firefox.
https://firefox-source-docs.mozilla.org/code-quality/coding-style/using_cxx_in_firefox_code.html
  
>Google C++ Style Guide. Geared toward **C++03** and (also) older code bases. Google experts are now actively collaborating here on helping to improve these Guidelines, and hopefully to merge efforts so these can be a modern common set they could also recommend.

They also moved to C++17.
https://google.github.io/styleguide/cppguide.html#C++_Version

**Comment by hsutter** [comment]
Editors call: Fixed, thanks!
