### ISSUE TITLE
F.17 - Clarification for functions that "might" modify the input arguments

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#1722]
Hi,

I'd like to ask about "F.17  For “in-out” parameters, pass by reference to non-const". Is the rule violated on a function that **might** (i.e. not always) modify the input argument? Example:

```
void Foo::maybeUpdate(Record& record)
{
    if (shouldUpdate())
    { 
           // Update record
    }
    // Do nothing, record is not modified
}
```
What would be a better implementation? Assume this function is called in many different places, so we don't want to duplicate the `shouldUpdate` logic at the caller site.

**Comment by beinhaerter** [comment]
To me this looks good and is an implementation according to F.17.

**Comment by carlosgalvezp** [comment]
Awesome, thanks for the clarification!
