### ISSUE TITLE
CP.2 Recommended "Good Books" on Concurrency

### ISSUE THREAD

**Issue by ghost** [isocpp/CppCoreGuidelines#1725]
A note in CP.2 delegates information on synchronisation and data races to a "good book" on concurrency. Should the document provide recommendations on such literature to reduce ambiguity?

**Comment by cubbimew** [comment]
[CP.102 Carefully study the literature](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-literature) has a list of books (although I'd say it's missing Herlihy-Shavit). Perhaps CP.2 could just link down to that rule.
