### ISSUE TITLE
Inconsistency between synopsis of rule F.5 and its enforcement

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1730]
Rule F.5 is about "If a function is very small and time-critical, declare it inline". The enforcement of this rule is "Flag inline functions that are more than three statements and could have been declared out of line (such as class member functions).". 

So the synopsis is telling me to use inline functions in certain situations, whereas the enforcement is about forbidding inline functions. I think the synopsis could be improved by adding the word "only" in the beginning. i.e. "Only if a function is very small and time-critical, declare it inline". This synopsis is consistent with the enforcement of the rule.

**Comment by hsutter** [comment]
Editors call: We looked at this and think the text is as clear as we can make it. If we added "only" then it wouldn't technically direct people to do it.

**Comment by hsutter** [comment]
From me: "If and only if" would do it, but to me personally it feels like a mouthful.
