### ISSUE TITLE
I.25 confusing regarding discourage vs better

### ISSUE THREAD

**Issue by AlexanderLanin** [isocpp/CppCoreGuidelines#1734]
It says "...to discourage users from writing such classes:" and then goes on with an example which states "better". So is it better or discouraged?

Also the examples are about "interface class loaded with data" and "pure interface". While the text talks about "Abstract classes". It's not clear which of the two is the abstract class. (You don't need to answer me here, thanks. The text should be improved IMHO).

**Comment by hsutter** [comment]
Editors call: The example tries to show a way that is not good followed by a way of improving it. We'll look at improving the text. Thanks!
