### ISSUE TITLE
Add a separate rule about returning const values.

### ISSUE THREAD

**Issue by siebenschlaefer** [isocpp/CppCoreGuidelines#1736]
As a community we all agree that one should not return a `const` value because it disables move semantics.

Please consider adding that as a separate rule. Currently it is  hidden as a *note* in [F.20](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-out) "For “out” output values, prefer return values to output parameters"  
I do a lot of mentoring and it would be nice to be able to reference a dedicated guideline.

**Comment by hsutter** [comment]
Editors call: We don't think it's important enough to discourage const return values to have a separate rule. The F.20 note seems enough, and in the right place about return values.
