### ISSUE TITLE
guideline how to store global const strings?

### ISSUE THREAD

**Issue by beinhaerter** [isocpp/CppCoreGuidelines#1741]
In a review for C++17 code that I currently was part of we had a discussion about how to store global string objects.

The old code had a global `constexpr char setting[]{ "my string" };` and passed the string around as `const char*`, having an array to pointer decay problem. According to the guideline the code was changed to pass the string around as `std::string_view` and not as `const char*`. But additionally the author changed the global character array to a `constexpr std::string_view{ "my string" };`

In my opinion having a string literal allows most possibilities, for example passing to an array-aware template, but at the cost of not preventing an array to pointer decay. A `string_view` prevents the array to pointer decay but also prevents passing the string to array aware templates. So I would chose the type depending on the use cases, probably prefering `string_view`.

Looking at the guidelines we saw that most of the guidelines, or at least the examples in the guidelines, are for how to pass strings around, not for how to store them.
Did we miss something? Is there some general guidance for how to best store global constant strings? Is there a preferred way how to do it? Would it make sense to extend some examples in the guidelines to better reflect for example if `string_view` is also a good idea for global constant strings?

**Comment by MikeGitb** [comment]
Just food for thought: 
In th unoptimized case, every conversion from constexpr char setting[] to std::string_view cost a couple of function calls, including `std::char_traits<char>::length` and I think msvc even recomputes the length during runtime in the optimized case.

https://godbolt.org/z/YGPddW

Regarding the use with array-aware templates I'm not sure if this is sanctioned by the standard, but if it s, a possible workaround would be `*reinterpret_cast<const char (*)[foo.size()]>(foo.data())`. size can also be used as an argument for non-type template parameter.

I prefer constexpr std::string_view (or actually something similar that is guaranteed to be null terminated), but priorities might be different in different contexts.

**Comment by jwakely** [comment]
Your `reinterpret_cast` is undefined if the actual array length is `foo.size()+1` (as would be the case if it is initialized from a string literal), or generally if the length is greater than `foo.size()` (as for a sub-view of a larger string).

**Comment by MikeGitb** [comment]
@jwakely: I was explicitly only thinking about the use case given here, where the std::string_view is known to come from a string litteral. But thanks for pointing out the off-by-one error.

Anyway - I wouldn't recommend it one way or another.

**Comment by hsutter** [comment]
Editors call: Changing to `string_view` makes the decision up front to drop the null terminator. Storing it as a string literal or `constexpr char setting[]{ "my string" };` is fine.
