### ISSUE TITLE
T.61: Account for local lambdas

### ISSUE THREAD

**Issue by johelegp** [isocpp/CppCoreGuidelines#1742]
Although the SCARY "acronym" doesn't do justice to local _lambda-expression_s, the concerns raised in T.61 still apply to them. They also apply to the proposed https://github.com/cplusplus/papers/issues/774.

**Comment by hsutter** [comment]
Editors call: We're not sure what change you are requesting, can you explain more about what the problem is with the current text and what kind of change would help address it?

**Comment by johelegp** [comment]
Sure. According to https://wg21.link/expr.prim.lambda.closure#2,
> The closure type is declared in the smallest block scope, class scope, or namespace scope that contains the corresponding lambda-expression.

This means there's a closure type for every instantiation of the following template, even though the lambda expression only depends on a single type:
```C++
template<class T,class U,class V> void f() { ...; [](T t) { ... }(); ...; }
```

It could be hoisted out:
```C++
inline constexpr auto the_t = []<class T>() { ... };
template<class T,class U,class V> void f() { ...; the_t<T>(); ...; }
```
Then it wouldn't depend on `U` and `V`. That leads to less code size and less limited uses thanks to it depending on a minimum set of types. These are the advantages pointed out in T.61. But it limits itself to members of templates.

**Comment by hsutter** [comment]
Editors call: Thanks! We agree and will update the item.
