### ISSUE TITLE
Default generated copy constructors should assume that member classes copy constructors may be explicit

### ISSUE THREAD

**Issue by greg7mdp** [isocpp/CppCoreGuidelines#1743]
Hi there,

Thanks for the great work. Really! Now on to my issue (no really an issue, just a pain point for me and a suggestion):

For classes like std::shared_ptr (I have my own class for an intrusive_ptr), it is really nice to make the copy constructor explicit, as it flags many occurrences when the object may be copied (like when passed by value, or using `auto` instead of `const auto&` in a `for` loop), which triggers excessive increment/decrement of the reference count.

The issue is that, when I make the copy constructor explicit, it prevents some compilers from generating default copy constructors for class containing my intrusive_ptr. There is no problem for msvc, but g++ (version 8.3.1) issues errors like:

```
xDrawableContext.h: In copy constructor xDrawableContext::xDrawableContext(const xDrawableContext&):
xDrawableContext.h:66:7: error: no matching function for call to xIntruPtr<xDrawable>::xIntruPtr(const xIntruPtr<xDrawable>&)
 class xDrawableContext
       ^~~~~~~~~~~~~~~~
```

This occurs when the copy constructor is declared explicit:

```
template <class T>
class xIntruPtr  
{
public:
    inline explicit xIntruPtr(const xIntruPtr<T>& o)  noexcept : _ptr(o._ptr)
    {
        if (_ptr)
            _ptr->AddRef();
    }
```

I think it would be great if the C++ standard specified that the default constructors generated by the compiler should assume that the constructors of class members may be explicit, and generate code that supports that use case.

**Comment by jwakely** [comment]
This seems to be a feature request for the C++ standard itself, not the Core Guidelines, so this is the wrong place to post it. See  https://isocpp.org/std/submit-issue for the correct place, but make sure you provide a complete example (I can't reproduce the error you showed).

 > or using `auto` instead of `const auto&` in a `for` loop

N.B. GCC 11 will warn about this.

**Comment by greg7mdp** [comment]
@jwakely thanks for the answer.
Indeed you are right on both counts. this is probably the wrong forum, and g++ shows the error only when using an array of xIntruPtr. Here is the sample:

```
template <class T>
class xIntruPtr  
{
public:
    inline explicit xIntruPtr() noexcept : _ptr(0) {}

    inline explicit xIntruPtr(const xIntruPtr<T>& o)  noexcept : _ptr(o._ptr) {}

    inline explicit xIntruPtr(xIntruPtr<T>&& o) noexcept : _ptr(o._ptr) 
    {
        o._ptr = nullptr; 
    }

    T* _ptr;
};

class A
{
    xIntruPtr<int> p[2];
};

void fn()
{
    A a;
    A a2(a);
}
```

**Comment by greg7mdp** [comment]
Also I think the `std::shared_ptr` copy constructor should have been defined as  `explicit` in the standard. That would have made programs faster, and saved a lot of electricity. However it is probably too late to change it now.

**Comment by jwakely** [comment]
I strongly disagree, explicit copy constructors are weird and awkward. They have no place in a type like `std::shared_ptr`. It would be better to improve compilers and static analysis tools to warn about it, not hobble the API.

I think the error from GCC is just a bug, nothing needs to change in the standard.

**Comment by greg7mdp** [comment]
> explicit copy constructors are weird and awkward.
this is your personal opinion, unsubstantiated, and which I disagree with, at least for the use case I mentioned. 

> They have no place in a type like std::shared_ptr.
really? who are you to decide?
