### ISSUE TITLE
recommended compiler warning flags

### ISSUE THREAD

**Issue by dvirtz** [isocpp/CppCoreGuidelines#1746]
Should the core guidelines have a list of recommended compiler warning flags?
The C++ Coding Standards book says "Use your compiler’s highest warning level" but that's usually not advisable, see e.g. [this](https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/) titled "Don’t put -Weverything in your build flags" blog post by Arthur O’Dwyer. 
Hence I think an official guideline is needed.
A good reference might be [Abseil Compiler Flags](https://abseil.io/docs/cpp/platforms/compilerflags)

**Comment by jwakely** [comment]
The existence of `-Weverything` can be considered a bug.

I don't think this belongs in the guidelines, because it depends on your compiler and even varies between releases of the same compiler.

**Comment by hsutter** [comment]
Editors call: Warnings are not usually defined as a coherent whole even in a given compiler. We don't think we can recommend everyone using a particular compiler's total set of warnings.
