### ISSUE TITLE
C.21 good example needs default ctor

### ISSUE THREAD

**Issue by ralfholly** [isocpp/CppCoreGuidelines#1748]
In the "good example", declaring the copy-ctor deletes the default constructor. Hence, the default constructor needs to be declared as default as well. Otherwise, derived classes can't be instantiated:
```
class AbstractBase {
public:
  virtual ~AbstractBase() = default;
  AbstractBase() = default;  // *** add this! ***
  AbstractBase(const AbstractBase&) = default;
  AbstractBase& operator=(const AbstractBase&) = default;
  AbstractBase(AbstractBase&&) = default;
  AbstractBase& operator=(AbstractBase&&) = default;
};
```

**Comment by hsutter** [comment]
Editors call: We agree the example should be improved and have reworked it to resolve this. Thanks!
