### ISSUE TITLE
Suggestion for new guideline: Prefer to keep logic simple (was "Prefer shallow nesting of conditions")

### ISSUE THREAD

**Issue by peno2** [isocpp/CppCoreGuidelines#1752]
I suggest to add a guideline on "using guard clause" to simplify conditions.
This is a guideline present in for example mongodb's "Server Code Style", there named "Return Early".
See: https://github.com/mongodb/mongo/wiki/Server-Code-Style#return-early

    // Deep nesting
    void foo() {
        ...
        if (x) {
            computeImportantThings(x);
        }
    }

    // Not so good either. Now an early return, but a redundant else.
    void foo() {
        ...
        if (!x) {
            return;
        }
        else {
            computeImportantThings(x);
        }
    }

    // Better, shallow nesting, no redundant else.
    void foo() {
        ...
        if (!x)
            return;

        computeImportantThings(x);
    }

See also: https://refactoring.guru/replace-nested-conditional-with-guard-clauses
and https://blog.codinghorror.com/flattening-arrow-code/

Related topic in the guidelines is at least:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rnr-single-return

**Comment by peno2** [comment]
Here comes a version which is a bit more worked through and more suitable as an actual guideline.
Comments are welcome!

-------------------------------------------
**Prefer shallow nesting of conditions.**

Prefer shallow nesting of conditions. This usually makes the code easier to follow. It also makes the intent clearer.
Strive to place the essential code at outermost scope, unless this obscures intent.

Use a guard-clause to take care of exceptional cases and return early.

```
// Deep nesting, avoid if possible.
void foo() {
    ...
    if (x) {
        computeImportantThings(x);
    }
}

// Not so good either. Now an early return, but a redundant else.
void foo() {
    ...
    if (!x) {
        return;
    }
    else {
        computeImportantThings(x);
    }
}

// Good. Shallow nesting, early return, no redundant else and the essential code at outermost scope.
void foo() {
    ...
    if (!x)
        return;

    computeImportantThings(x);
}

```
Another example:
```
// Not so good. Unnecessary nesting of if-clauses.
void foo() {
    ...
    if(x) {
        if (y) {
             computeImportantThings(x);
        }
    }
}

// Suggested rewrite: shallow nesting, early return and the essential code at outermost scope.
void foo() {
    ...
    if (!(x && y))
        return;

    computeImportantThings(x);
}
```
**Enforcement:**

- A tool can flag redundant else.

See also:
[NR.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rnr-single-return)

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rnr-single-return

**Comment by hsutter** [comment]
Editors call: We agree, but perhaps rephrase it as "prefer to keep logic simple"... For example, mandatory curly braces is just syntactic and doesn't affect complexity/structure, but early return does reduce complexity and nesting.

**Comment by peno2** [comment]
So, here is an updated text, trying to fulfil editors comment.

------------------------------------
**Prefer to keep logic simple**

Prefer to keep logic simple whenever possible. This reduces possibilities for mistakes. It also makes the intent clearer.
Strive to place the essential code at outermost scope to emphasize the normal flow.

Use a guard-clause with an early return to take care of exceptional cases.

```
// Deep nesting of the essential code, avoid if possible.
void foo() {
    ...
    if (x)
        computeImportantThings(x);
}

// Not so good either. Now an early return, but a redundant else.
void foo() {
    ...
    if (!x)
        return;
    else
        computeImportantThings(x);
}

// Good. Early return, no redundant else and the essential code at outermost scope.
void foo() {
    ...
    if (!x)
        return;

    computeImportantThings(x);
}

```
Another example:
```
// Not so good. Unnecessary nesting of if-clauses.
void foo() {
    ...
    if(x) {
        if (y)
             computeImportantThings(x);
    }
}

// Suggested rewrite: simplified logic, early return and the essential code at outermost scope.
void foo() {
    ...
    if (!(x && y))
        return;

    computeImportantThings(x);
}
```
**Enforcement:**

- A tool can flag redundant else.

See also:
[NR.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rnr-single-return)

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rnr-single-return

**Comment by hsutter** [comment]
@peno2 Thanks! After we started to write it, we ended up going back more to your original. In both cases though, thanks!
