### ISSUE TITLE
Download the PDF version of guidelines?

### ISSUE THREAD

**Issue by Behrouz-m** [isocpp/CppCoreGuidelines#1754]
is there any way to download a PDF version of the guidelines?

**Comment by alexhajdu** [comment]
Just print the page and instead of selecting a physical printer, choose Print to PDF. Win. Not sure about other platforms...
![image](https://user-images.githubusercontent.com/1824796/109483388-74909600-7a7f-11eb-8c3f-2e1c63597858.png)

**Comment by cugone** [comment]
But why would you want to? The guidelines change so often that the moment it's printed, it's already out of date. :/

**Comment by hsutter** [comment]
Editors call: Thanks for the tip @alexhajdu !

**Comment by kassane** [comment]
> Just print the page and instead of selecting a physical printer, choose Save as PDF. Win. Not sure about other platforms...
> ![image](https://user-images.githubusercontent.com/1824796/109483388-74909600-7a7f-11eb-8c3f-2e1c63597858.png)
> 

Fine! There is also an alternative to download the markdown file and use an md to PDF converter. Vscode for example has extensions for this purpose!

**Comment by zorchp** [comment]
I try the method in this [issue](https://github.com/isocpp/CppCoreGuidelines/issues/23), you just need use this command in the repo path. (need to install pandoc and tex)
```bash
pandoc CppCoreGuidelines.md --pdf-engine=pdflatex -o cppcoreguidelines.pdf
```
