### ISSUE TITLE
C63. Enforcement

### ISSUE THREAD

**Issue by HamzaHajeir** [isocpp/CppCoreGuidelines#1757]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c63-make-move-assignment-non-virtual-take-the-parameter-by--and-return-by-non-const-

I think the enforcement should change `T&` to `T&&` : 

- (Simple) An assignment operator should not be virtual. Here be dragons!
- (Simple) An assignment operator should return _`T&&`_ to enable chaining, not alternatives like _`const T&&`_ which interfere with composability and putting objects in containers.
- (Moderate) A move assignment operator should (implicitly or explicitly) invoke all base and member move assignment operators.

**Comment by jwakely** [comment]
No, absolutely not. You do not want assignment to perform an implicit conversion to an rvalue.

```
Foo f1, f2, f3;
f1 = f2 = std::move(f3);
```

With your suggestion this would silently move from `f2` to `f1`!

**Comment by HamzaHajeir** [comment]
You're right, I just was going to close/remove the issue.
