### ISSUE TITLE
CONTRIBUTING.md should specify an indentation strategy

### ISSUE THREAD

**Issue by blakehawkins** [isocpp/CppCoreGuidelines#176]
For example, all indented lines should begin with 4 spaces, and all tabulation should use spaces rather than tab characters.

Relevant: #175

**Comment by tkruse** [comment]
Is there a consensus of whether tabulation should have 2 or 4 spaces?

**Comment by tkruse** [comment]
The other thing that really worries me about style is line length in code blocks. Because a document like this may be distributed in various forms, and code blocks wrapped into the next lines are very difficult to read.

**Comment by blakehawkins** [comment]
> Is there a consensus of whether tabulation should have 2 or 4 spaces?

I don't think there ever will be :P I generally prefer 4 spaces.

> Sorry, I guess you meant tabulation for things like comments.

I think both should be specified, as you mentioned above.

> The other thing that really worries me about style is line length in code blocks.

Agree that should also be specified. Code and code comments should be limited to 79 characters or so.

Another thing that might be worth specifying is preferred markdown syntax/flavor - in particular there's a PR up right now which uses code fencing.

**Comment by tkruse** [comment]
I thought code fencing was ruled out anyway. See #219 anyway, with that, mdast can always easily switch between fences / no fences.

**Comment by blakehawkins** [comment]
> I thought code fencing was ruled out anyway.

Agree. I just think specifying so in `CONTRIBUTING.md` would be worthwhile.

**Comment by AndrewPardoe** [comment]
Discussed 11/30/2015.

@blakehawkins, thanks for the earlier PRs. Could you please prepare another PR regarding use of four-space indentation rather than tabs and indented code blocks rather than code fencing?

**Comment by blakehawkins** [comment]
PR for this was merged - closing.
