### ISSUE TITLE
Add new guideline against const/reference data members (was: Con.1 & 4 Exception)

### ISSUE THREAD

**Issue by SuperWig** [isocpp/CppCoreGuidelines#1762]
Could also be a separate item?

**Comment by hsutter** [comment]
Editors call: If we add a guideline against const data members it should also mention reference data members, which have the same problems.

**Comment by hsutter** [comment]
I covered the references part as part of ["References, Simply"](https://herbsutter.com/2020/02/23/references-simply/).

**Comment by hsutter** [comment]
Added C.12, closed. Thanks!
