### ISSUE TITLE
C.67: A base class should suppress copying, and provide a virtual clone instead if "copying" is desired

### ISSUE THREAD

**Issue by andralex** [isocpp/CppCoreGuidelines#177]
Two issues:

* A base class may choose to define copying as a protected operation, and use it inside clone(). Otherwise, implementing clone() efficiently and without code duplication is difficult.

* The Checked Clone idiom should be mentioned:

```C++
class S {
protected:
  virtual std::unique_ptr<S> cloneImpl() const;
public:
  std::unique_ptr<S> clone() const {
    auto result = cloneImpl();
    assert(typeid(*this) == typeid(*result.get()));
    return result;
  }
  ...
};
```

Ensures the result type is identical with the incoming type.

**Comment by AndrewPardoe** [comment]
Discussed 21 Dec 2015.

**Comment by hsutter** [comment]
We agree, but don't think a change is needed specifically here -- we want to avoid too much detail. For example, we agree that a `clone` implementation could use a helper function (though it doesn't need to be one of the special copy functions), and that in general Non-Virtual Interface (NVI) pattern suggests having a public nonvirtual function be implemented in terms of nonpublic virtual functions; we would like to avoid that kind of implementation detail, which applies generally, in a specific item like this one. Instead, we have opened the new broader issue #474 to capture more general points such as this. Thanks!
