### ISSUE TITLE
Confusion over what Concrete types are

### ISSUE THREAD

**Issue by tiagomacarios** [isocpp/CppCoreGuidelines#1780]
The Core Guidelines defines Concrete types as follows:

["concrete class: class for which objects can be created using usual construction syntax (e.g., on the stack) and the resulting object behaves much like an int as it comes to copying, comparison, and such (as opposed to a base class in a hierarchy)."](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#glossary:~:text=concrete%20class%3A%20class%20for%20which%20objects,a%20base%20class%20in%20a%20hierarchy)

The standard seems not to define concrete types. Below are the only hits for "concrete":

> [class.abstract]https://eel.is › c++draft › class.abstract
> The abstract class mechanism supports the notion of a general concept, such as a shape, of which only more concrete variants, such as circle and square, can ...
> 
> [util.smartptr.shared.create]https://eel.is › c++draft › util.smartptr.shared.create
> The object is initialized from args as specified by the concrete overload. The allocate_shared and allocate_shared_for_overwrite templates use a copy of a ...
> 
> [range.iter.ops]https://eel.is › c++draft › range.iter.ops
> ... operations adapt to the set of operators provided by each iterator category to provide the most efficient implementation possible for a concrete iterator type.
> 
> [range.iter.ops.general]http://eel.is › c++draft › range.iter.ops.general
> ... operations adapt to the set of operators provided by each iterator category to provide the most efficient implementation possible for a concrete iterator type.
> 
> [iterator.primitives]http://eel.is › c++draft › iterator.primitives
> ... operations adapt to the set of operators provided by each iterator category to provide the most efficient implementation possible for a concrete iterator type.
> 
> [util.smartptr.shared]https://eel.is › c++draft › util.smartptr.shared
> Effects: Allocates memory for an object of type T (or U[N] when T is U[], where N is determined from args as specified by the concrete overload). The object is ...
> 
> [utilities]https://eel.is › c++draft › utilities
> Effects: Allocates memory for an object of type T (or U[N] when T is U[], where N is determined from args as specified by the concrete overload). The object is ...
> 
> [smartptr]https://eel.is › c++draft › smartptr
> Effects: Allocates memory for an object of type T (or U[N] when T is U[], where N is determined from args as specified by the concrete overload). The object is ...
> 
> [iterators]https://eel.is › c++draft › iterators
> ... operations adapt to the set of operators provided by each iterator category to provide the most efficient implementation possible for a concrete iterator type.

The only definition for concrete that I found that agree with the guidelines come from BJarne's book, A Tour Of C++:

https://learning.oreilly.com/library/view/a-tour-of/9780134998053/ch04.xhtml#ch04lev1sec2

> 4.2 CONCRETE TYPES
> The basic idea of concrete classes is that they behave “just like built-in types.” For example, a complex number type and an infinite-precision integer are much like built-in int, except of course that they have their own semantics and sets of operations. Similarly, a vector and a string are much like built-in arrays, except that they are better behaved (§9.2, §10.3, §11.2).
> 
> The defining characteristic of a concrete type is that its representation is part of its definition. In many important cases, such as a vector, that representation is only one or more pointers to data stored elsewhere, but that representation is present in each object of a concrete class. That allows implementations to be optimally efficient in time and space. In particular, it allows us to
> 
> place objects of concrete types on the stack, in statically allocated memory, and in other objects (§1.5);
> 
> refer to objects directly (and not just through pointers or references);
> 
> initialize objects immediately and completely (e.g., using constructors; §2.3); and
> 
> copy and move objects (§5.2).
> 
> The representation can be private (as it is for Vector; §2.3) and accessible only through the member functions, but it is present. Therefore, if the representation changes in any significant way, a user must recompile. This is the price to pay for having concrete types behave exactly like built-in types. For types that don’t change often, and where local variables provide much-needed clarity and efficiency, this is acceptable and often ideal. To increase flexibility, a concrete type can keep major parts of its representation on the free store (dynamic memory, heap) and access them through the part stored in the class object itself. That’s the way vector and string are implemented; they can be considered resource handles with carefully crafted interfaces.

The current definition of concrete types in the guidelines leads to confusion because there is a widespread (mis?)understanding that concrete types are types that implement interfaces. Examples:

https://stackoverflow.com/questions/2149207/what-is-the-difference-between-a-concrete-class-and-an-abstract-class

> Abstract class can not be used to create an object. Whereas, concrete class can be used to create an object.
> 
> Concrete means''existing in reality or in real experience; perceptible by the senses; real''. Whereas, abstract means 'not applied or pratical; theoritical'.
> 
> An abstract class can't be instantiated. Whereas, a concrete one can.
> 
> An abstract class is one that has one or more pure virtual function. Whereas a concrete class has no pure virtual functions.

https://en.wikipedia.org/wiki/Abstract_type

> In programming languages, an abstract type is a type in a nominative type system that cannot be instantiated directly; a type that is not abstract – which can be instantiated – is called a concrete type. Every instance of an abstract type is an instance of some concrete subtype. Abstract types are also known as existential types.[1]

https://en.wikipedia.org/wiki/Class_(computer_programming)#Abstract_and_concrete

> Abstract and concrete
> In a language that supports inheritance, an abstract class, or abstract base class (ABC), is a class that cannot be instantiated because it is either labeled as abstract or it simply specifies abstract methods (or virtual methods). An abstract class may provide implementations of some methods, and may also specify virtual methods via signatures that are to be implemented by direct or indirect descendants of the abstract class. Before a class derived from an abstract class can be instantiated, all abstract methods of its parent classes must be implemented by some class in the derivation chain.[26]
> 
> Most object-oriented programming languages allow the programmer to specify which classes are considered abstract and will not allow these to be instantiated. For example, in Java, C# and PHP, the keyword abstract is used.[27][28] In C++, an abstract class is a class having at least one abstract method given by the appropriate syntax in that language (a pure virtual function in C++ parlance).[26]
> 
> A class consisting of only virtual methods is called a Pure Abstract Base Class (or Pure ABC) in C++ and is also known as an interface by users of the language.[14] Other languages, notably Java and C#, support a variant of abstract classes called an interface via a keyword in the language. In these languages, multiple inheritance is not allowed, but a class can implement multiple interfaces. Such a class can only contain abstract publicly accessible methods.[20][29][30]
> 
> A concrete class is a class that can be instantiated, as opposed to abstract classes, which cannot.

I am not sure exactly how to reduce the confusion and it looks like this was already discussed in issues:
#1268
#1267

One suggestion would be to rename that section to "value types".

**Comment by hsutter** [comment]
We've decided to take a pass and consistently use these terms:

*base class*: A type that is intended to be derived from (e.g., has a non-final virtual function), and objects of the type are intended to be used only indirectly (e.g., by pointer). [In strict terms, "base class" could be defined as "something we derived from" but we are specifying in terms of intent.]
 
*concrete type*: a type that is not a base class, and objects of the type are intended to be used directly (not only by pointer/indirection), its size is known, it can typically be allocated anywhere the programmer wants (e.g., stack or statically)
 
*semiregular type*: a concrete type that is assignable and default-constructible (see `std::semiregular` concept)
 
*regular type*: a semiregular type that is equality-comparable (see `std::regular` concept)
 
And a note: Some people use the term 'value type' to mean a regular or semiregular type.
