### ISSUE TITLE
ES:44 Bug in Example

### ISSUE THREAD

**Issue by Nishank-25** [isocpp/CppCoreGuidelines#1791]
// Given in guidelines
int i = 0;
f(++i, ++i);

// Corrected version
int i = 0;
f(i, ++i);

Also the explanation will have f(0,1) or f(1,1) as the 2 cases.

**Comment by cubbimew** [comment]
Both f(++i, ++i) and f(i, ++i) are equally good examples of undefined (C and older C++) / unspecified (C++ as of C++17) behavior, but yes the sentence right after the example "f(0, 1) or f(1, 0)," is currently wrong for C++17.

**Comment by Nishank-25** [comment]
Yes either of them can be corrected.

**Comment by hsutter** [comment]
Editors' call: We agree and will fix this, thanks!
