### ISSUE TITLE
Grammar mistake in T.43

### ISSUE THREAD

**Issue by deanhill1971** [isocpp/CppCoreGuidelines#1793]
I'm not sure if this is the correct place to report grammar and formatting errors. I tried emailing coreguidelines@isocpp.org, but that address was undeliverable.

Under section T.43 I think the words "used in" should be added:

> Generality: using can be used for template aliases, whereas typedefs can't easily be **[used in]** templates.

**Comment by cubbimew** [comment]
The places is correct, but it means what it says: typedefs can't be templates. It is also demonstrated in the example (PFT, a template typedef, doesn't compile, but PFT2, a template using, does)

**Comment by deanhill1971** [comment]
You're right. I mis-read the sentence. :-)
Thanks for the reply.
