### ISSUE TITLE
Example C.126 '???' 

### ISSUE THREAD

**Issue by MrQualifications** [isocpp/CppCoreGuidelines#1794]
Instead of no example, I propose the example found in "A Tour of C++ 2nd Ed" BS

Chapter 4.5 Class Hierarchies pg 58.

///////// EXAMPLE CODE ///////////////////////////////////////////////

class Shape {
public: 
    //**No Constructor Needed in Abstract/Base Class**
    virtual Point center() const =0;                                 // pure virtual
    virtual void move(Point to) =0;                               

    virtual void draw() const =0;                                    // draw on current "Canvas"
    virtual void rotate(int angle) =0;

    virtual ~Shape() {}                                                   // destructor
    //...
};

class Circle : public Shape {
public: 
     Circle(Point p, int rad);                                           // constructor in derived class

     Point center() const override
     {
          return x;
     }

//////////////////////////////////////////////////////////////////////////////
Example Continues on Pg 59

**Comment by hsutter** [comment]
Editors call: We agree, this is a good improvement. Thanks!
