### ISSUE TITLE
Markdown issue in "Pro.safety: Type-safety profile" section

### ISSUE THREAD

**Issue by madeso** [isocpp/CppCoreGuidelines#1800]
### Issue
*Pro.safety: Type-safety profile* type 1 bullet point attempts to use a letter lists but this doesn't render in markdown properly turning the nice text list into a unreadable textblock.

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#prosafety-type-safety-profile
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#prosafety-type-safety-profile

### Suggested fixes:

* To keep using a letter list one apparently has to [write html in markdown](https://stackoverflow.com/questions/13366820/how-do-you-make-lettered-lists-using-markdown).
* The other option would be to turn it into a regular numbered lists

**Comment by cubbimew** [comment]
resolved by #1801 thanks
