### ISSUE TITLE
[Proposal] The core guidelines should discourage out parameters on coroutines (CP.coro section)

### ISSUE THREAD

**Issue by dmachaj** [isocpp/CppCoreGuidelines#1804]
# Do not use out parameters in a coroutine

## Reason
Out parameters require that the caller has set aside memory for them, usually on the stack.  Once a coroutine has reached its first suspension point the stack will unwind and this memory will be reclaimed.  After that point, writing to the out parameter will overwrite memory that has already been freed.  

Out parameters that are allocated on the heap may have sufficient lifetime to avoid this problem.  However, it is not possible to validate the lifetime of memory passed in by a caller so this is a dangerous practice to rely upon for safety.

Out parameters that are always written before the first suspension point are not vulnerable to this issue.  Future changes may add or move suspension points in the coroutine, so that this is no longer true.  That makes this pattern fragile and thus discouraged.

## Example, Bad
```cpp
std::future<std::string> Class::do_something(int& result)
{
  co_await something();
  result = 42; // danger: result may be a reference to freed memory
  co_return "foo";
}
```

## Example, Good
```cpp
std::future<std::pair<std::string, int>> Class::do_something()
{
  co_await something();
  co_return std::make_pair("foo", 42);
}
```

**Comment by neithernut** [comment]
Isn't this already covered by [F.20: For "out" output values, prefer return values to output parameters](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-out) and [F.21: To return multiple "out" values, prefer returning a struct or tuple](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f21-to-return-multiple-out-values-prefer-returning-a-struct-or-tuple)?
Of course, with coroutines out parameters become (even) more of a problem. This _may_ merit an additional rule or at least a note in [CP.coro](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#SScp-coro) but maybe a note in F.20 and/or F.21 would be sufficient.

**Comment by dmachaj** [comment]
This is related to F.20/F.21 but I think this is a distinct problem that can justify a separate guideline under the coroutine section.  F.20/F.21 are guidance that it is _better_ to return instead of using out parameters.  Out parameters in normal functions are worse than return values, but they are not subtle bugs that will cause crashes or memory corruption.  Out parameters on coroutines are incorrect and will lead to problems.  An explicit guideline is useful because the crashes will often be intermittent and hard to debug (ask me how I know :) ).

**Comment by dmachaj** [comment]
It is probably simplest to roll this into #1812 as part of the "don't pass by reference" guideline.  I have added it as a note to CP.53.
