### ISSUE TITLE
[Proposal] Locks or other synchronization primitives should not be held across suspension points in a coroutine (CP.coro section)

### ISSUE THREAD

**Issue by dmachaj** [isocpp/CppCoreGuidelines#1805]
# Do not hold locks or other synchronization primitives across suspension points

## Reason
This is at best a degradation of performance, and at worst it will cause a deadlock.  When a suspension point is reached, such as co_await, execution of the current function stops and other code begins to run.  It may be a long period of time before the coroutine resumes.  For that entire duration the lock will be held and cannot be acquired by other threads to perform work.  

This pattern can also lead to deadlocks.  Some types of waits will allow the current thread to perform additional work until the asynchronous operation has completed.  If the thread holding the lock performs work that requires the same lock then it will deadlock because it is trying to acquire a lock that it is already holding.

## Example, Bad
```cpp
std::mutex g_lock;

std::future<void> Class::do_something()
{
  std::lock_guard<std::mutex> guard(g_lock);
  co_await something(); // DANGER: coroutine has suspended execution while holding a lock
  co_await somethingElse();
}
```

## Example, Good
```cpp
std::mutex g_lock;

std::future<void> Class::do_something()
{
  {
    std::lock_guard<std::mutex> guard(g_lock);
    // modify data protected by lock
  }
  co_await something(); // OK: lock has been released before coroutine suspends
  co_await somethingElse();
}
```

**Comment by oldnewthing** [comment]
And if the coroutine completes on a thread different from the thread that acquired the lock, you have UB. Even if you explicitly return to the original thread to destruct the guard, that isn't good enough because an exception might be thrown before you can get back.

**Comment by hsutter** [comment]
Editors call: Thanks, we agree with adding this rule. Could you please create a PR, with these adjustments:
   - make it guideline number CP.52
   - keep the reason short, and make the other rationale a 'Discussion' section
   - add @oldnewthing 's suggestion
Thanks!

**Comment by dmachaj** [comment]
#1812
