### ISSUE TITLE
[Proposal] Parameters to coroutines should not be passed by reference (CP.coro section)

### ISSUE THREAD

**Issue by dmachaj** [isocpp/CppCoreGuidelines#1806]
# Parameters to coroutines should not be passed by reference

## Reason
Once a coroutine reaches the first suspension point, such as a `co_await`, the synchronous portion returns.  After that point any parameters passed by reference are dangling.  Any usage beyond that is undefined behavior which may include writing to freed memory.

This problem does not apply to reference parameters that are only accessed before the first suspension point.  However, it is fragile to rely on that because subsequent changes to the function may add or move suspension points which would reintroduce this class of bug.  It is safer to always pass by value because the copied parameter will live in the coroutine frame that is safe to access throughout the coroutine.

## Example, Bad
```cpp
std::future<int> Class::do_something(const std::shared_ptr<int>& input)
{
  co_await something();
  co_return *input + 1; // DANGER: the reference to input is no longer valid and may be freed memory
}
```

## Example, Good
```cpp
std::future<int> Class::do_something(std::shared_ptr<int> input)
{
  co_await something();
  co_return *input + 1; // input is a copy that is still valid here
}
```

**Comment by hsutter** [comment]
Editors call: Thanks, we agree with adding this rule. Could you please create a PR, with these adjustments:
   - make it guideline number CP.53
   - keep the reason short (e.g., it's brittle and misuse can lead to UB), and make the other rationale a 'Note' section
   - please remove the idea that we can even rely on them before the first suspension point

**Comment by dmachaj** [comment]
#1812 1812

**Comment by dmachaj** [comment]
#1812

**Comment by nejati-deriv** [comment]
I think this rule might be wrong and make the code bases using coroutines more bug-prone. It is quite common to manage the lifetime of coroutines within the scope that they are spawned and pass const or mutable reference to the child coroutines. That is what we can expect from structured concurrency.

For example, here we launch two tasks and wait for them to complete:
```C++
auto socket = asio::ip::tcp::socket{ executor };
co_await socket.async_connect(endpoint, asio::deferred);

auto receive_task = [](asio::ip::tcp::socket &socket) -> asio::awaitable< void >
{
    // ..
};

auto send_task = [](asio::ip::tcp::socket &socket) -> asio::awaitable< void >
{
    // ..
};

co_await wait_for_all(receive_task(socket), send_task(socket));
```

Here we spawn one coroutine per connection and wait for them to complete at the end of the scope:
```C++
asio::awaitable< void > handle_session(asio::ip::tcp::socket socket, Database & database);

auto database   = Database{};
auto task_group = TaskGroup{};
auto acceptor   = asio::ip::tcp::acceptor{ executor, endpoint };

for (;;)
{
    auto [ec, socket] = co_await acceptor.async_accept(asio::as_tuple(asio::deferred));
    if (ec)
        break;
    task_group.spawn(handle_session(std::move(socket), database));
}

co_await task_group.join();
```

Aside from these examples, every coroutine member function has an implicit reference to the instance.
So if this guideline prohibits references in coroutine parameters and suggests allocating objects on the heap and passing them as `shared_ptr`, it would be against structured concurrency and can create a shared pointer spaghetti.
