### ISSUE TITLE
"Appendix C: Discussion" contains non-link references to old item number scheme

### ISSUE THREAD

**Issue by david-bakin** [isocpp/CppCoreGuidelines#1810]
["Appendix C: Discussion"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#appendix-c-discussion) contains non-link references to an old item numbering scheme, e.g., "see Items 35 through 37" and "See Items 39 and 55".

If I wanted to submit a PR to fix this - could someone point me to a point in time (or tag, or commit) where this older numbering scheme was still in use, so I could accurately determine what the references should be?  (I'm hoping for something easier than looking for when each paragraph was introduced using blame, and looking at those commits ... but I guess I could do that.)

(And would it be acceptable to submit all such fixes in this section in one PR?)

**Comment by hsutter** [comment]
Editors call: This numbering is unrelated to the Guidelines, this is material that was pasted in from another book to be reviewed and merged into the main Guidelines later and we haven't done that yet.
