### ISSUE TITLE
C.84 and C.85: Distinction without a difference?

### ISSUE THREAD

**Issue by david-bakin** [isocpp/CppCoreGuidelines#1811]
(I'm attempting to look at the C++ Core Guidelines with an eye to submitting (minor) improvements - but I don't have a history here, and don't know the history of what's been done to the document in the past.  Hence a couple of "newbie" questions ...)

To my eye [C.84 A swap function must not fail](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c84-a-swap-function-must-not-fail) and [C.85 Make swap noexcept](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c85-make-swap-noexcept) are saying the same thing, and there needs to be only one of them.  

* Similarly for [C.36 A destructor must not fail](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c36-a-destructor-must-not-fail) and [C.37 Make destructors noexcept](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c37-make-destructors-noexcept), though the wording in those two items do have somewhat different emphasis while saying the same things - they should be merged, not just one deleted in favor of the other

Is there are reason to have the very similar pairs of items?  Perhaps "findability" on the part of the reader?  Or the intent to have tools point to something specific in one or the other? Is there a process to follow to merge them? (Or is simply having the discussion in an issue like this one the entire process?)

**Comment by neithernut** [comment]
Well, `noexcept` functions and methods can still _fail_ (and abort the program). So you _do_ have two rules which complement each other with C.84/C.85 and C.36/C.37.

**Comment by hsutter** [comment]
Editors call: Good question! Exceptions are one way to report a failure. A destructor should not fail in any way, including by not throwing an exception but also by not reporting failure in other ways.
