### ISSUE TITLE
Weaken or retract guideline NL.26 (const-west vs east-const)

### ISSUE THREAD

**Issue by eyalroz** [isocpp/CppCoreGuidelines#1815]
I believe that the NL.26 guideline, as it stands now, is inappropriate/undesirable.

While I mostly work on codebases which are "const-west", I can definitely appreciate, and occasionally find myself pining, for the consistnency of "east-const". I believe that it is a "better idea", generally (to use the term in NL.26 itself); and it is conventional: It's not the custom for using const, but it is consistent with the convention of placing asterisks and ampersands to the right of the object they regard.

If "east-const" were more prevalent, I would probably use it exclusively. And I'm pretty sure this is true for many many people. It is certainly not inherently inferior to "const-west". As for confusion - the syntax of C and C++ variable declarations is inherently confusing, especially when we come to function pointers... 

I don't believe a guideline whose sole purpose is to encourage keeping a non-beneficial custom is appropriate - even with the current caveats it has.

I therefore suggest one of two changes:

Option 1: Make it a guideline about consistency, i.e. in the same codebase, either user east-const throughout or const-west throughout, rather than mixing them up.

Option 2: Just retract this guideline.

See also the opinions of several C++ luminaries who have signed the "east const petition", [here](http://slashslash.info/petition/).

**Comment by MikeGitb** [comment]
Isn't this covered by the first paragraph in NL:

> Consistent naming and layout are helpful. If for no other reason because it minimizes "my style is better than your style" arguments. However, there are many, many, different styles around and people are passionate about them (pro and con). Also, most real-world projects include code from many sources, so standardizing on a single style for all code is often impossible. After many requests for guidance from users, we present a set of rules that you might use if you have no better ideas, but the real aim is consistency, rather than any particular rule set. IDEs and tools can help (as well as hinder).

**Comment by eyalroz** [comment]
> Isn't this covered by the first paragraph in NL or in NL26 itself:

Well, if you interpret those paragraph the way you just did, then the paragraphs themselves suggest the rule should be retracted.

Having rule NL.26 does not promote consistency; it promotes adherence to custom, which in some cases improves one aspect of consistency and hurts others; and in other cases only hurts consistency.

**Comment by MikeGitb** [comment]
The point is that west / east const is really just as  much about style/personal  preference as the position of openin/closing braces or how to name variables. They have been asked to give their recommendation for people that don't have any preference of their own and thats what they have given while explicitly pointing out multiple times, that consistency is more important than following this particular recommendation.  
So if you have a codebase, where following NL.26 causes significantly  inconsitency (lets face it: No style is 100% consistent), just don't follow it.

 The same justification for removing NL26 could just as well be used to remove "NL.10: Prefer underscore_style names" or almost any other NL recommendation.

I hope the clang-format patch is going to land soon : https://reviews.llvm.org/D69764

>Developers these days seem to argue over east vs west const like they used to argue over tabs vs whitespace or the various bracing style. These previous arguments were mainly eliminated with tools like clang-format that allowed those rules to become part of your style guide. Anyone who has been using clang-format in a large team over the last couple of years knows that we don't have those religious arguments any more, and code reviews are more productive.
>
> https://www.youtube.com/watch?v=fv--IKZFVO8
> https://mariusbancila.ro/blog/2018/11/23/join-the-east-const-revolution/
> https://www.youtube.com/watch?v=z6s6bacI424
>
> The purpose of this revision is to try to do the same for the East/West const discussion. Move the debate into the style guide and leave it there!

**Comment by eyalroz** [comment]
> They have been asked to give their recommendation for people that don't have any preference of their own and thats what they have given

I'm not sure what you mean by "they".  Anyway, the guidelines are not for "people who have no preference of their own". They are general guidelines.

>  while explicitly pointing out multiple times, that consistency is more important than following this particular recommendation.

Pointing out multiple times something which contradicts the basic guideline is a clear sign it should not be a guideline in the first place. And, by the way, we don't see this in other NL section guidelines.

> So if you have a codebase, where following NL.26 causes significantly inconsitency (lets face it: No style is 100% consistent), just don't follow it.

Saying that does not justify an inappropriate guideline. By the same logic you could have a guideline saying "Use K&R brace style", with caveats like "except if it's inconsistent to do so, or if you have a better idea or whatever". 

Moreover, following NL.26 causes significant inconsistency in _all_ codebases: The inconsistency with the placement of other elements of type definitions. 

> The same justification for removing NL26 could just as well be used to remove "NL.10: Prefer underscore_style names" 

No, it's not the same situation. Using `underscore_style` names does not cause a semantic inconsistency. There is no principled argument (AFAIK) against the use of this naming style.

That being said - the fact that an argument for the removal of NL.26 may also apply to NL.10 is no reason to reject the argument.

> The same justification for removing NL26 could just as well be used to remove ... almost any other NL recommendation.

On the contrary. This argument does not apply to most NL section guidelines, e.g. "Don't say in comments what can be clearly stated in code", "State intent in comments", "Keep comments crisp", "Maintain a consistent indentation style" etc. etc.

> Developers these days seem to argue over east vs west const like they used to argue over tabs vs whitespace or the various bracing style. These previous arguments were mainly eliminated with tools like clang-format

No, they aren't: You simply need to decide what const style you tell clang-format to use instead of keeping the decision in your head.

**Comment by asdasdasdasdasdf** [comment]
> This argument does not apply to most NL section guidelines, e.g. "Don't say in comments what can be clearly stated in code", "State intent in comments", "Keep comments crisp", "Maintain a consistent indentation style" etc. etc.

that's actually a really good point some of the rules in NL seem pretty universally applicable and trump an argument for consistency (e.g. NL.3) whereas others (e.g. NL.17) are intended, I believe, to be read as the preference of the editors to be used if you don't have your own preference/standard. I think both are valuable but it is a bit confusing to have them exist in the same section with so much leading and trailing explanation explaining that they're not really rules.

Perhaps putting NL.26 in the same list as NL.2 implies it should be followed with more vehemence than the editors intended (or perhaps I think NL.2 is a more concrete rule than the editors to. I guess I can't tell).

**Comment by eyalroz** [comment]
@asdasdasdasdasdf : Separating NL into two lists, with clearer wording about "vehemence", would likely be an improvement. However, the better course of action may simply be to remove the "weak preference" guidelines.

But such ideas, and the question of what to do with other things in the NL question, are - with respect - muddying the watters. NL.26 itself is an unsound, inconsistent, somewhat-confusing guideline and should be amended or retracted as I've suggested above.

**Comment by BenjamenMeyer** [comment]
Working on a project that is looking to potentially adopt the ISO C++ Guidelines; and to strengthen:

> @asdasdasdasdasdf : Separating NL into two lists, with clearer wording about "vehemence", would likely be an improvement. However, the better course of action may simply be to remove the "weak preference" guidelines.
> 
> But such ideas, and the question of what to do with other things in the NL question, are - with respect - muddying the water. NL.26 itself is an unsound, inconsistent, somewhat-confusing guideline and should be amended or retracted as I've suggested above.

By having inconsistency in the guidelines is makes it harder to adopt. Further by adding things in the guidelines that are more preference also makes it harder when folks don't agree with the preference.

Keep things simpler and stick to things that can build community; keep consistency in the recommendations too.

If you really want to keep the preferences, then it would be a good idea to add something in the grouping information besides `Enforcement` to denote this - and keep it simple such as:

`status: [deprecated|proposal|preference|required]`

Again, keep it simple. Definitions for each could be given in one section. It might even need to include `required-c++XX` if it applies to a specific version or newer (e.g required-c++14 would be for C++14 and newer).

$0.02 FWIW

**Comment by hsutter** [comment]
Editors call: As @MikeGitb quoted, this isn't a guideline, just a suggestion if you are looking for a style recommendation and don't have a reason to use something else.

**Comment by eyalroz** [comment]
@hsutter : I've addressed that point make by @MikeGitb : If it isn't a guideline, then surely the guidelines document must not have it as a guideline, which is exactly what I've suggested.

**Comment by hsutter** [comment]
I understand this has confused people because it can look like a guideline at first, but the whole NL section is labeled "these are not guidelines." If we have the section then people get this impression and we occasionally have to point them to the section's intro that clarifies it. If we don't have the section, then people ask us for the section because they want default guidance (as the intro also mentions). So, we have the section.

We considered repeating the disclaimer (or a pointer to it) inside each NL rule but it seemed verbose to do that. Maybe in the future that would be worthwhile if we continue to see a lot of confusion.
