### ISSUE TITLE
Suggestion: NL.20: do not write `return 0;` at the end of the `main` function

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#182]
# NL.20: do not write `return 0;` at the end of the `main` function

## Reason

Because the Standard adds this for you (see references 1 and 2). Earlier `return`s are just fine.

## Example

```
int main() 
{
  return 0; //Unnecessary
} 
```

```
int main() {} //OK
```

```
int main() 
{
  //
  if (is_already_done) return 0; //OK: Earlier return
  //
} 
```

## Exceptions

Earlier returns are fine.

## Enforcement

Let the compiler generate a warning when the last line of `main` is `return 0;`.

## See alsos

None

## Notes

None

## Discussion

See references

## References

 * [1] C++. International Standard. ISO/IEC 14882. Second edition. Paragraph 3.6.1.5
 * [2] Working Draft, Standard for Programming Language C++. International Standard. ISO/IEC document number N3936. 2014-08-22. Paragraph 3.6.1.5

**Comment by rafzi** [comment]
Note on the enforcement part: A last line of "return 0;" could be preceded by a conditional "return non-null;" and then I would argue it's more clear to keep "return 0;" at the end.

More formal than "last line": "first unconditional return 0 statement".

**Comment by hsutter** [comment]
This rule seems more aesthetic. Perhaps it belongs with indentation rules? We don't know of programs where this would diagnose bugs, ones that are errors because of `return 0;` at the end of `main`. We are not sure what problem the rule would solve.
