### ISSUE TITLE
C.183 makes a too-general statement about whether reinterpret_cast to an unrelated type is defined behavior

### ISSUE THREAD

**Issue by mjbeardsley** [isocpp/CppCoreGuidelines#1823]
A sentence in C.183 states, `Accessing the result of a reinterpret_cast to a type different from the object’s declared type is defined behavior.`
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c183-dont-use-a-union-for-type-punning

It's true that it's defined behavior in the example code that's right above that statement, but only because it's casting to `unsigned char`:
`auto p = reinterpret_cast<unsigned char*>(&x);`

But that's more the exception than the rule, e.g. casting to a different non-character type would introduce UB (strict aliasing violation), e.g.:
`auto p = reinterpret_cast<float*>(&x);`
even though that now-UB cast is also "accessing the result of a reinterpret_cast to a type different from the object’s declared type"

I think it'd be helpful if that sentence in C.183 could be more specific or clarified, because as-written it could be taken out of context as an incorrect justification for code that's really UB

For reference, from the cppreference reinterpret_cast doc:
https://en.cppreference.com/w/cpp/language/reinterpret_cast

"The purpose of strict aliasing and related rules is to enable type-based alias analysis, which would be decimated if a program can validly create a situation where two pointers to unrelated types (e.g., an int* and a float*) could simultaneously exist and both can be used to load or store the same memory (see this email on SG12 reflector). Thus, any technique that is seemingly capable of creating such a situation necessarily invokes undefined behavior.

When it is needed to interpret the bytes of an object as a value of a different type, std::memcpy or std::bit_cast (since C++20)can be used:"

And also the "Type aliasing" section of the same doc page which states "Whenever an attempt is made to read or modify the stored value of an object of type DynamicType through a glvalue of type AliasedType, the behavior is undefined unless" ... [among other cases] ... "AliasedType is std::byte (since C++17), char, or unsigned char`"

**Comment by daviddetweiler** [comment]
There's also [this](http://open-std.org/JTC1/SC22/WG21/docs/papers/2019/p1839r2.pdf) paper; as of C++20, `reinterpret_cast`-based object representation access of the kind in the example is actually completely undefined.

**Comment by hsutter** [comment]
Editors call: Thanks! We think the example should be updated to use `std::byte*`, and the text updated to specify the three types that are legal to cast to (`char*`, `unsigned char*`, and `std::byte*`).
