### ISSUE TITLE
Guidance on `auto*` vs `auto`

### ISSUE THREAD

**Issue by bandrews-spirent** [isocpp/CppCoreGuidelines#1825]
Should we have guidance on which one is preferred when dealing with pointers? i.e.
```
thing* get_thing()
{
    return t;
}
```

`auto* p = get_thing();`
vs
`auto p = get_thing();`

Which is preferred? Would love to see a new guideline about this or add to existing guideline. 
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es11-use-auto-to-avoid-redundant-repetition-of-type-names

**Comment by hsutter** [comment]
Editors call: We view this as a style issue, but if you want to emphasize that the object is a pointer the code author could use a `Pointer` concept.
