### ISSUE TITLE
GSL.view: Do not advice to use `char*` after suggesting `span` earlier

### ISSUE THREAD

**Issue by JohelEGP** [isocpp/CppCoreGuidelines#1826]
The immediate paragraphs surrounding the definitions of `zstring` and `czstring` seem to provide conflicting suggestions.

In the preceding paragraph:
> A `char*` that points to more than one `char` but is not a C-style string (e.g., a pointer into an input buffer) should be represented by a `span`.

In the following paragraph:
> A sequence of characters that is not assumed to be zero-terminated should be a `char*`, rather than a `zstring`.

`char*` is enforced to be a pointer to a single `char` object.

**Comment by swang206** [comment]
The problem is that std::span has abi issues which is completely unacceptable.

**Comment by JohelEGP** [comment]
That's unrelated. The problem is that is that it's saying you _should_ use `char*` for a non-zero terminated sequence of characters. `char*` and all other pointers (with the exceptions of other type aliases the guidelines introduce to specifically mean other things) are supposed to point to a single object or its type or be `nullptr`.

**Comment by swang206** [comment]
> That's unrelated. The problem is that is that it's saying you _should_ use `char*` for a non-zero terminated sequence of characters. `char*` and all other pointers (with the exceptions of other type aliases the guidelines introduce to specifically mean other things) are supposed to point to a single object of its type or be `nullptr`.

For me, it is more like the C++ iostream problem which treats char const* as a string.

**Comment by hsutter** [comment]
Editors call: Fixed, thanks!
