### ISSUE TITLE
Typo in "Using the GSL: A Tutorial and FAQ"

### ISSUE THREAD

**Issue by char-lie** [isocpp/CppCoreGuidelines#1827]
Duplicated `is` is redundant in [Iteration: "How do I iterate over a span?"](https://github.com/isocpp/CppCoreGuidelines/blob/6dd14321c1eb01eaa4543b2d4d2b8ed0e80ddda8/docs/gsl-intro.md#iteration-how-do-i-iterate-over-a-span)

> A `span` supports range-`for` -- note this is zero-overhead and does not need to perform any range check, because the range-`for` loop **is is** known by construction not to exceed the range's bounds:

**Comment by char-lie** [comment]
https://github.com/isocpp/CppCoreGuidelines/pull/1828

**Comment by cubbimew** [comment]
yes, thanks - merged your PR
