### ISSUE TITLE
Suggestion: I.27: Use assert for self-checking and documentation

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#183]
# I.27: Use assert for self-checking and documentation

## Reason

The `Expects` and `Ensures` macros are useful as a self-check and documention of the (member) functions
and are located at the beginning and end of these.

For other self-checks and documentation inside these functions, use assert (see references 1-7).

## Example

```
int f(const int x) 
{
  //Work here, with Expects

  std::vector<int> v = { /* something */ };
  const int i{/* something */}; //Chose a random index in v
  assert(i >= 0 && i < static_cast<int>(v.size());
  v[i] = 42; //Should always work (so no use of v.at possible)

  //Work here, with Ensures
} 
```

## Exceptions

asserts can be redundant.

## Enforcement

None

## See alsos

None

## Notes

None

## Discussion

See references

## References

 * [1] Herb Sutter, Andrei Alexandrescu. C++ coding standards: 101 rules, guidelines, and best practices. ISBN: 0-32-111358-6. Chapter 68: 'Assert liberally to document internal assumptions and invariants'
 * [2] Bjarne Stroustrup. The C++ Programming Language (3rd edition). 1997. ISBN: 0-201-88954-4. Advice 24.5.18: 'Explicitly express preconditions, postconditions, and other assertions as assertions'
 * [3] Steve McConnell. Code Complete (2nd edition). 2004. ISBN: -735619670. Chapter 8.2 'Assertions', paragraph 'Guidelines for using asserts': 'Use assertions to document and verify preconditions and postconditions'
 * [4] Steve McConnell. Code Complete (2nd edition). 2004. ISBN: -735619670. Chapter 8.2 'Assertions', paragraph 'Guidelines for using asserts': 'Use assertions for conditions that should never occur'.
 * [5] Jesse Liberty. Sams teach yourself C++ in 24 hours. ISBN: 0-672-32224-2. Hour 24, chapter 'assert()': 'Use assert freely'
 * [6] John Lakos. Large-Scale C++ Software Design. 1996. ISBN: 0-201-63362-0. Chapter 2.6: 'The use of assert statements can help to document the assumptions you make when implementing your code
 * [7] Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 30.5. Advice. page 884: '[13] Use static_assert() and assert() extensively'

**Comment by hsutter** [comment]
We are interested in an assertion mechanism, but are waiting for discussions in the standards committee to finalize before we move on this. We don't want to go in the direction of C `assert` here because if we get contracts assert is likely to be a different mechanism.

**Comment by AndrewPardoe** [comment]
Discussed 21 Dec 2015.

**Comment by hsutter** [comment]
This is a good point but we should close this issue as it will be covered when the committee decides on a contracts design (we're not going to forget to cover this then so we don't need to keep this issue as a reminder).
