### ISSUE TITLE
"ES.27: Use std::array or stack_array for arrays on the stack" is false

### ISSUE THREAD

**Issue by swang206** [isocpp/CppCoreGuidelines#1830]
The problem is that std::array is not provided in the freestanding C++ environment, which means if you use std::array you are going to lose portabilities.

The same problem goes with std::addressof, std::move, std::forward.
C++ freestanding standard:
https://en.cppreference.com/w/cpp/freestanding
see video:
https://youtu.be/DorYSHu4Sjk

Other problems like using std::array to store tables (like for ryu/dragonbox table), it is extremely hard to do that (because they are arrays of 2d for example) and it hurts compilation speed extremely.

This means there are still a lot of legitimate reasons to use C-style arrays. Like C-style arrays forbid zero-size arrays which might be useful.

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slcon1-prefer-using-stl-array-or-vector-instead-of-a-c-array 
This has the same issue without mentioning pitfalls. std::vector will NEVER EVER be in freestanding C++ which means you have to ban it forever for a library that is designed to be maximumly portable

**Comment by MikeGitb** [comment]
I don't think the CppCoreGuidelines are designed with an eye towards freestanding/embedded systems, even though you can probably apply most rules there too.

That being said: I tend to avoid `std::array` even in "normal" code more often than I'd like to admit (mainly for member variables) exactly because (especially on old compilers) it can impact compilation speed, code gen and the ability to make code constexpr.

I think as with any general guideline, you can't cover every possible scenario and if you have special requirements, then you have to adapt the guidelines for your use-case.

**Comment by swang206** [comment]
> I don't think the CppCoreGuidelines are designed with an eye towards freestanding/embedded systems, even though you can probably apply most rules there too.
> 
> That being said: I tend to avoid `std::array` even in "normal" code more often than I'd like to admit (mainly for member variables) exactly because (especially on old compilers) it can impact compilation speed, code gen and the ability to make code constexpr.
> 
> I think as with any general guideline, you can't cover every possible scenario and if you have special requirements, then you have to adapt the guidelines for your use-case.

Most of the C++ core guidelines are very bad in my opinion. Like, avoid unsigned integers. Use smart pointers. Prefer exceptions etc. They are very bad even in real-world code.

It is so bad that I frequently see people abuse unique_ptr for things like std::unique_ptr<FILE,std::function<decltype(fclose)*>>, instead of writing a new c_file class.

C++ core guidelines have doomed to Google C++ Coding Style 2.0.

I am talking about the general case. Using std::array is very bad even for the general cases since it loses portability silently without even mentioning anything about freestanding.

**Comment by jwakely** [comment]
If they're so bad, why even bother commenting here? Do you expect to change anything with silly hyperbole like that?

**Comment by MikeGitb** [comment]
> I am talking about the general case. Using std::array is very bad even for the general cases since it loses portability silently without even mentioning anything about freestanding.

Best I can tell, freestanding isn't the general case at all (even most embedded toolchains I have worked with in the last 5 years offer much more than just freestanding). 
And in my experience: when you have restrict yourself to the freestanding subset , std::array is the least of your problem. Restricting the core guidelines to freestanding would imho make them significantly less usefull for most c++ projects that don't have to work under those restrictions.

> It is so bad that I frequently see people abuse unique_ptr for things like std::unique_ptr<FILE,std::function<decltype(fclose)*>>, instead of writing a new c_file class.

I don't think the guidelines would favor that use of unique_ptr, but if they do: Maybe you can point to the specific rule that should be updated

**Comment by jwakely** [comment]
Yeah, that's just bad code, nothing to do with the guidelines. Nothing in the guidelines says you need to wrap a function pointer in a `std::function` to make it callable. Please try harder to make your criticism useful.

There is no reason `std::array` couldn't be available in freestanding, and there are proposals to fix that.

**Comment by jwakely** [comment]
N.B. it looks like swang206 is the latest incarnation of the anonymous insult generator behind #1630 and #1584

**Comment by swang206** [comment]
> Yeah, that's just bad code, nothing to do with the guidelines. Nothing in the guidelines says you need to wrap a function pointer in a `std::function` to make it callable. Please try harder to make your criticism useful.
> 
> There is no reason `std::array` couldn't be available in freestanding, and there are proposals to fix that.

std::unique_ptr<FILE,decltype(fclose)*> is not good either. In fact, libcxx does something like this too. You can argue it can be optimized away from compiler, but you have to be extremely careful and they might have other side effects you wouldn't expect.
In general, i would argue the custom deleter of unique_ptr should be just deprecated in general.
https://github.com/llvm/llvm-project/blob/1ef62cb20028fb7b75c65badcafec8c4703cbda3/libcxx/include/fstream#L694

No reason for std::move, std::forward, std::addressof could be available in freestanding either. The problem is that we are not at that point. For me, I have to use __builtin_addressof for getting the address of any object all the time because std::addressof does not exist and & might be overloaded.

The proposal of fixing freestanding C++ would take a huge amount of time before it is actually available. (I guess even C++26 might not fix it.) Who knows what could happen 10 years later? Maybe C++ would have been dead considering WG21 refuses to break abis etc.

At the current point, the safest thing to ensure portability is to avoid all non-freestanding headers, std::move, std::addressof, std::forward, etc. Virtual functions have to be banned too since itanium ABIs require __cxa_pure_virtual() which would bloat binary size. -fno-exceptions -fno-rtti -fno-unwind-tables -fno-asynchronous-unwind-tables are also your friends.

**Comment by jwakely** [comment]
> At the current point, the safest thing to ensure portability is to avoid all non-freestanding headers

Portability to both freestanding and hosted environments is only a concern for a **tiny** fraction of C++ code.

The **vast** majority is explicitly written for one *or* the other, not both. And so this notion of "portability" is useless to most C++ users.

**Comment by jwakely** [comment]
And when you start with "ban virtual functions" ... well, this is just laughable. Can we close this, as another unproductive rant that isn't going to improve the guidelines in any way?
