### ISSUE TITLE
Question about public data members in `class` 

### ISSUE THREAD

**Issue by hg-zt** [isocpp/CppCoreGuidelines#1838]
Are public data members in `class` discouraged?

For example, `clang-tidy` warns that all public data members in classes are violating `cppcoreguidelines-non-private-member-variables-in-classes`. I can't find the exact rule but it seems to be related to
-  [C.9: Minimize exposure of members](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c9-minimize-exposure-of-members) 
> Enforcement
Flag mixtures of public and private data" 
- [C.2: Use class if the class has an invariant; use struct if the data members can vary independently](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c2-use-class-if-the-class-has-an-invariant-use-struct-if-the-data-members-can-vary-independently)
> Enforcement
Look for structs with all data private and classes with public members.

Meanwhile we have [C.131: Avoid trivial getters and setters](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c131-avoid-trivial-getters-and-setters) which suggests making some simple data members public.

I think exposing these "property-like" data members makes perfect sense while other internal states are private.

**Comment by raceychan** [comment]
> Editors call: We think the current rules say the right things... In our experience, classes with mixed accessibility are more often than not badly designed and become a maintenance burden, and we don't want to encourage that possibility.

are you saying that:
1. all member variables inside a class should share a same accessibility
2. that accessbility has to be private.

i have been searching around for the reasoning and do not have enough luck, would you mind explain a little on the second point?

**Comment by jwakely** [comment]
No, the guidelines do not say all data members must be private. Having them all public is OK, all-private is OK. A mixture of the two is not OK. If clang-tidy has a silly interpretation of that, report it to clang-tidy maintainers.

**Comment by jwakely** [comment]
> To me that sounds like a pretty big undocumented caveat on C.131. If two rules give contradictory advice in a specific case isn't it worth clarifying, in the rule which doesn't apply in that case, that it's an exception?

Yes, it seems like C.131 should have an exception for the case where one or more private data members has **non-trivial** getters or setters, because then all members should be private.
