### ISSUE TITLE
Add rule against throwing 'new' exceptions

### ISSUE THREAD

**Issue by bgloyer** [isocpp/CppCoreGuidelines#1848]
Should there be a rule against throwing dyanamically allocated exceptions?

I have seen this mistake made by people both new to C++ and people who frequently switch between languages.

````
    throw new runtime_error{"boing!"};  // bad
    throw runtime_error{"boing!"};      // good
````
Are there any valid reasons to throw ```new``` exceptions?

**Comment by cubbimew** [comment]
I suspect it would be against one of the many rules about raw pointers, but "throw by value" was indeed a popular standalone rule that may be worth adding.
* https://isocpp.org/wiki/faq/exceptions#what-to-throw in the Super-FAQ
* Item 73 "throw by value, catch by reference" in the Sutter/Alexandrescu guidelines book
(these guidelines already have the "catch by reference" part)

**Comment by jwakely** [comment]
> Are there any valid reasons to throw `new` exceptions?

It's necessary if you need to throw something that is not copy constructible or not destructible. But there are no valid reasons to do that. Just use a more suitable type for your exceptions.

**Comment by jwakely** [comment]
I don't think the new example makes it clear just how wrong this is.

       try {
            // ...
            throw new widget{}; // don't: throw by value not by raw pointer
            // ...
        }
        catch (base_class e) {  // don't: might slice
            // ...

It's not clear just from the example that the handler won't even match when a pointer is thrown.

I think it would be better to have a separate "bad" example specific to this, or just mention it in prose, don't try to recycle and existing example to caution against this in passing.
