### ISSUE TITLE
Add rule regarding repeating return type in return statement?

### ISSUE THREAD

**Issue by reddwarf69** [isocpp/CppCoreGuidelines#1850]
When reviewing code like
```
ClassWithLongName func()
{
  ...
  return ClassWithLongName{};
}
```
I see duplication and ask myself why the author decided to write that painful long name twice. Surely there must be a reason. Did I misread it? Is it a derived type? Slicing warning! ...
I see something strange and end up wasting time looking at the line with more detail than needed. So IMHO it's not a purely stylistic decision.

I couldn't see any rule about preferring `return {};`. Should there be one?

**Comment by jwakely** [comment]
You can't do that if the constructor is `explicit`, so I don't think making it a guideline is a good idea. It's not universally applicable, sometimes the name is needed, and even if it isn't needed, the name doesn't really do any harm.

**Comment by reddwarf69** [comment]
Well, it's duplication, it does the usual harm duplication does.
But fair point about the explicit part. Probably only with that "exception" the guidelines would end up too convoluted.

I'm going to close it.
