### ISSUE TITLE
Add clarification/examples for types of exceptions in E.14

### ISSUE THREAD

**Issue by bgloyer** [isocpp/CppCoreGuidelines#1852]
Add examples and clarify what kinds of exceptions should and shouldn't be thrown in [E.14](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-exception-types).

Maybe a list like below along with a short explanation of each case?

        class MyException : public std::runtime_error
        {
        public:
            MyException(const string& msg) : std::runtime_error(msg) {}
            // ...
        };
    
        class MyCustomError {};  // not derived from std::exception
 
        enum class alert {RED, YELLOW, GREEN};
 
        // ....

        // This is the best case?  It can be caught by something expecting
        // MyException or generally through std::exception
        throw MyException{"something bad"};  // good

        // Is this allowed under E.14?  I think this is common. It makes sense if
        // there is not much info to add at the point of detection.  There are cases
        // where callers would only care if the call was successful or not. 
        throw std::runtime_error("someting bad"); // good?

        throw std::invalid_argument("i is not even"); // good?

        throw std::exception{}; // bad - no info

        // When should types not derived from std::exception be thrown?
        throw MyCustomError{};  // good?

        throw 7; // bad

        throw "something bad";  // bad

        throw alert::RED; // ???

Also at the bottom the "See also: Discussion" link is broken.

**Comment by cubbimew** [comment]
The "Discussion" link is a ???, meaning it needs to be written; perhaps this issue can generate enough discussion?

An extra-interesting case is throwing a "purpose-designed user-defined type" that is not a class type; an enum/enum class

**Comment by bgloyer** [comment]
> The "Discussion" link is a ???, meaning it needs to be written; perhaps this issue can generate enough discussion?
> 
> An extra-interesting case is throwing a "purpose-designed user-defined type" that is not a class type; an enum/enum class

I added an enum class to the list

**Comment by cubbimew** [comment]
Editor's meeting: It is good to say that `int` and `string` are bad examples and enum class and `MyCustomError`, especially `class final MyCustomError{}`, are good examples. Both classes derived from std::exception and concrete classes are acceptable uses. A pull request would be welcome.

**Comment by cubbimew** [comment]
closed with https://github.com/isocpp/CppCoreGuidelines/pull/1857
