### ISSUE TITLE
Alternative operators

### ISSUE THREAD

**Issue by Daguerreo** [isocpp/CppCoreGuidelines#1853]
There are guidelines about the usage of the alternative operators? If they are discouraged, what should be the reason now? Could be interesting a section about these?

**Comment by cubbimew** [comment]
Editor's meeting: Could you please make a more precise statement of the problem and a suggested guideline?

**Comment by Daguerreo** [comment]
Alternative operators do exists as language feature and are not planned to be deprecated. So a legitimate question could be "can be used these in our codebase?". For someone can be intriguing to make the code more pythonish. My thought is that should be avoided because they don't really increase readability for complex statement and can lead to a mixed codebase style (standard and alternative). In addition the AO are there just for retro compatibility so there's no actual reason to use it. But honestly it sounded to myself just a matter of opinion and personal preferences, then I started looking for guidelines but out there are no topic about this. I have not a suggested guidelines because I'm the first one looking for a guideline, though my opinion is which should be avoided. But as I sad early, it's just a personal opinion.

**Comment by jwakely** [comment]
> In addition the AO are there just for retro compatibility

Why do you say that? I don't think that's true.

> But honestly it sounded to myself just a matter of opinion and personal preferences

Yes.

They have benefits, like making it harder to confuse `and` and `bitand`.

Apart from leading to mixed styles in a codebase, the biggest argument against them seems to be that you can misuse them for silly declarations like `void foo(int bitand)` and `void bar(T and)` ... but just don't do that.

**Comment by MikeGitb** [comment]
I think the biggest argument against them is that some devlopers are simply not aware of them and might be confused when they first see them the frist time. But learning of their existance is a (small) one time cost.

**Comment by cubbimew** [comment]
For myself, I'd love to experiment with using them consistently if they were themselves consistent, but they aren't; in particular there is a `not_eq`, but no `eq`

**Comment by hsutter** [comment]
Editors call: We don't have consensus for a rule. At this point we don't have enough data to ban them or recommend them.
