### ISSUE TITLE
About P.1: Express ideas directly in code

### ISSUE THREAD

**Issue by tuchang** [isocpp/CppCoreGuidelines#1856]
Why should we express the idea in defining types instead of variable names?
```
change_speed(Speed s); 
change_speed(Delta d); 
```
instead of 
```
change_speed(double speed); 
change_speed(double delta); 
```

**Comment by beinhaerter** [comment]
Your solution would not work because you have two overloads with the same signature.
Even if it did work, to see the difference you would need to look at the function declaration and at the variable names. With the encoding in the types you directly see the difference at the call site.

**Comment by tuchang** [comment]
> Your solution would not work because you have two overloads with the same signature. Even if it did work, to see the difference you would need to look at the function declaration and at the variable names. With the encoding in the types you directly see the difference at the call site.

Thanks.

**Comment by tuchang** [comment]
> Your solution would not work because you have two overloads with the same signature. Even if it did work, to see the difference you would need to look at the function declaration and at the variable names. With the encoding in the types you directly see the difference at the call site.

I tried 
```
typedef double Speed;
typedef double Delta;
change_speed(Speed s); 
change_speed(Delta d); 
```
They also can not work at the same time. Because Speed and Delta area actually both recognized as double in compilation.
I think we are just using one of them.

I understand that, at the call site, we can not know variable names at declaration. But it seems we cannot directly know the customized type at call site as well. We can still pass double variable.
And if we can define a proper named type to the call site, we can also define a proper named variable to the call site.

**Comment by BenBE** [comment]
Going with the above example you could go about this using POD as wrappers around those raw types so you got:

```cpp
class Speed { double s; };
class SpeedDelta { double d; };
```

You could then go ahead with your signatures for both functions like this:

```cpp
void change_speed(const Speed& s);
void change_speed(const SpeedDelta& d);
```

Which would force you to specify which of the two signatures you were talking about at the call site:
```cpp
change_speed(SpeedDelta{-42});
```

And while this may look like a good thing to do it actually litters your namespace with dozens of additional types you have to implement. A much easier approach, depending on the situation IMO is by properly naming things:

```cpp
void change_speed_to(double s);
void change_speed_by(double d);
```

Even has the benefit of allowing backwards-compatibility to plain C if you were to offer this in your library for some reason.

**Comment by tuchang** [comment]
> Going with the above example you could go about this using POD as wrappers around those raw types so you got:
> 
> ```c++
> class Speed { double s; };
> class SpeedDelta { double d; };
> ```
> 
> You could then go ahead with your signatures for both functions like this:
> 
> ```c++
> void change_speed(const Speed& s);
> void change_speed(const SpeedDelta& d);
> ```
> 
> Which would force you to specify which of the two signatures you were talking about at the call site:
> 
> ```c++
> change_speed(SpeedDelta{-42});
> ```
> 
> And while this may look like a good thing to do it actually litters your namespace with dozens of additional types you have to implement. A much easier approach, depending on the situation IMO is by properly naming things:
> 
> ```c++
> void change_speed_to(double s);
> void change_speed_by(double d);
> ```
> 
> Even has the benefit of allowing backwards-compatibility to plain C if you were to offer this in your library for some reason.

Thanks. 
`_to` and `_by` would be good approaches.
