### ISSUE TITLE
Rules ES.6 and ES.74 look the same

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1858]
Rule ES.6 states "Declare names in for-statement initializers and conditions to limit scope", whereas rule ES.74 is about "Prefer to declare a loop variable in the initializer part of a for-statement". What is the difference? To me they are very similar and could be merged. Or am I missing something?

**Comment by hsutter** [comment]
Editors call: You're right, there's a lot of duplication here. We'll take a look at merging and having one refer/redirect to the other. Thanks!
