### ISSUE TITLE
struct and class ambiguity

### ISSUE THREAD

**Issue by mambu** [isocpp/CppCoreGuidelines#186]
Hello,

I would like to raise a discussion on two keywords that can be used for the same purpose but with one exception: struct and class.
Also refer to section C.2 of the guidelines "Use class if the class has an invariant; use struct if the data members can vary independently" which touches on the using struct and class for different purposes (and avoid overlapping).

What I have always found annoying and confusing is that we can have two words to do the same thing with one exception: struct must be used if you want to define a "C" POD. Therefore my suggestion is to assign clear meanings to the two keywords:
  * struct: "C" POD only (that allows the compiler to do validations)
  * class: the same meaning it has now

Also I believe it is a good practice to always mark sections inside a class with their access specifier (public, protected or private) anyway so there should not be any savings on typing when using struct.

Benefits:
  * clear purpose of every keyword
  * no overlapping between the two
  * compiler can verify compatibility with "C" POD when using struct
    * software can evolve and change, but something that you created as a POD will never lose this property (for instance adding a virtual method, which is something that can be done in C++)
    * better interoperability with C libraries
  * other OOP languages have one keyword only (and probably that is "class")

Any thoughts?

Marco

**Comment by richelbilderbeek** [comment]
I do agree with your reasoning. I do think the rule you propose is easier to implement.

When I read the rule to the letter, `use struct if the data members can vary independently`, then you should mark a class with one data member also `struct`. Also, one has to understand a class its workings, before one can label it `struct` or `class`.

A third alternative rule would be: `use struct if the data has no invariants`, e.g. a `struct Coordinat {};` but not `struct PrimeNumber{ PrimeNumber(const int i) {} };`.

Personally, I like all three rules equally, and I'd be happy is one is (s)elected being the favorite.

**Comment by gdr-at-ms** [comment]
Both `struct` and `class` introduce data types.
It is quite reasonable to define a class type with `struct` where private members are listed need the end in the `private` section, while public members (usually functions) are listed first with no need for `public` label.  Ultimately, this is a case where an organization or team would refine the Core Guidelines with more restrictive rules.

**Comment by cubbimew** [comment]
> struct must be used if you want to define a "C" POD
POD types can use both class and struct keywords. What's a "C" POD?

**Comment by mambu** [comment]
Maybe POD is just enough... A Plain Old Data is basically a struct in C. See http://www.cplusplus.com/reference/type_traits/is_pod/ for a brief description of a C++ POD.

Therefore my suggestion to use struct for a "struct POD", since class is enough for the rest.

**Comment by avakar** [comment]
Since there's a recommendation to put public members first, I question the value of `class` keyword. Why not use `struct` always?

**Comment by gdr-at-ms** [comment]
History.  A new keyword was key in getting the basic ideas of encapsulation and abstract data type across, when the language was born.  To many, that still is the case today.

On Sep 29, 2015, at 5:35 AM, Martin Vejn?r <notifications@github.com<mailto:notifications@github.com>> wrote:


Since there's a recommendation to put public members first, I question the value of class keyword. Why not use struct always?

-

**Comment by galik** [comment]
**P.1: Express ideas directly in code**

To me the word `struct` implies *structured data* and it was historically about *aggregating* plain data. But *class* has the connotation of a *class* of data that follows the same (or similar) patterns of *behaviour*.

So, to me, a `struct` is a good way to express a (pure) data object whereas a *class* is a good way to express *behaviour* through an encapsulated entity were the specifics of the data are hidden.

Its not so much about whether or not one keyword can substitute for another as which keyword expresses which idea most directly.

**P.1: Express ideas directly in code**

**Comment by gdr-at-ms** [comment]
There is little actionable items that can be added to the existing guidelines on this specific issue.

**Comment by mambu** [comment]
Hi,

I disagree with this:

> There is little actionable items that can be added to the existing guidelines on this specific issue.

because we already have section C.2 in the guidelines that deals with this distintion.

> Use class if the class has an invariant; use struct if the data members can vary independently

That guideline is exaclty what I wanted to suggest. However I believe we are still missing another reason why we want it. 
The C++ language allows compatibility with C via [POD](http://en.cppreference.com/w/cpp/concept/PODType) using `struct` or `class`. However POD have special requirements (note that in C++11 an `std::is_pod` type trait was added to check whether a type is a POD).
Using `struct` (and only `struct`) for POD and `class` for everything else will make the code clearer and unambiguous (for instance, you should never add a virtual destructor to a `struct`, since that struct may have been used as POD somewhere else in the code).

To me it would have been much better if we only had had `class` for classes (to implement object oriented behaviour) and struct for POD, but this is not going to change in the language itself, therefore the guidelines seem to me the best place to highlight and hopefully standardise this behaviour.

Marco

**Comment by gdr-at-ms** [comment]
Note that "POD" has lost any practical meaning since C++11.  The predicate `std::is_pod` type trait is now largely viewed as a mistake.  Anytime you want to apply it, there is almost always a better predicate for the scenario you're considering.
