### ISSUE TITLE
Add rule ES.xx: Use the ternary operator '?' for conditional initialization

### ISSUE THREAD

**Issue by peno2** [isocpp/CppCoreGuidelines#1860]
_I suggest to add a rule that explicitly mentions the use of the ternary operator '?', since using '?' in many cases can make the code a lot simpler compared to using a lambda expression or some initialization function._
.
.
.
Use the ternary operator '?' for conditional initialization, in particular when the condition is simple enough to not justify the added complexity of using a lambda expression ([ES.28](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es28-use-lambdas-for-complex-initialization-especially-of-const-variables)). An important benefit of fully initializing an object is that it can be const-declared if so desired (see also [ES.25](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es25-declare-an-object-const-or-constexpr-unless-you-want-to-modify-its-value-later-on)).

**Example**
Here is an example that is often considered to demonstrate the difficulty to initialize objects direcltly at declaration.

```
widget w1;    // "widget" a type that's expensive to initialize, possibly a large POD
widget w2;

if (cond) {  // bad: w1 and w2 are initialized "late"
    w1 = f1();
    w2 = f2();
}
else {
    w1 = f3();
    w2 = f4();
}
```
Using the ternary operator '?' this can be rewritten to initialize both w1 and w2 at the time of declaration:

```
// good, properly initialized right away, may also be const now, if so desired
const widget w1 = cond ? f1(): f3();
const widget w2 = cond ? f2(): f4();
```
Or, as a matter of style, if this communicates the intent better, initialize both 'w1' and 'w2' in one single statement:

```
using std::pair;
const auto [w1,  w2]  = cond ?  pair{f1(), f2()}:  pair{f3(), f4()};    // C++17
```
.
.
.
_Now, if the above suggestion is accepted some questions arises. How shall we handle ES.20 and ES.21 which both overlaps with the suggested rule to some extent?_

**Comment by BenjamenMeyer** [comment]
Honestly, after decades of programming I find the ternary operator to be more of a hindrance to reading code than a useful construct with the exception of the extremely simple boolean cases. For readability it's often better to use an IF-block instead.

NOTE: ternary operators is an excellent tool for code obfuscation.

That said, it would be good to have a proper example here in the guidelines for when to use the ternary operator and emphasize its limited use to these simple case.

**Comment by peno2** [comment]
> Honestly, after decades of programming I find the ternary operator to be more of a hindrance to reading code than a useful construct with the exception of the extremely simple boolean cases. For readability it's often better to use an IF-block instead.
> 
> NOTE: ternary operators is an excellent tool for code obfuscation.
 
Ok, I understand that people can write bad code mis-using the ternary operator.
Maybe we should add another rule: "Do not use ternary operator when an if-else would be clearer".
The reason that I suggested this rule in the first place was that I came across some coding rules that prohibited
use of '?'.

> That said, it would be good to have a proper example here in the guidelines for when to use the ternary operator and emphasize its limited use to these simple case.

So, do you find my suggested rule good or bad, or in need for improvement?
If you have any suggestions for improvements I will try to adapt.

Should I add some text about the importance of not using '?' to obfuscate code?
I think that my suggesed rule illustrates well, when you should use a ternary operator instead of an if-else.

**Comment by shaneasd** [comment]
what is the relative merit of
```
using std::pair;
const auto [w1,  w2]  = std::invoke([&]{if (cond){ return pair{f1(), f2()}: } else { return pair{f3(), f4()}; }}    // C++17
```
?

If you like if over ? then an immediately invoked lambda is the way to do it as far as I can see. You mention added complexity but I'm not sure it's that much more complex. Perhaps there is a different example where the complexity is worse or perhaps the brevity offered by the ? justifies the use of a whole additional syntax? Personally I don't have a strong opinion either way and would happily use either but I'm curious if there is a reason one is objectively better.

**Comment by BenjamenMeyer** [comment]
> So, do you find my suggested rule good or bad, or in need for improvement?
> If you have any suggestions for improvements I will try to adapt.

It's a good idea provided:
- it emphasizes the limited use cases
- it warns against misuse

Having good examples of when to use and when not to use would be a good thing.

**Comment by jwakely** [comment]
Introducing structured binding, `std::invoke`, and an immediately invoked lambda just to avoid the conditional operator seems horrendous.

**Comment by BenjamenMeyer** [comment]
> If you like if over ? then an immediately invoked lambda is the way to do it as far as I can see. You mention added complexity but I'm not sure it's that much more complex. Perhaps there is a different example where the complexity is worse or perhaps the brevity offered by the ? justifies the use of a whole additional syntax? Personally I don't have a strong opinion either way and would happily use either but I'm curious if there is a reason one is objectively better.

The ternary operator is best for the simplest of assignments:
```c++
bool x = some_simple_expression ? simple_answer_A : simple_answer_B;
```
Where an `if` statement is best for:
```c++
bool x = default_value;
if (some_expression) {
   // complex answer A calculation
   x = result_of_complex_A
} else {
   // complex answer B calculation
   x = result_of_complex_B
}
```

The use of std::pair, std::invoke as in the example:
```c++
using std::pair;
const auto [w1,  w2]  = std::invoke([&]{if (cond){ return pair{f1(), f2()}: } else { return pair{f3(), f4()}; }}    // C++17
```
is closer to the obfuscation issue I was mentioning than to a valid use of the ternary operator. It avoids the ternary operator, but obfuscates things in the process. This isn't good coding or good readability.

The point is not to avoid all uses of the ternary operator, but to use it where and when appropriate. Any rule/guidance here should help folks differentiate between that, as well as keep folks out of the obfuscation territory.

**Comment by MikeGitb** [comment]
> The use of std::pair, std::invoke as in the example:
> 
> is closer to the obfuscation issue I was mentioning than to a valid use of the ternary operator. 

Imho the main problem was that everything was cramped into one line.  The advantage of the pattern (regardless of whether you use the ternery operator or an IILE) is that you can make `x/w1/w2` const and that it becomes very explicit that the code is only there to initialize the variables and that it is the only code that does it. 

Personally I think this is one of the patterns, where the tipping point between advantages on the one hand and reduced readability on the other heavily depends on the kind of code your team is used to. That makes it difficult to give general advice about it in guidelines.

**Comment by BenjamenMeyer** [comment]
> > The use of std::pair, std::invoke as in the example:
> > is closer to the obfuscation issue I was mentioning than to a valid use of the ternary operator.
> 
> Imho the main problem was that everything was cramped into one line. The advantage of the pattern (regardless of whether you use the ternery operator or an IILE) is that you can make `x/w1/w2` const and that it becomes very explicit that the code is only there to initialize the variables and that it is the only code that does it.

yes, the one liner is an advantage, but it's also a disadvantage if that line becomes too long or too complex to read which quickly negates the advantage. The same advantage - and const-ness - can be had by using a function instead; so there are other ways to skin the cat (so to speak).

> 
> Personally I think this is one of the patterns, where the tipping point between advantages on the one hand and reduced readability on the other heavily depends on the kind of code your team is used to. That makes it difficult to give general advice about it in guidelines.

Yes that does play a lot into it, and this is certainly going to be one of the harder issues to provide general advice on. However, we should still be able to provide some general advice/guidelines on its use by focusing on the simplicity.

**Comment by peno2** [comment]
BenjamenMeyer wrote:
> However, we should still be able to provide some general advice/guidelines on its use by focusing on the simplicity.

-Agree.
I think that I did that in the original post, quote follows:
> Use the ternary operator '?' for conditional initialization, _in particular_ when the condition is simple enough to not justify the added complexity of using a lambda expression (ES.28).

Maybe I could change from "in particular" to "only".

**Comment by hsutter** [comment]
Editors call: We think this is a taste issue, and people can use `?:` if they think that is best -- we don't think we have a rule against it. But it would be too much to have a whole rule for it.
