### ISSUE TITLE
Last enforcement suggestion of rule F.20 has nothing to do with the rule

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#1862]
The synopsis of rule F.20 is "For “out” output values, prefer return values to output parameters". The last enforcement suggestion in this rule is: "Flag returning a const value. To fix: Remove const to return a non-const value instead." This enforcement has nothing to do with the intention of this rule, although is somehow related. My suggestion is to create a separate rule and move the part of this rule that is about const return values (starting at the second note) to the new rule.

**Comment by cubbimew** [comment]
In other words, you are proposing to move that note+enforcement to a separate rule "do not return const values" or perhaps "do not return a const T" to match the style of some other rules in this block
Next available spot is F.49, following several other rules about return types.

**Comment by pauljansen42** [comment]
Yes, this is what I propose. Thanks!

**Comment by hsutter** [comment]
Editors call: Thanks, this sounds good and we will follow up to add a rule.
