### ISSUE TITLE
make: Target 'default' not remade because of errors.

### ISSUE THREAD

**Issue by apenn-msft** [isocpp/CppCoreGuidelines#1864]
Can anyone help me with the following error on my [pull request](https://github.com/isocpp/CppCoreGuidelines/pull/1863)?
https://github.com/isocpp/CppCoreGuidelines/runs/4402016859?check_suite_focus=true

The diagnostic isn't too helpful:
Done processing Sd-order0.cpp
 15  X* find(set<Blob>& s, const string& str, [[maybe_unused]] Hint h) 
 16  { 
 17      #if DEBUG
 18          // a hint is used only in debug builds
 19      #endif
 20  
 21      if constexpr (Blob::MaxSize > 1000)
 22      {
 23          // a hint is used only if blobs are of a certain size
 24      }
 25  }
make[1]: *** [Makefile:15: cpplint-all] Error 1
make: *** [Makefile:104: cpplint-all] Error 2
make[1]: Leaving directory '/home/runner/work/CppCoreGuidelines/CppCoreGuidelines/scripts/build/codeblocks'
##################### Bad chars check ##################
make: Target 'default' not remade because of errors.
Error: Process completed with exit code 2.

**Comment by cubbimew** [comment]
The actual diagnostic is a little earlier in the text:
```
Rf-unused1.cpp:15:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Rf-unused1.cpp:16:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
```
this means in the code snippet that follows, lines numbered 15 and 16 end in whitespace

**Comment by apenn-msft** [comment]
Thanks, I did happen to see this, my last commits are desperate attempts at locating this whitespace but I can't for the life of me see what whitespace it's referring to. My diff lines are numbered 2849 - 2871 so I can't tell what 15 and 16 are supposed to be pointing to.

Would be nice if they actually printed the offending line.
I've gone over every single line in the diff and  didn't see any whitespace out of the ordinary.
I hope it's not VS and Git fighting over crlf vs lf

**Comment by robert-andrzejuk** [comment]
For all my text editors, I usually find a plug-in or extension, that:
- visualizes white-space at the end of lines.
- removes white-space on save

This protects me from issues like this.

**Comment by jwakely** [comment]
https://editorconfig.org/ supports removing it on save.
