### ISSUE TITLE
Suggestion: ES.86: Raw for-loops should use the minimal required conditional

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#187]
# ES.86: Raw for-loops should use the minimal required conditional

**Reason**: You can reason about what happens in the `for` loop. 

**Example**s:

```
for (int i=0; i!=10; ++i) {} //Good
for (int i=0; i<10; ++i) {} //Bad: i has expected simple behavior

for (int i=0; i<10; ++i) //Good: i changes in the for loop, may reach the value of 11
{
  //
  if (/* something */) ++i;
  //
}
```

**Alternative**s: none

**Exception**s: none

**Enforcement**: not possible

**See also**s: none

**Note**s: the `for (int i=0; i<10; ++i) {}` is widely used.

**Discussion**: strict appliance of this rule does give a benefit in the reasoning of the programmer. The cost is that if a programmer changes the flow within a for-loop he/she may also need to change the for loop conditional.

**Comment by gdr-at-ms** [comment]
The version labelled "//Bad" is pretty good, common, with no pitfall. It is stable/robust vis-à-vis changes in the loop body (which should be avoided by the way).

**Comment by richelbilderbeek** [comment]
Thanks for the expert feedback. I suggested your comment-in-between-brackets as another guideline: #189

**Comment by AndrewPardoe** [comment]
Thank you for this! @gdr-at-ms will review this issue when he makes the changes proposed in #1098.

**Comment by richelbilderbeek** [comment]
Just for the record, [here](https://github.com/isocpp/CppCoreGuidelines/issues/246#issuecomment-350841296) is stated that the for-loop version below that is 'pretty good, common, with no pitfall' has been found 'isn't just as good'.

```
for (int i=0; i<10; ++i) {} //Bad: i has expected simple behavior
```

**Comment by xtofl** [comment]
As an aside, correctness of the program is easier to prove with the minimal form: after the loop has exited, `i == 10`.  In the 'bad' case, you need a proof by induction (` i >= 10 and the previous i can't have been 10 and i can only be incremented, so it must have been 9, so the current i == 10`)

**Comment by MikeGitb** [comment]
@xtofl: I don't see, his the price for the simple case works  any different, but more importantly, I don't think you have to prove anything. Any programmer with more than a couple of days experience sees what's going on. Isn't this just overthinking the topic? 

Do we really have to have rules for such minute details? Does such a rule catch bugs or is it just bikeshedding  territory?

**Comment by JonasToth** [comment]
I think it is contraproductive to require the != in simple for loops.

If I > condition to begin with (because you have a bug somewhere) you get
into bigger trouble.
If you are doing increment by two that can easily happen.

Am 21.12.2017 6:49 vorm. schrieb "MikeGitb" <notifications@github.com>:
