### ISSUE TITLE
ES.20, suggestion for change to a simpler solution in example

### ISSUE THREAD

**Issue by peno2** [isocpp/CppCoreGuidelines#1870]
I suggest to update an example in rule [ES.20](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es20-always-initialize-an-object).
A little background:
I have already made a suggestion to add a rule advising to use the ternary operator for conditional initialization. That suggestion was turned down by the editors, see [issue 1860](https://github.com/isocpp/CppCoreGuidelines/issues/1860
). Below follows a similar suggestion, but this time it is not a new rule explicitly promoting the use of the ternary operator.

So, there is an example in rule [ES.20](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es20-always-initialize-an-object) where it is stated that "This cannot trivially be rewritten to initialize i and j with initializers. ".
Actually, in my opinion the code example can be rewritten, maybe not "trivially", but still so the code becomes very simple.
In the example there is some reasoning about using lambdas, but in my opinion it would be good to suggest the simplest possible solution, using the ternary operator. It is important to write **simple code**. Thus I find this example, as it currently stands, leading inexperienced programmers and others too, in the wrong direction, by not presenting the simplest solution possible. A solution without lambdas or initialization functions.
So here follows my suggested rewrite:

**Example**
Here is an example that is often considered to demonstrate the difficulty to initialize objects directly at declaration.
```

widget w1;    // "widget" a type that's expensive to initialize, possibly a large POD
widget w2;

if (cond) {  // bad: w1 and w2 are initialized "late"
    w1 = f1();
    w2 = f2();
}
else {
    w1 = f3();
    w2 = f4();
}
```
Using the ternary operator '?' this can be rewritten to initialize both w1 and w2 at the time of declaration:

```
// Good, properly initialized right away, may also be const now, if so desired.
const widget w1 = cond ? f1(): f3();
const widget w2 = cond ? f2(): f4();

```
Or, as a matter of style, if this communicates the intent better, initialize both 'w1' and 'w2' in one single statement:

```
using std::pair;
const auto [w1,  w2]  = cond ?  pair{f1(), f2()}:  pair{f3(), f4()};    // C++17

```

If the condition is more complicated than in the example one could use a lambda [ES.28](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-lambda-init), or even a small function dedicated for the initialization.

>Then continue with the text as it was originally, starting from: "Using a value representing "uninitialized" is a symptom of a problem and not a solution:"

**Comment by BenjamenMeyer** [comment]
> using std::pair;
> const auto [w1,  w2]  = cond ?  pair{f1(), f2()}:  pair{f3(), f4()};    // C++17

This suffers from:
- not as readable as the earlier examples you listed
- use of `auto` which means even less readability since one then has to hunt down the functions to know the types. (This is actually a really bad use of auto IMHO.)

As with your earlier Issue (#1860) I'd still suggest adding a line about cautioning the use of the ternary operator and keeping it to the simple cases.

**Comment by peno2** [comment]
@BenjamenMeyer 

An observation, maybe a bit off-topic for improving my suggestion: the 2 code examples that I suggest to replace, both contains the ternary operator, where the code could as well have been written without it, instead using if-else and early returns. So it seems like there is some general acceptance for the ternary operator. Please don't take this comment as I am trying to promote '?', I am striving for clarity and simplicity, which is my ultimate goal.

I think the text already present: "If the condition is more complicated than in the example one could use a lambda" is enough of a disclaimer.

Also, the style with 
`const auto [w1, w2] = xxxx; // C++17
` was already present, and seems to be an established style.

Anyway, would you like to see something like the following:
.
<first part of suggestion, keep as is, then rewrite the rest as below>
.
Using the ternary operator '?' the code can be rewritten to initialize both w1 and w2 at the time of declaration.
This also has the benefit that the varaibles can be declared const ([Con.1](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#con1-by-default-make-objects-immutable)).

```
// Good, properly initialized right away, may also be const now, if so desired.
const widget w1 = cond ? f1(): f3();
const widget w2 = cond ? f2(): f4();

```
Or, as a matter of style, if this communicates the intent better, a pair of widgets could be initialized in one single statement:

```
using std::pair;
const pair<widget, widget> widgets{cond ?  pair{f1(), f2()}:  pair{f3(), f4()}};

```

Take caution when using '?' and use it only for simple cases. If the condition is more complicated than in the example one could use a lambda [ES.28](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-lambda-init), or even a small function dedicated for the initialization.

>Then continue with the text as it was originally, starting from: "Using a value representing "uninitialized" is a symptom of a problem and not a solution:"

**Comment by BenjamenMeyer** [comment]
@peno2 the example I quoted in https://github.com/isocpp/CppCoreGuidelines/issues/1870#issuecomment-999029498 is not very readable IMHO since the pair stuff complicates the readability, so I'd just drop that section entirely.  I do like your addition in https://github.com/isocpp/CppCoreGuidelines/issues/1870#issuecomment-999087262 regarding the caution statement: 

> Take caution when using '?' and use it only for simple cases. If the condition is more complicated than in the example one could use a lambda ES.28, or even a small function dedicated for the initialization.

**Comment by peno2** [comment]
@BenjamenMeyer 

Ok, so a complete example as follows:


**Example**
Here is an example that is often considered to demonstrate the difficulty to initialize objects directly at declaration.
```
widget w1;    // "widget" a type that's expensive to initialize, possibly a large POD
widget w2;

if (cond) {  // bad: w1 and w2 are initialized "late"
    w1 = f1();
    w2 = f2();
}
else {
    w1 = f3();
    w2 = f4();
}
```
Using the ternary operator '?' this can be rewritten to initialize both w1 and w2 at the time of declaration.
This also has the benefit that the variables can be declared const ([Con.1](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#con1-by-default-make-objects-immutable)).
```
// Good, properly initialized right away, may also be const now, if so desired.
const widget w1 = cond ? f1(): f3();
const widget w2 = cond ? f2(): f4();
```

Take caution when using '?' and use it only for simple cases. If the condition is more complicated than in the example one could use a lambda [ES.28](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-lambda-init), or even a small function dedicated for the initialization.

>Then continue with the text as it was originally, starting from: "Using a value representing "uninitialized" is a symptom of a problem and not a solution:"

**Comment by hsutter** [comment]
Editors call: The guideline does mention an example with the ternary operator and we don't think it would be improved much by adding more about the ternary operator. We think the guideline could probably be rewritten to be more concise, at some point.
