### ISSUE TITLE
ES.32 is duplicate with NL.9

### ISSUE THREAD

**Issue by markyin** [isocpp/CppCoreGuidelines#1877]
1. [ES.32: Use ALL_CAPS for all macro names](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es32-use-all_caps-for-all-macro-names)
2. [NL.9: Use ALL_CAPS for macro names only](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl9-use-all_caps-for-macro-names-only)

the name is duplicate and the content is similar.

**Comment by shaneasd** [comment]
I think technically these are two distinct complementary rules. One is saying don't use anything but ALL_CAPS for macros and the other is saying don't use ALL_CAPS for anything that isn't a macro. However I agree it feels intuitive that these would be in a single rule which amounted to "use ALL_CAPS if and only if you're naming a macro". In particular it's odd that ES.32 wouldn't be in the naming section.

**Comment by markyin** [comment]
> I think technically these are two distinct complementary rules. One is saying don't use anything but ALL_CAPS for macros and the other is saying don't use ALL_CAPS for anything that isn't a macro. However I agree it feels intuitive that these would be in a single rule which amounted to "use ALL_CAPS if and only if you're naming a macro". In particular it's odd that ES.32 wouldn't be in the naming section.

yes. we recommand only the macro in ALL_CAPS. 
But It's not so important that we need two rules .

**Comment by hsutter** [comment]
Editors call: Thanks! We think these are written the way we intend as they're not saying the same thing. We could have written it as one "if and only if" rule, but instead we wrote it as an "if" rule and an "only if" rule.
