### ISSUE TITLE
ES.42 and std::vector?

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#1882]
Hi!

I'm reading through ES.42 and notice that the enforcement section only talks about static arrays and `std::array`.

I was wondering if there is any particular reason why `std::vector` is not considered in the enforcement? It's also very commonly used and suffers from the same unsafe indexing problems. It's even more troublesome since it can only be checked at runtime, given that the size is dynamic.

Thanks!

**Comment by dksmiffs** [comment]
The specific enforcement you reference (the second bullet) doesn't apply to
std::vector, whose indexes are not required to be compile-time constants.

Also see [R.2], [SL.con.1], and [SL.con.3] for std::vector guidance
relative to span.

**Comment by carlosgalvezp** [comment]
Thanks for the pointers, answers my questions perfectly!
