### ISSUE TITLE
Suggestion: ES.86: Avoid modifying the counter variable in raw for-loops

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#189]
[edit: follow the document its coding standard]

# ES.86: Avoid modifying the counter variable in raw for-loops

**Reason**: If You can reason about what happens in the `for` loop. 

**Example**s:

```
for (int i=0; i<10; ++i) {} //Good

for (int i=0; i<10; ++i) {
  //
  if (/* something */) ++i; //Bad
  //
}
```

**Alternative**s: none

**Exception**s: none

**Enforcement**: none

**See also**s: none

**Note**s: none

**Discussion**: Following #187

**Comment by AndrewPardoe** [comment]
Discussed 21 Dec 2015.

**Comment by hsutter** [comment]
We like it, thanks!
