### ISSUE TITLE
C.65 example code is wrong

### ISSUE THREAD

**Issue by ltimaginea** [isocpp/CppCoreGuidelines#1892]
C.65 Link: [C.65: Make move assignment safe for self-assignment](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-self)
          
![image](https://user-images.githubusercontent.com/44518077/155306195-96fa5f37-976f-40f1-8896-b23b0bddd0bc.png)

          
If someone move-assigns an object to itself, line `delete ptr;` deletes both `this->ptr` and `other.ptr` (i.e., `temp`) since `*this` and `other` are the same object. Finally, `*this` is no longer a valid object.

In my opinion, the move assignment operator **must** have a self-assignment test. The correct example code is as follows:

```cpp
// move assignment operator
HasPtr& HasPtr::operator=(HasPtr&& other) noexcept
{
    // direct test for self-assignment
    if (this == &other) return *this;
    
    // move from other.ptr to this->ptr
    T* temp = other.ptr;
    other.ptr = nullptr;
    delete ptr;
    ptr = temp;
    
    return *this;
}
```

**Comment by shaneasd** [comment]
The way I read it the whole point of that example is to show what a bad implementation would look like. However I do think that meaning is difficult to arrive at so clarity could be improved. I wonder if the example is really adding anything. The example above that appears to be the "good" example so I'm not sure another good example would help. That said, the "this line is redundant" comment is a bit confusing as it seems to contradict the rule.

**Comment by jwakely** [comment]
The example specifically says it's showing how to do it **without** a test, so adding a test to it would break the example. And the rest of the item specifically says you **should** have the test, so I agree this is a "don't do it this way" example. You need to read the whole item, not just the final example. It should be clarified to avoid that misunderstanding.

**Comment by ltimaginea** [comment]
@shaneasd

In my opinion, the class Foo's data members are standard-library container types (incl. `string`) and the `int` type, they can handle self-assignment elegantly and efficiently. That's why it has the "this line is redundant" comment.

**Comment by ltimaginea** [comment]
@jwakely 

OK, I have understood that C.65 the final example is a "don't do it this way" example.

However, it is too misleading for readers. I think the final example needs to be clearly instructed that this is a "don't do it this way" example.

**Comment by cubbimew** [comment]
see also #1649

**Comment by bgloyer** [comment]
The wording of this one is a little confusing.  The text under 'Reason' implies that ````x = std::move(x)```` should never change ````x````.  However the stl containers don't give that guarnatee so in general developers should not count on that.  The rule should just require that it is "valid but unspecified" like C.64.

The last example is just showing a way to get ````x = std::move(x)```` to work without a compare.

There is a disussion about self move at: https://ericniebler.com/2017/03/31/post-conditions-on-self-move/

**Comment by hsutter** [comment]
Editors call: We will look to see if we can make this clearer.

**Comment by hsutter** [comment]
Editors call: We will update the example to say that this is an example of code that would break without the test.

**Comment by cubbimew** [comment]
oops, as @bgloyer pointed out, the example would *not* break without the test. On self-move, it leaves this->ptr unmodified.
