### ISSUE TITLE
R.smart - Ambiguity in call-side of `unique_ptr::reset` for pointer to an resetable objects

### ISSUE THREAD

**Issue by denzor200** [isocpp/CppCoreGuidelines#1893]
Hi. I propose to consider an interesting case, probably this is one of the slippery places in the use of smart pointers.

**Example**
```
class Resetable {
public:
    void reset() {
        // some reset logic here
    }
};

auto obj = std::make_unique<Resetable>();
// ...
obj->reset();  //   switch this Resetable object to "reset" state,
               //   pointer "obj" still refers to this object

obj.reset();   // just destroy Resetable object, and set pointer to null
```

**Problem**
Two actions that are completely different in meaning (reset and delete), but syntactically they are very similar, and it is easy to confuse them.

Does core guidelines accept any proposals to solve this problem?

**Comment by denzor200** [comment]
For example, how I see a solution to this problem:
```
class Resetable {
public:
    void reset() {
        // some reset logic here
    }
};
class Empty {}; // non resetable

auto obj = std::make_unique<Resetable>();

obj->reset();             // BAD
obj->Resetable::reset();  // GOOD
obj.reset();              // BAD
obj.unique_ptr::reset();  // GOOD

auto e = std::make_unique<Empty>();
e.reset();                // GOOD
```

**Comment by sankurm** [comment]
The proposed solution does make the intent clear for when the held object is used. 
But invoking `Resettable::reset()` would not be right if the held object was a `Subclass_of_resettable` and if `reset()` was `virtual`. Calling the base class function on the derived object will be wrong.

**Comment by hsutter** [comment]
Editors call: We don't think this is a common enough case to warrant its own guideline, and we have the ability to use `.` or `->` to distinguish which object we're invoking the function on.
