### ISSUE TITLE
F.46: int is the return type for main() -- main() should return an int

### ISSUE THREAD

**Issue by lums658** [isocpp/CppCoreGuidelines#1896]
Hi -- In the example for F.46: `int` is the return type for `main()` -- `main()` does not return anything.  I suggest the example read

```c++
    void main() { /* ... */ };  // bad, not C++

    int main()
    {
        std::cout << "This is the way to do it\n";
        return 0;
    }
```

In general, I think *all* examples with a `main()` should properly return a value -- but in the guideline calling out that `main()` returns `int` it definitely should.  (There are only a handful of `main()` examples in the guidelines.)

**Comment by jwakely** [comment]
Why? The point of the guideline is that it returns `int` not `void`. It still returns `int` whether you write `return 0;` explicitly or not.

**Comment by jwakely** [comment]
> I think *all* examples with a `main()` should properly return a value

N.B. they already do "properly return a value", because the language guarantees it.

**Comment by lums658** [comment]
Ah -- I think I missed some of the fine print about `main()` being an exception to the rule that "Flowing off the end of a function is equivalent to a return with no value; this results in undefined behavior in a value-returning function."  It just struck me when reading F.46 that if `int` is the return type for `main()` then `main()` should visibly return an `int`.  Maybe a reminder to the reader under Enforcement?  But perhaps I am being too pedantic.

**Comment by cubbimew** [comment]
> Maybe a reminder to the reader under Enforcement?

Enforce no redundant return in main? That's unlikely to pass.

But I'd agree it's worth reminding that the return statement is unnecessary in this case, Second sentence in the Note or comment in the example could work.

**Comment by hsutter** [comment]
Editors call: Thanks! We'll add something to the Note to remind that the `return 0;` is implicit.
