### ISSUE TITLE
Passing std::unique_ptr into a function nearly always means not_null

### ISSUE THREAD

**Issue by mrvn** [isocpp/CppCoreGuidelines#1898]
The guidelines say:

1. F.23: Use a not_null<T> to indicate that "null" is not a valid value
2. R.20: Use unique_ptr or shared_ptr to represent ownership
Lets assume I have a function that requires a resource to be passed in:

    void control_resource(Resource *resource); // takes ownership, must not be nullptr

Do I follow F.23 and make it

    void control_resource(gsl::not_null<Resource *> resource); // takes ownership

Or do I follow R.20 and make it

    void control_resource(std::unique_ptr<Resource> resource); // must not be nullptr

And then I remember this in F23:

> not_null is not just for built-in pointers. It works for unique_ptr, shared_ptr, and other pointer-like types.

Isn't nearly every function taking an std::unique_ptr<T> as argument expecting the pointer to be not_null? So should I do this?

    void control_resource(gsl::not_null<std::unique_ptr<Resource>> resource);

Isn't that such a frequent contract that we should have a separate type for this that allows a T&, T* or std::unique_ptr<T> to be moved into with a check for nullptr? It should not allow moving temporaries into it as well. I kind of want to use

    gsl::owner<T&>

because owner says something about ownership and reference can't be nullptr. But that lacks the RAII portion of std::unique_ptr. So maybe

    struct Holder {
       Holder(gsl::unique_ref<Resource> r) : p{std::move(r)} { // foo requires a Resource and takes ownership
        ....
      }
      private:
        std::unique_ptr<Resource> p
    };

A unique_ref could be moved out of with std::move to take over ownership like shown above. The std::move makes it clear the ref will now no longer be used so I think it would be OK for it to be nullptr in its invalid state.

The following code should fail to compile or throw an exception:

    gsl::unique_ref<Resource> r{alloc_resource()}; // returning nullptr will fail
    foo(r); // checks for nullptr on copy, compiler should optimize this away
    foo(r); // checks for nullptr on copy, will fail because the resource was moved out

Hopefully the compiler would see this all statically. But runtime checks would be better than nothing.

What do you think? Am I totally missing the big picture?

**Comment by hsutter** [comment]
Editors call: For this use case, we would recommend passing `unique_ptr` and checking for null. There might be a better solution in the future but we don't have one right now.
