### ISSUE TITLE
Why no gsl::maybe_null or gsl::non_owner?

### ISSUE THREAD

**Issue by shaneasd** [isocpp/CppCoreGuidelines#1899]
The core guidelines recommend annotating ownership and potential to be null by using gsl::owner and gsl::not_null. The lack of these annotations is intended to indicate, respectively, "this is a non-owning pointer" and "this pointer might be null". However in my code base (and I'd imagine most code bases) the lack of gsl::owner or gsl::not_null usually indicates "I haven't updated this code to conform with the core guidelines". Of the three possible states for a given annotation (e.g. owning, non-owning, and unspecified) why do the core guidelines pair two of them together?

I speculate that it's because, in this case, the core guidelines are describing a well defined end state rather than an a path to achieve it. I know that that's not the intention however as In.0 makes a point about gradual adoption.

I also wondered if it was because these are the annotations that require more checking (e.g. a static analyzer can complain about failure to destroy a member gsl::owner in an owning destructor and the not_null constructor can assert that it's argument is not null). However it seems to me that it would still be useful information for the static analyzer to know that a pointer is non-owning (and as such should not be destroyed) or that a pointer could be null (and as such should be checked before dereference).

Perhaps the most glaring reason would be just to keep the annotations down to a more manageable level but if so I'm curious why not_null and owner were chosen over maybe_null or nonowner (or whatever you might name them).

I suspect, in this case, the "issue" here is my own ignorance of the justification behind the decision and that there is a good reason for these decisions but I'm really curious to know what it is.

**Comment by cubbimew** [comment]
Funny you should say it, GSL used to have `maybe_null` until https://github.com/microsoft/GSL/issues/123 

As for distinguishing between GSL-blessed non-owner-non-array-maybe-null `T*` and questionable legacy who-knows-what `T*` in the same code, I've sen it come up before (e.g. [this comment ](https://github.com/isocpp/CppCoreGuidelines/issues/847#issuecomment-280431932)) . I know some people like to mark GSL-blessed `T*` with a custom tag, such as `observer<T>`, and someone floated marking not-yet-looked-at `T*` within a module under modernization. Either way would be good to pin down guidance if there is one.

**Comment by hsutter** [comment]
Editors call: No, we don't currently intend to specify negative annotations. By default an unannotated pointer is non-owning maybe-null.
