### ISSUE TITLE
I.7 mutex example: what is the relevant difference between good and bad example?

### ISSUE THREAD

**Issue by oliver** [isocpp/CppCoreGuidelines#190]
Forgive me for being dense, but in I.7 ("State postconditions") I don't understand the "mutex" example, in particular the "good" case.

Between

	mutex m;

	void manipulate(Record& r)	// don't
	{
		m.lock();
		// ... no m.unlock() ...
	}

and

	void manipulate(Record& r)	// better: hold the mutex m while and only while manipulating r
	{
		m.lock();
		// ... no m.unlock() ...
	}

I see as differences only that the second code doesn't declare m at all, and that the second code contains a comment which however doesn't seem to be part of the code but rather part of the CppCoreGuidelines explanation.

I'd appreciate it if this example could be made more clear, to indicate exactly where the improvement lies in the good case.
Also, maybe it would be helpful to add some declaration of "m" to the second code so that it mostly mirrors the first code?

**Comment by BjarneStroustrup** [comment]
clarified
