### ISSUE TITLE
Clarification of gsl::not_null supported types, and ease-of-use members

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#1901]
What is the guidelines' current position on adding "useful" methods to `not_null` to support ease-of-use for more general "nullable" types?

A recent issue in the ms-gsl repo https://github.com/microsoft/GSL/issues/1039 is asking whether `gsl::not_null` can be made to support `operator()` for `std::function`. 

Two similar issues existed in the ms-gsl repo in the past, but were closed due to `not_null` being only for pointers-to-objects and for standard smart pointers.
- https://github.com/microsoft/GSL/issues/626
- https://github.com/microsoft/GSL/issues/325

However, it seems that the guidelines now define `gsl::not_null` more generally as
> not_null<T> // T is usually a pointer type (e.g., not_null<int*> and not_null<owner<Foo*>>) that must not be nullptr. T can be any type for which ==nullptr is meaningful.

**Comment by hsutter** [comment]
Editors call: No. `not_null` is currently intended for pointers to single objects.
