### ISSUE TITLE
License Reference to internal business use

### ISSUE THREAD

**Issue by saadrahim** [isocpp/CppCoreGuidelines#1908]
The CPPCoreGuidelines projects appears to preclude referencing the source for business use in open source projects. Please see https://github.com/isocpp/CppCoreGuidelines/blob/dc8f95d60812a10cb7feae64082f0a75cc2f43fc/LICENSE#L5. Can you expand the license to allow references from business or commercial use? Some form of restricted use for business or commercial use as long as no content is changed?

**Comment by jwakely** [comment]
Referencing something does not require any kind of license. Only copying the content does.

**Comment by hsutter** [comment]
Editors call: Definitely freely link, that's why we provide stable links. The license only applies to copies of the Guidelines, such as if you tried to publish them as a book.
