### ISSUE TITLE
C.12 - Alternative solution with `std::reference_wrapper`?

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#1919]
Hi,

C.12 suggests replacing reference data members with pointers (raw, smart) or `gsl::not_null`. Would it make sense to also suggest using `std::reference_wrapper` as an alternative solution? Since it's rebindable, it also solves the problem of the class not being copy-assignable.

Thanks!

**Comment by hsutter** [comment]
Editors call: Thanks! We think `reference_wrapper` has special magic properties for library uses, and isn't really for broad use in cases like this.

**Comment by Xeverous** [comment]
What are these magic properties? I always thought of `reference_wrapper` as a vocabulary type, an abstraction that implements rebindable reference (basically never-null observing pointer).

**Comment by jwakely** [comment]
Various places in the library have special handling for `reference_wrapper` and do something special when it's used.

**Comment by Xeverous** [comment]
Ahh right, I know `std::thread` etc. treat these differently but I did not consider this to be a "magic property". This is indeed a good argument against using them in ordinary code.
