### ISSUE TITLE
Future-proof document structure and numbering

### ISSUE THREAD

**Issue by m-j-w** [isocpp/CppCoreGuidelines#192]
Dear editors, what an excellent initiative !

This concerns document section `In.struct`: The structure of this document

Although stated there the document not to be a language manual, it should be made more future proof, and to which end I'd like to propose the following measures:

**1. Introduce consistent sub-categories and add them to the numbering scheme.**
  __Reason__: Present numbering already leaves room for some topics in some vaguely defined sub-categories. But what happens if e.g. there is a fifth general rule on expressions ? Secondly, the sub-category title tags are currently not consistent.

  __Solution__: Explicitly define sub-categories and add them as a second field to the numbers.

  __Example__: Consider the present Expressions category:
    E - Expressions (and overview)
    E.G - General rules (and overview)
    E.G.1 - First general rule
    E.Dec - Declaration rules (and overview)
    E.Dec.1 - First declaration rule
    E.Def - Definition rules (and overview)
    E.Def.1 - First definition rule

  __Note__: This would also allow machine-parsing and referencing the document by 3rd party static-analyzers, compilers, forum discussions, ...

**2. Ensure (by definition) a reference number never changes its intended purpose**
__Reason__: If 3rd party tools would reference that document, the numbers shouldn't randomly refer to a new topic or content when there is a new revision. That would clearly confuse users. Also consider the rule for some reason suddenly proposing the opposite behaviour.

__Solution__: a) introduce a status flag such as _Status: {proposed,active,deprecated,revoked}_, and b) never change the principal meaning, instead deprecate/revoke and reference new one.

__Note__: This flag would also allow 3rd party tools to check for updated revisions and deactive a rule if it is deprecated or revoked.
__Note__: Ideally, the flag would include a date when the state last changed, e.g. from active to deprecated. For a user to recognize why his tool is telling him different
__Note__: If proposed, there could be a link to a discussion; if deprecated or revoked, there could be a link to a replacement rule.
__Note__: The state from proposed to active could be an editors decision after some short(!) discussion period.

**3) Provide explicit document version information**
__Reason__: When referencing a rule, the rule might have been changed slightly in its meaning, or not yet be included etc.

__Solution__: Provide a field at the top of the document indicating a document revision or issue number along with a date.

__Note__: Could again be used by a 3rd party tool to give an additional hint, or provide automatic updating the rule database.

**4) Add such rules on rule-making to document section `In.struct`**
__Reason__: A strict format would ensure machine-parsing and conversion e.g. into some other database or format.
__Solution__: See title.
__Note__: Perhaps someone would want to contribute such a tool during time, which then could also be part of the guidelines (e.g. markdown-guidelines to JSON or XML), even if it is just for an alternative presentation on a web page.

I know, that all might sound bureaucratic. But considering all that wisdom to form one document, that will pretty much ensure it to become a very fundamental guideline.

**Comment by BjarneStroustrup** [comment]
We will stick to a semi-structured approach for now. We consider it unlikely that we will get everything right the first time, so we expect to have to restructure after a few years (if possible). We also dislike deeply nested structures - they become an obstacle unless the subject matter is truly hierarchical, and we don't think that our subject matter is all that well served by a tree structure. Duplication and cross references are necessary.
