### ISSUE TITLE
New rule proposal: exception types should be nothrow copyable

### ISSUE THREAD

**Issue by szaszm** [isocpp/CppCoreGuidelines#1921]
There is a similar rule in the SEI CERT C++ Coding Standard: [ERR60-CPP. Exception objects must be nothrow copy constructible](https://www.securecoding.cert.org/confluence/display/cplusplus/ERR60-CPP.+Exception+objects+must+be+nothrow+copy+constructible) (down at the time of submitting this issue).

Rationale: [exception objects are copy-initialized](https://eel.is/c++draft/except.throw#3), and if an implementation chooses to not elide this copy, or there is an additional copy at the catch site (i.e. not following [E.15: Throw by value, catch exceptions from a hierarchy by reference](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference)), and the copy constructor throws, [then `std::terminate` is called](https://eel.is/c++draft/except.throw#7).

It's sufficient if the exception type is nothrow copy constructible, but I can't see why someone would want to make a throwing copy assignment operator at the same time, aside from doing some magic in the copy constructor and not bothering to define a copy assignment operator, but that already violates [the rule of three / five](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c21-if-you-define-or-delete-any-copy-move-or-destructor-function-define-or-delete-them-all).

**Comment by N-Dekker** [comment]
Would such a rule suggest using reference counting, internally, when the exception object contains dynamically allocated memory?

It's quite common for a user-defined exception class to have a dynamically allocated string, holding an error message.

**Comment by szaszm** [comment]
Yes, A `std::shared_ptr<const char[]>` or a `std::shared_ptr<const std::string>` is one way of achieving this. I usually just derive from one of the standard exception types that already contains a message, and use its storage.

**Comment by hsutter** [comment]
Editors call: We think this is a good suggestion. We plan to extend E.16 to include exception type copy/move construction.

**Comment by N-Dekker** [comment]
@hsutter Thank you for addressing this issue, cool! Small nitpick, it now says at https://github.com/isocpp/CppCoreGuidelines/blob/d5907d6dd505844237249f37c0a6f7cc02c9ab56/CppCoreGuidelines.md?plain=1#L16137

> even `throw std::string(...)` could throw but does not in practice.

Sounds a bit interesting. Of course, `throw` does throw! 

I guess you mean something like:

   _even when throwing an `std::string`, its copy-constructor could throw, but that is highly unlikely to happen in practice_  

Right? Would you like to fix it directly on the master branch, or would you rather have a pull request?
