### ISSUE TITLE
T.83 redundant?

### ISSUE THREAD

**Issue by mknejp** [isocpp/CppCoreGuidelines#193]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-t83-do-not-declare-a-member-function-template-virtual

I wonder what the point of this rule is.
It's a compile error to declare a virtual function as a template, so there isn't any actual "rule" to follow.
Am I missing something?

**Comment by BjarneStroustrup** [comment]
clarified
