### ISSUE TITLE
Clarification of C.127 with respect to final classes

### ISSUE THREAD

**Issue by shaneasd** [isocpp/CppCoreGuidelines#1930]
I'm trying to understand the difference between [C.127](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c127-a-class-with-a-virtual-function-should-have-a-virtual-or-protected-destructor) and [C.35](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c127-a-class-with-a-virtual-function-should-have-a-virtual-or-protected-destructor)

The two rules are very similar but not identical in terms of their area of application. As far as I can tell the reasoning for C.127 is that if a MyClass has a virtual function then it's almost certainly part of a class hierarchy. If it's not at the bottom then it's a base class and C.35 applies. If an ancestor class has a public destructor then it should be virtual (By C.35) and thus MyClass will have a virtual destructor by the rules of the language.

What about the case where MyClass is the bottom of the heirarchy and inherits solely from ancestors with protected non-virtual destructors?
```
struct MyParent
{
   protected: ~MyParent() {}
   virtual void doStuff();
};
struct MyClass final : public MyParent 
{
   public: ~MyClass(){} //not virtual, not protected
   void doStuff() override;
}
```

As far as I can see this does not violate C.35 but it not exposed to the problems described in C.127 (in that you couldn't destroy a MyClass via a point/reference to MyParent and thus could only do so correctly via MyClass's destructor.

It seems to me that a more precise rule would be
C.127: A **non-final** class with a virtual function should have a virtual or protected destructor

I'm not asserting that the wording needs to change but I'd like to understand why that isn't the rule.

Possible reasons I considered:
- The foremost reason in my mind is that I've misunderstood something fundamental so apologies if that's the case.
- I thought of is that the example is simply too obscure. It's simpler to make ~MyClass virtual following C.127 as written rather than try to account for every obscure edge case. Although I sympathize with this view, in my case, it creates worry that I've misunderstood the rule more broadly.
- It's possible that when we say "A class with a virtual function" what is meant is "a class with a member function declared which uses the virtual keyword". If we're following C.128 then that would imply that the function is there to be overridden rather than to override something else and thus it would be a reasonable assumption that the class **is** a base class so C.35 would apply (and marking the class final wouldn't make sense)

**Comment by hsutter** [comment]
Editors call: The difference in the guidelines is that C.35 is trying to say that if a class behaves polymorphically then deletion should also be polymorphic. Note that in your example `~MyClass` is virtual (implicitly). However this has raised another related issue we will open now to track. Thanks!

**Comment by shaneasd** [comment]
oh of course. A class with a virtual function either is a base class (and so is subject to C.35) or inherits from a base class which (by C.35) should have a virtual destructor and thus will itself have a virtual destructor implicitly. I guess the answer was the first of my speculations :(.

**Comment by shaneasd** [comment]
relates to  #1841
