### ISSUE TITLE
SF.5: an include of an interface should be relative

### ISSUE THREAD

**Issue by DanielKriz** [isocpp/CppCoreGuidelines#1943]
Although it is possible to include an interface as a library (or through the search path), it is much more common and standard using `#include "foo.h"` for interfaces of classes, than `#include <foo.h>`.

It is also supported by SF.12: `#include "foo.h"                 // A file locally relative to foo.cpp in the same project, use the "" form`

Therefore I think it should be changed to relative import.

**Comment by jwakely** [comment]
> it is much more common and standard

Citation needed.

Using `#include "foo.h"` only makes a difference if the code has headers and sources files in the same directory, so isn't useful for a project structured as:

    libfoo
    ├ include
    └ src
    
I don't think this change is as obviously correct as you suggest.

**Comment by DanielKriz** [comment]
I have to admit, that I have been only working on projects that didn't use include directory. So thanks for pointing that out.

I am going to try to look for some source to back my statement. But I haven't through about the include directory.

**Comment by DanielKriz** [comment]
I couldn't find anything trustworthy enough to support my claim "that it is much more common and standard".

But I still think, that it should be changed to `#include "foo.h"` as it is a bit more bare bone example, that does not expect you to setup some kind of include directory. If you are using include directories, then you probably understand that `#include "foo.h"` can be changed to `#include <foo.h>` with include directory.

But for newbies to the language it could be misleading as they could easily confuse it with some system library.

**Comment by jwakely** [comment]
> usually comes with using some kind of makefile/cmake or a bit more complex way of using compiler.

If you're only compiling toy examples with one or two source files, the guidelines don't really matter anyway.

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#innot-non-aims

"These guidelines are not intended to be a substitute for a tutorial treatment of C++. If you need a tutorial for some given level of experience, see [the references](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-references)."

**Comment by DanielKriz** [comment]
Yet even on complex project you don't really have to use the include directory. (But it is convenient for some use cases, for example if you are including some other file (`bar.h`) than interface)

Yes it is mentioned that "The rules are not intended to be minimal or orthogonal.". And I have to admin that your argument is really good. But from my point of view the `#include <>` for interfaces are a special case of `#include ""`. But that may be just a matter of preference (one or another). So it is probably up for a discussion.

**Comment by BenjamenMeyer** [comment]
I know Qt uses in-place headers;  however, personally I have found it's best to always separate out my headers into public and private includes:
```
includes // public interfaces, definitions, etc
includes-private // private interfaces, definitions, etc
source
```
All-in-all, they're probably about equally common and which methods used is based on the desires of the core devs/maintainers. Guidelines should support both methods equally as a result.

**Comment by DanielKriz** [comment]
> I know Qt uses in-place headers; however, personally I have found it's best to always separate out my headers into public and private includes:
> 
> ```
> includes // public interfaces, definitions, etc
> includes-private // private interfaces, definitions, etc
> source
> ```

But that is used like `#include <foo.h>` in both cases, right?

> 
> All-in-all, they're probably about equally common and which methods used is based on the desires of the core devs/maintainers. Guidelines should support both methods equally as a result.

Well I could change my pull request to something like `#include <foo.h> // or "foo.h" if they are both in one directory`, but I don't think that is done that way anywhere else in the guidelines. (funny thing, `#include "foo.h"` is located in one place and that is SF.12)

**Comment by MikeGitb** [comment]
> Honestly the #include "" version can be much more confusing. yes, it's convenient but what happens when the files get moved? More things tend to break. Further it leaves more paths for the compiler to search which can mean larger compile times (the little things add up)

Only, if you don't use the syntax for relative paths. Otherwise it should be the other way round, because the very first location the compiler looks at is the right one.

**Comment by DanielKriz** [comment]
It has been merger, therefore I am closing this issue, thank you everyone for great discussion.

**Comment by Satoshi-MM** [comment]
All in one finance and bank well for bank just but it under MAM Ddigital
Bank Global & finance in google finance i am the creator &  the owner. I
expect ,this to be done as i say
