### ISSUE TITLE
F.17 Possible Clarification Needed

### ISSUE THREAD

**Issue by CompCodeNet** [isocpp/CppCoreGuidelines#1948]
Is std::span an example of a lightweight wrapper that is often used as an in-out parameter but is commonly not passed by reference?

**Comment by hsutter** [comment]
Editors call: Yes, it is. We'll look at mentioning that some user-defined types act like references and passing those by value has reference semantics.

**Comment by CompCodeNet** [comment]
Sounds great! Thanks much for response.

**Comment by cubbimew** [comment]
@CompCodeNet I added a note; please review

**Comment by CompCodeNet** [comment]
The note certainly indicates that some value-types meet the rule. 
(The note also illustrates that reference is a concept as well as a literal syntax which is fine/interesting and perhaps a clue that one day C++ won't need pointers or at least won't need both pointers and references in syntax).
Thanks kindly.
