### ISSUE TITLE
Rename not_null<T> to never_null<T>

### ISSUE THREAD

**Issue by michaelbprice** [isocpp/CppCoreGuidelines#195]
It seems to me that `not_null<T>` should be a function template that verifies that it's parameter is not `nullptr` before using it (as a form of interface documentation).

`not_null<T>` as it currently exists is more of permanent restriction on the state of an object, thus I think it would be better named `never_null<T>`.

**Comment by hsutter** [comment]
We think it works better as a type and we want it as part of the type system, rather than as a function that people have to remember to call. The function would do the same thing as `never_null`'s constructor presumably. So it's unclear how this is different from the current design where we have a single type and can use it as a parameter and equally as a type with an invariant.

**Comment by michaelbprice** [comment]
I wasn't proposing to convert `not_null<T>` to a function, but to rather rename it to something that indicates that the value can never be `nullptr`, not just 'not `nullptr` right now'

No change in design, just a clearer name.

**Comment by thatbrod** [comment]
I feel the type name already conveys those semantics.  If at _any_ time you
see a value of this type it's `not_null`, then it is effectively _never_
null.

**Comment by michaelbprice** [comment]
@thatbrod.  That's a fair assessment.  What would we expect the behavior for the following to be (presuming  you didn't already know what the semantics of `not_null<T>` were).

```cpp
void dispatchTheThing (not_null<int*> & address) {
    address->doTheThing();
    address = nullptr;
}
```

I would think that it makes sure that the `address` is not `nullptr` so that I can safely use it, but I wouldn't expect it to then prevent me from assigning `nullptr` to `address` after I've done my work.

**Comment by thatbrod** [comment]
I'm not sure either of us can speak for everyone, but when I see code like that I would expect a compile-time error because a template saying that can't happen is wrapping `int*`.  Templates in practice help us generate compile-time errors, and so I wouldn't think of this case as an exception.

**Comment by michaelbprice** [comment]
Ah, the Microsoft implementation of GSL has this:

```cpp
not_null(std::nullptr_t) = delete;
```

This is another reason why there needs to be some sort of specification for this.

I would expect that the compiler should let that happen.  I still believe that `never_null` would be a clearer name.  Obviously there are different opinions.
