### ISSUE TITLE
Reference correctness in operators and member functions that return references.

### ISSUE THREAD

**Issue by theundergroundsorcerer** [isocpp/CppCoreGuidelines#1951]
Some member functions and operators return references, the obvious cases being assignment operator and subscript operators, as well as accessor functions in some cases. 

I begin with assignment operators, since they are fundamental part of class definition and return references by default.

Default behavior of assignment operations returns a lvalue reference. If we assign to rvalue and use the result as a reference, we can get a dangling pointer. (Same holds for access operators such subscript, that return a reference, even if the we apply it on a temporary object). Therefore, C.20 might need a review or modification - as default behavior of assignment operators allows incorrect behavior.
It is not that serious, as doubt that assigning values to rvalues and then assigning the result is often done intentionally, however this is not a bug caught by the compiler and/or immediately visible when running the program. Adding reference qualifier prevents this. At least, the possibility to add qualifiers to assignment operators should be mentioned. 

This is worse when we talk about accessors (including subscript operators) that return references - the examples in the guidelines describe how to avoid code duplication for const and non-const, but do not mention the need to consider applying reference qualifers and/or overloading them, which is easily overlooked and error-prone - it can easily result in dangling references, if not careful. Discussion of the need and the effect of applying various reference qualifiers  of these functions with various reference qualifiers is necessary, especially for newcomers to the language.

**Comment by Satoshi-MM** [comment]
No denied i am who owns it and i am putting order on what i created. I  do
not take orders and no one is in any position to but their own demands i do
not. Need anyone so this is your notic if you take such actions i will take
everything you have becauase i can and i will

**Comment by hsutter** [comment]
Editors call: We have some sympathy for lvalue-qualifying assignment operators for the reasons described in [N2819](http://wg21.link/n2819) for reasons other than dangling. For dangling, our current guidance is the [Lifetime safety profile](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#SS-lifetime).
