### ISSUE TITLE
R.1 RAII Clarification and Suggestion

### ISSUE THREAD

**Issue by CompCodeNet** [isocpp/CppCoreGuidelines#1953]
Hi, I'm not sure where to post suggestions for advances in C++. Regarding RAII, I definitely understand the "resource" management aspect via ctor / dtor. 

However, I propose that the "initialization" aspect should not be tightly bound with the acquisition aspect. I think that reuse of existing objects by reinitializing them and using the existing object memory without a memory free and malloc (new / delete) cycle is much more performant than always having to delete and re-"new" objects. Further, my understanding is that for safety critical software, memory allocations at run-time are sometimes not allowed or discouraged.

In Summary: My thought is that we need to leverage the ctor / dtor concept benefits without necessarily coupling them with memory free and allocation cycles under the hood, especially for the many cases when the object could simply be reused with re-initialization.

An example might help. Consider a File class that has features and data members besides the file handle. Under current RAII, the handle is closed by dtor. Fine. However, what if one wishes to simply re-open the same file object e.g., with a new path and thus a new handle would be created. Under current RAII, a new File object would need to be created (with the associated memory free and alloc). What I am proposing is a language feature for classes analogous to what unique_ptr::reset() does for pointers. I.e. Support an initialization cycle and _desired_ resource release e.g. handle close, without the memory free/alloc cycle.

**Comment by cubbimew** [comment]
> Consider a File class that has features and data members besides the file handle

```
class File
{
  std::map<std::string, int> lots_of_data;
  FileHandle fh;
};
```
>  the handle is closed by dtor.

right, the default ~File calls ~FileHandle, which presumably calls ::fclose or whatever its author used

> re-open the same file object e.g., with a new path and thus a new handle would be created
```
File::switch_file(fs::path p) 
{
  fh = FileHandle{p};
}
```
> Under current RAII, a new File object would need to be created (with the associated memory free and alloc). 

why? See above; no new File object, no memory free, no memory alloc

The point of RAII is every object is usable without a validity check. If there is a "reuse" method, it doesn't change that. All RAII wants is that the object is usable before "reuse" is called, and usable again after.

**Comment by CompCodeNet** [comment]
FileHandle, yes, I use similar. (I purposefully delete the copy ctor and assign btw.)

>> See above; no new File object, no memory free, no memory alloc. 
OK, so what you are saying is that RA guarantees initialization but not vice-versa. I can see that concept and thank you. I also do understand that we can add our own reuse methods. 

However, the remainder of my point is that ctor / dtor facilities that are involved with init are also tied to memory free/alloc cycles. Plus, a public reuse() function can be called any time including inadvertently whereas once an object is constructed, the private members cannot be changed (except for explicit setters, reuse/reinit functions etc.). So, I would like to see init/reuse capabilities that are similar to ctor in that once it's done, there are no public methods available to re-init etc. as we have with reuse function. So, it's effectively a ctor scenario without the memory alloc cycle.

(This also plays into need for standard init/ctor/move/copy special functions or keywords that can be used for both reuse and traditional ctor / dtor scenarios as well as copy/move because these functions often share code.)

Further a class "pool" keyword would be great whereby objects are automatically pooled (pool size specifiable) so ctor/dtor don't incur memory cycle. Still, this may have some overhead compared to re-init/reuse.

Thanks for thoughtful and helpful response. At least I will feel less discourage to use reuse methods now, Perhaps the guidelines could mention or emphasize the reuse concept prior to any new language features that further integrate it.

**Comment by jwakely** [comment]
> I think that reuse of existing objects by reinitializing them and using the existing object memory without a memory free and malloc (new / delete) cycle is much more performant than always having to delete and re-"new" objects.

RAII does not mean you have to delete and recreate objects all the time. I think maybe your idea of it is too rigid.

Re-initialization is still initialization - the clue is in the name.

The important point is just that when resources are acquired, they should be immediately owned by some object, so they will be released by the destructor. Don't have bare resources (memory, file descriptors, etc) that are not owned by some object.

We don't need a language feature to do what unique_ptr::reset does, we can already do what unique_ptr::reset does. It works fine, and is not in conflict with RAII.

**Comment by CompCodeNet** [comment]
>> I think maybe your idea of it is too rigid.
Agree to some extent and thank you. Please see my post before this one as I have addressed other aspects.

**Comment by hsutter** [comment]
Editors call: The comment thread seems to have addressed the question. Thanks!

**Comment by CompCodeNet** [comment]
Hi, please note that I'm still suggesting a ctor-like once-and-done capability in C++ for re-use/re-init.
