### ISSUE TITLE
C.168 should be updated for C++20 default comparisons

### ISSUE THREAD

**Issue by jwakely** [isocpp/CppCoreGuidelines#1955]
The text following this [example in C.168](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-141) is outdated:

https://github.com/isocpp/CppCoreGuidelines/blob/dca24a037924be3ddb0d5ab139342a56bc384e57/CppCoreGuidelines.md?plain=1#L8501-L8509

We do have such defaults since C++20.

**Comment by baiyanhuang** [comment]
Seems like not? - https://godbolt.org/z/x9njs3KEf

**Comment by jwakely** [comment]
I'm not sure what your link is demonstrating.

**Comment by jwakely** [comment]
Oh I see the comment now.

1. You didn't use a `-std` option, so your example is compiled as C++17.
2. C++20 does have default comparisons, but you need to explicitly opt-in.

This works:

```c++
struct S
{
    int a;
    bool operator==(const S&) const = default;
};
```

**Comment by jwakely** [comment]
Alternatively:

```c++
struct S {
    int a;
    friend bool operator == (S, S) = default;
};
```

**Comment by baiyanhuang** [comment]
I did use clang 14 with -std=c++20, but seems like godbolt doesn't preserve my compile options within the link - but as you pointed out, we need explicit opt-in.

**Comment by hsutter** [comment]
Editors call: Thanks! We'll change this to `operator+` for now to avoid the C++20 question. At some point it's getting to be time to take a pass through the Guidelines to update them for C++20.
