### ISSUE TITLE
C.21 Not clear on the virtual destructor example

### ISSUE THREAD

**Issue by baiyanhuang** [isocpp/CppCoreGuidelines#1958]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-five

> Example, good
> When a destructor needs to be declared just to make it virtual, it can be defined as defaulted.
> 
> ```
> class AbstractBase {
> public:
>     virtual ~AbstractBase() = default;
>     // ...
> };
> ```

It is not clear from the description whether it should or don't have to follow the rule of five, we should probably make it more clear?
> When a destructor needs to be declared just to make it virtual, it can be defined as defaulted **without following the rule of five**

**Comment by MikeGitb** [comment]
I think the Rule of 5 still applies. Its just not the focus of that rule, so they are not shown in the example code.

**Comment by baiyanhuang** [comment]
I think we need to give clear direction in a guideline, rather than confusing in this case, so we'd better:
1. Explicilt specify we don't have to follow the rule of five here, which is inline with the example code
2. Or we highlight we should follow the rule of five, and give a consistent example with all five functions spelled out explicitly

**Comment by hsutter** [comment]
Editors call: The `// ...` is for when we don't want to fill in a lot of boilerplate each time. The example that immediately follows shows one possible way to to write it all out.
