### ISSUE TITLE
Using f as function name and internal variables invites confusion. Recommending using better name for functions.

### ISSUE THREAD

**Issue by aerosayan** [isocpp/CppCoreGuidelines#1960]
Hello everyone,

I was reading [R12](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r12-immediately-give-the-result-of-an-explicit-resource-allocation-to-a-manager-object) and observed that the function name `f` is shadowed by the file variable inside the function. Then, `f` is used to call the `finally` block.

```c++
void f(const string& name)
{
    FILE* f = fopen(name, "r");            // open the file
    vector<char> buf(1024);
    auto _ = finally([f] { fclose(f); });  // remember to close the file
    // ...
}
```

This is potentially very confusing to the general reader who might not know about lambda scope captures.

"Does `finally` use the variable or the function `f`?" would be their question.

[R13](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r13-perform-at-most-one-explicit-resource-allocation-in-a-single-expression-statement) uses `fun` for the function name. Using `func` might be better, but `fun` is still good, and much easier to understand than `f`.

Recommending using `fun` at least for the function name used in R12.

Thanks :)

**Comment by beinhaerter** [comment]
If you want you can create a pull request with exactly that change.

**Comment by hsutter** [comment]
Editors call: Sure, let's change `f(...)` to `func(...)`. Thanks!
