### ISSUE TITLE
C.21 Question RE Slicing

### ISSUE THREAD

**Issue by CompCodeNet** [isocpp/CppCoreGuidelines#1962]
Hi, is the guidance for abstract (interface) classes to `=default` the virtual dtor and `=delete` the other four "rule of five" functions?

**Comment by cubbimew** [comment]
C.21 currently says "make the copy and move operations protected or =deleted", so it's one of the two approaches it offers.

**Comment by CompCodeNet** [comment]
Thanks much, so, as a general default coding habit, declaring virtual dtor `=default` and the rest `=delete` is fine?

**Comment by CompCodeNet** [comment]
Thanks very much.
