### ISSUE TITLE
C.120, C.129: Example Non-Conformance in STL?

### ISSUE THREAD

**Issue by CompCodeNet** [isocpp/CppCoreGuidelines#1964]
std::unordered_map inherits from _Hash. _Hash is not abstract.
Edit, I think this is my mistake - map inheritance from hash is a valid example of implementation inheritance. Closing, thank you.

**Comment by jwakely** [comment]
In any case, you're talking about an implementation detail of a specific std::lib implementation which is off topic here.

**Comment by CompCodeNet** [comment]
Hi Jonathan, 

> which is off topic here.

I propose that examples that are discussed in the context of understanding guidelines and that are not about a library per se are in topic. In my case, I agree, I did focus more on the lib itself, but still, if the lib itself was valid (which it is) and showed that a guideline was too broad, then it's on topic for discussion. In this case, the example, helped me understand the guidelines better. Many of the methods in Hash are protected and Hash is designed as a base. However, in the guidelines, the interface aspect of inheritance is more readily apparent than other valid forms of inheritance. So, this post may still help you to consider whether you might want to present the guidelines in such a way, that busy readers, don't get a quick impression that interfaces are good, and all other inheritance is bad (which is exactly the impression that I had). In the guidelines you could have two bolded list items that firmly the state the two valid forms of inheritance. From there, they can be expounded upon. My suggestion if helpful.

Thanks Much
