### ISSUE TITLE
T.140 - Why is this item of "Other template rules"

### ISSUE THREAD

**Issue by baiyanhuang** [isocpp/CppCoreGuidelines#1974]
It seems like not template specific, so maybe better move to a different section?

**Comment by hsutter** [comment]
Editors call: We agree, it should be moved to the F.* functions section.

- T.140 /141 should be made F.10/11
- T.140's name should change from "Name all operations with potential for reuse" to "If an operation can be reused, give it a name"
- the existing T.140/T.141 sections should be retained as empty and redirect to F.10/F.57 (to not break old links)
- C.lambdas should also be updated to refer to F.10/11
