### ISSUE TITLE
Multiple uses of same access specifiers in class layout

### ISSUE THREAD

**Issue by futurebreed** [isocpp/CppCoreGuidelines#1976]
The C++ Programming Language 4th Edition has a section on access control where it mentions:

"A compiler may reorder sections of a class with separate access specifiers"

and goes on to demonstrate a scenario:

```
class S {
public:
   int m1;
public:
   int m2;
}
```

It describes that `m2` could be reordered to be ahead of `m1` in the layout of an `S` object, and that this behavior is implementation-dependent so "do not use multiple access specifiers for data members without good reason."

This seems to be a really important distinction to note for folks who are trying to optimize layout, minimize padding etc, that they may inadvertently have worse layout with one compiler vs another. Is this worth a Guidelines note? Would it be too rigid to say not to use multiple cases of the same access specifiers at all in a class, or are there actual valid use cases not enumerated in the text?

**Comment by jwakely** [comment]
> This seems to be a really important distinction to note for folks who are trying to optimize layout, minimize padding etc, that they may inadvertently have worse layout with one compiler vs another. Is this worth a Guidelines note?

No, I don't think so.

Only one known compiler even supported doing that, and it's not believed any users ever used that feature. And they're not going to be allowed to now either, as [P1847R4](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1847r4.pdf) was approved for C++23.

N.B. I don't think the given example is actually correct. The rule prior to C++23 was for "different access control", but `m1` and `m2` both have public access.

**Comment by cubbimew** [comment]
The two public sections example appears here in [NL.16](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-bad-156) but only as optional "naming and layout" guidance.

**Comment by hsutter** [comment]
Editors call: Thanks! We agree with the replies that it's poor style but doesn't warrant a guideline beyond the suggestion in NL.16.
