### ISSUE TITLE
What's the appropriate approach to #1157?

### ISSUE THREAD

**Issue by SainoNamkho** [isocpp/CppCoreGuidelines#1978]
Suppose I'm writing an insertion sort
```c++
void insertSort(span<int> sp)
{
    for (int i = 0; i < sp.size(); ++i) {
        auto insert_pos = ranges::upper_bound(sp.first(i), sp[i]);
        if (insert_pos == sp.first(i).end()) {
            int temp = sp[i];
            ranges::copy(span{insert_pos, sp.begin()+i}, insert_pos+1);
            *insert_pos = temp;
        }
    }
}
```
It's wrong since `insert_pos`, `sp.first(i).end()` and `sp.begin()` are from three different `span` objects.
#1157 suggest to do this with ranges.
```c++
void insertSort(span<int> sp)
{
    for (auto it = sp.begin(); it != sp.end(); ++it) {
        auto insert_pos = ranges::upper_bound(ranges::subrange{sp.begin(), it}, *it);
        if (insert_pos == it) {
            int temp = *it;
            ranges::copy(ranges::subrange{insert_pos, it}, insert_pos+1);
            *insert_pos = temp;
        }
    }
}
```
But four years since that issue, clang still cannot compile it. llvm/llvm-project#52696 says it's fixed, while actually it just do not compile.

So what are we supposed to do? Just sit down and wait for clang 15 to fix it?

**Comment by jwakely** [comment]
Yes, or use a different compiler.

The future is already here, it's just not evenly distributed.

**Comment by jwakely** [comment]
You can also convert the span iterators to pointers and compare those, so that any debug checking on the iterators doesn't complain about iterators to different ranges.

**Comment by SainoNamkho** [comment]
> You can also convert the span iterators to pointers and compare those, so that any debug checking on the iterators doesn't complain about iterators to different ranges.

Thanks a lot, maybe I'll go back to the original unconstrained algorithms.
