### ISSUE TITLE
Non-rules N: vs NR:

### ISSUE THREAD

**Issue by shaneasd** [isocpp/CppCoreGuidelines#1993]
There's some ambiguity as to whether the Non-Rules prefix is N: or NR on http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines
![image](https://user-images.githubusercontent.com/23055764/201608816-9f3caed7-a18a-48b4-b4ad-90409ef7db5c.png)

the guidelines document itself appears to be consistent. It's just the wrapping website that introduces the inconsistency. I assume that's controlled externally but it seems quite closely related and I assume a lot of the same people are involved so I've raised it here.

This is certainly not a major issue. I'm assuming it's low impact, low cost fix.

**Comment by cubbimew** [comment]
Yes, that was a typo in that sidebar. fixed.
