### ISSUE TITLE
ES.43: Avoid expressions with undefined order of evaluation

### ISSUE THREAD

**Issue by domdrag** [isocpp/CppCoreGuidelines#2003]
I understand that codes like 
```cpp
v[i] = ++i;
```
should be avoided at all costs and I'm not here to argue that. I just wanted to point out that the expression `v[i] = ++i;` is, at least as far as I'm aware, well-defined in C++11 and higher.

**Comment by cubbimew** [comment]
C++17 and higher, since that's when simple assignment started sequencing its operands. That's the point of the sentence right before the example.
Just checked - both gcc and clang give Wunsequenced/Wsequence-point warnings

**Comment by domdrag** [comment]
@cubbimew Correct me if I'm mistaken, but since `++i` is defined to be identical to `i += 1` and the side effect of (compound) assignment is sequenced before its value computation, wouldn't that make the expression well-defined in C++11 as well?

**Comment by jwakely** [comment]
No, because `i` has to be evaluated in `v[i]` as well, and before C++17 that was unsequenced w.r.t the `++i` operand.

C++14 says:

>  In all cases, the assignment is sequenced after the value computation of the right and left operands, and before the value computation of the assignment expression.

Note there is no defined order of evaluation of the right and left operands.

C++17 says (emphasis mine):

>  In all cases, the assignment is sequenced after the value computation of the right and left operands, and before the value computation of the assignment expression. **The right operand is sequenced before the left operand.**

**Comment by domdrag** [comment]
@jwakely Got it. 
Thanks.

**Comment by jwakely** [comment]
> the side effect of (compound) assignment is sequenced before its value computation

This only refers to the evaluation of the entire assignment expression, i.e. the side effects and result of `(a = b)`, where the side effects are modifying `a` and the value computation is (typically) an lvalue referring to `a`. But that says nothing about the value computation of `a` and the value computation of `b`, only that both must happen before the side effects of the assignment. Prior to C++17, those two computations were indeterminately sequenced.

**Comment by BjarneStroustrup** [comment]
Such code is too subtle; the chance is that the author was confused or that some reader will be.
