### ISSUE TITLE
P.1: Express ideas directly in code  Example 4

### ISSUE THREAD

**Issue by nzmgng** [isocpp/CppCoreGuidelines#2005]
This rule states that code should expresses its purpose by giving them correct naming as far as I understand. However in the example
`change_speed(double s);  // bad: what does s signify?`   the lowercase ` s`  depicted here as a meaningles argument regarding its purpose on the other hand in the next example `change_speed(Speed s);    // better: the meaning of s is specified` defining ` s`  argument here by specifiying its intent by defining as a purposeful type  related with `s` seems to better approach . But the problem it is useless in the function scope again. So could it be a better way also declaring argument by its purpose like  `change_speed(double speed);  `

**Comment by hsutter** [comment]
Editors call: We think the example is good as written. Note that the issue it's illustrating is described as being not about speed (which is already in the function name) but about what the meaning of the parameter is (is it a delta? an absolute speed?). This is about not just giving a correct name, but conveying the right semantics, even if the parameter were of a type `speed` or were named `speed`.
