### ISSUE TITLE
not_null invariant and .get() Expects assertion

### ISSUE THREAD

**Issue by hsutter** [isocpp/CppCoreGuidelines#2006]
### Basic issue: Removing null check from `not_null::get()` implementation

In the Microsoft GSL `not_null` implementation, the `not_null<T>::get()` function has an assertion to check that the contained pointer is not null. However, the `not_null` object by design can never get into a not-null state by using the type’s own interface because the checks are performed on construction/assignment, and so the not-null runtime check in `.get()` is redundant, and users have complained it sometimes adds overhead.

The Microsoft GSL maintainers have been asked to remove the assertion in `.get()`, but wanted to check with the Guidelines editors.

### Concern: Can a user of `gsl::not_null` legitimately get it into a not-null state? Or can we assume types really do control their invairants?

A concern was raised that if a user abuses our `not_null` object they could force a null into it somehow.

(1) One way is to use a `union`:

    union U { something bad; not_null<T*> nnp; };
    U u;
    u.bad = random_bits; // bad: type-unsafe
    u.nnp.get(); // could read back a spurious null

(2) Another way is to use a `reinterpret_cast`:

    not_null<T*> nnp = *valid_object; // ok
    reinterpret_cast<something&>(nnp) = random_bits; // bad: type-unsafe
    u.nnp.get(); // could read back a spurious null

In (1) and (2), the user's code is violating the type system. The GSL maintainers agree that’s these cases are the user’s own fault, it’s not something the `not_null` type should try to defend itself against.

(3) However, a third way the user can bypass the `not_null` interface is using a `const_cast`, for example:

    // this is impossible for a raw T* because .get() returns by value
    const_cast<T*&>(nnp.get()) = nullptr;  // compile-time error, so this is fine

    // but for a smart pointer, .get() returns by const&,
    // and for a move-only smart pointer it has no other choice
    const_cast<unique_ptr<int>&>(nnp.get()).reset;  // nnp::ptr_ is now NULL

Technically this doesn't directly violate the language's type system, even though this use of `const_cast` violates the Guidelines which say not to use `const_cast`. However, it's clearly against the intent of the author of `not_null` which is doing the best it can to return a nonmodifiable reference.

Question: Do we care about supporting code that uses such a `const_cast` to potentially bypass `not_null`’s interface and break its not-null invariant, so that `.get()` should continue to assert not-null defensively just in case the user abuses our object? Or do we treat this as the same kind of unjustified abuse as the `union` and `reinterpret_cast` cases and not care about it and go ahead and remove the redundant not-null assertion in `not_null::get()`? (My vote is for the latter, a type should be able to control its invariants including control access to its internals.)

### A more fundamental need: State GSL types' invariants? or even their full interfaces?

Another GSL maintainer pointed out that they don’t care much which way these questions are resolved, but:

> However, these questions raise a more fundamental need: A high-level statement (some may call it “threat model”) of what it is that we are promising to users of the types”.  Such a set of principles would help us decide which facility/functions (including checks) to add or to remove.  That also provides guidance to implementers of the GSL.  Otherwise, we are likely bound to make temporally incoherent decisions based on the consensus du jour.

I agree, perhaps the right thing is to state the GSL types’ invariants. And I think that’s desirable anyway, because we know the GSL types were never well specified, and just writing down their invariants would be a bonus.

Here’s my suggestion for the GSL section:

Make a general statement something like this:

> For each GSL type below we state an invariant for that type. That invariant holds as long as user code only changes the state of a GSL object using its type’s interface (i.e., user code does not bypass the type’s interface to change the object’s value/bits via any unsafe `union`/casts/`memset`).

This is phrased to exclude both `reinterpret_cast` and `const_cast`.

Then consider the GSL types, starting with `not_null` to answer this thread's question:

- **`not_null`**: We already say “must not be `nullptr`,” so let’s state the invariant that “a `not_null<T>`’s stored value never compares equal to `nullptr`.”
- **`gsl::span`**: We can say “obeys the interface, semantics, and invariants of `std::span`, and in the implementation adds a way to guarantee element access operations are bounds-checked to be in the `span`’s bounds.”
- **`zstring` and `czstring`**: We already say “a zero-terminated sequence or `char` or `nullptr`” so I think that basically already states the invariant.
- **`stack_array` and `dyn_array`**: We don’t currently really specify any interface. Presumably if we did an invariant would be something like “`size() >= 0`” ?
- **`final_action`**: I’m not sure there’s a state-able invariant?
- **`joining_thread`**: We should probably actually remove it and refer to `jthread` but that’s part of the C++20 push.

I think that’s it for GSL types?

How does that sound?

**Comment by JohelEGP** [comment]
Another way it by using `std::bit_cast`: https://compiler-explorer.com/z/PvxExGTbo.
```C++
#include <bit>
#include <gsl/pointers>
int* i = std::bit_cast<gsl::not_null<int*>>(nullptr).operator->();
```

**Comment by hsutter** [comment]
Editors call: We think that the `const_cast` case is even more egregious than the `union` and `reinterpret_cast` cases. The `union` and `reinterpret_cast` can be used to just read the hidden internal bits of the object (which may be undesirable too), even when not modifying the object bypassing its interface. However, the `const_cast` is pretty much only used to modify the the object bypassing its interface. We don't need to support such uses. They can only get that effect by breaking rule ES.50.

**Comment by hsutter** [comment]
Add:

> For each GSL type below we state an invariant for that type. That invariant holds as long as user code only changes the state of a GSL object using the type’s provided member/free functions (i.e., user code does not bypass the type’s interface to change the object’s value/bits by violating any other Guidelines rule).

For the types: We think they already state their invariants well, except it seems that for `gsl::span` we don't say that it is bounds checked and we should add a sentence in the GSL Views section to say that explicitly.
