### ISSUE TITLE
C.12 should not apply to non-regular polymorphic types

### ISSUE THREAD

**Issue by strpbrk** [isocpp/CppCoreGuidelines#2012]
Please consider limiting C.12 to data members of **regular types**. Alternatively, please amend the guideline to cover reasoning why it is damaging to other use cases, such as the one presented here. Thanks!

I understand and support the reasoning for banning const data members in regular types. However, why ban it in a private data member of a **non-copyable polymorphic type**?

I have read a few discussions about this issue, and I saw an argument made by @MikeGitb about this, but it was ignored.

From the guideline:

> They are not useful

For a private data member of a non-copyable polymorphic type, the const qualifier documents the intent they at least add a bit of "documentation". Example below.

> make types difficult to use by making them either uncopyable or partially uncopyable for subtle reasons

The class is already non-copyable and is declared as such. The const qualifier on a private data member does not make it worse.

It is very useful to me to mark some **private** data member as const to express and document how it is used. Since the type is non-copyable and non-assignable, there is **no down side** of marking it private, otherwise please amend the guideline with this case and reasoning.

Example:

```
class AnimatedMesh : public Renderable, public AnimatedObject { 
  public:
    explicit AnimatedMesh(shared_ptr<Renderer> renderer);

    // copy/assign marked as deleted

    void animate(...) override;
    void draw(...) override;

  private:
    const shared_ptr<Renderer> renderer;
    ...
    VBO vbo;
};
```

**Comment by hsutter** [comment]
Editors call: We agree, thanks!
