### ISSUE TITLE
.at() and gsl::at() suggestion

### ISSUE THREAD

**Issue by JaroPaska** [isocpp/CppCoreGuidelines#2013]
[SL.con.3: Avoid bounds errors](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rsl-bounds) encourages the use of the `.at()` member function or the `gsl::at()` free function over the use of `operator[]`. However, this is quite inconvenient while working with nested structures. For example, here is a line from my Floyd-Warshall implementation:
```cpp
dist.at(i).at(j) = std::min(dist.at(i).at(j), dist.at(i).at(k) + dist.at(k).at(j));
```
It would be nice to have a version of `gsl::at` which accepts a parameter pack of indices, like this: `gsl::at(dist, i, j)`. This could make code using two or more dimensional arrays/vectors significantly less verbose and easier to read. Would you agree?

**Comment by hsutter** [comment]
Editors call: `gsl::span` exactly follows `std::span` except to add guaranteed bounds-checking, so we wouldn't expand its interface. C++23 is adding a multidimensional `mdspan`, so when it comes time to add C++23 support we will look at whether to have a `gsl::mdspan`.
