### ISSUE TITLE
Strike out the std::forward enforcement line 

### ISSUE THREAD

**Issue by seanbaxter** [isocpp/CppCoreGuidelines#2017]
Please strike out this line. It is wrong.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enforcement-43

It gets cited a lot as a reason to write incorrect code, eg:
https://github.com/hsutter/cppfront/issues/77

**Comment by hsutter** [comment]
Editors call: Yes, we should mention piecewise forwarding. Done, thanks Sean!
