### ISSUE TITLE
Viewing https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines hangs my browsers 

### ISSUE THREAD

**Issue by dtlhlbs** [isocpp/CppCoreGuidelines#2019]
When viewing the site at https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines in both Chrome and Microsoft Edge the browser becomes unresponsive, I can still view and click links intermittently, but most often any interaction is unavailable as the browser is unresponsive. 

![image](https://user-images.githubusercontent.com/49377835/211700865-09931a9b-8f73-4bff-855c-ac8ee54c202d.png)

![image](https://user-images.githubusercontent.com/49377835/211701204-35d33098-75b9-43b6-8779-b7a745826c78.png)

![image](https://user-images.githubusercontent.com/49377835/211700981-340171a3-89c0-416f-8873-62dc67935957.png)

**Comment by hsutter** [comment]
Editors call: It works for all of us, but we want to know if this is an issue others are experiencing too...

@dtlhlbs Both of those are Chromium... can you investigate (e.g., with the browser's debugging tools) to find out more about what is causing the hang on your system?

All: If anyone else has also had this problem, please comment here with any additional details about what caused it that can help us reproduce it, or workarounds you found worked.

**Comment by BjarneStroustrup** [comment]
Odd. I just tried Chrome, Edge, and Firefox and it worked in each case.

**Comment by dtlhlbs** [comment]
This is only an issue on my work laptop and only affects this website. I updated Chrome and Edge with no change, I disabled extensions with no change. I tried it on my personal laptop and it's fine. We can probably close this as something unique to my setup.

**Comment by dtlhlbs** [comment]
No errors in the devtools console. I'll try to debug via the performance tab and if I find anything useful I'll post it here.

**Comment by luyendt** [comment]
I got similar issues when viewing the site at https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines in both Chrome and Microsoft Edge the browser, even with incognito mode. The browser got hang, no responding when I do scrolling up/down. It happens on my laptop and some of my co-worker's laptop, meanwhile it works well on some other laptops.
Any solution so far?
