### ISSUE TITLE
Some internal links are not working

### ISSUE THREAD

**Issue by rogerorr** [isocpp/CppCoreGuidelines#2021]
When I view the CG in a browser, some of the hyperlinks to other sections within the CG are not working.

For example, in the second paragraph there are internal links for "[the introduction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-introduction)" and "[here](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#SS-ack)"

However, the *targets* for these links are not found.

(I've tried with both Chrome and Edge on Windows 11)

The introduction sections does have two anchors, either of these work:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#in-introduction

and 

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#user-content-S-introduction

It would make the document easier to read online if these links worked.

**Comment by amateomi** [comment]
Based on the links you provided, I'm assuming you're reading the Core Guidelines as a Markdown file on GitHub. If so, none of the internal hyperlinks work for me (firefox, win10). I don't think it's intended to read the Core Guidelines this way. You can use [GitHub Pages website](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines).

**Comment by rogerorr** [comment]
Thanks, I wasn't aware of that distinction; makes sense.
I'll close the issue
