### ISSUE TITLE
Why does rule R.12 exists if we have rule R.1?

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#2024]
I have a small question about rule R.12 on behalf of the Philips company. Rule R.12 is "Immediately give the result of an explicit resource allocation to a manager object". It looks like this is a contradiction with rule R.1: "Manage resources automatically using resource handles and RAII". If you manage resources automatically, rule R.12 will never fire. Or to put it the other way around, whenever R.12 fires, R.1 will fire too. If this is the case then it is better to revise rules because they should be independent. Or do I misunderstand rule R.12?

**Comment by neithernut** [comment]
Ideally you'd just follow R.1 and be done with it. However, you may need to work with an API which doesn't provide any RAII types but only "bare" resources. For example, C APIs don't feature RAII.

In such cases, you could construct your own RAII type specific to the resource, but that may not always be practical (e.g. when you only need to handle said resource in a single place) and even if you do, R.12 still applies to your RAII implementation.

Maybe somewhat related: #1990

**Comment by hsutter** [comment]
Editors call: @neithernut is correct. Thanks!
