### ISSUE TITLE
Strengthening 'move' requirements in F.18 

### ISSUE THREAD

**Issue by ccotter** [isocpp/CppCoreGuidelines#2026]
F.18 suggests 

 > Flag all X&& parameters (where X is not a template type parameter name) where the function body uses them without std::move.

https://reviews.llvm.org/D141569#4048359 raised a question about code where the function body uses the parameter in a `std::move`, although it doesn't actually call a move constructor or assignment operator. Should we strengthen F.18's enforcement to flag parameters that are never passed to a move copy constructor or assignment operator?

Another twist is that some libraries like [Folly's Future](https://github.com/facebook/folly/blob/main/folly/docs/Futures.md) declare destructive member methods as `&&` qualified:

```
void future_sink(Future<int>&& f) {
    // f.then(...); // does not compile. no non-&& qualified member 'then'
    std::move(f).then(...); // after this line, 'f' should not be accessed, as if it were moved from.
```

**Comment by cubbimew** [comment]
I think that example that calls and discards an `std::move` should violate [ES.56: Write std::move() only when you need to explicitly move an object to another scope](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es56-write-stdmove-only-when-you-need-to-explicitly-move-an-object-to-another-scope)

**Comment by ccotter** [comment]
Thanks for pointing that out. That should be sufficient for what I was interested in answering with this.

I have a second related question, which I'll ask here: F.19 added a qualifier on the enforcement:

 >  or std::forwarding it more than once but qualified with a different data member exactly once...

Should we have a similar qualification? I think I might be too pedantic here, and I should assume that std::move-ing data members counts here? This is in the context of implementing the clang-tidy check for F.18.

**Comment by BjarneStroustrup** [comment]
Editors call. We think that allowing moving individual parts of an object is too hard to verify, so we think that we should require moving the whole object. We need time to consider this and phrase it properly.
This would apply to F.19 also.

**Comment by ccotter** [comment]
Thanks - I think this has answered my questions.
