### ISSUE TITLE
C.137 is not clear to me

### ISSUE THREAD

**Issue by wyzzoo** [isocpp/CppCoreGuidelines#2033]
Why use virtual inheritance instead of normal inheritance? To get rid of diamond problem?
I think adding the explanation/bad example will make it more clear for me.
Does anyone else have the same confusion?

**Comment by markyin** [comment]
In the "reason" section, it said:

> Allow separation of shared data and interface. To avoid all shared data to being put into an ultimate base class.

**Comment by wyzzoo** [comment]
> In the "reason" section, it said:
> 
> > Allow separation of shared data and interface. To avoid all shared data to being put into an ultimate base class.
> 
> Hope it's helpful for u.


I think this explains why extract utility from the interface.
But my confusion is why to use virtual inheritance
```
class Derive1 : public Interface, virtual protected Utility {
```
instead of regular inheritance.
```
class Derive1 : public Interface, protected Utility {
```
My guess is virtual inheritance can get rid of the diamond problem. But I don't know CPP that well, to support my guess. I think an explicit explanation/bad example will make things more clear.

**Comment by cubbimew** [comment]
if you forget `virtual`, `Utility`'s data members will be duplicated; see https://en.cppreference.com/w/cpp/language/derived_class#Virtual_base_classes  for a brief intro

**Comment by wyzzoo** [comment]
> if you forget `virtual`, `Utility`'s data members will be duplicated; see https://en.cppreference.com/w/cpp/language/derived_class#Virtual_base_classes for a brief intro

That's solved my confusion, thanks.
