### ISSUE TITLE
I.2 - Clarification regarding private mutable static members

### ISSUE THREAD

**Issue by bjosv** [isocpp/CppCoreGuidelines#2039]
The clang-tidy check [cppcoreguidelines-avoid-non-const-global-variables](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-non-const-global-variables.html) covers the `I.2` enforcement which says:
"Report all non-const variables declared at namespace scope and global pointers/references to non-const data."

Currently this checker gives warnings for a static private class member which is non-const, like in the following example:
```C++
class C {
private:
    static int i;
};
int C::i = 0;
```
```
<source>:4:16: warning: variable 'i' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables]
    static int i;
               ^
<source>:6:8: warning: variable 'i' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables]
int C::i = 0;
```
https://godbolt.org/z/GjGcee6nr

This behavior has raised some [issues](https://github.com/llvm/llvm-project/issues/47384) and also triggers warnings in well-known projects like [GoogleTest](https://github.com/google/googletest/blob/main/googletest/include/gtest/internal/gtest-internal.h#L1541).

The enforcement only mentions namespace scope, but this is a private class member which in some sense is not global.
Are the warnings from the checker correct and according to the guidelines intention?

A clarification is welcomed.

**Comment by walkthetalk** [comment]
SAME! WHY?

**Comment by jwakely** [comment]
The wording of the guidelines seems pretty clear. In your example `i` is neither declared at namespace scope, nor a pointer/reference to global data. So it's just a clang-tidy bug. And indeed it's been fixed: https://github.com/llvm/llvm-project/commit/3e2ed5701b7e0a5f5b2f0d248fe82f78e0e07267

I don't see anything that needs to be done here, so closing.
