### ISSUE TITLE
Is a rule's header's HTML anchor name still a valid `tag` inside `gsl::suppress`?

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#2044]
The specification [In.force: Enforcement](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#inforce-enforcement) allows for `[[gsl::suppress(Rh-public)]]`, where `Rh-public` is the HTML anchor name for [C.134](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-public). Is this type of tag still supported?
 Is there potential for confusion if the guidelines ever move away from their current HTML/Markdown format?

Note that currently the only way to find the appropriate anchor name for a given rule when viewing the rendered HTML is to inspect the webpage and navigate through its elements.

Update:
On the github pages, clicking on the anchor button next to a title will sometimes generate a different anchor name than the "intended" anchor name
![image](https://user-images.githubusercontent.com/89153909/220484690-2ee81f5f-8815-476b-8ad3-18954943e42e.png)
- will give `http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i13-do-not-pass-an-array-as-a-single-pointer` as opposed to `http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-array`

**Comment by hsutter** [comment]
Editors call: Sorry for the lag on this. The answer is that.

- Item numbers are for users, and users should suppress by item number. For example for I.13, the user would suppress using `[[gsl::suppress("I.13")]]`)... note that the tag will now be a string literal.

- Anchors are for tools, and tools should link by the anchor name. For example for I.13, the tool should link to "Ri-array" using `https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-array`.
