### ISSUE TITLE
Are profile names the only way of selecting multiple rules in a single `tag` inside `gsl::suppress`?

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#2046]
[In.force: Enforcement](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#inforce-enforcement) currently specifies only 3 warning "groups", one for each of the 3 profiles: `type`, `bounds`, `lifetime`.

However, one might want to be more granular, for instance suppressing all warnings under a certain [major section](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#insec-major-sections) or [subsection](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c-classes-and-class-hierarchies) i.e., `[[gsl::suppress(C)]]` or `[[gsl::suppress(C.ctor)]]`.

 If this is accepted, then certain naming conventions should be cleaned up / standardized. Some examples: 
- Throughout the CG the `C` section rules are referred to simply like `C.20` or `C.160`, even if they are in different subsections (`C.20` is under `C.ctor` and `C.160` is under `C.over`). In contrast, the `SL` major section rules always include the subsection (i.e., `SL.io.4`, `SL.str.3`, ...).
- The ES family only has [implicit(unnamed) subsections](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es-expressions-and-statements) although these can probably be made explicit.
- The `C.1-C.9` rules aren't under any subsection, whereas the other `C.*` rules are under subsections.

**Comment by hsutter** [comment]
Editors call: Yes, those three profile names are the only exceptions to that suppress must give a single rule number.
