### ISSUE TITLE
Is `justification: "message"` always the last element inside `gsl::suppress`?

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#2047]
Is `gsl::suppress(justification: "message", tag)` valid? [In.force: Enforcement](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#inforce-enforcement) doesn't explicitly define an ordering.

**Comment by hsutter** [comment]
Editors call: No, that is not valid. It is intended that it be like a function call, the arguments are ordered.
