### ISSUE TITLE
Is the `justification` field in `gsl::suppress` case-sensitive?

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#2048]
i.e., `gsl::suppress(tag, Justification: "message")` vs `gsl::suppress(tag, justification: "message")`, ...

**Comment by hsutter** [comment]
See In.force:

![image](https://user-images.githubusercontent.com/1801526/231891744-36ec4272-affc-40b5-8f70-ac743de8e638.png)

**Comment by hsutter** [comment]
Editors call: Yes we intend it to be case-sensitive, for consistency with other code in the rest of the language.
