### ISSUE TITLE
Updating `gsl::span` for C++23

### ISSUE THREAD

**Issue by dmitrykobets-msft** [isocpp/CppCoreGuidelines#2049]
Standard span will likely get four new members `cbegin`, `cend`, `crbegin`, `crend` in C++23 (https://eel.is/c++draft/span.overview). 
Should these be added to GSL span unconditionally, or should they be guarded with C++23 feature flags?
Or in other words, considering GSL span is intended to adhere strictly to standard span's API, except with added bounds checking, does this take into account C++ versioning, or is it always assuming the latest C++ version?

**Comment by MikeGitb** [comment]
As `gsl::span` existed long before std::span (c++14 vs c++20) anyway, I see no reason, why it should ty individual features to the current c++ version.

**Comment by hsutter** [comment]
Editors call: Yes, please do track the C++23 additions and add those functions, and please make them always available without checking the standard version -- there should be only one `gsl::span` interface that is always in sync with the latest `std::span` interface.
