### ISSUE TITLE
Enum.1 suggests that enumerations are the only possible substitution for macros

### ISSUE THREAD

**Issue by pauljansen42** [isocpp/CppCoreGuidelines#2054]
We have implemented a check for rule Enum.1 ("Prefer enumerations over macros"). The enforcement for this rule states "Flag macros that define integer values".  This means that if you have defined somewhere

  #define FOO 42

as a stand-alone macro, the rule "Prefer enumerations over macros" will fire. Due to the synopsis of the rule it will be solved in the following way:

  enum Bar { foo = 42 };

isn't it better to have:

  const int foo = 42;

So shouldn't the synopsis be something like "Prefer enumerations *or constants* over macros" or the enforcement be something like "Flag *related* macros that define integer values" (and possibly combine it with Enum.2)?

**Comment by jwakely** [comment]
If you put `const int foo = 42;` in a header it has internal linkage by default, so you can have ODR violations if it's used from inline functions or function templates. Enumerators avoid that problem (but I agree they're not the only way to replace macros - but they are a simple way).

**Comment by beinhaerter** [comment]
Would `constexpr int foo = 42;` be better or have the same problems as `const int foo = 42;`?

**Comment by jwakely** [comment]
No different.

Since C++17 you can use an inline variable, but that isn't portable to older standards.

**Comment by hsutter** [comment]
Editors call: Thanks for the feedback. Right, `enum` isn't the only answer and we've now added some other alternatives.
