### ISSUE TITLE
P.3: Express intent  Example improvement    coordinates of a 2D point,

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#2058]
Hello
Could the first 4 parameter obscure example be changed to only two ints? Then it would match the clearer example on the line below

Example If two ints are meant to be the coordinates of a 2D point, say so:
draw_line(int, int, int, int);  // obscure
draw_line(Point, Point);        // clearer

Change to:

Example If two ints are meant to be the coordinates of a 2D point, say so:
draw_line(int, int);  // obscure
draw_line(Point, Point);        // clearer

**Comment by kimim** [comment]
Hi, a 2D point is represented by two ints.

**Comment by jonnygrant** [comment]
> Hi, a 2D point is represented by two ints.

yes. Sounds like you agree with my proposal. Do you have commit access to change it?

**Comment by jwakely** [comment]
> Sounds like you agree with my proposal

I don't think so.

A point is represented by a pair of numbers. If draw_line takes two points, then it needs four ints. Not two.

**Comment by jwakely** [comment]
The clear version takes two points, the coordinate of the start of the line, and the coordinate of the end of the line.

The unclear version takes four ints, the x and y coordinates for the start of the line, and the x and y coordinates for the end of the line. If you change it to just two ints, how can it draw a line?

If that's not obvious, maybe this would be a better change:

```c++
draw_line(int x1, int y1, int x2, int y2); // obscure
draw_line(Point p1, Point p2); // clearer
```

I do have access to change this, but I'm not sure it's an improvement, so I'm not going to do it without approval from the editors. You can submit a pull request if you want to suggest a change.



Maybe

**Comment by jonnygrant** [comment]
Thank you for your reply. I see what you mean now, the Point being (x,y) so that API needs two.

Your change looks good. 

I'd probably say the text being "If two ints are meant to be the coordinates of **each** 2D point:"

The "say so" wording is a bit odd. There are four instances of "say so" in the guidelines. I'd suggest to just remove them.
