### ISSUE TITLE
F.54: Consider applying the rule only when using by-value capture default 

### ISSUE THREAD

**Issue by carlosgalvezp** [isocpp/CppCoreGuidelines#2060]
Reading the rationale for the rule, it appears that the problem only occurs when having a by-value capture default `[=]`, which can seem to indicate that all is captured by value, while member variables are not.

On the other hand, I don't see why it would be a problem to have lambdas that e.g. capture all variables by reference `[&]` (which according to @hsutter "We believe that [&] is the right default capture for a local lambda" [here](https://github.com/isocpp/CppCoreGuidelines/issues/1419)). 

Would you consider updating the rule such that it only applies if using by-value capture default?

Thanks!

**Comment by hsutter** [comment]
Editors call: We agree, thanks.
