### ISSUE TITLE
ES.45: Avoid “magic constants”; use symbolic constants

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#2062]
Noticed the example doesn't show what the container is.
Maybe it's a std::vector<std::string> month; ?

Seems better to count "m" from 0. As is conventional for a container of month name strings.
If this was a vector of strings, they'd need to put an empty space at month[0]. Same issue if it was a C array of strings
const char * month[2] = {"Jan", "Feb"};

The "better still" part of the example wouldn't face this issue.

**Comment by jwakely** [comment]
> Seems better to count "m" from 0. As is conventional for a container of month name strings.

As I see it, the point of the example is that **in this code** the months are indexed from 1 to 12. Maybe that's a requirement of the application logic, maybe it's for consistency with `std::chrono::month`. It doesn't really matter, the point is that in this code the months are numbered from 1 to 12, and `month[m]` gives you the name (maybe it's a `map<int, string>`). What's the point in redesigning code that isn't shown here and isn't relevant to the example?

It's not supposed to be a good example of how to store dates in your application, it's just saying that **when you have magic constants** like 1 and 12 here, give them names. Refactoring the example to change the values of the magic constants seems completely pointless.

**Comment by jwakely** [comment]
I disagree. It's conventional for examples to show what's pertinent to the point being made. For many of the rules making the examples complete would take a hundred lines or more, defining class hierarchies and complete interfaces. That would just obscure the point being made, because the lines you're supposed to be looking at would be lost in the noise. The examples are not supposed to be complete programs, and you're not supposed to be copying them into your own code (especially they are showing the wrong way to do something!)

The intro seems clear:

> Examples are written to illustrate rules.
>
> -  Examples are not intended to be production quality or to cover all tutorial dimensions. For example, many examples are language-technical and use names like `f`, `base`, and `x`.
> -  We try to ensure that "good" examples follow the Core Guidelines.
> -  Comments are often illustrating rules where they would be unnecessary and/or distracting in "real code."
> -  We assume knowledge of the standard library. For example, we use plain `vector` rather than `std::vector`.
>
> This is not a language manual. It is meant to be helpful, rather than complete, fully accurate on technical details, or a guide to existing code. Recommended information sources can be found in [the references](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-references).

**Comment by jwakely** [comment]
Or in other words, it's assumed that you're able to look at code like `month[m]` and understand that it's accessing **some data structure** to retrieve a value. The exact type of the data structure (and even the type of the values stored in it) is irrelevant to this example. That's not what you're supposed to be focussing on here.

**Comment by jonnygrant** [comment]
Ok fair enough, I see that intro you shared.
