### ISSUE TITLE
I.24: Avoid adjacent parameters that can be invoked by the same arguments in either order with different meaning

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#2063]
```
struct SystemParams {
    string config_file;
    string output_path;
    seconds timeout;
};
void initialize(SystemParams p);
```
Better to show best practice const and & reference for that param?

That being
```
void initialize(const SystemParams & p);
```

The drawback of this interface guideline being the copying 3 objects into the struct. Seems it's only at Initialization, so it's fine.

**Comment by hsutter** [comment]
Editors call: Thanks! Note these are not parameters though, they are data members of a struct, so `const&` doesn't apply.
