### ISSUE TITLE
RF.rules: Coding rules

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#2070]
RF.rules: Coding rules

The AUTOSAR C++ link gives a 503 error
https://www.autosar.org/fileadmin/user_upload/standards/adaptive/17-03/AUTOSAR_RS_CPP14Guidelines.pdf

**Comment by cubbimew** [comment]
thanks, switched to archive.org link

**Comment by jonnygrant** [comment]
Will there be a new release generated?

RF.rules: Coding rules
Still has old link
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

**Comment by cubbimew** [comment]
it's usually after editor meetings, but sure, pushed one now
