### ISSUE TITLE
What is member variable?

### ISSUE THREAD

**Issue by GabrielDosReis** [isocpp/CppCoreGuidelines#2078]
The document uses the term "member variable" without indication of what it means.  The C++ community has been using the term "non-static data member" for over 40 years and that is well understood.  Either define "member variable" (a new terminology) or consistently use "non-static data member".

**Comment by BenjamenMeyer** [comment]
@GabrielDosReis the term "member variable" has been used to mean `non-static data member` for at least as long as I've been using it (1990's). I submit it's a well-known term.

Other types of members (static, etc) have usually been prefaced with their differences.

**Comment by cubbimew** [comment]
I'd say "member variable" relates to "non-static data member" like "method" relates to "non-static member function". One is a general programming concept, the other is how C++ makes it happen.

(I also think it rarely matters to most everyday programmers, until they are baffled by a compiler telling them "error: capture of non-variable ‘X::n’")

**Comment by iglesias** [comment]
There's a wikipedia page for "member variable" with history from 2004. I think that can be used as an argument that the term "member variable" has been widely used and is generally understandable. Having said that, "non-static data member" is more precise.

@GabrielDosReis, are the usages of "member variable" in the document ambiguous?

**Comment by hsutter** [comment]
Resolved with the merged change.
