### ISSUE TITLE
ES.30: Don’t use macros for program text manipulation

### ISSUE THREAD

**Issue by jonnygrant** [isocpp/CppCoreGuidelines#2136]
The suggested C++ stringify example doesn't compile

https://godbolt.org/z/1vj3YE5GK

**Comment by cubbimew** [comment]
closed by #2143

**Comment by jonnygrant** [comment]
So just the warning about the x,y params. Can the x,y there be removed?
```
<source>: In function 'void f(int, int)':
<source>:17:12: warning: unused parameter 'x' [-Wunused-parameter]
   17 | void f(int x, int y)
      |        ~~~~^
<source>:17:19: warning: unused parameter 'y' [-Wunused-parameter]
   17 | void f(int x, int y)
      |               ~~~~^
```
https://godbolt.org/z/hb41sfnsb

**Comment by jonnygrant** [comment]
> There is a warning about the unused x,y params. Can those x,y there be removed?
> 
> ```
> <source>: In function 'void f(int, int)':
> <source>:17:12: warning: unused parameter 'x' [-Wunused-parameter]
>    17 | void f(int x, int y)
>       |        ~~~~^
> <source>:17:19: warning: unused parameter 'y' [-Wunused-parameter]
>    17 | void f(int x, int y)
>       |               ~~~~^
> ```
> 
> https://godbolt.org/z/hb41sfnsb

#2152 filed
