### ISSUE TITLE
Turning off clang unsafe buffer warnings fails when compiling with a gcc based compiler

### ISSUE THREAD

**Issue by pirgia** [isocpp/CppCoreGuidelines#2184]
The code sections (in span and util)

```
// Turn off clang unsafe buffer warnings as all accessed are guarded by runtime checks
#if defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
#endif // defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
```

and (similarly)

```
#if defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
#pragma clang diagnostic pop
#endif
```

fails when compiling with a GCC-based compiler (the STM compiler for an STM32 microcontroller in this case).
The generated error is:

**missing binary operator before token "("**

I solved this by separating the checks:

```
// Turn off clang unsafe buffer warnings as all accessed are guarded by runtime checks
#if defined(__clang__)
#  if __has_warning("-Wunsafe-buffer-usage")
#    pragma clang diagnostic push
#    pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
#  endif // __has_warning("-Wunsafe-buffer-usage")
#endif // defined(__clang__)
```

There are 4 points that needed to be modified:
span: lines 67 and 855
util: lines 45 and 163

Thanks for your attention

**Comment by jwakely** [comment]
Alternatively, check `#ifdef __has_warning` before trying to use it.

But this is the wrong repository, I think you want to report it to the GSL:
https://github.com/microsoft/GSL/blob/b39e7e4b0987859f5b19ff7686b149c916588658/include/gsl/span#L67

**Comment by pirgia** [comment]
Oops.....
Sorry!
