### ISSUE TITLE
C.30: Define a destructor if a class needs an explicit action at object destruction - note

### ISSUE THREAD

**Issue by kobi-ca** [isocpp/CppCoreGuidelines#2188]
C.30 It says
```
Note: If the default destructor is needed, but its generation has been suppressed (e.g., by defining a move constructor),
use =default.
```

Doesn't this need to be "If the default constructor is needed ..."

the destructor is never suppressed, and the "default destructor" sounds strange.

**Comment by hsutter** [comment]
Editors call: Thanks! We agree this note should be removed,
