### ISSUE TITLE
I.2: Avoid non-const global variables, but exempt "file scope" from this rule

### ISSUE THREAD

**Issue by nolange** [isocpp/CppCoreGuidelines#2195]
The rule [I.2: Avoid non-const global variables](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i2-avoid-non-const-global-variables) states to avoid non-const global variables.

As i understand this, it seems to relate to accesses across compilation units, see:

> The initialization of global objects is not totally ordered

It is in a compilation unit.

> Report all non-const variables declared at namespace scope and global pointers/references to non-const data

Seems to exclude file scope.

As well as the subtle hint that the section is "Interfaces".

There's a discussion related to this at https://github.com/llvm/llvm-project/issues/73433

I would like to clear up the intent of the rule, for my part I would like to explicitly exempt
"file scope" from this rule (all variable declarations, definitions and uses in are one C/C++ file).
A global variable in a header should be always cause of concern.

As an example such static global / anonymous namespace variables (no external binding) can be really useful for

-   One-time initialization which can then be used from functions / static methods

     eg. loading an implementation, collection system information

-   Hooking together systems with statically allocated transports (other resource)

    imagine you use several Instances that need to be hooked up with resources,
    but you have a completely static setup for your application. Instead of allocating
    anything you can just hook up everything statically.
    (ideally completely taking out memory allocation from the initialization phase)
    
    ``` c++
    namespace {
    Queue s_simplequeue;
    SystemA onesystem{s_simplequeue};
    SystemB another_system{&onesystem, s_simplequeue};
    }
    
    /* the only externally visible function */
    SystemInterface &getSystemB() {another_system};
    ```

**Comment by hsutter** [comment]
Editors call: Thanks! We think this could make sense if everyone kept translation units small, but we've all seen some pretty humungous TUs where this advice would be abused, so we're not ready to accept that exception at this time. Sorry, and thanks for understanding!
