### ISSUE TITLE
Why isn't the exception safety mentioned in the Reason of R.22?

### ISSUE THREAD

**Issue by Boyeong0** [isocpp/CppCoreGuidelines#2197]
[R.22: Use make_shared() to make shared_ptrs](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-make_shared)
[R.23: Use make_unique() to make unique_ptrs](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-make_unique)

The exception safety is mentioned as a reason for R.23 but not for R.22. Is it because `make_shared` does less in preventing memory leaks compared to `make_unique` or is it simply omitted?
```
class X {
public:
    X() { throw std::runtime_error(); }
};

void f() {
    unique_ptr<X> p1 { new X() };
    shared_ptr<X> p2 { new X() };
}
```

**Comment by beinhaerter** [comment]
That seems just to be omitted.

**Comment by hsutter** [comment]
Editors call: Thanks! We agree that R.22 should add "It also ensures exception safety in complex expressions." (Which is still true as of C++14, and although it was fixed in C++17, the Guidelines are still generally for "C++14 and up" so we should include it.)

**Comment by CJCombrink** [comment]
Sorry for posting on a closed issue: is there someone that perhaps have a link to the paper to describe what "it was fixed" refers to?

**Comment by beinhaerter** [comment]
With C++17 the order of evaluation changed/was restricted. Here is a (randomly selected) blog post that describes the change: https://www.cppstories.com/2021/evaluation-order-cpp17/. It also has a link to the proposal that went into the standard.
