### ISSUE TITLE
Doesn't the title of ES.3 break that very guideline itself?

### ISSUE THREAD

**Issue by eyalroz** [isocpp/CppCoreGuidelines#2199]
[ES.3: Don’t repeat yourself, avoid redundant code](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-DRY)

isn't that kind of a self-repeating title? Perhaps remove one of these? Or at least make it something like "Avoid redundant code (i.e. 'Don't Repeat Yourself')"

**Comment by mdodkins** [comment]
Code can be redundant without being duplicated and that's expressed in this guideline ("or otherwise redundant"). The wording of this is a little odd though - I'm not sure 'redundant' is a great word to describe duplication. I do like the term "dead code", it's widely used and its meaning is clear.

**Comment by hsutter** [comment]
Editors call: Thanks! Repetition is useful in prose, and unuseful in code. Here, the two parts don't mean exactly the same thing, and we think that having both parts gets the message across better than either alone. Also, the title text is not code. Furthermore, the title text is not code ([sic] sorry).
