### ISSUE TITLE
Section E.27

### ISSUE THREAD

**Issue by petecasso** [isocpp/CppCoreGuidelines#2200]
In the Gadget example in this section, there's mention of using a std::pair.

Wouldn't it be more idiomatic to use std::optional, or std::expected here? It seems this section, dealing with not being able to use exceptions should be refreshed, based on language evolution.

**Comment by hsutter** [comment]
Editors call: Thanks! The guideline does generally say to 'use error codes' and that you can write your own struct, and `std::expected` is such a thing so falls under that guidance. The Guidelines don't do C++23 yet but when we do we can consider mentioning `std::expected`.
