### ISSUE TITLE
Recommend against using RAII only for release functions that can fail, including all IO

### ISSUE THREAD

**Issue by nh2** [isocpp/CppCoreGuidelines#2203]
The title may seem controversial at first, but read the details below.

The recommendations as they are today frequently introduce common critical errors.

---

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-raii currently says:

> C++’s language-enforced constructor/destructor symmetry mirrors the symmetry inherent in resource acquire/release function pairs such as `fopen`/`fclose`

Putting `fclose()` into destructors _only_ is a bad recommendation because it **enforces silent ignoring of critical errors**.

In C++, destructors

* generally must not `throw`
* cannot return information

Thus, if any form of resource deallocation error arises in a destructor, the only option is to silently ignore it.

At the same time, almost all I/O can raise important errors during `close()` or equivalent.

For example, when writing data to a file, critical errors such as `No space left on device` usually only surface during `close()`, due to buffering: When you `write()` to a file, most Operating Systems only raise errors at the time of `close()`.

Such errors must not be silently ignored! This would lead to lost data.

I have encountered countless systems that invisibly swallowed errors because they are delayed to the destructor, where they get lost.

The core guidelines should not recommend patterns that necessarily introduce these errors.

---

* RAII is not fit for releasing actions that can fail.
  This includes all I/O, including:
  * files
  * sockets
  * database connections
* RAII resource release is only safe for release actions that cannot fail.
  This includes:
  * memory allocation
  * locks

Relying on RAII for failable closes is fundamentally flawed.

The situation is extra severe when using exceptions, e.g. when using [`ostream.exceptions()`](https://en.cppreference.com/w/cpp/io/basic_ios/exceptions) to explicitly opt into exceptions for I/O, because destructors simply ignore this explicit opt-in. But it equally applies to exception-less C++, because destructors generally make returning information impossible (*).

## Proposal

I propose that the core guidelines RAII section be updated to explicitly mention this problem:

* That destructors necessarily swallow errors, so care needs to be taken when using RAII for failable resource release.
* Examples should be updated, e.g. those involving files should call `close()` explicitly, outside of destructors

For clarity, there is nothing wrong with the fact that a destructor may still _additionally_ call `close()`. It makes semantic sense that an `open()` in a constructor is paired with a `close()` in a destructor.
But the key point is that _failable resource release_ should happen outside of destructors.

### General recommendation shape for file examples

**Bad:**

```c++
{
  ofstream myfile("myfile.txt");
  myfile.exceptions(ofstream::badbit | ofstream::failbit);
  myfile << "abc";
}
```

The above introduces a silent failure at the invisible `close()` in the destructor, despite the call to  [`.exceptions()`](https://en.cppreference.com/w/cpp/io/basic_ios/exceptions).

**Good:**

```c++
{
  ofstream myfile("myfile.txt");
  myfile.exceptions(ofstream::badbit | ofstream::failbit);
  myfile << "abc";
  myfile.close();  // ensures errors are not silently ignored
}
```

I'd like to get some feedback on this; then I might attempt a PR.

**Comment by hsutter** [comment]
Editors call: Definitely use RAII and have destructors release resources, and definitely follow that destructors cannot fail (don't let destructors throw an exception). If the resource release could return error information of potential interest to the caller, provide a separate `Close` function that such a caller can call before destruction if they want to see the error. Alternatively, have the destructor put the resource that couldn't be closed into a list that can be looked at later for cleanup, and return normally. Alternatively, let the caller register an error handler with the object, and if there is a problem in the destructor the destructor can inform the caller by notifying the error handler and return normally.
