### ISSUE TITLE
Clarify ES.23: Prefer the {}-initializer syntax

### ISSUE THREAD

**Issue by tastyherring** [isocpp/CppCoreGuidelines#2204]
Does this apply to all object initialization?  

Is the guideline also recommending we should  prefer `Foo foo{};`  to `Foo foo;` when auto is not being used?

**Comment by hsutter** [comment]
Editors call: Yes, the guideline is recommending `{}` initialization. However, when we know a default constructor is available and the empty braces are redundant, it's fine to write `std::vector v;`.
