### ISSUE TITLE
gsl::span UB if used over containers of non-implicit lifetime types?

### ISSUE THREAD

**Issue by vdemichev** [isocpp/CppCoreGuidelines#2211]
The current implementation of gsl::span https://github.com/microsoft/GSL/blob/main/include/gsl/span seems to use pointer arithmetic to implement the [] operator. Which means that in C++20 the underlying range must be a slice of a valid array https://eel.is/c++draft/expr.add, otherwise this is formally an UB. This will be the case when used over a C array or std::array, however I cannot find anything in the specification that mandates that the underlying storage of std::vector is an array of its elements. 

Same problem also applies to any custom vector-like container. It in fact does not seem to be possible to make the underlying storage a valid array, if the elements are of a non-implicit lifetime type (with implicit lifetime can just rely on implicit creation by malloc or create the array implicitly with `::new (_data) unsiged char[capacity_in_bytes]` upon each reallocation).

I am not sure, can this ever actually be a problem in some exotic situation? Note the specification of std::span is different and only allows construction from iterators and not raw pointers, although the MSVC implementation uses pointer arithmetic similar to gsl::span. Maybe worth mentioning in the guidelines that gsl::span might not be formally OK to use over anything other than arrays?

**Comment by jwakely** [comment]
> I cannot find anything in the specification that mandates that the underlying storage of std::vector is an array of its elements.

The vector's allocator is responsible for starting the lifetime of an array in the allocated storage. For `std::allocator`, see [allocator.members] p5.

> It in fact does not seem to be possible to make the underlying storage a valid array, if the elements are of a non-implicit lifetime type

All array types are implicit lifetime types ([basic.types.general] p9), so all storage obtained from `malloc` or the default forms of `operator new` will have an array type implicitly created ([intro.object] p11), even if the array elements are not implicit-lifetime types.

**Comment by vdemichev** [comment]
Makes perfect sense, thank you for the clarification!
