### ISSUE TITLE
Following the rule C. 48 will require redundant recompilation

### ISSUE THREAD

**Issue by skashtanoff** [isocpp/CppCoreGuidelines#2213]
[C.48](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c48-prefer-default-member-initializers-to-member-initializers-in-constructors-for-constant-initializers) says:

```cpp
class X2 {
    int i {666};
    string s {"qqq"};
    int j {0};
public:
    X2() = default;        // all members are initialized to their defaults
    X2(int ii) :i{ii} {}   // s and j initialized to their defaults
    // ...
};
```

If we declare this class in a header file (and define its constructors) and include it in $n$ files.
Lets call them `dependecy_1.cpp`, ..., `dependency_n.cpp`.

After that, if we want to change default value for $i$ from $666$ to $777$, then we should re-compile all `dependency_*.cpp` files, because they will change. In other hand, if we place all initializers in `.cpp` file, we would have to recompile only one file.

How is it supposed to deal with this? Maybe this problem will be solved via modules, because they doesnt use includes as text substitution.

**Comment by hsutter** [comment]
Editors call: We agree there are exceptions and so the title starts with "Prefer" and the body contains an "Alternative."
