### ISSUE TITLE
C.46: Recommend marking nonexplicit single-argument constructors with `explicit(false)`

### ISSUE THREAD

**Issue by LocalSpook** [isocpp/CppCoreGuidelines#2216]
[C.46](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c46-by-default-declare-single-argument-constructors-explicit) currently just says that nonexplicit single-argument constructors are rarely justified and suggests warning for any that aren't on some whitelist. Then the GSL section recommends making intent explicit with the nonstandard attribute `[[implicit]]`. 

Since C++20 introduced conditionally explicit specifiers, we can express this portably with `explicit(false)`:

```cpp
class Complex {
public:
    explicit(false) Complex(double d);   // OK: we want a conversion from d to {d, 0}
    // ...
};

Complex z = 10.7;   // unsurprising conversion
```

(I first saw this in [P3094](https://wg21.link/P3094#implementation-experience)'s [sample implementation of `basic_fixed_string`](https://godbolt.org/z/4fh9bxfTh).)

**Comment by hsutter** [comment]
Editors call: Thanks! We understand the motivation but we don't think making such declarations longer has significant benefits.
