### ISSUE TITLE
F.55 / ES.34: Is forwarding va_list justified example? Especially to printf/scanf-like functions.

### ISSUE THREAD

**Issue by adambadura** [isocpp/CppCoreGuidelines#2218]
F.55 states in the "_Enforcement_" the following:
> * Issue a diagnostic for using va_list, va_start, or va_arg.

while ES.34 goes even further with:
> * Flag definitions of C-style variadic functions.
> * Flag `#include <cstdarg>` and `#include <stdarg.h>`

However, perhaps only `va_arg` should be flagged? `va_arg` indicates a function that actually consumes those C-style variadic arguments. In fact, the F.55 is even titled "_Don’t use va_arg arguments_", right?

Functions which only forward the variadic arguments cannot be blamed. It would only mean artificial inflow of "flags". Wrappers around `printf`-like functions (in particular from various logging frameworks) seem to be an important class of functions which are forced to use this interface because their destination uses it. What gain in flagging them?

One could rewrite such wrappers into `template` functions and use `template` variadic arguments. However, my experience is that `[[gnu::format(...)]]` (on both GCC and Clang) will refuse to validate such arguments. What you are left with is validating the format string only. Hence, not only no security was gained - the arguments eventually end up in a `prinf`-like function anyway, but also dedicated compiler specific (yet, I think common) checks are lost.

I think it would be better if both F.55 and ES.34 would make it easier for functions which only forward the C-style variadic arguments and explicitly mentioned exceptions for `prinf`-like wrappers, instead encouraging the use of compiler warnings to validate those.

**Comment by hsutter** [comment]
Editors call: Thanks!

> Wrappers around `printf`-like functions (in particular from various logging frameworks) seem to be an important class of functions which are forced to use this interface because their destination uses it.

We agree such wrappers exist, but we think such a wrapper should not also repeat an unsafe varargs interface, but should be a type-safe C++ variadic template that then wraps the unsafe varargs if it must use those in its implementation.

**Comment by adambadura** [comment]
But what benefit there is in making those wrappers variadic templates? What safety is added? Perhaps the point should emphasis that?

The loss is this: existing vendor-specific features (the `format` attribute) do not work with variadic templates. Hence, applying such transformation results in worse static analysis of formatting string and its arguments. Perhaps the point should acknowledge that as well?
