### ISSUE TITLE
reasoning behind adding `std::has_single_bit` to standard library

### ISSUE THREAD

**Issue by devendranaga** [isocpp/CppCoreGuidelines#2219]
Hi there,

i am styding C++20 and see the function `std::has_single_bit` in the standard library. The reference i am reading is here: https://en.cppreference.com/w/cpp/numeric/has_single_bit.

Is there any usecase behind of adding this member function within the standard library?

thanks

**Comment by jwakely** [comment]
Your question seems more appropriate for the std-discussion](https://isocpp.org/std/forums) mailing list, not here.

The function tests if a number is a power of two. That's useful for checking that a value is a valid alignment, e.g. for values passed to `std::align`, `operator new(size_t, align_val_t)`. This are the concrete uses we have for it in libstdc++. There are plenty of other reasons to want to check if something is a power of two.
