### ISSUE TITLE
Don't mix "default operations" and "special functions" in C.xx sections

### ISSUE THREAD

**Issue by miemoe** [isocpp/CppCoreGuidelines#2224]
In the C.xx sections we can find the term: "default operations" a lot.
I don't think the terms are used correctly in every place.

In the same sections we can find 2 times: "special functions".
I think the ISO standard uses the term: "special _member_ functions".

In my understanding the "default operations" are "special member functions" that the compiler can _generate_ for you _by default_.
If you define the "special member functions" then the compiler will only generate some of "default operations".

E.g. the section

> C.ctor: Constructors, assignments, and destructors
> 
> These functions control the lifecycle of objects: creation, copy, move, and destruction.
> Define constructors to guarantee and simplify initialization of classes.
> 
> These are default operations:
> 
> a default constructor: X()
> a copy constructor: X(const X&)
> a copy assignment: operator=(const X&)
> a move constructor: X(X&&)
> a move assignment: operator=(X&&)
> a destructor: ~X()
> 
> By default, the compiler defines each of these operations if it is used, but the default can be suppressed.
> 

should be:

C.ctor: Constructors, assignments, and destructors

These _**special member**_ functions control the lifecycle of objects: creation, copy, move, and destruction.
Define constructors to guarantee and simplify initialization of classes.

These are _**special member functions**_:

a default constructor: X()
a copy constructor: X(const X&)
a copy assignment: operator=(const X&)
a move constructor: X(X&&)
a move assignment: operator=(X&&)
a destructor: ~X()

By default, the compiler defines _**default operations**_ for each of these _**functions**_ if it is used, but the default can be suppressed.

The lines following this intro C.20, C.21, ... should be checked, for correctness of usage of "default operations."

e.g. C.20 should be
C.20: If you can avoid defining _**special member functions**_, do
as defining "default operations" in contractionary it itself: How can a user _define_ a _default_ ?

**Comment by hsutter** [comment]
Editors call: Thanks! We reworded three occurrences of "special operation" to help clarify this.
