### ISSUE TITLE
gsl::span does not work with address sanitizer

### ISSUE THREAD

**Issue by lijh8** [isocpp/CppCoreGuidelines#2232]
```
  // C++
  #include <gsl/gsl>  // github.com/microsoft/gsl
  #include <vector>
  std::vector v = {1, 2, 3};
  gsl::span s = v;
  s[3] = 1;
```

```
  # Makefile
  CPPFLAGS += -I/home/ljh/app/GSL/include
  CXXFLAGS += -fsanitize=address -std=c++2a -g
  LDFLAGS += -fsanitize=address
```

```
  Error:
  terminate called without an active exception
  Aborted (core dumped)
```

```

$ uname -a
Linux fedora 6.11.5-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024 x86_64 GNU/Linux
$ 
$ gcc --version
gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)
$
$ coredumpctl list
Sun 2024-11-03 04:28:06 CST 9150 1000 1000 SIGABRT none     /home/ljh/doc/hello_cpp/src/main/main      -
$ 
$ coredumpctl debug
...
       Message: Process 9150 (main) of user 1000 terminated abnormally without generating a coredump.
Coredump entry has no core attached (neither internally in the journal nor externally on disk).
$ 
```

1. When out of bound in gsl::span happens, and address sanitizer is enabled,
    there is no core dump generated.

2. There is no filename, line number reported related to the error.

3. When out of bound in gsl::span happens, address sanitizer can not detect it.

4. Are sanitizers considered a help of C++, or considered out of scope of C++?

**Comment by jwakely** [comment]
This seems to be related to the gsl library, not the core guidelines.

Whether a coredump is generated has nothing to do with gsl.

Address sanitizer cannot detect an out of bounds write in this code because an out of bounds write never happens. gsl::span prevents it from happening.
