### ISSUE TITLE
C.139 - remove note about capping virtual functions

### ISSUE THREAD

**Issue by WelliSolutions** [isocpp/CppCoreGuidelines#2236]
[C.139](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c139-use-final-on-classes-sparingly) says

> Note: Capping an individual virtual function with final is error-prone as final can easily be overlooked when defining/overriding a set of functions. Fortunately, the compiler catches such mistakes: You cannot re-declare/re-open a final member in a derived class.

I don't consider this as error-prone. Sure, it generates a compiler error, but that's not the common sense of error-prone.

If you consider this error-prone, let me make this statement as a counter-argument:

> The definition of an `int` is error-prone as quotation marks can easily be overlooked when defining an int. Fortunately, the compiler catches such mistakes: you can't assign a `string` to it. 

Proposal: simply remove the note. Using `final` on virtual methods works as in Java or C#. It's just normal to get a compiler error.

**Comment by hsutter** [comment]
Editors call: Thanks! We agree and will remove the note.
