### ISSUE TITLE
Where to put Preprocessor guidelines?

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#226]
Wondering in we should add a Preprocessor category for guidelines about macros, ....

**Comment by hsutter** [comment]
There are some guidelines to not use macros to make functionlike things, to change the meaning of code, etc. We don't think they need to be pulled into their own section. They can be found by searching for `ifdef` and `define`.

**Comment by viboes** [comment]
My concern was, where to put guidelines that could justify the definition of the macros Expect and Ensure as done on GSL or the opposite, guidelines that could be used to say, how, GSL definition of Expect and Ensure goes against the C++ Core guidelines ;-)
