### ISSUE TITLE
Provide PDF version in releases

### ISSUE THREAD

**Issue by tdicola** [isocpp/CppCoreGuidelines#23]
This is an awesome document that I'd love to print out and read offline, but GitHub doesn't provide a nice way to print markdown docs (you basically get what's rendered on the page and there's a ton of wasted space & bad formatting).  As a suggestion, when you reach certain milestones with the doc can you render the contents to a PDF (perhaps something like this would work? http://www.markdowntopdf.com/) and create a new release on GitHub with the PDFs?  That would make it really easy for people to grab a nicely formatted version for printing.  Thanks!

**Comment by octoploid** [comment]
You can easily do it yourself with http://pandoc.org/, e.g.:

     pandoc CppCoreGuidelines.md --latex-engine=xelatex --variable fontsize=11pt --variable papersize=a4paper --variable geometry=margin=2.4cm --variable mainfont="Lexicon" --variable monofont="TheSansMonoCd" -o core.pdf

**Comment by octoploid** [comment]
Adding  "-f markdown-blank_before_header" is needed to render the headers correctly.

```
pandoc CppCoreGuidelines.md -f markdown-blank_before_header --latex-engine=xelatex --variable fontsize=11pt --variable papersize=a4paper --variable geometry=margin=2.4cm --variable mainfont="Lexicon" --variable monofont="TheSansMonoCd" -o core.pdf
```

**Comment by octoploid** [comment]
I've uploaded an A4 and a letter version:
https://github.com/octoploid/CppCoreGuidelines/raw/master/CppCoreGuidelines_a4.pdf
https://github.com/octoploid/CppCoreGuidelines/raw/master/CppCoreGuidelines_letter.pdf

**Comment by gdr-at-ms** [comment]
See comments about use of pandoc.

**Comment by tkruse** [comment]
In #154 I described how I also got syntax highlighting and section links to work.

**Comment by Wilbeibi** [comment]
@octoploid Hi, it seems these two links are not valid anymore.

**Comment by xiaoerlyl** [comment]
@Wilbeibi xidianer ?
