### ISSUE TITLE
Consider "Avoid using trigraphs" rule?

### ISSUE THREAD

**Issue by delta-nry** [isocpp/CppCoreGuidelines#233]
Avoiding the use of trigraphs may be considered a self-evident rule by many people, but as of this time of writing, trigraphs are not mentioned in the Guidelines. Please note that I am not proposing that trigraphs should be banned outright, as they may still be useful in certain situations and I do not feel that I have the authority to impose that restriction on all Guideline users.

**Comment by gdr-at-ms** [comment]
Trigraphs are no longer part of C++, so we are not exceedingly worried about them.  Most compilers disable them by default - when they are supported.


-------- Original message --------
