### ISSUE TITLE
Re I.2: "global variable" is not a standard term

### ISSUE THREAD

**Issue by tkoeppe** [isocpp/CppCoreGuidelines#235]
The Standard doesn't really define a concept of a "global variable"; it only knows about "variables at namespace scope". The term "global" is vague; it doesn't take visibility and linkage into account, and variables at namespace scope can have varying degrees of globality.

I think it's fine to use a *colloquial* term "global", but we should define it properly before we use it. Once we have cleaned up the definition, the note regarding namespace scope can probably go away.

**Comment by hsutter** [comment]
We intend to add/extend a Glossary section and may add this. This isn't a standards document so we don't always choose to use precise standardese terminology (which is generally for people who implement C++, and not spoken by people who use C++) because it can be confusing in a general document.
