### ISSUE TITLE
NL.8 vs. NL.10

### ISSUE THREAD

**Issue by alrekr** [isocpp/CppCoreGuidelines#239]
NL.10 states that camelCase (of any type) should be avoided. NL.8 shows examples of CamelCase and camelCase. 

I get that NL.8 takes precedence over NL.10 and I do think that NL.8 makes sense. But there's still a clash in those two guidelines. 

I don't have a better solution; either examples in NL.8 should be removed only leaving Stroustrup or ISO++, or some caveat in both .8 and .10 should be added.

**Comment by paulbendixen** [comment]
IMHO the discussion of whether to use camelCase or underscore does not belong here.
The reccomendations to use a consistent style is enough.
The purpose of this document is to get people to write modern, secure bug-free code. Whether you use underscores and where you put your braces has nothing to do with that, it should be left open for people to find their own style of writing.

**Comment by alrekr** [comment]
I would just like the guidelines to be consistent. Otherwise, what's the point of having guidelines?

I don't think the discussion belongs 'here' as well, that is why I'm aiming at the guidelines themselves rather than the underlying discussion of CamelCase vs. underscored_naming.

Please note that I didn't write any of the guidelines. People much smarter than me did, and they found the two points needed to be there. Naming and Layout is certainly one of the least necessary points in the guidelines, but it's there, people will give them authority, and thus they need to be consistent.

**Comment by thecoshman** [comment]
I think the logic that you need to apply is; if you are starting out on a 'green field' project, avoid the use of camel case and stick the 'standard library' style. If however you are working with an existing library, it is preferable to just accept what ever style they are using.

It is more important to have a consistent style than to have have one particular style.

**Comment by jaredgrubb** [comment]
Looks like NL.8 has been changed to "Use a consistent naming style". I think this issue can be closed as Fixed.

**Comment by jaredgrubb** [comment]
I agree that NL.10 should be removed. Even if we all agreed that CamelCase is bad (which is doubtful), having the rule is a distraction and fodder for flame wars. Anyone that has tried to negotiate a style guide knows how quickly those conversations degenerate. NL.8 says "be consistent" and that is the right advice in my opinion.

[Edit note: Removed my prior post because this was not fixed after all. ]

**Comment by mcvsama** [comment]
I'd add that GSL sounds more like guidelines for code architecture, not for naming of identifiers or style conventions. Those two are separate types of guidelines in my opinion.

**Comment by hsutter** [comment]
We'll take another pass over this to keep these consistent. When there isn't a suggested "here's a naming you can use if you don't already have a house style" convention, people complain that there's no guidance. When there is such a suggestion, people complain when it's not the one they like. :) You can't be perfectly consistent because you'll be using libraries from people who use different conventions.

**Comment by thecoshman** [comment]
NL8 is primarily concerned about consistency; the only thing that makes a bad code style worse is when it's not used consistently. Using multiple libraries almost certainly means multiple styles, and NL8 is more or less saying, just use those libraries in the style they already are; don't go wrapping a library just for the sake of code style. Your own code, however, should stick to its own style...

    struct my_type{
        SomeLibrary::Foo foo_of_wonder;
        oThErSiLlYtHiNg::Bar bar;
    };

I think NL10 is getting more at what you maybe suggest @hsutter, when you have no existing code style, use the style standard lib. Though I do not think this rule is stated clearly enough, if that is the intent.

Perhaps this entire section needs to be re-thought; I think the intro already does a fairly good job explaining what I think we're all agreeing here. The rules in this section can then focus more clearly on just stating the style used by the stanrd.

**Comment by BjarneStroustrup** [comment]
clarified
