### ISSUE TITLE
Req: array subscript rules be taken out.

### ISSUE THREAD

**Issue by aunk** [isocpp/CppCoreGuidelines#24]
I find it increasingly hard to get compilers to digest im using a counter. And what if i want a meta engine that pops out near xeroxes of the program, or what have you and wish to change buffer sizes to protect goods inside?

**Comment by AndrewPardoe** [comment]
Aunk, the guidelines are meant to be adopted as a whole, but developers are free to opt out of any individual guidelines as they see fit. If you need to have a meta engine or variable buffer sizes in your code, you should opt out of the array subscript guidelines for those sections of your code. 

C++ is a powerful programming language. We want to preserve your ability to write powerful code. However, the requirements of any particular program don't influence the guidance. For those programs, just opt out.

**Comment by aunk** [comment]
How do i opt out?

**Comment by AndrewPardoe** [comment]
The guidelines are meant to be enforced by your compiler or static analysis tools. Opting out globally is equivalent to not apply that particular guideline to your code. Opting out for a specific section of your code should be possible by adding a #pragma(suppress, xxxx) or [suppress: xxxx] attribute that references the particular guideline enforcement to suppress.

Microsoft’s version of the enforcement tooling will support both these mechanisms to opt out.

**Comment by aunk** [comment]
Btw, would you look at github.com/aunk/press and tell me if it works? Not one coder will give me a straight eye for it. I just want to know if it works. And i don't have a pc to do it on. It's in C++. Thanks.
