### ISSUE TITLE
Example and Enforcement for Enum.1

### ISSUE THREAD

**Issue by hallsoftware** [isocpp/CppCoreGuidelines#243]
I'm having trouble updating my fork on Github (I'm new to git) and therefore don't know how to create pull request.  Hopefully, the following will still be helpful.

------------------------------

### <a name="Renum-macro"></a> Enum.1: Prefer enums over macros

**Reason**: Macros do not obey scope and type rules.

**Example**:

*Bad Code*:

    // webcolors.h (third party header)
	#define RED   0xFF0000
	#define GREEN 0x00FF00
	#define BLUE  0x0000FF
    
    // productinfo.h
    // The following define product subtypes based on color
	#define RED    0
	#define PURPLE 1
	#define BLUE   2
    
If both of the above headers are `#include`d in a single source file, then there will be a naming conflict between the two RED macros and the two BLUE macros.  Code that depends on one value (ex: RED being 0xFF0000) will not work properly if the second definition is active (RED being 0 in our example).

To fix this, we want to use enums in a properly defined scope:

    // productinfo.h
    namespace product
    {
        enum color
        {
            red,
            purple,
            blue,
        };
	}

Now to access product colors, one must specify the product scope. (Ex: `product::red`)  This will help avoid naming conflicts.

Even better, use `enum class`:

    // productinfo.h
    namespace product
    {
        enum class color
        {
            red,
            purple,
            blue,
        };
	}

[Enum.3: Prefer class enums over ''plain'' enums](#Renum-class) explains why this is better.

**Enforcement**:

Look for multiple lines of macro definitions that expand to integer constants.  These likely can be changed to use enums.

**Comment by hsutter** [comment]
Thanks, adding an example like this will be helpful. Bjarne will look at this and Enum.1 and Enum.3 together.

**Comment by hallsoftware** [comment]
My pleasure!

**Comment by thecoshman** [comment]
Considering there is a rule already explaining why you should prefer `enum class` ove plain `enum`, I'd not bother with the plain enum example. The key point here is to use enums.
