### ISSUE TITLE
Suggestion: F.28: When a function has no arguments, leave the argument brackets empty

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#245]
# F.28: When a function has no arguments, leave the argument brackets empty

## Reason

In C++ this is the standard [1] or considered bad style [2], or even an `abomination` [3]. This is in contrast to C, in which it is considered good style. To prevent the ambiguity, consider this rule when writing good C++ code.

## Example

```
int f(void); //error: abomination
int g(); //OK: g takes no argument
```

## Exceptions

None

## Enforcement

Let the compiler generate a warning when the function has `void` written in its arguments.

## See alsos

None

## Notes

In C using `void f(void);` is an example of good style.

## Discussion

See references

## References
 
 * Working Draft, Standard for Programming Language C++. 2014-08-22. N3936. Paragraph C.1.7. First change. 'In C++, a function declared with an empty parameter list takes no arguments. In C, an empty parameter list means that the number and type of the function arguments are unknown.'
 * https://isocpp.org/wiki/faq/newbie#void-in-param-list :
```
Should I use f(void) or f()?  

f()

C programmers often use f(void) when declaring a function that takes no parameters, however in C++ that is considered bad style.
```
 * http://www.stroustrup.com/sibling_rivalry.pdf

**Comment by hsutter** [comment]
We think it's a good rule. Bjarne will add it.

**Comment by BjarneStroustrup** [comment]
added as NL25
