### ISSUE TITLE
Suggestion: Non-rule 10: Raw for-loops should use the minimal required conditional

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#246]
# NR.10: Raw for-loops should use the minimal required conditional

**Reason**: 

Suppose a simple for-loop counting from 0 to 10 without changing the for-loop counter. One could argue that `operator!=` is all that is needed to end that loop and allows one to reason about what happens in the for loop. However, using `operator<` is just as good and commonly used.

**Example**s:

```
for (int i=0; i!=10; ++i) {} //Good
for (int i=0; i<10; ++i) {} //Just as good: i has expected simple behavior
```

**Alternative**s: none

**Exception**s: none

**Enforcement**: not possible

**See also**s: none

**Note**s: The non-rule is proposed at #187

**Discussion**:

**Comment by AndrewPardoe** [comment]
Revisited this today in our editors' discussion. The one with `<` isn't just as good--we tend to think that one should use the minimal required condition (e.g., `!=`). 

C programmers tend to use `<`, but Koenig and Stepanov started using `!=` in the STL. You can't use `<` for algorithms on lists, and `unsigned` loop variables cause issues. 

Do we want to have a guideline or a note somewhere about what we should do? Closing this issue in favor of the work proposed in #1098.
