### ISSUE TITLE
ES.78: Suggested example, enforcement

### ISSUE THREAD

**Issue by Eliyahu-Ravuna** [isocpp/CppCoreGuidelines#249]
I suggest the following text for the example and enforcement of ES.78.

Eliyahu Ravuna

### <a name="Res-break"></a> ES.78: Always end a `case` with a `break`

[...]

##### Example, bad

    switch(eventType)
    {
    case Information:
        update_status_bar();
        break;
    case Warning:
        write_event_log();
    case Error:
        display_error_window(); //in addition to write_event_log() - bad
        break;
    }
    
##### Example, good

    switch(eventType)
    {
    case Information:
        update_status_bar();
        break;
    case Warning:
        write_event_log();
        break;
    case Error:
        write_event_log();	
        display_error_window(); //the intention is clear - good
        break;
    }

[...]

##### Enforcement

(Simple) Every non-empty `case` should end with a `break`.

**Comment by richelbilderbeek** [comment]
I can imagine places where you would like to do a fall-trough `case`. I will show a trivial example here that I can imagine in some dice and/or RPG games:

```
int dice_roll{ /* some random number */ };
switch (dice_roll) {
  case 1: case 2: case 3: std::cout << "You die!\n"; break;
  case 4: case 5: std::cout << "You are poisoned!\n"; break;
  case 6: std::cout << "You are lucky\n"; break;
}
```

But I do see this more as an exception. I think the rule you suggested will catch more errors than cause trouble.

**Comment by avakar** [comment]
@richelbilderbeek, note the word *non-empty* in "Every non-empty case should end with a break."

**Comment by MichaelCook** [comment]
FWIW, the Coverity static analysis tool recognizes a comment where the
"break" should have been. The presence of the comment suppresses any
diagnostic. (The actual text of the comment doesn't matter.)

case 'a':
  f();
  // no break / fall through
case 'b':
  g();
  break;

Michael

**Comment by grahamreeds** [comment]
The rule where I work is if you have a fall-through you have to document it
explicitly. Ie:

case IDOK:
  doSave():
  /* fall through */
case IDCANCEL:
  doCleanup()
  break;

GR

**Comment by thecoshman** [comment]
I can think of valid reasons to break this rule, but I think simply having to put a comment to that effect to suppress the warning is fair enough.

**Comment by BjarneStroustrup** [comment]
Changed to say "non-empty case". There is a [[fallthrough]] proposal in the works.
