### ISSUE TITLE
Implementation of alternative to dynamic_cast way of identifying types

### ISSUE THREAD

**Issue by mcvsama** [isocpp/CppCoreGuidelines#251]
Some libraries make their own `int type()` methods for identification of types, to avoid using dynamic_cast. Every subclass is supposed to return a different integer. It's easy, but it might be harder to maintain if user is allowed to add his own subclasses.

My idea is to use `const char* type()` that points to publicly visible static member of the class, which can be a name of a class for example (with namespaces and stuff, so it's unique).

Pros:
* still as fast as an int
* better to debug (if the string is meaningful).
* no need for extending some common enum where all such types are listed, the ID is contained in the class itself (a static public data member).

Cons:
* can't use in a switch() without casting.

**Comment by thecoshman** [comment]
You can use [std::type_index](http://en.cppreference.com/w/cpp/types/type_index) for this for the most part. Fairly sure that covers the needs you have listed here, plus it stops you from needing to implement anything in each class, something that could be very easy to get wrong.

**Comment by BjarneStroustrup** [comment]
See C.146. There is a huge variety of ways of "Faking RTTI" and they are all less than general and somewhat error-prone.
