### ISSUE TITLE
Import certain identifiers with `using` instead of addressing them with namespace prefix

### ISSUE THREAD

**Issue by mcvsama** [isocpp/CppCoreGuidelines#252]
If there's specialization of some std functions (like std::swap), use:
```c++
using std::swap;
swap(a, b)
```
instead of
```c++
std::swap(a, b)
```
Argument-Dependend Lookup ensures the specialized swap() will be used, when in second example it may or may not be used, depending on code layout.

**Comment by mcvsama** [comment]
This is related to C.5. Maybe it would be worth mentioning in C.5 that specializations like swap() should also be put in related namespace instead of std.

**Comment by BjarneStroustrup** [comment]
C.165 added
