### ISSUE TITLE
Suggestion: NR. 11: you do not need to write `return 0;` at the end of the `main` function, but you may

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#259]
# NR. 11: you do not need to write `return 0;` at the end of the `main` function, but you may

## Reason

You do not need to write `return 0;` at the end of the `main` function, because the Standard adds this for you (see references 1 and 2). But if you like, you can keep it

Earlier `return`s are just fine.

## Example

```
int main() {
  return 0; //Unnecessary, but OK
} 
```

```
int main() {} //OK
```

```
int main() {
  //
  if (is_already_done) return 0; //OK: Earlier return
  //
  // Possibly a 'return 0;' here 
} 
```

## Exceptions

None

## Enforcement

None

## See alsos

None

## Notes

One can also return EXIT_SUCCESS and EXIT_FAILURE, which are macros within the STL.

This non-rule originated from #182 and was declared a non-rule by Herb.

## Discussion

See references

## References

 * [1] C++. International Standard. ISO/IEC 14882. Second edition. Paragraph 3.6.1.5
 * [2] Working Draft, Standard for Programming Language C++. International Standard. ISO/IEC document number N3936. 2014-08-22. Paragraph 3.6.1.5

**Comment by hsutter** [comment]
There's only one `main` per program and this one line does no real harm. It doesn't seem worth having a rule against it.
