### ISSUE TITLE
Error in example in F.4

### ISSUE THREAD

**Issue by mrwonko** [isocpp/CppCoreGuidelines#27]
int m3 = min(-1,v);             // run-time evaluation
    constexpr int m4 = min(-1,2);   // error: connot evaluate at compile-time

I take it that second line should read

    constexpr int m4 = min(-1,v);   // error: connot evaluate at compile-time

**Comment by gdr-at-ms** [comment]
Was fixed.

**Comment by gdr-at-ms** [comment]
Closed #27
