### ISSUE TITLE
"Type.2: Don't use static_cast downcasts. Use dynamic_cast instead." only works for polymorphic objects

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#270]
If the object is not polymorphic, then dynamic_cast cannot replace static_cast. This should be explicitly mentioned in the rule.

**Comment by hsutter** [comment]
Bjarne will add wording to cover this. Part of the answer is that if it's not polymorphic you shouldn't be using `static_cast` either.

**Comment by BjarneStroustrup** [comment]
added an example and explanation
