### ISSUE TITLE
Add maybe_null into GSL

### ISSUE THREAD

**Issue by trebconnell** [isocpp/CppCoreGuidelines#271]
The Microsoft GSL implementation includes a maybe_null class.  This class seems like a good idea to me, but is not currently mentioned in the guidelines.

**Comment by thatbrod** [comment]
What's the difference between a maybe_null and a pointer _not_ wrapped 
by not_null?

**Comment by trebconnell** [comment]
Their class gives the option for runtime analysis of whether you're checking for null before accessing the pointer.  An alternative would be to instrument the compiler to do this.

**Comment by hsutter** [comment]
This class was a leftover during experimentation. It makes code verbose and should be removed from the GSL implementation.
