### ISSUE TITLE
Is it new feature of std::find or just a typo in P.1 second example for better style?

### ISSUE THREAD

**Issue by enzochiau** [isocpp/CppCoreGuidelines#272]
In the *P.1: Express ideas directly in code* section, the second example for better style. It use *std::find* as below:

    auto p = find(v, val);

But I think the *std::find* needs *v.begin()*, *v.end()*, and *val*. 

Is it a new feature or just a typo for the example?

**Comment by cubbimew** [comment]
It's how it works with Ranges TS

**Comment by gdr-at-ms** [comment]
This is a style possible the Concepts TS.
