### ISSUE TITLE
Should 'implicit' in GSL.Util be a macro or an attribute

### ISSUE THREAD

**Issue by neilmacintosh** [isocpp/CppCoreGuidelines#282]
[[implicit]] seems like another standards-conforming alternative that could have the same documentation effect.

**Comment by hsutter** [comment]
Violent agreement, being fixed.

**Comment by BjarneStroustrup** [comment]
implicit is now [[implicit]]
Ensures and Expects are macros (yuck) pending WG21 decisions.
