### ISSUE TITLE
Translate another languages

### ISSUE THREAD

**Issue by utilForever** [isocpp/CppCoreGuidelines#29]
Hello, my name is Chris Ohk, administrator of Facebook C++ Korea community (http://www.facebook.com/groups/cppkorea).
This is an awesome document that I'd love to read. C++ Korea users, too. However, they have a hard time reading because it is not Korean, but English. So, as a suggestion, I want to translate from English into Korean. Can you ask for permission? That would make it really easy for Korean people to read a nicely formatted version. Thanks!

**Comment by AndrewPardoe** [comment]
Hi Chris,

We'd love to have this document translated into other languages. You don't need permission to modify the document--this includes translation.

If you decide to take on this project, please let us know when you've made some progress and we'll figure out how to host the document or link to it as appropriate.

Thank you!

Andrew

**Comment by utilForever** [comment]
Hi, Andrew

I really appreciate you saying so! Thank you!
I want to make this project in my repository. Can do so?
Otherwise, I fork and modify it.

Chris

**Comment by AndrewPardoe** [comment]
Yes, Chris, you're welcome to make this project in your repository. We would at least want to have links from our repo to your repo so that Korean speakers around the world can find this.

**Comment by utilForever** [comment]
I created repository to translate Korean.
https://github.com/CppKorea/CppCoreGuidelines

Chris.

**Comment by AndrewPardoe** [comment]
Thanks. I'll watch that repo. Let me know when you've made some progress and I'll get links up from our repo to yours.
