### ISSUE TITLE
Suggestion: NL.19: Do not name a function 'cout_something', define `operator<<` instead

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#290]
# NL.19: Do not name a function 'cout_something', define `operator<<` instead

**Reason**: 

Because of the complex-looking syntax of `operator<<` beginners may name their
functions `cout_something`. This is unnecessary, as `operator<<` is
close to synonymous with this name, but has the added benefit that the
data type can be streamed to anything.

**Example**s:

```
void cout_my_class(const my_class& c) { //Bad
  std::cout << /* class members here */;
}

std::ostream& operator<<(std::ostream& os, const my_class& c) { //OK
  os << /* class members here */;
  return os;
}
```

**Alternative**s: none

**Exception**s: sometimes some special formatting is required. Then the function can be named something like `pretty_print_my_class`.

**Enforcement**: not possible

**See also**s: none

**Note**s: none

**Discussion**:

**Comment by miyuki-chan** [comment]
This could be generalized to other operators as well, e.g. "prefer `operator==` to `are_equal`". Also, this should probably be in section C.over.

**Comment by richelbilderbeek** [comment]
Created the general rule at #293

**Comment by thecoshman** [comment]
As you are going for a 'general rule', this can be closed. I see not point to say "use overloaded operators where appropriate", and then also have "user overloaded operatoe<< where appropriate".

**Comment by BjarneStroustrup** [comment]
We adopted the general rule as C.167: Use an operator for an operation with its conventional meaning
