### ISSUE TITLE
Don't use memcpy etc.

### ISSUE THREAD

**Issue by Horstling** [isocpp/CppCoreGuidelines#292]
This is kinda linked to #267 and maybe it's too lowlevel, but working with a old C codebase and trying to transform it to C++ makes me wish there would be a guideline that says something about not using memcpy, memset, memcmp etc.

These functions make it very hard to augment some old C structures with new C++ types (as part of a incremential transition process) because every call to these functions hidden somewhere in the code will cause some nasty errors as soon as the type they are working on becomes non-trivial.

Because there are safe replacements for all of them (std::copy, std::fill, std::equal or even just a plain assignment) I don't see any real need for the mem* functions at all today (assuming the algorithm functions are well-optimized for trivial types).

**Comment by djarek** [comment]
There is one valid use of memcpy that I can think of - reading binary protocols and the necessary type-punning. While std::copy can be coerced to do the same when deserializing/serializing, I think it would be very confusing and less readable. To be honest, a type-safe conversion function would be nice, something like:
```
std::array<uint8_t, 1024> buffer;
//fill the buffer with data to be deserialized
auto position = buffer.begin();
auto deserialized_data = convert_bytes_to<uint32_t>(position);

int value_to_be_serialized = 42;
position = convert_to_bytes<uint32_t>(value_to_be_serialized, position);
position = convert_to_bytes<int>(value_to_be_serialized, position); //Warning: No size guarantee for type int

position = convert_to_bytes<std::pair<uint32_t, uint32_t>>(std::make_pair(value_to_be_serialized, value_to_be_serialized), position); //Warning: Aggregate types are not portable

//use the serialized data in the buffer
```
This would allow tools to issue a number of diagnostics on potential problems, like:
- relying on some types having a certain size (like assuming int is 4 bytes)
- using aggregates as the source or destination for the data (we shouldn't make assumptions on the layout of aggregates)
- limited compile-time bounds checking (perhaps possible)

**Comment by neilmacintosh** [comment]
I agree that the scenario is important @djarek. `array_view` in the GSL provides methods to convert to/from byte-representation. While it does not copy the data, it might be a useful building block for writing a function like `convert_bytes_to()` or `convert_to_bytes()`. In the slide deck for my [CppCon2015 talk](https://github.com/isocpp/CppCoreGuidelines/blob/master/talks/MacIntosh%20-%20A%20Few%20Good%20Types.pdf) on array_view, I gave a quick example of using array_view to read from an incoming array of bytes in a type-safe way.

**Comment by Horstling** [comment]
How about supplying a function that returns an `array_view` to the byte representation of an object, something like:

    template <class T>
    array_view<byte> byte_representation(T& object)
    {
    	static_assert(std::is_trivially_copyable<T>::value, "T must be trivially copyable");
    	return{ reinterpret_cast<byte*>(&object), reinterpret_cast<byte*>(&object + 1) };
    }

After obtaining this view, one could use algorithms like `std::copy` or whatever to read/write the underlying bytes of an object.

**Comment by neilmacintosh** [comment]
@Horstling actually, you don't even need to do the `reinterpret_cast` yourself. `array_view` is supposed to have a constructor from single element (that it is missing in the current implementation is an oversight that is soon to be corrected). So the function could look like:

```
template<class T>
array_view<byte> as_writeable_bytes(T& object)
{
    array_view<T> av = object;
    return av.as_writeable_bytes();
}
```
`array_view::as_bytes()` is then responsible for doing all the right `static_assert` work.

**Comment by djarek** [comment]
@Horstling 
That function could break strict aliasing rules if it were inlined. We should assume that, in general, pointer casts are illegal (there are exceptions of course).

**Comment by Horstling** [comment]
@neilmacintosh
Nice. Having these tools I really don't see any need for memcpy & CO anymore.

@djarek
Can you please elaborate on this? I'm not aware of any aliasing issue when casting to a char/byte pointer.

**Comment by djarek** [comment]
@Horstling 
My bad, I noticed reinterpret_cast to a pointer cast and yelled UB too soon. You're absolutely right, the standard guarantees that any pointer can be cast to char/byte pointers. That takes care of serialization, what about serialization? Casting char/byte to other types results in UB.

**Comment by Horstling** [comment]
@djarek
Deserialization could look something like this:

    void read(array_view<byte> packet)
    {
        Foo f = {};
        auto f_bytes = as_writeable_bytes(f);
        if (f_bytes.size() == packet.size())
    		std::copy(packet.begin(), packet.end(), f_bytes.size());
    }

This only involves casts to char* under the hood, not the other way round. A caveat is that it requires `Foo` to be default-constructible.

Neil's slides are showing this function for deserialization:

    auto foo = packet.as_array_view<Foo, 1>();

But I don't know how this is supposed to work in the general case without running into the aliasing issues you mentioned (it looks like this method is not implementend in the current version of GSL).

**Comment by thecoshman** [comment]
If you go back to the original idea here, I think it's right. These functions generally should not be used, yes there are occasionally times where it is required, but for these rare exceptions, we can use a flag to suppress such warnings at the exact location.

**Comment by neilmacintosh** [comment]
Yes, going back to objects from bytes does rely on UB. However, it is occasionally required by programs (as the beginning of the thread observes), so we added it to `array_view` to at least ensure bounds-safety in those cases. As @thecoshman observes, it would be sensible to avoid using the from-bytes version of `as_array_view` as far as possible, and being prepared to suppress warnings about using it if you do. And just as a passing note, I'm fairly sure `as_array_view()` is in the current GSL implementation.

**Comment by Horstling** [comment]
@neilmacintosh 
Of course you are right, it's there. I did a short test and my compiler choked on the `p.as_array_view<Foo, 1>()` call so I concluded rashly it's missing. I guess it's time to update my VS.

**Comment by gdr-at-ms** [comment]
I would like to encourage us not to scream "UB" too soon.  Please do keep in mind that these libraries and types will be part of your implementation (e.g. compiler) and they can conspire to do things that you couldn't be doing.  That is why they are part of the guidelines.

**Comment by djarek** [comment]
@gdr-at-ms
I got the impression that at first, the GCL is going to be more or less "standalone", doesn't that mean it has to have well-behaved code? Or am I wrong and it's going to be a "magical built-in library" from the start?

It seems that it is indeed possible to forbid using mem* functions without restricting programmers. However, we should consider providing a higher-level facility for binary serialization/deserialization that is simpler, more robust and less verbose than the read() code proposed above by @Horstling, but that is a discussion belonging to an another issue.

**Comment by gdr-at-ms** [comment]
@djarek 
"standalone" does not contradict "part of the implementation.
As a concrete example, take the alias template `owner`.  If you view it as just a "standalone" library, with no special treatment by the tools/compilers, you don't get the assistance from the checkers enforcing the guidelines.

To be sure: the code isn't not "well-behaved", and UB does not necessarily mean "daemons will fly out of your nose".  The actual reality is far more complicated than that.  This isn't an excuse for not writing good code; but we can't judge the aim and intent by just literal reading of the standards text.  It is a delicate balancing act, refinement here, strengthening there.

**Comment by neilmacintosh** [comment]
I think the discussion here has been useful but the original concern from @Horstling, appears to be addressed by the existing Bounds.4 rule (although as #267 points out...the example could be improved).
