### ISSUE TITLE
Suggestion: NL.20: Prefer operator overloading over naming what the operator does

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#293]
# NL.20: Prefer operator overloading over naming what the operator does

**Reason**: 

Operator overloading can (and is known to) be abused. Often is
it is preferred to name an operation instead of overloading an
operator. But when the operation does exactly the same as
what is expected by the operator, use the operator overload.

**Example**s:

```
bool is_equal(const my_class& lhs, const my_class& rhs) noexcept; //Bad
bool operator==(const my_class& lhs, const my_class& rhs) noexcept; //OK
```

```
bool is_not_equal(const my_class& lhs, const my_class& rhs) noexcept; //Bad
bool operator!=(const my_class& lhs, const my_class& rhs) noexcept; //OK
```

```
bool is_less(const my_class& lhs, const my_class& rhs) noexcept; //Bad
bool operator<(const my_class& lhs, const my_class& rhs) noexcept; //OK
```

**Alternative**s: none

**Exception**s: sometimes a special version of the operator is needed. Then the function can be named something like `is_equal_case_insensitive`.

**Enforcement**: not possible

**See also**s: none

**Note**s: none

This is a generalization of NL.19.

**Discussion**:

**Comment by richelbilderbeek** [comment]
A generalization of #290

**Comment by thecoshman** [comment]
You could 'enforce' this by having some sort of pattern matching, functions such as 'bool equals(const T& other);` is a bit of a code smell. Could be tricky to come up with a list of function signatures that are considered 'bad'.

**Comment by TBBle** [comment]
Is this covered by [C.167](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ro-overload) now?

**Comment by richelbilderbeek** [comment]
@TBBle : it is. This Issue can be closed then.
