### ISSUE TITLE
Suggestion: SL.10: Prefer STL containers over arrays

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#294]
[edit: layout]

# SL.10: Prefer STL containers over arrays

**Reason**: 

There is no need to use arrays anymore: 

For a constant-sized array, you can use std::array,
which does not degenerate to a pointer when passed to a function and does know its size.

For a dynamically-allocated array, you can use std::vector,
which additionally can change its size and handles memory allocation

**Example**s:

```
const int sz{10};
int v[sz]; //No need to
std::array<int,sz> w; //OK
```

```
int sz{10};
int * v = new int[sz]; //No need to
delete[] v; //Do not forget this

std::vector<int> w(sz); //OK
```

**Alternative**s:

Prefer std::vector by default, but do check the other STL containers.

**Exception**s: When you use a const-size array in the private part of a class, it will not affect anyone. But you could also use a std::array instead.

**Enforcement**: 

**See also**s:

 * Herb Sutter, Andrei Alexandrescu. C++ coding standards: 101 rules, guidelines, and best practices. 2005. ISBN: 0-32-111358-6. Chapter 76: 'Use vector by default. Otherwise, choose an appropriate container'.
 * Herb Sutter, Andrei Alexandrescu. C++ coding standards: 101 rules, guidelines, and best practices. 2005. ISBN: 0-32-111358-6. Chapter 77: 'Use vector and string instead of arrays'.
 * Marshall Cline, Greg Lomow and Mike Girou. C++ FAQs. ISBN: 0-201-3098301. FAQ 28.02: 'Are arrays good or evil?' (Answer: 'Arrays are evil').
 * Bjarne Stroustrup. The C++ Programming Language (3rd edition). 1997. ISBN: 0-201-88954-4. Chapter C.14.11 'Prefer vector over array'.
 * Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 31.6. Advice. page 924: '[2] Use vector as your default container'
 * Scott Meyers. C++ And Beyond 2012 session: 'Initial thoughts on Effective C++11'. 2012. 'Prefer std::array to Built-in Arrays'
 * Scott Meyers. Effective Modern C++ (1st Edition). 2014. ISBN: 978-1-491-90399-5. Item 1, page 17: 'Of course, as a modern C++ developer, you'd naturally preder a std::array to a built-in array'
 * Bjarne Stroustrup. A tour of C++. 2014. ISBN: 978-0-321-958310. Chapter 11.7.11: 'Prefer array over built-in arrays'
 * Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 34.7. Advice. page 1007: '[2] Prefer array over built-in arrays'

**Note**s: 

**Discussion**: I wonder if it is possible to write code that is faster with an array than with std::array, because that would be a valid pro-array argument.

**Comment by justanotheranonymoususer** [comment]
There's also [dynarray](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-faq58-is-dyn_array-the-same-as-vector-or-the-proposed-dynarray).

**Comment by gdr-at-ms** [comment]
dynarray isn't part of any technical specification.  We do not know of anybody working on it.
There are ideas and interests in stack_array, but there is no concrete proposal right now, and there is no actual implementation yet.  So, we cannot advise people to use it.

**Comment by justanotheranonymoususer** [comment]
I meant `dyn_array`, sorry. It's going to be a part of the GSL, isn't it?

**Comment by gdr-at-ms** [comment]
We have been talking about `stack_array`.

**Comment by justanotheranonymoususer** [comment]
> We have been talking about stack_array.

Who are "we"? The OP wrote:

> For a dynamically-allocated array, you can use std::vector,
> which additionally can change its size and handles memory allocation

**Comment by gdr-at-ms** [comment]
@justanotheranonymoususer "we" is "the editors of the Core Guidelines."

**Comment by AndrewPardoe** [comment]
Discussed 14 Dec 2015.

**Comment by hsutter** [comment]
We agree with the original proposal. I'll write it up. And make sure we have a rule that says vector should be the default container.

**Comment by hsutter** [comment]
Applied, thanks again!
