### ISSUE TITLE
Typo in P.7: Catch run-time errors early

### ISSUE THREAD

**Issue by ulfi666** [isocpp/CppCoreGuidelines#30]
```
void increment2(array_view<int> p)
{
    for (int x : p) ++x;
}
```
I assume that this should be:
```
void increment2(array_view<int> p)
{
    for (int& x : p) ++x;
}
```
because otherwise we're incrementing and immediately throw away the result without any side effects, which would contradict the earlier example.

**Comment by pjacak** [comment]
Same goes with passing p object by value ... there will be no efect of that
function execution.
19 wrz 2015 17:43 "ulfi666" <notifications@github.com> napisał(a):

**Comment by ulfi666** [comment]
> Same goes with passing p object by value ... there will be no efect of that
function execution.

I must admit that I'm not sure how `array_view` will be implemented in C++17, but I think it will have an effect if we iterate with `int&`. The reason is that `array_view` contains a non-const pointer to `int` much like `shared_ptr` contains a non-const pointer to `T` (unless specified).

For example, this code:
```
void foo(shared_ptr<int> n)
{
    *n = 42;
}

void bar()
{
    auto n = make_shared<int>(13);
    foo(n);
    cout << *n << "\n";
}
```
will print 42 even though the parameter `shared_ptr<int> n`isn't a reference. I believe that `array_view` will allow modification to the underlying array and therefor provide similar behavior.

**Comment by cubbimew** [comment]
This is not the C++17 array_view, this is the GSL array_view: https://github.com/Microsoft/GSL/blob/master/include/array_view.h (and yes, it's just a fat pointer, so pass by value)

**Comment by pjacak** [comment]
So if it isn't that that clear for everyone I belive that passing it by
referencje will let no doubts about that and will make this example much
cleaner.
19 wrz 2015 19:03 "Sergey Zubkov" <notifications@github.com> napisał(a):

**Comment by ulfi666** [comment]
It's getting close to sleepy time here, so I won't answer for a while after this.

Apart from the table of content, the first mention of [GSL](https://github.com/Microsoft/GSL) is in part P.8, which doesn't make sense when one reads sequentially (like me). This seems like something that should be fixed (in another issue).

However, when I copy-pasted from array_view.h into my own project, the following code worked like the first example:
```
void increment2(array_view<int> p)
{
    for (int& x : p) ++x;
}
```
if I change it to `increment2(array_view<int>&)` it fails to compile on my machine.

**Comment by neilmacintosh** [comment]
array_view is intended to be passed by-value in the majority of cases - just like you would pass a raw pointer. So the example is correct as it stands.

Separately, if you are getting a compile error passing it by-reference, please log this as an issue against the GSL. It would be helpful if you could include some test code that demonstrates the problem and details of your compiler+platform.

**Comment by pjacak** [comment]
Thanx for clarification,

Now I wonder if I have missed note about how array_view  works, or same
note about that type in document would be helpfull.
19 wrz 2015 21:38 "Neil MacIntosh" <notifications@github.com> napisał(a):
