### ISSUE TITLE
R.11: clarify the meaning of "application code"

### ISSUE THREAD

**Issue by kkeri** [isocpp/CppCoreGuidelines#300]
The term *application code* is used in the Guidelines without a specified meaning. Even if there's a common agreement on it, it's not obvious to me.

1. In R.11 it is stated that "In a large program, a naked `delete` (that is a `delete` in *application code*, rather than part of code devoted to resource management) is a likely bug".
2. In Bjarne Stroustrup's talk: "owners in *application code* is a sign of a problem".

I prefer writing reuseable code whenever I can. Now I'm in doubt what is considered application code in this context(s)? It's not always clear if a reuseable code module is application code or not.

The two extreme ends might look like this:
* everything is application code except core libraries (the STL and friends)
* only code that isn't intended to be reused counts as application code

Both cited sentences refer to something that (for the first sight) could be subject to automated checks. Even if code review is left to me, I'd like to know whether I can have a good reason at all to write down `delete` or `owner`. 

Possible solution:
(1) can be interpreted as an implicit advice that resource management code should be separated from other type of code. It sounds like essential information there. I would consider making it more explicit, e.g: 

X. Use standard resource management types whenewer possible.
Y. Clearly separate resource management code from other parts of your application.
Z. Avoid using `delete` and `owner` outside of resource management code.

**Comment by kkeri** [comment]
I was a little bit confused when I posted this issue. Now I have a cleaner view and a different approach.

R.11 "Avoid calling new and delete explicitly" speaks from the perspective of an application developer (as opposed to a low-level library developer), which is a good default, given that majority of programmers work on applications. However it is claimed that the Guidelines is for all C++ programmers.

Now I understand that not all rules are applicable in all situations. So instead defining what is application code, that is quite subtle, users may choose which rules and which profiles they apply to their sources. Ideally it is being done by running an analysis tool with different options on different code modules. This approach is beneficial, because it promotes clear separation of code in different roles (application vs. framework, high level vs. low level, etc.).

I wonder if the Guidelines can support this separation of roles by defining new rules or new profiles. What do you think?

**Comment by gdr-at-ms** [comment]
You pointed out, defining a role is subtle; at some point, good judgment need to be exercised as to determine the role.
