### ISSUE TITLE
Missing derived class code for "Discussion: Use a factory function if you need "virtual behavior" during initialization"

### ISSUE THREAD

**Issue by jeanphilippeD** [isocpp/CppCoreGuidelines#310]
Hi,
The example omit the implementation of the derived class.
It seems to make the example less easy to understand without saving much space.

In particular regarding this sentence in the discussion:
"Derived classes such as D must not expose a public constructor. Otherwise, D's users could create D objects that don't invoke PostInitialize."
=> Do we need to add friendship?
=> If the constructor of 'D' is private/protected, B::Create() and std::make_shared cannot call it.

I implemented it with friend for test in (extract bellow):
https://github.com/jeanphilippeD/SimpleExperiments/blob/master/CppCoreGuideLine/VirtualBehaviorDuringInitialization/UseFriendAndProtectedDerivedConstructors.cpp

While working on it, I wondered whether the base class could not better enforce the requirement by using a token provided in B::Create and requested by B constructor.
This way the derived class does not need to have its constructor private, nobody can call it but B::Create, and there is no need to declare friendship in all derived class:
https://github.com/jeanphilippeD/SimpleExperiments/blob/master/CppCoreGuideLine/VirtualBehaviorDuringInitialization/UseMoveOnlyToken.cpp

I hope this is helpful.
Kind regards,
Jean-Philippe.

Code extract:
This fill in the 'D' class and add friendship with B::Create.
It also call the protected default constructor in B::Create instead of in std::make_shared.

```
template<class T>
static shared_ptr<T> B::Create()    // interface for creating objects
{
    auto p = make_shared<T>( T() ); // call T() in friend Create
    p->PostInitialize();
    return p;
}

class D : public B {
public:
    void f() override { /* ...  */ };
    
protected:
	D() {}
	
	template<class T>
	friend shared_ptr<T> B::Create();
};

shared_ptr<D> p = D::Create<D>();    // creating a D object
```

**Comment by hsutter** [comment]
Thanks! For now I've added your suggested definition of `D` and left the surrounding discussion as-is.
