### ISSUE TITLE
T.81 - should this be there?

### ISSUE THREAD

**Issue by MaxDZ8** [isocpp/CppCoreGuidelines#312]
Ok, I get the solution is related to templates but it really does not seem like this should be here.
It seems to me this would be better presented as a C.145bis or in some other issue regarding slicing as there are a few before and it's not like templates are forbidden until the corresponding section.

To be completely honest I'm not sure the issue of slicing is exposed with adequate emphasis but that's for another time.

How did T.81 end up in the template section?

**Comment by BjarneStroustrup** [comment]
Added ES.63 "Don't slice"
