### ISSUE TITLE
E.25: What to do in programs where exceptions cannot be thrown

### ISSUE THREAD

**Issue by nolange** [isocpp/CppCoreGuidelines#313]
Given that there are a few cases where this is true, which are (not necessarily complete):
* You need to ensure exception paths will execute correctly in safety critical code. That means you should check in regular intervals if your critical error handling is functional. Thats hard to do if the unwinding depends on large amounts of stack that hasnt been accessed for days.
(On a similar note, this also makes virtual classes problematic since you would have to check the hidden vtable pointer and std::exception is virtual)
* You prefer to build without RTTI and exception tables. There still are problems with exceptions thrown across module (shared libraries) binaries. Those issues aren`t solvable by C++ but are nonetheless there.
* Hard realtime and the need to guarantee maximal response times

I would like a proposed default scheme, should exceptions not be used. The scheme that`s uses by the filesystem TS seems rather smart, all functions have 2 versions - one that registers errors in a std::error_code instance and one that throws.
This is an excellent idea, as it allows to create a (single binary) library that doesn`t depend on exceptions but allows their use by some simple inline functions.
The only downside might be some runtime penalty compared to a "pure" exception-variant, but I am not so sure about that since unwinding still needs to inhibit some optimizations around function calls that might throw, particularly if the function can be inlined.

**Comment by thecoshman** [comment]
If I understand correctly, the intent is that the Core Guidelines cover the default general case. As such, in general case, you should throw an exception when you hit an error. Other 'enviroments', such as embedded systems, should define their own guidelines that provide amendments.

**Comment by nolange** [comment]
Quite possible, the GSL still should cover generic guidelines and not enforce a single decision for everything (thats how I understood Bjarne, you might be right after all but we should atleast talk about it)
The more of a library is useful for a broad range of applications the better, if its easy enough to serve embedded/realtime aswell why dont do it? There is not a single default application for C++, thats probably the reason its everywhere.

filesystem TS is a good example, you can pretty much take the interface and make a implementation for an realtime OS without exceptions. Well, I had to cut away the use of std:string and simplify path but its still possible to write code that compiles and runs with MSVC library aswell.

**Comment by NicolBolas** [comment]
I don't think it's unreasonable for the guidelines to at least acknowledge that these circumstances exist and to give guidance on how to deal with them.

That being said, I think `expected`, from [N4109 (pdf)](http://wg21.link/N4109) is a much better solution than the FileSystem way of error code returning.

**Comment by nolange** [comment]
Well, at the very least, a short description and links to such alternatives would be nice. I did not know about N4109 for example

**Comment by germandiagogomez** [comment]
> That being said, I think expected, from N4109 (pdf) is a much better solution than the FileSystem way of error code returning.

+1

**Comment by BjarneStroustrup** [comment]
I added a few general rules. I'm sure that we need more, so I'm not yet closing this issue

**Comment by nolange** [comment]
Hello,

I like to add what would be more "RAII-Style" Code in my opinion, using a final_action for cleanup.
This solves the cleanup in a natural manner, in case "make_gadget" returns an allocated pointer, you would use a (potentially customized) unique_ptr.

The scheme with unique_ptr ist that the resource gets freed/destructed/cleaned unless its moved or released. Similar methods should be used with or without exceptions.
(I proposed adding a release method to final_action to cover for some of these usecases and a few more cases to get rid of try/catch blocks: https://github.com/Microsoft/GSL/issues/23 )

Further change is that the errors get written to an argument variable, allowing custom return values and easily cascading error handling (eg. you might call multiple functions with the same ec instance and only care if everything worked).
Lastly it can be wrapped easily into exception-enabled code.


```cpp
SomeReturn user(std::error_code &ec) noexcept
{
    std::error_code old = ec;
    ec.clear(); 

    Gadget g1 = make_gadget(17, ec);
    if (ec)
            return Something1;
    auto guard1 = make_final_action([&g1](){
       cleanup(g1);
    });

    Gadget g2 = make_gadget(19, ec);
    if (ec)
            return Something2;
    auto guard2 = make_final_action([&g2](){
       cleanup(g2);
    });


    if (all_foobar(g1,g2)) {
        ec.assign(foobar_error);
        return Something3;
    }

    ec = old;
    // Cleanup RAII style
}

SomeReturn user()
{
   // wrap for exception ready code
   std::error_code ec;
   SomeReturn res = user(ec);
   if (ec)
      throw std::system_error( ec ); // or custom class
   return res;
}

**Comment by NicolBolas** [comment]
I fail to see how that's "RAII-style" at all. Final Action is just syntactic sugar; more "RAII-Style" would be to encapsulate the `make_gadget` function, making your new version return some from of `expected`.

**Comment by nolange** [comment]
Sure (I referenced unique_ptr for that reason), its more RAII than the current examples in E.27 though, which use gotos or multiple cleanups in every exit branch.

**Comment by Pazns** [comment]
@nolange 
>Hello,

>I like to add what would be more "RAII-Style" Code in my opinion, using a final_action for cleanup.
This solves the cleanup in a natural manner, in case "make_gadget" returns an allocated pointer, you would use a (potentially customized) unique_ptr.

I'm utterly sorry, but your code snippet looks like absolute gibberish to me.
Too much abstraction of what the code is actually trying to do or resolve, almost no explanation whatsoever.

Also I have difficulties seeing where this is RAII.

**Comment by Sqeaky** [comment]
@nolange

If you want to write RAII, then why not put that call to cleanup in the destructor of the gadget class? If the cleanup steps can vary and really need to accept a lambda then maybe the constructor or some other member function could accept that lambda. The suggestions in E.25 seem to be about replacing throws with returning error codes, not doing away with destructors.

Do you really need to be passing around the error code by reference? Won't these references be another possible source of bugs if not carefully managed? I can see that if none of the functions retain a reference that there won't be a problem, but it can be easy to accidentally retain references. An accidental [&] in a lambda could leave it with a dangling if the lambda has longer lifetime. 

Having a member function on the gadget class could make writing the manual checks easier. I would presume most optimizers would have an easier time with it too. This is also how E.27 does with Gadget::valid().

**Comment by nolange** [comment]
I think I shouldve explained myself better or opened another Issue (or two) for this. 

I was referencing the code from E.27, I never said its a good example or clean RAII, its a first step on improving this specific example of code from the CppCoreGuidelines docs.

*) Using scope guards instead of goto exit
*) Allowing return values, which has many advantages over pass-by-reference (As speaky mentioned)

The code from E.27 is weird in any way, as you could just manage the "valid" state in the object and call cleanup in the destructor. If I want true RAII then I dont start with this code.

If I want to simultate RAII, which is the point of this chapter, then I add my guards by hand.

Further, the use of error_code as reference can be easily specified in a way you dont run into any trouble. using error code as return means I wont be able to return a gadget-by-value which means all the disadvantages will be shifted to the more important data.
It also gives you a easy path to produce code that can be similary used with or without exceptions

**Comment by NicolBolas** [comment]
"Valid" states for objects are a bad idea and should only be used when there is no better alternative. `expected` is the proper way to handle this.

**Comment by BjarneStroustrup** [comment]
I have added a few comments in section E based on the comments here. We need to add something in the Discussion section about exceptions, but the rules in E are not the place for philosophical discussions of error handling.
