### ISSUE TITLE
Moving and reference parameters.

### ISSUE THREAD

**Issue by NicolBolas** [isocpp/CppCoreGuidelines#316]
I would suggest some additions to the function parameter guidelines with regard to taking reference parameters. The guidelines already discourage reference parameters. But I think it would be useful (and very testible) to have a strong prohibition against two kinds of behaviors.

The first is moving from lvalue reference parameters:

`````
void lval_move(vector<int> &v)
{
  auto my_var = std::move(v);
  ...
}
`````

The second is the requirement to move or forward from rvalue reference parameters):

`````
void rval_no_move(vector<int> &&v)
{
  std::find(v.begin(), v.end(), ...);
  return; //Forgot to claim ownership.
}
`````

The purpose of both of these is to make sure that users can easily reason about the behavior of code that calls these functions:

`````
vector<int> v = {4, 3, 2, 1, 0};
lval_ref(v); //Either copies or passes an lvalue refernce.
v.push_back(10);
rval_ref(std::move(v)); //Either moves or passes an rvalue reference.
v.push_back(20);
`````

The call to `lval_ref` does not explicitly dictate that a move happened. Therefore, it should *not* have been moved from. So the next line ought to always be valid.

Similarly, the call to `rval_ref` explicitly dictated a move. This means that `v` should have been moved from either in the initialization of the parameter to `rval_ref` or in the actual function implementation. So the next line should always be invalid.

Statically checking these should be relatively easy. If `move` is called for a function parameter that is a non-const lvalue reference, fail. If there is a path of execution of a function where `move` or `forward` is *not* called for a parameter of non-const rvalue reference type, fail.

**Comment by hsutter** [comment]
Good reminders, thanks. I've added the rule to not `move` from a `&` parameter to F.16 and F.17. It seemed reasonable to split it into two halves, one for const and one for non-const, because that's the way the items were already split by "in" vs "in-out" use case.

We already had a rule to diagnose failure to `move` from an `X&&` parameter. As part of the parameter passing guidance merger, this should be more visible now (in the new F.18).
