### ISSUE TITLE
ES.20 Always initialize variable

### ISSUE THREAD

**Issue by danmar** [isocpp/CppCoreGuidelines#320]
This is related to my previous issue #131.

I am still not satisfied. The rule contains the text "as well as a rule protecting against used-before-set errors.". Maybe it can also warn that if people follow this rule they might get hard-to-detect hidden bugs in their code instead of easy-to-detect "use-before-set" bugs that compilers/tools normally warn about?

I am far more scared about bugs that are not detected than bugs that are detected immediately by a compiler warning (or a static/dynamic analysis tool).

I guess that people have different point of views about this rule. So I fully understand if you close this issue as wontfix.

In the rule there is this "non-comformant" example code:

    void use(int arg)   // bad: uninitialized variable
    {
        int i;
        // ...
        i = 7;  // initialize i
    }

I don't think that is a good example code. If "i" can be used in any way anywhere in the "// ..."  code I recommend that we don't initialize i as that will prevent that errors are detected.

So a better example might be:

    void use()   // bad
    {
        int i;
        i = 7;
    }

**Comment by gdr-at-ms** [comment]
We considered this issue extensively, looking at both sides of the argument, and arrived at the conclusion that led to the clarification of the guidelines based on issue #131.  As you said, people have different views on the issue and this is one where we won't change our recommendations at this point.
