### ISSUE TITLE
A typo in Introduction to type and resource safety

### ISSUE THREAD

**Issue by nikitablack** [isocpp/CppCoreGuidelines#321]
On page 7:
`X* x = 7;`
should be:
`X x = 7;`

**Comment by thecoshman** [comment]
Could you perhaps link to the exact section you are referring too? Or better still, could you perhaps look to make a PR to fix this?

**Comment by nikitablack** [comment]
It's a pdf file - `Introduction to type and resource safety.pdf`. The section is `3.4 Static model limitations`, page 7, function `pair<X*,bool> mix(X* p1, bool own, int i)`

**Comment by thecoshman** [comment]
Yeah I don't think that would be within the scope of this project. I believe that is provided as reference material.

**Comment by hsutter** [comment]
Fixed, thanks!
