### ISSUE TITLE
GSL.Util: narrow for sign change?

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#323]
The current specification of narrow() does not flag sign conversions, e.g.

    narrow<unsigned>(-1)

does not throw. 
I think that narrow() should throw on any conversion which changes the value, thus also in the sign conversion case.

**Comment by thecoshman** [comment]
Should for sure be done as a compile time check where it can. As a runtime check though, this would have to be done with something like `if (input != output) throw ~something~`.

I think this might be considered bad practice, as you are doing more than is required. Typically one would expect the caller to have performed a check first, or know in advanced. Perhaps an additional template parameter can controlled if this is 'value checked' or not, which by default would not check for you.

**Comment by mgehre** [comment]
narrow could then be implemented as follows:
````
template< class T, class U >
T narrow_cast( U u ) 
{ 
    return static_cast<T>( u ); 
}

struct narrowing_error : public std::exception {};

template< class T, class U >
T narrow( U u ) 
{ 
    T t = narrow_cast<T>( u ); 
    
    if ( static_cast<U>( t ) != u ) 
        throw narrowing_error(); 
    if ((t > 0) != (u > 0))
        throw narrowing_error(); 
    return t; 
}
```

**Comment by BjarneStroustrup** [comment]
narrow()

template <class A, class B>

constexpr bool IsSignedToUnsigned<A,B>() { ... }

 

template< class T, class U >
T narrow( U u ) 
{ 
    T t = narrow_cast<T>( u ); 
 
    if (static_cast<U>(t)!=u || (IsSignedToUnsigned<U, T>() && (t > 0)!=(u > 0)))
        throw narrowing_error(); 
if (static_cast<U>(t)!=u || (IsSignedToUnsigned<U, T>() && (t > 0)!=(u > 0)))
        throw narrowing_error(); 
    return t; 
}

**Comment by BjarneStroustrup** [comment]
narrow() should catch sign changes.

We can do slightly better with the implementation:

template <class A, class B>
constexpr bool IsSignedToUnsigned<A,B>() { /* suitable template magic */ }

template< class T, class U >
T narrow( U u ) 
{ 
    T t = narrow_cast<T>( u ); 

    if (static_cast<U>(t)!=u) throw narrowing_error(); 
    if (IsSignedToUnsigned<U, T>() && (t > 0)!=(u > 0))) throw narrowing_error();
    return t; 
}

**Comment by neilmacintosh** [comment]
Implementation in the Microsoft GSL repository has been corrected to match this suggestion. Thanks everyone!
