### ISSUE TITLE
Trigger syntax highlighting for code examples

### ISSUE THREAD

**Issue by patrickmckenna** [isocpp/CppCoreGuidelines#33]
Suggestion: make use of syntax-highlighting available in GitHub-flavored Markdown. 

[Example current view](https://github.com/isocpp/CppCoreGuidelines/blob/95f6cfcdd8209e85d398132cad481d837c6d714b/CppCoreGuidelines.md#discussion-make-base-class-destructors-public-and-virtual-or-protected-and-nonvirtual):

<img width="954" alt="no_syntax_highlighting" src="https://cloud.githubusercontent.com/assets/3589536/9977284/1a06c6cc-5eb6-11e5-9d6c-1f8e4af06b70.png">

[Example with syntax highlighting](https://github.com/patrickmckenna/CppCoreGuidelines/blob/bf0d5a54de184e8edfa06477948a612e2d7baff2/CppCoreGuidelines.md#discussion-make-base-class-destructors-public-and-virtual-or-protected-and-nonvirtual):

<img width="952" alt="with_syntax_highlighting" src="https://cloud.githubusercontent.com/assets/3589536/9977289/37b8253a-5eb6-11e5-8d86-1d7873d22495.png">

Note: many of the current code examples use indentation, rather than [fenced code block syntax](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), to trigger monospace rendering. Those examples would need to be converted to fenced code blocks to get syntax highlighting.

Happy to open a PR if this is desired.

**Comment by gdr-at-ms** [comment]
Thanks for the suggestion.
It is noteworthy that this is an issue that divides reasonable people, especially the larger C++ community, in many ways.  Some people wonder if we should similarly systematically highlight verbs and nouns in every English sentence we write :-) 
For now, we are doing without syntax highlighting, but we will definitely keep syntax highlighting in mind (e.g. comments formatted differently).

The issue about fenced code block syntax is more substantive, I think.  It would require lot of work to fix, but I suspect having an open issue won't hurt.  Thanks!

**Comment by Kristine1975** [comment]
Just for the record: It apparently (I havent't tested it) is possible to [turn off syntax highlighting in Github](https://mobile.twitter.com/greghendershott/status/561027345096916992):
1. Install the Stylish browser-addon ([Firefox](https://addons.mozilla.org/de/firefox/addon/stylish/), [Chrome](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe)).
2. Use [this stylesheet](https://gist.github.com/greghendershott/671dd311b77569ba2eaf).

**Comment by torbjoernk** [comment]
FYI: there is already a massive PR for this: #96

**Comment by Liryna** [comment]
@torbjoernk ty, I haven't found this issue before making the PR :D
The PR is massive because I removed all first tabulations that become useless after moving to syntax highlighting.

@gdr-at-ms,
The PR should be review quickly or there will be easily some conflict to fix.

**Comment by gdr-at-ms** [comment]
@Liryna Yes; we have all been busy this week; will get to that.

**Comment by AndrewPardoe** [comment]
We prefer the simple, non-syntax highlighted code blocks for the time being. Thank you, @Liryna, for making the PR but we're not merging it at the time. Sorry!

**Comment by tkruse** [comment]
Since @gdr-at-ms said "The issue about fenced code block syntax is more substantive, I think. It would require lot of work to fix, ..."
I hope you realize you can take the PR by @Liryna, then run find/replace "```c++\n" -> "```\n" and you're done.

**Comment by skyrpex** [comment]
what's the reason for not using syntax highlighting in the documentation?

**Comment by blakehawkins** [comment]
@skyrpex not all flavors of markdown support such a thing. In a word: portability.

**Comment by tkruse** [comment]
Regarding mere fencing: Note there is a tool that reformats markdown: https://github.com/wooorm/mdast. Getting the file to be idempotent would be very useful.

It's not quite the case yet, but in case you get interested, I get close with this ```.mdastrc```:
```
{
  "settings": {
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }
}
```
By adding ```"fences": true``` this will create fences (mostly correct, a handful of cases must be fixed manually).


Regarding syntax highlighting, note I could get this on github pages via Jekyll configuration: https://github.com/isocpp/CppCoreGuidelines/issues/146 without changing the source.

**Comment by gdr-at-ms** [comment]
Thanks for the suggestion, @tkruse

**Comment by novasdream** [comment]
to be portable dont need be ugly
