### ISSUE TITLE
misspelling in Abstract

### ISSUE THREAD

**Issue by S-A-Scott** [isocpp/CppCoreGuidelines#330]
The second paragraph of abstract.
"and catches many more programming logic errors than is common in code today"
should be
"and catches many more programming logic errors _that_ is common in code today"

**Comment by AndrewPardoe** [comment]
Thanks for the note, but "than" seems to be the word intended here. The whole sentence is "Following the rules will lead to code that is statically type safe, has no resource leaks, and catches many more programming logic errors than is common in code today." 

It is a long sentence. It's easier to parse if you remove some of the detail: "Following the rules will lead to code that catches more errors than is common in code today."
