### ISSUE TITLE
not_null<T> or not_null<T*>

### ISSUE THREAD

**Issue by thecoshman** [isocpp/CppCoreGuidelines#331]
In section [F16](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-f16-use-t-or-ownert-to-designate-a-single-object) both forms are used.

I believe `null_ptr<T*>` is the correct form.

**Comment by kryptan** [comment]
`null_ptr<T*>` is subset of `null_ptr<T>`.

**Comment by AndrewPardoe** [comment]
As @kryptan stated: the `not_null<T*>` is a subset of `not_null<T>`. This Item is about pointer types.
