### ISSUE TITLE
Flush-left headers

### ISSUE THREAD

**Issue by ascherer** [isocpp/CppCoreGuidelines#337]
I suggest to eliminate the whitespace between the `<a>` anchors and the actual text of `#` headers on all levels. The formatted version results in notable raggedness of the left side.

**Comment by AndrewPardoe** [comment]
@ascherer, good suggestion. Would you like to prepare a PR with the changes?

**Comment by ascherer** [comment]
Am Sonntag, 22. November 2015, 09:29:48 schrieb Andrew Pardoe:
> @ascherer, good suggestion. Would you like to prepare a PR with the changes?
Will do ASAP.

**Comment by ascherer** [comment]
See PR #413.

**Comment by ascherer** [comment]
See PR #414. (Sorry for the doublette; I merged/pushed to the wrong branch and accidentally destroyed #413.)
