### ISSUE TITLE
Suggestion: NL.26: Keep comments in sync with code

### ISSUE THREAD

**Issue by kkeri** [isocpp/CppCoreGuidelines#339]
This advice is so obvious, yet I have seen it neglected many times. I think it deserves to be included in the Core Guidelines. Suggestions for better wording/examples are welcome.

##### Reason

Out of date or misplaced comments add noise to source code and stand in the way of understanding. 
If a comment is inconsistent with the code, correctness of the code is questionable.

##### Example, bad

    // this function never returns null
    std::unique_ptr<T> foo(float f) {
        if (f < 0)
            return nullptr;  // argument checking, inserted later??

        return gen(std::sqrt(f));
    }

##### Note

Inconsistent comments often arise from copying a piece of code and modifying it in place.

##### Example, bad

    int s = 0;
    
    s += frob1;
    s += 1;  // add one for adjustment
    
    s += frob2;
    s -= 1;  // add one for adjustment

If you can't afford maintaining comments, remove superfluous and redundant parts. Leave only what is essential.
[Express intent](#Rl-comments-intent) in comments, not accidental details.

##### Example, good

    // summarize frobs - take care of individual adjustment
    int s = 0;
    
    s += frob1;
    s += 1;
    
    s += frob2;
    s -= 1;

**See also**: [Keep comments crisp](#Rl-comments-crisp)

##### Enforcement

Not possible.

**Comment by thecoshman** [comment]
I think that as a rule with higher precedence, you want to aim to reduce the need for comments. If the code itself can express clearly what it is doing, you don't need comments, and thus they never get out of data.

    // calculates the distance between two points
    float d(int x1, int x2, int y1, iny y2);

vs

    float distanceBetween(point x, point y);

That second example it is a lot clearer what the function is doing, that it takes two points. It's also not clear in the first example if the first point is `x1` and `y1` or `x1` and `x2`.

But yes, where there are comments, changes to code must be accompanied by a review of the comments. For example, I might decide to change this function to return the distance squared, obviously, I should change the function name in that case; but that also makes it easier to understand how if I see an existing `distanceBetween(...) * distanceBetween(...)`I could just swap to `distanceBetweenSquared(...)`

**Comment by kkeri** [comment]
Usefulness of comments is a hot topic, and I believe that there are estabilished arguments on both sides. It's a long story, and I don't want to be offtopic. After all, my proposed rule doesn't aim that comments are either good or bad. It says that if you do it, do it right.

I absolutely agree, expressive code is better than comments, and there is already a rule that states this (NL.1). It sounds like a higher level rule, but I guess we should rely on users in determining priority of rules for themselves, at least for rules that can't be automated.

**Comment by thecoshman** [comment]
Oh it's certainly a heated debate.

However, this is supposed to be a guideline, and thus needs to come down with some form of concrete advice. 

In which case, I would think it fair to say that *if* you have comments around the code you are working on, make sure they are updated such that they are not wrong. This could be done by re-wording as needed, or simply deleting them if the code is considered self explanatory enough.

**Comment by kkeri** [comment]
Ok, here is an updated version, with a few minor changes. I included your sentences literally, if you don't mind. Did you expect something like this?

### NL.26 Keep comments in sync with code

##### Reason

Out of date or misplaced comments add noise to source code and stand in the way of understanding. 
If the comment is inconsistent with the code, correctness of the code is questionable.

##### Example, bad

    // this function never returns null
    std::unique_ptr<T> foo(float f) {
        if (f < 0)
            return nullptr;  // argument checking, inserted later?

        return gen(std::sqrt(f));
    }

##### Note

Inconsistent comments often arise from copying a piece of code and modifying it in place.

##### Example, bad

    int s = 0;
    
    s += widget1;
    s += 1;  // add one for adjustment
    
    s += widget2;
    s -= 1;  // add one for adjustment

If you have comments around the code you are working on, make sure they are updated such that they are not wrong. This could be done by re-wording as needed, or simply deleting them if the code is considered self explanatory enough.

**See also**: [State intent in comments](#Rl-comments-intent) and [Keep comments crisp](#Rl-comments-crisp)

##### Example

    // summarize widgets - notice individual adjustment
    int s = 0;
    
    s += widget1;
    s += 1;
    
    s += widget2;
    s -= 1;

##### Enforcement

Not possible.

**Comment by thecoshman** [comment]
Oh no problem at all with you using my words like that. 

Yeah, this looks fine enough proposal to me now. Stresses the importance of keeping comments correct, whilst also highlighting nicely that they may be improved best by simply being removed.

**Comment by kkeri** [comment]
Thanks for your suggested improvement. I think it really fits better here.
Also, I don't completely trust my dictionary-english so extra eyes always come handy.

**Comment by kkeri** [comment]
No more activity on this issue, so I plan to create a PR, with a small change in wording: I'd like to change the part *such that they are not wrong* to *such that they are consistent with the code*. 

Any caveat?

**Comment by BjarneStroustrup** [comment]
I think that NL.1, NL.2, and NL.3 states what needs saying. Obviously, people don't maintain comments well, just as they don't maintain code well. I don't think we can legislate consistency.

"If the code and the comments disagree, both are probably wrong"
