### ISSUE TITLE
Where is stack_array?

### ISSUE THREAD

**Issue by mmatrosov** [isocpp/CppCoreGuidelines#347]
There is an item "[ES.27: Use std::array or stack_array for arrays on the stack](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-es27-use-stdarray-or-stack_array-for-arrays-on-the-stack)", where a type `stack_array` is mentioned. It is clear what it should do, but I see no references too it. I would expect to have it GSL, but it is no there. I cannot find any major implementation anywhere.

**Comment by neilmacintosh** [comment]
@mmatrosov you are correct, there is no implementation in the Microsoft version of the GSL at this time. Adding it has simply been lower on the priority list than other tasks for that implementation so far. However it should show up at some point in the future. If you'd like to contribute an implementation, I'd be happy to take a PR over at that repository.

**Comment by HamzaHajeir** [comment]
Any updates so far :) ?
