### ISSUE TITLE
Enforcement for "Type.8: Varags"

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#348]
The rule states for enforcement:
> Enforcement:
> Issue a diagnostic for using va_list, va_start, or va_arg. To fix: Use a variadic template parameter list instead.
> Issue a diagnostic for passing an argument to a vararg parameter. To fix: Use a different function, or [[suppress(types)]].

1) What is the rational for warning on va_list and va_start? It seems that only va_arg performs a type-unsafe operation. I propose to only warn on va_arg.

2) Just above the enforcement section, the rule notes that there are valid use-cases (e.g. SFINAE):
> Note: Declaring a ... parameter is sometimes useful for techniques that don't involve actual argument passing, notably to declare “take-anything” functions so as to disable "everything else" in an overload set or express a catchall case in a template metaprogram.

Still, the enforcement requires to flag all calls passing a vararg parameter. Is it expected to decorate all SFINAE uses with [[suppress(type)]]?
It was suggested to suppress warnings on calls if the variadic part is a single argument with literal value 0, which is what is commonly used for SFINAE checks. Is this an option for the CppCoreGuidelines?

**Comment by hsutter** [comment]
Re 1: Is there a valid use for va_start not followed by va_arg? And is there a valid use of va_list not followed by va_start (and then va_arg)? If there is I'd be happy to relax this but I don't know of one.

**Comment by hsutter** [comment]
Re 2: Good point, thanks. I've made the enforcement more specific to allow calling an `...` in an overload set.
