### ISSUE TITLE
Bad wording in section ES.23

### ISSUE THREAD

**Issue by rnburn** [isocpp/CppCoreGuidelines#351]
This text from section ES.23 is both confusing and incorrect english:
> Initialization of a variable declared auto with a single value {v} surprising results until recently

**Comment by khatharr** [comment]
I sent a PR with some fixes. Feel free to do the same when you find typos or broken grammar.

**Comment by BjarneStroustrup** [comment]
I don't see the PR, but I clarified (I hope) the text.

**Comment by GSP361-15575** [comment]
I think Gabby already merged it.

**Comment by khatharr** [comment]
I think Gabby already pulled it. Thanks though.
