### ISSUE TITLE
"Bounds.3: No array-to-pointer decay." only for implicit casts?

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#352]
It is unclear if
```
  void f(int *);
  void g() {
    int a[5];
    f((int*)a); //Explicit conversion of array to pointer
  }
```
is forbidden under this (or any other) rule.
The "Enforcement" section currently forbids implicit decay only. As far as I understand the reasoning, if you pass an array to a function expecting a pointer, you can be quite sure that that function is bounds-unsafe (because it cannot statically check the size of the passed-in array).
I.e. converting an array to a pointer is not bounds-unsafe in itself, but it allows to call bounds-unsafe functions.
Following that reasoning, I propose to also forbid explicit casts from arrays to pointers, such as in the example above.
I don't think that explicit casts should be a way to suppress this rule. For that, we will eventually have a general suppression syntax (ala [[suppress(bounds)]]).

**Comment by neilmacintosh** [comment]
@mgehre It's difficult to - in general - ban forming pointers from arrays. As you observe - forming the pointer is not necessarily unsafe. It is usually in its use that the "unsafety" occurs. In the example you gave, it would be difficult to know if `f()` intends to address only a single element, or just treat the pointer as some sort of cookie, or compare it to some other pointer value (which is safe), or whatever. So in that case, I think it's easier to rely on the fact that when `f()` is checked, any use of the pointer that is unsafe (e.g. `p[4]`) would be flagged as violating the profile.

**Comment by mgehre** [comment]
If `f()` only addresses one single element, we can use `f(&a[0])`, which is not forbidden, but makes explicit that we are only interested in the first element.

Following you reasoning, the whole rule could be removed, because we should check inside `f()` if bounds-unsafety occurs. 

I guess (correct me if I'm wrong) that this rule aims at the case where `f()` itself is not subject to checking, e.g. standard library or other external library. This rule e.g. ban using `memset` on arrays, for which then the gsl will provide a safe variant that takes an `array_view` instead.

Or is there another use case for this rule?

**Comment by neilmacintosh** [comment]
No, the rule doesn't explicitly aim at functions that are not checked against the profile. The profiles are written with the aim that all code is checked. The aim is more about making intent explicit.

The problem with implicit decay is that it is not always obvious to the caller that they have lost the size information at the callsite. At least with a cast, someone is making their intent to use the pointer to the first element of the array explicit (same goes for taking the address of an element). Whether or not the consuming function goes further than that single element is an issue for analysis of the consuming function.

**Comment by mgehre** [comment]
Thank you for the explanation.
If this rule is about making intent explicit, I would then propose to move it to another section (e.g. ES). All other rules in the profiles lead to some kind of guarantee (type safety/bound safety). This rule does not contribute to that guarantee (i.e. prevent out-of-bound access).
Moving the rule would make the profiles more focused.

**Comment by neilmacintosh** [comment]
It prevents people inadvertently passing an array as a pointer and requires them to be explicit about doing so. Both outcomes contribute to safer code.

**Comment by mgehre** [comment]
Fair enough. I have no additional arguments to present.
I will adapt the clang-tidy check to the current wording of the rule.
Thanks for the discussion!

Neil MacIntosh <notifications@github.com> schrieb am Sa., 24. Okt. 2015
03:37:

**Comment by neilmacintosh** [comment]
@mgehre thank you! It's great to see people thinking deeply about the profiles and questioning individual enforcements is part of that. And many thanks for the clang-tidy implementation of the check!
