### ISSUE TITLE
Proposal for techniques that improve ad-hoc generic code: static_if emulation

### ISSUE THREAD

**Issue by germandiagogomez** [isocpp/CppCoreGuidelines#353]
Hello everyone,

I am using successfully in my code a small tool that I think serves its purpose quite well,
given we do not have language support. 

I would like to propose this tool as an alternative to tag dispatching or naked SFINAE
for many of the cases.
Let us write an example with `static_if`. I would like to widen this writing the 
SFINAE or tag dispatching equivalents, but I do not have much time, so I leave it
out for now.

## Motivation

Some motivation for the use of `static_if` in my personal case is:

1. It is difficult to follow code with SFINAE, due to its lack of good locality.
2. It is difficult for the average programmer to write SFINAE-based code.
3. It is not easy to immediately formalize everything as a concept, so ad-hoc `static_if` 
can be useful in many real cases where you do not want to reach the level of refinement
of STL concepts, which is quite time-consuming, 
or it simply does not make sense to formalize for your use case.

## Example

Imagine we want to reuse some already written code.
We want to calculate the physics calculations from several classes in the context of
having all the static information available.
The problem is that the classes were already written and have different function names
for the same purpose. One of them has `calculatePhysics`, another one has `updatePhysics`.

Additionally, some of the classes with `updatePhysics` were patched with `correctPhysicsErrors` for some 
of the types, because there was a bug whose cause is not clear, but it was known how to correct it
for the defective classes,
so for these classes updating the physics is the combination of calling two methods.

```c++
//File A.h
namespace FrameworkA {

class Monster {
public:
    void calculatePhysics(float delta) { } };

} //ns FrameworkA


//File B.h
namespace FrameworkB {

class MainCharacter  {
public:
    void updatePhysics(float delta) {  }
};

class NPCPlayer {
public:
    void correctPhysicsErrors() {}
    void updatePhysics(float delta) {  }
};

} //ns FrameworkB

using namespace FrameworkA;
using namespace FrameworkB;

template <class T>
using has_update_physics = decltype(std::declval<T&>().updatePhysics(0.0f));

template <class T>
constexpr bool has_update_physics_v = has_op<T, has_update_physics>{};


template <class T>
using has_calculate_physics = decltype(std::declval<T&>().calculatePhysics(0.0f));

template <class T>
constexpr bool has_calculate_physics_v =
    has_op<T, has_calculate_physics>{};

template <class T>
using has_correct_physics_errors = decltype(std::declval<T&>().correctPhysicsErrors());


template <class T>
constexpr bool has_correct_physics_errors_v =
    has_op<T,  has_correct_physics_errors>{};

template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    static_if<has_calculate_physics_v<Entity>>(
        [](auto && e, float delta) {
            e.calculatePhysics(delta);
            std::cout << "CalcluatePhyiscs" << std::endl;
        },
        static_if<has_update_physics_v<Entity>>
        ([](auto && e, float delta) {
            e.updatePhysics(delta);
            std::cout << "UpdatePhysics" << std::endl;

            static_if<has_correct_physics_errors_v<Entity>>
                ([](auto && e) {
                    e.correctPhysicsErrors();
                    std::cout << "CorrectPhysicsErrors" <<
                        std::endl;
                })(e);
        })
        )(e, delta);
}

```

## Advantages:

- The code is all local. Doing the equivalent with SFINAE or tag dispatching is
more difficult to follow. Gives me the same feeling as when writing async code
without coroutines or then-style continuations.
- No need for SFINAE. SFINAE is hidden inside `static_if` implementation.
- Makes tractable the problem of having ad-hoc requirements that are not as formalized
as full Concepts. 
- Without `static_if`, there can be a combinatoric explosion of tag dispatching/sfinae
with ease.

This tool is `static_if`. My current implementation looks as follows:

```c++
template <bool Cond>
struct static_if_ {
    template <class FTrue,
              class FFalse,
              bool Cond2 = Cond,
              std::enable_if_t<Cond2, int> = 0>
    static constexpr auto get(FTrue && f, FFalse &&) {
        return std::forward<FTrue>(f);
    }

    template <class FTrue,
              class FFalse,
              bool Cond2 = Cond,
              std::enable_if_t<!Cond2, int> = 0>
    static constexpr auto get(FTrue &&, FFalse && f) {
        return std::forward<FFalse>(f);
    }
};


template <bool Cond, class FTrue>
constexpr auto static_if(FTrue && f) {
    return static_if_<Cond>::get(std::forward<FTrue>(f),
                                 [](auto &&...) {});
}

template <bool Cond, class FTrue, class FFalse>
constexpr auto static_if(FTrue && f, FFalse && g) {
    return static_if_<Cond>::get(std::forward<FTrue>(f),
                                 std::forward<FFalse>(g));
}
```

Thanks for your time.

**Comment by germandiagogomez** [comment]
I just discovered that my example will swallow any class silently in the case it does not reach any `static_if`. That can be corrected issuing an error through a static_assert if the else branch is ever reached.

**Comment by germandiagogomez** [comment]
Full working example attached.

**Comment by pfultz2** [comment]
You should use `integral_constant` for your predicates. I see no point in having a *_v variables as it can lead to ODR violations in C++14 and much more clumsy syntax as we will see:

```cpp
template <class T>
using has_update_physics = has_op<T, has_update_physics>;

template <class T>
using has_calculate_physics = has_op<T, has_calculate_physics>;

template <class T>
using has_correct_physics_errors = has_op<T,  has_correct_physics_errors>;
```

The problem with your `static_if` definition is that it becomes clumsy to chain multiple predicates of them together. A better definition would be the following:

```cpp
struct static_if_nop
{
    template<class F>
    auto else_(F&&)
    {
        return [](auto&&...) {};
    }

    template<class F>
    auto then(F&& f)
    {
        return [](auto&&...) {};
    }

    template<class Cond>
    static_if_nop else_if(Cond)
    {
        return {};
    }
};

template<bool B>
struct static_if_
{
    template<class F>
    auto else_(F&&)
    {
        return [](auto&&...) {};
    }

    template<class F>
    auto then(F&& f)
    {
        return f;
    }

    template<class Cond>
    static_if_nop else_if(Cond)
    {
        return {};
    }
};


template<>
struct static_if_<false>
{
    template<class F>
    auto then(F&&)
    {
        return [](auto&&...) {};
    }

    template<class F>
    auto else_(F&& f)
    {
        return f;
    }

    template<class Cond>
    static_if_<Cond::value> else_if(Cond)
    {
        return {};
    }
};


template<class Cond>
static_if_<Cond::value> static_if(Cond)
{
    return {};
}
```

So now you can right your function like this:

```cpp
template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    static_if(has_calculate_physics<Entity>()).then(
        [](auto && e, float delta) {
            e.calculatePhysics(delta);
            std::cout << "CalcluatePhyiscs" << std::endl;
        })
    .else_if(has_update_physics<Entity>()).then(
        [](auto && e, float delta) {
            e.updatePhysics(delta);
            std::cout << "UpdatePhysics" << std::endl;

            static_if(has_correct_physics_errors<Entity>()).then(
                [](auto && e) {
                    e.correctPhysicsErrors();
                    std::cout << "CorrectPhysicsErrors" <<
                        std::endl;
                })(e);
        })
    (e, delta);
}
```

Even more so, it becomes much easier and more natural to chain multiple functions together:

```cpp
template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    static_if(has_calculate_physics<Entity>()).then(
        [](auto && e, float delta) {
            e.calculatePhysics(delta);
            std::cout << "CalcluatePhyiscs" << std::endl;
        })
    .else_if(has_update_physics<Entity>()).then(
        [](auto && e, float delta) {
            e.updatePhysics(delta);
            std::cout << "UpdatePhysics" << std::endl;
        })
    .else_if(has_correct_physics_errors<Entity>()).then(
        [](auto && e, float delta) {
            e.correctPhysicsErrors();
            std::cout << "CorrectPhysicsErrors" <<
                std::endl;
        })
    .else_(
        [](auto&&...) {
            std::cout << "No physics" << std::endl;
        })
    (e, delta);
}
```

**Comment by germandiagogomez** [comment]
Nice input. I think I could migrate to this design.

**Comment by germandiagogomez** [comment]
> You should use integral_constant for your predicates. I see no point in having a *_v variables as it can lead to ODR violations in C++14 and much more clumsy syntax as we will see:

I always find difficult to know when ODR happens. Why does it happen if you have a variable template?

**Comment by gdr-at-ms** [comment]
Two things:
    (1) The current standards text for ODR is conceptually broken in this respect.  So are literal readings of it.  There is ongoing work to fix it.
    (2) I understand it is Halloween season, but maybe it will be helpful if people stop quoting broken texts to scary people away from conceptually sound programming practices.

We should strive to fix standards text, where they are conceptually broken, to support good idiomatic constructs.

**Comment by pfultz2** [comment]
> Nice input. I think I could migrate to this design.
> 
> I would like to support (not proposed) static_if pseudo-statement, like Alexandrescu's SCOPE.
> For that, the natural thing is to capture the environment with & instead of passing parameters, but later I think that static_if must be invoked anyway...

Well, if you want it to be more general, you could pass the `identity` function to the lambda instead, and the use that to prevent compile errors, like this:

```cpp
struct identity
{
    template<class T>
    constexpr T operator()(T&& x) const
    {
        return std::forward<T>(x);
    }
};

template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    static_if(has_calculate_physics<Entity>()).then(
        [&](auto id) {
            id(e).calculatePhysics(delta);
            std::cout << "CalcluatePhyiscs" << std::endl;
        })
    .else_if(has_update_physics<Entity>()).then(
        [&](auto id) {
            id(e).updatePhysics(delta);
            std::cout << "UpdatePhysics" << std::endl;

            static_if(has_correct_physics_errors<Entity>()).then(
                [&](auto id) {
                    id(e).correctPhysicsErrors();
                    std::cout << "CorrectPhysicsErrors" <<
                        std::endl;
                })(identity());
        })
    (identity());
}
```

It should be possible with some changes to `static_if` function and some macro magic to write this:

```cpp
template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    STATIC_IF(has_calculate_physics<Entity>()) {
        id(e).calculatePhysics(delta);
        std::cout << "CalcluatePhyiscs" << std::endl;
    }
    STATIC_ELSE_IF(has_update_physics<Entity>()) {
        id(e).updatePhysics(delta);
        std::cout << "UpdatePhysics" << std::endl;

        STATIC_IF(has_correct_physics_errors<Entity>()) {
            id(e).correctPhysicsErrors();
            std::cout << "CorrectPhysicsErrors" <<
                std::endl;
        };
    };
}

```

I believe some people would prefer to avoid the macros, though.

**Comment by pfultz2** [comment]
> (1) The current standards text for ODR is conceptually broken in this respect. So are literal readings of it. There is ongoing work to fix it.

But in current compilers the address of the variable template across translation units do not match, pure and simple. Perhaps in future C++17, this will hopefully be fixed, or we will at least have the ability to define inline variable as they are being called. Either way...

> (2) I understand it is Halloween season, but maybe it will be helpful if people stop quoting broken texts to scary people away from conceptually sound programming practices.

No, it is best practice to use integral constants for compile time values instead raw constexpr primitives. This is because it leads to simpler and more natural code. The above `static_if` construct is a perfect example of this. Had raw booleans been used(like from the *_v versions) then it would have looked like this:

```cpp
template <class Entity>
void updatePhysicsFor(Entity && e, float delta) {
    static_if<has_calculate_physics_v<Entity>>().then(
        ...
    )
    .template else_if<has_update_physics_v<Entity>>().then(
        ...
    )
    .template else_(
        ...
    )
    (e, delta);
}
```

Those `.template` used everywhere is ugly and can be confusing for people who are newer to the language. Even more so, even if you don't believe a user should write `static_if` construct like the above, you can still see how integral constants are better in many other common examples(like in tuple with `std::get<1>(t)` vs `t[1_c]`]).

We should strive to make code simple and natural, and avoid exposing these corner cases to newer users(such as the ambiguity involved in dependent template types). Using integral constants helps do that and is the obvious best practice for C++.

**Comment by hsutter** [comment]
This particular problem is under discussion in the evolution working group so we don't want to prejudge the outcome of that.
