### ISSUE TITLE
Duplicated Rules R.22 and R.23

### ISSUE THREAD

**Issue by thecoshman** [isocpp/CppCoreGuidelines#354]
These two rules are about using `make_shared()` and `make_unique()` respectively. Both of these rules are duplicates of previous rules. I don't mean they cover similar topics, I mean they are covering exactly the same point, with practically the same reasoning.

How can we work on a guide for writing good code with such sloppy duplication?
Which version of these rules should an analysis tool claim was broken; both?

At the very least, for the sake of avoiding fixing things twice, one version of these should just be a link to the other.

The previous examples are rules [C.150](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-c150-use-make_unique-to-construct-objects-owned-by-unique_ptrs-or-other-smart-pointers) (which corresponds to [R.23](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-rule-r23-use-make_unique-to-make-unique_ptrs)) and [C.151](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-c151-use-make_shared-to-construct-objects-owned-by-shared_ptrs)  (which corresponds to [R.22](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-r22-use-make_shared-to-make-shared_ptrs))

**Comment by kkeri** [comment]
I agree on the duplication issue, however I would prefer keeping R.22 and R.23, because they are surrounded with smart pointer related rules.

In addition, the enforcement sections of C.150 and C.151 doesn't seem to enforce exactly what the rules state. They tell me: don't declare shared/unique_ptr variables other than auto. Both issues could be addressed by removing this pair of rules.

**Comment by BjarneStroustrup** [comment]
The duplication is deliberate; some people do read sections of the rules and too many cross references makes reading unnecessarily hard. The enforcement sections emphasize different aspects, but my guess is that a tool will simply enforce all aspects
