### ISSUE TITLE
A myth or a rule: Prefer preincrement for loop variables?

### ISSUE THREAD

**Issue by kkeri** [isocpp/CppCoreGuidelines#362]
I have heard it many times that preincrement should be preferred, at least for iterators, because it is more efficient than postincrement. E.g:

    vector<int> v;
    ...
    for (auto it = v.begin(); it != v.end(); ++it) {...}

It sounds reasonable, as the previous value should be stored in a `temp` until it is returned by the operator++ function. However a good compiler might easily optimize `temp` away.

I can't decide, but you may have an established position on this. If so, I propose to add it to the guidelines.

**Comment by galik** [comment]
Typically *post-increment*, for user defined types, involves the creation of a *copy* in order to return the previous value after an increment. So I can only imagine that's going to be slower, more consumptive. The rule of consistency would then suggest to me to always use *pre-increment*.

**Comment by khatharr** [comment]
From what I've been told, and I haven't researched this outside of VS, the modern compilers all skip the temporary if the return value is not captured.

**Comment by mflerackers** [comment]
Why not just check with any compiler? You will see that the produced code will call the post-increment operator even if the result will not be used (because it can't tell whether it is safe to replace it with a pre-increment operator) and the return value of the post-increment is placed in the %esi register even though unused. So writing ++i is faster, it's not a myth, it's fact, it's less instructions.

For example clang 3.7 gives the following:

++i
```assembly
leaq	-72(%rbp), %rdi
callq	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const
movl	(%rax), %ecx
addl	-64(%rbp), %ecx
movl	%ecx, -64(%rbp)
leaq	-72(%rbp), %rdi
callq	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator++()
movq	%rax, -96(%rbp) 
jmp	.LBB0_2
```
i++
```assembly
leaq	-72(%rbp), %rdi
callq	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const
movl	(%rax), %ecx
addl	-64(%rbp), %ecx
movl	%ecx, -64(%rbp)
leaq	-72(%rbp), %rdi
xorl	%esi, %esi
callq	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator++(int)
movq	%rax, -88(%rbp)
jmp	.LBB0_2
```

GCC 5.2.0 produces very similar code

++i
```assembler
leaq	-96(%rbp), %rax
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const
movl	(%rax), %eax
addl	%eax, -36(%rbp)
leaq	-96(%rbp), %rax
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator++()
jmp	.L3
```

++i
```assembler
leaq	-96(%rbp), %rax
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const
movl	(%rax), %eax
addl	%eax, -36(%rbp)
leaq	-96(%rbp), %rax
movl	$0, %esi
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator++(int)
jmp	.L3
```

i++
```assembler
leaq	-96(%rbp), %rax
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const
movl	(%rax), %eax
addl	%eax, -36(%rbp)
leaq	-96(%rbp), %rax
movl	$0, %esi
movq	%rax, %rdi
call	__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator++(int)
jmp	.L3
```

**Comment by khatharr** [comment]
Interesting...  This is what I get from VS2015. (Only the addresses change.)

```Assembly
  auto stop = derp.end();
  for(auto iter = derp.begin(); iter != stop; iter++) {
00911085  mov         esi,ecx  
00911087  sub         ebx,ecx  
00911089  add         ebx,3  
0091108C  shr         ebx,2  
0091108F  cmp         ecx,dword ptr [ebp-18h]  
00911092  cmova       ebx,edx  
00911095  test        ebx,ebx  
00911097  je          main+0C3h (09110C3h)  
00911099  nop         dword ptr [eax]  
    std::cout << *iter << std::endl;
009110A0  mov         ecx,dword ptr ds:[913040h]  
009110A6  push        9111A0h  
009110AB  push        dword ptr [esi]  
009110AD  call        dword ptr ds:[913034h]  
009110B3  mov         ecx,eax  
009110B5  call        dword ptr ds:[913038h]  
  auto stop = derp.end();
  for(auto iter = derp.begin(); iter != stop; iter++) {
009110BB  inc         edi  
009110BC  lea         esi,[esi+4]  
009110BF  cmp         edi,ebx  
009110C1  jne         main+0A0h (09110A0h)
```

versus

```Assembly
  auto stop = derp.end();
  for(auto iter = derp.begin(); iter != stop; ++iter) {
00CF1085  mov         esi,ecx  
00CF1087  sub         ebx,ecx  
00CF1089  add         ebx,3  
00CF108C  shr         ebx,2  
00CF108F  cmp         ecx,dword ptr [ebp-18h]  
00CF1092  cmova       ebx,edx  
00CF1095  test        ebx,ebx  
00CF1097  je          main+0C3h (0CF10C3h)  
00CF1099  nop         dword ptr [eax]  
    std::cout << *iter << std::endl;
00CF10A0  mov         ecx,dword ptr ds:[0CF3040h]  
00CF10A6  push        0CF11A0h  
00CF10AB  push        dword ptr [esi]  
00CF10AD  call        dword ptr ds:[0CF3034h]  
00CF10B3  mov         ecx,eax  
00CF10B5  call        dword ptr ds:[0CF3038h]  
  auto stop = derp.end();
  for(auto iter = derp.begin(); iter != stop; ++iter) {
00CF10BB  inc         edi  
00CF10BC  lea         esi,[esi+4]  
00CF10BF  cmp         edi,ebx  
00CF10C1  jne         main+0A0h (0CF10A0h)
```

**Comment by adrian17** [comment]
I'd try some more heavyweight iterator too:

	/* __declspec(noinline) */ void f(directory_iterator &it) {
		//++it;
		//it++;
	}

Both on GCC (Boost.Filesystem) and VS (std::experimental::filesystem) postincrement seems to have more unoptimizable side effects.

**Comment by gdr-at-ms** [comment]
Whether post-increment is optimized to pre-increment is largely a function of the quality of your compiler and also the source code you feed it with.  If your post-increment is implemented in terms of pre-increment, and is inline and/or lightweight you will find that some compilers are good at doing a good job optimizing it out.  So, it isn't a myth.  On the other hand, your overall code can use the improvement from following a consistent style -- whichever you chose. You will find a good majority these days use pre-increment..

**Comment by kkeri** [comment]
Thanks for the rationale. 

What I have learnt is that using pre-increment can't hurt even in cases when post-increment is well optimized. So it goes to good practice in my toolbox.
