### ISSUE TITLE
SF.5: Add recommendation, that a .cpp file should include the .h file(s) that defines its interface at first.

### ISSUE THREAD

**Issue by KaiStuhlemmer** [isocpp/CppCoreGuidelines#366]
Including the interface defining header(s) at first ensures, that the header(s) are self-sufficient. Example:

// foo.h
int mean(const std::vector<int> v);

// foo.cpp - bad include order
#include <vector>
#include <foo.h>

Missing include of vector in foo.h is undiscovered until other users may stumble over it. By including foo.h first the implementer immediately encouters this problem.

**Comment by gdr-at-ms** [comment]
Components are not always neatly divided into `A.h`/`A.cxx` one-to-one correspondence.  Furthermore, if `A.h` contains the interface of component `A`, then it should be self-contained.
