### ISSUE TITLE
Proposal: outlaw static initialization fiasco

### ISSUE THREAD

**Issue by MichaelCook** [isocpp/CppCoreGuidelines#367]
Should we have a rule to disallow declaration of objects at file scope (i.e., non-function scope) whose constructors are non-trivial?

See also: https://isocpp.org/wiki/faq/ctors#static-init-order

**Comment by thecoshman** [comment]
I don't think it is something that should be out right banned. That seems a bit heavy handed to me. But it certainly seems like something that would be trivial for an analysis tool to detect and warn about. Maybe I am naive here, but it's not the static objects that are the problem, but the combination of them trying to access each other.

**Comment by BjarneStroustrup** [comment]
Some things should be banned outright; this is a set of guidelines, rather than the standard. However, I will stick to "avoid" for now. I added:

I.22: Avoid complex initialization of global objects
