### ISSUE TITLE
C.131 contradicts C.134

### ISSUE THREAD

**Issue by NicolBolas** [isocpp/CppCoreGuidelines#373]
Note: This seems similar to #302, but it is a separate issue.

C.134 tells us that

> If you’re writing a type that maintains an invariant, then all the variables should be private – it should be encapsulated.

However, not all variables actually participate in the class's invariants. A user might be able to freely set the name of some object, without any kind of special checking or anything. Whereas setting some other value requires testing invariants or adjusting multiple variables or whatever.

Even so, to follow C.134, we will have to make the name field private. So, to allow the user to get and set the name field, we must do this:

    std::string &get_name() {return name;}
    const std::string &get_name() const {return name;}

However, C.131 makes it very clear that we shouldn't do that:

> A trivial getter or setter adds no semantic value; the data item could just as well be public.

These functions add no semantic value. Indeed, the two `get_name` functions effectively make it public.

I'm not saying that C.134 should be rescinded. I'm simply saying that you can't enforce both C.134 and C.131. Not unless you believe that, if some variables form an invariant, then *all* variables in a type must form an invariant.

**Comment by bajamircea** [comment]
@NicolBolas :

In general, if in a class some member variables are tied together, working to maintain an invariant, while others are not involved in maintaining it, then the class is confused about what's supposed to do, and probably you have missed an additional abstraction, hence the apparent contradiction.

A concrete example: say you have a class `person_info` with members `name`, `brithday_month` and `birthday_day`, where the `name` can be anything, but last two must enforce that the day is not larger than the number of days for the month. In that case you could have a `class birthday` with `month` and `day` private, and have the new `struct person_info` with public `name` and  `birthday`. You end then with two abstractions with a clear purpose: `birthday` maintains a invariant, `person_info` groups several pieces of data.

I don't see a contradiction for the two rules above.

**Comment by NicolBolas** [comment]
The problem with your example is that it results in a proliferation of special case classes for what should be very simple.

Dates, as a class, are a perfectly valid construct. It's a thing that many people may need to use for many reasons. And having a date data structure that retains the basic invariants of being a valid data is good.

The problem is when you want to constrain date to being within a certain valid region. Take your `person_info` example. You have a `name` and `date_of_birth`. For DOB, you use the standard date data structure, since it handles the basic date invariant.

Now what happens if you add a `date_of_death` field. Well, we have a logical invariant now: DOB must be <= DOD.

Your way of coding would require that we make a data structure specifically for that particular invariant. One which is not part of `person_info`. So we to do this:

``````
class dob_and_dod
{
public:
  date GetDOB() const;
  date GetDOD() const;
  void SetDOB(date dob);
  void SetDOD(date dod);
private:
  date dob_;
  date dod_;
};

struct person_info
{
  std::string name;
  dob_and_dod dates;
};
``````

So now you have to write a class who's only purpose is to maintain this invariant. And it's an invariant that, unlike `date`, is virtually *useless* for any class other than `person_info`. Oh sure, you can probably come up with one or two other use cases for it, but odds are good that this will be the only place where this data structure exists in your code.

This API also forces users to do things like this to access data: `person.dates.GetDOB()`. That is a needlessly cumbersome expression. Oh sure, you could add matching members to `person_info`. But then you have to write a bunch of forwarding functions for an interface that, by all rights, ought to be part of `person_info` itself.

What you seem to be suggesting is that the right way to code by the guidelines is to make a lot of one-off, special case classes. Where each class manages the minimum invariant possible. And larger data structures should be built out of them, with `struct`s being potentially the most forward-facing part of an interface.

If that's the coding style that the core guidelines are biased towards, then the guidelines should make that more explicit. It needs to be said up-front so that it's clear to everyone, rather than requiring users to work out the way to implement C.131 and C.134 in their code.

It would also allow you to make an argument for why this coding style should be preferred, as neither C.131 nor C.134 seems to justify this style.

**Comment by BjarneStroustrup** [comment]
The coding guidelines are meant to simplify the task of writing, reading, and maintaining code. This cannot be done by modifying the rules to cater to every technique and taste.

In particular, I find the data example above unconvincing; for starters dob and dod are not independent: you can either make them both "plain data" and rely on external code to keep them correct, or you can implement the invariant.

**Comment by NicolBolas** [comment]
Perhaps you misunderstood my point.

`dob_and_dod` does implement the invariant. So the question is not *whether* the invariant is implement, but *where* it is implemented. I would like to implement it in `person_info`. I would argue that it is the most natural place for it, since it is the only class which will actually need the invaraint. But the rules seem to force me to implement it outside of the class that actually uses it.
