### ISSUE TITLE
Change C.35 to  "A base class destructor should be either public and virtual, or protected and nonvirtual"

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#375]
Currently the rule says "A base class with a virtual function needs a virtual destructor". This is only true if the base class is meant to be used for deleting derived objects. Otherwise, the destructor can be nonvirtual (and protected). This will also be safe and may save a virtual function call and allow inlining.

See Guideline #4 in http://www.gotw.ca/publications/mill18.htm for a more detailed investigation.

**Comment by hsutter** [comment]
I agree. Fixed and added cross-reference to the Discussion section later in the document that already said the same thing. Thanks!

**Comment by mmatrosov** [comment]
C.35 in the table of contents says "C.35: A base class with a virtual function needs a virtual destructor", but when you click on it, you see "C.35: A base class destructor should be either public and virtual, or protected and nonvirtual". Seems like the first link needs to be fixed.
