### ISSUE TITLE
[Progress Report] Translation to Korean

### ISSUE THREAD

**Issue by utilForever** [isocpp/CppCoreGuidelines#376]
Currently, C++ Korea translates C++ Core Guidelines to Korean.

Translation progress is showed below.
(It could be different from actual progress.)

Abstract (100%)
C++ Core Guildlines (0%)
A - Architectural Ideas (0%)
C - Classes and Class Hierarchies (0%)
Con - Constants and Immutability (0%)
CP - Concurrency and Parallelism (0%)
CPL - C-Style programming (100%)
E - Error Handling (100%)
Enum - Enumerations (100%)
ES - Expressions and Statements (70%)
F - Functions (1%)
GSL - Guideline support library (0%)
I - Interfaces (60%)
In - Introduction (0%)
N - Non-Rules and myths (0%)
NL - Naming and layout rules (100%)
P - Philosophy (0%)
PER - Performance (50%)
PRO - Profiles (0%)
R - Resource management (0%)
RF - References (0%)
SF - Source files (0%)
STL - The Standard Library (0%)
T - Templates and generic programming (0%)
To-do - Unclassified proto-rules (0%)
Appendix A - Libraries (0%)
Appendix B - Modernizing code (100%)
Appendix C - Discussion (0%)

You can check this project at [this](https://github.com/CppKorea/CppCoreGuidelines).

Thanks,
Chris.

**Comment by AndrewPardoe** [comment]
Fantastic progress! It's great to see translations. Thank you!

1. Feel free to reopen this issue later to make more progress reports, comments, etc.
2. Please let us know when you've got "enough" and we'll make sure to blog about it!
