### ISSUE TITLE
Frustrated 

### ISSUE THREAD

**Issue by 3vol3m** [isocpp/CppCoreGuidelines#381]
So I lost use of all my devices. Passwords changed etc. content added and exported without consent. blakehawkins sent emails from one of the accounts and I wish I understood for what purpose. My google ID was showing up all over the world literally. And some of the craziest things. I ended up because of all this having a mental breakdown. If this was your goal congrats. I traced request pulls to this repository. I am so emotionally destroyed. I suffer from bipolar along with other mental conditions. Maybe you guys are trying to help. It's weird at times it's like my phone knows exactly what is going on in my life. Plays songs accordingly etc. or news feeds that hit on what I'm feeling. Typing it sounds crazy but I have screenshots that Apple and others can't explain. I have screenshots of Blake sending emails from my account. Now I am thankful for part of this because my life is able to move on in areas of hurt that I have felt for years. And finding me and who I am through all this. But can I get any idea of what is going on? I know that my mind is nowhere near what your thinking processes are. I wish it could and I am going to push until it is. I don't get how it was that people hit milestone achievements by me finding your repository then quickly it went private. All I know is I don't ever want what I experienced to happen to anyone else. Ty for reading.

**Comment by blakehawkins** [comment]
@3vol3m if you prefix my name with an @ sign, I will see it right away. Can you send me an email? Maybe I can help explain what's going on. I am sorry something has confused you, but I can assure everything on github is behaving as normal.

**Comment by 3vol3m** [comment]
Sure dscholtens00@gmail.com
