### ISSUE TITLE
Need a version of `finally` that only triggers on exceptions.

### ISSUE THREAD

**Issue by NicolBolas** [isocpp/CppCoreGuidelines#382]
Consider this function:

`````
auto func()
{
  owner<T> res = get_resource();

  //Various stuff.

  return res;
}
`````

If the `various stuff` happens to throw an exception, you still need `res` to clean up. Assuming we don't want to capture this in an object, we instead do:

`````
auto func()
{
  owner<T> res = get_resource();
  auto thingy = finally([&]() {/*free up `res`*/});

  //Various stuff.

  return res;
}
`````

The problem of course is if an exception is not thrown. We want to transfer ownership of the object to the caller. But `finally` will ensure that the functor is called no matter what. Which will destroy `res`, thus causing the function to return a freed resource.

What we need is a version of `final_action` that is *only* called in the event of stack unwinding due to an exception. I know that implementing that is non-trivial, and until the adoption of C++17 and `std::uncaught_exceptions` it will require platform-specific code. But it is a very useful thing to be able to do.

Obviously there should be a guideline to go along with this.

**Comment by mgehre** [comment]
This example can easily be solved by RAII. Do you have another example
where RAII is not sufficient?

NicolBolas <notifications@github.com> schrieb am Mi., 11. Nov. 2015 06:24:

**Comment by NicolBolas** [comment]
I'm not sure what you mean. Technically, every use of the GSL type `owner` could conceivably be handled by a RAII type. Yet the core guidelines do seem to allow its use. Similarly, every use of `finally` could have instead been part of some RAII type. Yet the guidelines seem to want people to use it where appropriate.

All I'm asking for is a variation that allows ownership to transfer out naturally. Indeed, this is one of the main reasons why C++17 got `std::uncaught_exceptions`. [Herb Sutter outlined a bunch of use cases in his paper (PDF)](wg21.link/N4152), most of which translate very well to an "on-fail" version of `finally`.

**Comment by KevinDHall** [comment]
It appears to me that you are asking for a new language feature, not a guideline.  Am I correct?

**Comment by NicolBolas** [comment]
It does not require a new language feature. `finally` works by creating an object that will call the given functor in its destructor. `on_fail` would simply call the functor in its destructor, but *only* when the stack is being unwound due to exception handling.

There are platform-specific methods for detecting when an object is being destroyed due to the stack is being unwound, but C++17's `std::uncaught_exceptions` will do the job. Just look at the link I posted. It doesn't suggest a new language feature at all.

**Comment by KevinDHall** [comment]
I've seen the paper as well as Andrei's talk.  There's no mention about an object type named finally. Andrei uses something called SCOPE_FAIL in his talk.  I suppose that one could create a class named `finally`.  However, I don't think that most people care about creating a named variable to hold the lambda to call at cleanup.  The SCOPE_FAIL macro hides the details really well and many people I've talked to have already implemented his macros and naming convention.  I'd much rather see Andrei's macros adopted than try creating something new.

**Comment by NicolBolas** [comment]
>  However, I don't think that most people care about creating a named variable to hold the lambda to call at cleanup.

And yet, the Core Guidelines *explicitly* tell people to do just that. [C.30 says to use `finally` to establish do this.](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-dtor)

    auto act = finally([]{ cout << "Exit test\n"; });  // establish exit action

It can't get more direct than that. `finally` is a GSL-defined function that returns a `final_action` instantiation that calls a lambda when the scope ends. This is *exactly equivalent* to Andrei's `SCOPE_EXIT` macro, and the [GSL already has this](https://github.com/Microsoft/GSL/blob/master/include/gsl.h).

So however much you may not think people want to, the core guidelines already tell people to do it. All I'm asking for is support for the `SCOPE_FAIL` equivalent.

**Comment by KevinDHall** [comment]
Ahhh... OK.  I thought C.30 was a suggestion for creating a class, not that the GSL already has the class.  I personally like Andrei's macros because I don't have to create a variable name.

I understand what you're saying now.  Sorry for the long conversation needed to get me to understand your point.

**Comment by hsutter** [comment]
This is a very rare class of example, and if you want to write such a RAII type (e.g., a DBTransaction type that does a rollback if its destructor is called as part of stack unwinding) you should use the new `std::uncaught_exceptions` function which gives you the correct answer.
