### ISSUE TITLE
F.7: For general use, take T* arguments rather than smart pointers. Some thoughts.

### ISSUE THREAD

**Issue by PiotrSliwa** [isocpp/CppCoreGuidelines#388]
Hi *,

I would like to touch the problem mentioned by **F.7. For general use, take T* arguments rather than smart pointers**. I agree that passing a smart pointer is not always a good practice, as it pollutes a declaration with the kind of knowledge that can be redundant in many general-purpose cases.

However, in such cases, I would rather encourage to use references instead of raw pointers. Basically, both raw pointer and reference are used as windows to a place in memory with the difference that reference is fixed to one place (i.e. as an alias) for all the time whilst pointer is just a numerical value holding an address. It implies that reference to a value requires someone to be already in charge of the object's lifetime. On the other hand, pointer tells nothing about it, but can be reassigned, can be null and can provide multiple levels of indirection (I ignored other properties, less relevant for the issue). Nevertheless, when you consider pointer and reference as value holders being passed to a method/function, they both do the same, yet reference holds also additional, crucial information (that a callee is not an owner).

And here is my concern: while raw pointer can be a useful implementational tool, I cannot imagine when it should be preferred to a reference (and a smart pointer) when it comes to passing it as an argument, other than e.g. old C-style functions for memory management and when, for some reason, you feel like having `T**` parameter. From caller's point of view, when you call a function/method and you pass an argument, you are responsible for it, i.e. you create/destroy the object, and you pass it just for the time it is used by the function/method. Other cases (passing the object for longer than local scope when you are the object's owner) indicate, you most probably want to use `unique_ptr` anyway. Even if there are some situations where a raw pointer is really needed given its unique features, they are in minority and I would treat them as special, low-level cases, rather encouraging their usage for general purposes.

The final thought - even for those maybe-four-or-so situations requiring a raw pointer argument - I would recommend to enforce flagging pure `T*` whatsoever and use `T const *` instead, as its allows to use almost all raw-pointer-specific features much safer.

PS. Let the force be with y'all!

**Comment by AndrewPardoe** [comment]
Discussed 21 Dec 2015.

**Comment by AndrewPardoe** [comment]
Should cross-reference R.30 to F.7 as well as the sections starting in F.15, all of which talk about references.

**Comment by hsutter** [comment]
Applied, thanks!
