### ISSUE TITLE
"Return containers by value" should be elaborated

### ISSUE THREAD

**Issue by elronayellin** [isocpp/CppCoreGuidelines#390]
"Return containers by value" is a great guideline, but I think there should be a note about when this guideline should be ignored or modified.  RVO and `move` take care of the cost of the copy, but not the allocation/deallocation.

for example:
```
for (auto& item : items)
{
 vector<int> v = get_large_vector();
 use(v);
}
```
in this case, an appropriate alternative might be either passing by reference or using the following idiom:

```
vector<int> get_large_vector(vector<int>&& prealloc={})
{
  prealloc.clear();
  modify(prealloc);
  return std::move(prealloc);
}

vector<int> singleuse = get_large_vector(); // small increase in cost vs original
vector<int> multiuse;
//multiuse.reserve might be appropriate
for (auto& item : items)
{
 multiuse = get_large_vector(std::move(multiuse));
 use(multiuse);
}
```

**Comment by NicolBolas** [comment]
Would it not make more sense for `get_large_vector` to simply take a number of elements to reserve (with a default of 0)? After all, `reserve` is the only possible preallocation that could be done.

**Comment by elronayellin** [comment]
The allocation is reused on each call to get_large_vector by virtue of the moved in vector.

**Comment by NicolBolas** [comment]
Then `get_large_vector` is misnamed. It isn't getting a vector at all; it's *modifying* one. In which case, it shouldn't be returning a value at all. It should only be returning an object if it created it. If the function modifies a live object, it should have a name that spells that out and not return the modified vector at all.

**Comment by elronayellin** [comment]
Sure, the name can be different-- I kept the name from the existing example for continuity in the demonstration.
But I disagree with your objection.  Ideally, the function just returns by value, but I'm discussing the exceptional case when for performance reasons that's not good enough.  Only the caller knows which form-- return by value or pass by reference-- is appropriate; this form allows one function to like act as either.  
The alternative would be two functions with the return by value implemented in terms of the pass by reference; either way, the guideline should note when the rule is not appropriate.

**Comment by hsutter** [comment]
Essentially this example is in F.20 so I added a cross-reference to that.

I'm setting this to Review instead of Resolved pending discussion about whether we want to capture the above suggested `&&`-parameter-to-pass-in-storage idiom too.

**Comment by AndrewPardoe** [comment]
Editors discussed 8 Dec 2015.

**Comment by hsutter** [comment]
We've discussed the `&&` parameter idiom and decided not to include it. The rest is now covered. Thanks!
