### ISSUE TITLE
Rule F.15: Prefer simple and conventional ways of passing information

### ISSUE THREAD

**Issue by rodiers** [isocpp/CppCoreGuidelines#398]
With respect to https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-conventional

The picture expresses that:
If "Cheap or impossible to copy" and we use the argument as an input parameter => we pass by value (f(X))

The text however says: "For an "input-only" value: If the object is cheap to copy, pass by value. Otherwise, pass by const&." It doesn't mention impossible to copy here.
So here "impossible to copy" is not mentioned.

I personally think the picture is wrong and the text is correct: If the argument is an input and a copy doesn't need to be retained, there is no reason to move away the value and hence it should be passed as "const reference".

Impossible to copy or not is not relevant if you don't need to retain a copy. So the table would need an extra column and should look like this:

  |Cheap to copy |Impossible to copy| Cheap to move or Moderate cost to move or don't know| Expensive to move
------------ | -------------| -------------| -------------| -------------
Out | X f()| X f()| X f()| X f()
In/Out | f(X&) | f(X&) | f(X&) | f(X&)
In | f(X)| f(const X&)| f(const X&)| f(const X&)
In & Retain copy | f(X)| f(X)| f(const X&)| f(const X&)

You could also argue to remove the impossible to copy completely. Especially for the advanced picture it is weird since it says if "In  & retain copy" + impossible to copy => f(X) and if In & move from => f(X&&). But the first condition is actually the second condition, since in the first case the copy can't happen you are actually doing a move instead (so it is In + move from and not In + copy from).

**Comment by hsutter** [comment]
The intent was that "impossible to copy" isn't limited to the case when you keep a copy. It affects how you pass the actual argument to be presented as a parameter to the function.

As you mention, this affects primarily the advanced picture. Also, as part of cleaning up the parameter passing guidance, I added the "consume" category (F.18), which by default would encourage passing by `&&` and then applying `move`. I've merged this in to note the overlap for the `unique_ptr` example.
