### ISSUE TITLE
There is no smartptrconcepts to link to in GSL.concept

### ISSUE THREAD

**Issue by GBGamer** [isocpp/CppCoreGuidelines#407]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-gslconcept-concepts

For Pointer, Unique_ptr, and Shared_ptr, it says "see smartptrconcepts". This is a dead link.

**Comment by AndrewPardoe** [comment]
Thanks for the note. Maybe we should retarget to S-resource?

**Comment by AndrewPardoe** [comment]
Reviewed 11/30/2015. We should link to the lifetimes paper and include a short summary in the Guidelines text.

**Comment by hsutter** [comment]
Added smartptrconcepts as a reference to the Lifetimes paper. Thanks!
