### ISSUE TITLE
ES.76: gotos

### ISSUE THREAD

**Issue by cdkrot** [isocpp/CppCoreGuidelines#411]
Since the only good use of gotos is jumping of nested loops, it is a good idea to add in c++ standard an alternative way of such a jump, so nobody will need gotos.

Possible ways:
```cpp
break LABEL; // like goto, but break. Java (?) style.
break 2; // break two loops up. Ruby (?) style. 
````

**Comment by GamerGambit** [comment]
Correct me if I'm wrong but that syntax is not valid C++. Because of this, your `break` syntax should be written up and proposed to the comittee.

**Comment by cdkrot** [comment]
Yes it is not a standard, but i think it is good idea to be. I don't know how to write proposals to comittee, so i decided to ask here first.

**Comment by martinmoene** [comment]
On the [ISOCPP website](https://isocpp.org/) there's a section [How To Submit a Proposal](https://isocpp.org/std/submit-a-proposal). Then it's only a little bit of hard word.

**Comment by AndrewPardoe** [comment]
@GamerGambit  and @martinmoene  suggestion is a good resolution. Thanks!

**Comment by cdkrot** [comment]
Ok, thank you for you reply, i will try to prepare a proposal.
