### ISSUE TITLE
for (;i;) (alpha[i] ^ beta[i] ^ 0xFFFFFFFF == delta[i] ? gamma[i]=1 : gamma[i]=0); 

### ISSUE THREAD

**Issue by aunk** [isocpp/CppCoreGuidelines#412]
This would make finding hashes sooooo much faster. But I can't seem to do it in C++. Can this be implemented?

**Comment by aunk** [comment]
long S_Rend::convBit(bitset<32> A, bitset<32> B, int transform=0) {

	long rtrn=0;
	for (int i=0;i<=31;i++) {
		int binA = A[i];
		int binB = B[i];
		bitset<1> BAC;

		bitset<1> Ab = static_cast<long>(binA);
		bitset<1> Ba = static_cast<long>(binB);
		bitset<1> def = 1;

		switch (transform) {
			case 2:
				BAC = Ab | Ba | def;
			break;
			case 1:
				BAC = Ab & Ba & def;
			break;
			default:
				BAC = Ab ^ Ba ^ def;
		}
		rtrn += BAC.to_ulong() * (2^i); 
	}
	return rtrn;
     }

**Comment by hsutter** [comment]
This appears to be off-topic -- a library extension request, not a guideline issue.
