### ISSUE TITLE
Does R.4 even need to be said?

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#418]
R.4 "A raw reference (a T&) is non-owning" surprises me: does that even need to be said?  I'm not aware of anything being said on this in other style guides (like the Google guide), and I can't find any meaningful instances of this in the 100M lines of code I've got access to.  Can it just be scrubbed?

**Comment by gdr-at-ms** [comment]
I tend to agree.  Assigning to Herb to clarify.

**Comment by hsutter** [comment]
I think we just wanted to be very explicit.

The worry is that there can sometimes be confusion. For example, with `const&` lifetime extension, the & may look like an owner (though it isn't really the same kind of thing). Similarly with `&` class members (also rare). The intent was that we didn't want to have any confusion about whether a `&` was owning.

Assigning back to Bjarne to make a change or close.
