### ISSUE TITLE
F.4 is overly eager to suggest constexpr

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#420]
F.4 says "If a function may have to be evaluated at compile time, declare it constexpr" but the issue isn't merely "may be evaluated at compile time" - the implementation of that function *for all time* must always be able to be evaluated at compile time.

Consider the following scary story:
int pagesize() { return 4096; }  // We know our pages are this size.

Well, we can make that constexpr, clearly.  And now all sorts of things (allocators, static allocations, etc) can depend on it.  But if we start building on other platforms and have to replace that with proper calls to an underlying getpagesize(), we have a mess on our hands - everything that calls that function has to be evaluated (and in some cases that fans out transitively).

Mostly this is a concern in long-term maintenance.

(I don't have good suggested replacement wording, however.)

**Comment by gdr-at-ms** [comment]
Clearly something like `pagesize()` is platform dependent and we expect it to be appropriately abstracted in platform-dependent headers/interfaces.  Clearly we can't forbid platform-dependent constants.  They are a necessity.  The right guidelines is that platform-dependent constants be appropriately abstracted.

**Comment by tituswinters** [comment]
But it's not just pagesize(), it's any function that can at some point in the future no longer be evaluated by the compiler.  Perhaps business logic changes, perhaps defaults must be provided by command line parameters, whatever.  The set of functions that *can* be constexpr (while allowing the program to build) is not the same as the set of functions that *should* be constexpr, when evaluated over time.

**Comment by gdr-at-ms** [comment]
Hmm, that is overgeneralization: that reasoning will ban any named constant.

**Comment by tituswinters** [comment]
Some things pretty clearly can be constexp (say, math functions, or operations on data structures).  I don't have (yet) any great rule-of-thumb for deciding whether constexpr is appropriate, but it's definitely an issue.  

Perhaps something like: 
Note - Any API that may in the future become configurable or customizable at runtime should not be made constexpr: such customization cannot be evaluated by the compiler, and any constexpr functions depending on that API will then fail to compile.

**Comment by gdr-at-ms** [comment]
@tituswinters 
The spirit of the last suggestion looks good.  I will add that clarifying note.

**Comment by AndrewPardoe** [comment]
Discussed 14 Dec 2015. We like the suggestion of a clarifying note.

**Comment by gdr-at-ms** [comment]
Fixed by #463
