### ISSUE TITLE
F.6, noexcept, and memory allocation

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#421]
Preamble:
The *standard* is clearly required to adhere to the issue of "a call to new may throw" and behave accordingly.  However, the set of environments where an allocation failure can be reasonably dealt with is small. Over the years I've collected only two examples:
* When the system has pre-allocated memory sufficient to do emergency-state dump and can invoke that panic method
* In a program like Photoshop where the size of the memory allocation is governed by user-input (allocating a new document of far-too-large a dimension)

In basically any other case, letting the system die because of the allocation failure is likely to be the best option.  

Suggestion:
Clarify whether the core guidelines are focused on environments where failure-to-allocate exceptions can be reasonably dealt with.  If not, revisit the text in the note for F.6:
"In most programs, most functions can throw (e.g., because they use new, call functions that do, or use library functions that reports failure by throwing), so don't just sprinkle noexcept all over the place. noexcept is most useful for frequently used, low-level functions."

**Comment by cubbimew** [comment]
More examples: Applications that allocate objects in shared memory, session memory, and pretty much any arena other than the system heap. Applications that process data (where size of a some intermediate heap allocation depends on the data) that visited an untrusted network.
It's `bad_alloc`, not `OutOfMemoryError`.

**Comment by tituswinters** [comment]
Sure, that's a plausible example.  But that's still a rare (extremely rare?) scenario.  I'm not a decider on the issue, but I'd be surprised if C++ *Core* Guidelines were primarily concerned with rare scenarios.  The fact that things like this are mentioned semi-regularly makes less-informed programmers do all sorts of poor things in the name of sort-of-trying to handle allocation errors (which mostly just makes a mess of their code and makes failures even more inscrutable if they do occur).

**Comment by AndrewPardoe** [comment]
We are in general agreement. Most systems should not try to recover from out-of-memory.

**Comment by cubbimew** [comment]
Doesn't that put resource-constrained environments, ostensibly one of the strengths of C++, out of focus?
My old company dropped C and Java for C++ exactly because it helped us guarantee transactional integrity and service availability despite limited memory (and semaphores, sockets, etc).

**Comment by tituswinters** [comment]
C++ has many strengths, and many odd environments that it *can* function in nicely.  Making the *core* guidelines address all of those environments and edge cases will only ensure that the guidelines aren't useful for anyone.

**Comment by cubbimew** [comment]
The specific issue is the suggestion to (further) encourage noexcept functions that may attempt allocations.
I believe that libraries that follow such guideline would not be useful (or worse, would seem useful until the next DoS) to the wide variety of applications that you call "edge cases" (to recap, applications that make allocations based on user input, applications that make allocations based on data received over the network, applications that use allocators, applications designed for memory-constrained environments, and, forgot this case, applications that use memo caches which can be shrunk in response to system heap pressure in order to complete a transaction)

**Comment by tituswinters** [comment]
I'm sure that we can phrase this in a way that threads that needle.  General purpose code (like the standard library and other utility code) should not make assumptions about where it is used, or should make those assumptions clear.  That doesn't change the fact that the majority of code and majority of programmers don't need to worry about this issue.

I'll try to get a PR out this afternoon along these lines.

**Comment by hsutter** [comment]
Resolved via PR 465. Thanks, Titus!
