### ISSUE TITLE
Missing F.x rule: Don't return "const T&" from assignment

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#422]
This is mentioned in passing deep in F.15, but was fairly common recommendation a decade ago IIRC.  It comes up both reflexively (people use more const-ref than non-const-ref) and based on old recommendations.  Might be worth surfacing as a rule on its own.  (If so, I'll take a crack at wording.)

**Comment by hsutter** [comment]
Good point. I remember knowing reasons why this shouldn't be recommended anymore but I don't remember them all now... IIRC they included that this interferes with move semantics, it's doesn't follow the standard library types' convention, and it violates "do as the ints do." On the flip side, arguably its only benefit was to solve a non-problem, to prevent calling code of the form `(a=b)=c` which IMO was never common and doesn't need to be prevented if it is written.

**Comment by AndrewPardoe** [comment]
Titus, we agree. Thank you for offering to do the wording on this. Could you please submit a PR?

**Comment by hsutter** [comment]
Thanks!
