### ISSUE TITLE
New rule suggestion: do not hide a type name with a non-type name

### ISSUE THREAD

**Issue by zygoloid** [isocpp/CppCoreGuidelines#436]
For compatibility with C, C++ allows the name of a class or enumeration to be hidden by a function, variable, or enumerator. This usage is confusing and results in convoluted code (you must use `struct Foo` or similar to name the hidden type).

Rule suggestion:

# Do not declare a type and non-type with the same name in the same scope

## Reason

Code clarity. This removes the need to disambiguate with a keyword such as `struct` or `enum`. It also removes a source of errors, as `struct X` can implicitly declare `X` if lookup fails.

## Example, bad

    struct foo { int n; };
    struct foo foo();
    struct foo x = foo();

## Enforcement

Report all cases where a variable, function, or enumerator hides a class or enumeration declared in the same scope.

**Comment by hsutter** [comment]
We agree to ban it. Exception: Antique header files.

**Comment by hsutter** [comment]
I decided to roll this into ES.8 "Avoid similar-looking names" instead of having a separate item.
Thanks, Richard!
