### ISSUE TITLE
New rule suggestion: class and enumeration definitions should always be stand-alone

### ISSUE THREAD

**Issue by zygoloid** [isocpp/CppCoreGuidelines#437]
C++ permits a class or enumeration definition to be used as a *type-specifier* within the declaration of another entity. This usage is confusing, and the existence of the feature is error-prone (if it were not permitted, an extremely common error -- missing the trailing `;` after such a definition -- could be diagnosed accurately every time). It also permits giving an anonymous class or enumeration a name for linkage purposes, which causes implementation issues.

Rule suggestion:

# Class and enumeration definitions should be standalone

## Reason

Mixing a type definition and the definition of another entity in the same declaration is confusing and unnecessary.

## Example, bad

    struct Data { /*...*/ } data{ /*...*/ };

## Example

    struct Data { /*...*/ };
    Data data{ /*...*/ };

## Enforcement

If the `}` of a class  or enumeration definition is not followed by a `;`, report that the `;` is missing.

**Comment by hsutter** [comment]
We agree. It exists only because limitations of old C.

**Comment by hsutter** [comment]
Thanks!

**Comment by hsutter** [comment]
Thanks!
