### ISSUE TITLE
Decide on the term between "reference to const" vs "const reference"

### ISSUE THREAD

**Issue by mpark** [isocpp/CppCoreGuidelines#440]
We currently use both terms (7 instances each). While many are familiar with the meaning, we should still choose one and use it consistently.

Note: [F.16](https://github.com/mpark/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-rule-f16-for-in-parameters-pass-cheaply-copied-types-by-value-and-others-by-reference-to-const) uses "reference to const" in its title.

**Comment by hsutter** [comment]
Agreed, and I also changed a few more uses. Should be consistent now. Thanks!

**Comment by alex-weej** [comment]
@hsutter it's almost a shame that C++ does not technically distinguish "reference to const" (aka immutable) from "const reference" (aka "read only"). But I'd say that `T const &` is actually a read only reference... its value can definitely change!

**Comment by jwakely** [comment]
Not necessarily, it could be a reference to an object that really is const.

Since a "reference to logically const" doesn't exist in the C++ type system using "reference to const" is unambiguous. It can only mean `T const&` and so there's no reason not to call it a read-only reference instead.

**Comment by alex-weej** [comment]
That it isn't expressible in the type system is exactly what I am calling unfortunate. I'd say the term "reference to const" clearly doesn't match reality, but vis a vis "const pointer" and "pointer to const", clearly "const reference" is not really right either.

Sigh.

**Comment by scraimer** [comment]
@alex-weej In your opinion, what would be the semantic difference between "reference to const" and "const reference"? Does "immutable" vs. "read-only" imply that the lack of writabilty is temporary? Or perhaps to be used as a guide for storage in ROM?

**Comment by MikeGitb** [comment]
Not sure if that is what alex-weej is talking about, but one could imagine a type of reference, that ONLY binds to const objects which would then be a litteral *"reference to const [ant object]"*

**Comment by jwakely** [comment]
Or rather than a different type of reference, simply a reference to an object which is known to be really const, like [`immutable` in D](https://dlang.org/spec/const3.html). But that's off-topic here, since it's not part of C++ and so not really relevant to guidelines on using C++ well.
