### ISSUE TITLE
Forbid overloading `operator&()`.

### ISSUE THREAD

**Issue by NicolBolas** [isocpp/CppCoreGuidelines#455]
Could we please have the guidelines completely disallow this?

Most users who haven't looked into some of the darker parts of C++ will assume that `&t` will return a pointer to the object stored by `t`. Overloading `operator&` breaks that assumption. It is so broken in fact that we had to invent a function in C++11 (`std::addressof`) just to work around this.

Which also means that well-behaved template code must assume that the user will overload operator&. So such code will have to use `addressof` if it wants to actually get a pointer to an object. Not a lot of people know about this, so a lot of template code gets written that assumes types don't overload this operator. Code that will naturally become broken when it gets applied to code that overloads this operator.

Nothing in the standard library (as far as I'm aware) overloads `operator&`. Smart pointers and `reference_wrapper` are the types that would benefit from such overloads, and they don't have such overloads.

Such overloading causes far more trouble than its worth, so let us be rid of it.

**Comment by hsutter** [comment]
+1

**Comment by AndrewPardoe** [comment]
Discussed on 14 Dec 2015. We should adopt this rule, with an exception for when you're building a system of smart pointers and references.

**Comment by ChrisGuzak** [comment]
One use of overloading operator& is to avoid leaks with smart references. WRL ComPtr<> does this for example as generally COM objects are returned via out pointer. This is a useful mitigation for that problem so should be considered.

**Comment by gdr-at-ms** [comment]
@ChrisGuzak 
Fully agreed.  
We also considered that particular scenario as part of the design of operator dot -- see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4477.pdf

**Comment by BjarneStroustrup** [comment]
New rule: C.166: Overload unary `&` only as part of a system of smart pointers and references
