### ISSUE TITLE
Question about F.41 and RVO (Return Value Optimiation)?

### ISSUE THREAD

**Issue by galik** [isocpp/CppCoreGuidelines#47]
**F.41** recommends returning a `tuple` and accepting a `tie`:

    tie( iter, success ) = myset.insert( “Hello” );

Does this prevent **RVO**?

**Comment by Eliyahu-Ravuna** [comment]
In this case RVO will work on the tuple, not on the objects inside the tuple.

But tie() will use the move assignment operator whenever possible, so the performance penalty is negligible.

Eliyahu Ravuna

**Comment by Eliyahu-Ravuna** [comment]
To speak about RVO you need the following pattern:

    my_class y = f();

    my_class f()
    {
        my_class result; //constructed directly inside y
        //...
        return result;
    }

In the following code RVO is not relevant:

    my_class y; //the default constructor of my_class is called
    y = f(); //the temporary object returned by f is move-assigned to y

When you use tie, you need to write:

    my_class my_object1;
    my_class my_object2;
    tie(my_object1, my_object2) = f();

my_object1 and my_object2 are already constructed before f() is called, so we cannot speak about RVO here. 

But tie() will use move operators to put values inside my_object1 and my_object2. So no data will be copied unnecessarily even if my_class is a big type.

Eliyahu Ravuna

**Comment by thecoshman** [comment]
@galik does this answer your question? Can this issue be closed now?

I don't think **F.41** needs to be updated in anyway to cover anything.
