### ISSUE TITLE
Suggestion : Software visualization

### ISSUE THREAD

**Issue by MattG4Search** [isocpp/CppCoreGuidelines#476]
"In other words, what would you like your code to look like in 5 years' time, given that you can start now? In 10 years' time?"
=> I would like code source could be easily parsed for automatic understand purpose.

Write a C++ application is quite easy. New C++ feature improve this also. But when application grow, share its content is time consumer. What slow developement process appears to be lack of global application overview and understanding. Get all class representation is fine but it does not explain how application works. Debug step by step is great, analysis call stack is fine but could we do better ? Could we parse code and understand already the application ?

I know this project does not aim to make software visualization (text editor is enough visualization tool here) but as said in : 
"The guidelines are focused on relatively higher-level issues, such as interfaces, resource management, memory management, and concurrency. Such rules affect application architecture and library design."
=>if interface, resource, memory and concurrency are managed in a right way, it should be able to say what source code is expected to produce.

**Comment by AndrewPardoe** [comment]
@MattG4Search, thanks for the suggestion. As you say software visualization is outside of the scope of this project. But there is work being done to help with visualization of C++ programs. Check out the IPR repo, for example. It's a project that Gabriel Dos Reis and Bjarne Stroustrup are working on the help represent C++ programs in their most general form: https://github.com/GabrielDosReis/ipr
