### ISSUE TITLE
new rule proposal. F.4x "Don't return a const T"

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#477]
While recommended elsewhere (most notably, Effective C++, even though the [errata to the 3rd edition](http://www.aristeia.com/BookErrata/ec++3e-errata.html) now include two comments to the contrary), this is almost surely a misuse of the const qualifier.

const-qualifying a class rvalue prohibits move semantics (both binding to rvalue reference overloads of constructors/operators/push_back/etc and the pre-C++11 swap-with-temporary).

const-qualifying a non-class rvalue does nothing at all, since such rvalues do not exist -- gcc and clang warn on `const int f();` at -Wextra and icc warns by default.

Any exceptions?

**Comment by hsutter** [comment]
Added to F.20 with an Enforcement. Thanks!
