### ISSUE TITLE
non-public inheritance is unfairly oppressed by C.120's Enforcement

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#478]
C.120 Enforcement currently says "Flag every use of a nonpublic base class where the derived class does not override a virtual function or access a protected base member" - this appears to echo Effective C++'s pre-template view on what nonpublic inheritance can be used for, and would trip over every typical policy-based or statically composed class. To give an easily accessible example, clang's own libc++ uses private inheritance some 40 times and protected inheritance 4 times (if my grep didn't miss any), none of which is a case involving virtual or protected members,

I suggest this enforcement check should not trigger if the nonpublic base is an empty class, a template parameter (think compressed_pair), a class template specialization, or a parameter pack.

(there are some additional non-template uses for nonpublic inheritance, like sharing virtual bases, limiting polymorphic behavior of a class to its members and deriveds, or initialization order machinations, but those are probably rare)

**Comment by gdr-at-ms** [comment]
Agreed.  It is not just libc++; well-established modern C++ idioms are affected as well (almost any good and competitive implementation of the standard library I am aware of), policy-based techniques, including use of "Empty Base Optimization" (which is now required starding with C++11).

**Comment by hsutter** [comment]
Agreed, I massaged the suggestion only slightly.
