### ISSUE TITLE
Following CERT's syntax highlighting

### ISSUE THREAD

**Issue by ToApolytoXaos** [isocpp/CppCoreGuidelines#479]
Is it possible to follow CERT's syntax highlighting that distinguishes Noncompliant Code (in red-ish color) from Compliant Code (in light green-ish color) and make it more readable?

As it is it can sometimes deceive a tired pair of eyes.

Here's the link that make it look very clean and elegant in my humble opinion: https://www.securecoding.cert.org/confluence/display/cplusplus/DCL50-CPP.+Do+not+define+a+C-style+variadic+function

**Comment by hsutter** [comment]
Can it be done in [CommonMark](http://commonmark.org/) or [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/), without resorting to HTML color tagging?

**Comment by ToApolytoXaos** [comment]
I have never done this, but I could play around a bit to figure it out. Is that alright?

**Comment by ToApolytoXaos** [comment]
@hsutter it seems we have to edit our CSS file to accomplish the desired output. Can you try __c++__ at the beginning of backticks of any example and see whether it clears the syntax a bit or not?

The border though would have be of a great help along with syntax highlighting.

**Comment by ToApolytoXaos** [comment]
@hsutter so it seems there's no way to add a colorful border and I forked the entire documentation a few minutes ago and tested it with c++ syntax highlighting; it helps immensely.

Should I continue editing all examples and then push it back to master?

**Comment by ToApolytoXaos** [comment]
@hsutter I'm becoming a pain in the neck now, but I have actually finished with editing and looks quite nice as a whole. It's a shame though that GitHub is not allowing us to add custom CSS styles; it would be nice to indicate a red-ish color as border around our **bad** examples. This way users would have correctly interpreted bad examples as bad and not mistakenly perceive them as the way to go.

Here you go: 
* [CppCoreGuidelines.md](https://github.com/ToApolytoXaos/CppCoreGuidelines/blob/master/CppCoreGuidelines.md)
* I have also edited [CONTRIBUTING.md](https://github.com/ToApolytoXaos/CppCoreGuidelines/blob/master/CONTRIBUTING.md)'s examples.

Keep up the good work people!

**Comment by AndrewPardoe** [comment]
Just a note: this change adds syntax highlighting, not the red shading or border as originally suggested. (This is just a restatement of part of @ToApolytoXaos' comment above.)

**Comment by ToApolytoXaos** [comment]
@AndrewPardoe yep, I have mentioned it at https://github.com/isocpp/CppCoreGuidelines/issues/479#issuecomment-167263825 that we can't unfortunately edit CSS to add any custom styling.

By the way, should I pull request to merge my changes with official project?

**Comment by gdr-at-ms** [comment]
See previous discussions about syntax highlighting.


-------- Original message --------

**Comment by novasdream** [comment]
https://github.com/isocpp/CppCoreGuidelines/issues/33

**Comment by ToApolytoXaos** [comment]
I see. @gdr-at-ms should I close this ticket then?

**Comment by gdr-at-ms** [comment]
Yes, but not before you mention it in the other tickets so that we don't lose track of it in case we decide yo revisit the whole issue.
Thanks.


-------- Original message --------

**Comment by ToApolytoXaos** [comment]
well @gdr-at-ms, @novasdream mentioned #33 above and that alone create reciprocal linkage and pretty much got us covered I would say.

Just let me know when to close it, else if you have access, please feel free to do so.

Cheers.

**Comment by gdr-at-ms** [comment]
Ah, it is ok to close it then.


-------- Original message --------

**Comment by ToApolytoXaos** [comment]
I'm doing it now.

Cheers @gdr-at-ms

**Comment by gdr-at-ms** [comment]
Thanks!


-------- Original message --------
