### ISSUE TITLE
P.7 use C99 VLA which is not a part of C++ standard

### ISSUE THREAD

**Issue by georeth** [isocpp/CppCoreGuidelines#480]
In the example in P.7

```c++
void use1(int m)
{
    const int n = 10;
    int a[n] = {};
    // ...
    increment1(a, m);   // maybe typo, maybe m <= n is supposed
                        // but assume that m == 20
    // ...
}
```

a is C99 VLA(variable length array).

C++ doesn't have a dynamic allocated on-stack array, but most compilers support this language extension. (dynarray was voted out from C++14 working paper into a separate Technical Specification)

So the example is misleading.

PS: I personally want the VLA to be adopted by C++.

**Comment by gdr-at-ms** [comment]
That example uses plain old-fashioned C-style array, not VLA, because the `n` is a constant.
