### ISSUE TITLE
Non-virtual interface (Template Method pattern)

### ISSUE THREAD

**Issue by Jon12345** [isocpp/CppCoreGuidelines#484]
I was surprised to read "Speaking of virtual functions, should non-virtual interface be promoted? NO." in the "To-do" list.

The guidelines in http://www.gotw.ca/publications/mill18.htm are sound, yet not widely understood. 
What's the reason for the "NO"?

**Comment by hsutter** [comment]
Good catch, thanks.

**Comment by cubbimew** [comment]
Although I originally submitted that TODO item expecting a "yes" as well, I am not sure it makes a good candidate for a guideline that may be checked by tools: mechanically NVI'ing every virtual function gives us things like [std::time_get](http://en.cppreference.com/w/cpp/locale/time_get) with seven dummy public forwarders. Is it any different from dummy getters and setters? If the customization points exactly match the public API this seems superfluous.

Something like [std::streambuf](http://en.cppreference.com/w/cpp/io/basic_streambuf), where customization points are entirely different from the public API makes more sense as a design guideline, but how could it be formalized?
