### ISSUE TITLE
ES.2x redundancy

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#488]
ES.20 takes up about 10% of the text of the whole ES section. It hits a lot of good points, but doesn't provide (stable) links to sub-points for citation in code review or the like.  (Yes, you can cite the examples or notes, but those are numbered globally and will change over time.)  

Relatedly: ES.21 and ES.22 basically just restate ES.20.  

I'd suggest adding stable links into sub-sections of ES.20 and dropping 21 and 22 entirely.
Alternatively, the text of 20 can be spread out between 21 and 22, but I think it'd be hard to ever be completely sure when to cite one or the other.

If there's editorial consensus, I'm happy to take a stab at whatever direction you like.

**Comment by BjarneStroustrup** [comment]
Now that we have structured binding, I was able to shorten ES.20 a bit. Note that every example in ES.20 are there because someone thought that the rule should be relaxed. I don't see a good way to refactor ES.20, ES.21, and ES22.
