### ISSUE TITLE
Consider {}s for arithmetic casts

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#491]
We recently had an update to our internal style guide (which I've just pushed public for this discussion) - Use {}s for arithmetic casts, since they've got good behavior wrt. narrowing and they're generally clearer.
See: https://google.github.io/styleguide/cppguide.html#Casting

I'd suggest updating ES.49 to include that style.  Let me know if that's acceptable and I'll send you a proposed change.

**Comment by hsutter** [comment]
Titus, I think the item you want to look at is ES.46 -- this touches on `narrow` and `narrow_cast`. Could you take a look at that please and let us know if you propose adding/changing anything there?

**Comment by tituswinters** [comment]
ES.46 talks about narrowing, while the brace-initialization syntax for arithmetic types only applies when there is no narrowing.  Sent you PR 530 as a suggestion.

ES.46 is also hard to act on - did you want the note about the GSL narrow_cast/narrow to be the guidance?

**Comment by tituswinters** [comment]
Closed with PR 530.
