### ISSUE TITLE
N1: myth: a raw array is orders of magnitudes faster than std::vector

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#493]
Edit: reworded 'slow == Good' to 'slow due to' thanks to @NicolBolas 
Edit: explicitly mention that the example is thanks to an initialization flaw, thanks to @scraimer, @cubbimew and @galik
Edit: mention the discussion of @scraimer, @cubbimew and @galik in the Discussion section

# N.1: myth: a raw array is orders of magnitudes faster than std::vector

**Reason**: 

The C++ Core Guidelines suggest to use a std::vector of a raw array (see 'SL.10: Prefer using STL array or vector instead of a C array'). There is a myth that for run-time speed, one should use arrays. A std::vector can never be faster than an array, as it has (a pointer to the first element of) an array as one of its data members. But the difference in run-time speed is slim and absent in any non-trivial program.

One reason for this myth to persist, are examples that compare raw arrays with mis-used std::vectors. For example, when constructing a big std::vector without reserve, arrays can indeed be orders of magnitude faster, due to copying of the std::vector its elements when exceeding its capacity. Prefer to learn the correct workings of std::vector over falling back to the use of raw arrays.

A second reason for this myth to persist is when comparing arrays and std::vector in debug mode. Where a std::vector has mechanisms in place that will help you during debugging, array are indifferent between debug and release mode. That std::vector is slower in debug mode is due to range checks, which will save time debugging run-time errors. When doing a benchmark, do this in release mode.

**Example**s:

This example shows how incorrect initialization of a `std::vector` helps this myth persist.

This example is slightly modified from the first hit when Googling 'benchmark array versus std::vector' (the post is [here](http://stackoverflow.com/questions/3664272/is-stdvector-so-much-slower-than-plain-arrays)).

Here is the benchmark code shown to be twice as slow as when using a raw array:

```
std::vector<Pixel> pixels;
pixels.resize(dimension * dimension); //Create elements that need to be modified
for(int i = 0; < dimension * dimension; ++i)
{
    // Modify each element
    pixels[i].r = 255;
    pixels[i].g = 0;
    pixels[i].b = 0;
}
```

This code is indeed twice as slow, as there are twice as much Pixels allocated. The correct equivalent would be:

```
std::vector<Pixel> pixels(dimension * dimension, Pixel(255,0,0)); //Create desired elements directly 
```

When running the benchmark in release mode, the run-time speeds are equivalent.

Note that still the comparison is unfair (in the favor of an array), as is compares a static array versus a dynamic array (in the std::vector).

**Alternative**s: 

If you do not need resizing, std::array may suit your needs and give better performance at debug mode.

**Exception**s: 

There may be cases in which you need good performance in debug mode as well. 

**Enforcement**: 

**See also**s: none

**Note**s:

**Discussion**:

It may be that optimizers once were better in optimizing calls to `operator[]` on a plain array, instead of a `std::vector`. Nowadays there is little evidence that this still is the case (see for example [std::vector](https://godbolt.org/g/P5pPYE) versus [array decayed into a pointer](https://godbolt.org/g/9Tj8n2)

**Comment by NicolBolas** [comment]
> That std::vector is slower in debug mode is A Good Thing.

Well, that kinda depends on how much performance you need while still being able to debug your code.

**Comment by MikeGitb** [comment]
I think it is a good idea to address this in the C++CG.

Regarding the text itself I think it needs to be mentioned that that workaround doesn't work if the elements need to get initialized to different values (at least not without some trickery). I guess one important thing to point out is that it is a one-time cost that applies to initialization and not to the `[]`-operator.

**Comment by galik** [comment]
If I am not mistaken the example appears to be presenting a false comparison. It appears to be comparing *static arrays* with `std::vector` when it should be comparing *dynamic arrays* with `std::vector` and *static arrays* with `std::array`.

**Comment by jdgarciauc3m** [comment]
That is a very good point.
When you do the right comparisons you will find that C++ ends up being as fast as C. And in some cases C++ results being even faster than C.

**Comment by MikeGitb** [comment]
@galik: Not really: What do you consider a static array? Lots of times you might have an array that doesn't change its size after creation, but you still don't know the size at compile time, so you can't use std::array. In the example both arrays are created on the heap.

**Comment by galik** [comment]
@MikeGitb Maybe my terminology is not great but by *static array* I mean an array whose size is determined at *compile time* as opposed to a *dynamically created* array.
```cpp
int arr1[10]; // static

int* arr2 = new int[10]; // dynamic
```

**Comment by MikeGitb** [comment]
@galik: Assuming you are talking about the SO-example: The question uses the latter syntax (although using malloc instead of new).

**Comment by galik** [comment]
@MikeGitb  No, I was thinking about parts in @richelbilderbeek  discussion here, for example, where it says
>"A std::vector can never be faster than an array, as it has (a pointer to the first element of) an array as one of its data members."

This appears to imply that the array it is being contrasted with is not accessed through a pointer to its first element. But a *dynamic array* is always accessed through such a pointer.

**Comment by MikeGitb** [comment]
@galik: Ah, thats the reason for my confusion. 

Still, I don't think the argument was about static vs dynamic array or about access through a pointer, just that - as vector is an abstraction on top of a native array - it can not be more efficent than a plain array, but at most match it (whether that is strictly true or not is up to debate).

**Comment by cubbimew** [comment]
> But a dynamic array is always accessed through such a pointer.

in source code, but not necessarily in the compiled program: https://godbolt.org/g/CA8JSU

**Comment by galik** [comment]
@MikeGitb I agree with you, I'm not trying to make a statement about its relative speeds I just think the piece may not be being precise enough about the comparisons it is presenting. So the real answer to those who compare the speed of a `std::vector` to that of a *static array* would be to point out the false comparison. Once that is made clear the details can focus on the real comparison between a *dynamic array* and a *vector*.

**Comment by galik** [comment]
@cubbimew I am impressed by the optimization the compiler made there. However I suspect the compiler has optimized away the entire code because you gave it all the information at compile time. If you were to obtain your values from an *opaque* function (like a random number generator) the compiler might have a harder time getting rid of operations.

**Comment by MikeGitb** [comment]
@galik: OK, so first of all I don't think @richelbilderbeek wanted to talk about comparison between static array and vector, but that is something he himself can better answer. 
I also don't think this is a common complain around programmers - at least I hope no one is using a vector when a static array or std::array would do. Where I did hear some justified grumbling is std::vector vs non-standard, but widely supported variable length arrays. But that is of course not the the scope of this rule.

All that aside, you are probably right and the non-rule should state more clearly, what the example is compared to.

**Comment by richelbilderbeek** [comment]
Blimey, thanks for this IMHO fun discussion. 

I agree on the points mentioned about flaws in the benchmark,  but this is not my main point (I used that benchmark as it is the first hit when Googling 'run-time speed array versus vector').

I just hope we can defuse this myth, by putting it in the C++ Core Guidelines.

**Comment by scraimer** [comment]
@cubbimew and @galik got me thinking.
I should compare just the usage of each container, excluding the setup.
The size of the array should not be known at run-time.

Both GCC and Clang generate the same amount of assembly, and the content is nearly the same.
It seems that the example I chose is too opaque for the optimizer to see through.

* std::vector - https://godbolt.org/g/P5pPYE
* array decayed into a pointer - https://godbolt.org/g/9Tj8n2

Maybe the basis of the myth is in the limits of the optimizer

**Comment by richelbilderbeek** [comment]
> Maybe the basis of the myth is in the limits of the optimizer

In the example I show, the myth is based on incorrect usage of std::vector, as all elements are created twice.

Here I quote myself, with some extra comments:

> Here is the benchmark code shown to be twice as slow as when using a raw array:

```c++
std::vector<Pixel> pixels;
pixels.resize(dimension * dimension); // Creates all elements
for(int i = 0; < dimension * dimension; ++i)
{
    // Modify all elements
    pixels[i].r = 255; 
    pixels[i].g = 0;
    pixels[i].b = 0;
}
```

> This code is indeed twice as slow, as there are twice as much Pixels allocated. 
> The correct equivalent would be:

```c++
//Directly create the correct elements
std::vector<Pixel> pixels(dimension * dimension, Pixel(255,0,0)); 
```

> When running the benchmark in release mode, the run-time speeds are equivalent.

**Comment by scraimer** [comment]
Oh! You're focusing on the cost of _initialization_!
See, I was focusing on the cost of "usage" (what do you call that? access?).
In my day-to-day, the software allocates and initializes huge tracts of memory just once, but latency is affected by how fast you can finish the tasks that you have to do over and over.

Is this guideline meant to focus just on initialization costs? Can we separate the concerns between init-time and the rest of the run-time?

**Comment by richelbilderbeek** [comment]
Thanks to you, I guess there are two concerns :-)

I'll edit the rule to make this more explicit...

**Comment by richelbilderbeek** [comment]
I just modified the rule, I hope I you think I did a good job condensing our discussion. If not, I look forward to more of it :-)

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, this is a good rule to have in some fashion or another. We can have a myth-busting rule of "Arrays are always faster/simpler than alternatives". Bjarne would like to take a stab at this.

**Comment by BjarneStroustrup** [comment]
I added a comment about performance comparisons to SL.con.1

**Comment by hass612** [comment]
i disagree vectors are dynamically allocated while arrays are static and when you look at data in memory in an array they are all right next to each other, but since vectors are dynamically allocated they are all over your memory in random locations so the program jumps from memory spot to memory spot and takes more time to run, instead of just going to the next memory spot like an array. but vectors are better if you constantly shift elements around and delete since they are not right next to each other inside of memory you dont have to shift ALL of the elements inside of the vector like you would an array, so it really depends on what you need them to do
