### ISSUE TITLE
F.5 Incorrectly states that template functions must be in headers

### ISSUE THREAD

**Issue by SaintDubious** [isocpp/CppCoreGuidelines#496]
I often hear this falsehood repeated even by senior developers. I think it would help people adopt templates if they were aware that they can act like "normal" classes with the interface in the header and the implementation in a cpp file (by using the <code>template class Foo&lt;int>;</code>). More info at:
https://isocpp.org/wiki/faq/templates#separate-template-fn-defn-from-decl
Granted there are cases where you can't know all the possible types that will be used to instantiate a template, so this technique doesn't always work. The Exception should be expanded so that it doesn't seem so black and white.

**Comment by NicolBolas** [comment]
I fail to see how that improves anything. The translation units that instantiate a template must have access to its definition.

The FAQ example makes no sense in general. What's the point of sticking the declaration in the header at all? It's not like someone else can include it and use it without also copying the definition to their translation unit. And if the definition is updated in one place and not the other... oops: ODR violation. No, that coding style is just exceedingly dangerous.

Templates cannot "act like 'normal' classes" in any genuinely meaningful way. The best you can do is have a header that declares it and a second header that defines it. Your code still needs to include both, so they're both still headers.

**Comment by SaintDubious** [comment]
@NicolBolas Unless I misunderstand, the point to the technique is that the compiler actually does not need to include both the declaration and the code. You can create a template header with no function body at all, which can be included by other .cpp files. Then you create a separate cpp file that includes the function body AND the list of specific instantiations you want to create (using the previously mentioned <code>template class Foo&lt;int></code> syntax). 

Granted there is a bit caveat to this, which is that you are specifically telling the compiler which types you want to instantiate your template with. So it doesn't work for a general purpose, library template. But if you have an application and you know you want to instantiate a template for only specific types in your app, then you can do this.

I've only used this trick with Visual Studio and gcc, but I believe it's correct usage. I think it's something that should be better understood by the community at large, which is why I think the text to F.5 should be amended.

**Comment by MikeGitb** [comment]
@NicolBolas: I'm sure you are aware of explicit template instanciation right? So it appears there is in deed some missunderstanding between the two of you.

@SaintDubious :
> Granted there are cases where you can't know all the possible types that will be used to instantiate a template

I'd say it is usually the other way round: The more common case is that you don't know all the types and only in rare situations can you actually enumerate all possibilities.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we can change this to state that templates are normally defined in headers.
