### ISSUE TITLE
T.43.1: Omit uses of typedef to get rid of struct/class/union

### ISSUE THREAD

**Issue by LegalizeAdulthood** [isocpp/CppCoreGuidelines#499]
**Reason**

Improved readability by eliminating unnecessary clutter.

**Example**

In `C`, the `struct`, `class` and `union` keywords are necessary before an identifier to specify a full type:

```
struct S
{
    int a;
    int b;
};

struct S f;  // OK S is the name of a struct
S g; // error: unknown type name 'S'
```

Therefore it is common `C` idiom to use `typedef` to introduce a synonym for the `struct`:

```
struct tagS 
{
    int a;
    int b;
};
typedef struct tagS S;

struct tagS f;  // OK tagS is the name of a struct
S g; // OK: S is a synonym for tagS
```

In `C++`, `struct`, `class` and `union` introduce the names of new types and we don't need to decorate the name with their declaring keywords in order to use them directly, but the `typedef` habit persists from C style code, particularly when declaring structures.

**Enforcement**

Flag uses of `typedef` of the form:

```
typedef struct id1 id2;
typedef union id1 id2;
typedef class id1 id2;
```

The suggested refactoring is to replace the declarations of the original structure (`struct id1`) to one using the typedef alias name directly (`struct id2`) and eliminate the `typedef` alias.

**Comment by mbait** [comment]
I would also mention that this is a bad style in C as well, because now it sounds like it's normal to do it in C.

**Comment by galik** [comment]
Also there is the idiomatic  anonymous `struct` version that gets rid of the first identifier and goes straight for the typedef:
```cpp
typedef struct
{
    // struct definition here
} mystruct;
```

**Comment by LegalizeAdulthood** [comment]
@mbait I think in `C`, there is no avoiding the `typedef` unless you want to keep repeating the declaring keyword `struct` or `union` throughout your code.

**Comment by mbait** [comment]
That's the point. When you hide `struct` and `union` the code becomes less
readable. I won't insist here, because ultimately it's C++ guidelines. It's
just very frustrating to see people using `typedef` to hide `struct` in C
just because they saw it somewhere. The most of mature C projects don't
follow this style.

On Fri, Jan 15, 2016 at 10:47 AM, Richard Thomson <notifications@github.com>
wrote:

> @mbait <https://github.com/mbait> I think in C, there is no avoiding the
> typedef unless you want to keep repeating the declaring keyword struct or
> union throughout your code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isocpp/CppCoreGuidelines/issues/499#issuecomment-172048579>
> .
>



-- 
Sincerely, Alexander

**Comment by LegalizeAdulthood** [comment]
@mbait The only large `C` code base I ever worked on was the X Window System and they used `typedef` quite a bit in that code circa 1988-1993 ([example `Xlib.h`](http://www.opensource.apple.com/source/tcl/tcl-87/tk/tk/xlib/X11/Xlib.h)).  Since then, I've only worked in `C++` code bases where I've seen this `C` habit creeping into `C++` code bases over and over again when it isn't needed.  From that I inferred that this habit is still widespread in `C` code bases, since `C++` doesn't need it at all (just use the type identifier directly) and it is `C` that needs it if you want to use the identifier directly.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we appreciate the suggestion but find it to be a bit too specific. Rule [P.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-Cplusplus) and the entire [CPL section](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-cpl) cover the topic of favoring C++ code over C code at a good level for these guidelines. We feel specific instances like this are better handled by C++ textbooks.
