### ISSUE TITLE
F.46 sample code is incorrect

### ISSUE THREAD

**Issue by SaintDubious** [isocpp/CppCoreGuidelines#500]
I could be wrong, but I thought the one true, correct main function was
<pre>
int main( int agrc, char** argv )
</pre>
F.46 states that returning void is incorrect, but then says the correct version is 
<pre>
int main()
</pre>
It then goes on to show an example that claims to return an int, but doesn't actually return anything. I hope this wouldn't compile, at the very least I imagine it's a warning. I'd suggest we make the example:
<pre>
int main( int agrc, char** argv )
{
    std::cout << "This is the way to do it\n";
    return 0;
}
</pre>

Also, it may be a good idea to explain that 0 is the proper return for no error (and why that's correct despite the fact that people think of 0 as false).

**Comment by mbait** [comment]
`int main()` declares a function that takes arbitrary number of arguments, so unless you use `argc` and `argv` it's fine to omit them.

**Comment by galik** [comment]
The `C++` standard mandates that two specific signatures must be allowed for main, those being:

    int main() {}

    int main(int argc, char* argv[]) {}

And that main must return `int`.

It also states that if no return statement is given when `main()` exits it is equivalent to calling `return 0;`.

So the example should compile on a conforming compiler.

**Comment by SaintDubious** [comment]
Well I'll be darned, looks like I'm wrong on both counts. A little embarrassing, but always nice to learn something. Thank you both for the information.

**Comment by galik** [comment]
@mbait I think you may be confusing the rules of `C++` with those of `C`. Unlike `C` declaring a function with an empty parameter list `int func()` is equivalent to declaring it as `int func(void)` meaning zero parameters.

**Comment by mbait** [comment]
Yes, you're right.

On Fri, Jan 15, 2016 at 11:04 AM, Galik <notifications@github.com> wrote:

> @mbait <https://github.com/mbait> I think you may be confusing the rules
> of C++ with those of C. Unlike C declaring a function with an empty
> parameter list int func() is equivalent to declaring it as int func(void)
> meaning zero parameters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isocpp/CppCoreGuidelines/issues/500#issuecomment-172055034>
> .
>



-- 
Sincerely, Alexander

**Comment by gdr-at-ms** [comment]
The example is correct.
