### ISSUE TITLE
Suggestion: Why don't provide LaTeX file

### ISSUE THREAD

**Issue by svandex** [isocpp/CppCoreGuidelines#501]
If those pdf files and md files are LaTeX files, users can build the pdf by their own.I think it is better for us to provide pull quests and make the guidelines better?

**Comment by NicolBolas** [comment]
The guidelines are authored in Markdown; that's the source for the PDF and so forth. So you'd be asking them to switch to using LaTeX as the primary format. And LaTeX is not particularly easy to author, particularly for those not used to it.

**Comment by mbait** [comment]
Not to mention, that isn't as readable as markdown, so one would probably
have to compile the former to be able to see what a PR is about.

On Sun, Jan 17, 2016 at 11:47 AM, NicolBolas <notifications@github.com>
wrote:

> The guidelines are authored in Markdown; that's the source for the PDF and
> so forth. So you'd be asking them to switch to using LaTeX as the primary
> format. And LaTeX is not particularly easy to author, particularly for
> those not used to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isocpp/CppCoreGuidelines/issues/501#issuecomment-172371256>
> .
>



-- 
Sincerely, Alexander

**Comment by LegalizeAdulthood** [comment]
[pandoc](http://pandoc.org/) claims to be able to convert from markdown to LaTeX, but I've never tried it.

**Comment by AndrewPardoe** [comment]
Thanks for the great discussion. As suggested, we'll keep MarkDown as the main format and you're welcome to convert it to whatever other formats you like.
