### ISSUE TITLE
Suggestion: C.9: prefer design patterns over custom class architectures

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#503]
# C.9: prefer design patterns over custom class architectures

**Reason**: 

The GoF classic 'Design Patterns' supplies twenty field-tested design patterns that are designed to be extendible. It also gave software architects a common vocabulary and a way to think about your software architecture at a higher abstraction level.

**Example**s:

If you want to encapsulate an algorithm, use the Strategy design pattern.

**Alternative**s: 

**Exception**s: none

**Enforcement**: none

**See also**s: none

**Note**s:

**Discussion**: 

AFAIK there is no reference to C++11/14/17 versions of the design patterns by the GoF. 

I personally would like to have a reference somewhere or add a guideline for every pattern, for example: 'C.x: Use the Strategy design pattern if you want to encapsulate an algorithm' that supplies a full example Strategy.

**Comment by cubbimew** [comment]
Design patterns in the C++ context are an involved topic that might be too high-level for this guide: @andralex wrote a whole book on the Strategy design pattern once. And @stephencdewhurst wrote a few, too.

**Comment by richelbilderbeek** [comment]
@cubbimew: the guide is also intended to have high-level rules (see Stroustrup's introductory talk, slide 13, e.g. https://github.com/isocpp/CppCoreGuidelines/blob/master/talks/Stroustrup%20-%20CppCon%202015%20keynote.pdf). 

AFAIKS I do not think that Alexandrescu wrote 'a whole book on the Strategy design pattern once'. Sure, he mentioned some design patterns in 'Modern C++' from the pre-C++11 era. Same for Dewhurst in 'C++ Common Knowledge' or 'C++ Gotchas'. I'd love to hear the title of a C++11/14/17 design patterns book I appear to overlook.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we are inclined to agree with @cubbimew. These references exist: where design patterns are appropriate, please refer to these books. The Guidelines are more about the proper use of the C++ language and constructs than they are about architectural patterns.
