### ISSUE TITLE
Should we list tool support in recommendations?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [isocpp/CppCoreGuidelines#505]
I like that the guidelines mention how automated checks could be performed to flag violations.

Where a guideline has support from a specific development tool, should we call those tools out explicitly?

For instance, clang-tidy is gaining a number of checks that can enforce some of the specific recommendations and I suspect they will continue adding more over time.

**Comment by johnthagen** [comment]
Migrating from #545.

I suggest that a short list be added to the `CppCoreGuidelines` Appendix or FAQ.

I spent some time searching and found two linters:
- [Visual Studio 2015 CppCoreCheck](https://www.nuget.org/packages/Microsoft.CppCoreCheck)
- [`clang-tidy`](http://clang.llvm.org/extra/clang-tidy/#writing-a-clang-tidy-check)

@LegalizeAdulthood also mentioned:
- [Cppcheck](http://cppcheck.sourceforge.net/) (though [the core developer is not interested](https://sourceforge.net/p/cppcheck/discussion/development/thread/2875f97d/))
- [OCLint](https://github.com/oclint/oclint)

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we should mention tools only if they directly support enforcement of the Guidelines. This would, I believe, only currently include [clang-tidy's CppCoreGuidelines rules](https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clang-tidy/cppcoreguidelines/) and the [VS 2017 CppCoreCheck](https://blogs.msdn.microsoft.com/vcblog/2016/10/12/cppcorecheck/).

CppCheck and OCLint seem to be too general for inclusion here. 

I will add these two tools to the Appendix or FAQ.
