### ISSUE TITLE
Suggested rule: ES.87: Always enclose control-flow statement bodies within braces

### ISSUE THREAD

**Issue by villintehaspam** [isocpp/CppCoreGuidelines#506]
Motivation for why there should be a rule:

Omitting braces for if/for/do/while statements that only have single statement as their body is error-prone during maintenance and code merging. This can lead to serious bugs.

Note: some programmers do not agree with the proposed rule for stylistic reasons, such as the closing brace taking up vertical space. IMHO, decreased risk of maintenance problems trumps personal taste.

An alternative to using a separate rule would be to include this advice together with [ES.85: Make empty statements visible](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es85-make-empty-statements-visible) - that is how the [JSF coding standards](http://www.stroustrup.com/JSF-AV-rules.pdf) do it.

Suggested wording:

## ES.87: Always enclose control-flow statement bodies within braces

The bodies of `if`, `else if`, `else`, `while`, `do..while`, and `for` statements should always be enclosed within braces.

**Reason**

Code added during maintenance may change the program behavior in subtle ways that where not intended. It is easy to overlook the issue as indentation may cause the code to appear to be correct.

**Example**

    // BAD
    if (condition)
        do_something();
        and_do_something_more(); // Always called regardless of condition
    if (other_condition)
        do_something_else();

    // Better
    if (condition) {
        do_something();
        and_do_something_more(); // Now clear when this is called
    }
    if (other_condition) {
        do_something_else();
    }

**Enforcement**
Flag control-flow statements that do not use braces to enclose their bodies.

**Comment by LegalizeAdulthood** [comment]
I view "taking up vertical space" as a feature, not a bug.  We want small functions and methods; I will use the term "function" synonymous with method from hereon.  When the braces take up vertical space it puts even more psychological pressure on the function to be smaller.  Large amounts of control flow within a function is where all the braces show up and take up all the space.  This is a sign that the function is getting too complex and should be broken up into smaller functions that reveal the intermediate intentions of the previously long function.

My personal experience has been that I hear the "too much vertical space" complaint from exactly the same people that write functions that are overly complex or long.  They use their arguments for compactness to mask the fact that they are producing large and/or complex functions.

Therefore, I view taking up vertical space as a feature: it shines the light on these large and/or complicated functions and makes them stand out.

**Comment by rwst** [comment]
Commata suggested around "where not intended".

**Comment by mhandb** [comment]
A recurrent issue I have observed with omitted braces is with code commenting, some  developer comments the instruction after the if/for without caring about the impact on the lines bellow.

This rule is a must in many dev guidelines.

**Comment by gdr-at-ms** [comment]
We discussed this in the past.  Our recommendation is that single statement controlled by control conditionals and jumps need not be included in braces.  
A team or organization is free to impose stricter formatting requirement and use tools to enforce them -- see rule [NL.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-indent)
