### ISSUE TITLE
auto x = {1};   // x is an int (after correction of the C++14 standard; initializer_list in C++11)

### ISSUE THREAD

**Issue by gmartin-epic** [isocpp/CppCoreGuidelines#51]
The above quoted information is incorrect as I understand the standard. That case will always be an initializer list, even in C++17.

What's changed is direct-list-initialization: `auto x{1};` will result in x being an int in C++17, but was an initializer_list previously.

**Comment by AndrewPardoe** [comment]
Fixed, thanks for the correction.
