### ISSUE TITLE
Typos in second example for "F.24: Use a span<T> or a span_p<T> ..."

### ISSUE THREAD

**Issue by jmarathe1** [isocpp/CppCoreGuidelines#511]
Here's the example:

void f(span<int> s)
{
    for (int x : s) cout << x << '\n';  // range traversal (guaranteed correct)
    for (int i = 0; i<s.size(); ++i) cout << x << '\n';  // C-style traversal (potentially checked)
    s[7] = 9;                           // random access (potentially checked)
    std::sort(&s[0],&s[s.size()/2);     // extract pointers (potentially checked)
}

Typos:
1. In the second 'for' loop, should 'x' be 's[i]' instead? 'x' is not in scope.
2. In the call to 'std::sort', missing ']'. Should be '&s[s.size()/2]' .

**Comment by jwakely** [comment]
1 was fixed by d6143fb6c75238adb7a449abc9fc135242ecd2e5

2 was fixed by 67bf6a14ab4ef2dbd9e16c0e4676f0860596ccf0

**Comment by jwakely** [comment]
Closing as fixed.
