### ISSUE TITLE
F.18 (use std::move) contradicts ES.56 (do not use std::move)

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#514]
`F.18: For "consume" parameters, pass by X&& and std::move the parameter`
contradicts with the recently-added rule
`ES.56: Avoid std::move() in application code`

I am not sure which one makes a better guideline:

F.18 asks the enforcement to flag uses of moved-from objects, which addresses the chief complaint of ES.56 (leaving bad objects behind). 

ES.56 permits `std::move` when moving from an rvalue function parameter, which appears to take care of most correct uses of `std::move` in practice (at least as seen in the first few pages of the [debian code search results](https://codesearch.debian.net/perpackage-results/std%3A%3Amove/2/page_0)), the only additional case I can readily think of is the [`std::promise` hand-off](http://en.cppreference.com/w/cpp/thread/promise#Example) into a new thread.

**Comment by hsutter** [comment]
Thanks! We ended up rewriting ES.56 and it's much better now.
