### ISSUE TITLE
C.2: Make a stronger case for why this matters

### ISSUE THREAD

**Issue by DanielJump** [isocpp/CppCoreGuidelines#516]
This feels more like a style guideline to me / personal preference. I don't infer any meaning when I see struct or class in the code. Using 'class' is just extra typing to add public: on the next line. If we are going to keep this style rule, it should be enforced by forcing structs to have all publics and classes to have no publics.

**Comment by BjarneStroustrup** [comment]
I strengthened the rationale. I added rule C.8 and C.9 about using `class` for classes with private data and placing interfaces first in a class. Added a link to the rule against protected data.
