### ISSUE TITLE
I.11: "Never transfer ownership by a raw pointer (T*)" doesn't mention transfer by method parameter

### ISSUE THREAD

**Issue by murraycu** [isocpp/CppCoreGuidelines#522]
[I.11: Never transfer ownership by a raw pointer (T*)](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i11-never-transfer-ownership-by-a-raw-pointer-t)
discusses how to transfer ownership as a return type. But shouldn't it also discuss transferring ownership via a method parameter? I guess it would look like this, from the caller:

auto something = std::make_unique<Something>("something");
...
foo.set_something(std::move(something));

These other sections don't mention this either:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-unique_ptr
(discusses return types only)
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f7-for-general-use-take-t-or-t-arguments-rather-than-smart-pointers
(only has an example of when _not_ to take a smart pointer (shared_ptr) as a parameter).

**Comment by villintehaspam** [comment]
The rule does have a link to [F.15: Prefer simple and conventional ways of passing information](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f15-prefer-simple-and-conventional-ways-of-passing-information) on the topic of argument passing.

So I would argue that the information is present in F.15 + F.18, and that the link in I.11 is enough.

**Comment by murraycu** [comment]
Thanks. If the advice is then _not_ to take ownership like so:
  void set_something(std::unique_ptr<Something> something)
then I think it could be much clearer about it. But I don't think that's what the document is trying to say.

F.15 seems to be more a discussion of whether the type should be passed by ref, const ref, ref ref, etc, rather than what the underlying type should be.

F.18 (which has no example) does mention "Unique owner types that are move-only and cheap-to-move, such as unique_ptr, can also be passed by value" but I'd far rather have an explicit obvious example in I.11 which actually discusses why and when you'd use owner and unique_ptr (as parameters), rather than exactly how to pass them.

**Comment by murraycu** [comment]
By the way, one reason that I'd like to see this spelled out clearly, is that it would sometimes require use of std::move() by the caller, correctly I think. But that's something that's sometimes discouraged and there's even a rule against it:
[ES.56: Avoid std::move() in application code](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-move)

However, see https://github.com/isocpp/CppCoreGuidelines/issues/514

**Comment by murraycu** [comment]
Actually, "[R.32: Take a unique_ptr<widget> parameter to express that a function assumes ownership of a widget](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r32-take-a-unique_ptrwidget-parameter-to-express-that-a-function-assumes-ownership-of-a-widget)"  does mention exactly this, so maybe it should just be linked to from I.11.

I feel that the advice about this is spread rather widely across the whole document.

**Comment by murraycu** [comment]
> By the way, one reason that I'd like to see this spelled out clearly, is that it would sometimes 
> require use of std::move() by the caller, correctly I think. But that's something that's sometimes 
> discouraged and there's even a rule against it:
> ES.56: Avoid std::move() in application code
> However, see #514

That section has now been rewritten, with some examples of when you _should_ use std::move when passing parameters. I guess I.11 should have a link to that too, as well as a link to R.32. Though really, it seems that all these sections should maybe just be combined or link to some combined example.

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, these links are useful. Thank you for the suggestion!

**Comment by BjarneStroustrup** [comment]
added xrefs as suggested
