### ISSUE TITLE
Re question by Herb Sutter in C.129: An example of legitimate implementation inheritance

### ISSUE THREAD

**Issue by hpenne** [isocpp/CppCoreGuidelines#525]
I agree with Herb Sutters comment in C.129 that implementation inheritance often seems like an anti pattern.  It is used far too often.

However, I'm right now involved with a protocol implementation that uses the State Design Pattern:
https://en.wikipedia.org/wiki/State_pattern

This uses implementation inheritance to model super states, and this seems like a legitimate use of implementation inheritance.  This design pattern keeps little or no data in the state classes (that's what the Context class is for), which means that there is very little actual coupling vertically in the class hierarch.

**Comment by gdr-at-ms** [comment]
Thanks.  This section has been clarified since the original submission.
