### ISSUE TITLE
Enforcement for Data Races

### ISSUE THREAD

**Issue by tituswinters** [isocpp/CppCoreGuidelines#529]
The enforcement section for CP.2 is currently just "Some is possible, do at least something."

We've done a ton of work to make our code resistant to data races, through both static and dynamic analysis.  It is all, however, toolchain specific.  

So, question for the editors: Would you like me to put together discussion and examples (and links to tools) for this, knowing that the examples and links are going to be clang specific?

**Comment by BjarneStroustrup** [comment]
Yes, please do, remembering that we might want to edit/polish what you wrote a bit to make it applicable to a wider audience.

**Comment by tituswinters** [comment]
Sent PR 787

**Comment by BjarneStroustrup** [comment]
Closed after PR 787 was done
