### ISSUE TITLE
Reversed comments in F.19

### ISSUE THREAD

**Issue by jcoffin01** [isocpp/CppCoreGuidelines#53]
Unless I'm misreading things, the comments on the example in F.19:

    int length(zstring p);  // it is the caller's job to make sure p!=nullptr

    int length(not_null<Zstring> p);    // the implementor of length() must assume that p==nullptr is possible

...are swapped. At least as I'd normally read things, a `not_null<Zstring>` allows the imlementor to assume that `p!=nullptr`, and a simple `zstring` parameter requires him to assume that `p==nulltpr` is possible (In fact, I'd assume that `not_null`'s ctor would throw when/if passed a `nullptr`).

**Comment by AndrewPardoe** [comment]
We've taken a PR to fix this, thank you.
