### ISSUE TITLE
F4. Why example is C++14 and not C++11

### ISSUE THREAD

**Issue by jepessen** [isocpp/CppCoreGuidelines#538]
Rule F4 says that following sample is for C++14 and not C++11, and for the last one we should use the recursive version of factorial. Why this code is not C++11, and why recursive version of factorial is not used here?

`
constexpr int fac(int n)
{
    constexpr int max_exp = 17; 
    Expects(0 <= n && n < max_exp);
    int x = 1;
    for (int i = 2; i <= n; ++i) x *= i;
    return x;
}
`

**Comment by malchemist** [comment]
>  Why this code is not C++11
Because in C++11, the function body can't contain definitions of the variables.

**Comment by jepessen** [comment]
Ok thanks for the explanation.
