### ISSUE TITLE
C.86 example accesses private members

### ISSUE THREAD

**Issue by martinbis11** [isocpp/CppCoreGuidelines#541]
The example for rule C.86 "Make == symmetric with respect to operand types and noexcept" defines the == operator outside of the class.

```
class X {
    string name;
    int number;
};

bool operator==(const X& a, const X& b) noexcept { return a.name == b.name && a.number == b.number; }
```

However, the operator accesses private member variables.

**Comment by GiovanniDicanio** [comment]
They could either substitute `class X` with `struct X`, or just declare `operator==` _friend_ of X.

**Comment by BjarneStroustrup** [comment]
fixed
