### ISSUE TITLE
CPL.1: Example is not valid C

### ISSUE THREAD

**Issue by jibsen** [isocpp/CppCoreGuidelines#542]
In the example, the assignment `pi = pv` results in undefined behavior unless `ch` happens to be correctly aligned for an int (C11 6.3.2.3p7).

Accessing the memory of a char value using a pointer to int in `*pi = 999` breaks the strict aliasing rule, and is also undefined behavior (C11 6.5p7).

I think the point would come across better if the example were valid C.

**Comment by borissmidt** [comment]
you are right, it can be solved with a union... which grantees that both the int and the char are alligned.
But the example should have used structs i think. 
```
struct dataX{
  int type;
  bool x;
  double weight;
}
struct dataY{
   int type;
   int x;
  double temperature;
  int acceleration_XYZ[3];
}
int main(){
    struct dataX x;
    void* ptrX = &x;
    struct dataY* = ptrX; // C cast
}
```
this is mostly used with void* functions.

**Comment by cubbimew** [comment]
Note; as of https://github.com/isocpp/CppCoreGuidelines/commit/2950a035893b9d9cf153fd37f3b17eb8520e160e CPL.1 explicitly makes the point that its C code has these subtle bugs

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, the associated PR was closed almost a year ago, and the change that @cubbimew mentions makes the reasons clear. Thank you for the suggestion, but we will take no action at this time.
