### ISSUE TITLE
Enumerate C++ Core Guideline Linters

### ISSUE THREAD

**Issue by johnthagen** [isocpp/CppCoreGuidelines#545]
I think it's very important for people new to the C++ Core Guidelines to be able to easily discover the available C++ Core Guidelines linters for their project.  I suggest that a short list be added to either the `README` or the `CppCoreGuidelines` Appendix or FAQ.

I spent some time searching and found two:
- [Visual Studio 2015 CppCoreCheck](https://www.nuget.org/packages/Microsoft.CppCoreCheck)
- [`clang-tidy`](http://clang.llvm.org/extra/clang-tidy/#writing-a-clang-tidy-check)

If a user isn't using Visual Studio 2015 or `clang`, do they have any options at this point?

The section listing the linters could also encourage developers of new C++ Core Guidelines linters to register themselves here.

**Comment by LegalizeAdulthood** [comment]
Seems to duplicate [issue 505](https://github.com/isocpp/CppCoreGuidelines/issues/505)

**Comment by johnthagen** [comment]
@LegalizeAdulthood Sorry about that, didn't see the previous issue you listed.

**Comment by johnthagen** [comment]
Duplicate of #505
