### ISSUE TITLE
CP suggestion: don't share data

### ISSUE THREAD

**Issue by tvaneerd** [isocpp/CppCoreGuidelines#547]
To avoid data races, contention, and dead-locks in concurrent code, it is often best to just not share data.  It is better to make copies of data, or a "snapshot" of the current state, with each thread getting its own copy.

If your data is always changing (ie rendering a document on a thread while the user edits it in another thread) the snapshot may be out of date as soon as it is taken, but even if you were use the latest-greatest data (with locks), the results would also be out of date as soon as they were calculated anyhow.  With threading, "when" is a fleeting notion.

**Comment by tvaneerd** [comment]
Could steal from my own slides:

Guide to Threaded Coding
1. Forget what you learned in Kindergarten - Stop Sharing
2. Use Locks
3. Measure
4. Measure (your first measurements were wrong)
5. Change your Algorithm - ie GOTO 1

∞. Lock-free
∞+1. Measure. Measure.

Lock-free coding is the last thing you want to do.

**Comment by tvaneerd** [comment]
And/or for lock-free guidelines

**Comment by AndrewPardoe** [comment]
We've since created item [CP.mess](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#SScp-mess). & CP.31. Bjarne, could you add a comment that the point of message passing is what Tony suggests: avoiding shared data? Maybe a "don't share data" section?

**Comment by BjarneStroustrup** [comment]
I added a cross reference ,
