### ISSUE TITLE
CP suggestion: never call unknown code while holding a lock

### ISSUE THREAD

**Issue by tvaneerd** [isocpp/CppCoreGuidelines#549]
Never call unknown code from within a lock.  Unknown code includes virtual functions, interfaces, pointers to functions, function-like objects, etc.  The unknown code could also obtain - or _wait_ on - a lock, and in certain (usually rare and untested thus hard to find) cases, this could lead to deadlocks.
### Example

```
MyClass::OnMouseMove(int x, int y)
{
    std::lock_guard<std::mutex> lock(myMutex);
    myPos = calcNewPosition(myPos, x, y);
    notify(POS_CHANGED, myPos);   // virtual
}
```

Do any of the derived classes obtain a lock in their notify() function?  Do you even know what the derived classes are (now and in the future)?
If notify() also attempts to grabs a lock, there is potential for deadlock.

Instead:

```
MyClass::OnMouseMove(int x, int y)
{
    Position temp;
    {
        std::lock_guard<std::mutex> lock(myMutex);
        myPos = calcNewPosition(myPos, x, y);
        temp = myPos;
    }
    // call unknown code outside the lock:
    notify(POS_CHANGED, temp);   // virtual
}
```

**Comment by tvaneerd** [comment]
sorry if that is not the right function-naming style.  (ie maybe should be on_mouse_move() etc)

**Comment by tvaneerd** [comment]
There will be a talk at C++Now (and probably CppCon) about how to do this correctly with the observer pattern.  It is harder there because the lock typically guards the list of observers.  If you copy the list and call them outside the lock, you may call listeners who have already detached from listening (and possibly have been destroyed)! (They detached between when the list was copied vs when the list was processed and called.)

**Comment by hsutter** [comment]
This now exists as item CP.22.

**Comment by hsutter** [comment]
But we agree that example is horrible, it should not be using or encouraging a `recursive_mutex`.
