### ISSUE TITLE
CP suggestion: characterization of async tasks

### ISSUE THREAD

**Issue by tvaneerd** [isocpp/CppCoreGuidelines#550]
Know the characteristics of your async tasks.  Do they consume memory? CPU? Are they bound by disk throughput? Bus?  Are they waiting on the network? Or waiting on the internet?

Different types of tasks "cooperate" better than others.  If you have 20 CPU intensive tasks and only 8 cores, concurrency just leads to "fighting" for the cores and excess context switching.  It may be better (in that the totality of tasks is completed sooner) if some of those tasks were serialized.

On the other hand, if you have a fixed-size thread pool (ie some thread-pool libraries), you may find that you are using up all your threads on tasks that are just waiting on the internet. MeanwhileCPU intensive tasks are waiting for those tasks to finish (to free up a thread in the pool), while the CPU goes unused. :-(

Separate tasks by their characteristics, and use separate thread pools for separate categories of tasks.

// is there a good library out there for this?

**Comment by hsutter** [comment]
Tony, sorry for the lag, but now we have an executors proposal making progress in SG1: It seems like that would overlap with this as one use of an executor is for a collection of related tasks that share the same kind of execution, have similar characteristics, etc. Would that help cover these kinds of things? Of course, executors aren't standard yet...

The main thing is, is there a concrete guideline or three (or five) that would help guide programmers? For example, a guideline about CPU-bound tasks, or one about when to use a function vs a a task, or one about best practices for memory-bound tasks, etc.?
