### ISSUE TITLE
CP Let the Iron Triangle of Parallelism/Concurrency guide your overall approach

### ISSUE THREAD

**Issue by paulmckrcu** [isocpp/CppCoreGuidelines#555]
The Iron Triangle of Parallelism/Concurrency is the tension between these three desiderata:
- Performance (generalized to include scalability, energy efficiency, and so on)
- Generality (often proxied by the expected number of users)
- Productivity (generalized to include any number of cost metrics, including time, money, people, and so on)

Of course, everyone wants all three, but you get to pick at most two.

For example, for "hot" code paths, you might need to sacrifice productivity to achieve the required level of performance.  You might then strive for additional generality to amortize the resulting increased costs.  This is the portion of the Iron Triangle that Linux kernel developers will normally be dealing with, which does much to explain the approach they normally take.

In contrast, for an application with a small user base that has non-trivial performance requirements, you will likely need to sacrifice generality to gain the needed performance.  The small user base will usually mean that productivity is a first-order concern.  The result is often specialized algorithms using high-level programming environments.  The parallelism/concurrency will likely be either less aggressive on the one hand or banished to pre-existing libraries (or other components) on the other.

In the case where performance is sacrificed for generality, productivity, or both, you will usually avoid concurrency altogether.  After all, if single-threaded performance is sufficient, why bother with any sort of parallelism, concurrency included?  And if single-threaded performance is not sufficient, you will likely do the bare minimum to gain the needed performance.  In an increasing number of cases, this again means banishing parallelism/concurrency to pre-existing libraries or other components.

If all you care about is performance, to the point where you want performance at any price, you might well be hand-coding assembly language.

In order to make discussions on concurrency and parallelism more productive, clearly identify the corresponding point on the Iron Triangle.

**Comment by AndrewPardoe** [comment]
Paul, thanks for the discussion. Is there any part of this you could suggest as checkable rules with examples of "bad" and "good" patterns?

**Comment by paulmckrcu** [comment]
My hope is that the Iron Triangle would help determine which checkable rules apply.  For example, "Avoid concurrency" would apply most strongly in the "productivity" vertex, while rules governing aggressive application of concurrency would apply most strongly in the "performance" vertex.

**Comment by AndrewPardoe** [comment]
Per our discussion this week, we will keep this in mind. Thank you!
