### ISSUE TITLE
ES.26 "Don't use a variable for two unrelated purposes" should have an exception for caller-allocated variables

### ISSUE THREAD

**Issue by martinbis11** [isocpp/CppCoreGuidelines#557]
Regarding the rule:
### ES.26: Don't use a variable for two unrelated purposes

An exception should be added for caller-allocated variables.

See exception in "F.20: For "out" output values, prefer return values to output parameters":

> In the special case of allowing a caller to reuse an object that carries capacity (e.g., std::string, std::vector) across multiple calls to the function in an inner loop, treat it as an in/out parameter instead and pass by &. This is one use of the more generally named "caller-allocated out" pattern.

The same kind of exception should apply here.

**Comment by AndrewPardoe** [comment]
ES.26 doesn't directly address callers/callees. Consider changing the title to "Don't use a local variable for two unrelated purposes". Does that address your concern, @martinbis11?

**Comment by martinbis11** [comment]
Not exactly...  The callers/callees thing also applies to local variables.  For instance, something like:

```
std::string buffer;
for (o : objects)
{
    // First part of the work.
    generateFirstString(buffer);
    writeToFile(buffer);
    
    // Second part of the work.
    generateSecondString(buffer);
    writeToFile(buffer);
    
    // etc...
}
```

Here, we have a local variable that is used for two unrelated purposes.  In the general case, you would want something more like:

```
for (o : objects)
{
    // First part of the work.
    const std::string firstString = generateFirstString();
    writeToFile(firstString);
    
    // Second part of the work.
    const std::string secondString = generateSecondString();
    writeToFile(secondString);
    
    // etc...
}
```

or even:

```
for (o : objects)
{
    // First part of the work.
    writeToFile(generateFirstString());
    
    // Second part of the work.
    writeToFile(generateSecondString());
    
    // etc...
}
```

However, some cases might still justify using the first approach (caller-allocated variable), for performance reasons, in order to reuse the memory allocated in the string object.

So that would be an example of why using a local variable for two unrelated purposes is kind of justified by the "caller-allocated variable" way to pass parameters to/from functions.

Hope this clarifies things.

**Comment by tvaneerd** [comment]
When will compilers be smart enough to change the 2-strings into 1-string-reused for us?

**Comment by gdr-at-ms** [comment]
@martinbis11 
Is there an expression of your rules does not need to talk about callers vs. caller?

**Comment by martinbis11** [comment]
Yes, I guess the "caller-allocated" approach is only one of the examples/contexts where you want to reuse variables for different purposes to reuse memory.  For instance:

```
std::string buffer;
for (o : objects)
{
    buffer = o.name();
    buffer += " : Some other stings.";
    // Further work.
    // ...
    
    buffer.clear();
    // Some other work using buffer, for a different purpose.
    // ...
}
```

This previous example does not call functions, but reuses the string (and its memory).

So the exception to the rule "Don't use a variable for two unrelated purposes" is mostly for when you want to reuse memory (or other resources...?) held by this variable for two different purposes.  I think caller-allocated approach is worth mentioning of its own because it's basically what this approach enables, but yes the "performance exception" can also be justified without function calls, i.e. without a function with a caller-allocated parameter in its interface.

**Comment by galik** [comment]
It occurs to me to wonder, if you're dealing with a buffer, is it such a different purpose? A buffer is a buffer and its purpose is to be a buffer. If I have a `SpellChecker` is it really a *different purpose* if I spell check two different documents with the same `SpellChecker` object?

With the buffer it is not so much being used as a `variable` to *store a value* but as a *functional object* with an active purpose.

In fact there are many cases when you are going to want to create a single object and keep it around to operate on multiple data. Maybe the core of this lies in when a value stops being a *dumb variable* and starts having an active, self fulfilling,  purpose. A *buffer* is probably on the cusp of that definition somewhere between the two - leaning towards the *dumb variable*.

Maybe it is worth exploring those examples when *reusing a variable* is **decidedly bad** and possibly arrive at a less general rule that applies more specifically to such instances?

**Comment by tvaneerd** [comment]
Sounds like it is really a rule about naming variables. 

If the variable is firstName you better not reuse it for lastName. If I is instead called scratchBuffer, reuse it all you want.

**Comment by AndrewPardoe** [comment]
We can add text to the rule that clarifies that this is good hygiene, but there are cases such as desperately short stack space, where you might violate it. Violations can leak information however.

**Comment by MikeGitb** [comment]
Imho this is not only about stack space, but also about avoiding unnecessary dynamic memory allocation (as e.g. in the case of `std::string`)

**Comment by AndrewPardoe** [comment]
The simplest approach might say to not use a non-reference parameter for unrelated purposes. You do sometimes want to reuse a buffer. Could change to say that "reusing a buffer is not two unrelated purposes." But even then you have to be careful to not cause bugs from data left in a recycled buffer. 

We don't want to lose the main case that people recycle loop variables, or put large blocks of variable declarations at the top and recycle them through the function.
