### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by masterl** [isocpp/CppCoreGuidelines#567]
I recently started a YouTube channel to teach whatever I know about C++ (using C++14 !), but I'm doing the videos in portuguese since most material I looked up in portuguese were not so good.

Anyway, It would be nice to have the Core Guidelines in portuguese, so I could link people to it.
I used the search but only found an issue about Korean translation, so my question is:
- Is there a portuguese translation already or should/can I start one?

**Comment by AndrewPardoe** [comment]
@masterl, feel free to fork this and create a Portuguese version. Please let us know where it's located.

**Comment by AndrewPardoe** [comment]
For reference, the Korean translation is here: https://github.com/CppKorea/CppCoreGuidelines

**Comment by masterl** [comment]
Alright!
I just haven't thought on a way to keep the translations updated should new versions come.
But I'll do the translations, then.
Thank you. :)

**Comment by Pazns** [comment]
@masterl : 
Same problem here : https://github.com/isocpp/CppCoreGuidelines/pull/543
Without some milestones, a permanent update is necessary.

**Comment by masterl** [comment]
Well, I'll start doing the translation in my own fork.
When a solution for this is decided, I can change the files to conform to it.

**Comment by masterl** [comment]
Sorry for the long delay, unfortunately I couldn't start the translation before, I got a new job and I'm studying, but I finally managed to start it properly.
Here's the repo: https://github.com/masterl/CppCoreGuidelines_PT_BR

I decided to not make it a fork, so que repo name could have the "PT_BR" in it.
I added this repo as a submodule on git.
I copied the LICENSE too.

I'm not sure if everything is the way it should be, if anyone could verify if it conforms to the license and whatever else.

**Comment by soroshsabz** [comment]
ITNOA

For reference, the Persian translation is here: https://github.com/BSVN/CppCoreGuidelines

@cubbimew

**Comment by masterl** [comment]
@soroshsabz 
omg, why didn't I think of adding a file with the -Language suffix?

That is way better than how I'm doing.
When I have time, I'll properly fork the repo and just add a CppCoreGuidelines-PT_BR.md to it and move what I have already translated.

I also liked the way the Korean translation (linked on #1409 ) was done (separating each section into it's own file), maybe I'll use part of both ideas.
