### ISSUE TITLE
Type.4: Avoid T(expr) like you would (T)expr

### ISSUE THREAD

**Issue by LegalizeAdulthood** [isocpp/CppCoreGuidelines#569]
[Type.4](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#type4-dont-use-c-style-texpression-casts-that-would-perform-a-static_cast-downcast-const_cast-or-reinterpret_cast) mentions not to use a `(T)expr` C style cast, but doesn't mention that `T(expr)` is also a C style cast and should be avoided for the same reasons.

**Comment by AndrewPardoe** [comment]
Neil, please tidy this up.

**Comment by BjarneStroustrup** [comment]
Done, adding Type.7
