### ISSUE TITLE
I.6 The good example is bad

### ISSUE THREAD

**Issue by wrigleyster** [isocpp/CppCoreGuidelines#571]
I did have a question where this Expects object/function comes from, however shelving that question for the time being, I see how the construct is both useful and clarifies intention. The example given, however, I think ought to be changed. Currently it goes:

``` c++
int area(int height, int width)
{
    Expects(height > 0 && width > 0);            // good
    if (height <= 0 || width <= 0) my_error();   // obscure
    // ...
}
```

but surely in that example, you would want to use `unsigned` for both width and height. Thus, instead a better thing to do would be

``` c++
int area(unsigned height, unsigned width)
{
    Expects(height < SENSIBLE_MAX_HEIGHT && width < SENSIBLE_MAX_HEIGHT 0);       // good
    if (height < SENSIBLE_MAX_HEIGHT || width < SENSIBLE_MAX_WIDTH) my_error();   // obscure
    // ...
}
```

or choosing another example entirely. Choosing `int` over `unsigned` was already putting a maximum height in place, but implicitly so.

**Comment by EricTing** [comment]
In my understanding of the context, the `Expect` here is a function that may throw an exception if the argument is false.

`Expect` is recommended because it is _declarative programming_ style, and assures "Preconditions should be part of the interface rather than part of the implementation".

**Comment by AndrewPardoe** [comment]
Notes: We don't have a rule about unsigned. We've been getting a number of comments on the GSL about using unsigned as the standard uses it. We likely need a rule about overflow, wraparound, unsigned, etc.

**Comment by BjarneStroustrup** [comment]
do not use unsigned to try to ensure that values are positive. See ES.106 and ES.107
