### ISSUE TITLE
C.139 is harmful

### ISSUE THREAD

**Issue by jonathantims** [isocpp/CppCoreGuidelines#576]
The advice here is to avoid marking a class final – unless you’re sure it cannot be “improved” later.

I am from the school that believes writing base classes requires thought and is a different activity from writing a normal class (eg. C.35).

Also, for me the idea of subclassing something is very different from “improve[ing]” it.

This is a sore point for me because I’ve suffered examples in practice where people confused the two.

So I think the thrust and wording of this is all wrong.

**Comment by tvaneerd** [comment]
Particularly if we are (as we should be) encouraging Value Semantics.  Most class hierarchies aren't value types.  Should Point be final?  Should Rect derive from Point, or contain a Point?

In a weather simulation, should TempuratureReading be a class with a Point and a degreesCelius member, or should it derive from Point?  And if it does derive from Point, should the destructor be virtual "just in case"?

Point with a virtual destructor!!?

Maybe most classes are not like Point? No, when doing Value Oriented Programming, most classes actually _are_ like Point.

**Comment by AndrewPardoe** [comment]
Per our discussion, consider "refine" in the comment of the bad example?

**Comment by BjarneStroustrup** [comment]
added clarifying note
