### ISSUE TITLE
C.131 harmful as currently worded

### ISSUE THREAD

**Issue by jonathantims** [isocpp/CppCoreGuidelines#579]
I can see what this is getting (and setting?) at but I think it’s harmful as currently worded. I think it would be better to change it to “don’t use getters and setters for a class without invariants” or something like that.

**Comment by AndrewPardoe** [comment]
Could add a simple example showing that if you set one variable and update another, that it's not trivial. Or some checks on the validity of the value. A sentence saying "some cases aren't trivial" rather than changing the title. Let's not define "trivial".

Neil, please prep a PR for this.

**Comment by neilmacintosh** [comment]
I updated the note to add some more clarity around what a trivial getter/setter might "smell" like ;-)
