### ISSUE TITLE
The term "Regular Type" requires definition/description before it is used

### ISSUE THREAD

**Issue by eyalroz** [isocpp/CppCoreGuidelines#585]
I am a moderately-experienced C++ programmer - not a guru, but I pull my weight. Still, I have never before encountered the use of the term "Regular Type". The first time I stumbled upon it is in Section [C.Concrete-Types](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#a-namess-concreteacconcrete-concrete-types) of the guideline.

I believe that a very large fraction of the readership of the document will also not be familiar with this term, and that it merits either an exact definition, a rough description, or an outside link to some (stable) location discussing Regular Types. I assume the meaning is the Regular Types [discussed here](http://stackoverflow.com/q/13998945/1593077)?

**Comment by tvaneerd** [comment]
Yes, it is referring to Stepanov's Regular.
Yes, it would be nice to both define it and supply links.

**Comment by tvaneerd** [comment]
Note that it is somewhat defined in that section, but the definition is just interspersed:

"A value of regular type can be copied and the result of a copy is an independent object with the same value as the original. If a concrete type has both = and ==, a=b should result in a == b being true."

That basically _is_ the definition of Regular.

And also, as it says: That means roughly "behaves like an int." 

But the definition could be made more clear.

**Comment by eyalroz** [comment]
@tvaneerd : You do realize you can only tell that's sort-of the definition if you already _know_ the definition proper, right? :-)

**Comment by tvaneerd** [comment]
exactly.  It needs to be made more clear by proper separation.

**Comment by AndrewPardoe** [comment]
Bjarne, per our discussion, could you comment on this in the Glossary?

**Comment by BjarneStroustrup** [comment]
regular and semiregular added to the glossary
