### ISSUE TITLE
std::find use in P1 

### ISSUE THREAD

**Issue by dpantele** [isocpp/CppCoreGuidelines#59]
There is a following example in P1:
```
auto p = find(v,val);               // better
```

I can't find any mention of that even with c++17 context (although I would love to have that). Should that be replaced with
```
auto p = find(v.begin(), v.end(), val);
```
or that not a typo and intended?

**Comment by cubbimew** [comment]
It's using the Ranges TS definition

**Comment by dpantele** [comment]
Oh, ok, great!

It would be nice to have a list of TSes used there, with links to documentation, like https://ericniebler.github.io/std/wg21/D4128.html
