### ISSUE TITLE
Mention github pages in github description

### ISSUE THREAD

**Issue by tkruse** [isocpp/CppCoreGuidelines#590]
The convention on github is that when a project has github pages, these are mentioned in the description.
Here is an image of where to find the description.

![header](https://cloud.githubusercontent.com/assets/1525116/14588683/3d3b36ae-04cf-11e6-93d9-ac5f8e6db923.png)

Some examples to prove my point:
https://github.com/boostorg/thread
https://github.com/emacs-mirror/emacs
https://github.com/vim/vim
https://github.com/ruby/ruby
https://github.com/apple/swift
https://github.com/google/protobuf

**Comment by AndrewPardoe** [comment]
Done, thanks.
