### ISSUE TITLE
Need help reviewing cpplint style issues

### ISSUE THREAD

**Issue by tkruse** [isocpp/CppCoreGuidelines#592]
Hi, I have an experimental branch of this repo where I use cpplint to check all code snippets for code style errors. This works mostly fine, except for these two warnings:
```
Rh-override0.cpp:30:  "virtual" is redundant since function is already declared as "final"  [readability/inheritance] [4]
    29  struct D2 : B {
    30      virtual void f2(int) final;  // BAD; pitfall, D2::f does not override B::f
    31  };
    32


Makefile:49: recipe for target 'Rh-override0.lint' failed
make[1]: *** [Rh-override0.lint] Error 1
Rc-delete1.cpp:21:  Missing spaces around &&  [whitespace/operators] [3]
    14  // ../CppCoreGuidelines.md : 5296
    15  template <class T, class D = default_delete<T>> class unique_ptr {
    16  public:
    17      // ...
    18      constexpr unique_ptr() noexcept;
    19      explicit unique_ptr(pointer p) noexcept;
    20      // ...
    21      unique_ptr(unique_ptr&& u) noexcept;   // move constructor
    22      // ...
    23      unique_ptr(const unique_ptr&) = delete; // disable copy from lvalue
    24      // ...
    25  };
```

Can someone tell me whether those are a likely cpplint bug, or whether the code is not sytactically correct in the two samples?

Is there any other recommended free linux-compatible style checker I could try integrating?

**Comment by gs93** [comment]
The first one isn't an error: To mark a function as final it needs to be virtual or else the compiler will produce an error and that's the reason why this is a bad example. The second warning looks like an error (google/styleguide#61).

**Comment by tkruse** [comment]
thx!
