### ISSUE TITLE
R.37, R.30, F.7 and template functions

### ISSUE THREAD

**Issue by duneroadrunner** [isocpp/CppCoreGuidelines#602]
Consider the issue of "function parameter lifetimes" addressed in [Herb's CppCon 2015 talk](https://www.youtube.com/watch?v=hEx5DNLWGgA) (59 minutes in). That is, the possibility that a reference parameter could be deallocated before the function is finished using it. So it seems that the static analyzer can, in a lot of situations, verify that the parameters will not be deallocated. But what about the cases where it can't? Well, to the extent that these guidelines address that situation, they essentially put the onus on the caller to somehow change the situation so that it becomes more obvious that the referenced parameters will not be deallocated. Specifically, in the case of obviously aliased shared_ptrs ("R.37: Do not pass a pointer or reference obtained from an aliased smart pointer"), the guideline instructs the programmer to grab a copy of the shared_ptr before passing the object by "dumb"/raw reference.

This is not an adequate solution for several reasons. First, guideline R.37 doesn't identify or give any guidance/solutions for situations other than the "obviously aliased shared_ptr" case. And that's not by accident. "Do not pass a pointer or reference obtained from an aliased smart pointer" is a rather pithy imperative that fails to acknowledge the fundamentally difficult problem involved. For non-trivial definitions of "aliased", just identifying whether or not a smart pointer is actually aliased can be difficult. And even the given solution for the obviously aliased shared_ptr case, while effective, is kind of unnatural because the solution is to make a copy of a pointer and do absolutely nothing with that copy.

In general, if you see some code that makes a copy of an object, and does absolutely nothing with that copy, you would expect a compiler warning about "an unused variable" or the like. And if you stumbled across such code, you might assume that it would be inconsequential to eliminate the redundant copy. But now the guidelines are breaking this traditional semantic. So now, if we see some code like this

```
{
    auto i2 = i;
    f(i);
}
```

we now have to assume that `i2` is a vital part of the code and can't even consider the possibility that it might just be redundant left-over code. If it so happens to be redundant left-over code, well, now it's permanent because in order to justify removing it you'd have to set up a commission to thoroughly investigate `i2`'s inner machinations for the possibility that its mere existence is vital to some other part of the code.

There is a better solution to this "function parameter lifetimes" problem. But first we first need to address a controversial point.

Consider "F.7: For general use, take T\* or T& arguments rather than smart pointers". Now, even if there is agreement on the rule (which there isn't), there are different interpretations as to why the rule is a good one. You could take the position that a function doesn't need (even shared) ownership of an object to use it, so it can use a non-owning reference (like T\* or T&) to access the object. Or, alternatively, you could take the position that any direct access of an object requires (at least temporary shared) ownership of the object, and that T\* and T& can be considered "highly optimized" owning references that can be used under certain conditions. Note that you can't access an object directly through, for example, a (non-owning) std::weak_ptr.

The former interpretation is wrong. The latter one is more correct. Both interpretations allow you to use T\* or T& for reference arguments in most cases. 

So I'm directly challenging the implication of "R.30: Take smart pointers as parameters only to explicitly express lifetime semantics" here. Any direct access to an object requires (at least temporary shared) ownership of the object, so all functions that are planning to actually access their reference arguments need to do so through owning references, even if those owning references happen to be "highly optimized" ones like T\* or T& (that can be safely used under certain conditions).

R.30 explains its motivation. If your function declares its reference argument to be a specific owning pointer/reference type, it would impose an undesirable restriction on those using the function. But there are (at least) two ways of alleviating that restriction. One is to use the very fast and very standard (but sometimes unsafe) T\* or T& (owning) reference type. Note that this doesn't actually "remove" the restriction, it just trades it in for a more familiar and preferred restriction. Another way is to "templatize" your function so that it can accept any pointer type, smart or otherwise. Note that this actually does remove the restriction.

Ok, some of you are saying "Ewwwww, function templates are gross." So first of all, you don't have to templatize all your functions. Just the ones intended for general use. And second, you only think they're gross because you haven't tried them. Once you start templatizing your functions you quickly realize that it makes more sense and you'll even be tempted to templatize all your function parameters, not just the reference ones. First let's acknowledge that no one consciously decided that mandatory explicit declaration of function parameter types was better than (optionally) unrestricted parameter types. We just inherited the former from C and never questioned it.

But think about all the template functions in the STL (e.g. std::sort()). At the time of authorship, those functions couldn't care less what kind of parameters you intend to give them. If you end up trying to give them parameters that are fundamentally incompatible with the function, then the function just won't compile. Otherwise, they'll take whatever parameters float your boat. So why shouldn't that policy apply to most functions (intended for general use)?

From a safety point of view, if you commit to a specific parameter type at the time of a function's authoring, then you are imposing a (perpetual) ceiling on the safety features of the parameter. Even, for example, if you declare an int parameter. What if in the future someone wants to use your function in a safety critical application that uses custom integer types that have range checked arithmetic operations? If you had declared your function to accept any type of integer (or whatever), then your function would automatically inherit the intrinsic safety of the given integer type. But if you declared it to only accept "int"s, then your function will remain intrinsically unsafe and probably not suitable to be used in that hypothetical future application.

Or, for example, you might imagine a smart pointer that keeps track of the number of, or perhaps timing of, it's dereferences for debug, or maybe security purposes.

All I'm saying is that we should recognize that we inherited an intrinsic inflexibility in the way we declare function parameters. At the time, there was no alternative. Today we have a choice whether or not to perpetuate this inflexibility. If we're gonna do it, do we not have an obligation to justify doing so?

And back to the original point, template functions properly (and efficiently) address the "function parameter lifetimes" problem (in a way that R.37 does not). If you're in a situation where you (or the static analyzer) happen to know that passing a raw pointer is safe, then you can go ahead and do so. On the other hand, if you (or the static analyzer) aren't so sure, then pass a proper "owning" smart pointer. So everyone's happy. :)

Right? Or am I somehow being delusional here?

Noah

**Comment by AndrewPardoe** [comment]
We thank you for the discussion.
