### ISSUE TITLE
comparing with an alternative set of guidelines and support library

### ISSUE THREAD

**Issue by duneroadrunner** [isocpp/CppCoreGuidelines#604]
[This article](http://www.codeproject.com/Articles/1093894/How-To-Safely-Pass-Parameters-By-Reference-in-Cplu) (I wrote) describes a coding style with the primary aim of duplicating the memory safety of garbage collected languages without resorting to garbage collection. While the priorities may be different from those of these core guidelines (safety vs performance vs convenience), I think it might be instructive to compare approaches.

The goal of this "SaferCPlusPlus" coding style (or "[semantically enhanced library language](http://www.stroustrup.com/SELLrationale.pdf)" as Bjarne calls it) is zero chance of invalid (or uninitialized) memory access. Noting that garbage collected languages already achieve this at a reasonable performance cost, the approach taken was to basically emulate garbage collection through reference counting pointers. This is an old and common idea, but it seems that no one has gone all the way with it. At least not since the advent of C++11, which makes the idea a lot more practical.

First thing to note is that std::shared_ptr is too expensive for ubiquitous use. Easy to fix, since std::shared_ptr's thread safety is unnecessary in most situations, SaferCPlusPlus just introduces a [more efficient reference counting pointer](http://duneroadrunner.github.io/SaferCPlusPlus/#reference-counting-pointers). And as a bonus from a memory safety point of view, it doesn't support construction or assignment from (user supplied) raw pointers, and it comes in a "not null" flavor that guarantees "not null"ness with zero runtime cost.

So this brings up an issue with these guidelines. Take, for example, guideline "F.27: Use a shared_ptr<T> to share ownership". If you standardize on an unnecessarily expensive reference counting pointer implementation, you unnecessarily discourage its use. Should we not consider introducing a more efficient one in the gsl for situations when thread safety is not a requirement? And imo, these guidelines should be strongly discouraging the "casual" sharing of objects between asynchronous threads. It's a more dangerous practice than any alluded to in the guidelines.

I realize that it is not the purpose of the gsl to compete with the existing standard library. But these guidelines are meant for new code. As Bjarne said iirc, "Imagine what you want your code to look like five or ten years from now." Do you want your code to be littered with unnecessarily costly std::shared_ptrs, with some scattered runtime checks for "nullness"? And probably mixed with the occasional non-standard reference counting pointer implementation in performance critical code where it's clear that std::shared_ptrs are just too expensive?

These guidelines currently advocate universal dependence on an already aging smart pointer that was probably never intended for this kind of common use. They could instead identify, as the article describes, a more flexible, efficient and modern coding style, with which C++ does not take a back seat to any language in terms of code safety or performance.

And let me just point out that the standard library's (reasonable but) peculiar implementations of "shared" and "unique" pointers have resulted in a widespread misconception that (properly implemented) "shared" pointers are intrinsically slower than "unique" pointers. Properly implemented "shared" pointers should have a cheap reference counting mechanism simple enough that most increment-decrement pairs could be discarded by optimizing compilers. Properly implemented "unique" pointers, on the other hand, would require that each dereference check whether or not the pointer is actually still valid. And these guidelines currently perpetuate this problematic misconception.

When asked why the gsl was not made part of the standard library, or boost library, Bjarne said that he didn't want to wait that long. He wanted a way to improve C++ code right now. Well, I don't know what the state of these guidelines or the gsl is - based on the traffic in this issue board, it looks like the project might have been abandoned. On the other hand, the SaferCPlusPlus library and guidelines, while not totally complete, are available and usable right now.

The SaferCPlusPlus coding style is new, but it seems to effectively accomplish the goal of memory safety with only modest performance penalty. It may be a little verbose, but it is compatible with the traditional (unsafe) coding style and does not conflict with traditional C++ coding principles. It does, however, conflict with a lot of the new directives introduced in these guidelines. In particular with respect to smart pointers and function parameters. I think that's an indication of problems with these guidelines.

So, this post is not just an advertisement for SaferCPlusPlus. I'm presenting SaferCPlusPlus as a legitimate, effective, modern coding style (maybe with niche priorities) for a) comparison of approach, and b) compatibility considerations.

Or if this this project really is abandoned, then maybe as a practical replacement.

Noah

**Comment by cubbimew** [comment]
> the approach taken was to basically emulate garbage collection through reference counting pointers [...]  So this brings up an issue with these guidelines. Take, for example, guideline "F.27: Use a shared_ptr to share ownership"

To avoid such misunderstanding, perhaps F.27 could be strengthened to also say "do not use shared_ptr to emulate garbage collection"

**Comment by duneroadrunner** [comment]
Yeah, I also have problems with other recommended uses of std::shared_ptr. Enough to open [another issue](https://github.com/isocpp/CppCoreGuidelines/issues/606) about it.

**Comment by AndrewPardoe** [comment]
@cubbimew, we discussed this but disagree with your suggestion. We don't want to mix the idea of `shared_ptr` with garbage collection, which is not a well-defined concept. Thank you for a good discussion however!
