### ISSUE TITLE
R.3: A raw pointer (a T*) is non-owning -- typos regarding owner

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#609]
The third example (just before Exceptions) reads:

<pre>
    template<typename T>
    class X2 {
        // ...
    public:
        <b>owner&ltT&gt p </b>;   // OK: p is owning
        T* q;         // OK: q is not owning
    };
</pre>

Shouldn't there be an asterisk with the T to make it an pointer? **owner\<T*\> p**;

In this section there are a number of places in the text where **owner\<T\>** is given without the asterisk.  For example in **Note**.  For consistency, shouldn't the asterisk be considered a part of the owner notation?  So the two cases in **Note** should be changed to read **owner\<T*\>**.

For a moment, this section made me think that the asterisk was a part of the template definition in the GSL.  Which is not the case.

If this seems reasonable, I am willing to make the pull request and submit the fix

**Comment by MikeGitb** [comment]
I agree that this is confusing and should be fixed at least for the cases, where T* and owner<T> occur next to each other. In particular, as raw pointer types are - I believe - currently the only standard types for which owner is meaningful (contrary to notnull)

**Comment by tlanc007** [comment]
So in this case, only the owner in the code block should be changed and leave the two instances in the **Note** section as they are?

**Comment by MikeGitb** [comment]
Sorry, if I wasn't clear: No, I think all instances of `owner<T>` should be changed to `owner<T*>`. 

Altough I'm not 100% sure that owner is actually limited to raw pointer types, I can't think of a different type for which it would make sense right now.

**Comment by tlanc007** [comment]
A patch has been submitted and merged.  Closing this out.
