### ISSUE TITLE
C.33 If a class has an owning pointer member: inconsistency in the example

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#610]
The example just before **Note** has to me a slight inconsistency:

<pre>
    template<typename T>
    class Smart_ptr3 {
        <b>owner&ltT&gt* p; </b>  // OK: explicit about ownership of *p
        // ...
    public:
        // ...
        // ... copy and move operations ...
        ~Smart_ptr3() { delete p; }
    };
</pre>

Although this is legal.  Wouldn't it be better, if the usage was kept consistent and the asterisk was moved inside the brackets?

**owner<T*> p;**

Also the end of this section, under **Enforcement** owner<T> is referred to without an asterisk.  For clarity, shouldn't owner always be referred to with a type followed by an asterisk, **owner<T*>**?

I am willing to submit a fix, if desired.

**Comment by tlanc007** [comment]
Submitted a patch for review.  Only changed the code example part.  

I left the owner<T> alone in the **Enforcement** section.  The whole document uses this style in the text.  So assuming this is the intended style for now.

**Comment by AndrewPardoe** [comment]
Thank you! We have merged PR #613. Thanks for isolating your PR to the parts you were certain about.

**Comment by AndrewPardoe** [comment]
Cleaning up and closing. Thanks again!
