### ISSUE TITLE
Do we need guidance or preferred style for definitions using span<>?

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#614]
There appear to be a number of ways **span<>** can be used in definitions:

```
constexpr size_t Size {5};

int c_array[] = {0, 2, 4, 6, 8};
gsl::span <int> c_span1 {c_array};
gsl::span <int, Size> c_span2 {c_array};
gsl::span <int> c_span3 {c_array, Size};
std::cout << "sp1 size: " << c_span1.size()
    << " sp2 size: " << c_span2.size()
    << " sp3 size: " << c_span3.size() << '\n';
```

<pre>
sp1 size: 5 sp2 size: 5 sp3 size: 5
</pre>

However, the third form doesn't work if std::array is the source.  (At least it doesn't compile under clang++ OSX)  Which is why I had to comment the third form out:

```
std::array <int, Size> nums = {1, 2, 3, 4, 5};
gsl::span <int> n_span1 {nums};
gsl::span <int, Size> n_span2 {nums};
//gsl::span <int> n_span3 {nums, Size};
std::cout << "sp1 size: " << n_span1.size()
    << " sp2 size: " << n_span2.size()
    /*<< " sp3 size: " << n_span3.size()*/ << '\n';
```

<pre>
sp1 size: 5 sp2 size: 5
</pre>

With the third form failing for std::arrays, is that an issue with the GSL?  Or should the second form, `span<T, size_t>` be considered more robust and so the more preferred choice?

**Comment by MikeGitb** [comment]
I think there has to be much more documentation, specification and usage guidelines of the guideline support library in general (and I believe the mainteiners are working on it - see issue #144).

As far as this particular issu is concerned, imho none of those forms should be used to create a span over all elements of a container or array. The third version (construction from a pointer + length) is by far the worst, as the constructor has no way of checking, whether the length is correct. In fact, it is exactly the kind of error prone interface `gsl::span` was designed to replace. The only reason it exists is for interfacing with legacy code and incremental adoption. 

The second version does ensure that the span is not longer than the underlying array, but you still have to repeat the type and the length unnecessarily. The first version will always produce a span of the correct (runtime) length, but you still have specify the underlying type and you are prematurely throwing away compile time information. So unless you want to be explicit about the type of the span (element type, compile time / runtime bounds) I'd rather use: 
```auto n_span = gsl::as_span(nums);```

which works correctly for any array or container type and exhibits the least redundancy. 

And if you want to create a span over a subrange:

```
auto n_span = gsl::as_pan(nums).subspan(...);  //runtime length    
auto n_span = gsl::as_pan(nums).subspan<...>(); //compiletime length
```

**Comment by tlanc007** [comment]
Thanks for the pointer to #144. I agree with your reply completely.  After mulling over the GSL, it seems much of its purpose is for helping out with legacy or ABI compliant code.

And thanks for pointing out **gsl::as_span()**.  I missed that one completely.  Before, if I had a need for span, I would have leaned towards the first form.  But yours is even better.

The third form of **span**, was something I noticed in the guidelines.  I'll create an issue for it and submit a patch.

**Comment by neilmacintosh** [comment]
@tlanc007 the purpose of the GSL is not solely to help out with legacy or ABI code...though it's design does include the pieces necessary to carry out that important task.

Even within a brand-new, C++ program written today, we would advocate for use of the GSL, as it contains basic vocabulary types key to writing good programs.

Consider `span<T>`, this is a view over a contiguous sequence of objects that is decoupled from the details of their underlying storage. That concept seems perfectly useful both when writing brand new C++17 code and when interfacing to legacy code.

@MikeGitb Note that `as_span()` is not part of the standardization proposal for `span<T>` at this time. The proposal can be found at: http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0122r1.pdf. 

Also, we have dropped the array+length ctors from `span<T>`. You can either initialize an array (whether built-in or std::array) either directly using the ctor that deduces the length, or by passing the address to the first element and a size (the ptr+length ctor).

The GSL implementation will be updated to match the standardization proposal very soon.

**Comment by tlanc007** [comment]
@neilmacintosh -- Thanks for the reply.  I was taking a bit of limited view of spans and was thinking they were a nice way of dealing with C-style arrays. But viewing them as a way of dealing with all consecutive sequences does make them a bit more interesting.

A bit off topic, but what about some of the string-like items in the gsl,  (ie. zstring),  is the expectation that if code doesn't need all of the std::string features that `gsl::zstring` is a perfectly acceptable style?  Or is `std::string` still the preferred string type and the gsl forms are primarily for dealing with legacy and ABI concerns?

**Comment by neilmacintosh** [comment]
@tlanc007 Well `gsl::zstring` is just a useful typedef for a `char*`, that signifies to readers and tooling that you expect that `char*` to be a null-terminated string. That type happens to be one of the GSL types that truly does exist for legacy interop purposes.

However, `string_span` (formerly `string_view`) is to `std::string` as `span` is to `std::array`. A `string_span` is a view of a string (a sequence of characters) abstracted from notions of termination or specific storage details.  A `std::string` or a `CString` or a `QtString` or an array of chars...these are all specific string containers. 

So if you were writing a function that needs to read a string as its input, I would recommend using a `cstring_span` as first choice. It requires the least of clients (i.e. is most accepting at callsites), describes just what you need to access the string data and does not couple your function to a choice of string storage.

**Comment by AndrewPardoe** [comment]
Closing based on @neilmacintosh's comments. I believe this is handled.
