### ISSUE TITLE
F.6 constexpr functions can throw

### ISSUE THREAD

**Issue by MikeGitb** [isocpp/CppCoreGuidelines#616]
A note in F.6 (If your function may not throw, declare it noexcept) says:

> **Note**
> constexpr functions cannot throw, so you don't need to use noexcept for those.

Which is - to the best of my knowledge - simply not true (of course they can only throw when they are evaluated during runtime and not compiletime). Should this sentence just be removed or - if that is a common misconception - replaced it with a note explicitly mentioning this possibility?

**Comment by cubbimew** [comment]
Since it found its way here, it appears to be a common enough misconception. This was even an NB comment on C++11  [CWG issue 1129](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1129)

**Comment by MikeGitb** [comment]
F.6 Still contains this note which is plain wrong. Is there a specific reason why this wasn't fixed or is it just a matter of not having enough time to fix every reported bug? Just deleting those two lines would be enough for now.

**Comment by BjarneStroustrup** [comment]
Fixad

**Comment by MikeGitb** [comment]
Thank you.
