### ISSUE TITLE
CP.2 suggestion for alternate form for span in example

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#617]
In **CP.2: Avoid data races**, the form of **span** used in the 2nd example, may give readers this is the preferred form:

```
void f(fstream&  fs, regex pat)
 {
      array<double, max> buf;
      //...
      gsl::span<double> s {buf, max};
      //...
 }
```

Here are two alternatives that should be better:

```
gsl::span<double> s {buf}

auto s {gsl::as_span(buf)}
```

I will submit a patch using the second form.

**Comment by AndrewPardoe** [comment]
Thanks! Closing the issue on cleanup.
