### ISSUE TITLE
A concern regarding the possibility of __restrict__'ing spans

### ISSUE THREAD

**Issue by eyalroz** [isocpp/CppCoreGuidelines#623]
Making my question [here](http://stackoverflow.com/questions/37521437/avoiding-loss-of-restrict-when-using-gsl-spans) into a concern for guidelines authors:

Without span's, I would declare:
```
void foo(int* __restrict__ p, size_t len);```

But if I now declare:
```
void foo(gsl::span<int> s);
```

I don't get the `__restrict__` effect unless my compiler super-smart. Now, I know `__restrict__` is not part of C++. However, it can be important for optimization, so there's reason to take it into account.. So please mind this issue and consider addressing it explictly.

**Comment by grahamreeds** [comment]
Personally I think no.  While `restrict` is a keyword of C, it isn't part of C++ (hence the `__`).  If we start adding support for popular, but non-standard, extensions then why one and not another?

Also this is about the Core Guidelines, your question seems to be about the GSL which is located [here](https://github.com/Microsoft/GSL).

Once `restrict` appears in C++ then the Guidelines can be updated.  However there wasn't a proposal in 2011 and so wasn't considered.  There are restrict-like semantics proposed in papers up to [n4150 ](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4150.pdf) but I don't think it has been voted in.

**Comment by eyalroz** [comment]
I did not suggest the guidelines directly "support" or rely on keywords that are not part of C++; I am merely indicating that it is problematic to recommend a certain idiom or idiomatic construct be used, if its use hinders a very popular and important optimization extension - which, as you suggest, is likely to make its way in some form into the language in the future.

Also, I have no issue with one specific GSL implementation or another (and Microsoft's is not the only one) - it's a more general concern. I would like the editors to consider it, discuss it, and reach a thoughtful conclusion about it. I don't have a specific suggestion I would put forward myself.

**Comment by gdr-at-ms** [comment]
The C++ Core Guidelines are for good programming with standard C++. We are aware of gazillions "popular" extensions, and the recommendations we put forward are the result of thoughtful considerations.

**Comment by fwyzard** [comment]
> The C++ Core Guidelines are for good programming with standard C++. We are aware of gazillions "popular" extensions, and the recommendations we put forward are the result of thoughtful considerations.

Nice way of saying "we don't care about your use case".

**Comment by eyalroz** [comment]
> The C++ Core Guidelines are for good programming with standard C++. 

No, no it is not. As stated at the beginning of the introduction,

> This document is a set of guidelines for using C++ well. 

And using `__restrict__` in supporting compilers is part of using C++ well, even if is not standardized.
