### ISSUE TITLE
F.21: prefer returning tuple or struct

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#627]
For the most part, i can agree with this Guideline.  

However, there is one area that I haven't been able to reconcile.  That case is when the intent is to use the call as loop control condition.  In such a case, the function should be viewed foremost as a boolean function, but with side-effects. Would this be considered a reasonable exception for this Guideline? 

Take for example `std::getline()` a common usage is:

    std::string line {};
    while (std::getline (line) ) { /* do stuff */ }

Short, nice, and to the point.

Looking at the following example, the first function is following the same pattern as std::getline() while the second function tries to follow this Guideline:

    bool test1 (std::string& other_result) {
            other_result = "";
            return false;
     }

    using MultiReturn = std::tuple <std::string, bool>;

    MultiReturn test2 () {
        return std::make_tuple ("", false);
    }

    int main () {
        std::string my_str {};
        while (test1 (my_str) ) { /* do stuff */}

        bool my_cond {false};
        while ( (tie (my_str, my_cond) = test2 (), true) && my_cond) { /* do stuff */ }

        // alternate while form to avoid the awkward always true test in the left operand
        do {
            tie (my_str, my_cond) = test2 ();
            if (!my_cond)
                break;
            // do stuff
        } while (1);
    }

To me, the code resulting from the `std::getline()` pattern is cleaner.

**Comment by MikeGitb** [comment]
I'm inclined to agree. In theory this can be solved by using `std::optional` as a return type. In practice, passing a buffer by reference might often be more efficient, as it e.g. avoids repeated dynamic memory allocations.

**Comment by cubbimew** [comment]
The case of passing a buffer by reference to reduce allocations (thereby making it an in/out parameter) is already discussed in F.21 (and is lacking an example).

I think the cases where returning `pair<result, bool>` makes sense today will be replaced by returning `optional<result>`. Given that it is already part of C++17 and one of the original goals for these guidelines was C++ the way you want to write several years in the future, a guideline on returning `optional<T>` should probably be introduced to the F section (there are some cute idioms coming with that too, `while(auto x = f()) { stuff }`, but I dunno how editors feel about those)

**Comment by galik** [comment]
I agree that for repeated values its more efficient to reuse the variable, especially when re-allocations are involved like with a string. I also like the `while(auto = f()) {}` idiom as it removes cruft (unused variables) from the wider scope. To that end it may be worth consifering using a `for()` rather than a `while()`:
```cpp
for(std::string line; std::getline(in, line);)
{
    // stuff
}

// no cruft here, line is only in the scope of the `for()`
```

**Comment by tlanc007** [comment]
@galik except the `for` loop example violates [ES.73](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-while-for)

**Comment by galik** [comment]
@tlanc007 Its a fair cop. I still think there is value in using the `for` to keep the string local rather than pollute the wider scope.

**Comment by MikeGitb** [comment]
If you want to go all the way, it is relatively simple to write a wrapper class, which makes `std::getline` compatible to a rang-for loop (`for (std::string& line : lines(in))`), but to be honest, I think the for loop as shown by @galik strikes the best balance between simplicity, overhead and readability.

**Comment by BjarneStroustrup** [comment]
clarification and example added
