### ISSUE TITLE
Proletarianization

### ISSUE THREAD

**Issue by joeedh** [isocpp/CppCoreGuidelines#628]
This should be an obvious point, but we programmers never seem to connect the dots: proletarianizing your workforce in order to protect against technical incompetence is self-defeating.  If you formulate professional guidelines from the premise that programmers are intrinsically stupid, you will end up with a great many stupid programmers.  It becomes a self-fulfilling prophecy.

**Comment by grahamreeds** [comment]
So are you for or against the guidelines? 

Generally programmers aren't dumb.  Naive at the start but not dumb. The guidelines say a lot of times: "Don't do this, it is dumb" and hopefully a few of these programmers will take on board the change and pass that information along to colleagues in code reviews, etc.

I do feel that the guidelines are getting to unwieldy. When it got announced I was expecting a "50 ways to improve your existing c++ code".  With at least a couple of hundred points now, no one is going to read them all except the authors who wrote them and they aren't the target audience.  It took me a long time to get past the first 6 chapters on ```auto``` in Effective Modern C++ and there are only 42 items in there.

GR

**Comment by Redchards** [comment]
I agree with Graham about programmer being more naives than dumb. Especially with a language as convoluted as C++, making mistakes or falling into pitfalls has close to nothing to do with stupidity.

Moreover, to me the guidelines were written with the firm intention to help static analysis, which is not "fool proof", but can save us some trouble every now and then when C++ decide to bite. Again, making mistakes in C++ (or any other langage) has nothing to do with being stupid, but can be very punishing when not warned about, especially in the cases where the error is silent and will come back to make a debugging hell one day.

For an example of static analyzer based on those guidelines, there is the CppCoreCheck from microsoft. It works very nicely, albeit being still in early stage.

**Comment by gdr-at-ms** [comment]
Thanks for the feedback.

**Comment by joeedh** [comment]
@Redchards: "Again, making mistakes in C++ (or any other language) has nothing to do with being stupid, but can be very punishing when not warned about"

I disagree.  It's better to learn these lessons for yourself; programmers are far too superstitious to be trusted to give good advice (this may be a consequence of conflicts of interest in the software consulting industry).  The fear mongering surrounding memory management is a case in point, as is the encapsulation mania (though admittedly this is less damaging in C++ since it can inline accessors).

Too many of these rules are based on fear.  Some programmer somewhere had a bad experience, and decided the solution was to blunt his tools lest he cut himself with them.  He then discovers that the more stridently paranoid he is, the more money people will pay him for consulting and speaking fees.

**Comment by Pazns** [comment]
@joeedh : 
We could add a rule "Meta.1: Read the CppCoreGuidelines, you uncivilized monkey.", but it can be self-enforced only by those who read it. :)

We can't do much about it if mad programmers don't want to apply the guidelines.
See it more as a treaty between programmers who care about it than an international law upon programming criminals.

**Comment by joeedh** [comment]
@Pazns, I thought the whole point was to make everyone follow (at least some subset of) these rules.  I don't even work in C++ at the moment, but I'm still learning the rules in case a future employer requires I use them.

Frankly I find CppCoreGuidelines off-putting.  Most of them (by no means all) are the same sort of superstitious crap all of us have had to deal with for years.  I think its important for us more experienced developers speak up, since this sort of thing kills productivity.

**Comment by Pazns** [comment]
Superstitious crap ? That's something.
If you think a specific guideline is this much useless or harmful, feel free to open a ticket about it.
We all would be pleased :-)
