### ISSUE TITLE
C.4 Rule Refinement

### ISSUE THREAD

**Issue by d-winsor** [isocpp/CppCoreGuidelines#633]
I agree with the idea of using non-member when possible to reduce coupling and improve maintainability but I feel the rule is too restrictive and could be harmful if implemented by tooling.

Although it is somewhat obvious the rule doesn't seem to clearly state what is needed to justify use of a member function. Instead of saying they must depend on data members it should make clear it means only private/protected members. Something like:
"Look for member functions that only access the public data/function members of a class."

Some considerations where this rule would be obtrusive are:
- Overloaded functions that redirect to another function. 

```
DoWork(int x)    {...}
DoWork(double x) { DoWork(math.round(x)); }
```
- Functions that depend on the implicit 'this' to allow patterns such as the following which would otherwise be excessively verbose: 

```
obj.Function(param1).Function(parm2);
```
- Virtual methods because particular derivations may need not access its class state.

**Comment by BjarneStroustrup** [comment]
Thanks
