### ISSUE TITLE
SF.4: Include .h files before other declarations in a file

### ISSUE THREAD

**Issue by lorros** [isocpp/CppCoreGuidelines#634]
If your headers contain a lot of inline code (e.g., you're developing a header-only templated library) and implementations might use other headers that are not needed on the interface, I think it's wise to have a separate header for declarations and for definitions. In this case, your main.cpp (or any other .cpp) would include the declarations first, but it might be wise include the implementations at the end. This way, you'll avoid the effect of headers of definitions and be less coupled with the library. What do you think?
A common example is a memoize template that, given a functor, can be used as a drop-in replacement for that functor, but caches the calculation result and returns the cached value when it can. Implementation might depend on a lot of libraries, including std::map<> / std::vector<>, mutex, potentially hash algorithm(s), timers and threads to release unused values; whereas the declaration only exposes a single template with no details about the implementation.

**Comment by vcato** [comment]
Imagine that you have a complex class template that your application uses in many translation units, but the template parameters are always the same (huge_template<int>).  An application could choose to use huge_template_decl.hpp in all source files except one and then explicitly instantiate huge_template<int> in just one source file:

```
// huge_template_int.hpp
#include <huge_template_decl.hpp>
extern template huge_template<int>;

// huge_template_int.cpp
#include <huge_template_int.hpp>
#include <huge_template.hpp>

template huge_template<int>;
```

This might cause a big savings in compilation time.

**Comment by lorros** [comment]
I see your point on compilation time, but - to my knowledge - extern template is non-standard.
Also, I understand that any cpp of the same hpp will naturally include the hpp's on top; what I'm trying to say that main.cpp (+ other libs) might include decl-like headers, including your extern, on top, compile your cpp's as you'd do normally, but have any remaining (i.e., non-cpp'ed) templates / inlines included on bottom. I'm not saying it's obligatory, I'm just saying it's a use case where an `#include` is not on top.

**Comment by vcato** [comment]
Yes, my comment was a bit tangential.

As far as your suggestion, I'm having trouble understanding how including at the bottom helps.  Can you give a concrete example?

**Comment by lorros** [comment]
I'm thinking of this use-case: https://ideone.com/oAs8Go .

**Comment by vcato** [comment]
I see the advantage of breaking up the decl and impl files, but I'm not sure I see the advantage of including the impl file at the bottom versus at the top.   This seems to work okay as well:

```
#include <iostream>
 
#include "memoized_decl.h"
#include "memoized_impl.h"
 
// main.cpp, notice that map, mutex, utility are not included here.
int f(const int i)
{       
    std::cout << "calc...";       
    return i * 2;
}

int main() { 
    std::cout << memoized<f>(1) << " ";
    std::cout << memoized<f>(1) << " ";
    std::cout << memoized<f>(2) << " ";
    std::cout << memoized<f>(2) << " ";
    std::cout << memoized<f>(3) << " ";
    std::cout << memoized<f>(3) << " ";
}

```

**Comment by lorros** [comment]
True, it works. However, now your main function is aware of implementation details like <map>, <mutex>, <utility>. You might not want to expose this there, as the typical user will then 'forget' to include these. This is not a big issue (well, it is, but...) as long as it's the standard library - but what happens when they suddenly start to depend on an implementation choice (i.e., the company has several implementations of one of the classes used by _impl.h, all of them being drop-in replacements.
The drawback? Any using namespace in main will affect _impl.h. (One of the reasons why I'd like to see a version of using namespace with scope, i.e., {}).

**Comment by BjarneStroustrup** [comment]
No change in recommendation, but I added a brief comment.
