### ISSUE TITLE
Address use of prefix or postfix "const"

### ISSUE THREAD

**Issue by alex-weej** [isocpp/CppCoreGuidelines#637]
e.g. `char const * const` vs. `const char * const`. Personally I prefer postfix const for uniformity in parsing (always applies to the left) and code layout (the actual type of a variable stays in the same place regardless of whether it is const).

**Comment by BjarneStroustrup** [comment]
I added such as rule. NL.26. However, it gives the opposite recommendation to the one suggested.

**Comment by alex-weej** [comment]
I don't see it in master - do you have a commit ID? Thanks

**Comment by BjarneStroustrup** [comment]
not yet
