### ISSUE TITLE
passing predefined expressions (__PRETTY_FUNCTION__) as parameter

### ISSUE THREAD

**Issue by ericLemanissier** [isocpp/CppCoreGuidelines#640]
Passing the predefined expressions __PRETTY_FUNCTION__, __func__ or __FUNCTION__ as a parameter is a very common case of logging function, for example

void logImpl(const char *message, const char *fun);
#define logMessage(message) logImpl((message), __PRETTY_FUNCTION__)

__PRETTY_FUNCTION__, __func__ or __FUNCTION__  are implicitly declared by the compiler as const char arrays, so such code is flagged at each call site by I.13: Do not pass an array as a single pointer.
It feels like there should not be a problem decaying these to pointer, because they are generated. Couldn't they be added to the exceptions (zstring/czstring) ?

Speaking of this, I find quite unclear the sentence "Use zstring and czstring to represent a C-style, zero-terminated strings. But when doing so, use string_span from the GSL to prevent range errors". Does it mean that such variables should be declared as (c)zstring, but passed to function as string_span ? Does it mean the other way ? Does it mean anything else ?

Thanks

**Comment by gdr-at-ms** [comment]
The better practice is to have `logImpl` express the intended design in its interface.

**Comment by KrisTC** [comment]
We have similar patterns, I belive the correct thing to do here is use `gsl::cstring_span`.

I have tested the following in VS2015 and it works perfectly and adds the nice compile time safety of GSL.

```c++
void logImpl(gsl::cstring_span<> message, gsl::cstring_span<> fun) {
    std::cout << "Message Len: " << message.length() << " in: \"" << message.data() << "\"" << std::endl;
    std::cout << "Function Len: " << fun.length() << " in: \"" << fun.data() << "\"" << std::endl;
}
#define logMessage(message) logImpl((message), __FUNCTION__)
```

And then use of it:
```c++
logMessage("This is is a string constant");
```

And the console output:
```
Message Len: 28 in: "This is is a string constant"
Function Len: 5 in: "wmain"
```

**Comment by ericLemanissier** [comment]
Thanks for the information. 
It has to be noted that you chose to incur the cost of strlen (in cstring_span constructor) for each call to logMessage, and also that you take the risk that someone passes a cstring_span referring to a non null terminated string as second argument to logImpl, which in term cause read ouf of bounds in cout<<fun.data().

C++ Core guidelines advises the use of czstring_span in this case, so I think the best would be
```c++
void logImpl(gsl::czstring_span<> message, gsl::czstring_span<> fun) {
    std::cout << "Message: \"" << message.assume_z() << "\"" << std::endl;
    std::cout << "in: \"" << fun.assume_z() << "\"" << std::endl;
}
#define logMessage(message) logImpl(gsl::ensure_z(message), gsl::ensure_z(__FUNCTION__))
```
@gdr-at-ms is it what is recommended by "Use zstring and czstring to represent a C-style, zero-terminated strings. But when doing so, use string_span from the GSL to prevent range errors" ?

**Comment by ericLemanissier** [comment]
It's true that constructing string_span from ensure_z is doing basically the same as strnlen.

> Both czstring_span and cstring_span have specialisations for string literals with known compile time lengths
I could not find (c)zstring_span specialization for string literals. Where did you find it ?

**Comment by gdr-at-ms** [comment]
Performance concerns are best investigated with concrete data in hand.

**Comment by ericLemanissier** [comment]
Indeed, strlen is totally optimized out on recent versions of gcc and clang.
Having said that, I realized the macro I posted earlier was wrong, it should have been
```c++
#define logMessage(message) logImpl(gsl::span<const char>(message), gsl::span<const char>(__PRETTY_FUNCTION__))
```
gsl::ensure_z actually removes the null terminator from the result string
