### ISSUE TITLE
P.9 Doesn't mention or expect RVO

### ISSUE THREAD

**Issue by Melkonka** [isocpp/CppCoreGuidelines#641]
There is a note for the waste function: "The spurious definition of copy operations disables move semantics so that the return operation is slow."

I am a little bit confused. I believe we can safely assume, that named return value optimization will apply in this case.

Am i missing something?

**Comment by gdr-at-ms** [comment]
The RVO is not guaranteed in this case.  Will tidy up the document,

**Comment by BjarneStroustrup** [comment]
Noted

**Comment by Melkonka** [comment]
I am not sure if being this defensive is a good idea. It's surely not garantueed, but a modern compiler will most likely do it, so i think it's important to count with it.
GCC 4.8 (2 years old) does nrvo, clang also does it.

I understand, that the guideline have to be somewhat politically correct, but i believe reality is more important.

So i think instead of this: " (please note that the Return Value Optimization, RVO, is not guaranteed here)"
This would be much better: " (please note that modern compilers does Named Return Value Optimization, even if it's not garantueed by the standard C++17.)"
