### ISSUE TITLE
Dependency manager

### ISSUE THREAD

**Issue by Avitella** [isocpp/CppCoreGuidelines#66]
What about dependency manager? This is a much more important part of the infrastructure of the language than string_view or array_view.

**Comment by cirosantilli** [comment]
+1 Also mentioned by a few people on Reddit: https://www.reddit.com/r/programming/comments/3ltwwf/bjarne_stroustrup_announces_c_core_guidelines/

**Comment by AndrewPardoe** [comment]
Thanks for the suggestion, @Avitella and @cirosantilli. We agree that C++ should have a good, cross-platform, cross-compiler dependency manager. But while it's an important problem, it's not the problem we're trying to solve with the Guidelines.

Dependency managers so far have been tied to build systems. Here's a Reddit thread about the need for a dependency manager for CMake, for example: https://www.reddit.com/r/cpp/comments/2eiulw/dependency_manager_for_ccmake_projects/. The Guidelines are intentionally agnostic of your compiler or build system.
