### ISSUE TITLE
F.4 and F.8 constexpr functions are pure

### ISSUE THREAD

**Issue by Amaroker** [isocpp/CppCoreGuidelines#660]
Note in F.4 says:

> constexpr functions are pure: they can have no side effects.

Note in F.8 says:

> constexpr functions are pure.

Since constexpr functions may throw, it's not true that constexpr functions are pure when they are evaluated during runtime. 

When an object is thrown, the constructor is allowed to modify global variables. Doesn't that count as a side effect?

**Comment by mfukar** [comment]
According to §5.19/2 throw-expressions are not constant expressions.

**Comment by cubbimew** [comment]
Indeed, it appears that constexpr functions are often mistaken for constant expressions.

**Comment by BjarneStroustrup** [comment]
Note added
