### ISSUE TITLE
Pro.safety.Type.3 Don't use const_cast at all

### ISSUE THREAD

**Issue by Amaroker** [isocpp/CppCoreGuidelines#662]
> Don't use const_cast to cast away const (i.e., at all).
> 
> Exception: You may need to cast away const when calling const-incorrect functions.

Don't you think const_cast can be appropriate in a case like this? 

```
std::map<X*, Y> map;
map.find( const_cast<X*>(x) );
```

If so (assuming that std::map::find isn't considered a const-incorrect function), there needs to be at least one more exception to the rule.

**Comment by BjarneStroustrup** [comment]
Pro.safety.Type.3 should be merged into ES.50

**Comment by AndrewPardoe** [comment]
Rule ES.50 and Pro.safety.Type.3 are related and should possibly refer to each other. But the profiles do double-duty here: we have a guarantee in the beginning of the profile section that doesn't exist in the other rules.

**Comment by neilmacintosh** [comment]
I do not think this is an exception that warrants being called out in the profile, it feels synthetic (esp. without additional context explaining why `const_cast` is the only option in this case).

Any user can suppress violations of the profiles, documenting why they think a particular violation is reasonable for their code.

**Comment by AndrewPardoe** [comment]
Regarding Bjarne's comment, I've added cross-references on these two issues.
