### ISSUE TITLE
Do not encourage using ={0}; to "fill array with zeroes"

### ISSUE THREAD

**Issue by ascheglov** [isocpp/CppCoreGuidelines#663]
"ES.20: Always initialize an object" says

    int buf[max] = {0};   // better in some situations

It should be rewritten as ` = {};`

And there should be a paragraph which says "don't use `= {0}` because it creates a dangerous misconception that `= {X}` would fill an array with `X`".

**Comment by MikeGitb** [comment]
In addition: Why `int buf[max] = {}` instead of just `int buf[max]{}`?

**Comment by BjarneStroustrup** [comment]
yes, and I chose ={} because it's "louder" (less easy to miss)
