### ISSUE TITLE
Encourage the use of variants

### ISSUE THREAD

**Issue by DemiMarie** [isocpp/CppCoreGuidelines#664]
Variant (discriminated union) types are very useful, as shown by ML, Haskell, and Rust.  Variant types should be used whenever there is exactly one of several possibilities.  `boost::variant` already has an implementation.

In environments where exceptions are not available (often including kernels and embedded systems), variants can also be used for error handling.  Rust (which doesn't have exceptions and generally only uses stack unwinding to report bugs) uses pattern matching and variant types to report errors.  Unfortunately, C++'s lack of statement expressions make the ergonomics worse: instead of Rust's `let x = try!(something_that_can_fail);`, we will need something like `TRY(x, something_that_can_fail);`.

**Comment by BjarneStroustrup** [comment]
See the union section. What to do when you can't use exceptions will receive more attention once we find the time
