### ISSUE TITLE
Example in Enum.4 contradicts Enum.3 by preferring "plain" enum 

### ISSUE THREAD

**Issue by wooleyra** [isocpp/CppCoreGuidelines#665]
The example for Enum.4 displays a technique of overloading the ++ operator to increment an int-based enum. This comes directly after Enum.3 which states that one should "Prefer class enums over 'plain' enums" and is the only example in the Enum guidelines to do so.

Also, I'm not sure that "Define operations on enumerations" is a rule that should regularly be followed. I would argue that it risks bloating the CppCoreGuidelines with an unusual technique rather than adding a valuable rule that applies to the general use of enums.

**Comment by BjarneStroustrup** [comment]
done

**Comment by june-panic** [comment]
The example has been changed back to a using a plain enum (possibly by the fix to #716). Please reopen.
