### ISSUE TITLE
Provide an "impact" section for profiles?

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#674]
This would allow people to prioritize the most important sets of guidelines first. Also, we want to encourage that developers adopt groups of rules rather than picking and choosing from a set. 

Example: 
### Impact:

This particular code sample has been associated with ____ security violation.

**Comment by BjarneStroustrup** [comment]
I started, but I/we need to look at the way the profiles are specified. I think they should be defined as a list on rules they enforce, rather as separate rules listed under the profiles. We would not be able to keep two sets of rules in sync.

**Comment by BjarneStroustrup** [comment]
The type-safety and bounds have been reorganized

**Comment by BjarneStroustrup** [comment]
The lifetime profile has been reorganized.
