### ISSUE TITLE
Don't duplicate/contradict already existing CERT Secure Coding Standard

### ISSUE THREAD

**Issue by kmindi** [isocpp/CppCoreGuidelines#70]
There is already a Secure Coding Standard which is activly maintained as a community project at 
https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=637

It would be bad if there would be **two contradicting standards/guidelines** (which inevitably will occur if not everyone involved knows about both projects). There should be a clear statement and before that a decision wether those rules are
- repeated here
- referenced here
- only stated/edited there
- or both guidelines should be merged
- or security related stuff will be handled regardless of the existing "standard" here

Should maybe be transformed in a wiki page after initial discussion.

**Comment by AndrewPardoe** [comment]
There are at least a dozen existing coding standards. They are mutually contradictory. We would like ours to be comprehensive.
