### ISSUE TITLE
ES.23: Multiple  {}  initializers in one line. Good or bad?

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#701]
Example:
1. `auto* a{ new int{5} };`
2. `auto* b = new int{5};`
3. `auto c{ sum({ 1, 3, 5}) };`
4. `auto d = sum({1, 3, 5});`

Rule ES.23 should be improved by adding information on this case.
Add current version contain new vector in a sample, which should be refactored if needed.

What you guys think?

**Comment by BjarneStroustrup** [comment]
I don't think that an initializer in an initializer expression is a special case.

**Comment by hsutter** [comment]
Editors discussed on 8/29 and we can't see a problem here.
