### ISSUE TITLE
Improve P.11 example

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#704]
Current: `v.push_back(yet_another)int);` 
Remove typo: `v.push_back(yet_another_int);` or
Better replace line with: `v.reserve(v.size()*2)` or `v.resize(v.size()*2)`
So its code behavior would be more similar to bad example.

**Comment by MikeGitb** [comment]
I agree that the two versions don't quite do the same thing (you can interpret the missing parts into the `//...` sections of course), but I'm not too happy about your suggestion to use `resize,` or `reserve` as it runs somewhat contrary to what this example is supposed to demonstrate: 
> Encapsulate messy constructs, rather than spreading through the code

The nice thing about vector (and the whole point it is used here) is that it encapsulates/hides that growth logic. If anything, I'd rather expand the C-style version to match more closely what the vector does.

**Comment by ParadineG** [comment]
> If anything, I'd rather expand the C-style version to match more closely what the vector does.
I also agree that would be more fitting with also removing only typo from good example. 
`//...` sections are dangerous. While they seem understandable for experienced programmers, they might be too much for newcomers.

**Comment by BjarneStroustrup** [comment]
I modified the C-style example a bit
