### ISSUE TITLE
variable shadowing may be addressed

### ISSUE THREAD

**Issue by coollpe** [isocpp/CppCoreGuidelines#711]
Variable shadowing can cause some bugs difficult to find. I have came across one today when a colleague adding a if-else block and use the same name of variable in the big else block.

Suggest add a guide about how to deal with variable shadowing and avoid potential risks.

int d = 0;
if (...) {
   d = ...;
} else {
   // a big block
   int d = ...
}
return d;

**Comment by BjarneStroustrup** [comment]
Hmmm. I thought we had such a rule, but I don't see it. Will add.
