### ISSUE TITLE
ES.100 example does not illustrate ES.100

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#712]
The example in ES.100 "Don't mix signed and unsigned arithmetic" is inappropriate:

`cout << abs(x-y) << '\n'; // wrong result`

This illustrates an attempt to use unsigned types for non-modular arithmetic (exactly what ES.102 says); no signed types are involved here, so this does not illustrate "Don't mix"

It also only gives "wrong result" prior to LWG #2192. In current C++17 WP this call to abs() is explicitly ill-formed by `26.9.2[c.math.abs]p3`

I still think multiplying `-1` by `sizeof` in hope to move some file pointer or char* to the left is a better demo of the problem mixing signed and unsigned types in the same arithmetic expression (because that's one case I've seen fail in real life)

**Comment by BjarneStroustrup** [comment]
And I still think that the realistic example is too realistic. It has distracting features, such as the reinterpret_cast. Also, Microsoft C++ diagnoses many such examples, e.g., int x = -sizeof(S);
I added a simple synthetic example; better?

**Comment by cubbimew** [comment]
okay, fair enough.
