### ISSUE TITLE
Good example for C.128

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#713]
Without a good example C.128 is confusing still confusing, because not seen often in practice yet.
class Base {
public:
	virtual void func1() { std::cout << "Base"; }; 
	virtual void func2() = 0; //virtual also implicitly applies to any overwriting functions
	virtual ~Base() = default;
};
class Middle : public Base {
public:
	void func1() override { std::cout << "Middle"; };  //override only enforces
	void func2() override { std::cout << "Can be changed"; };
	~Middle() override = default;
};
class Top : public Middle {
public:
	void func1() override { std::cout << "Top"; };	//Common
	void func2() final { std::cout << "Can't be changed"; }; //Rare (See C.149)
	~Top() override = default;
};

**Comment by BjarneStroustrup** [comment]
Thanks. I have made some changes
