### ISSUE TITLE
C.131 - Consider marking getters as const and using brace-init for data members

### ISSUE THREAD

**Issue by GiovanniDicanio** [isocpp/CppCoreGuidelines#718]
In the `Point` class definition, getters like `get_x()` and `get_y()` should be marked as `const`:

```
class Point {
...
public:
    int get_x() const { return x; }
    int get_y() const { return y; }
};
```

Moreover, since those guidelines are about modern C++, probably brace-init should be the default preferred way of initializing data members, e.g.:

```
struct Point {
    int x{}; // or int x{0};
    int y{};
};

```

The x and y data members in the Point class may be initialized using brace-init as well, with the addition of a =default ctor.

I saw a separate thread on the validity of this rule, so I won't touch this topic here.

**Comment by ParadineG** [comment]
Those are nice suggestions but low on priority: Issue #699 
If sb has time to fix those why not.
If someone starts fixing it please also improve titles:
**Example, bad**
`class Point ...`
**Example, good**
`struct Point ...`
It will help clarify intent for advice C.131.

**Comment by BjarneStroustrup** [comment]
Done
