### ISSUE TITLE
are examples from Bounds.1 still up to date?

### ISSUE THREAD

**Issue by peteer22r** [isocpp/CppCoreGuidelines#735]
Example, good

```
void f(span<int> a) // BETTER: use span in the function declaration
{
    int n = *a++; // OK
    span<int> q = a + 1; // OK
}
```

I tired this using https://github.com/Microsoft/GSL and it didn't compile.
Maybe it's library issue?

**Comment by neilmacintosh** [comment]
@peteer22r no, the examples are out-of-date and refer to functions that are no longer part of the interface of `span`. I'll take a look at cleaning them up. Thanks for the catch!

**Comment by neilmacintosh** [comment]
@peteer22r thanks for raising this issue. I went through and cleaned up the obsolete `span` syntax. As of commit deb47c0 this should be fixed.
