### ISSUE TITLE
F.17 "in-out" parameters -- make explicit, add a gsl::inout helper function.

### ISSUE THREAD

**Issue by daphnediane** [isocpp/CppCoreGuidelines#739]
The current guidelines seem to allow obscure the use of references as in-out parameters. Might it be better to encourage making in out explicit. Some checkers such as lang-tidy's google-runtime-references which references [Google's Style guide for reference arguments](https://google.github.io/styleguide/cppguide.html#Reference_Arguments) already highlight these references.

I was thinking that a different approach might work as well as be visible at the call site without having to check function definitions, similar to how owen and the like help out with ownership. This could be done by adding a inout helper function something like:

```
template <typename T>
inline T& inout(T &x) { return x; }

template <typename T>
void inout(T &&) = delete;

template <typename T>
void inout(T const &x) = delete;
```

This could be used thusly

```
void some_function( a_type &a_val );
...
void some_caller() {
  a_type local_var;
  ...
  some_function( local_var ); // checker would suggest wrapping local_var in gsl::inout( ) here
  ...
}
```

Resulting in the updated code

```
void some_caller() {
  a_type local_var;
  ...
  some_function( gsl::inout( local_var ) );
  ...
}

```

**Comment by KrisTC** [comment]
I agree. I personally don't like in out parameters as references for this reason. In our code base we use pointers because when you can see the address of to highlight this, but then we have null checks everywhere :( 

I may get shot for this but I actually like the way C# did this with out and ref keywords. These methods make much more explicit. I wonder if a type a bit like owned could help too so the param is gsl:inout<t&>?

**Comment by daphnediane** [comment]
If the parameter where to be type it could be done something like this:

```
template <typename T>
using inout = T&;

template <typename T>
inline T& make_inout(T &x) { return x; }

template <typename T>
void make_inout(T &&) = delete;

template <typename T>
void make_inout(T const &x) = delete;

template <typename T>
inline T& make_temporary_inout(T &&x) { return x; }
```

With the using code being something like this.

```
void some_function( gsl::inout<a_type> a_val );
...
void some_caller() {
  a_type local_var;
  ...
  some_function( gsl::make_inout( local_var ) );
  ...
}
```

With the advantage that checkers could check both the code as well as the callers. I made make_temporary_inout explicitly different as having make_inout ( or inout in my original version ) implicitly work with rvalues seems dangerous.

Another possible implementation would be to make gsl::inout be an alias to std::reference_wrapper and make_inout be similar to std::ref.

**Comment by AndrewPardoe** [comment]
By default, anything that is non-const is in-out. Adding an "inout" is syntactic sugar. That raises the question of how valuable it is to mark this in the code. It raises visibility but is it sufficiently valuable?

Are you asking that we should have a syntactic marker in every possible place where a parameter should be modified? If not, could you clarify what you're asking?

**Comment by daphnediane** [comment]
Yes it is syntactic sugar and ideally should optimize away similar to how owned does.

The reason I think it should be consider is that their already are checkers and guidelines that suggest replacing non-const references with pointers and using ampersands at the calling location. As Kris pointed out this leads to a lot of extra NULL pointer checks. Following those guidelines also raises potential issues with array to pointer decay, potential nullptr issues etc. I'd like to see the core guidelines recommend against such an approach and ofter an optional alternative that should be easily handled by code checking and rewriting tools. I've recently gone through a code base that I work on switching to this approach and while it was a lot of locations it added no overhead and actually caught a couple of pointer decay issues.

Example of how non-const reference to pointer argument guidelines can introduce array to pointer decay issues and the like:
```
extern void ref_version( int &arg1 );
extern void ptr_version( gsl::not_null<int *> arg1 );

extern void test() {
  int bar[5];
  // original
  ref_version( bar[1] );
  ref_version( bar ); // correct error here
  // with inout
  ref_version( inout( bar[1] ) );
  ref_version( inout( bar ) ); // correct error here
  // with non-const reference => ptr
  ptr_version( &bar[1] );
  ptr_version( &bar ); // correct error here
  ptr_version( bar ); // but decay not detected here
}
```

**Comment by gdr-at-ms** [comment]
Within this suggestion, should programmers then switch to writing
```
std::vector<int> v { 1, 2, 3, 4, 5 };
inout(v)[1] = 42;
ref_version(v)[3] = 43;
ref_version(v).push_back(56);
```
or
```
std::vector<int> v { 2, 3, 4, 5, 6 };
std::vector<int> w { 0, 9, 8, 7, 6 };
std::swap(inout(v), inout(w));
```
?

**Comment by daphnediane** [comment]
I assume you meant:
```
std::vector<int> v { 1, 2, 3, 4, 5 };
inout(v)[1] = 42;
inout(v)[3] = 43;
inout(v).push_back(56);
```
and yes point well taken.

**Comment by MikeGitb** [comment]
Just to understand this: contrary to the pointer version your typedefs don't require the caller to make this visible at the callsite by using `inout` or `make_inout`, right? Tho the checking would be done by some tool that checks for the cppcoreguidelines like clang_tidy

**Comment by daphnediane** [comment]
Exactly. They are just syntactic sugar and would require a checker to catch mismatches in use. In particular this means that if say a library was developed using this, the users of the library wouldn't have to care about it if they didn't want to and could just use unannotated references. Same would be true in the other direction as well.

**Comment by MikeGitb** [comment]
I'm a bit torn on the subject.

In general, I belong to the group of people who believe that concise code is more readable, even if information is omitted (e.g. By using shorter aliases for namespaces or using abbreviations in variable names, using auto a lot etc.) so I'm not too thrilled about the idea of having this convention enforced by some coding standard. I think most of the time, const correctness + function naming + minimizing the number of parameters takes care of this problem. (`sort(v)` doesn't require any additional explanation).

However, every know and then I find myself in situations where I'd like to explicit signal other programmers that a parameter will be modified.

**Comment by daphnediane** [comment]
Understandable, as GDR pointed out above it would be needless verbose when used with member functions and well known standard library functions, etc.

The second version `template <typename T> using inout = T&;` and `make_inout` have a slight advantage compared to just using at call sites because it can restrict checking to just functions that programmers have flagged explicitly. So an update function might just use plain references, but a function that might not be clear could have some explicitly marked with `inout<T>`.

**Comment by Pazns** [comment]
Isn't this the role of comments ?

**Comment by daphnediane** [comment]
Comments and documentation are great but a lot harder for for tools to check and also tend not be be as visible at the call site. See also [P.1: Express ideas directly in code](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#a-namerp-directap1-express-ideas-directly-in-code).

**Comment by cubbimew** [comment]
Even though I find it surprising to hear that pass-by-reference is "obscure": `cin >> var;` and `getline(cin, str);` modify both arguments and are taught very early on, I believe Microsoft has experience with [these annotations](https://msdn.microsoft.com/en-us/library/hh916382.aspx) (they spell this one `_Inout_`). How did it work out?

**Comment by gdr-at-ms** [comment]
SAL was originally developed for C-style programs.

In recent years, Microsoft has been encouraging direct modern C++ where the annotations are superseded by the semantics of ISO C++.  So, in C++ programs that follow the Guidelines, `_In_` is redundant and deprecated. There is no full replacement for `_Out_` yet in the language.  The Guidelines recommend preferring return by value -- especially even better now that we have structured bindings, but ABI concerns in some contexts may interfere.  

I don't think the suggestion in its current form in this PR is something we would recommend at Microsoft.  One principle we are follow.ing consistently is that if programmers are asked to write something extra (compared to the default), then it should be because that extra typing is adding value that is worth the trouble.

**Comment by neilmacintosh** [comment]
Thanks everyone for the discussion!

@gdr-at-ms is correct. We have plenty of experience with making "inout" explicit in people's programs and it is actively unhelpful. Our standard recommendation for SAL today is "please do not use _Inout_"). Anything that is passed by-pointer or by-reference without a const qualification is - by definition - being passed "inout".
