### ISSUE TITLE
ES.28 complex initialization with lambda should discuss parenthesising the expression

### ISSUE THREAD

**Issue by alex-weej** [isocpp/CppCoreGuidelines#741]
The example given is basically like so:

```
auto const somethingComplex = [&] {
   // snip
}();
```

It's not clear from the first line whether `somethingComplex` is actually a function, or not. In JavaScript, it's a very common pattern (IIFE / Immediately-Invoked Function Expression) and parentheses are used as a visual cue, i.e.:

```
auto const somethingComplex = ([&] {
   // snip
})();
```

There is some debate around exactly where the `()` go, and other JavaScript-specific reasons for including the parentheses at all, but the visual cue of reading on the first line:

```
auto const somethingComplex = ([&] {
```
helps indicate immediately that it's not "merely" a lambda expression.

Recommend a brief note about this pattern.

**Comment by MikeGitb** [comment]
I agree, that a visual clue might make reading those expressions easier. I'm not sure I agree with the solution though, as it imho looks weird and isn't really self-explanatory (at least not for a c++ - programmer like me). I personally would prefer to use invoke on the lambda:

	auto const somethingComplex = std::invoke([&] {
		// snip
	});

that way the `()` suffix gets replaced by an `std::invoke` "prefix", but this is admittedly even more verbose.

**Comment by alex-weej** [comment]
Agree with your points. I guess the problem is that `std::invoke` is not a thing yet, and indeed the verbosity is kind of annoying for something we expect to become more common.

**Comment by alex-weej** [comment]
Worth also noting that this syntax was also alien to the JavaScript community until a few authors started promoting it.

**Comment by gdr-at-ms** [comment]
If we were going to add some syntactic clue that this is invocation of the lambda, I think I would go with @MikeGitb 's suggestion.

**Comment by AndrewPardoe** [comment]
We don't _need_ an explicit syntax. It may have some value for those who are unfamiliar with lambdas but once people are used to lambdas it will just be extra syntax. 

Thank you for the suggestion.

**Comment by alex-weej** [comment]
Hi @AndrewPardoe 

The standard library sets a precedent of accessors that are merely nouns, e.g. `std::vector::size()`.

With that, if I have

```
auto const size = [&] {
   // ... lots ...
   // ... lots ...
   // ... lots ...
```

It's not clear until you get to the END of the lambda expression, whether this is something which should be *called* as `size()` or not.
