### ISSUE TITLE
But [[suppress]] into namespace to not collide with standard attributes

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#742]
Hello,

I worked on some initial support for the [[suppress]] attribute in clang [1], [2].
By clang's policy, I cannot call the attribute [[suppress]](without a namespace), because it is not an attribute from the official C++ standard. Clang-specific attributes, e.g., are all in clang namespace (like [[clang::something]]).
The [[suppress]] attribute is not clang-specific, though, so I would like to ask the editors if they
consider moving the [[suppress]] attribute into a (vendor-neutral) namespace.
(Examples from the top of my head: "cpg::", "core::")

Thank you!

Best wishes,
Matthias Gehre

[1] https://reviews.llvm.org/D24886
[2] https://reviews.llvm.org/D24888

**Comment by MikeGitb** [comment]
Should probably be `gsl::` as this is also the namespace used by the guideline support library.

**Comment by neilmacintosh** [comment]
@mgehre this is actually where MSVC already puts it : in the namespace `gsl`. So I think we just need to update the documentation here to match.

**Comment by AndrewPardoe** [comment]
Neil, can you please update the documentation to match?

**Comment by AaronBallman** [comment]
This does not appear to be resolved in the public documentation yet. There's no need to file a PR for LLVM, the patch is still under review (and will go in with the name gsl::suppress).

**Comment by neilmacintosh** [comment]
@AaronBallman The only public documentation I can see is the single example in the Core Guidelines, where the attribute is first mentioned. I just updated that example, so hopefully that's enough.

@AndrewPardoe I'm pretty sure you can use GitHub as well, and I don't work for you ;-)

**Comment by AaronBallman** [comment]
@neilmacintosh Yes, that looks great to me, thank you!

**Comment by neilmacintosh** [comment]
Glad to hear it @AaronBallman! Thanks for following up!
