### ISSUE TITLE
ES.75 code snippet issue

### ISSUE THREAD

**Issue by omtcyfz** [isocpp/CppCoreGuidelines#747]
This is what ES.75 code snippet looks like:

```
int x;
do {
    cin >> x;
    x
} while (x < 0);
```

First of all, it doesn't compile. I'm not sure what should be on the line with `x`.
Second, I'm not even sure what it is supposed to do. I know, it doesn't have to be smart, but I would love to see at least meaningful examples.

**Comment by johelegp** [comment]
That line should probably be something like

    use(x) // is the termination condition the call's precondition?
           // do we meet it the first time?

**Comment by omtcyfz** [comment]
@johelegp This is slightly less confusing, but IMO still is remains that.

I mean, there are dozens of absolutely trivial use-cases for `do {} while (x)` with `x--` in the end of each `do` iteration. Otherwise it still looks confusing to me.

**Comment by johelegp** [comment]
I believe that the example, as it would be with the correction of my previous comment, would do be better if it was marked as _bad_ and a _good_ example was given to show the downfalls mentioned in the _reason_, like this:

**Example (better)**

    int x;
    while (cin>>x && x<0) // check that x is read
        use(x); // precondition checked
    // use x (possibly uninitialized)

**Example (best)**
See ES.72.

    for (int x; cin>>x && x<0; )
        use(x);
    // can't use (uninitialized) x here

**Comment by MikeGitb** [comment]
I don't want to defend `do while` here, but quite honestly I don't see the point here :

> [...] and the condition is not checked the first time through. ???

or  

> // is the termination condition the call's precondition?

Of course it isn't. If I wanted it to be checked, I wouldn't use a do while loop in the first place. The whole purpose of a do while loop is to give me one guaranteed pass through the loop body and if I want that (which is probably very rarely the case), then it doesn't make sense to use a different loop.

Btw.: I think one example, where do while loops are seen often is something like this::

	int selection = 0;
	do {
		std::cout << 
			"######### Fooo #########\n"
			"#  Select and option:  #\n"
			"#  1) pay              #\n"
			"#  2) withdrawl        #\n"
			"########################\n";
		cin >> selection;
	} while (! (0 <selection && selection < 3));

	switch (selection) {
		//...
	}

More generally: I make a query (could also be a web request) and repeat that query until I'm satisfied with the answer.

**Comment by AndrewPardoe** [comment]
Bjarne says he intended that `x` line to be a `// ...`. Thank you for catching the error! We'll fix it.

**Comment by AndrewPardoe** [comment]
Fixed with commit f6dd6159f8eb2f154d28b6132fd583cb8611101a

**Comment by omtcyfz** [comment]
Good, thanks!
