### ISSUE TITLE
C.183 states/implies that reinterpret_cast<> to char type is UB

### ISSUE THREAD

**Issue by villintehaspam** [isocpp/CppCoreGuidelines#750]
Rule [C.183](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c183-dont-use-a-union-for-type-punning) among other things gives the advice to use a `reinterpret_cast<unsigned char*>` to look at object representations. In the comment in the code example it is claimed that the access through the resulting pointer is undefined behavior, this is likely a copy and paste error from the example above.

In the paragraph below it is stated that accessing the result of a `reinterpret_cast` to a different type is undefined behavior, which is true except when the resulting type is `char` or `unsigned char`.

While my legalese may be failing me, I believe this is stated in rule 3.10 in the standard.

For the specific example, it might also be a good idea to add a comment that says that byte order is unspecified or similar.

**Comment by AndrewPardoe** [comment]
We agree. GDR will create a PR to fix this.

**Comment by gdr-at-ms** [comment]
Fixed.
