### ISSUE TITLE
Call stack trace standartization

### ISSUE THREAD

**Issue by tapika** [isocpp/CppCoreGuidelines#753]
Hi !

I would be interested in standardization of call stack determination on C++ level, which would include native and mixed mode call stack determination.

I've now just opened source code for call stack determination (as well as it's design) over here: https://sourceforge.net/p/diagnostic/svn/HEAD/tree/src/
https://sourceforge.net/p/diagnostic/svn/HEAD/tree/ - "7. Stack trace determination".

but main problem is that this is small utility, it does not have background support. At any time when Microsoft decides to break API compatibility - my call stack determination will perish.

Also portability - Mac / Linux is interested also to me.

I'm not sure if this is correct place to ask about this ?

**Comment by gdr-at-ms** [comment]
[Standardization forums](https://isocpp.org/forums) are better sweated for this topic and question.
