### ISSUE TITLE
Add a warning about fwrite can crash if 2nd and 3rd arg are a length or size of a std::string.

### ISSUE THREAD

**Issue by AraHaan** [isocpp/CppCoreGuidelines#764]
I have noticed that it can crash when having the second and third args the same and > 1 that their code will definately crash.

I even have code that can provide a example of such to avoid doing so documenting that it is safer to always have the 3rd arg being 1 (unless they know what they are doing) is and should be part of the Guidlines.

``` cpp
int FileStuff(std::string filename1, std::string filename2, std::string CustomVariable, std::string basedir)
{
    /*
    TODO: Check if file actually exists before trying to open them to avoid a crash with trying to open a file to read with fopen.
    Might as well also somehow check if the disc is not full as well for when trying to write to a new file to avoid a crash as well.
    */
    f = fopen(filename1.c_str(), "r");
    f2 = fopen(filename2.c_str(), "w");
    unsigned long n = 0;
    data = "/*\n    File Generated with bin2c Conversion Tool v0.0.1.\n Free for any use.\n DO NOT MODIFY THIS FILE!!!\n*/\n/*\n    ";
    data += filename2.replace(0, basedir.length(), "");
    if (CustomVariable != "")
    {
        data += "\n*/\n\nconst unsigned char ";
        data += CustomVariable;
        data += "[";
        //TODO: ADD in Calculating the Size in bytes to make Arrays just like a ex editor gets the hex data for every byte in every file.
        //This is for properly embedding the data in a source or header file.
        data += "] = {\n";
    }
    else
    {
        data += "\n*/\n\nconst unsigned char a[";
        //TODO: ADD in Calculating the Size in bytes to make Arrays just like a ex editor gets the hex data for every byte in every file.
        //This is for properly embedding the data in a source or header file.
        data += "] = {\n";
    }
    while(!feof(f))
    {
        unsigned char c;
        fread(&c, 1, 1, f);
        //if(fread(&c, 1, 1, f) == 0)
        //{
        //  break;
        //}
        //std::cout << "0x" << (unsigned int)c << std::endl;
        data2 = "0x%.2X,";
        data2 = data2.replace(3, 4, (unsigned int)c);  //TODO: Actually get the true hex data as shown in any hex editor without std::hex related Errors from this.
        data += data2;
        ++n;
        if (n % 10 == 0)
        {
            data += "\n";
        }
    }
    data += "};\n";
    fwrite((const void *)data.c_str(), data.length(), data.length(), f2);
    std::cout << filename2.replace(0, basedir.length(), "") << " was successfully generated. Be sure to add it to your C/C++ Project file.\n";
    fclose(f2);
    fclose(f);
    return 0;
}
```

Basically the compiler should at least warn them that using fwrite like this can produce a assembly that will for sure crash at the fwrite line.

alternatively the same thing with the crash fixed:

``` cpp
int SIZE = 1;
int FileStuff(std::string filename1, std::string filename2, std::string CustomVariable, std::string basedir)
{
    /*
    TODO: Check if file actually exists before trying to open them to avoid a crash with trying to open a file to read with fopen.
    Might as well also somehow check if the disc is not full as well for when trying to write to a new file to avoid a crash as well.
    */
    f = fopen(filename1.c_str(), "r");
    f2 = fopen(filename2.c_str(), "w");
    unsigned long n = 0;
    data = "/*\n    File Generated with bin2c Conversion Tool v0.0.1.\n Free for any use.\n DO NOT MODIFY THIS FILE!!!\n*/\n/*\n    ";
    data += filename2.replace(0, basedir.length(), "");
    if (CustomVariable != "")
    {
        data += "\n*/\n\nconst unsigned char ";
        data += CustomVariable;
        data += "[";
        //TODO: ADD in Calculating the Size in bytes to make Arrays just like a ex editor gets the hex data for every byte in every file.
        //This is for properly embedding the data in a source or header file.
        data += "] = {\n";
    }
    else
    {
        data += "\n*/\n\nconst unsigned char a[";
        //TODO: ADD in Calculating the Size in bytes to make Arrays just like a ex editor gets the hex data for every byte in every file.
        //This is for properly embedding the data in a source or header file.
        data += "] = {\n";
    }
    while(!feof(f))
    {
        unsigned char c;
        fread(&c, 1, 1, f);
        //if(fread(&c, 1, 1, f) == 0)
        //{
        //  break;
        //}
        //std::cout << "0x" << (unsigned int)c << std::endl;
        data2 = "0x%.2X,";
        data2 = data2.replace(3, 4, (unsigned int)c);  //TODO: Actually get the true hex data as shown in any hex editor without std::hex related Errors from this.
        data += data2;
        ++n;
        if (n % 10 == 0)
        {
            data += "\n";
        }
    }
    data += "};\n";
    fwrite(data.c_str(), SIZE, data.length() , f2);
    std::cout << filename2.replace(0, basedir.length(), "") << " was successfully generated. Be sure to add it to your C/C++ Project file.\n";
    fclose(f2);
    fclose(f);
    return 0;
}
```

Yeah, this might be small but it would be nice to at least warn about it for others who are wondering why their code might be crashing while on the fwrite line only because of the 3rd arg. Alternatively if the fwrite function was to know that both are the same and > 1 and override it to 1 on the 3rd arg would be a good idea too.

You guys might also be thinking `why fopen over fopen_s` the answer is I heard that secured version when it throws a overflow or something can and will close the program that called the function. Not entirely sure myself as I did not have that happen to me yet, and that I know how to use the unsecured one properly.

so, @BjarneStroustrup you think 1 of these would be a good idea to note down for Cuture versions of C++? I hope I can be of help with this find.

Also it would be nice that if there was a file opening mode that would directly return a list of 0x[hex of every byte] in the very exact same order to not try to for loop that stuff to make code like this smaller and easier to do. And would not add in a extra `,` like my for loop would So there might be at least a noteable idea here.

**Comment by jwakely** [comment]
Thanks for the suggestion, but IMHO it's not practical to add specific warnings about every possible misuse of every standard library function, you need to read the documentation for the APIs you use.

Anyway, you're still calling the function incorrectly, it should be `fwrite(data.c_str(), 1, data.length(), f2);` i.e. the size of the items to write is 1 and the number of items to write is `data.length()`.

> You guys might also be thinking why fopen over fopen_s

No, I'm thinking why `fopen` over `std::fstream`?

**Comment by AraHaan** [comment]
ok fixed my use of fwrite on the second code useage. 

hmm I guess I could use fstream I would have to test it some to see.

**Comment by AraHaan** [comment]
The code on it now uses ``std::ifstream`` and ``std::ofstream`` from ``<fstream>``, and the exist check uses ``std::experimental::filesystem::exists`` from ``<experimental/filesystem>`` sadly building on linux and OSX fails when you need at minimum for those ``g++-6`` and ``clang 3.9``. Well linux works on the ``g++-6`` part but not the ``clang 3.9`` part and OSX fails on both. Maybe I just have to build ``clang 3.9`` with ``clang 3.4``.

Feel free to look at the code of it at https://www.github.com/AraHaan/bin2c if you would like to. I am also open to suggestions. Also it would be nice if the ``.format`` function in ``std::string`` supported string tuples that can be formatted like so in this example hello world python code:

```py
>>> stuff = "hello {0}".format("world!")
>>> print(stuff)
hello world!
```

If C++ had something like this for ``std::string`` which contains any ``{}``'s which can hold a number donoting the possition of the arg to use from the ``.format`` it would help remove a lot of ``std::string`` variables.

This would become old:

```cpp
mystring += SOMESTRINGCONST + _myvariabledatathatcanchange + ANOTHERSTRINGCONST;
```

And then if it was added this would become new:

```cpp
mystring += SOMESTRINGCONST.format(_myvariabledatathatcanchange)
```

Note: ``mystring``, ``SOMESTRINGCONST``, ``_myvariabledatathatcanchange``, and ``ANOTHERSTRINGCONST`` in these examples are of type ``std::string``.

But yeah it C++ had something like this it would help optimize a lot of code like I shown in the examples.

**Comment by grahamreeds** [comment]
Why use filesystem at all? As you point out this requires quite recent
versions of C++ - a luxury that a lot of devs (I am stuck with GCC 4.8.4
until 14.04 leaves LTS).

Also file exists at that specific moment. It may not exist at a later date
(though in practice it probably will do).

Thirdly, and iirc, if fstream fails it throws - which means people who
can't use exceptions are ruled out.

Finally what are the speed implications of using streams. It may be okay on
one or two tests but send through three thousand and is there a performance
increase/decrease?

Sent from my Nexus 6P

On 2 Jan 2017 11:51 pm, "AraHaan" <notifications@github.com> wrote:

The code on it now uses std::ifstream and std::ofstream from <fstream>, and
the exist check uses std::experimental::filesystem::exists from
<experimental/filesystem> sadly building on linux and OSX fails when you
need at minimum for those g++-6 and clang 3.9. Well linux works on the g++-6
part but not the clang 3.9 part and OSX fails on both. Maybe I just have to
build clang 3.9 with clang 3.4.

Feel free to look at the code of it at https://www.github.com/AraHaan/bin2c
if you would like to. I am also open to suggestions. Also it would be nice
if the .format function in std::string supported string tuples that can be
formatted like so in this example hello world python code:

>>> stuff = "hello {0}".format("world!")>>> print(stuff)
hello world!

If C++ had something like this for std::string which contains any {}'s
which can hold a number donoting the possition of the arg to use from the
.format it would help remove a lot of std::string variables.

This would become old:

mystring += SOMESTRINGCONST + _myvariabledatathatcanchange + ANOTHERSTRINGCONST;

And then if it was added this would become new:

mystring += SOMESTRINGCONST.format(_myvariabledatathatcanchange)

Note: mystring, SOMESTRINGCONST, _myvariabledatathatcanchange, and
ANOTHERSTRINGCONST in these examples are of type std::string.

But yeah it C++ had something like this it would help optimize a lot of
code like I shown in the examples.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/isocpp/CppCoreGuidelines/issues/764#issuecomment-270033903>,
or mute the thread

**Comment by jwakely** [comment]
> when you need at minimum for those g++-6

FWIW GCC 5.3 supports `<experimental/filesystem>`.

> if fstream fails it throws

Only if you request it to. The default is to set the stream state to indicate failure and not throw anything.

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion--per our discussion we feel the correct place for this checking would be in compilers themselves. 

We do have guidance such as I.23, avoiding lots of arguments.
