### ISSUE TITLE
Allow __PRETTY_FUNCTION__ and friends without array bounds checks

### ISSUE THREAD

**Issue by rianquinn** [isocpp/CppCoreGuidelines#765]
Currently tools like Clang Tidy get mad about the use of __PRETTY_FUNCTION__ and friends because the C++ Core Guidelines do not explicitly call out that these are safe to use without bounds checks. For reference, please see the following:

https://reviews.llvm.org/D22196

and

https://llvm.org/bugs/show_bug.cgi?id=28480

The only advice they have at the moment is to wrap built in macros with a static cast, or with a GSL container. Neither of these should be needed as there is no way to really make a built in macro safer. Based on the links, they seem to open to fixing the issue if the C++ Core Guidelines explicitly calls out that bounds checks do not apply to built in macros. 

Thoughts?

**Comment by gdr-at-ms** [comment]
They are compiler-specific extensions in addition to the standard `__func__`.  Issues with them should be taken to the relevant compiler writers.

**Comment by rianquinn** [comment]
@gdr-at-ms The link I provided is from the compiler writers (specifically Clang Tidy). Since the C++ Core Guidelines doesn't exclude built in macros from bounds checks, they currently throw a failure on any use of a built in macro, which (if you read the link), they agree is pointless and incorrect, but because the Core Guidelines is lacking in this area, there is nothing they can do. 

The specifically are asking for the Core Guidelines to address the problem in the documentation so that they too can fix the problem on their end. 

So it would be something as simple as saying "the bound checks do not apply to built in macros", and the problem would be solves in the guidelines, thus enabling Clang Tidy to address the issue in their code.

**Comment by jwakely** [comment]
N.B. `__PRETTY_FUNCTION__` is not a macro, it's an array of `char`.

**Comment by rianquinn** [comment]
@jwakely agreed, sorry for the confusion. 

But yeah, there is nothing wrong with doing:
```
std::cout << "Hello" << '\n';
```

Thus there should be nothing wrong with doing:
```
std::cout << __PRETTY_FUNCTION__ << '\n';
```

as they are basically the same thing.

**Comment by gdr-at-ms** [comment]
@rianquinn I don't consider the Core Guidelines to be lacking regarding `__PRETTY_FUNCTION__`.  The compilers who introduced these extensions are best position to give you guidelines here.

In general, we try to help programmers to write good programs with standard C++.  That is a pretty daunting task already, but we do welcome suggestion for improvements on standard C++ usage.

Where your compiler vendors offer extensions that fall under existing general principles (e.g. what to do with arrays), it is only natural that they use their judgments to decide how they want to expose those extensions to you, considering the Core Guidelines.

**Comment by rianquinn** [comment]
@gdr-at-ms I can respect that argument, and agree since these are extensions. That being said... this begs the questions, why doesn't C++ define (e.g. like Swift), a set of useful features like this for debugging. Knowing which line you're on, which file, and which function is and extremely important debugging tool (every debugger I have used provides this information, and all compilers provide their own versions of these extensions). If C++ defined how this should be done, not only could this problem be avoided, but the need for a macro function to handle default args for logging functions could also be fixed as well. 

Speaking as a user of the Core Guidelines and GSL, my reasons for bringing this up is that doing the following:
```
std::cerr << static_cast<const char *>(__PRETTY_FUNCTION__) << '\n';
```

is really annoying. Seems to me if the issue can be addressed in a non-compiler specific fashion, it's worth a try. I'd be willing to provide a PR if time is the issue. Specifically... because every time something silly like this occurs, it's one more reason people might refuse to listen to the guidelines and use the GSL, and my understanding is that the GSL specifically exists because "standard C++" is not enough.

For example, we might be able to provide in the GSL, clean versions of these to ease development for others attempting to debug their code.

**Comment by jwakely** [comment]
See [std::experimental::source_location](https://rawgit.com/cplusplus/fundamentals-ts/v2/fundamentals-ts.html#reflection.src_loc)

**Comment by gdr-at-ms** [comment]
Those are good questions, for the C++ standards committee or the general C++ community (the committee only works on concrete proposals on the table.)

That being said, standard C++ has `__func__`, and it separate TS facilities to query line and numbers -- see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4519.pdf

**Comment by rianquinn** [comment]
@jwakely, @gdr-at-ms that's awesome as I had no idea that existed. If I read the spec correctly, it appears that it addresses the call site problem, and the non-standard C++ argument. My guess is, the way the spec is written, static tools would still get mad as these functions return the same const char * and not a guarded string, which begs the question, should the GSL provide similar functions for now until this is accepted in a way that the Core Guidelines is in sync with?

For example, GSL::Expects is a temporary function for Contracts. It's not a perfect replacement, but it solves some of the issues people are running into. A `gsl::line()`, `gsl::file_name()` etc... could be provided that returns a guarded string and serves as a means examine whether the spec needs an update, or if the C++ Core Guidelines do.

**Comment by gdr-at-ms** [comment]
They require compiler support.

**Comment by rianquinn** [comment]
I think only for the call site problem, which I would agree needs to wait for that spec. But providing a GSL version that wraps the "const char *" and provides a standard was to do this is enough to get rid of bounds check problems. This is similar to `Ensures` as the real implementation requires compiler support as well, but it's a starting point to at least get everyone on the same page.

**Comment by gdr-at-ms** [comment]
Hmm, I am not understanding. Are you saying you want the GSL to provide wrappers for the source location TS, or are you asking for the GSL to implement that TS?

Either way, I don't know it is the GSL's job.  The GSL's primary goal is to provide a minimal set of library abstractions to support the Guidelines (`span`, `narrow_cast`, etc.)  I don't know source location is one of those obligations.

**Comment by rianquinn** [comment]
I'm saying the GSL can provide wrappers around the source location TS if the compiler has support, and if it doesn't it would provide a wrapper around the compiler extensions. 

IMO this is a GSL issue as the original reason for bringing this up is Clang Tidy complains about `const char *` array bounds due to a Core Guideline. In the link I provide, Clang Tidy developers are saying we should wrap these extensions (and likely the TS if it also returns a `const char *`) in GSL classes to avoid the failed check. So something has to change... either the Core Guidelines explicitly says that the source location can use a `const char *` safely (in which case Clang Tidy can now change their code per the Guideline contract), or the use of `const char *` for source location has to change in which case the GSL can provide an implementation people can use until that is fixed.

**Comment by gdr-at-ms** [comment]
Thanks for clarifying.

I don't think this isn't GSL's charter.  It is the developer's responsibility to use the zcstring wrapper types in their function prototypes. We shouldn't try too hard to make GSL the dumping ground for these sort of things.

**Comment by martinmoene** [comment]
mmm,
>I don't think this isn't GSL's charter.

A double negation and likely not what you mean ;)

**Comment by jwakely** [comment]
> I'm saying the GSL can provide wrappers around the source location TS if the compiler has support, and if it doesn't it would provide a wrapper around the compiler extensions.

It seems unlikely that a compiler would have suitable extensions to implement `source_location` and not implement `source_location` itself. e.g. if GCC provided the necessary extensions then I'd already have added `source_location` to GCC's std::lib. So GSL could only provide a wrapper when `source_location` already exists, in which case a wrapper is pointless, just use `source_location`.

**Comment by rianquinn** [comment]
@jwakely Based on what Clang Tidy is complaining about (assuming it is the use of `const char *`), even if source_location was available, you couldn't use it directly as it goes against the Core Guidelines. You would first have to wrap it in a guarded string.

**Comment by gdr-at-ms** [comment]
@rianquinn Maybe convince Clang Tidy to be more reasonable?

@martinmoene Nice catch! Fixed comment.

**Comment by RedDwarf69** [comment]
Would it make sense to make an exception for any `const char[]` with static storage?

This is not showing a warning with clang-tidy
```
std::cout << "string literal OK" << std::endl;
```

but this does
```
static const char literal[] = "string literal not OK";
std::cout << literal << std::endl;
```

I can't think of any use for a "const char[]" variable with static storage... other than to label a string literal.

**Comment by jwakely** [comment]
@RedDwarf69 

> I can't think of any use for a "const char[]" variable with static storage... other than to label a string literal.

````
const int nbullets = 3;
static const char bullets[nbullets] = { '*', '-', '>' };
...
make_bulleted_list(list_items, bullets[style]);
````

**Comment by RedDwarf69** [comment]
I obviously lack imagination. Yeah...
