### ISSUE TITLE
[request] ES.10: Declare one name (only) per declaration enforcement extension

### ISSUE THREAD

**Issue by omtcyfz** [isocpp/CppCoreGuidelines#770]
Rule ES.10 states

> **Reason** One-declaration-per line increases readability and avoids mistakes related to the C/C++ grammar. It also leaves room for a more descriptive end-of-line comment.

However, the enforcement part only says

> **Enforcement** Flag non-function arguments with multiple declarators involving declarator operators `(e.g., int* p, q;)`

Which leaves out, say

``` c++
int a, b, c;
```

And such. While I can see why code like  `(e.g., int* p, q;)` is especially bad I can totally see why the previous example is also potentially harmful, especially when it comes to using `auto` in C++.

Consider the following piece of code:

``` c++
#include <iostream>
#include <limits>

int get_int() { return 42; }
int get_long() {
  return static_cast<long>(std::numeric_limits<int>::max()) + 1L;
}

int main() {
  const auto a = get_int(), b = get_long();
  std::cout << a << " " << b << " " << std::numeric_limits<int>::max()
            << std::endl;
  return 0;
}
```

Which causes b to be downcasted from `long` to `int`. Thus, similar cases are also very dangerous.

I would also be happy if you could add a simple example like this

``` c++
int a = 42,
    b = 5,
    c;
```

Because it hurts readability.

CERT has very similar [rule](https://www.securecoding.cert.org/confluence/display/c/DCL04-C.+Do+not+declare+more+than+one+variable+per+declaration), which allows few more cases. I'd be happy to extend cppcoreguidelines rule to be a little more strict.

**Comment by AndrewPardoe** [comment]
Per our discussion, "Flag variable declarations with multiple declarators" may be a better phrasing.

**Comment by BjarneStroustrup** [comment]
done
