### ISSUE TITLE
Check "Con.3: By default, pass pointers and references to  const s" doesn't take into account code that calls non-const methods

### ISSUE THREAD

**Issue by Dave-Lowndes** [isocpp/CppCoreGuidelines#773]
The check [Con.3: By default, pass pointers and references to  const s](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-ref) is inappropriate where code has to call non-const methods. For example, Windows code like this using a shell interface IPropertyDescription:

static void ListPropDescription( IPropertyDescription \* pPropDesc )
{
    wchar_t \* pDName = nullptr;
    pPropDesc->GetDisplayName( &pDName );
}

won't compile if the interface pointer parameter is made const.

**Comment by Amaroker** [comment]
There's already a note: "Pass a pointer to non-const should be done only when the called function is supposed to modify the object."

So, unless the object is modified, you should pass it as const.

However, if the object is not modified but the API is lacking const correctness, you need to:
- use const_cast
- ensure safe concurrent access

Well, this is just the default recommendation. You might find it acceptable to leave it as non-const for pragmatic reasons in the context of your application.

**Comment by Dave-Lowndes** [comment]
> You might find it acceptable to leave it as non-const for pragmatic reasons in the context of your application.

Since having to add a const_cast anywhere the pointer is used would be confusing and inelegant, the option to leave the code as it is, is the cleanest one. It's also why this check applied indiscriminately as it is will result in it annoying developers and leading them to regard this (and other checks) as pointless.

**Comment by Amaroker** [comment]
You can simply provide a wrapper function that only calls GetDisplayName and returns the name.

The const cast will only appear once inside that function.

**Comment by rianquinn** [comment]
Would a Linter flag this function at all? I might be missing something, but if GetDisplayName is not marked `const`, then I don't think you could mark `pPropDesc` either, in which case why would this rule apply?

Granted `GetDisplayName` may not supposed to modify anything but if it is not marked as such, you have no way of knowing under the hood what it's going to do and therefor a Linter should not either.

**Comment by AndrewPardoe** [comment]
Per our discussion, we should consider to add a note to the effect of "except when you call `const`-incorrect libraries", also referring to a discussion about how to convert old code.

**Comment by BjarneStroustrup** [comment]
Note added
