### ISSUE TITLE
Con.4: Use  const  to define objects with values that do not change after construction is issued inappropriately

### ISSUE THREAD

**Issue by Dave-Lowndes** [isocpp/CppCoreGuidelines#774]
The check [Con.4: Use  const  to define objects with values that do not change after construction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#con4-use-const-to-define-objects-with-values-that-do-not-change-after-construction) is issued inappropriately with the following code:

static void Fn4()
{
	// Warning	C26496	Variable szBuffer is assigned only once, use const. ( con.4: https://go.microsoft.com/fwlink/p/?LinkID=784969)
	TCHAR szBuffer[_MAX_PATH];
	GetFullPathName( nullptr, _countof( szBuffer ), szBuffer, nullptr );
	LPCTSTR pFilePath = szBuffer;
}

szBuffer can't be made const as GetFullPathName requires a non-const buffer.

**Comment by neilmacintosh** [comment]
Hi @Dave-Lowndes. Again, this looks like a tool-specific bug (assuming that the relevant parameter for GetFullPathName() is declared as a pointer to non-const). I'll close this out and consider it raised with the vendor for resolution ;-)
