### ISSUE TITLE
Move semantics should not allocate resources

### ISSUE THREAD

**Issue by cjdb** [isocpp/CppCoreGuidelines#778]
Does this sound like a reasonable guideline?

------------

Allocating resources (including via `make_unique`, etc.) may be costly*, and can degrade from the benefits of making a move. Since resource allocations can throw, a move constructor should also avoid allocation to ensure that an exception isn't thrown, causing problems with the `noexcept` specifier.

As moved objects are left in an unspecified state, they shouldn't be usable until their state is well-specified.

\* Performance testing necessary.

**Exception**
After rigorous performance testing to invalidate the performance claim above, _or_ when the requirements of an object require it to well-defined at all times (that is, a named object can be used immediately after a move).

**Comment by jwakely** [comment]
I agree that throwing moves should be avoided wherever possible, see issue #231 which already says this should be covered.

> a move constructor should also avoid allocation to ensure that an exception isn't thrown, causing problems with the noexcept specifier.

I don't follow this part, why would it problems with the `noexcept` specifier? If a move constructor throws then you wouldn't make it `noexcept`.

> As moved objects are left in an unspecified state, they shouldn't be usable until their state is well-specified.

This is not accurate, it depends how you want to use them. Many objects are left in completely specified states (e.g. a `unique_ptr` is guaranteed to contain a null pointer after a move) and others can still be used safely (e.g. you can `push_back` into a `vector` that has been moved-from). So this would need to be stated differently.

But I think this can be closed as a duplicate of #231 anyway.

**Comment by cjdb** [comment]
Now that it's been reviewed, it's pretty obvious that this is a snowflake suggestion. Thanks for your input!

Closed.
