### ISSUE TITLE
C.84/85 merge into one rule. Addition of a new C.85 rule

### ISSUE THREAD

**Issue by ginging** [isocpp/CppCoreGuidelines#781]
In my opinion Rule C.84 and C.85 can be merged into one rule as they cover the same issue.
As for a new rule C.85, I would propose one which treats the issue of having a member swap function but not a swap(a, b) function implemented for the same type in the namespace.
This restricts the ADL to find the (hopefully) optimised swap function which would speed up several of the std::algorithms and other libraries.
As an example:

```
namespace ownSwap {
    class Swappable {
        int number;
        void swap (Swappable &other) {
            //swap implementation
        }
    };

    //should be implemented as well
    void swap(Swappable &a, Swappable &b) { 
        a.swap(b);
    }
}
```

**Comment by AndrewPardoe** [comment]
Per our discussion, there are many rules that can be merged. This is an example of where we come at this question from two different ways.
