### ISSUE TITLE
Expects(), Ensures(), and noexcept functions

### ISSUE THREAD

**Issue by JimHewes** [isocpp/CppCoreGuidelines#784]
What am I missing?
It seems that Expects() and Ensures() cannot be used in functions that are marked noexcept since they throw exceptions. (or at least, it triggers a warning on VS2015)
How about defining them in terms of system-specific functions, like _assert() which is what the assert() macro does in VS2015?

Edit: Never mind, I think I posted to the wrong repository. Please delete.

**Comment by neilmacintosh** [comment]
@JimHewes If you're referring to the Microsoft GSL implementation, `Expects()` and `Ensures()` only throw exceptions if you choose to build with a certain set of flags (see the comments at the top of `gsl_assert` for details).

**Comment by rianquinn** [comment]
The explanation of the flags are here:
https://github.com/Microsoft/GSL/blob/master/gsl/gsl_assert#L25

If you have enabled GSL_THROW_ON_CONTRACT_VIOLATION, you cannot use [Expects](https://github.com/Microsoft/GSL/blob/master/gsl/gsl_assert#L63) / [Ensures](https://github.com/Microsoft/GSL/blob/master/gsl/gsl_assert#L66) in a function labeled noexcept without attempting the catch `gsl::fail_fast`
