### ISSUE TITLE
Use memmove/memcpy to do bitwise copying between objects of different types

### ISSUE THREAD

**Issue by DemiMarie** [isocpp/CppCoreGuidelines#785]
`memcpy` has well-defined behavior when copying between pointers of different types.

**Comment by jwakely** [comment]
Is this suggestion in the context of a particular guideline?

N.B. memcpy is only well-defined for trivially-copyable types, not in general.

**Comment by gdr-at-ms** [comment]
In general, I would suggest avoiding any of these functions.  Standard libraries and compilers know when to turn assignments of `std::copy` into those functions.
