### ISSUE TITLE
"F.44 Return a T&":  why no ref-qualifier recommended?

### ISSUE THREAD

**Issue by williamspatrick** [isocpp/CppCoreGuidelines#788]
F.44 gives the following example:

```
class Car
{
    array<wheel, 4> w;
    // ...
public:
    wheel& get_wheel(size_t i) { Expects(i < 4); return w[i]; }
    // ...
};

void use()
{
    Car c;
    wheel& w0 = c.get_wheel(0); // w0 has the same lifetime as c
}
```

Why is there no recommendation to use a ref-qualifier on get_wheel to prevent get_wheel from being used on a temporary?

`wheel& get_wheel(size_t i) & { ... }`

Should this be added to this rule or does it merit its own rule?  I see nothing referencing ref-qualifiers.

**Comment by williamspatrick** [comment]
Example:

```
struct foo
{
    int value = 5;
    int& get_value() & { return value; }
};

int main()
{
    return foo().get_value();
}
```

In GCC 5.4 results in:
```
foo.C: In function ‘int main()’:
foo.C:9:28: error: passing ‘foo’ as ‘this’ argument discards qualifiers [-fpermissive]
     return foo().get_value();
                            ^
foo.C:4:10: note:   in call to ‘int& foo::get_value() &’
     int& get_value() & { return value; }
          ^
```

Removing the ref-qualifier results in a compiling program.

**Comment by cubbimew** [comment]
Why make `std::cout << foo().get_value();` ill-formed? It's not unusual to read from an lvalue result of a function call in the same full-expression. As for returning a reference that outlives the expression, it's part of lifetime safety issues that should be linked in the beginning of F.44, probably to some parts of https://github.com/isocpp/CppCoreGuidelines/tree/master/docs , except the links are... dangling.

**Comment by williamspatrick** [comment]
I'm not suggesting making l-value references ill-formed, only r-value references.  If foo() returns an l-value reference then the l-value specified function will be called.  If foo() returns an r-value reference it is already undefined behavior to call get_value on it.

**Comment by cubbimew** [comment]
I am not sure what you mean by "If foo() returns an l-value reference" - foo() is a prvalue temporary in the example above.

In any case, the suggestion was
> Why is there no recommendation to use a ref-qualifier on get_wheel to prevent get_wheel from being used on a temporary?

and I am pointing out that using `get_wheel` on a temporary is useful, as long as the reference it returns doesn't outlive the temporary (for which the dangling links in the document need to be fixed.)

**Comment by williamspatrick** [comment]
You wrote "It's not unusual to read from an lvalue result of a function call in the same full-expression."  The word lvalue specifically is what made me assume you were talking about something else. 

I re-read object lifetime on temporaries and realize that the 'foo' in your example is valid until the cout full-expression completes, so you are right that it is not ill defined code and always give the correct (and expected?) results. 

The CppCoreGuidelines are also about safety though and it is, in my mind at least, less safe.  The example you gave can also be solved with an overload: int get_value() &&. Correct?

**Comment by williamspatrick** [comment]
Since the F.44 talks specifically about when return by value is undesirable, maybe I have no room to dispute.

**Comment by AndrewPardoe** [comment]
Per our discussion, first we agree with @cubbimew that we do want this on a temporary. Also, in general we agree that ref qualifiers can be useful but we find them unteachable. We want these rules to be reasonably simple. We recommend all sorts of advanced features but the usability of ref qualifiers causes us to shy away from these changes.

**Comment by jwakely** [comment]
In other words, ref-qualifiers have their uses, but those uses are far less frequent than many people think.

**Comment by Talkless** [comment]
I would like some guidelines on ref-qualifiers as returning reference seems _dangerous_ in for loops.
Consider this `Widget`:
```
class Widget {

public:
    explicit Widget(std::int64_t number) : m_foo{std::to_string(number)} {}
    const std::string &getFoo() const noexcept { return m_foo; }

private:
    std::string m_foo;
};
```
Then, maybe you have some (helper) functions that return that `Widget`:
```
Widget makeWidget(int a, int b) {

    return Widget{std::int64_t{a} * b};
}
```
Let's assume that `getFoo()` returns big heavy object so you need to return reference to avoid costly copies. And then you write ranges-base for loop like this:
```
int main()
{
    for (char c: makeWidget(1234567890, 1000000000).getFoo()) {
        std::cout << c << '\n';
    }
}
```
This is UB as `Widget` temporary is destroyed after that expression, and you gonna loop trough `std::string` instance, accessed via reference, which is already destroyed. Fix is either to delete `&&` ref-qualified overload or to implement moving-one:
```
class Widget {

public:
    explicit Widget(std::int64_t number) : m_foo{std::to_string(number)} {}

    const std::string &getFoo() const & noexcept { return m_foo; }
    std::string getFoo() && noexcept { return std::move(m_foo); }

private:
    std::string m_foo;
};
```
