### ISSUE TITLE
C.10: Clarify title

### ISSUE THREAD

**Issue by severinmeyer** [isocpp/CppCoreGuidelines#793]
The current title of [C.10](http://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c10-prefer-a-concrete-type-over-more-complicated-classes) is:
**C.10: Prefer a concrete type over more complicated classes**

However, without the explanatory text, it is not clear what "complicated classes" means.

I therefore propose the more descriptive title:
**C.10: Prefer concrete types over class hierarchies**

**Comment by AndrewPardoe** [comment]
Thank you! We discussed this long ago but I missed making the update. I've changed the document now.
