### ISSUE TITLE
Possible contradiction between ES.5 and ES.40

### ISSUE THREAD

**Issue by severinmeyer** [isocpp/CppCoreGuidelines#797]
[ES.5: Keep scopes small](http://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es5-keep-scopes-small)

    // good: pc is local to if-statement
    if (auto pc = dynamic_cast<Circle*>(ps))

[ES.40: Avoid complicated expressions](http://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es40-avoid-complicated-expressions)

    // bad: assignment hidden in subexpression
    while ((c = getc()) != -1)

Both examples showcase a similar approach, i.e. conditional(boolean(assignment))), one slightly more verbose than the other. It is not immediately clear to me at what point this approach turns from good to bad.

**Comment by galik** [comment]
To my mind putting function calls with *out-parameters* or *assignments* inside `if`, `for` or `while` loops is *idiomatic*. It can save repeating a statement which is better maintenance. It's made obvious by ysing surrounding *parens* which also functions to tell the compiler not to issue a warning (because it is deliberate).

**Comment by cubbimew** [comment]
> Both examples showcase a similar approach, i.e. conditional(boolean(assignment)))

the first one is not an assignment, it is a declaration, of the kind that exists specifically to keep the scopes small. The scope of `c` in the second example is larger than it needs to be (although I feel that idiomatic C I/O loop is not the best demo of a complicated expression)

**Comment by severinmeyer** [comment]
Yes, you are right. Though to be honest, I thought the `= ...` part is an assignment within the declaration.

In any case, the quoted examples are still similar enough to make it difficult to understand why one is recommended practice, while the other is deemed too complicated. So maybe all that is needed is a more explicit definition of *complicated*.

**Comment by lbrandy** [comment]
We just discussed this and most were in fairly vigorous agreement with @cubbimew. The tightly scoped declaration in the first example is specifically the intention here. The second statement isn't, doesn't, tightly scope some variable... and it's not great for other reasons related to complexity. 

> So maybe all that is needed is a more explicit definition of complicated.

I don't think anyone is opposed to this its just unclear to me how we might do that w/o causing a new argument. PR?
