### ISSUE TITLE
Document that 1 liner code to converting an std::istream to std::string is slow.

### ISSUE THREAD

**Issue by AraHaan** [isocpp/CppCoreGuidelines#798]
I noticed when I tested that 1 liners that would allow someone to convert ``std::istream`` to ``std::string`` is 4~6x slower than making an override version of ``std::to_string()``. Code I used is below I would be very happy if this was added to the header file that impliments ``to_string`` into the standard because it would become very useful instead of having to manually override for it.

```cpp
#include <string>
#include <fstream>

namespace std
{
	std::string to_string(std::istream &in)
	{
		std::string ret;
		char buffer[4096];
		while (in.read(buffer, sizeof(buffer)))
		{
			ret.append(buffer, sizeof(buffer));
		}
		ret.append(buffer, in.gcount());
		return ret;
	}
}
```

So, yeah not only can it help those who use ``istream`` and then want to convert the contents of it to ``std::string`` Although then again it could be possible to ``reinterpret_cast`` it.

**Comment by cubbimew** [comment]
>  I would be very happy if this was added to the header file that impliments to_string into the standard 

Are you making a suggestion for a new C++ standard library component? The procedure for doing that is outlined at https://isocpp.org/std/submit-a-proposal

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion, @AraHaan, and the clarification, @cubbimew! Closing this as it's not directly related to the Guidelines.
