### ISSUE TITLE
Proposal: SF rule - don't use unscoped "using namespace x;" in header files

### ISSUE THREAD

**Issue by iso8859-1** [isocpp/CppCoreGuidelines#805]
**Reason**
The problem with unscoped "using namspace x;" is that they import all the symbols from namespace x into every file that is including the header file for unqualified lookup. This can cause unwanted collisions.

**Note**
explicitly mention the provide the namespace instead of using unqualified lookup. Alternatively scope the using-directive.

**example bad:**

```
#include <vector>
using namespace std;
 
vector<int> foo();
```

**example, good:**

```
#include <vector>

std::vector<int> foo();
```

**Enforcement**
This can easily be detected by static code analysis

**Comment by scraimer** [comment]
IIRC this is already detected by clang with `-Wheader-hygiene`, so "**can be** easily detected" can be changed to "**there exist** [compilers and] static analysis tools to detect this"

**Comment by iso8859-1** [comment]
correct: http://clang.llvm.org/docs/DiagnosticsReference.html#wheader-hygiene
didn't know of that.

**Comment by AndrewPardoe** [comment]
FYI, SF.7 mentions this in headers.

**Comment by iso8859-1** [comment]
agreed. It could be more detailed about scoping, but essentially this is the issue.
