### ISSUE TITLE
Add a guideline for separating declarations from definitions of class/function templates

### ISSUE THREAD

**Issue by daviddoria** [isocpp/CppCoreGuidelines#806]
I see many projects do something like this:

MyClass.h
--------------
    #ifndef MyClass_H
    #define MyClass_H

    template <typename T>
    class MyClass
    {
      void foo();
    };

    #include "MyClass.hpp"
    #endif

MyClass.hpp
--------------
    #ifndef MyClass_HPP
    #define MyClass_HPP

    template <typename T>
    void MyClass::foo()
    {
      // do something
    }

    #endif

I believe this is identical to the compiler as:

MyClass.h
--------------
    #ifndef MyClass_H
    #define MyClass_H

    template <typename T>
    class MyClass
    {
      void foo()
      {
        // do something
      }
    };

    #endif

but the idea seems to be to mirror the separation of declarations/definitions in non-template .h/.cpp pairs.

This guidelines document seems to be a great place to have experts comment on this style - care to weigh in?

**Comment by cubbimew** [comment]
Wouldn't "impl" headers only make it harder to switch to using modules?

**Comment by daviddoria** [comment]
It's super hard to see the interface "at a glance" with the template implementations inline with their declarations though, no? That is, it is a really nice feature of a .h (in a .h/.cpp non-template pair) that you can just see what the class does without caring about how it does it. This goes away entirely unless you have a .h/.hpp template pair.

**Comment by MikeGitb** [comment]
> Wouldn't "impl" headers only make it harder to switch to using modules?

Why?

**Comment by cubbimew** [comment]
> Why?
It was mentioned at Manuel Klimek's CppCon16 talk; such headers don't compile on their own

**Comment by MikeGitb** [comment]
@cubbimew: I'd have to re watch the talk, but I'm pretty sure, it is not an issue. The important thing is that you can create an empty cpp file, include MyClass.h and the result will compile. In particular, you don't need to include any other headerfile before or after MyClass.h.

**Comment by lbrandy** [comment]
We just discussed this and the general consensus was that this falls too close to style arguments to be appropriate for the guidelines.

**Comment by lbrandy** [comment]
Re: modules transition.

IMO, when transitioning a large codebase to use modules, this pattern is a bit harmful, but not insurmountable. It's just a generally useful assumption by e.g. the build system that every header is separably compilable. So this pattern is something you'd need to teach your build system about. In the post-modules world, this discussion is hopefully obviated entirely.
