### ISSUE TITLE
Suggested rule: unused parameters should be unnamed

### ISSUE THREAD

**Issue by neilmacintosh** [isocpp/CppCoreGuidelines#808]
The feature to allow parameters to be declared without names was added to the language to allow a simple way to express that a parameter was not going to be used in a function.

Rather than the myriad other schemes that have come into existence for marking a parameter unused (macros, attributes, casting to `void` etc), using the simple technique of omitting a parameter name should be the preferred option for C++ code.

**Comment by gdr-at-ms** [comment]
Agreed.  This is described as general technique in TC++PL4, section12.1.2.

**Comment by BjarneStroustrup** [comment]
Just FYI: allowing parameters to be unnamed was introduced in the early 1980 to address this problem :-)
