### ISSUE TITLE
question: SF.7 "Don't put using..." true only for using namespace 

### ISSUE THREAD

**Issue by MikeMitterer** [isocpp/CppCoreGuidelines#810]
OK - it's clear why `using namespace` in .h-files should be avoided  but how about something like this?

```cpp
using NCWindow = std::shared_ptr<WINDOW>;
```

**Comment by gdr-at-ms** [comment]
Rule SF.7 talks about "using directives".  What you show above is a type alias declaration, it is no different from writing `typedef std::shared_ptr<WINDOW> NCWindow;`.  In fact, declarating a type alias via `using` is the prefer notation.
