### ISSUE TITLE
C.36 should mention the case of logging

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#813]

**Comment by cubbimew** [comment]
The case of logging (I am guessing it refers to libraries such as [boost.log](https://github.com/boostorg/log/blob/master/include/boost/log/sources/record_ostream.hpp#L520) or  [galera](https://github.com/codership/galera/blob/3.x/galerautils/src/gu_throw.hpp#L65)) is really just a special case of a destructor of a temporary exiting by exception, although the only non-logging real life example I can point to is [SOCI](https://github.com/SOCI/soci/blob/master/src/core/once-temp-type.cpp#L38) which can throw from the dtor in e.g. `sql << "select count(*) from invoices", into(count)`

**Comment by neilmacintosh** [comment]
I don't see any need to mention an exception in C.36. If a particular logging class library feels there is strong need to have destructors that throw, then it would be appropriate for them to explain/justify that (unusual) design. The general applicability of the rule stands.  If enforcement tools are used that enforce C.36, then this is a good case for a suppression with comment.
