### ISSUE TITLE
`owner`-like aliases for F.52 and F.53

### ISSUE THREAD

**Issue by mpark** [isocpp/CppCoreGuidelines#816]
[F.52](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-reference-capture) and [F.53](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-value-capture) recommend declaring the lambda captures according to how it will be used by the function (locally or non-locally).

Documenting how it will be consumed by the function at the interface-level seems like it would be as useful as marking pointers with `owner`.

Given the following aliases:
```cpp
template <class F> using local = F;
template <class F> using nonlocal = F;
```

We could capture the consumption intent of the function in its the interface:
```cpp
template <class RandomIter, class Compare>
void sort(RandomIter first, RandomIter second, local<Compare>);

template <class Function, class... Args>
std::future<std::result_of_t<Function(Args...)>>
async(nonlocal<Function&&> f, Args&&... args);
```

This annotation should also provide tooling with more information for enforcement.

**Comment by mpark** [comment]
cc @neilmacintosh

**Comment by SirRade** [comment]
Off topic, you might be interested in [this](http://stackoverflow.com/questions/213121/use-class-or-typename-for-template-parameters)

**Comment by cubbimew** [comment]
Slightly less remote off-topic,[ F.54](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f54-if-you-capture-this-capture-all-variables-explicitly-no-default-capture) needs to mention the new `[*this]` capture

**Comment by viboes** [comment]
@mpark Could you clarify the kind of enforcements the tools could require for local/non-local functions?

**Comment by mpark** [comment]
@viboes: I don't know concretely. At a high-level, I was thinking that given `nonlocal<T>`,
one could analyze `T` along with lifetime tracking (using the same system as for
`shared_ptr` lifetime tracking?) to determine whether it is indeed feasible as a non-local function.

Anyway, I mainly suggested this as a way to more clearly declare the intent of the interface.
