### ISSUE TITLE
Pro.safety Type.3: Don't use const_cast

### ISSUE THREAD

**Issue by a-n-t-h-o-n-y** [isocpp/CppCoreGuidelines#817]
The [last example](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-330) (putting common code in a helper function template), is unhelpful if the function needs to return any member data. In the example the function is static, if you instead make this non-static and const, you end up having to use a const_cast in order to return any data as non-const.

I'm fairly new to C++ so maybe there is something I am missing.

**Comment by a-n-t-h-o-n-y** [comment]
The example in question:
```
class Foo {
public:                         // good
          Bar& get_bar()       { return get_bar_impl(*this); }
    const Bar& get_bar() const { return get_bar_impl(*this); }
private:
    Bar my_bar;

    template<class T>           // good, deduces whether T is const or non-const
    static auto get_bar_impl(T& t) -> decltype(t.get_bar())
        { /* the complex logic around getting a possibly-const reference to my_bar */ }
};
```

**Comment by jwakely** [comment]
> is unhelpful if the function needs to return any member data

It works fine, that's exactly what the example is demonstrating! The "complex logic" in this case could be simply `return t.my_bar;` which accesses member data.

> if you instead make this non-static and const

Don't do that then. It's static for a reason.

If changing the wording code makes it stop working, don't change it.

**Comment by a-n-t-h-o-n-y** [comment]
Thank you! I see my misunderstanding now.
