### ISSUE TITLE
Overview of Tools implemeting Checks for various guidelines

### ISSUE THREAD

**Issue by JonasToth** [isocpp/CppCoreGuidelines#819]
Hi,

Are you aware of a list/overview of rules that are already checkable by tools?
It would be niche to have a "implemented in ..." Part in rules to see what can be done for codebases with CI for example.

**Comment by AndrewPardoe** [comment]
Per our meeting, we don't want to become the maintainers of what rules are implemented where, nor judges of what rule enforcements are implemented sufficiently well. 

We will consider creating a list of what we consider to be the minimum set of rules to be enforced.

**Comment by JonasToth** [comment]
Ok. :)
I think the already existing profiles are somewhat core checks and reasonable to 'demand' from tools, arent they?

**Comment by neilmacintosh** [comment]
@JonasToth Speaking as a tool vendor, I think it's definitely reasonable for users to expect that support. :-) The profiles are a good start to the list Andrew mentioned, but they are focused by topic. There are other good, simple rules in the guidelines that could make it to a "minimum useful" list.

**Comment by JonasToth** [comment]
@neilmacintosh I try out my luck on clang-tidy, and would like to contribute usefull stuff as well.
Maybe there is a way of some coordination on that?
I believe that the gsl::owner<> - support would be really valueable (and partly easy).

If there is intrest, i would love to put a list together and ask the clang - community what they think about as well.
