### ISSUE TITLE
Acronyms should be made explicit at first use

### ISSUE THREAD

**Issue by rivokl** [isocpp/CppCoreGuidelines#820]
Acronyms should be made explicit/spelled out at first use in order to (help) make the document as self-contained as possible. For example TS is not explicitly defined before first use ("Use the ISO Concepts TS style of requirements specification"). And/or a link maybe? There are also ISO, ABI but they seem clear enough ...

**Comment by MikeGitb** [comment]
I'd agree for the introduction and maybe the philosophical rules, but the other parts are afaik not really meant to be read from start to end. So putting those abbreviations into the glossary and linking to it might be more helpful.

**Comment by AndrewPardoe** [comment]
Thanks, this is a good suggestion. We should add those definitions to the Glossary, making instances of TS, ISO, ABI, etc. into links into those definitions. Would one of you like to prepare a PR?

**Comment by BjarneStroustrup** [comment]
improving the glossary is a good idea. "first use" is not very meaningful in a hyperlinked document.

**Comment by AndrewPardoe** [comment]
Lacking a PR, I've made some additions to the glossary myself. Thanks, all!
