### ISSUE TITLE
Suggestion : Change the way various section acronyms are specified

### ISSUE THREAD

**Issue by sivaraam** [isocpp/CppCoreGuidelines#826]
In the _CppCoreGuidelines.md_ file, the abbreviations of various sections are stated explicitly. They could possibly be made implicit by emphasising the portions of the section titles that denote the abbreviations.
<table>
    <tr>
        <th>Number</th>
        <th>Syntax</th>
        <th>Rendition</th>
    </tr>
    <tr>
        <th>1</th>
        <td>[In: Introduction](#S-introduction)</td>
        <td><a href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-introduction">In: Introduction</a></td>
    <tr>
        <th>2</th>
        <td>[*In*troduction](#S-introduction)</td>
        <td><a href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-introduction"><i>In</i>troduction</a></td>
    </tr>
    </tr>
    <tr>
        <th>3</th>
        <td>[**In**troduction](#S-introduction)</td>
        <td><a href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-introduction"><b>In</b>troduction</a></td>
    </tr>
    <tr>
        <th>4</th>
        <td>[***In***troduction](#S-introduction)</td>
        <td><a href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-introduction"><b><i>In</i></b>troduction</a></td>
    </tr>
</table>

In the above table **1** is currently used. I thought it the alternatives like **2**, **3** or **4** (i like the **3**, more than the others) would be a good choice as they imply the abbreviations directly. This could be make it easy to find the sections as the names would align to the left allowing for easily scanning through the section names as they align in order regardless of the length of the abbreviations.

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion! We've discussed this and prefer not to rely upon typography to highlight the abbreviation. Consider, for example, what happens when someone reformats this document into, for example, a local wiki or a PDF file.
