### ISSUE TITLE
GSL.view lists `owner<T&>`

### ISSUE THREAD

**Issue by hpesoj** [isocpp/CppCoreGuidelines#835]
I assume this is a mistake? The guidelines state that "References are never owners." and I've certainly never seen ownership transferred by reference.

**Comment by johelegp** [comment]
"References are never owners" refers to plain old `T&` references, just like a `T*` is never an owner. This means that you shouldn't `delete` them.

It is totally valid to have an owning reference `owner<T&>`, and use it like an `owner<T*>`, with the same differences between a `T&` and a `T*` (`.` access instead of `->`, no rebinding, etc.)

**Comment by hpesoj** [comment]
Is there a precedent for this? It just seems plain wrong.

**Comment by hpesoj** [comment]
It's just that I thought references were like the safe part of C++, and now they can carry ownership? Seems like a pretty huge can of worms to be opening.

**Comment by cubbimew** [comment]
References were never safe: they have many opportunities to outlive the objects they refer to (returning a local variable by reference, holding a reference to an element of a vector and doing `push_back`, binding to `std::max(x,y+1)`, etc.

Perhaps `owner<T&>` deserves a few words somewhere. The Lifetimes paper only mentions it once in the sentence "binding a reference to x is still a T& (not an owner<T&>)"

**Comment by hpesoj** [comment]
I probably didn't mean "safer". More like, easier to understand, less surprising, more predictable. Where did the idea of references carrying ownership come from? I've never ever seen anything like this:

    T& r = *(new T);
    delete &r;

Code like this just smells to me. What is the benefit? Why not just recommend using pointers?

**Comment by hsutter** [comment]
Agreed, `owner<T&>` is a mistake, removed. Thanks.

**Comment by hsutter** [comment]
And added @cubbimew's comments in the text.
