### ISSUE TITLE
C.50 why is the example factory returning std::shared_ptr?

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#836]
in [C.50: Use a factory function if you need "virtual behavior" during initialization](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-factory) and the corresponding [discussion ](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Sd-factory), a factory is shown returning `std::shared_ptr`. What is the other owner it is sharing ownership with?

Should it not be returning `std::unique_ptr<D>` per [F.26: Use a unique_ptr<T> to transfer ownership where a pointer is needed](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-unique_ptr) or even `gsl::not_null<std::unique_ptr<D>>` ([I.12: Declare a pointer that must not be null as not_null](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-nullptr))?

**Comment by jwakely** [comment]
Yes, good point.

**Comment by hsutter** [comment]
`shared_ptr` is appropriate when you know the object will be shared. Will update C.50 to capture that, and add xrefs.
