### ISSUE TITLE
C.62 Simple Enforcement (yes, marked incomplete), Issues with.

### ISSUE THREAD

**Issue by anand-hariharan** [isocpp/CppCoreGuidelines#838]
The essence and most of what what is stated under C.62 is valid.  That said, I would like to raise a couple of issues with it:

1. The case against check for self-assignment is made primarily on performance grounds.  Just prior to that, a categorical statement "[Check for self-assignment] _is obviously safe and apparently efficient._" is made; I have my doubts.  James Kanze has made posts on c.l.c++ (or c.l.c++.m, I do not recall), as to where the self-assignment check could fail (e.g., for virtual base classes).  This was a long time ago, and possibly when compilers weren't as thorough or conformant as they are now.  Please confirm the veracity of "_obviously safe_".

2. There is no mention of copy-and-swap idiom in the entire guideline.  C.60 shows an example that is close to the copy-and-swap idiom.  However, it receives by const reference and creates a copy, while it could just as well receive by value (i.e., copy).  Again, there seems undue (my opinion, of course) emphasis on performance.  IMHO C.60 needs revision, but this git-hub issue is not with C.60!

3. A [website](http://en.cppreference.com/w/cpp/language/copy_assignment) talks about the different forms of the copy-assignment operator.  I am interested in what the web-site considers as case #2. This is more a question -- In light of my first concern above reg. dubiousness of self-assignment-check, how do I implement an assignment operator **without** copy-and-swap (e.g., in case of abstract classes)?

Thank you for your time,

**Comment by cubbimew** [comment]
> [A website](http://en.cppreference.com/w/cpp/language/copy_assignment) talks about the different forms of the copy-assignment operator

better link is its [operator overloading page](http://en.cppreference.com/w/cpp/language/operators#Assignment_operator ) (which discusses copy-and-swap vs separate overloads)

**Comment by hsutter** [comment]
Re 1: Yes, it's safe.

Re 2, 3: Copy-and-swap isn't mentioned here just because it isn't always available (not all types support efficient move and/or `swap`) and it isn't necessary in this example.
