### ISSUE TITLE
SF.x should there be a rule to avoid transitive standard library includes?

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#841]
Would this make a useful rule?

> Include the correct header for every standard library component used in the program.  Do not rely on transitive inclusion.

I think it stands the chance of being enforceable if a tool knows what header which standard library symbol "officially" belongs to - it's not that big of a database.

Reasons why this is a problem:

1. `#include <iostream>` exposes the definition of `std::string` ("why?" makes for a fun trivia question), but it is not required to do so by transitively including the entire `<string>` header, resulting in the popular beginner question "why doesn't `getline(cin, str)`; work?" or even an occasional "strings cannot be compared with ==, use str.compare" - "yes they can" - "no, it doesn't compile!"
2. Lots of real-life code uses `size_t` without bothering to include one of the [six headers](http://en.cppreference.com/w/cpp/types/size_t) where it is guaranteed to be defined. At one point recently gcc's libstdc++ dropped a transitive inclusion of `stddef.h` somewhere and dozens of opensource packages failed to compile. As a Gentoo enthusiast, I remember having to patch quite a few of them locally just to update the system compiler.

(not suggesting to apply this to non-standard libraries because of how common it is to have a user-facing header that just further includes fine-grained or implementation-detail headers)

**Comment by MikeGitb** [comment]
I'd very much like to have  such a rule and in particular a tool that tells me which headers I'm missing. 
But just to be clear: We are not talking about outlawing indirect inclusion of standard library headers via your own headers right?

**Comment by cubbimew** [comment]
> We are not talking about outlawing indirect inclusion of standard library headers via your own headers right?

Personally I would (and that would even make the tool's job for detecting this issue much easier), but technically that would be a different rule with different motivation.. and since Code Guidelines are supposed to be about the way we want to see code written five years from now, I'd rather see guidelines for Modules instead.

**Comment by MikeGitb** [comment]
I'm not certain that this would make it easier for tooling (at least if you want to avoid false positives). While the standard makes it absolutely clear that you should not rely on one header exporting another, it is much less clear if a normal headerfile exposes a standard headerfile deliberately or by accident. E.g. think about precompiled headers, the header file of a class or libraries that use standard library types in their API.

But as you said, this will (hopefully) get better in the future.

**Comment by BjarneStroustrup** [comment]
done
