### ISSUE TITLE
Should there be a F.X for static functions

### ISSUE THREAD

**Issue by tlanc007** [isocpp/CppCoreGuidelines#842]
Should the guidelines have some mention on static functions?

Something to the effect that they should be avoided and a namespace is probably a cleaner way to go?

**Comment by cubbimew** [comment]
Do you mean choosing between the (formerly-deprecated) static keyword and an anonymous namespace when defining a function with internal linkage?

**Comment by gdr-at-ms** [comment]
It is unclear what the suggestion is.  Please re-open if you have more information.
Eventually we would look into issues related to static objects.
