### ISSUE TITLE
Use of int, size_t, std::size_t or a custom class?

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#848]
I cannot find a clear guideline about the use of size types.
Should I use int, size_t, std::size_t or a custom class?

I've observed:

 * No guideline in the CppCoreGuidelines yet
 * References [1-9] to Stroustrup and Lakos also seems to hint to prefer int
 * Jon Kalb [10] recommends using `int` for qualities.
 * Jason Turner [11] uses `size_t`
 * `std::size_t`/`size_t` is a typedef for unsigned int in my C++ STL
 * All these are type sinks: a number of sheep is something different then the number of generations a simulation should run

I am just a novice programmers that would advocate to 

 * use `int` over `size_t` and `std::size_t` as it looks simpler, avoid arithmetic with mixed types
 * if needed, create datas type like 'number_of_sheep' and 'number_of_generations' that store the number as an int. These two types cannot be added

What are your thoughts about this?

## References

 * [1] John Lakos. Large-Scale C++ Software Design. 1996. ISBN: 0-201-63362-0. Chapter 9.2.2: 'Avoid using unsigned in the interface; use int instead'
 * [2] Joint Strike Fighter Air Vehicle C++ Coding Standards for the System Development and Demonstration Program. Document Number 2RDU00001 Rev C. December 2005. AV Rule 163: 'Unsigned arithmetic shall not be used.'
 * [3] Bjarne Stroustrup. The C++ Programming Language (3rd edition). 1997. ISBN: 0-201-88954-4. Chapter 4.10 'Advice', item 18: 'Avoid unsigned arithmetic'
 * [4] Bjarne Stroustrup. The C++ Programming Language (3rd edition). 1997. ISBN: 0-201-88954-4. Chapter 4.4 'Integer types': 'Using an unsigned instead of an int to gain one more bit to represent positive integers is almost never a good idea. Attempts to ensure that some values are positive by declaring variables unsigned will typically be defeated by implicit conversion rules'
Bjarne Stroustrup. The C++ Programming Language (3rd edition). 1997. ISBN: 0-201-88954-4. Chapter    * [5] 4.10 'Advice', item 19: 'View signed to unsigned and unsigned to signed conversions with suspicion'
* [6] C++ FAQ Lite. [29.12] What's the point of the L, U and f suffixes on numeric literals?: 'It's probably a good idea to use unsigned integers for variables that are always >= 0. [...] at least if you are careful to check your ranges'
 * [7] C++ FAQ Lite. [29.12] What's the point of the L, U and f suffixes on numeric literals?: 'If you end up using unsigned variables, it is generally a good idea to force your numeric literals to also be unsigned'
 * [8] Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 6.6. Advice. page 169: '[9] Prefer plain char over signed char and unsigned char'
 * [9] Bjarne Stroustrup. The C++ Programming Language (4th edition). 2013. ISBN: 978-0-321-56384-2. Chapter 6.6. Advice. page 169: '[10] Beware of conversions between signed and unsigned types'
 * [10] [CppCon 2016: Jon Kalb “unsigned: A Guideline for Better Code"](https://youtu.be/wvtFGa6XJDU?t=5m59s)
 * [11] [One of Jason Turner's video's](https://www.youtube.com/watch?v=iCL6GYoi1RU)

**Comment by jwakely** [comment]
I think [ES.102](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-signed) already covers whether to use a signed or unsigned type.

Sometimes it does make sense to use distinct types for different quantities, especially if they are associated with some dimension (e.g. a units library should not allow a number of metres to be added to a number of seconds). But in many programs that's overkill, a number of sheep and a number of generations are both dimensionless quantities, and it might be necessary to multiply them to get another dimensionless quantity. I don't know if a general-purpose guideline for this is appropriate.

**Comment by richelbilderbeek** [comment]
Thanks for pointing me to ES.102.

And I do agree that making classes can indeed be overkill. Boost.Units has a nice trick to allow to  distinguish dimensionless units that I would prefer myself.

But what about `std::size_t`/`size_t`?

**Comment by jwakely** [comment]
What about them? They are two different names for the same unsigned type.

**Comment by richelbilderbeek** [comment]
I agree. I just hope to stop wondering if these names should be preferred over `unsigned int`.

**Comment by jwakely** [comment]
`std::size_t` is the type used for result of the `sizeof` operator, which is not necessarily `unsigned int` (and definitely isn't on my machines). You should not use `siez_t` as a general replacement for `unsigned int`. I suggest taking this to somewhere like StackOverflow.

**Comment by richelbilderbeek** [comment]
I *know* what it is. I just hoped this guideline would give some guidance about its use. Too bad this remains in the dark, but thanks for your time.
