### ISSUE TITLE
Testing is unimportant?

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#849]
Beyond the C++ introduction books, testing is seen as vital to ensure high quality. There are even methodologies (e.g. Test-Driven Design) based on testing.

Does testing not have a place in these guidelines?

**Comment by jwakely** [comment]
"The guidelines are focused on relatively higher-level issues, such as interfaces, resource management, memory management, and concurrency. Such rules affect application architecture and library design."

This doesn't replace testing.

**Comment by richelbilderbeek** [comment]
I hope I get this right: 'This doesn't replace testing' == 'This doesn't include testing.'?

For example, a rule that could be suggested 'Make functions testable'. This is not directly about testing, but it does already improve the application architecture, even without a testing harness. Sure, it has some overlap with many other rules already ([F 8. Prefer pure functions](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-pure), but I would agree with such a rule being added.

**Comment by cubbimew** [comment]
1. There already is a guideline requesting design for testability [P.6: What cannot be checked at compile time should be checkable at run time](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rp-run-time) - that's actually a strong guideline if you really follow it; you can't for example check if an iterator is reachable from another, so it requires ranges, not iterator pairs.
2. There are also rules suggesting making contracts (Expects/Ensures) explicit (I.5 through I.8)

There could be a guideline for making all (salient) class states observable for test drivers. What else would be suitable as a "core", cross-industry guidelines?

**Comment by jwakely** [comment]
I mean that _how_ to do your testing is outside the scope of the guidelines. But you should still test your software, following the guidelines doesn't make testing unnecessary.

But intentionally twisting your APIs to make them testable by some particular methodology is not universally seen as good practice. I don't think "Make functions testable" is a good guideline, unless you define "testable" and recommend a particular style of testing it's too vague to be useful.

**Comment by richelbilderbeek** [comment]
Thanks for convincing me this subject is covered already well enough :+1: .
