### ISSUE TITLE
GSL is not unique

### ISSUE THREAD

**Issue by markthornton** [isocpp/CppCoreGuidelines#851]
There is also a Gnu Scientific Library which puts headers in gsl/
Many other languages have guidelines that reduce or prevent such clashes. Is it too late for C++?

**Comment by BjarneStroustrup** [comment]
It is too late, and we always knew that there were many GSLs out there. All the good TLAs are taken and we hope that there isn't much scope for confusion because all of the GSLs we know of are in different domains.

**Comment by jwakely** [comment]
The domain doesn't really matter when the expected header path is `<gsl/gsl_foo>`, which both that GSL and this GSL use.

I think it will work in practice because this GSL doesn't use a `.h` suffix on its files, whereas the GNU Scientific Library does use suffixes, so names should remain unique.
