### ISSUE TITLE
Should C.64 ("move should move") discourage move that swaps?

### ISSUE THREAD

**Issue by cubbimew** [isocpp/CppCoreGuidelines#852]
It is sometimes convenient to implement move operations as swaps. For example, this was the case for std::string's move assignment in GNU libstdc++ 4.x and 5.x:

```
#include <iostream>
#include <utility>
#include <string>
 
int main()
{
    //  the moved-from object is NOT empty in gcc 4.x and 5.x
    std::string str1 = "Hello";
    std::string str2 = "Good-bye";
    std::cout << "Before move from str2, str2 = '" << str2 << "'\n";
    str1 = std::move(str2);
    std::cout << "After move from str2, str2 = '" << str2 << "'\n";
}
```
[Live demo on wandbox](http://melpon.org/wandbox/permlink/OERX8J45eh9iX0wb) 

While often convenient to implement, I feel this breaks user expectations: if the lhs of assignment held a resource, it's still being held after the assignment, until the rhs gets destroyed. It might even change hands again if the rhs is later move-assigned to.

Would it be appropriate to add a small note to [C.64: A move operation should move and leave its source in a valid state](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-semantic) discouraging that practice? Or would you say it doesn't matter since we're not supposed to use std::move all that much anyway ([ES.56](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-move))?

(note this has nothing to do with copy-and-swap assignment, which, when called with rvalue rhs, does not modify the argument in the caller's scope)

**Comment by jwakely** [comment]
It's still the case today for GCC's COW std::string: http://melpon.org/wandbox/permlink/xc7g9hjKlFwDO9gg

> if the lhs of assignment held a resource, it's still being held after the assignment, until the rhs gets destroyed.

And that's precisely the point of doing it: you don't throw away memory that can be reused if the RHS gets assigned to. I could be persuaded that the we should do `rhs.resize(0)` before returning, but that would still leave `rhs.capacity()` as non-zero, i.e. the resource is still held.

For types that manage an object, such as `unique_ptr` and `shared_ptr` it certainly makes sense to ensure the previous value is not preserved beyond when users would expect it to be destroyed (and the standard guarantees that). But for a sequence of allocated bytes in a `std::string` I think it's far less clear that it should be discouraged.

**Comment by cubbimew** [comment]
> you don't throw away memory that can be reused if the RHS gets assigned to

huh, okay, that does kinda makes sense, thanks.
