### ISSUE TITLE
ES.6 should be updated to reflect C++17's if-statement and switch-statement

### ISSUE THREAD

**Issue by cjdb** [isocpp/CppCoreGuidelines#856]
Currently, ES.6 reads

> ES.6: Declare names in for-statement initializers and conditions to limit scope

Both GCC 7 and Clang 3.9+ support C++17 initialiser statements.

## Proposed resolution

ES.6: Declare names in selection statement and for-statement initializers and conditions to limit scope.

**Note**

C++17 introduces initializer statements for `if`-statements and `switch`-statements, which are present in GCC 7 and Clang 4 with the `-std=c++1z` flag.

**Comment by hsutter** [comment]
Looks good but we'll massage the text as we want to keep C++17-specific features distinct for now until people have broad access to compilers that support them.
