### ISSUE TITLE
I.7 example of buffer clearing is harmful and incorrect

### ISSUE THREAD

**Issue by sstewartgallus** [isocpp/CppCoreGuidelines#858]
The code is just plain wrong:
~~~
void f()    // better
{
    char buffer[MAX];
    // ...
    memset(buffer, 0, MAX);
    Ensures(buffer[0] == 0);
}
~~~
First of all, only testing the first byte will just mean that only the first byte will be cleared. Second of all `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` can be defined and so the `memset` will be wrong anyway. The appropriate thing to do is to use `memset_s`. However, the approach is flawed anyway because in general modern processors and operating systems can and do cache anything and everything. If you want memory isolation the appropriate thing to do is spawn a separate OS process handle the security functionality there and then exit it.

**Comment by MikeGitb** [comment]
FYI: Zu https://github.com/isocpp/CppCoreGuidelines/issues/11

**Comment by galik** [comment]
Isn't it enough to make the buffer clearing function opaque by putting it in its own translation unit so that the optimizer can't second guess its utility?

**Comment by jwakely** [comment]
`memset_s` is not in the C++ standard library, and not provided by most C implementations.

@gallik, no, not with link-time optimisation.

Closing as a dup of #11
