### ISSUE TITLE
C.21 is broken for constexpr destructors

### ISSUE THREAD

**Issue by gnzlbg** [isocpp/CppCoreGuidelines#863]
constexpr destructors must be implicitly generated, so following rule 21 and defining a destructor (e.g. by defaulting it) prevents it from being constexpr.

**Comment by MikeGitb** [comment]
Unless I misunderstand what you mean by a constexpr destructor I think you are mistaken. This is imho perfectly fine: 

    struct A {
      ~A() = default;
    };
    constexpr A a{};

AFAIK a defaulted constructor doesn't qualify as user defined.

**Comment by gnzlbg** [comment]
Indeed, this destructor is `user-declared` and `implicitly-generated` and thus is `constexpr`. Only `user-**provided**` destructors cannot be constexpr. 

Thanks, TIL. I had mixed up. I thought that `user-declared` constructors could not be constexpr.

**Comment by gnzlbg** [comment]
FWIW this seems like a bug in clang-trunk, since gcc 7 accepts this code. 

See: https://godbolt.org/g/00MQI8
Clang bug report: https://bugs.llvm.org//show_bug.cgi?id=32215
