### ISSUE TITLE
Avoid reinterpret cast when sharing data-layouts

### ISSUE THREAD

**Issue by gnzlbg** [isocpp/CppCoreGuidelines#864]
Is there a way of doing the following in a type-safe way (e.g. without reinterpret cast)?  

```c++
struct base {};

struct bar : private base {
  using base::base;
  using base::operator=;
  // some imports
  // some new methods
};

struct foo : private base {
  using base::base;
  using base::operator=;
  // some imports and some new methods

  // constructor from bar
  explicit constexpr foo(bar const& v) noexcept
   : base(reinterpret_cast<base const&>(v)) {}
};

int main() { return 0; }
```

I don't see how using a variant would help here.

**Comment by jwakely** [comment]
This seems more like a stackoverflow question, is it related to one of the guidelines?

**Comment by gnzlbg** [comment]
The type safety profile does not allow using reinterpret cast and I am
trying to enable it but it doesn't tell me what to use instead.

**Comment by jwakely** [comment]
So don't write code that has to use `reinterpret_cast` to access private bases. If you want to share the base between classes, don't use private inheritance.

**Comment by jwakely** [comment]
"Doctor, doctor, it hurts when I do this"
"So don't do that"

**Comment by gnzlbg** [comment]
I guess that my question would then be: "How I do reuse data-layout and some functionality without adding implicit conversions to base classes (e.g. using public inheritance) and without boiler plate (e.g. using a data member)" , but that is indeed better suited for stackoverflow, sorry for the noise.

**Comment by gnzlbg** [comment]
Also, I still need to figure out a way to use `std::aligned_storage` for anything useful without using `reinterpret_cast`, but maybe `aligned_storage` is inherently type-unsafe, and no code that depends on it can be made type-safe ?

**Comment by jwakely** [comment]
````
std::aligned_storage<sizeof(T)>::type buf;
T* p = new(static_cast<void*>(&buf)) T;
````
Now you have a `T*` which can be used safely. You only need `reinterpret_cast` to recover a `T*` from the raw buffer, but if you're doing that then you're giving up type-safety.

**Comment by gnzlbg** [comment]
Yes, I have a `static_vector` implemented as: `std::aligned_storage_t<sizeof(T), alignof(T)>::type data[N];`, to implement, e.g.,`data()` I need to recover a `T*` from the raw buffer. 

For a single element that's neat, it was one of the things preventing me from implementing `std::variant` using `aligned_storage`. TIL thanks!
