### ISSUE TITLE
span::size_bytes() signed return type

### ISSUE THREAD

**Issue by djarek** [isocpp/CppCoreGuidelines#866]
Hi, I'm wondering what is the motivation behind ```span::size_bytes()``` returning a signed size? Wouldn't it be more consistent with the rest of the language if it actually returned something like ```std::size_t```? As it is now it's a little awkward to use, e.g. in serialization code when one needs to use a ```gsl::narrow_cast()``` to compare the size of a span against the size of a type:
```cpp
bool read(uint64_t& output, gsl::span<const byte>& input) {
  if (input.size_bytes() < gsl::narrow_cast<std::ptrdiff_t>(sizeof(output))) {
    // premature EOF
    return false;
  }
  //deserialize in a portable way
  // ...
  input = input.subspan(sizeof(output));
  return true;
}
```

**Comment by jwakely** [comment]
See [ES.100](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-mix) and [ES.101](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-unsigned) and [ES.102](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-signed).

**Comment by MikeGitb** [comment]
There have also been some discussions about this at the gsl repo. E.g.: https://github.com/Microsoft/GSL/issues/322.

Concerning this particular problem: I'm often using an [`as_bytes(output)` helper function](https://github.com/Microsoft/GSL/pull/374/files) which takes care of taking the size internally (just realized, that it might need a `narrow_cast` internally).

**Comment by djarek** [comment]
Okay, now it makes sense. Still, very annoying, but what can you do :D.
