### ISSUE TITLE
Span proposal, range checking: P0122R4.pdf 

### ISSUE THREAD

**Issue by galik** [isocpp/CppCoreGuidelines#868]
I was reading the standards proposal for `std::span` and I was curious about the bounds checking:

>**Range-checking and bounds-safety**
>
>All accesses to the data encapsulated by a span are conceptually range-checked to ensure they remain within the bounds of the span. What actually happens as the result of a failure to meet span’s bounds-safety constraints at runtime is undefined behavior. However, it should be considered effectively fatal to a program’s ability to continue reliable execution. This is a critical aspect of span’s design, and allows users to rely on the guarantee that as long as a sequence is accessed via a correctly initialized span, then its bounds cannot be overrun.
>
>As an example, in the current reference implementation, violating a range-check results by default in a call to terminate() but can also be configured via build-time mechanisms to continue execution (albeit with undefined behavior from that point on).

If any out-of-bounds access is deemed *undefined behavior* then how is that any different from accessing (say) a `std::vector` directly where out-of-bounds access is **already** *undefined behavior*?

What exactly has `std::span` added there?

Bounds checking with functions like `std::vector::at` gives *well defined behavior* so you can programatically recover from out-of-bounds access  with the assurance that no *undefined behavior* took place. Shouldn't `std::span` do something similar here? Otherwise its out-of-bounds checking doesn't seem any different from not having out-of-bounds checking at all, you simply get *undefined behavior* which is what you get when you don't check anything.

**Comment by jwakely** [comment]
It clearly says that violating a range-check calls terminate() in the reference impl.

> What exactly has `std::span` added there?

It's not supposed to replace `std::vector`, it's supposed to replace raw pointers.

Accessing through a span is an assertion that the access is in range. If you want to be able to programmatically recover then don't make that assertion, add your own checks.

Undefined behaviour means the implementation can do range-checking and handle it however it sees fit, like terminating, or something else such as removing all checks when explicitly told to do so. Specifying that range-checking always happens, with defined semantics, doesn't allow that freedom. Requiring the same behaviour as `vector::at()` and supporting recovery means you always pay for the checking.

If an implementation of `span` failed to do range checking by default you should complain to the vendor of that implementation. That's not a problem with the core guidelines or the design of `span`.

**Comment by CaseyCarter** [comment]
This language was stronger in older versions of the proposal, back in the `array_view` days:

> All accesses to the data encapsulated by an `array_view` are range-checked to ensure they remain within the bounds of the `array_view`. Any failure to meet `array_view`’s bounds-safety constraints will result in a call to `std::terminate()` (a “fail-fast” approach to safety). This is a critical aspect of `array_view`’s design, and allows users to rely on the guarantee that as long as a sequence is accessed via a correctly initialized `array_view`, then its bounds cannot be overrun.

It was later relaxed to UB for out-of-range access leaving behind this odd "conceptually range-checked" language which has no real normative teeth. I assume (I wasn't there, and I never asked @neilmacintosh) that LEWG wanted the type and extent of range checking to be left to QoI and/or be tunable, for which UB is the best normative choice.

**Comment by neilmacintosh** [comment]
So the language isn't really *that* odd. It's a section of the paper that gives background and design rationale, not wording for the standard ;-)

@CaseyCarter correctly guesses that LEWG didn't want to mandate range-checking in the standard. UB is the standard way of saying "you're on your own if you do this", so we went with that, and it certainly doesn't prohibit range-checking. It gives implementations more latitude about how they range-check and what they do with failures (terminate/throw/order cake/email your family...). That lets `span` be immediately useful in the real world.

I think @jwakely has interpreted things exactly right, and lays out our approach much better than I can (but I'll repeat it badly here anyway ;-)).

We want to be clear to users that the right way to think about `span` is that it is range-checked. When someone uses `span`, they opt into the view that an out-of-bound access is an end-of-the-world moment. 

The key difference from `vector` (in terms of range-checking) is that the *API* you use with `span` does not allow you to pick-and-choose change whether accesses are being range-checked in your implementation.

That is very important. It makes "assume it is range-checked" that default mental model. It also encourages tooling to do a good job, as for the most robust development experience, people will choose an implementation and tooling that enforces range-checks and does so as efficiently as possible.

**Comment by neilmacintosh** [comment]
I think we've discussed and clarified this now, so closing the issue out.
