### ISSUE TITLE
Do =default destructors lead to violations of C.21 ?

### ISSUE THREAD

**Issue by jbcoe** [isocpp/CppCoreGuidelines#870]
**C.21 If you define or =delete any default operation, define or =delete them all**

states:

Reason:
The semantics of the special functions are closely related, so if one needs to be non-default, the odds are that others need modification too.
<https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#reason-76>

and:

Enforcement:
A class should have a declaration (even a =delete one) for either all or none of the special functions.
<https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enforcement-71>

clang-tidy has a check, cppcoreguidelines-special-member-functions, <https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html>

which currently (by default) warns on

```
struct A
{
  virtual ~A() = default;
};

class 'A' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
```

Is this correct behaviour? It follows the enforcement rule (which talks about declarations) but not the reason (which talks about non-default functions). 

There's an LLVM bug raised against this: https://bugs.llvm.org/show_bug.cgi?id=31858

I'm not trying to be pedantic here. Either behaviour is possible to implement but I want to ensure we're following the intent of C.21.

**Comment by cubbimew** [comment]
cppreference specifically mentions the virtual destructors under [Rule of Zero](http://en.cppreference.com/w/cpp/language/rule_of_three#Rule_of_zero) 

> When a base class is intended for polymorphic use, its destructor may have to be declared public and virtual. This blocks implicit moves (and deprecates implicit copies), and so the special member functions have to be declared as defaulted

this was popularized by Scott Meyers in [A Concern about the Rule of Zero](http://scottmeyers.blogspot.fr/2014/03/a-concern-about-rule-of-zero.html)

**Comment by jbcoe** [comment]
Some further thought:

```
struct A
{
  virtual ~A() = default;
};
```

is not innocuous. As @cubbimew says it prevents compiler-generation of moves and deprecates copies. This is dangerous as many (most?) compilers will continue to generate copy-constructors but not move-constructors, producing potentially inefficient code.

What's more a virtual destructor, or protected destructor, implies that the class will be a base class of an inheritance hierarchy in which case copies and moves will slice derived objects. I think the enforcement rule is sensible, declare all five or none and make intent explicit.

I suggest changing the 'reason' text to read:

"The semantics of the special functions are closely related, so if one needs to declared, the odds are that others need consideration too."

**Comment by jbcoe** [comment]
The code below illustrates the issue with writing `=default` on a destructor.

```
#include <iostream>
#include <vector>

struct S { 
  S(const S&) { std::cout << "Copied an S\n"; }

  S(S&&) { std::cout << "Moved an S\n"; }

  S() = default;
};

struct A { 
  S s;
};

struct B { 
  S s;
  ~B() = default;
};

int main(int argc, char* argv[]) {
  std::vector<A> vas;
  std::cout << "push A() into a vector of A's\n";
  vas.push_back(A());
  
  std::vector<B> vbs;
  std::cout << "push B() into a vector of B's\n";
  vbs.push_back(B());

  return 0;
} 
```

**Comment by jbcoe** [comment]
Are there any further thoughts on this issue?

**Comment by jwakely** [comment]
I assigned the issue to myself, and I think I had further improvements in mind  that never happened, sorry. I think your suggestion of s/non-default/declared/ and s/modification/consideration/ is definitely better than the current text. Would it also help to add something about your example? Maybe in (or after) the note that starts _"If you want a default implementation of a default operation ...", or in the **Reason** section. I'll create a pull request ...

**Comment by jwakely** [comment]
Huh, I can't add the example, because it violates [C.67 A base class should suppress copying, and provide a virtual clone instead if "copying" is desired](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-copy-virtual).
