### ISSUE TITLE
ES.31 needs more discussion

### ISSUE THREAD

**Issue by AlexanderLanin** [isocpp/CppCoreGuidelines#872]
In my opinion [ES.31](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es31-dont-use-macros-for-constants-or-functions) needs additional explanation regarding e.g. RAM, CPU, time of computation etc for *macro* vs *const* vs *constexpr* **regarding constants**.

Isocpp blog recently linked [this stackoverflow question](http://stackoverflow.com/questions/42388077/constexpr-vs-macros), however it lists only some *high level* differences. More subtle ones **may** be increased/decreased RAM usage (yes I'm talking about 4 bytes here), in case computations are done at compiletime / runtime there may be a small impact on cpu time and on results for float computations - but I may very well be wrong here. I'm not at expert.

**Comment by jwakely** [comment]
> In my opinion ES.31 needs additional explanation regarding e.g. RAM, CPU, time of computation etc for macro vs const vs constexpr regarding constants.

Why? There is no difference between them in terms of RAM, CPU or computation time. The differences are the ones already listed in ES.31, not the ones you mention.

**Comment by BjarneStroustrup** [comment]
agree with jwakeley

**Comment by AlexanderLanin** [comment]
Thank you very much for your feedback and sorry for my long response time. I've been trying to produce any difference myself, but was unable to.
I may be the only one asking that question here but it actually came independently from different colleagues while I showed them ES.31. So maybe you could add such a remark/note to the rule as you stated above?
