### ISSUE TITLE
I.12, F.23 If a pointer can't be null, why not just reference?

### ISSUE THREAD

**Issue by allyusd** [isocpp/CppCoreGuidelines#873]
I.12: Declare a pointer that must not be null as not_null
F.23: Use a not_null<T> to indicate that "null" is not a valid value

I have question, if a pointer can't be null, why not just reference?
I missing something about pointer and reference meaning?

**Comment by jwakely** [comment]
You can't change what a reference is bound to, but you can change what a pointer points to. So there are other differences apart from just allowing null.
