### ISSUE TITLE
F.9: Unused parameters should be unnamed, why don't remove it?

### ISSUE THREAD

**Issue by allyusd** [isocpp/CppCoreGuidelines#874]
F.9: Unused parameters should be unnamed, why don't remove it?

Maybe don't want to change function signature, or something others?

**Comment by jwakely** [comment]
Yes, you might have a fixed API and the parameter is no longer needed, but you don't want to change the API. Or you might have a virtual function that overrides a function from the base class, so the signature must be the same, but one of the overrides doesn't use the parameter. You can't remove it, or you won't override the same function.

````
struct NonAbstractBase {
  virtual bool doSomething(int) { return false; }
};

struct Derived : NonAbstractBase {
  void doSomething(int x) override { return x > 10; }
};
````
The base class doesn't use the parameter, but removing it would change the interface.

These kind of questions are more appropriate for somewhere like StackOverflow.
