### ISSUE TITLE
F.21: To return multiple "out" values, prefer returning a tuple or struct, it's not self-documenting

### ISSUE THREAD

**Issue by allyusd** [isocpp/CppCoreGuidelines#875]
F.21: To return multiple "out" values, prefer returning a tuple or struct

A return value is self-documenting as an "output-only" value, but it also make problem.

Consider this:
```
// ???
bool foo(const obj& input, bool& isLogin, bool& isOnline);

// bad
tuple<bool, bool, bool> foo(const obj& input);

// maybe? need check struct
struct FooData
{
    bool isLogin;
    bool isOnline;
}

tuple<bool, FooData> foo(const obj& input);
```

Return tuple value without name, it's not self-documenting.

**Comment by BjarneStroustrup** [comment]
Agree with jwakely. His example is an example of a source of bugs that is a major reason for the rule.

**Comment by MikeGitb** [comment]
I do believe return values are usually to be prefered over out parameters, but I also agree with allyusd that returning a `pair` or `tuple` is all but self documenting (in particular the then following calls to `foo.first` / foo.second`). 
Could we have a recommendation to prefer structs with actual named members over the more generic pair/tuple?

**Comment by arvidn** [comment]
@MikeGitb I believe the "self documenting" refers to whether it's an "in", "in/out" or "out" parameter.

To provide names that the compiler will help you use correctly, probably a better suggestion would be to use:

```
enum class login_state { logged_on, logged_off };
enum class online_state { online, offline };

std::pair<login_state, online_state> foo();
```

which I believe is covered by P.1

**Comment by jwakely** [comment]
Right. As I already said:

> With return values it is clear they're out parameters, i.e. it's self-documenting.

It doesn't mean that returning something rather than taking out parameters documents _every aspect_ of the function and its behaviour. I thought that was obvious. It means it's clear that the return value is the output, whereas an out parameter isn't clear at the call site.

> returning a pair or tuple is all but self documenting (in particular the then following calls to foo.first / foo.second`).

Nobody is claiming that returning tuples documents the meaning of the tuple elements. And nobody forces you to refer to `foo.first` or `foo.second`:

````
iterator pos;
bool inserted;
std::tie(pos, inserted) = c.insert(x);
````

Or in C++17:

````
auto [pos, inserted] = c.insert(x);
````

You still need to know the order of the members of the return type to do this, but even returning a struct with named fields doesn't solve the problem completely:

````
auto foo = c.insert(x);
if (foo.???)
  // ...
````
You still need to consult the function's documentation (or the struct's documentation) to know what to do with it. Simply returning a struct instead of a pair or tuple doesn't make it self-documenting either. But in any case, that's unrelated to F.21.

**Comment by MikeGitb** [comment]
@arvidn: That is certainly the intent, but imho it falls short. In particular - as @allyusd has rightly observed -  the examples bring advantages on one side,, but have drawbacks on the other, which makes the overall rule less convincing to some people.

And while enums are a nice way to replace bools, flags and a few other types, there is e.g. afaik no easy way to replace an int or a string with a more descriptive type (and there should be no need to do so). It also doesn't solve the `foo.first` / `foo.second` "problem" - not to mention the pretty verbose syntax for tuples.

**Comment by MikeGitb** [comment]
@jwakely: With a struct I get a simple autocomplete hint.

**Comment by MikeGitb** [comment]
And it is relevant to F.21, because it is related to the examples shown there and the preferred alternative to having multiple output parameters.

**Comment by djarek** [comment]
@MikeGitb 
Another place where tuples/pair have an advantage is in metaprogramming - it is sometimes necessary to "unpack" the returned values of one function into the arguments of another:
```cpp
template <typename... Ts>
std::tuple<Ts...> generator();
// ...

//Function from another library:
template <typename... Ts>
void consumer(Ts&&... args);

template <typename Callable,  typename... Ts>
void composed_operation(Callable consumer)
{
  apply(consumer, generator<Ts...>());
}
```
Though I agree that the tuple syntax is a little bit arcane.

**Comment by MikeGitb** [comment]
I'm not saying that a pair/tuple should not be used (also think about something like `split`), just that structs should be preferred by default.

**Comment by djarek** [comment]
Saying "tuples should be preferred by default" or "structs should be preferred by default" is IMO way too vague in this context. I think that a distinction should be made - if the values returned from a function are only related within the context of the function call, then using a tuple makes sense, e.g.
```
std::tuple<buffer, error_code> read();
```
I think is a lot better than the alternative:
```
struct  read_result{
  buffer buf;
  std::error_code error;
}
read_result read();
```
Obviously there are examples where tuples are actually harmful, after all, you wouldn't want ever to see something like this:
```
using buffer = std::tuple<std::vector<std::byte>, std::vector<std::byte>::iterator>;
```

**Comment by arvidn** [comment]
@MikeGitb 
> And while enums are a nice way to replace bools, flags and a few other types, there is e.g. afaik no easy way to replace an int or a string with a more descriptive type (and there should be no need to do so).

I disagree with that. There is absolutely a need to use specific types, just like ``Month`` in P.1 along with ``std::chrono::duration`` and ``std::chrono::time_point``. I would not make sense to recommend *less* type safety. I take it your argument is based on your intellisense providing better support for in/out parameters, that still doesn't seem like a reason to dismiss proper type safety.

returning a struct with named fields won't help you avoid binding the results to incorrectly named variables at the call site when using structured binding, only distinct types will.
