### ISSUE TITLE
Provide enforceable rules that guarantee the absense of data races

### ISSUE THREAD

**Issue by DemiMarie** [isocpp/CppCoreGuidelines#878]
It would be nice to have enforceable rules that guarantee the absence of data races.  This is because data races are (to my knowledge) one of the last remaining sources of undefined behavior that is not detectable by one of the other profiles.  (Integer overflow and various It would be nice to provide Rust’s ironclad guarantee that **safe programs cannot go wrong**: bugs in safe libraries and programs cannot invoke undefined behavior.  In this context, “safe” roughly means “conforms to these guidelines, specifically the ones that can be enforced by automated tools”.

**Comment by MikeGitb** [comment]
That would certainly be nice, but is that even possible without switching to Rust's ownership model and using their annotations? I might be wrong, but I think that in c++ a tool has - in general - no chance to know if data is shared between two or more threads and/or if certain objects are threadsafe.

But maybe it is possible to translate at least parts of rusts semantics/features to c++. I don't know enough about rust to make any proposal there though

**Comment by hsutter** [comment]
Discussed by editors: The general topic of data race detection/prevention is a research project. We're doing work on a subset of it which is lifetime safety (dangling/null deref).
