### ISSUE TITLE
P.9 examples are improveable

### ISSUE THREAD

**Issue by a-teammate** [isocpp/CppCoreGuidelines#879]
As I'm reading this to learn to make better use of the stdlib but as well to improve my code I stumbled across this example:

> Example, bad
> 
> void lower(zstring s)
> {
>     for (int i = 0; i < strlen(s); ++i) s[i] = tolower(s[i]);
> }
> Yes, this is an example from production code. We leave it to the reader to figure out what's wasted.

Every time somewhere is written `We leave it to the reader` they mean: `this is actually more complex, you'll need some more knowledge to grasp it. We didn't find a catchy sentence which explained it.`

No example would have been better than this example.
(Besides that this is actually a pretty explosive topic dealing with string conversations without locals, but `::tolower` is equally sensitive to that. A std::transform would only mean you use iterators of the unknown zstring, so that would neither tell you correct multibyte support. My point is: what is the correct example here in the authors opinion?).

-- 
For the first example of P.9 theres no corrected version it's just stated that:

> Yes, this is a caricature, but we have seen every individual mistake in production code, and worse. Note that the layout of X guarantees that at least 6 bytes (and most likely more) are wasted. The spurious definition of copy operations disables move semantics so that the return operation is slow (please note that the Return Value Optimization, RVO, is not guaranteed here). The use of new and delete for buf is redundant; if we really needed a local string, we should use a local string. There are several more performance bugs and gratuitous complication.

Imo the first sentence is totally useless here. Only giving the impression "beware, you can do so much wrong. And we'll laugh at you.". People are here to learn.

**Comment by jwakely** [comment]
There's nothing complex about the "We leave it to the reader" example, it just wastes a lot of time calling `strlen` on every iteration. I don't think it's referring to `std::transform`, don't over-think it.

The guidelines are not meant to be a tutorial teaching C++ to beginners, and this is from the philosophy section talking about wasting time & space in a high-level way, not dealing with specific technical matters. It's saying not to waste cycles and bytes, that's all.

**Comment by a-teammate** [comment]
Ah okay, i overlooked that one. kk, saw it. shame on me.

However the other issue i thought about here is something not addressed in the guidelines yet: The issue of assuming ASCII input or the locale problem in general.
Did I just missed the paragraph? Or should I open another issue? In my experience that's sometimes troublesome (mostly because everything is working perfectly on your English dev pc but as you ship it.. forcing a local is the easy fix, but bears its very own flaws)

**Comment by AndrewPardoe** [comment]
Thanks for the suggestion and the great discussion. Closing this issue based on @jwakely's comment.
