### ISSUE TITLE
CP.23, CP.24, CP.25 & CP.26 consistency and numerical order

### ISSUE THREAD

**Issue by galik** [isocpp/CppCoreGuidelines#881]
**CP.23** uses `gsl::rai_thread` as its example of a *joining thread*.

**CP.24**, however, uses `std::thread` followed by calls to `detach()` as its example of a *detached thread*.

To be consistent would it be better if *both* examples use `std::thread` and call `join()` and `detach()` or (my preference) if they should each use `gsl::raii_thread` and `gsl::detached_thread` respectively?

Also would it be better if **CP.25** & **CP.26** came *before* **CP.23** & **CP.24** as they explain what `gsl::raii_thread` & `gsl::detached_thread` do? It may be better to explain them *before* the examples that use them.

**Fore reference:**
[CP.23](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-join): Think of a joining thread as a scoped container
[CP.24](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-detach): Think of a detached thread as a global container
[CP.25](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-raii_thread): Prefer gsl::raii_thread over std::thread unless you plan to detach()
[CP.26](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconc-detached_thread): Prefer gsl::detached_thread over std::thread if you plan to detach()

**Comment by galik** [comment]
Also I notice that some examples in this section use namespace prefixing `std::thread` & `gsl::raii_thread` whereas other examples omit namespace qualification using `thread` & `raii_thread`. Which is correct? Should all names be qualified or do we assume the relevant namespace is available?

**Comment by AndrewPardoe** [comment]
Thanks for noticing this! Yes, your improvement would be good. However, people rely on these numbers and link into them directly. We prefer not to reorder rules.
