### ISSUE TITLE
Suggestion to use containers to manage `raii_threads`

### ISSUE THREAD

**Issue by galik** [isocpp/CppCoreGuidelines#882]
* [CP.??: Use a container to manage your `raii_thread` objects](#Rconc-contain)

##### Reason

A container provides a place to keep your threads without having to create spurious variable names. A forgotten name creates a *temporary* which will not execute in parallel but will still appear to work. Also it gives you a nice way to control the scope of your `raii_threads` without having to add explicit scope operators `{ }`.

##### Example

```cpp

// bad

{ // start a new scope
    gsl::raii_thread t1([&]{ std::sort(a, b); });
    gsl::raii_thread   ([&]{ std::sort(b, c); }); // oops, accidental temporary, runs serially
    gsl::raii_thread t3([&]{ std::sort(c, d); });
    gsl::raii_thread t4([&]{ std::sort(d, e); });
}

// good

// a container to manage the scope of parallel running threads
std::vector<gsl::raii_thread> threads;
threads.reserve(4);

// everything in the vector runs in parallel
threads.emplace_back([&]{ std::sort(a, b); });
threads.emplace_back([&]{ std::sort(b, c); });
threads.emplace_back([&]{ std::sort(c, d); });
threads.emplace_back([&]{ std::sort(d, e); });

// clearing the elements makes the running threads block
// waiting to join
threads.clear();

// vector `threads` is now available for the next batch of parallel jobs

threads.emplace_back([&]{ std::inplace_merge(a, b, c); });
threads.emplace_back([&]{ std::inplace_merge(c, d, e); });
threads.clear();

std::inplace_merge(a, c, e);

```

**Comment by galik** [comment]
This can be made even nicer with a little template function to create an array of `raii` jobs:
```cpp
template<typename... Funcs>
void parallel_invoke(Funcs... funcs)
{
    gsl::raii_thread a[]{gsl::raii_thread{funcs}...};
}

void parallel_sort(std::vector<int>& v)
{
    auto a = std::begin(v);
    auto b = a + (v.size() / 4);
    auto c = b + (v.size() / 4);
    auto d = c + (v.size() / 4);
    auto e = std::end(v);

    parallel_invoke(
        [&]{ std::sort(a, b); },
        [&]{ std::sort(b, c); },
        [&]{ std::sort(c, d); },
        [&]{ std::sort(d, e); }
    );

    parallel_invoke(
        [&]{ std::inplace_merge(a, b, c); },
        [&]{ std::inplace_merge(c, d, e); }
    );

    std::inplace_merge(a, c, e);
}
```

**Comment by MikeGitb** [comment]
I'm not sure, if I'd really endorse this. Spawning many identical threads at the same point is imho a design smell. In most cases, one should prefer to work on a higher level of abstraction by either using a parallel algorithm or packaging the work into tasks that are then executed by a thread pool (e.g. std::async).

Managing `std::thread`s should ideally only be necessary if one actually needs concurrency (not just parallelism) in which case one tends to have dedicated threads for different purposes, or when writing writing one's own thread pool (which should be rare).

Also the fact that `clear()` means `join_all()` is a little too clever for my taste - but that is certainly a matter of opinion..

What imho does merit a guideline is the part that an raii_threads must be assigned to a named variable (similar to the result of std::async) which may or may not be an array. This can then also easily be checked by tools.

**Comment by MikeGitb** [comment]
I'd love to have the `parallel_invoke` from your example in the standard library or gsl though (with the ability to specify an execution policy similar to the parallel algorithms)

**Comment by hsutter** [comment]
Editor discussion: We should make sure there is a general rule somewhere against a statement that is only an unnamed temporary -- that's almost certainly unintentional.

**Comment by hsutter** [comment]
Note that C++17 guaranteed copy/move elision allows this style where you can't get it wrong:

    auto t2 = gsl::raii_thread([&]{ std::sort(b, c); }); // cannot forget the variable name

**Comment by AndrewPardoe** [comment]
This sample may make a valuable addition to the ES section. Maybe ES.84 so that it is next to ES.85?

**Comment by BjarneStroustrup** [comment]
ES.84 banning "unnamed local variables" added
