### ISSUE TITLE
Suggestion to "E.28: Avoid error handling based on global state (e.g. errno)"

### ISSUE THREAD

**Issue by Fearguz** [isocpp/CppCoreGuidelines#883]
Hello All,

The problem with the E.28 rule is that, it is pretty common to mix C++ code with calls to 3rd party libraries written in the old ANSI C (posix would be a good example). If the external library provides an errno-like error handling mechanism, a developer is not able to avoid errno in his program, so a rule like "errno shall be avoided" does not really solve the problem.

I would suggest to slightly reformulate the rule. Functions that provides error handling mechanism based on a global state shall be isolated from other modules of C++ programs so the errno is never propagated outside the wrapper function (it means the errno does not need to be checked anywhere in the project besides such wrappers). If a project allows exceptions, then the errno error message/code could be mapped to suitable std::system_error exception in order to propagate it back to the caller function.

**Comment by hsutter** [comment]
Note there is a cross-reference to E.25 which is the actionable item that includes discussion of what to do. The E section hangs together and should be read together.

We don't want to discourage using modern C++ error handling, including exceptions. However, for legacy/interop uses you can consider `system_error` as well as various proposals of nonstandard wrapping solutions. It is a problem today that there are too many ways of handling errors.
