### ISSUE TITLE
F.52, though correct, is a source of errors for the unweary

### ISSUE THREAD

**Issue by xtofl** [isocpp/CppCoreGuidelines#884]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f52-prefer-capturing-by-reference-in-lambdas-that-will-be-used-locally-including-passed-to-algorithms

Capturing by reference has lead to many, many problems (dangling references) in our codebase when the 'locality' of the passed in objects was misjudged.

I think it would be wise to rephrase this guideline inversly.

When you're sure that the lambda is local (e.g. the `algorithms`), capture by reference.

The only provided example covers the most dangerous use case, multithreading.  A simple use case with `transform` or `generate` may be more appropriate, and the fact that it also works for the parallel algorithms is worth noting.

Also, I'm not sure how this relates to the mentioned 'correctness'.

**Comment by Fearguz** [comment]
@xtofl I agree with what you wrote, and I do subscribe to the question.

Also, I would like to add that under the https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f16-for-in-parameters-pass-cheaply-copied-types-by-value-and-others-by-reference-to-const rule it is written:

> Enforcement
> (Simple) ((Foundation)) Warn when a parameter being passed by value has a size greater than 4 * sizeof(int). Suggest using a reference to const instead.

I think this concerns variables captured by lambda expressions too. I would definitely capture _std::int8_t_ by copy, and not by reference to const.

**Comment by xtofl** [comment]
@Fearguz that's a great idea.  I'll add F.16 as a 'see also' to the topic.

**Comment by AndrewPardoe** [comment]
Herb, per our weekly discussion, could you please take a stab at improving F.52?

**Comment by hsutter** [comment]
Also incorporating the suggested example from PR #885, thank you.
