### ISSUE TITLE
How to include a header file?

### ISSUE THREAD

**Issue by viboes** [isocpp/CppCoreGuidelines#886]
I don't see a guideline about when to use 

```
#include "file.h"
```

or 

```
#include <file.h>
```

I use to use the last so that I can stub, fake or mock a header file by just selecting the folder with `-I`.

What is the advice of the C++ core guidelines contributors?

**Comment by galik** [comment]
I always used `#include "file.h"` for headers files that are part of the same project and `#include <file.h>` for headers that are installed elsewhere on the system. I believe `#include "file.h"` searches the current directory first so it picks up files relative to the location of the current header file before looking elsewhere. That is ideal for project header files. On the other hand `#include <file.h>` looks at system default locations first.

**Comment by Fearguz** [comment]
It is implementation-defined how the preprocessor identifies header files.

> A preprocessing directive of the form
> # include < h-char-sequence> new-line
> searches a sequence of implementation-defined places for a header identified uniquely by the specified sequence between the < and > delimiters, and causes the replacement of that directive by the entire contents of the header. How the places are specified or the header identified is implementation-defined.
> A preprocessing directive of the form
> # include " q-char-sequence" new-line
> causes the replacement of that directive by the entire contents of the source file identified by the specified sequence between the " delimiters. The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read
> # include < h-char-sequence> new-line
> with the identical contained sequence (including > characters, if any) from the original directive. [from C++

However, the Standard says also:

> [ Note: Although an implementation may provide a mechanism for making arbitrary source files available to the < > search, in general programmers should use the < > form for headers provided with the implementation, and the " " form for sources outside the control of the implementation. For instance:
> #include <stdio.h>
> #include <unistd.h>
> #include "usefullib.h"
> #include "myprog.h"
> —end note ]

**Comment by viboes** [comment]
@galik Do you use to mock the files in your projects? If yes, how do you reach to do it?

**Comment by viboes** [comment]
@Fearguz I was not aware that the search was implementation defined and that there couldn't be any differences.

Does it means that the standard cannot ensure in a portable way which file is included if the files have the same name?

**Comment by galik** [comment]
@viboes I have not used mocking much tbh. Looking at the current standard the `#include` directive does allow `MACROS` to be used which get substituted before the *include* is processed so you could implement mocking that way I suppose.

The original Kernighan & Ritchie `C` programming book suggested that `#include "file.h"` should search the current directory first before checking the implementation defined search order. Every compiler I have used has honored that tradition. I think the main reason the current standard shies away from being too specific is to allow implementation to use non-traditional file systems.

For example in the past I programmed for the `RISC OS` operating system which did not support file name extensions because file system uses the *period* `'.'` as the directory separator. So the *include* directives were transposed from `"filename.h"` to `"h.filename"` and the headers were stored in a subdirectory called `"h"`.

**Comment by Fearguz** [comment]
@viboes That's right, standard does not define how the search should be implemented. The only difference between include<> and include "" is that, the include "" falls back to include <> if fails.
So I would say it is definitely not portable. To be sure that correct files are included, you need to specify all include paths in the compiler's configuration or include a file with its directory specified, e.g. include <the/path/file.h>.

You can take a look at the working draft of the C++ Language Standard (from November 2014): http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf. The working draft is free.

**Comment by viboes** [comment]
I guess the C++ Core Guidelines couldn't help here then, isn't it?

**Comment by MikeGitb** [comment]
Afaik the semantics are pretty portable across the major compilers. I guess the question is: What is the Problem you want to address here?

So far the maintainers have avoided to talk about things like source code organization and I'm not sure, if there are good, general rules.

**Comment by viboes** [comment]
My intent was to get good advice from this community on when to use one or the other way to include a file.

I find it easier and less intrusive to mock files that are included using <> and making use of the  compiler flag -I to flip to a mock directory. 

If I organize my files as

```
include/
  component/
    file.h
tests/
  my_test/
    test1.cpp
    mock
      component/
        file.h
```

Then I include the file file.h as 

```
// component/anotherfile.cpp
#include <component/file.h>
//...
```
I can choose the mock files by adding -Itests/my_test/mock

Maybe others have a better solution. How people are mocking files with classes that don't use dynamic polymorphism? How do they replace the class declaration/definition?

When a file depends on another file and the definition of this file is not subject to be mocked I could accept including it using 

```
// component/annotherfile.h
#include "file.h"
//...
```

but I would need to change the inclusion if one day I decide to mock the file `component/file.h`.

I don't know how to mock a file included using  

```
#include "file.h"
```
without changing it and using conditional compilation, which is IMO intrusive. 

```
// file.h
#ifdef MOCK_COMPONENT_FILE
#include <mock/component/file.h>
#else
// real declaration/definition
#endif
```
BTW, if I cannot change the file.h contents (3pp), I must include it using <>. 

Maybe I'm wrong. I would like to learn what is the better way to do it.

P.S. I'm asking here because I want to make this an internal guideline for the project I'm working on, but want first to check what others are doing.   

P.S.S. Please close this issue if it is out of the scope of this repository.

**Comment by AndrewPardoe** [comment]
Thanks, all, for the discussion. Closing this issue based on the information from @Fearguz. Piotr, thank you for the reference in the Standard!

**Comment by viboes** [comment]
Given that the inclusion order is implementation defined, does it means that there is no portable way to use `#include <file.h>`?

Given the language specification, I would say that we could have a rule that says 
Use 

```
#include <file.h>
```

if you want to have a chance to include a file that is not collocated with the current file.

This will allow you to replace the file while doing test.
