### ISSUE TITLE
Keep your literals readable if possible.

### ISSUE THREAD

**Issue by ParadineG** [isocpp/CppCoreGuidelines#887]
We are missing topic on literals. Where their readability improvements are suggested like:
For decimals use digit separator after each 3rd number and for binary and hex after each 4th number. 
For text break it to new line if text gets to long if possible. 
And most likely there are more.

**Comment by AndrewPardoe** [comment]
Bjarne, per our discussion, could you add an item about this to the naming & layout section?

**Comment by BjarneStroustrup** [comment]
Done: NL.11
