### ISSUE TITLE
ES.28 'good' example promotes 'bad' habit

### ISSUE THREAD

**Issue by xtofl** [isocpp/CppCoreGuidelines#893]
[ES.28 Use lambdas for complex initialization...](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es28-use-lambdas-for-complex-initialization-especially-of-const-variables)

The last example shows a boolean variable to represent whether or not the `owned<istream*>` is an owner or not.  This totally violates the idea of using an `owned` at all.

**Comment by AndrewPardoe** [comment]
There is a proposed PR to fix this, #894.

**Comment by AndrewPardoe** [comment]
Per our discussion, maybe we should hide this ugliness behind a class?

**Comment by xtofl** [comment]
@AndrewPardoe sorry - per what discussion?  Do you mean as proposed in the PR #894?

**Comment by jwakely** [comment]
A discussion amongst the guideline editors, during our meeting yesterday.

**Comment by AndrewPardoe** [comment]
Thanks for the clarification, @jwakely! Yes, I meant our editors' discussion.

Getting a pointer or resource handle from some other code, need to decide whether to take ownership of this pointer/handle or not. Quite often what's being passed is a pointer with some indication of ownership by convention. Some give you ownership to manage, some give a pointer to  what they want to own. Example is a `bool is_owned` being passed, which we do not want to encourage.

Is there a case for a `maybe_owner` here? Maybe we should write this up as a proposed GSL type? We can then recommend that it's a bad pattern, but real, so developers should use it only when necessary. 

Is there a static solution? Maybe a `unique_ptr` with a null deleter? Not pretty, but this code has been written before. 

Bjarne will draft something.

**Comment by BjarneStroustrup** [comment]
I moved the bad example from ES.28 to a new rule: I.30: Encapsulate rule violations.

I may inadvertently have invented a new suppression syntax

**Comment by neilmacintosh** [comment]
No, you just used the existing one ;-)
