### ISSUE TITLE
ES.28: use std::invoke to call the lambda

### ISSUE THREAD

**Issue by thelostt** [isocpp/CppCoreGuidelines#898]
Now that C++17 has `std::invoke`, we could make use of it when doing complex initialization with lambdas. It improves readability, as it becomes clear that you are calling the lambda right away, rather than finding out about it later at the end of a lambda. Example:

Without `std::invoke`:

```
const widget x = [&]{
    widget val;                                // assume that widget has a default constructor
    for (auto i = 2; i <= N; ++i) {            // this could be some
        val += some_obj.do_something_with(i);  // arbitrarily long code
    }                                          // needed to initialize x
    return val;
}();
```

With `std::invoke`:

```
const widget x = std::invoke([&]{
    widget val;                                // assume that widget has a default constructor
    for (auto i = 2; i <= N; ++i) {            // this could be some
        val += some_obj.do_something_with(i);  // arbitrarily long code
    }                                          // needed to initialize x
    return val;
});
```

**Comment by cubbimew** [comment]
`std::invoke` is not `constexpr` ([[func.invoke]](http://eel.is/c++draft/func.invoke)), while lambdas can be used in constant expressions (as of C++17, as well). So you can use the first form, but not the second form, for a `constexpr widget x`. Although perhaps `std::invoke` could be fixed to allow this.

**Comment by gdr-at-ms** [comment]
The version with `std::invoke` is a few characters longer, but the improvement in readability isn't apparent.
There might be other cases where `std::invoke` might be the right choice, but this particular instance isn't one of them.

**Comment by jwakely** [comment]
N.B. GB 51 in [P0488](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0488r0.pdf) proposed making `std::invoke` constexpr, but was not accepted for C++17.

**Comment by mcvsama** [comment]
I use that syntax and was just about to fill similar issue. To me std::invoke() makes it obvious that it's the result of an invocation that's assigned, otherwise it just looks like typical lambda assigned to a variable.

Non-constexprness might be a problem in some cases. In such cases I'd use () and add a NOTE comment or something to make the intent clear.

**Comment by shaneasd** [comment]
I agree. @feroldi 's first example reads like a [garden path sentence ](https://en.wikipedia.org/wiki/Garden-path_sentence). The std::invoke option seems clearly easier for a human to parse to me. It's not so clear whether that justifies the extra characters or the sacrifice of constexpr until c++20.
