### ISSUE TITLE
CP.111 DCLP

### ISSUE THREAD

**Issue by tvaneerd** [isocpp/CppCoreGuidelines#899]
I agree that people shouldn't typically write or use the double-checked locking pattern.
However, the "Example, bad" is actually correct.  In particular the guideline says "The x_init.load(memory_order_relaxed) call may see a value from outside of the lock guard." but that isn't true.

I'm all for discouraging DCLP, but I'm even more all for correctness.

Also, the "Example, good" could use a comment highlighting that it only works because `state` is atomic.  Otherwise it is too easy to think that the if statement could be anything (ie a complex statement with 2 atomics...?)

**Comment by cubbimew** [comment]
So what would be a good bad example? 

I recall the CppCon15 talk by Fedor Pikus had mupltiple DCLP examples: https://github.com/CppCon/CppCon2015/blob/master/Presentations/Live%20lock-free%20or%20deadlock/Live%20lock-free%20or%20deadlock%20-%20Fedor%20Pikus%20-%20CppCon%202015.pdf

**Comment by AndrewPardoe** [comment]
Sergey, can you please make the changes you recommend?

**Comment by cubbimew** [comment]
addressed by PR #920
