### ISSUE TITLE
P.6 has some ABI issues

### ISSUE THREAD

**Issue by yurymik** [isocpp/CppCoreGuidelines#9]
Item P.6 is misleading: it encourages use of `vector` and `array_view` templates in the interface functions, but completely ignores ABI and compatibility issues.

```
extern void f4(vector<int>&);       // separately compiled, possibly dynamically loaded
extern void f4(array_view<int>);    // separately compiled, possibly dynamically loaded
```

I think it has to at least briefly mention that these templates may not be implemented in the same way, and most likely than not "possibly dynamically loaded" wouldn't work as expected.

**Comment by hsutter** [comment]
Fixed, thanks! Added comments to mention these assume an ABI-compatible caller using a compatible compiler and the same stdlib implementation.
