### ISSUE TITLE
ES.23: Cannot use {} syntax with a template parameter that might be `void`

### ISSUE THREAD

**Issue by TBBle** [isocpp/CppCoreGuidelines#900]
Playing with [`void()` VS `void{}`](http://stackoverflow.com/a/43576047/166389), I noticed [ES.23: Prefer the {} initializer syntax](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es23-prefer-the--initializer-syntax).

It might be worth adding a *Note* there that if initialising a value typed to a template parameter, and `void` is a possible template argument, then you cannot use `{}`: `void()` is special-cased to be valid where it would not otherwise not be, but `void{}` has no such exception.

Technically, `void()` is not an initialisation, but it seems that it's functioning the same way.

In my minimal sample, neither `T()` in `make` can become `T{}`.
```c++
#include <iostream>
#include <typeinfo>
 
template<class T>
auto make() -> decltype(T()) { return T(); }

int main(int, char**, char**)
{
    std::cout << make<int>() << "\n";
    std::cout << typeid(make<int>()).name() << "\n";
    make<void>();
    std::cout << typeid(make<void>()).name() << "\n";
    return 0;
}
```

This seems like a defect in the standard, but it's been that way since C++11, so presumably this was intentional. A `T()` where `T` can be void is only useful in [limited contexts](http://stackoverflow.com/a/37708167/166389) anyway.

**Comment by jwakely** [comment]
Even if we ignore the fact it's not an initialization and so the guideline doesn't apply, this is such an odd special case that I don't think the guideline needs to be changed. I doubt it matters in real code, not contrived examples.

**Comment by TBBle** [comment]
I wasn't suggesting changing the guideline, "prefer `{}`" is terrific. Since the guideline already presents some exceptions and notes already, I don't see the harm in noting this lurking surprise too.

`return void{}` is precisely as useful as `return void()`, and will appear in the same circumstances when ES.23 is applied to generic code. `return void()` is explicitly allowed as an exception by the standard, so it must have non-contrived use-cases around. I did fail to come up with any 'real code' use-cases when I tried... The main use case I can find for `void()` at all is with the comma-operator and `decltype` for SFINAE.

The fact it's not an initialisation (even though it has an initialiser) is somewhat esoteric for the reader --- any other type there would be an initialisation.

**Comment by jwakely** [comment]
> `return void()` is explicitly allowed as an exception by the standard,

Could you point me to that exception? I'm failing to find the precise wording.

> so it must have non-contrived use-cases around.

Not necessarily. I suspect it's allowed for consistency with other uses of `void()` such as an operand to the comma operator. The use of it in [dcl.type.auto.deduct] seems to be a convenience for the purposes of specification, not because it's useful in real code.

When the standard talks about a return statement with an operand of type void the main use case of that is not explicitly writing `return void();` but `return f();` where `f()` is a function returning void.

> I did fail to come up with any 'real code' use-cases when I tried... The main use case I can find for void() at all is with the comma-operator and decltype for SFINAE.

I'm unconvinced it has real-world uses, or needs to be mentioned in the guidelines. The standard allows lots of weird corner cases.

**Comment by TBBle** [comment]
That's true, I mentally conflated the 'special-case' with the explicit list of places you can use an expression of type `void` from [[basic.fundamental]/9](http://eel.is/c++draft/basic.fundamental#9).

I can see that the special-case in [[dcl.type.auto.deduct]/2](http://eel.is/c++draft/dcl.type.auto.deduct#2) is to make the return-type deduction machinery work.

The special-case I was **actually** thinking of is actually about the behaviour of `void()` vs `void{}`: [[expr.type.conv]/2](http://eel.is/c++draft/expr.type.conv#2) makes the former work, but the latter is not mentioned and hence fails once it tries to resolve the initialisation.

I've been poking around for other use-cases, and it does seem that most use-cases will fall onto library implementors and similar people who'll be able to do the right thing here anyway. So I agree, not a strong case to put in a note on the guidelines.

As a side-note (and for any late-comers), I'm going to see if I can get this particular special-case fixed in the standard instead.

**Comment by gdr-at-ms** [comment]
> I'm going to see if I can get this particular special-case fixed in the standard instead.
Indeed, that would be the better solution.  Thanks!
