### ISSUE TITLE
Suggest reconsideration of Enum.6

### ISSUE THREAD

**Issue by eyalroz** [isocpp/CppCoreGuidelines#901]
I suggest guideline Enum.6: "Avoid unnamed enumerations" be reconsidered.

This has two reasons, a minor and a major one. 

### Minor reason

The reason given for avoiding unnamed enum's is:
> If you can't name an enumeration, the values are not related

Well, whoever said I had multiple values? Maybe it's just a single value? Of course, having just a single value ties in to...

### Major reason: There are legitimate, common, use cases for unnamed enum's

There are, IMHO, at least two kinds of legitimate and not-uncommon cases where unnamed (though typed) enums are an appropriate, best, or only solution

#### Aliasing values of another type (typically bool)

Take some function with a boolean paramter:
```
int frobnicate( bar x, bool be_thorough );
```
How does this look from the call site? Very often, we would be looking at:
```
bar my_bar = get_some_bar();
auto y = frobnicate( my_bar, true ); // frobnicate thoroughly
```
... and that's if we were gracious enough to add the comment. Otherwise, this looks like a magic number. Now, true, it isn't really - you can look up the declaration and figure out what that means. But for readability, I very often have:
```
enum : bool { be_cursory = false, be_thorough = true };
```
(don't worry, it's in a namespace, I'm not polluting anything.)

If you'd ask me "why not an enum class?" - well, I want to be able to use it like a bool, and I don't want to _have_ to cast it, if I, say, get a boolean value from somewhere else. And if you'd ask "why not name this enum?" - well, that' superfluous. These are just aliases for bool values. I _could_ name that enum, but I don't want to hint at it having an 'independent life", or that I would lvalues like that.

So that's

#### Constants which are assured not be allocated space in memory

Many advocate for using `constexpr const` for constant values (or `static constexpr const` in a class), instead of enum's. However, these modifiers do not guarantee (nor purport to guarantee) that memory will _not_ be allocated for the constant, that it will _not_ be accessible via an address at run-time..

Such a guarantee may be useful or even important: Sometimes you need to have tight control over what has space allocated for it in memory. It could theoretically be because of dearth of memory space, but it could also be due to the need to have your class' memory layout compatible with code compiled elsewhere, that expects a certain layout. At any rate, in those cases you have to use enum's for these constants. They are very typically just _single-value_ enums, something like
```
struct my_speciality_layout_structure {
    enum : size_t { bits_to_frob = 24; }
    boost::uint_t<bits_to_frob>::least data;
}
```
If I had used a `constexpr const`, someone could "troll" me by using `&my_speciality_layout_structure::bits_to_frob` and forcing instantiation in some translation units. And while I could make it static - I would then have static data, which can be a nuisance in some cases.

**Comment by jwakely** [comment]
Your first example of a replacement for bool nicely demonstrates the point of the guideline: you should be able to name the type, and the API you're calling should use that type for its parameter. Fixing it at the call site is the wrong place.

    enum Throughness { thorough, unthorough };
    int frobnicate( bar x, Thoroughness );

**Comment by jwakely** [comment]
And your second example is wrong: for C++11 and C++14 a static const data member doesn't use storage unless you provide a definition (forgetting to provide such a definition is a [common mistake](https://gcc.gnu.org/wiki/VerboseDiagnostics#missing_static_const_definition) and gives a linker error precisely because there's no storage for the object).

I don't find these argument convincing for a change to the guidelines. Just because you want to do it in your code doesn't make it a good idea that should be promoted by the guidelines.

**Comment by eyalroz** [comment]
I do not _want_ to name the enum, I don't _want_ it to be anything but a bool. And the name you chose is _wrong_. It's not the thoroughness of anything - it's just a choice of whether the function will frob thoroughly, and that's very much not the same thing. I also do not want to encourage the use of this enum elsewhere, which would create dependencies I'm not interested in.

Also, I would argue that you are somewhat biased here, Jonathan: We were having an exchange on StackOverflow regarding a case in which GCC emits a warning but clang does not - and you were using this guideline as a justification. (Of course, truth be told, that's what brought me to open this issue as well.)

As for C++17 and the implicit inlining - that's still not mandated no-storage. Until there's a language construct for constants which are guaranteed not to exist at runtime (= no storage, no address), I think (unnamed) enums remain important for this reason as well.

**Comment by jwakely** [comment]
Your reasoning is circular. I pointed you to this guideline because I agree with it, so it's not surprising I don't think the guideline should change. IMHO it is already correct.

**Comment by neilmacintosh** [comment]
@eyalroz Based on my knowledge of @jwakely, I do not believe he is arguing for a guideline in order to to justify a particular GCC warning. It would be nice if we could assume the best of one another in these sorts of discussions, rather than resorting to ad hominem comments.

Personally, I also find your justification for recommending unnamed enums uncompelling. As @jwakely pointed out there is a perfectly viable alternative. And even if you don't like that, just using `true` or `false` with a comment is hardly the worst thing in the world either. I think the value of the guideline is it steers people away from a design error and towards common-sense use of types.

**Comment by eyalroz** [comment]
@neilmacintosh : With due respect - Jonathan is continuing a discussion here that began elsewhere about a GCC warning message. That's not to say his arguments are not without merit.

To the point though, it seems you're framing this discussion incorrectly. I did not claim unnamed enums should be *recommended* in the guidelines; I'm challenging the strong recommendation to the contrary, the recommendation to *avoid* them altogether. The onus is not on me to prove or justify the significant utility of unnamed enums - the onus is on the authors of this particular guidelines to justify avoiding a valid language construct - which is not esoteric and is used by many. I do not see that either the text of the guideline nor the arguments in on this issue page so far bear this onus. 

Also, I'm having trouble following your last sentence. You're justifying the encouragement to avoid enums by arguing that it helps avoid making a design error; but what is that design error? I mean, other than the use of unnamed enums, which is what we're debating? The same for "common-sense" use of types: What lack of common-sense does the use of unnamed enum constants result in?

Finally, on my part - I presented several several scenarios in which I believe that not only are unnamed enums reasonable to use, but they are in fact the favorable if not the only construct with the desired semantics irrespective of compiler behavior. What Jonathan wrote about the first of these scenarios is in line with my argument - it illustrates how naming the enum has undesirable outcomes, without demonstrating any desirable one (other than, again, non-use of unnamed enums). And my second use case still stands, in that there does not seem to be another language construct for guaranteed compile-time-only constants (unless you could `#define`s).

**Comment by neilmacintosh** [comment]
@eyalroz As Jonathan pointed out - accusing him of bias was a nonsensical statement, regardless of where prior discussions may have occurred. He agrees with the guideline, it's as simple as that. As do I.

The guideline gives clear reasoning as to why it recommends avoiding unnamed enums.  You do not have to agree with that reasoning, but it is given. I'll repeat it here because it is not particularly lengthy: "If you can't name an enumeration, the values are not related".

That is the design error to which I was referring: if you collect together a bunch of special names in a type, but can't give them a name...then I believe you have a design error. Either the names are unrelated, or you are using the enum for a purpose like "faking" integer constants that should no longer be necessary in today's C++.

Your first use case fails to convince me, or Jonathan. Your second use case (i.e. constants) should not require unnamed enums. If you think there is still a shortcoming in the language around constants, then encouraging the use of unnamed enums would not be the correct way to solve it.

**Comment by arvidn** [comment]
@eyalroz What I think you would need a stronger argument for is why you want your names to be implicitly convertible to bool. As jonathan points out, the way you would normally write your frobnicate function is to make the parameter type-safe (i.e. ``enum class``). what is the benefit of not having it be type safe? i.e. have names that are just aliases for ``true`` and ``false``.

I think the drawbacks are obvious. It's still possible to call your function with ``true`` or ``false``, decreasing its readability. It would also be possible to use your names (that are implicitly convertible to ``bool``) in other, unrelated, contexts.

**Comment by eyalroz** [comment]
@arvidn : The parameter is very type-safe - its type is `bool`; and there could be various reasons why that's appropriate. However, I do concede that fact that it would be possible to use my names in other contexts is, indeed, a drawback. That's why typically I have these enums within a namespace, so while you could pass `util::frobnication::be_thorough` to any function taking a `bool`, that will not happen accidentally.

@neilmacintosh : With your clarification of the  reference to a "design error", it seems that argument is mostly circular reasoning: You recommend against not naming enums because if you don't name enums than you have values without a common name, i.e. you have a unnamed enum.

The part that is not circular reasoning is the argument that it should not be necessary to "fake integer constants" in C++. I agree that it should not be necessary to use enums for compile-time-only integer constants - but is there another language construct which allows for them, irrespective of compiler optimizations? AFAIK the answer is negative.

As for the part of the text you quoted from the guideline - "If you can't name an enumeration, the values are not related":

1. There might just be a single value, in which case relatedness is meaningless.
2. Values not being related is not very consequential if you merely want compile-time-only constants of the underlying type.
3. Sometimes you _can_ name the enum, but you have reasons to _not_ name it and little or no benefit from naming it.

Finally, again, whoever wishes to discourage a language feature has to make the convincing argument, not the other way around.

**Comment by jwakely** [comment]
> but is there another language construct which allows for them, irrespective of compiler optimizations? AFAIK the answer is negative.

Nonsense. The guideline you're objecting to is about __unnamed enums__ and the language feature that allows compile-time-only integer constants without violating the guideline is a named enum.

You seem overly concerned with an imaginary cost of using `constexpr` variables, in case somebody takes their address, which is not a problem I've encountered in the real world. If that's really a problem for you then enumerations work, but unnamed enums should be avoided for the reasons given in the guidelines. You haven't presented a convincing argument why the guideline is wrong (indeed you've shown examples that support it!) but feel free to write whatever you want in your own code. That doesn't mean the guidelines have to agree with your peculiar design choices.

**Comment by AndrewPardoe** [comment]
Closing this issue as a result of our editor's meeting. Thank you for the discussion, everyone!
