### ISSUE TITLE
Suggestion, new rule "Con.6"

### ISSUE THREAD

**Issue by Amaroker** [isocpp/CppCoreGuidelines#902]
Use const member functions appropriately.

Reason: Const correctness. To prevent unwanted side effects or data races.

Note: In const member functions that involve non-const member pointers/references there are opportunities for mistakes that can result in accidental modifications.

Example:
```
Data& foo() const { return m_p->x; } // bad

const Data& bar() const { return m_p->x; } // good
```

Example:
```
auto X::foo() const
{ 
    // ...
    m_p->reset(); // oops! 
    // ...
}
```
Exception: members declared mutable

Enforcement: Flag non-const and non-mutable member pointers/references that are returned or used to modify the pointee, inside const member functions.

**Comment by arvidn** [comment]
You don't really address why you think const should apply "deep". A counter-example would be ``std::shared_ptr``.

I also believe that a common mistake is to heap allocate members that really should be just direct members (which is one way one might conclude that const should behave like you suggest).

**Comment by Amaroker** [comment]
Const member function should typically "act const". This is especially important for thread safety.

Yes, there are a few cases where the rule needs to be ignored. For example, shared_ptr is a wrapper, the templated type T can be non-const, but get() must be declarated const so that you can call it for a const shared_ptr<T>.

However, you can still **use** the shared_ptr safely inside const member functions. so if m_p is a shared_ptr in the example above, the guideline checker should warn you.

Of course, if you can avoid non-const heap allocated members that's even better.

**Comment by jwakely** [comment]
I think it could be useful to draw attention to this potential problem. Deep constness isn't always desirable, but sometimes is. When it's wanted `std::experimental::propagate_const` can be used to enforce it.

**Comment by Amaroker** [comment]
Do you think that propagate_const should be added to the support library? That way, while we are waiting for the next standard and inclusion in all compilers, we can use gsl::propagate_const.

**Comment by AndrewPardoe** [comment]
Should we potentially make this a note on Con.2 rather than an entire rule? We don't necessarily want to encourage this programming style. 

The question is in the absence of language support for deep `const` what guidance should we provide?

**Comment by BjarneStroustrup** [comment]
Added a note to Con.2
Also, we need a guideline about PIMPL
