### ISSUE TITLE
ES.24 rule in TOC and body differ

### ISSUE THREAD

**Issue by ewoudvc** [isocpp/CppCoreGuidelines#904]
TOC:  ES.24: Use a unique_ptr<T> to hold pointers in code that may throw
Body: ES.24: Use a unique_ptr<T> to hold pointers

Let me know which of the 2 you prefer, I'll fix and send a pull request

**Comment by jwakely** [comment]
The body was changed by @tituswinters with d653d5e89c6b42b410a328981c475d05f46d6fc7 so assuming that was what was wanted the TOC should be changed to match

**Comment by jwakely** [comment]
Fixed by your pull request. thanks.
