### ISSUE TITLE
Anchors for C.147 and C.148 are backwards

### ISSUE THREAD

**Issue by jwakely** [isocpp/CppCoreGuidelines#918]
The titles are:

C.147: Use dynamic_cast to a reference type when failure to find the required class is considered an error
C.148: Use dynamic_cast to a pointer type when failure to find the required class is considered a valid alternative

But the anchor for the first one is `#Rh-ptr-cast` and the second one is `#Rh-ref-cast`. That's confusing.

Any fix should be sure to also fix cross-references using the anchors.

**Comment by AndrewPardoe** [comment]
Thank you!
