### ISSUE TITLE
Add additional guidance on using casts

### ISSUE THREAD

**Issue by ZachHenkel** [isocpp/CppCoreGuidelines#926]
- New enforcement suggestion for Res-casts: Avoid unnecessary casts
- New enforcement suggestion for Res-casts-named: Use braced initialization or gsl::narrow_cast instead of named casts on arithmetic types
- Add specializations of the rules for Pro-type-reinterpretcast for treatment of casts involving void* (already implemented in Microsoft's CppCoreCheck)

A draft of the proposed changes can be found [here](https://github.com/ZachHenkel/CppCoreGuidelines/commit/f1b348e0db2c49b9980f732b8a4aeb5a719eb9a6)

**Comment by AndrewPardoe** [comment]
You've found a really good point, but it could be clearer. Per our discussion, we'd like you to expand the PR a bit. On the first change, please expand on what constitute unnecessary casts and provide some examples. The last change raises the question of when and where it is appropriate to have a `void *`.

**Comment by ZachHenkel** [comment]
Thanks!
