### ISSUE TITLE
Making `std::move` safer?

### ISSUE THREAD

**Issue by galik** [isocpp/CppCoreGuidelines#928]
Looking at items [C.64](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-semantic) & [C.65](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-self) I was thinking about ways to detect invalid uses of objects that had been *moved from*. Item [C.64](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-semantic) says it is "unenforceable" to make sure a variable is properly reset to a known value. But what if you were to flag **every** use of a variable after a `std::move(v)` unless the programmer indicates that the variable had been properly *reset*?

For example, after *moving* a vector it is good to use after the `std::vector::reset()` function has been called or after *reassignment*:
```cpp
std::vector<int> v {1, 2, 3};

func(std::move(v));

// re-initialize the object so that we can continue using it

v.clear(); // now it is good to use

v = more_random_numbers(1000); // now it is good to use
```

However any use of a *moved from* object, that does not correctly *reinitialize* it, is a bug. The compiler can already tell us when *uninitialized variables* are used before they are assigned a value and could potentially do something similar for *moved from* objects. However, as [C64]() points out, the compiler can't know if the *move* operation allows for that (though the CppCoreGuidelines strongly encourage it).

Also there are potentially more ways to *reinitialize* a *moved from* object than simple *assignment*. Calling a member function for example.

So what if we had a simple way to tell the *static analysis* tools that a *moved from* object is being properly *reinitialized*?

Consider something like this:

```cpp
template<typename Object>
Object& move_reset(Object& o) { return o; }
```

Now, the static analysis software can bug the programmer with **warning** messages whenever they use a *moved from* variable without first, telling the static analyzer that it is being properly *reinitialized*:

```cpp
std::vector<int> v {1, 2, 3};

func(std::move(v));

v.clear(); // causes the tools to flag a use-after-move warning

// re-initialize the object in a way that tells the
// static checkers to stop flagging use-after-move error

gsl::move_reset(v).clear(); // no warning now

gsl::move_reset(v) = more_random_numbers(1000); // same here
```

This is good for maintenance too because if a future programmer adds an operation *before* the `gsl::move_reset()` call, the static tooling will once again start spitting out warnings but it will remain silent for any operations added *after* the call.

This is also relevant to:

[ES.56](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-move)
[F.18](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-consume)

**Comment by MikeGitb** [comment]
The problem I have with this suggestion is that move_reset itself doesn't do anything and is in no way tied to the function that actually does the reset. 

Also, what about types where the moved from state is clearly defined and doesn't require a `move_reset` in the first place (think std::unique_ptr)?
Finally, even in cases like `std::vector`, where a move leaves the original object in a valid but unspecified state (e.g. `std::vector`) there are still a lot of member functions that don't have a precondition on the object's state and hence can safely be called without a reset (e.g. `std::vector::size()`).

My gut feeling would be to look at pre and post conditions: Post conditions of a move operation could state if the moved from object is in a defined state, whereas preconditions on other functions can state whether they require the object to be in a defined state at all. Unfortunately I don't believe contracts will be available soon to the broad audience. Maybe attributes could be a workaround till then?

**Comment by galik** [comment]
@MikeGitb  I agree with all of your thoughts. But if you look at [F.18](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-consume) under *enforcement* it says:

> Flag access to moved-from objects.

 Which is all very well but that could create a lot of noise in those cases that you mention where moving is well defined or, the more usual case, where it is easily recovered from. This is just a trick to flag the static checker to turn its warning off.

I like *moving* things around as it obviates almost every need for a pointer. Passing a `std::vector` around is as efficient as passing pointers so there is hardly a need to have a pointer to a vector. But treating vectors like sort-of-pointers with value semantics is going to trip the static checker's warning rather a lot.

So I suppose I was looking for some way to make *moving* objects feel a little bit more like a respectable activity.

**Comment by jwakely** [comment]
I agree that not all uses of moved-from objects are problematic, but I don't think these guidelines are the place for novel inventions like that.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, this is a suggestion for the GSL, not the Guidelines directly. As @jwakely suggests, the Guidelines should focus on techniques that have been proven on a larger scale. Are there examples of this technique in common usage?

We encourage further thought in this area--possibly in the GSL, possibly in tooling, possibly in the Guidelines, possibly in WG21--but don't think that this is the right suggestion or formulation. Thank you for bringing up this issue!

**Comment by lbrandy** [comment]
My 2c. 

I think the general problem of warning/enforcing on use-after-move is potentially very valuable. The problem with that, that we're trying to address here, is how to annotate for the static analysis tools that certain things are OK. This is a really hard problem in general. But getting something decent would make for quite a bit more bug-prevention. 

IMO, that said, the proposed solution isn't really baked enough nor obviously correct enough to get codified. I think there's a number of first-impression concerns I'd have with this: notably, imo, that the call-site is the wrong place to be annotating this. But the deeper concern I have is that this problem is sufficiently difficult that w/o a fair bit of experience in deploying and using some annotations and a tool that supports it, it's hard to say what's good and what's bad.

**Comment by mloskot** [comment]
AFAIU, this suggestion is not concerned about detecting situation like this:

```
std::unique_ptr<T> p1;
auto p2 = std::move(p1);
...
p1->foo();
```

AFAIK, there is no compiler offering warning-level diagnostics for that either.

Am I correct?
