### ISSUE TITLE
Preparing talks on CppCoreGuidelines

### ISSUE THREAD

**Issue by Juanmihd** [isocpp/CppCoreGuidelines#929]
Hi all, 

I plan to do some talks on this guidelines in my workplace (Hewlett Packard), to help some of the engineer to transition to Modern C++. 
I think that some times a big long document can be intimidating to some people, that's why I thought of preparing a series of talks on this document, were I could give an overview of some of the main points (just as Herb Sutter, Bjarne Stroustrup and Neil MacIntosh's talks) explaining them and opening them to questions to the attendees.

Would you have any suggestion on preparing those presentations? 

I was thinking on just going through the sections of the CppCoreGuidelines, focusing on the examples, and trying to explaing them over some slides.

I would appreciate any kind of suggestions or feedback!

Cheers,

Juanmi Huertas

**Comment by cubbimew** [comment]
Don't overlook Peter Sommerlad's talk from ACCU 2017

When preparing a guidelines talk for C++ Russia earlier this year, I found it helpful to alternate obvious and controversial rules to keep the audience awake.

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, we can improve the References section (possibly renaming it Resources?). We can add links to Peter's talk, as well as resources in https://github.com/isocpp/CppCoreGuidelines/blob/master/talks/README.md. 

Thank you for the suggestion!

**Comment by BjarneStroustrup** [comment]
There is now a good start.
