### ISSUE TITLE
Instead of doing this... does that

### ISSUE THREAD

**Issue by magol** [isocpp/CppCoreGuidelines#930]
I would like a list of common ways to build programs in the past, and how to write instead in modern C++.

Reading all the rules is very interesting, but it's hard to quickly see how they affect your own programs.
If I can read through a short list of  easy-to-identify program examples, I may be able to identify more quickly the worst things in my program.

**Comment by jwakely** [comment]
This might be useful in an appendix or separate document. I also think it's the kind of thing that should be provided by the community, as it would require significant work.

**Comment by magol** [comment]
@jwakely 
I totally agree with you.
Maybe start with just creating a document with a base to start from, and then we help each other to fill it with content.

I think everyone who has worked with this can contribute with experiences from migrating old code.

**Comment by BjarneStroustrup** [comment]
There is not just one right way to write "modern C++". Different communities have different constraints and "modern C++" is constantly evolving.
The Core guidelines have lots and lots of small examples, but not a complete philosophy of code modernization. How to upgrade, how to gradually improve a large code base, is something we'd like field experiences with. It's important and "philosophy" tend to be inadequate.
We need coherency of rules and examples; that's hard to achieve and to maintain.
I'd particularly like to hear suggestions for the modernization section; it's currently feeble and needs concrete examples based on experience (positive and negative).

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, no work is immediately planned on this item. Thank you for the suggestion!
