### ISSUE TITLE
Per.11: Move computation from run time to compile time

### ISSUE THREAD

**Issue by scraimer** [isocpp/CppCoreGuidelines#936]
I've got a first draft for Per.11.
If anyone could spare some time to take a look and comment before I create a PR, it would be appreciated.

Here's the [suggested changes](https://github.com/scraimer/CppCoreGuidelines/commit/6fb9f6a78f184d08b8b7e39d70c803d0a34ee799)

**Comment by MikeGitb** [comment]
What I'm wondering is how much computation can realistically be done at compile time in nontrivial applications? My guess would be that the vast majority of data handled in a program is either coming from a dynamic source (The user, a file, the Network) or is some configuration parameter that also comes more often than not from a config file. In both cases, compile time computations are not possible, simply because the data is not known at compile time.

**Comment by scraimer** [comment]
@MikeGitb  Oh, I agree that the vast majority of _data_ comes from an external source. But many of the _decisions_ about that data are unchanging, and can be known at compile time.

Jason Turner had a great talk in which he showed how he wrote a pong-clone for the C64.
 https://www.youtube.com/watch?v=zBkNBP00wJE
The key point is that the compiler knew enough at compile-time that it could optimize a lot away. The program became a pure input-processing application. All the branches dependant only on the input, and producing output directly.

A terrible and common example that I've seen is processing market data from exchanges. While the correct way is to have the definitions of the protocol in a configuration file, you can gain a lot by hard-coding those definitions. So instead of having to perform lookups  in the information loaded from the definition file on every input, the code has the results of the lookups already hard-coded. Since those results are known at compile time, any branches based on those results can also be computed at compile time. What you end up with is assembly that only has branches on the inputs, and none dependant on the configuration or compile-time decisions. For an HFT, the difference in latency between the approaches can spell the difference between making another thousand dollars, or losing ten times that.

The point I'm trying to make is that you're right. Programs depend on inputs. If we could cause the programs' executions to do exactly nothing more than the minimum needed to process those inputs, they would run faster. One way to do that without sacrificing abstraction of complex logical chains, is by moving computation to compile-time.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, saying "Write code that does **all** its computation during compile time" is a bit too radical. There are times where some cycles spent in execution are well worth the tradeoff in compile time and debugging complexity. 

We appreciate the direction you've taken in starting this item. Bjarne would like to take a stab at writing this one up himself. Thank you, @scraimer!

**Comment by BjarneStroustrup** [comment]
I have added some text and examples. More examples could be useful.
