### ISSUE TITLE
Use of links to undefined anchor

### ISSUE THREAD

**Issue by k-satoda** [isocpp/CppCoreGuidelines#95]
There are many links to undefined anchors. I sent fixes (PR #84) for some easy parts of them. To fix remaining I think some guidance (or action) from the author(s) are required.

The remaining (the result of script shown in PR #84, after the fixes are applied) are:

> (empty)
> # Sd-noexcept
> 
> Rcon-empty
> Rcon-init
> Rcon-move
> rcon-ptr
> Rcon-stl
> Rcon-val
> Ref-conceptsTS
> Rf-local-ref-ref
> Rper-checking
> Rr-smartptrconcepts
> Rt-???
> Rt-cast
> Rt-specialization2
> S-???
> Sd-???
> Sd-noexcept

I couldn't figure out fixes for them because:
- Some of them seems to be intentional placeholders:
  - ["Rcon-*" (including "rcon-ptr")](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L4611)
  - ["Rr-smartptrconcepts"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L11410)
  - ["Rt-???"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L8769)
  - ["S-???"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L60)
  - ["Sd-???"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L8503)
  
  I don't know whether it is OK or not to keep such placeholders as dead links. I think dead links are bad, and the link (not the text) should be removed, or the anchor should be defined somewhere with a note like "to be written" or something.
- ["Ref-conceptsTS"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L8968) is surely referring to ISO C++ Concepts TS. But the use of the link (anchor name) is at only one place among some more places referring the same TS. Also, there is "References" section. I think It is better to be fixed with a document wide policy about how to link to TS or the Standard.
- I couldn't be sure of the intended target of some links:
  - ["Sd-noexcept" (including "#Sd-noexcept")](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L8208):
    "Sd-never-fail" seems the most relevant discussion. But I think it is possible to be a placeholder to future discussion or an oversight after removal of old discussion.
  - ["Rf-local-ref-ref"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L2506):
    The link is set to the text "F54". But there is no rule with such number. There are similar anchor; "Rf-return-ref-ref" and "Rf-pass-ref-ref". But "Rf-local-ref-ref" is used beside them, so they seem distinct rules. If it is a removed rule, entire "See also [F54](#Rf-local-ref-ref)." should be removed.
  - ["Rper-checking"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L1272):
    There is no such rule in "Rper-*" that is saying something like the link text: "move checking outside the critical part of the code".
- ["Rt-specialization2", "Rt-cast"](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L8759)
  They seems to be oversight of removal of corresponding rules. In that case, the link (with text) should be just removed from the summary. But I think it is possible that the rule is just not written yet.
- [The link with empty anchor ("[example of such overloading](#)")](https://github.com/isocpp/CppCoreGuidelines/blame/245f82acd58eecf6b92cc51393fe32e114dc7b90/CppCoreGuidelines.md#L2222) seems like an old placeholder when the example was not there. In that case, I think the link (with text) should be removed.

**Comment by AndrewPardoe** [comment]
Thank you! I'll fix merge errors in your PR and pull it. I'll leave this open for the issues you couldn't address.
