### ISSUE TITLE
Enum.4: Some defects in the Example

### ISSUE THREAD

**Issue by d25fe0be** [isocpp/CppCoreGuidelines#953]
In **Example** of Enum.4:

```
enum class Day { mon, tue, wed, thu, fri, sat, sun };

Day operator++(Day& d)
{
    return d == Day::sun ? Day::mon : Day{++d};
}

Day today = Day::sat;
Day tomorrow = ++today;
```

`++d` in  `return d == Day::sun ? Day::mon : Day{++d};` calls the overload itself, recursing infinitely. I believe that it was meant to cast `d` to `std::underlying_type_t<Day>` first.

I'm also curious if `operator ++(Day&)` should return `Day&` instead of `Day`.

Another defect in the example is that as we're calling pre-increment operator on `today` to initialize `tomorrow`, `today` is incremented before assigned to `tomorrow`. So `today` equals to `tomorrow` in the end. I'm not sure if this is intended.

I tried writing a "better" example, but the code looks awkward. Mainly because of the castings..

```
enum class Day { mon, tue, wed, thu, fri, sat, sun };

Day operator+(Day d, int incr)
{
	return static_cast<Day>((static_cast<std::underlying_type_t<Day>>(d) + incr) % 7);
}

Day today = Day::sat;
Day tomorrow = today + 1;
```

Or we might simply fix the infinite recursion and remove `Day tomorrow = ++today`  to keep the example easy to read, as following (Also looks a bit awkward, but better than the `operator +` overload.):

```
enum class Day { mon, tue, wed, thu, fri, sat, sun };

Day &operator++(Day& d)
{
    return d = (d == Day::sun ? Day::mon : Day{static_cast<std::underlying_type_t<Day>>(d) + 1});
}

Day today = Day::sat;

++today; // Today is Sunday.
```

ps: `Day{...}` may be substituted with `static_cast<Day>(...)` to be comply with C++11.

**Comment by robert-andrzejuk** [comment]
I have submitted a patch, which you can review: #944 716 - new example in Enum.4

**Comment by d25fe0be** [comment]
I'm sorry I didn't realize that. I appreciate your changes, which further take `constexpr` into consideration (which I didn't.).

I still think the line `Day tomorrow = ++today` in the original example is a small defect though, I'll post this point there for discussion.

Closing the issue.
