### ISSUE TITLE
NL.16 - What does it really mean? - Is it consistent ?

### ISSUE THREAD

**Issue by travnick** [isocpp/CppCoreGuidelines#962]
NL.16 is not clear for me. Should I write

```
class X {
public:
    // types, constructors, assignments, destructor, functions, data
protected:
    // types, constructors, assignments, destructor, functions, data
private:
    // types, constructors, assignments, destructor, functions, data
};
```

**or** 

```
class X {
public:
    // types, 
protected:
    // types, 
private:
    // types, 

public:
    //  constructors, assignments, destructor, functions, 
protected:
    //  constructors, assignments, destructor, functions, 
private:
    //  constructors, assignments, destructor, functions, 

public:
    // data, 
protected:
    // data, 
private:
    // data, 
};
```

**Comment by jwakely** [comment]
Your second form violates "Avoid multiple blocks of declarations of one access (e.g., public) dispersed among blocks of declarations with different access (e.g. private)."

I'm not sure about enforcing this though, it's not always practical, for example:

````
class X {
  using internal_type = ...;
public:
  X(internal_type::value_type);
};
````

The typedef for internal use needs to come before any declarations of public members that refer to it.

**Comment by travnick** [comment]
You are right but `Private types and functions can be placed with private data.` suggest that by default private types, functions and data are in separate blocks as in second example.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we believe the discussion already here resolves the issue. Thank, @travnick and @jwakely!

**Comment by travnick** [comment]
Unfortunately the issue is not resolved.

As I said before ```Private types and functions can be placed with private data.``` suggest that primary grouping is by type not by visibility which is in conflict with ```Avoid multiple blocks of declarations of one access (e.g., public) dispersed among blocks of declarations with different access (e.g. private).```

**Comment by jwakely** [comment]
> As I said before `Private types and functions can be placed with private data.` suggest that primary grouping is by type not by visibility

No it doesn't, it says exactly the opposite. It says place private types with private data, and place private functions with private data. So place all the private things together. So group by visibility.

**Comment by BjarneStroustrup** [comment]
Clarifying (I hope) text and example added

**Comment by travnick** [comment]
Thank you for the reply. I'm reading the example over and over

>Sometimes, the default order of members conflicts with a desire to separate the public interface from implementation details.
In such cases, private types and functions can be placed with private data.

but probably I'm missing something.

How it's possible that default order may conflict with public interface separation? (example?) I see only one plain wrong way:
```
public:
    void MyFunction(PrivateType value);
```
but it renders the function unusable (except `PrivateType` is just an alias for some public type).
If it's another case I'd really appreciate if you provide an example of that.

As I asked at the beginning and the answerers confirmed the default valid layout is like
```
class X {
public:
    // public interface - types/aliases, functions, data (fields)
protected:
    // types/aliases, functions, data (fields)
private:
    // implementation - types/aliases, functions, data (fields)
};
```
Am I right? If so then I'm not understanding that
> private types and functions can be placed with private data

because it's the default. Making such exception strongly suggest that the default order is different.

**Comment by jwakely** [comment]
> but it renders the function unusable

No it doesn't. You don't need to name the private type to use that function:

````
struct X {
private:
  struct PrivateType { PrivateType(int); };
public:
  void MyFunction(PrivateType);
};

X x;
x.MyFunction(1);
````

**Comment by travnick** [comment]
Ok, you are right but (regardless of sense of that) this does not resolves the confusion here. There is a talk about **exception** that private data **can** be placed with private function and types in **one** `private` section. What I'm missing here?
