### ISSUE TITLE
ES.76: Avoid goto

### ISSUE THREAD

**Issue by MikeGitb** [isocpp/CppCoreGuidelines#963]
[ES.76](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es76-avoid-goto) states getting out of a nested loop as a valid use case for a goto statement.

I found that those cases can often also be solved by enclosing the loop into an immediately invoked lambda expression. Taking the example from ES.76:

	[&] {
	    for (int i = 0; i < imax; ++i)
	         for (int j = 0; j < jmax; ++j) {
	             if (a[i][j] > elem_max)
	                 return;
	             // ...
	         }
	}();

I don't necessarily think that it is more readable than the goto version, but it allows banning goto from code completely. Any thoughts on this?

**Comment by gdr-at-ms** [comment]
readability, part of maintainability, should be considered key factor.

**Comment by MikeGitb** [comment]
@gdr-at-ms: I agree and as far as my personal opinion on the matter goes: I said it is not necessarily better, that doesn't mean I think it is worse.

Do you have a clear preference?

**Comment by galik** [comment]
I'm not sure that it is so unreadable. Especially when lambda functions are the recommended way to perform *complex initialization* ([ES.28](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-lambda-init)). I suspect we are going to see that type of construct popping up more regularly. What would be nice is to have a syntactically nice short-cut for this kind of lambda:

**Comment by gdr-at-ms** [comment]
I have a strong preference on not embarking on "ban goto" crusade.  I am approaching this on more from a more pragmatic view.

Regarding complex initialization: My view is if your initialization is complex, you're already doing it wrong.

**Comment by MikeGitb** [comment]
It's certainly not about a cursade, but the less exceptions there are to a rule/guideline the easier it is to  teach, follow and automatically check that rule. 

For me, using an IILE is a very pragmatic way to deal with those (rare) situations.

**Comment by gdr-at-ms** [comment]
@MikeGitb I don't disagree; however, I don't know how far to take that.  A rule without exception can be either toothless or too restrictive, or just too complex.  For example "don't write bugs", or "never use goto."  It is tricky and I am consciously not optimizing for the rules governing the rules themselves.  When I see a lambda that spans several lines, I want to say "please, write a named function."  I definitely don't want to encourage such lambdas because of optimization of "exception to rules".

**Comment by MikeGitb** [comment]
I don't quite understand why you are putting a completely ridiculous rule like "Don't write bugs" in the same sentence as "never use goto" .
The former you can't enforce and is pretty much unachievable. The latter can easily be checked and --in my experience -- achieved. 

That aside, I don't share your apparent aversion against multi-line lambdas, but I do understand (and accept) that people have different opinions on that matter and place their priorities differently.

A little off topic, but for what I really would like to have a syntactic short form would be one line lambdas. E.g. instead of

    [](const auto& p){ return p.field(); }

rather

    [] p -> p.field()

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, we agree that the simple code--even with the `goto`--is preferable. We can't expect to teach programmers lambdas to solve a problem as common as a nested loop exit. 

Thank you for your suggestion and the good discussion!
