### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by fkromer** [isocpp/CppCoreGuidelines#968]
Would it be possible to add a search functionality to the [CppCoreGuidelines GitHub.io](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines)? That would improve the usability of the website significantly.

**Comment by AndrewPardoe** [comment]
Hitting "ctrl-f" in Edge or Chrome brings up a search dialog. For example, searching "template" yields 350 results currently. And there's a clickable index on the left. Please reopen this issue if there's something else you were thinking of.
