### ISSUE TITLE
"Design for Testability" guidelines

### ISSUE THREAD

**Issue by fkromer** [isocpp/CppCoreGuidelines#969]
I tried to find some guidelines addressing "Design for Testability" (e.g. the various generic alternatives for Dependency Injection and C++ specific implementation variants of DI) but I did not find anything. Are there guidelines which address DFT?

(I know about the controversy about DFT in contrast to "design from a production code only point of view" but I think every developer should have the right to know how to design and implement DFT if it is crucial for her.)

**Comment by scraimer** [comment]
related: #849

**Comment by gdr-at-ms** [comment]
Look at #849.
