### ISSUE TITLE
I.10: incorrect error_code check in examples.

### ISSUE THREAD

**Issue by Talkless** [isocpp/CppCoreGuidelines#970]
[I.10](https://github.com/isocpp/CppCoreGuidelines/blob/69d2341c1e7043c64c35901823188a663c068eee/CppCoreGuidelines.md#Ri-except) example checks for zero:
```
if (error_code == 0) {
    // ... handle the error or exit ...
}
```
Though error_code of zero means (usually?) a success.

**Comment by cubbimew** [comment]
since it's demonstrating "tie(val, error_code) = do_something();", perhaps it would be more recognizable to use "tie(iterator, inserted) = s.insert(something)"

**Comment by Talkless** [comment]
@cubbimew I believe what you are suggesting is out of scope for this issue..?

What I mean is, that statement:
```
if (error_code == 0)
```
Should become:
```
if (error_code != 0)
```
Or maybe:
```
if (error_code)
```

**Comment by cubbimew** [comment]
Okay, #974 makes a good minimal fix.
