### ISSUE TITLE
gh-pages tweaks

### ISSUE THREAD

**Issue by AndrewPardoe** [isocpp/CppCoreGuidelines#973]
@tkruse, I'm making some cosmetic changes to the IO page for this repo. You can see what I've done so far at http://andrewpardoe.github.io/CppCoreGuidelines/CppCoreGuidelines.html

There are three more things I'd like to adjust:

1. I'd like the button text to be "Turn ON syntax highlighting"  | "Turn OFF syntax highlighting". I've been messing with the custom.css file trying to widen the button but have been failing badly.
2. On the main page, is there a way to increase the font or otherwise bold "Read the C++ Core Guidelines"?
3. On the main page, the CONTRIBUTING.md file doesn't load in the browser directly. You're doing a trick to render the README.md but I don't think I can repeat that where the CONTRIBUTING is mentioned. 

Any advice? Thank you!

**Comment by tkruse** [comment]
Re 1: It seems you have found a way to widen the button by now, at least it renders correctly in Firefox.

Re 2: In sidebar.html, you have the means to change the font options of the "Read the C++ Core Guidelines" link.
The orthodox way is to give the anchor tag an additional class like 'sidebar-strong':
```
<a class="sidebar-nav-item active sidebar-strong" href="CppCoreGuidelines.html">C++ Core Guidelines</a>
```
And then in custom.css, define the font attributes for that class, like:
```
.sidebar-strong {
    font-size: larger
}
```
See here for what you can change: https://www.w3schools.com/cssref/pr_font_font.asp
There are other more hackish way to achieve the same. 

Re 3: I am not sure I understand what you want to achieve. what you can do is to add this:
```
{% capture contribute %}{% include_relative CONTRIBUTING.md %}{% endcapture %}
    {{ contribute | markdownify }}
```
I believe the first line kind-of declares a variable 'contribute' with the file contents, and the second line uses this variable transformed into html. Some explanation here: https://jekyllrb.com/docs/includes/

**Comment by AndrewPardoe** [comment]
Thanks, Thibault. I'll try #2 and #3 later. 

As for the button width, it renders nicely with the phrase "Turn ON syntax" but I was actually trying to get the word "highlighting" in there as well. I can't figure out how to make it wide enough for the last word.

TBH, I was trying to get something that had text and a button on the same line. My ideal would look something like [this image](http://imgur.com/a/wyGED). But I quickly realized that I have no idea how to do this in HTML except for using tables, and the Internet advised against using tables. 

By the way, I've also updated my instructions.txt file to remind me to refresh the index periodically. I should just make a script to create the text from the CppCoreGuidelines.md, but at least with a reminder I won't forget.

**Comment by tkruse** [comment]
The button with is controlled in custom.css :
```
.tgl + .tgl-btn {
   width: 8em;
   ...
}
```
All the 'tgl' rules relate to some aspect of the toggle button.

Having just ON/OFF after some text is also possible, probably by putting
them into a parent 'div' tag with special styling. See
https://www.designcise.com/web/tutorial/how-to-force-html-elements-to-stay-on-the-same-line

**Comment by tkruse** [comment]
Also, while I like having a logo, consider people looking at this page from
their smartphone, in landscape orientation.

With the current design visiting the page would fill the entire phone
screen with half the logo.

The CSS rules allow special styling just for smaller screens, so you don't
have to worry about making compromises, but making sure phones render a
page nicely is considered important in this day and age.
By the way I also slightly before that in my last pr now having an ugly
white stripe right off the sidebar, I can refer that later

**Comment by AndrewPardoe** [comment]
@tkruse Thus the private preview page : ) I haven't tested on my phones yet.
