### ISSUE TITLE
Please reopen and answer the #962 about NL.16

### ISSUE THREAD

**Issue by travnick** [isocpp/CppCoreGuidelines#977]
Sorry about kind of non issue but inconsistency in NL.16 mentioned in #962 is not answered but closed (as you are able to see there is no clear conclusion there)

**Comment by galik** [comment]
I am pretty sure the conclusion was that your *first* example is the correct one:
```cpp
class X {
public:
    // types, constructors, assignments, destructor, functions, data
protected:
    // types, constructors, assignments, destructor, functions, data
private:
    // types, constructors, assignments, destructor, functions, data
};
`

**Comment by jwakely** [comment]
I've responded there, because your interpretation is backwards.
