### ISSUE TITLE
Issue with the link in guidelines.

### ISSUE THREAD

**Issue by jack17529** [isocpp/CppCoreGuidelines#978]
I found out a link which is not working here -
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#reason-102

named " F.24 " which should redirect to - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f24-use-a-spant-or-a-span_pt-to-designate-a-half-open-sequence

instead it's directing to - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-pass-ref-ref

which in the end does nothing.

**Comment by jwakely** [comment]
I don't think it's supposed to point to [F.24](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f24-use-a-spant-or-a-span_pt-to-designate-a-half-open-sequence), that has nothing to do with passing by `&&`

I think the correct link is F.18

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#reason-59 has the same problem, it links to F.24 and F.25 but I think those should be F.18 and F.19.

**Comment by jack17529** [comment]
@jwakely  I just started reading them today the move and copy ctor parts.

**Comment by jack17529** [comment]
Another link in the line " The swap implementation technique offers the strong guarantee. "

**Comment by jack17529** [comment]
Here https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-264
the link named - " make move operations noexcept "

**Comment by jack17529** [comment]
These links to important references don't work - " [C++CS] Item 51; [C++03] §15.2(3), §17.4.4.8(3), [Meyers96] §11 " here - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-373

**Comment by jwakely** [comment]
> These links to important references don't work - " [C++CS] Item 51; [C++03] §15.2(3), §17.4.4.8(3), [Meyers96] §11 " here - 

Fixed by 598e6f99b62ae5c0bf6552cd32d06828fac03e8d

**Comment by jwakely** [comment]
> the link named - " make move operations noexcept "

Fixed by 3a6466f09c4b8465581cac713871b2032bcabbff

**Comment by jwakely** [comment]
> Another link in the line " The swap implementation technique offers the strong guarantee. "

Addressed by #991

**Comment by jwakely** [comment]
The original issue of broken links to F.24 and F.25 is addressed by #992

**Comment by gdr-at-ms** [comment]
fixed by @jwakely
