### ISSUE TITLE
NL.16 has missleading sentences.

### ISSUE THREAD

**Issue by travnick** [isocpp/CppCoreGuidelines#980]
As mentioned in #977 by @galik and @jwakely it should be clearly stated in NL.16 that (in ideal situation) **in the first place** one should order class members by visibility **and then** by type of member.

Statement "**Private types and functions can be placed with private data.**" suggest an opposite situation that in **normal case** private types and functions **are not** placed with private data so there are multiple private blocks what suggest ordering in the first place by type of member and then by its visibility.
But this interpretation conflicts with "Avoid multiple blocks of declarations of one access (e.g., public) dispersed among blocks of declarations with different access (e.g. private)." so it renders whole NL.16 as not consistent.

**Comment by BjarneStroustrup** [comment]
Clarifying (I hope) text and example added to NL.16
