### ISSUE TITLE
Grammatical error in README.md

### ISSUE THREAD

**Issue by qalpaq** [isocpp/CppCoreGuidelines#984]
Typo in the first paragraph last sentence of the Getting Started section of README.md.
https://github.com/isocpp/CppCoreGuidelines/blob/master/README.md

The text reads: 
"Note that it manually integrated and can be slightly older than the version in the master branch."

Should read something like:
"Note that it is manually integrated and can be slightly older than the version in the master branch."

**Comment by lbrandy** [comment]
I would accept this pull request :)

**Comment by qalpaq** [comment]
Thanks lbrandy, if interested I'd like to suggest the rewording of several passages in the README.md. Should I continue to submit issues or is there another way that would be preferable?

**Comment by cubbimew** [comment]
For a small uncontroversial change a pull request without an issue is better for the editors - they have fewer buttons to click.

**Comment by qalpaq** [comment]
Ok, thanks.

**Comment by jwakely** [comment]
Right, there's no point submitting an issue _and_ a pull request, it just means more work to close the issue after merging the fix. Just create a pull request.
