### ISSUE TITLE
Minor syntax error

### ISSUE THREAD

**Issue by jack17529** [isocpp/CppCoreGuidelines#988]
Here  - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enforcement-100
 in the points , deleted should be written instead of "delete d".

**Comment by jwakely** [comment]
Feel free to send pull requests to fix things like this.

**Comment by AxelStrem** [comment]
I don't think there is a space - it's just a code markdown

**Comment by jwakely** [comment]
You're right, there's no space, it's just how the <code> markup looks.
