### ISSUE TITLE
Minor change I suppose.

### ISSUE THREAD

**Issue by jack17529** [isocpp/CppCoreGuidelines#989]
##Here - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-101

It is written after the code " copy operations " but should be " move operations " according to me.

**Comment by jwakely** [comment]
I think it's talking about the copy operations on the data members, i.e.

    elem{a.elem}, sz{a.sz}

and

    elem = a.elem; sz = a.sz;

**Comment by jack17529** [comment]
okay then it is fine.
