### ISSUE TITLE
GSL Expect() and Ensure() and the CppCoreGuidelines naming convention

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#993]
I would prefer if Expect() and Ensure() used in I.6, I.7 follow the CppCoreGuidelines naming convention.

**Comment by neilmacintosh** [comment]
@franzhollerer If you look at the issues @MikeGitb has referenced, you can see the reasoning for the existing naming convention approach. The fact that these calls happen to be macros is an unfortunate and (hopefully) temporary implementation detail. We would not want to reflect that state of affairs in their names, especially when they are such critical pieces of the approach taken in the Guidelines.

**Comment by franzhollerer** [comment]
Thanks @MikeGitb and @neilmacintosh for pointing me to the related issues.

I merely noticed that their naming neither follow the naming convention for macros, nor for functions, but start with an upper case which would indicate a type. Anyway, that's a negligible flaw.
