### ISSUE TITLE
F.4 typos

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#995]
I guess the spaces before the *dot* ending the sentence is not intended.

![f](https://user-images.githubusercontent.com/17589466/28492546-0ad93984-6f06-11e7-9463-783ffacf9f78.png)

**Comment by scraimer** [comment]
The space isn't actually there in the markdown of the article. It's a visual artifact of GitHub's rendering of a code-style word in a fixed-width font.

Looking at the CSS, it seems to be coming from the `::before` of elements with the class name `.markdown-body`, which adds `content: "\00a0"`. Google says that is a "NO-BREAK SPACE' (U+00A0)".

 I'm not sure why it was added. But this seems to be design choice made by GitHub. You could try rendering the markdown with a different renderer, and it'll probably go away.

**Comment by jwakely** [comment]
Yes, this is inserted by Github and not a problem with the sources.
