### ISSUE TITLE
Discourage unowned member variables

### ISSUE THREAD

**Issue by quicknir** [isocpp/CppCoreGuidelines#996]
It's possible that this is already present and I missed this. The idea here is pretty simple, if you design a class like this:

```
class Foo {
public:
  Foo(const Bar& x)  : m_x(&x) {}
  
  void baz(double y) {
    m_x->qux(m_blub, y);
  }
private:
  Bar const * m_x;
  int m_blub = 0;
};
```

It's extremely easy to have instances of Foo where the corresponding Bar has already died, leaving behind a dangling pointer. You can mitigate this slightly by making it so that Foo cannot be assigned, but it's still a huge hole that underlies many memory issues in C++.

In some cases, `Foo` has to conform to an existing interface, or there are performance concerns. But this is avoidable in the vast majority of cases, by e.g. changing `baz`'s interface so that a `Bar` reference has to be passed in. Even if conformance to an interface is necessary, maybe the interface can be reworked so that it is no longer necessary.

I've found in practice that people include non-owning pointers/references as member variables *very* casually, even when it is completely unnecessary. Justifying it by the fact that it is slightly less verbose (e.g. if `Bar` would have to be passed in repeatedly in different calls), or that it makes sense conceptually (it doesn't!).

**Comment by maikel** [comment]
This advice is too broad, in my opinion. `std::weak_ptr<Bar>` is not owning but safe to use.
There are already related warnings to naked pointers, for example

P.8/Enforcement (Don't leak any resources): 

> Look at pointers: Classify them into non-owners (the default) and owners. Where feasible, replace owners with standard-library resource handles (as in the example above). Alternatively, mark an owner as such using owner from the GSL.

**Comment by MikeGitb** [comment]
@quicknir: I think you lost me. Can you show an example, where the above class would be used and how you'd like the class be designed instead?

**Comment by quicknir** [comment]
@MikeGitb I'm not sure what the usage side would eliminate, as for how it should be designed instead:

```
class Foo {
public:
  Foo() = default;  
  void baz(double y, const Bar& x) {
    x.qux(m_blub, y);
  }
private:
  int m_blub = 0;
};
```

**Comment by quicknir** [comment]
@maikel Yes, weak_ptr is a good example, so maybe this specific piece of advice should be restricted a bit more. The combination of non-owning, with ignorance of destruction, is what makes it especially bad.

The existing warnings are about leaks, and not using raw pointers for ownership generally. This is about neither of those. The concern here is not a leak (`Bar` is owned elsewhere), it's dangling.

On a final note, weak_pointer and shared_ptr to mutable types also make poor member variables (though not as bad as a raw pointer), because it's hard to enforce any invariant on them. You can check the invariant in the constructor but since the person who constructed the class can easily keep a copy of the shared_ptr, they can mutate your invariant out from under you. This point is discussed more generally (in terms of not exposing member variables, and information hiding) but I don't think this specific point is made; it should be because it's an important one.

**Comment by MikeGitb** [comment]
I see where you are coming from, but just think of proxy objects like `std::string_view` or `gsl::span`. I don't think finding a good rule when non-owning members are OK and when not is really difficult or maybe even impossible.

**Comment by quicknir** [comment]
@MikeGitb I don't think it's about finding a black and white rule. It's just that it should be discouraged, the same way that `shared_ptr` is discouraged relative to `unique_ptr`. `string_view` and `span` are lightweight objects whose primary purpose is to serve as inputs and outputs for functions, similar to iterators. How often do you see it recommended that an iterator would be a member variable?

These objects also have the advantage that they are lightweight and referencing other objects is all they do. In some sense they are themselves semantically equivalent  to references/raw pointers in providing "views" of other objects. This is quite different from writing a more complex object that owns some things but doesn't own others.

**Comment by AndrewPardoe** [comment]
Per our discussion, this is known bad code that we have rules against already. It should be caught by static code analysis. Assigning to Neil, who should discuss the IPR technique with Bjarne and GDR.

**Comment by neilmacintosh** [comment]
Non-owning member variables are a very reasonable design choice. `gsl::span<T>` and `std::string_view` are both examples of useful classes that (correctly) have non-owning member variables.

**Comment by quicknir** [comment]
@neilmacintosh Maybe a better phrasing would be to avoid mixing owning and non-owning member variables. That is, a class should either have owning semantics, and own all its members, or it should be a reference-like type where all it does is provide views to other data.

It's reasonable for span and string_view because the only thing they do is reference other data. They have semantics equivalent essentially to a `T&` in themselves. And yes, there are other useful examples, like `std::lock_guard` whose only purpose in life is to lock a mutex and keep a reference to it so it can unlock it on destruction.

span and string_view are not preserving much in the way of data invariants (of course they have them, but they are relatively simple). They are normalized (i.e. compatible with multiple sources) ways of passing views of data around. lock_guard does preserve an invariant but it is RAII related only, and not data related.

These are just exceptions that prove the rule: most classes that are not PODs should be preserving invariants, and you can't really enforce much in the way of invariants when you have a reference to a class that other people have as well. Many people have made this point before: Sean Parent has also argued e.g. against shared_ptr to mutable types, because it "destroys your ability to locally reason about code".

If you don't think this should be a guideline, I'm curious whether you think that the code example I gave is fine, or whether you think it would be ruled as a bad idea under some other guideline. I think in practical, real C++ codebases, this issue with complicated classes have pointers/references to other classes, that should really be passed in as members, is a very real issue, and a core guideline preventing it would help a lot.

**Comment by jwakely** [comment]
> That is, a class should either have owning semantics, and own all its members, or it should be a reference-like type where all it does is provide views to other data.

`std::vector` is the counterexample to that. It has one owning pointer and two other non-owning ones.

**Comment by quicknir** [comment]
My phrasing still isn't very good, but `vector` in no way contradicts the sentiment here. All of vector's pointers point to data that the `vector` owns. The other two pointers point to regions owned by the first (or one past that, to get technical, but that's still part of the owned region in that particular context).

If you look at my `Foo` and `Bar` example above, it's pretty clear that it's a very different situation from `vector`. The problem occurs when a class has pointers to data it doesn't control. This is data that it can't enforce invariants on, and *in general* doesn't need to be part of the class. There are exceptions obviously, but this is still a very useful and much needed guideline.

I'm curious about examples from the standard library that really do mix owning and non-owning semantics. I don't think it will change my viewpoint as I don't claim this is a black and white rule but rather a guideline (like most other items in the, ah, "Core Guidelines"), but seeing an example and its design justification would still be interesting.

**Comment by hsutter** [comment]
@quicknir I understand your argument, and I agree that `vector` conceptually owns all of its elements. Nevertheless, the three pointers most implementations store are fundamentally different in character: only the first pointer is an owner (of the whole array); the other two are merely positions and could as easily be integer offsets in a valid implementation, which emphasizes that they are about observation (position) not ownership.

Also, there are other classes that own vs. observe different things. For example, in reference counting `std::shared_ptr`s own the object but `shared_ptr`s and `weak_ptr`s together own the control block. So every `weak_ptr` contains (at least conceptually, and directly in some implementations) two pointers to objects, one of which it owns and one of which it does not.

I don't think it makes sense to have a guideline about not mixing owning and non-owning. Lots of classes own some objects that are part of their state, while also having ways to access other objects that they need for information but that they do not own. For example, whether to hold a subobject by value or by owning pointer can be an implementation choice that doesn't affect semantics, whether or not there are other non-owning pointers in the object; if we had a rule against mixing owning and non-owning, then we'd be saying that it's wrong to hold a member by unique owning pointer rather than by value (which are operationally identical) if the class happens to also have a non-owning pointer, which doesn't make sense as those things are independent.

**Comment by quicknir** [comment]
@hsutter Okay, fair enough, I see your points, `weak_ptr` is a strong example. My original motivation in bringing up this point is to have something that would clearly state that my original `Foo` `Bar` example is bad code (would you agree?), which I very strongly feel it is, but maybe I have chosen a poor axis for the guideline.

The Core Guidelines talk quite a bit about the important of establishing invariants. Maybe there should be a specific guideline that says that for a class that is involved with establishing invariants, avoiding including members that do not meaningfully participate in the invariants? Maybe that more accurately captures my issue, rather than talking about ownership at all. In some sense this is loosely implied by the discussion on invariants and members which vary independently, but I think an explicit guideline would be helpful here. Code similar to what I give above could be used as an example.

**Comment by MikeGitb** [comment]
While I see the danger of dangling pointers, I don't find the invariant argument convincing here: 

Imho, the most common reason why a class has a pointer to something that is conceptually not a part of this class is, because it either serves as a proxy for that class (view classes, iterators, proxies) or because it needs to access information which that other object provides or pass data to it. The state of those objects isn't part of my own state and the only invariant I need to ensure is that those objects are still alive when I use them, which brings us back to dangling pointers.

Regarding your example above: The reason I asked for a usage example is that I find it difficult to assess a class api design without knowing the purpose of a class and the context in which it is used - so no, from a foo bar example I can not say which one is better.

**Comment by quicknir** [comment]
Well, a proxy could still be owning or non-owning, but let's please leave aside view classes and iterator and focus on the common case.

We're comparing a class having a reference to having it passed it in at a method. The reason for having things in a class in the first place is to enforce invariants, yet having a reference/pointer as a member can't even enforce that the object in question is actually alive. Whereas if you have a method that accepts a reference to that object, this is much less an of an issue, the contract of a function accepting a reference requires that the object be alive (and usually you have to actively work around it). So by making the reference a member, we've actually worsened our invariants.

If the object has a shared or weak pointer, yes, it can at least be keeping the object alive, or check if it's alive before using it, but that's it. If you have the user of the class pass in the object, you already get that guarantee that the object is alive (or you can take a pointer which the user can set to null if you want it to be optional). It's not buying you hardly anything.

The key point is that members added to a class should *add* to the invariants. Breaking even is not enough because then you can simply start adding unrelated data to your classes and end up with enormous classes (let's not pretend like this doesn't happen in a lot of real code).

@MikeGitb In sum I think that if you want to make something a member of a class, you should have a good reason; every member of a class should have a clear case made for it. And when adding members that can be mutated out from under you, that case is harder to make.

Near the beginning of the discussion @AndrewPardoe said that this is known bad code, so it seems this has been discussed and at least some people agree with the general point. Maybe you can help refocus this into a guideline?

I'll say having read the core guidelines on class design, I feel from first hand experienced, that classes that contain piles of references to other classes, and end up forming giant, entangled, action-at-a-distance webs of state, are one of the biggest problems in real life code, yet it's not clear to me that any of the core guidelines actually come out and say this is a bad idea.

**Comment by jwakely** [comment]
But coming up with a concrete rule that is actually useful is hard. You can't just dismiss cases that would break the rule by saying _"let's please leave aside view classes and iterator and focus on the common case"_. Those are valid cases.

The suggestions here are too vague to be actionable.
