### ISSUE TITLE
F.34, misleading comment

### ISSUE THREAD

**Issue by franzhollerer** [isocpp/CppCoreGuidelines#997]
There is the following example in F.34:

```cpp
class Handle {  // Very suspect
    Shape& s;    // use reference rather than pointer to prevent rebinding
                        // BAD: vague about ownership of *p
    // ...
public:
    Handle(Shape& ss) : s{ss} { /* ... */ }
    // ...
};
```
I think there is a copy & paste error within the comment from the previous example.

>                        // BAD: vague about ownership of *p

The class does not contain a pointer *p*.

**Comment by AndrewPardoe** [comment]
Note this is now C.34. 

And this does appear to be a cut and paste error from C.33. Could you please submit a PR to correct this?

**Comment by hsutter** [comment]
The root cause is that we have since been clearer that references are never owners (see GSL.view).

So we will fix this by rewriting C.34 to say "don't have owning references."

**Comment by hsutter** [comment]
Aha, and we have the rule already in R.4. So I'll just delete C.34 and connect GSL.view to refer to R.4.
